### ISSUE TITLE
API post 1.6

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#100]
Is the car_id in `/api/car/$car_id/logging/resume` Still a numerical value like 1 or is now the car name? Say my car name is Model 3.
Would it be 

`/api/car/Model_3/logging/resume`

Or does it stay

`/api/car/1/logging/resume`

Thanks!

**Comment by Simple-Complexity** [comment]
Should still be the same as far as I'm aware. The change that you see in Graphana should only be for convenience for those that have multiple vehicles. It is much easier distinguish cars by name than ID.

**Comment by adriankumpf** [comment]
That's right, @Simple-Complexity
