### ISSUE TITLE
change of authorization for contributors in this project

### ISSUE THREAD

**Issue by roadrash2108** [adriankumpf/teslamate#1008]
**What would you like to be added**:
Allow contributors to add labels to issues and assign issues to people

**Why is this needed**:
would bring more structure in the project.

**Comment by adriankumpf** [comment]
Where can this be set? According to the [GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users):

> Anyone with write permissions to a repository can assign issues and pull requests.

Write access means **full** write access, as far as I have understood.

**Comment by roadrash2108** [comment]
Ah, I found my mistake: For organizations there is a role "Triage" (https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization), but this isn't available for user-repositories, where the only difference is between owner and contributor (who will gain full write access).

I can fully understand to limit the full write access, so therefore assigning labels/issues will stay with you, @adriankumpf .
