### ISSUE TITLE
"Scheduled Charging" Displays "Invalid Date"

### ISSUE THREAD

**Issue by jmiverson** [adriankumpf/teslamate#101]
This isn't new for v1.6.  I don't know when exactly it started and it's quite possible it has been this way since the beginning, but the "Schedule charging" value on the Teslamate (port 4000) page always lists "Invalid Date".

![image](https://user-images.githubusercontent.com/22219533/63230161-b116dc80-c1ce-11e9-8200-aa182e3e2624.png)

Thanks for everything you've done! I'm loving it.

**Comment by bahree** [comment]
I don't even see that option - does that show up, only when plugged in?

**Comment by adriankumpf** [comment]
@jmiverson Just to make sure I understood you correctly: is scheduled charging is actually enabled? Does that happen across browsers?

**Comment by jmiverson** [comment]
Scheduled charging is enabled, yes.  It is set for 3:00am local time every day.  I have only been using Safari on my Apple devices, so I tried it in Chrome.  It seems to show the time correctly there.

![image](https://user-images.githubusercontent.com/22219533/63301423-14247400-c2a0-11e9-98a7-8bcf86e11f6b.png)

I wouldn't worry about it too much, just odd that Safari can't handle the date object.

**Comment by adriankumpf** [comment]
Gotcha! I can reproduce that with Safari. Let's see if there's an easy workaround.

**Comment by adriankumpf** [comment]
Found something. The next release will include the fix. Thanks for reporting it.

**Comment by adriankumpf** [comment]
> I don't even see that option - does that show up, only when plugged in?

@bahree sorry, I missed your comment. The time does only show up when plugged in and if scheduled charging is enabled.
