### ISSUE TITLE
Mouseovers on front page not showing text

### ISSUE THREAD

**Issue by mrwolf78** [adriankumpf/teslamate#1015]
Since version 1.20.0 the mouseover on the frontpage for th lock and update icon shows only a small black box, but no text. This is the case for at least Chrome, Firefox and Edge Chromium on Windows 10.

On Android 10 (Chrome) the mouseovers do work.

**Comment by rndpsn** [comment]
I've seen the same behaviour but only on Desktop browser when the browser window is wide and the location map (leaflet-container) is displayed on the left-hand side of the car's info ("div.cardcontent").  In this case the mouseover is shown above the (lock/update available) icon and outside the "div.cardcontent" -- thus shows no text.  If I resize the browser window to make it narrower, such that the location map is displayed on top of the car's info, the mouse-over displays fine, on the left of the (lock/update available) icon.

**Comment by dyxyl** [comment]
I think this has been fixed in the source code (see #975).

**Comment by mrwolf78** [comment]
It looks like it, indeed. I didn't find that issue, but I'll close this one
