### ISSUE TITLE
Grafana dashboards show function convert_km does not exist upon upgrade 

### ISSUE THREAD

**Issue by rtega** [adriankumpf/teslamate#1025]
Upon upgrading from 1.19.3 to version 1.20 I get the message on grafana "pq: function convert_km(double precision, unknown) does not exist" in a lot of dashboards.

I'm using raspbian with postgres 11.9 and grafana version 7.2.1.

Apparently something goes wrong with the function convert_km. When I run the following query in psql:

`select convert_km(sum(distance), 'km') from drives where car_id = 1;
`
I get
```
ERROR:  function convert_km(double precision, unknown) does not exist
LINE 1: select convert_km(sum(distance), 'km') from drives where car...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

```
Running the query in steps manually doesn't seem to pose a problem
```
select sum(distance) from drives where car_id=1;
     sum      
--------------
 14854.956456
(1 row)
select convert_km(14854.956456, 'km') ;
  convert_km  
--------------
 14854.956456
(1 row)

```

**Environment**

- TeslaMate version: 1.20
- Type of installation: Manual
- OS TeslaMate is installed on: Raspbian
- User OS & Browser: not relevant

**Comment by dyxyl** [comment]
It looks like you need to run `grafana/dashboards.sh restore` to upgrade the dashboards (see the Manual install section of https://docs.teslamate.org/docs/upgrading).

**Comment by rtega** [comment]
Indeed, something went wrong with the restore process. I'm sorry. Solved.
