### ISSUE TITLE
City aliases are not precise enough

### ISSUE THREAD

**Issue by nnoally** [adriankumpf/teslamate#1030]
City aliases are not precise enough since #489 is resolved.

When i drive to a small town / village, Teslamate seems to use the municipality as city alias.

Some exemples:
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=122005&class=boundary
is aliased as 
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1686640&class=boundary

https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=120585&class=boundary
is aliased as
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1693119&class=boundary

The #489 reporter was right: hamlet is not a good alias for city. But i think it would be better to remove it from city alias (as locality and croft). Perhaps it could be used as last resort for neighbourhood_aliases ?
But according to https://wiki.openstreetmap.org/wiki/Key:place, the city alias order seems to be in wrong order. I think village / town / city / municipality order would be more precise.

If this problem is fixed, is there a way to force Teslamate to update all addresses with the new algorithm ?

**Comment by shanbs** [comment]
I agree with @nnoally, current city display is not accurate, at least in France. Example:

Crozet (01170) is the correct city name in the **official address**, while it is identified to be Gex.

Crozet: https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=139262&class=boundary

Gex: https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1668429&class=boundary

Village should have be placed in front of city, at least in France it is this case. If it is not this case in other countries, maybe it should be treated differently according to the countries.

**Comment by shanbs** [comment]
@adriankumpf In fact I found out that in all the examples listed by @nnoally and me, the key issue is that "municipality" is higher than "village", any reason for this? Maybe we should just move "municipality" lower.
