### ISSUE TITLE
Enhancement - Statistics dashboard

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#1032]
**What would you like to be added**:
On the statistics dashboard, can a link be added to the "Period" rows that link to the Trip dashboard and carry the period value? E.g. if you are looking at October/2020, 10/1 to 10/31 would be the time range sent to the Trip dashboard.

**Why is this needed**:
Seeing the values in a table is one thing, but then visualizing the data and seeing it in the Trip dashboard would be another good view. 

**Additional context**:

**Comment by DrMichael** [comment]
Links to Trip, Drives, Charges, Charging Stats will be in the next version.
