### ISSUE TITLE
Accessing the database from another device on the same network

### ISSUE THREAD

**Issue by rileymd88** [adriankumpf/teslamate#1035]
Hi all,

I have been running teslamate on a local ubuntu server for some time now. I just used the standard docker install with docker-compose up -d. I now would like to access the postgresql db from another computer on the same network but not sure what I can do to achieve this. I have tried to following:

Opening up the postgresql port (5432) on the ubuntu server with `sudo ufw allow 5432/tcp`
Trying to connect using the machine IP address (I am able to reach the dashboards with this IP)
Trying to connect using the docker IP address, received using the following command `docker exec -it <container id or name> hostname -i`

My next guess would be to change the yml file to also include the postgresql db port, similar to how the other ports are being used, however not sure if this would be the correct way forward for this. Any ideas?

Thanks for your help

**Comment by DrMichael** [comment]
Add

```
    ports:
      - 5432:5432
```

to the database part in docker-coompose.yml and restart.

**Comment by rileymd88** [comment]
Hi @DrMichael,

Thanks for your help - I did updated my docker-compose.yml file then ran `docker-compose restart`, however I am still not able to access the database (using `telnet <IP_ADDRESS> 5432` from my windows machine to test)

I noticed when I run `docker container ls` and inspect the PORTS area that all the other entries look like this `0.0.0.0:3000->3000/tcp` and the teslamate database container looks like this `5432/tcp`. Any ideas?

**Comment by rileymd88** [comment]
I am guessing that `docker-compose` restart does not actually update the port mappings and that I most likely need to run a `docker-compose up -d` again to make the changes take effect. Will this remove my existing data?

**Comment by DrMichael** [comment]
No

**Comment by rileymd88** [comment]
Great I did this and now it seems to be working! Thank you 👍
