### ISSUE TITLE
Dates In Statistics in Epoch Format

### ISSUE THREAD

**Issue by gary-hammer** [adriankumpf/teslamate#1037]
**Describe the bug**

Dates are in epoch format in the Statistics dashboard.
date_from          Date_to
1590969600000 1593561600000

**Expected behavior**

Should be human readable date.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to Statistics dashboard.
2. See error

**Environment**

- TeslaMate version: 1.20.1
- Type of installation: Docker
- OS TeslaMate is installed on: Pop!OS 20.10
- User OS & Browser: Win10 Edge Dev
- Others:

**Comment by DrMichael** [comment]
Those fields are used for the links and should be hidden, but then the cannot used for the links due to a bug in Grafana. We are waiting to get that bug fixed.
