### ISSUE TITLE
Order in Statistics dashboard wrong

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#1040]
**question**

@adriankumpf did you hide "Starting at" in Statistics on purpose? The order is so a bit wierd:
![image](https://user-images.githubusercontent.com/8087682/97103740-b020eb00-16ae-11eb-9889-953556a11c9c.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/8087682/97103768-dd6d9900-16ae-11eb-9b29-fde899c3f0d7.png)

Apparently Grafana does not order on hidden fields?!?!

**Environment**
- TeslaMate version: 1.21.0-dev
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu 20.04
- User OS & Browser: Chrome
- Others: -

**Comment by DrMichael** [comment]
But it would be good to have "Starting at" visible anyway, for the case the timezone is changed. Then it is clear, when the period starts exactly.

**Comment by leewillis77** [comment]
I think this is actually caused by https://github.com/adriankumpf/teslamate/issues/1074

**Comment by DrMichael** [comment]
@adriankumpf could you enable "Starting at" again?

**Comment by DrMichael** [comment]
@adriankumpf And, the "AT TIME ZONE (select current_setting('TIMEZONE'))" are too much and must be removed.

Then setting PGTZ for the grafana container will produce the desired result.

**Comment by DrMichael** [comment]
Created PR https://github.com/adriankumpf/teslamate/pull/1254

**Comment by snicoll** [comment]
FTR my install is full UTC and the ordering is wrong for me as well. I'd expect the list to start with the current month indeed. Thanks for creating the PR @DrMichael!
