### ISSUE TITLE
[error] Mounting lv:phx-nu/mu23f failed while verifying session with: :invalid

### ISSUE THREAD

**Issue by nullgel** [adriankumpf/teslamate#105]
Everything appears to be working, but the Docker logs are spitting these errors out:

![image](https://user-images.githubusercontent.com/27741277/63352122-7c219b80-c32e-11e9-93cc-7940d56866c9.png)

Any ideas what this could be?

**Comment by adriankumpf** [comment]
There is probably a browser tab open somewhere that was opened before Teslamate was restarted.

A new session id is generated with each restart. When the client tries to reconnect with the previous session those warnings are emitted.
 
You can either set a fixed `SECRET_KEY_BASE` and `SIGNING_SALT` env variable OR just find and reload the tab :p

**Comment by nullgel** [comment]
Ah-ha! 🤦

I took the lazy (preferred) route and reloaded tabs. No more errors. Thanks!
