### ISSUE TITLE
Create Custom Alerts

### ISSUE THREAD

**Issue by cmchauvin** [adriankumpf/teslamate#1053]
**What would you like to be added**: Ability to setup alerts. For example, when the odometer hits a certain mileage - or x miles have been driven, alert me that it's time to rotate tires. When internal temperature hits a certain point, notify me.  

**Why is this needed**: Currently the Tesla app doesn't support any IFTTT type functions.

**Additional context**:

**Comment by pmboothby** [comment]
This is quite easy to do with Node-RED. If you're running Teslamate on Docker, you can just add a Node-red container and send the alerts to your email, etc. I've been thinking about writing a Guide for the Teslamate doco on how to set up Node-red with examples of alerts. If you're interested, perhaps I'll do it sooner than later. :)

**Comment by cmchauvin** [comment]
Would be much appreciated. I was successful setting up Node-RED but for the life of me I can't figure out MQTT (far from experienced on this one). I'm not using my own broker - when I navigate to my virtual host address and port 1883 nothing is returned. Within Node-RED the MQTT server is just always in a "connecting" status.
