### ISSUE TITLE
Ecto.MultipleResultsError: expected at most one result but got 3

### ISSUE THREAD

**Issue by scottismyname** [adriankumpf/teslamate#106]
I believe last week I updated to 1.5.3 and I didn't quite check after that, but it doesn't appear that new data was being retrieved since that update.  Today I tried looking at my stats for the last several days and noticed.  I tried updating to 1.6 but that didn't help.

I'm on Synology and here are the logs I see when I do (the same paragraph of logs seems to repeat every minute or so):

$ docker logs docker_teslamate_1

> Crash dump is being written to: erl_crash.dump...done
>10:07:33.196 [info] Already up
>10:07:55.785 [info] Running TeslaMateWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)
>10:07:55.787 [info] Access TeslaMateWeb.Endpoint at http://nas
>10:07:55.833 [info] Found Model 3 LR: 'Worth It'
>10:07:55.864 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an 
error: shutdown: failed to start child: TeslaMate.Vehicles
    ** (EXIT) shutdown: failed to start child: TeslaMate.Vehicles.Vehicle_1
        ** (EXIT) %Ecto.MultipleResultsError{message: "expected at most one result but got 3 in 
query:\n\nfrom s0 in TeslaMate.Log.State,\n  where: ^1 == s0.car_id and is_nil(s0.end_date)\n"}
>{"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles.Vehicle_1',#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.MultipleResultsError',message => <<\"expected at most one result but got 3 in query:\n\nfrom s0 in TeslaMate.Log.State,\n  where: ^1 == s0.car_id and is_nil(s0.end_date)\n\">>}}}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
>Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Ve
`

**Comment by adriankumpf** [comment]
The data in the `states` table seems to be corrupt. Do you still have  the previous logs? I can't figure out how that could've possibly happened.

To fix it, manually update the `states` table: remove all but the most recent entry where the `end_date` is NULL.

**Comment by scottismyname** [comment]
I do have logs for the db container if that helps at all?

> 2019-08-16 18:21:23.237 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
>2019-08-16 18:21:23.238 UTC [1] LOG:  listening on IPv6 address "::", port 5432
>2019-08-16 18:21:23.308 UTC [1] LOG:  listening on Unix socket >"/var/run/postgresql/.s.PGSQL.5432"
>2019-08-16 18:21:23.359 UTC [23] LOG:  database system was interrupted; last known up at 2019-08-16 18:13:59 UTC
>2019-08-16 18:21:23.527 UTC [23] LOG:  database system was not properly shut down; automatic recovery in progress
>2019-08-16 18:21:23.546 UTC [23] LOG:  redo starts at 0/5CB8610
>2019-08-16 18:21:23.546 UTC [23] LOG:  invalid record length at 0/5CB86F0: wanted 24, got 0
>2019-08-16 18:21:23.546 UTC [23] LOG:  redo done at 0/5CB86B8
>2019-08-16 18:21:23.860 UTC [1] LOG:  database system is ready to accept connections
>2019-08-16 18:21:26.829 UTC [30] LOG:  incomplete startup packet
>2019-08-18 01:24:27.730 UTC [27] LOG:  using stale statistics instead of current ones because stats collector is not responding
>2019-08-18 01:24:38.815 UTC [1904] LOG:  using stale statistics instead of current ones because stats collector is not responding
>2019-08-18 16:36:22.769 UTC [27] LOG:  using stale statistics instead of current ones because stats collector is not responding
>2019-08-18 16:36:33.883 UTC [2815] LOG:  using stale statistics instead of current ones because stats collector is not responding
>2019-08-20 16:36:00.904 UTC [5694] LOG:  incomplete startup packet
>2019-08-20 16:36:38.031 UTC [5703] LOG:  incomplete startup packet
>2019-08-20 16:37:10.239 UTC [5712] LOG:  incomplete startup packet
>2019-08-20 16:37:41.571 UTC [5721] LOG:  incomplete startup packet
>2019-08-20 16:38:15.838 UTC [5730] LOG:  incomplete startup packet

**Comment by scottismyname** [comment]
How would I go about manually updating the states table?

**Comment by adriankumpf** [comment]
I was just writing down how to get there. Yes, perfect. Just delete those two.

**Comment by scottismyname** [comment]
Awesome, just for anyone else who might see this in the future and needs to fix this, here is what I did (since I'm a docker/psql noob).

Enter the docker container for your database, and in a terminal:
1) Open the database:

> psql teslamate teslamate

2) List the tables in the database (just to be sure): (Note the leading \ is necessary)
 > \dt

3) List all of the rows in the states table (this could be very long):

> TABLE states;

4) Find out which entries you need to delete.  For my case, I had 3 entries in my states table that had a blank (null) end date.  There should only be 1 of them.  So I needed to delete the 2 of them.

> DELETE FROM states WHERE state.id=203 OR state.id=204;

5) Once this was done, I didn't even need to restart the container or anything, the web interface started working again.

**Comment by adriankumpf** [comment]
Okay, cool!

I'm still wondering how that could happen though.

**Comment by scottismyname** [comment]
It seems to coincide with when I was doing the upgrade to 1.5.3 though I don't have any definitive way to do that....my upgrade process is simply:

docker-compose pull && docker-compose up -d

No need to stop the container first, right? I wonder if the database was corrupted during the upgrade process?

No idea if it's worth adding a sanity check to make sure there's not more than 1 state entry with a blank end date, and if so, fixing it on the fly?

**Comment by adriankumpf** [comment]
Nope, stopping is not necessary. And it should always pick up the most recent state entry. 

Let's see if there are others affected.
