### ISSUE TITLE
[cold weather] charge port latch behaviour change -> MQTT: plugged_in = false

### ISSUE THREAD

**Issue by LelandSindt** [adriankumpf/teslamate#1060]
**Describe the bug**

It appears Tesla has changed the charge port latch behaviour [?in cold weather?]. Historically, after plugging in the charge cable the charge port latch would engage and stay engaged until the power cable button is pressed. Recently [in cold weather] the charge port latch will engage after the charge cable is plugged in, and then disengage. 

This is causing teslamate to set `plugged_in = false`

https://github.com/adriankumpf/teslamate/blob/master/lib/teslamate/vehicles/vehicle/summary.ex#L131

**Preferred [Expected] behavior**

Teslamate use `charging_state != Disconnected` instead of `charge_port_latch == Engaged` to determine if the car is plugged in.

**How to reproduce it (as minimally and precisely as possible)**:

1. Be in cold climate.
2. Plug in charge cable.
3. Observe MQTT: plugged_in = false

**Comment by LelandSindt** [comment]
Additional observation....
In the last hour `charge_port_cold_weather_mode` flipped from `true` to `false` and `charge_port_latch` changed to `Engaged`.

**Comment by bpankz** [comment]
I believe the threshold is 4C / 40F when the lock remains disengaged so it doesn't freeze

**Comment by LelandSindt** [comment]
closed by 5ed9131e1fb572f97fd4c097d894e92f63f2a3b2
