### ISSUE TITLE
SoC Data Discrepancy

### ISSUE THREAD

**Issue by nullgel** [adriankumpf/teslamate#107]
I'm trying to figure out this data discrepancy between the web interface and the Grafana interface. The web interface correctly shows 74% SoC while the Grafana board shows 78%.

Could this be a matter of bad database data? I don't mind clearing the data out completely to test that. Is there a simple way to do that, by the way?

![image](https://user-images.githubusercontent.com/27741277/63374643-3d084000-c358-11e9-950e-03a31b3a6b79.png)
![image](https://user-images.githubusercontent.com/27741277/63374669-4c878900-c358-11e9-8694-48b4a4995e2d.png)
![image](https://user-images.githubusercontent.com/27741277/63374759-7ccf2780-c358-11e9-8787-49d547b76ce3.png)

**Comment by adriankumpf** [comment]
No need to clear all data. That's a design decision. The web interface always shows the most up-to-date data whereas Grafana's purpose is reporting and visualizing historical data. That's why there is, by default, no real-time dashboard (similar the Tesla-apiscraper) built into Grafana.

**Comment by nullgel** [comment]
Oh, I see. I missed that distinction.

If only there were a way to combine the two methodologies... 🤔

**Comment by adriankumpf** [comment]
Haven't tested it, but it should be possible to create a Text / HTML Panel in Grafana that includes an iFrame with the web interface.

**Comment by nullgel** [comment]
I was considering something along those lines.
