### ISSUE TITLE
Running Teslamate and PiHole in Docker containers on a Raspberry Pi 4b/4gig

### ISSUE THREAD

**Issue by jdhorner** [adriankumpf/teslamate#1075]
Greetings all!

Not long ago, I purchased and installed a Raspberry Pi 4B/4gig on my local network, running Ubuntu 20.04.1 LTS headless. My goal was to set up docker and run a PiHole container. It works great!

That being said, I bought my first Tesla (Model 3 SR+ in blue) 12 days ago and while I'm impatiently waiting, I wanted to see what I could do nerd-wise to prepare for its arrival some time in December. I came across youtube videos that recommended things like ABRP, A Better Theater, TeslaFi, etc... and that led me to Teslamate.

I'm a software developer by trade, but not exactly one that's overly familiar with networking config and dockerized containers. I figured I'd give Teslamate a go anyway. Following the simple tutorial, I was able to get it running locally at home without any issues in its own docker container and all was great! The missing piece of the puzzle, though, was that it's obviously not accessible from outside of my local LAN. (Meaning, no pulling it up in the car while out and about)

That means I need to do three things: (1) set up two subdomains and point them to my home, (2) redirect those from my router to the proper containers on my Pi, and (3) put it all behind some sort of authentication, so random people can't stumble across it. I've done 1 and 2 in the past, and ended up at the official repo guide explaining how to do an advanced setup.

Here's where things get disappointing.

Following the guide works! I get prompted for the .htaccess auth, I get a real LetsEncript SSL cert, and it connects to Tesla and authorizes fine (even though I don't actually have a car on the account yet). Even grafana works like a charm without any data. 😅

However, if I walk everything back, and enable my PiHole container, which uses ports 53, 80, and 443 (I skip 67 since I'm not using it for DHCP), obviously the out-of-the-box solution above doesn't work, because the HTTP/HTTPS ports are already in use. I thought I could get around that by editing Traefik's ports like this:
```
ports: 
  - 50080:80   ##previously 80:808
  - 50443:443  ##previously 443:443
```
And then calling those ports explicitly externally. E.g. teslamate.mydomain.com:50443, then point that to my container. At first, I thought it was going to work, but then certain things started to break. First, it seems that whatever LetsEncrypt normally does by getting/generating certificates, it wasn't able to do any more. And even ignoring that, once I get to the login screen for Teslamate, submitting the login form fails (With the ever helpful error message) due to some obvious dns errors, too:
```
16:52:31.659 [error] Postgrex.Protocol (#PID<0.4017.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (database:5432): non-existing domain - :nxdomain

16:58:57.341 [warn] Update check failed: %Mint.TransportError{reason: :nxdomain}
```
I've searched about both of these, and have tried nearly every reasonable modifications I can think of to docker, pihole, resolv.conf, - dns: in the docker-compose.yml, and on and on. I feel as though there's something simple and fundamental I'm missing to make this work alongside pihole. Has anyone out there gotten that type of setup to work?

**Comment by DrJohnM61** [comment]
As a suggestion, you could install pivpn and vpn into your pi. You can then access things on your local network as if you were at home.

**Comment by jdhorner** [comment]
But that wouldn't really be possible from the console inside the M3, right?

**Comment by DrJohnM61** [comment]
Btw, if I recall correctly, with Traefik, you would need to run everything within the same container (docker-compose) or deploy images as services (docker-deploy). You have to expose the network ports so that Traefik can see the addresses and ports across stacks (on a single node or across a docker storm).

**Comment by DrJohnM61** [comment]
> But that wouldn't really be possible from the console inside the M3, right?

As, I did not consider that you would want to access from your (to be) teslas web browser. You could do this with VPN by connecting to your home machine from you phone using VPN and then creating a hotspot to allow access to your tesla web browser. A bit too complex.

You need to consider that HTTPS works on port 443. I don't think you can access HTTPS using something like HTTPS://mydomain.com:50443

I did a lot of painful Traefik work until hitting a realisation that it is not simple to get things working across multiple docker-compose files within or single machine or across a cluster. But here is something that I got working (it does not have Teslamate but should be simple to add). This uses DNY as the domain name server (those bits may need to be changed). You access the different applications using HTTPS://pihole.mydomainname.com (for example for pihole)

version: "3.5"
services:

# we deploy portainer and the agent in the portainer-agent-stack as it has to be deployed using:
#
# docker stack deploy --compose-file=portainer-agent-stack.yml portainer
#

  traefik:
    image: "traefik:v2.2"
    restart: unless-stopped
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker=true"
# turn off swam mode until we can get this working!
#      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
#  - "--certificatesresolvers.myresolver.acme.httpchallenge=true" does not seem to work
      - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"
      - "--certificatesResolvers.myresolver.acme.dnsChallenge.provider=dyn"
# use the staging environment for testing (to avoid the letsencrypt rate limit)
#      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=my.email@me.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - DYN_CUSTOMER_NAME="my DNY customer name"
      - DYN_PASSWORD="my DNY password"
      - DYN_USER_NAME="my DNY user name"
    networks:
      - $DEFAULT_NETWORK
      - inbound
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./.authenticate:/authenticate"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`traefik.$MY_DOMAIN`)"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth2"
      - "traefik.http.middlewares.auth2.basicauth.usersfile=/authenticate/.auth_file"
      - "traefik.http.routers.redirect-https.entrypoints=web"
      - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirect-https.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
## Router for the dashboard
## HTTPS connection to traefik.$MY_DOMAIN
## HTTPS certificate is used or generated
## security check that the user is allowed (using the middleware "auth" and then
## connects to the internal traefik api service
## note - generate the password using echo $(htpasswd -n drjohnm61) | sed -e s/\\$/\\$\\$/g
##
## HTTP REDIRECT router to HTTPS
## anything (unresolved) that comes in on HTTP routes to the middleware redirect-to-https that modifies
## the address to go to HTTPS


  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    env_file: ./services/nodered/nodered.env
    ports:
      - 1880:1880
    networks:
      - inbound
    volumes:
      - ./volumes/nodered/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.routers.nodered.rule=Host(`nodered.$MY_DOMAIN`)"
      - "traefik.http.routers.nodered.tls.certresolver=myresolver"
      - "traefik.http.routers.nodered.service=nodered"
      - "traefik.http.routers.nodered.middlewares=auth2"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      - "traefik.docker.network=inbound"


  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./backups/influxdb/db:/var/lib/influxdb/backup

  grafana:
    container_name: grafana
    image: grafana/grafana:6.3.6
    restart: unless-stopped
    user: "0"
    ports:
      - 3000:3000
    env_file:
      - ./services/grafana/grafana.env
    networks:
      - inbound
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`grafana.$MY_DOMAIN`)"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=inbound"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "1883"
    ports:
      - 1883:1883
      - 9002:9002
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf


  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8089:80/tcp"
      #- "443:443/tcp"
    env_file:
      - ./services/pihole/pihole.env
    networks:
      - inbound
    volumes:
      - ./volumes/pihole/etc-pihole/:/etc/pihole/
      - ./volumes/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.rule=Host(`pihole.$MY_DOMAIN`)"
      - "traefik.http.routers.pihole.tls.certresolver=myresolver"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.routers.pihole.middlewares=auth2"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=inbound"

  homebridge:
    container_name: homebridge
    image: oznu/homebridge:no-avahi-arm32v6
    restart: unless-stopped
    network_mode: host
    ports:
      - "8081:8081"
    env_file: ./services/homebridge/homebridge.env
    volumes:
      - ./volumes/homebridge:/homebridge
# cannot get homebridge running through traefik (unless setting up a macvlan network)



  whoami:
    image: "containous/whoami"
    container_name: "simple-service2"
    networks:
      - $DEFAULT_NETWORK
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.rule=Host(`whoami1.$MY_DOMAIN`)"
      - "traefik.http.routers.whoami1.entrypoints=websecure"
      - "traefik.http.routers.whoami1.tls.certresolver=myresolver"



networks:
    traefik-net:
      external: true
      name: $DEFAULT_NETWORK
    inbound:
      driver: overlay
      name: inbound

**Comment by DrMichael** [comment]
> First, it seems that whatever LetsEncrypt normally does by getting/generating certificates, it wasn't able to do any more.

Yes, LetsEncrypt needs access to the directory, where port 80 serves content from. And it does not with PiHole.

**Comment by jdhorner** [comment]
I think the headache and frustration of having it all in docker containers on one Pi has gotten too annoying. Hahaha! I'm going to leave it set up as local-only, and not worry about pulling up charts while I'm in the car. 💯 

Keep up the amazing work @adriankumpf
