### ISSUE TITLE
How to pull application logs

### ISSUE THREAD

**Issue by jmaddr** [adriankumpf/teslamate#1087]
I'm having an issue signing in where I get "Error: unknown" in red at the top at initial sign-in on a completely new docker install.  I looked around but could not find how to pull application logs (container logs don't give anything useful). I think it might be a DNS issue.  

Any help?  TIA.

**Comment by cwanja** [comment]
To get the TeslaMate Docker container logs, for example, use the following command: `docker-compose logs teslamate`.

**Comment by jmaddr** [comment]
Thanks @cwanja.  I did look at the container logs but they didn't result in any useful information.  I was hoping their might be a shell script I could execute through a docker exec command.  I'm getting the following error and I'm having trouble tracking it down.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/15809711/99529960-a8332e80-296e-11eb-9f7b-de94e676a83d.png">

I'll likely open another question on this since my title is misleading trying to track it here.

**Comment by emilbayes** [comment]
Hey, just had a similar issue. You know it's a DNS issue (out to the world) if you see `:nxdomain` from the `teslamate` container, or if you see `nc ...` when running `docker-container top` (DNS between containers)
