### ISSUE TITLE
GenStateMachine receive update event with error end_date timestamp cause server to be terminated

### ISSUE THREAD

**Issue by wty21cn** [adriankumpf/teslamate#1088]
Sometimes when I wake up My tesla model 3 from asleep,  the teslamate will crash, and the log says GenStateMachine receive update event with error end_date which violate the "end date must be after start date" constraint and cause server to be terminated. 

The time zone setting of teslamate is Asia/Shanghai

**Expected behavior**

the car state change from asleep to online

**How to reproduce it (as minimally and precisely as possible)**:

make tesla from online to asleep and wake it up

**Relevant entries from the logs**

22:54:42.471 car_id=1 [info] Start / :online
22:54:42.477 [error] GenStateMachine :"1" terminating
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2020-11-19 06:45:52.538000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
    (teslamate 1.20.1) lib/teslamate/vehicles/vehicle.ex:682: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
    (ecto_sql 3.5.0) lib/ecto/adapters/sql.ex:959: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.2.2) lib/db_connection.ex:1427: DBConnection.run_transaction/4
    (teslamate 1.20.1) lib/teslamate/vehicles/vehicle.ex:677: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib 3.12.1) gen_statem.erl:1120: :gen_statem.loop_state_callback/11
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Screenshots**

then current table states of postgresql is below,  the timestamps in schreeshot are shown as in +08:00 timezone.
![image](https://user-images.githubusercontent.com/3928233/99632114-a6a15d80-2a77-11eb-839e-42a40c35b080.png)

**Data**

**Environment**

- TeslaMate version: 1.20.1
- Type of installation: Docker
- OS TeslaMate is installed on:
- User OS & Browser: Chrome on Mac
- Others:

**Comment by wty21cn** [comment]
I've done some further test.
I notice that when I do a fresh boot of teslamate when my tesla is asleep with no data in postgresql, the start_date column of states table is inserted with timestamp according to my TZ setting, then I wake up tesla, the error instantly accurs with wrong timestamp of end_date colume which is in UTC .

**Comment by DarkRider1768** [comment]
Wondering if we can reopen this, it's happening again.

> 2025-03-17 17:03:43.728 car_id=1 [info] Start / :offline
2025-03-17 17:03:43.729 [error] GenStateMachine :"1" terminating
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2025-03-18 00:03:43.728808Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false, ...>}
    (teslamate 1.32.0) lib/teslamate/vehicles/vehicle.ex:728: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib 5.2.3.1) gen_statem.erl:1397: :gen_statem.loop_state_callback/11
    (stdlib 5.2.3.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
2025-03-17 17:03:43.733 [notice] Application teslamate exited: shutdown
Kernel pid terminated (application_controller) ("{application_terminated,teslamate,shutdown}")
