### ISSUE TITLE
What does "Health Check Failed" mean?

### ISSUE THREAD

**Issue by shadow7412** [adriankumpf/teslamate#1103]
![image](https://user-images.githubusercontent.com/286341/100570650-56eb4d80-3325-11eb-888c-db10073b7bc7.png)

I can't see anything in the car itself implying something is wrong, and there's nothing coming up on the Tesla app. I don't see anything about this warning in the teslamate docs.

What does it mean? How can I find out what it thinks is wrong with my car?

**Comment by sfarley85** [comment]
According to https://github.com/adriankumpf/teslamate/issues/613 it sounds like the health check indicates the app is having trouble connecting to Tesla's servers. I'm seeing this as well as of today, but the app appears to be updating with current data so not sure where it's failing.
