### ISSUE TITLE
Drive Details stats not updating when time frame changed

### ISSUE THREAD

**Issue by 3rdStng** [adriankumpf/teslamate#1114]
When I click on a drive from the Drives dashboard, I see the data as expected. Graphs, Maps, Stats (Distance, Duration, Energy used, etc.) However when I change the time frame from the drive time frame to something else, Last 2 days, Last 7 days. The stats in the top right corner of the page do not update. These stats remain the same. The rest of the data on this dashboard does update accordingly though.

![2020-12-09_111233](https://user-images.githubusercontent.com/24888063/101676207-b7f2df80-3a0f-11eb-862d-e2e2fccfe50b.jpg)

**Comment by DrMichael** [comment]
Dupplicate of #1159

**Comment by DrMichael** [comment]
@3rdStng can this be closed then?

**Comment by 3rdStng** [comment]
Yes it can. Sorry, I thought it was when the dupe was closed.
