### ISSUE TITLE
Model X type missmatch

### ISSUE THREAD

**Issue by virtualm2000** [adriankumpf/teslamate#112]
My car is identified as P90D ( I wish! :) ) instead of 90D.
The code for correct option codes is there:
defp get_efficiency("MX", "BTX4", true, _), do: {"X 90D", 0.208},

but the log says:

17:16:03.548 [info] Found Model X P90D:

My option codes:

"option_codes":"REEU,AD15,AF02,AH01,APF1,APH2,APPB,AU01,BC0B,BP00,BR00,BS00,**BTX4**,CC03,CDM0,CF01,CH04,COGB,PMBL,CW02,DRRH,DSH7,DV4W,FG02,FR02,GLTL,HP00,IDCF,IX01,LP01,LT3W,ME01,MI00,OSSW,PA00,PF00,PI01,PK00,PS00,QLEW,RFPX,S06W,SC01,SP01,SR01,ST02,SU01,TIM7,TM00,TP03,TR01,TRA1,TW00,UM01,UTAB,WT20,X001,X003,X007,X011,X014,X021,X025,X026,X028,X031,X037,X039,X042,X044,YFCC,MDLX"

Thanks!

**Comment by adriankumpf** [comment]
Oh, good catch! It will be fixed soon.

**Comment by olexs** [comment]
Maybe relevant: my 3 Performance is identified as 3 LR. I can dig out the full option code list if needed, though I see you're fixing Performance identification across the board anyway :)

**Comment by virtualm2000** [comment]
git pull https://github.com/adriankumpf/teslamate.git master
From https://github.com/adriankumpf/teslamate
 * branch            master     -> FETCH_HEAD
Updating 1676a89..b4bd1f2
Fast-forward
 README.md                                |  5 +++++
 lib/teslamate/vehicles.ex                |  3 ++-
 lib/teslamate/vehicles/identification.ex | 60 +++++++++++++++++++++++++++++++++++-------------------------
 3 files changed, 42 insertions(+), 26 deletions(-)

It works:

22:53:50.468 [info] Found Model X 90D:

Thanks!

Best regards,
Mihai

**Comment by adriankumpf** [comment]
Oh, you're quick. It's not even released :) Thanks for testing!
