### ISSUE TITLE
Drives Columns - Meaning

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#114]
![drives](https://user-images.githubusercontent.com/19696424/63657425-ac19d600-c756-11e9-9ad8-92a04c0be233.png)

Most of the column meanings I understand. Does Ø = Average?

What do these mean?
-  TR Loss
- Ø Speed
- Ø Consumption
- Consumed (would I use this value to calculate the consumed kWh of say 7.7 kWh and multiply that by my utility rate ($0.15663/kWh) to find the cost of how much going on that trip would cost me to charge at home)

Even on a larger screen the columns get mushed together. Is there a better way to format/display this?

Thanks!

**Comment by adriankumpf** [comment]
TR means Typical Range. It is calculated as the difference of the reported "ideal range" at the start and end of a trip.

Ø is used as a symbol for the average. Apparently it's particularly known in German-speaking countries. I initially thought it's more common :D

Yep, "Consumed" can be used to calculate the costs of a trip. The value is not directly reported by the car and therefore needs to be derived from other measurements. It should be fairly accurate, though.
