### ISSUE TITLE
Add current location to the "Overview" dashboard (Grafana)

### ISSUE THREAD

**Issue by fatbasstard** [adriankumpf/teslamate#1148]
I think it would make sense (well, I would like it) to add the current location of the car to the "Overview" dashboard.

Not sure if this a value that is present somewhere, but else it could be based on the end position of the last drive.

**Comment by fatbasstard** [comment]
Got an example: 

![image](https://user-images.githubusercontent.com/35613489/103285432-6f12c300-49de-11eb-9a4f-61c2b184d290.png)


If people think this is "usefull" I can create PR

**Comment by DrMichael** [comment]
Looks great...

While you're at it...

Could we change the interval for the temperature from 10m to perhaps 4h? That would still make sense and otherwise it is almost always "No data".
