### ISSUE TITLE
Grafana - drive details "tiles" do not update when manually setting time range

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#1159]
**Describe the bug**

When viewing the drive details dashboard and adjusting the time range manually, none of the tiles update to match the new duration. First noticed duration and when validating for this bug, discovered none of them update.

**Expected behavior**

Expect all the tiles to adjust to the new data in the time range provided. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Open a drive to get to the drive details
2. Make note of the values in the tiles above the map
3. Adjust the time range manually to include an additional drive
4. Note that none of the tiles update.

**Relevant entries from the logs**

```
Grafana - N/A
```

**Screenshots**

_Note the difference in the time range of the upper corner_
![Screen Shot 2020-12-30 at 8 19 20 PM](https://user-images.githubusercontent.com/54645561/103390900-69030c00-4adc-11eb-8aa4-887a81a2b1d0.png)
![Screen Shot 2020-12-30 at 8 19 36 PM](https://user-images.githubusercontent.com/54645561/103390899-686a7580-4adc-11eb-8ff4-b02dfe7f78b6.png)

**Data**

**Environment**

- TeslaMate version: 1.20.1
- Type of installation: docker compose
- OS TeslaMate is installed on: Raspbian
- User OS & Browser: macOS Big Sur, Safari
- Others: N/A

**Comment by DrMichael** [comment]
That dashboard is designed to work with exactly one drive, identified by the drive_id handed over in the URL.

@adriankumpf Perhaps we should hide the time picker?

**Comment by cwanja** [comment]
> That dashboard is designed to work with exactly one drive, identified by the drive_id handed over in the URL.
> 
> @adriankumpf Perhaps we should hide the time picker?

Thanks for the response! Did not know it was driven by the drive_id. I would not, personally, hide it. I am about to do another long drive and was doing some analysis on a previous drive. It was nice to combine multiple drives into a single dashboard. Can a disclaimer be added to the dashboard once the timeframes has been modified?

**Comment by adriankumpf** [comment]
To combine multiple drives into one dashboard the "Trip" dashboard  might be a better choice.

I like the idea of hiding the time picker. It would then only be more difficult to change the period if you have previously zoomed into the graph.

**Comment by DrMichael** [comment]
Trip dashboard is gorgeous... I also had that thought.

**Comment by cwanja** [comment]
Forgot about the trip dashboard. Will give that a try to review my drives yesterday! Thanks to both of you! 😊

Sent from my iPhone
Chris Wanja
chris.wanja@mac.com
713.444.6999

**Comment by DrMichael** [comment]
@cwanja can be closed?

**Comment by cwanja** [comment]
> @cwanja can be closed?

Yes! Closed in this comment. Sorry.
