### ISSUE TITLE
Efficiency Numbers Anomaly

### ISSUE THREAD

**Issue by virtualm2000** [adriankumpf/teslamate#117]
After few days of running TeslaMate I'm starting to get the efficiency data. However, they are too good to be true. 
For example a round trip I did yesterday. The difference can't be that high.
![return trip](https://user-images.githubusercontent.com/24257689/63671362-3dc92800-c7d7-11e9-8f5b-35c5e22eac59.png)

Also the Efficiency dash is looking like this:
![efficiency](https://user-images.githubusercontent.com/24257689/63671429-5b968d00-c7d7-11e9-85e7-62a5235dc0d7.png)

Thanks!

**Comment by virtualm2000** [comment]
Ok, I see the TR Loss is only 5.4 mi  (180.57-175.16 as per Grafana) miles on the first leg of the trip. 
The terrain doesn't have high elevation difference to explain the  5.4 mi only.

**Comment by adriankumpf** [comment]
Oops, I messed up the efficiency calculation in the Efficiency dashboard. The efficiency value is incorrectly multiplied by 1.60934.

Regarding the first screenshot: technically, the efficiency is correct. However, the values can only be as good as what is reported by the car. I noticed in the past that sometimes the reported (ideal) range increases slightly at the beginning of a trip, for example.

**Comment by virtualm2000** [comment]
Digging a bit further in Drive details I have noticed that SOC % difference consumed is actually different in both trips. 3% vs 5%. So pre-cooling the car had more impact on range in the first leg than coming back. Interesting data.

Thank you for your hard work!

Best regards,
Mihai

**Comment by adriankumpf** [comment]
Ah, that makes sense. Interesting!

I just published a new Grafana image which includes the bugfix.

**Comment by virtualm2000** [comment]
Looks good. 

![Screenshot 2019-08-26 at 12 15 30](https://user-images.githubusercontent.com/24257689/63687000-459ac380-c7fb-11e9-9234-6a36dab2946d.png)


Thank you!

**Comment by adriankumpf** [comment]
Nice 👍

**Comment by vkarthikbalaji** [comment]
> Digging a bit further in Drive details I have noticed that SOC % difference consumed is actually different in both trips. 3% vs 5%. So pre-cooling the car had more impact on range in the first leg than coming back. Interesting data.
> 
> Thank you for your hard work!
> 
> Best regards,
> Mihai

In addition to precooling, I see your average speed and max. power are higher, which implies you drove a bit more enthusiastically on the 'to' drive than on the 'fro' drive..That also eats up your energy..
