### ISSUE TITLE
Provide docker-compose.yml and outsorce user settings to seperate file

### ISSUE THREAD

**Issue by ghostreader86** [adriankumpf/teslamate#119]
Idea is to provide a docker-compose.yml within this repository and outsource the needed userdata like `DATABASE_PASS` to a file, for example environemt which stays local.
This would make prevent errors during yml creation and reduce variance. In addition the the update process would be more elegant.

**Comment by adriankumpf** [comment]
Feel free to do it like that :) 

The `docker-compose.yml` is only intended as an example. Since cloning this repo is not mandatory to run TeslaMate (with docker), I don't see the benefit of adding example file(s) right now.

**Comment by ghostreader86** [comment]
Ah understood, beaucse it is in [hub.docker.com](hub.docker.com). I quit new to docker.
