### ISSUE TITLE
After upgrading Teslamate is waiting for postgres to start (which is already running)

### ISSUE THREAD

**Issue by ronnyandre** [adriankumpf/teslamate#1202]
**Describe the bug**

After upgrading Teslamate to v1.21.1, as well as upgrading PostgreSQL to major version 13, Teslamate won't start, saying it is waiting for `postgres`.

**Expected behavior**

PostgreSQL is running (available through SQL app and other apps), but Teslamate is still waiting for connection. Expect Teslamate to connect to database and run properly.

**Relevant entries from the logs**

```
teslamate       | waiting for postgres at postgres:5432 (2sec)
teslamate       | waiting for postgres at postgres:5432 (4sec)
teslamate       | waiting for postgres at postgres:5432 (8sec)
teslamate       | waiting for postgres at postgres:5432 (16sec)
teslamate       | waiting for postgres at postgres:5432 (32sec)
teslamate       | waiting for postgres at postgres:5432 (64sec)
teslamate       | waiting for postgres at postgres:5432 (128sec)
teslamate       | waiting for postgres at postgres:5432 (256sec)
teslamate       | waiting for postgres at postgres:5432 (512sec)
```

**Environment**

- TeslaMate version: 1.21.1
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian GNU/Linux 10 (buster)
- User OS & Browser: macOS Catalina 10.15.7 & Google Chrome 87.0.4280.141

**Comment by DrMichael** [comment]
Did you follow https://docs.teslamate.org/docs/maintenance/upgrading_postgres ?

What does the database log say?

**Comment by ronnyandre** [comment]
Yes, although I have installed Teslamate as a part of IOTstack software, so I have a custom database volume.

**Comment by DrMichael** [comment]
I'd say, POSTGRESS_USER, POSTGRES_PASSWORD and POSTGRES_DB should all match the corresponding in teslamate's DATABASE_????. Here "teslamate".

**Comment by ronnyandre** [comment]
Not sure if I completely follow. Should I change the environment settings for Postgres? I have multiple databases and users in the same database.

**Comment by DrMichael** [comment]
Yes, you need to change the env settings for Postgres. You surely want a separate user und separate database for teslamate...

Not sure about the networks part in the postgres service definition.

**Comment by ronnyandre** [comment]
I understand that part, but these settings have been unchanged since I installed Teslamate last August, and before upgrading from PostgreSQL 12. Not sure why this suddenly is an issue now.

I thought the database settings in the Postgres container is for the database container itself. I have a separate database and user/pass for teslamate (and any other third party containers using the same database service).

So the environment settings for Teslamate should be correct according to the setup.

**Comment by ronnyandre** [comment]
I tested setting all Postgres environment variables according to your feedback and documentation. This didn't change anything. Still same issue. Seems like the Teslamate doesn't find the Postgres database somehow. Which is strange, because every other container uses it and it works.

**Comment by DrMichael** [comment]
(not too sure about the env vars anymore...:-)

Could it be caused by

    networks:
    - iotstack_nw
?

**Comment by ronnyandre** [comment]
@DrMichael You are absolutely correct! Seems like either there is a change in IOTstack or Teslamate that requires me to specify a network for the container. (Also strange because I have other containers running that connects to the database container without defining a network.)

Thank you for all your help!
