### ISSUE TITLE
PostgreSQL's TimeZone setting impacts temperature readings in Overview dashboard

### ISSUE THREAD

**Issue by jmalcaide** [adriankumpf/teslamate#1210]
**Describe the bug**

If PostgreSQL's `TimeZone` parameter is set to other timezone than `Etc/UTC`, the temperature panels in the Overview Dashboard show no data or incorrect data, even when temperature readings has been updated in the last 10 minutes.

**Expected behavior**

Temperature panels in Overview dashboard should show correct data whenever temperature readings has been registered in the `positions` table in the last 10 minutes.

**How to reproduce it (as minimally and precisely as possible)**:

Set PostgreSQL's `TimeZone` to `Europe/Madrid`. (This parameter can be edited in `postgresql.conf`; then, restart both PostgreSQL and TeslaMate.) Go to the Overview dashboard about 15 minutes after beginning to charge the vehicle (temperatures are updated every 5 minutes while charching). Temperatures panels will show "No Data".

**Relevant entries from the logs**

N/A

**Screenshots**

Not necessary.

**Data**

This is what happens when `TimeZone` is set to `Europe/Madrid` (currently CET = UTC+01):

```
teslamate=# select NOW();
              now              
-------------------------------
 2021-01-15 01:21:20.181959+01
(1 row)

teslamate=# show time zone;
   TimeZone    
---------------
 Europe/Madrid
(1 row)
```

Note that `NOW()` always returns the current time as a timestamp _with timezone_ (`+01` in this case).

```
teslamate=# select date,inside_temp from positions where inside_temp is not null order by date desc limit 1;
          date           | inside_temp 
-------------------------+-------------
 2021-01-15 00:19:51.798 |        11.9
(1 row)
```

Note that the UTC timestamps stored in the `date` column are of type timestamp _without timezone_, so they are interpreted relative to PostgreSQL's `TimeZone` parameter. In this example, that temperature reading was actually done at 00:19:51.798+00 (equivalent to 01:19:51.798+01). But that timestamp, not carrying its timezone, is interpreted relative to the PostgreSQL's `TimeZone` setting, as 00:19:51.798+01, one hour early.

And this is the consequence:

```
teslamate=# select date,inside_temp from positions where inside_temp is not null and date >= (NOW() - interval '10m') order by date desc limit 1;
 date | inside_temp 
------+-------------
(0 rows)
```

This query is a simplified version of the query used by the temperature panels in the Overview dashboard. As it can be seen, no temperatures are retrieved. The key is the comparison expression `date >= (NOW() - interval '10m')`. The left side of the inequality (`date`) has type timestamp _without_ timezone, so that, while intended to be UTC (+00), it is actually interpreted as CET (+01). At the right side, the expression is of type timestamp _with timezone_, so its interpretation does not depend on the `TimeZone` setting.

Let's suppose that `NOW()` is returning `2021-01-15 01:23:30.1163+01`. Then, that expression is actually comparing

`2021-01-15 00:19:51.798+01  >=  2021-01-15 01:13:30.1163+01`

which results in False. So, no temperature readings meet the criteria of the query.

My PostgreSQL server is using the timezone `Europe/Madrid` because `initdb` chose the operating system's timezone as the `TimeZone` setting in `postgresql.conf`. Other people may be using with TeslaMate with a PostgreSQL server running on another system, with its `TimeZone` parameter set to any timezone different from UTC. Therefore, _TeslaMate (and the dashboards) should not depend on PostgreSQL's `TimeZone` is being set to UTC_.

A partial solution to this issue could be forcing the same time timestamp type (either with timezone o without timezone) in both sides of the comparison expression of the query:

`date AT TIME ZONE 'Etc/UTC' >= (NOW() - interval '10m')` (both sides are timestamps with timezone)
or
`date >= (NOW() - interval '10m') AT TIME ZONE 'Etc/UTC'` (both sides are timestamps without timezone, in UTC)

Another possible alternative: set the teslamate database timezone to `Etc/UTC`:

`ALTER DATABASE teslamate SET TIME ZONE TO 'Etc/UTC'`

That could be done at the time of creation of the teslamate database (for new installations), or a posteriori, stopping TeslaMate, executing that command, and restarting.

Anyway, I think that the best solution might be changing the type of the `date` column of `positions` to timestamp with timezone, avoiding in this way any ambiguity and dependencies on the PostgreSQL server's `TimeZone` parameter.

**Environment**

- TeslaMate version: 1.21.1
- Type of installation: Manual
- OS TeslaMate is installed on: FreeBSD 11.4 jail running on FreeNAS-11.3-U5.
- User OS & Browser: macOS 11.1, iOS 14, …
- Others: PostgreSQL 12.4, Grafana 7.3.4 running inside the same jail.

**Comment by DrMichael** [comment]
Good analysis... Timezones are a nightmare with Grafana. :-)

> `date AT TIME ZONE 'Etc/UTC' >= (NOW() - interval '10m')` (both sides are timestamps with timezone)
> or
> `date >= (NOW() - interval '10m') AT TIME ZONE 'Etc/UTC'` (both sides are timestamps without timezone, in UTC)
I like the first one.

> A possible alternative: set the teslamate database timezone to `Etc/UTC`:
> 
> `ALTER DATABASE teslamate SET TIME ZONE TO 'Etc/UTC'`
> 
> That could be done at the time of creation of the teslamate database (for new installations), or a posteriori, stopping TeslaMate, executing that command, and restarting.
There are many possibilities. You never know, what implications timezone changes to the database have for other dashboards...

> Perhaps, a more general solution might be changing the type of the `date` column of `positions` to timestamp with timezone, avoiding in this way any ambiguity and dependencies on the `TimeZone` parameter.
The other dashboards assume, that all dates in the database are in Etc/UTC. So, rather not do that.

**Comment by jmalcaide** [comment]
I just edited my description of the issue in order to clarify the problem. I rushed it last night and it was a little confusing.

My proposal of changing the type of the `date` column to timestamp with timezone should'n affect to current assumptions by the dashboards (I think), because the timezone would continue to be 'Etc/UTC', but explicitly declared. In fact, I think that that could prevent any timezone issues.

**Comment by jmalcaide** [comment]
The second solution I propose (ALTER DATABASE teslamate SET TIME ZONE TO 'Etc/UTC') would make the TeslaMate database use the 'Etc/UTC' timezone in the same way is doing now when the PostgreSQL's server `TimeZone` is set to `Etc/UTC`, so everything should continue working as now. The advantage of this solution is that it does not change anything in the code of TeslaMate or the dashboards, and it permits hosting the TeslaMate database in the same PostgreSQL server which is already hosting other databases, whatever its `TimeZone` is.

**Comment by DrMichael** [comment]
I am getting confused...

The default timezone in postgresql.conf in the database container is Etc/UTC. Why would you want to set it to Europe/Madrid?

If you want to act Grafana as postgresql client in Europe/Madrid, you should set PGTZ for the grafana container.

So, I am still with the solution to compare times with identical timezone properties.

**Comment by jmalcaide** [comment]
I am not using Docker (see my environment at the end of my report).

In my case, I installed the PostgreSQL 12 FreeBSD port. Initdb took the system timezone as the `TimeZone` setting in postgresql.conf.

There are more people running TeslaMate even in separate PostgreSQL instances, each one can configured i a different timezone. TeslaMate should not make assumptions about that.

**Comment by DrMichael** [comment]
It probably does not.

Anyway, when comparing times, it should be done with the same timezone, of course. So, the correct solution is one of:

`date AT TIME ZONE 'Etc/UTC' >= (NOW() - interval '10m') (both sides are timestamps with timezone)`
or
`date >= (NOW() - interval '10m') AT TIME ZONE 'Etc/UTC' (both sides are timestamps without timezone, in UTC)`
as proposed by you. All should be fine then.

**Comment by jmalcaide** [comment]
I think that TeslaMate does assume implicitly that PostgreSQL's `TimeZone` is set to `Etc/UTC` in the moment it stores all dates in UTC with type "timestamp _without_ timezone". Since all those dates do not carry timezone information, all accesses to them by any client (in this case, Grafana) will interpret them as pertaining to the timezone defined by the `TimeZone` parameter. If `TimeZone` is set to `Etc/UTC`everything works fine, but problems will arise if that is not the case.

What I am proposing is to continue storing all dates in UTC, but as timestamps with timezone: i.e., `TIMESTAMPTZ '2021-01-16 15:42:00+00'` (declaring explicitly it's in UTC) rather than `TIMESTAMP '2021-01-16 15:42:00'` (whose interpretation depends on the `TimeZone` parameter).

On the other hand, you mentioning PGTZ gave me an idea: maybe another solution could be running Grafana with `PGTZ` set to `Etc/UTC`. This is another way of setting `TimeZone` to `Etc/UTC` for the client session, independently of the PostgreSQL server's `TimeZone` general setting.

The problem I am seeing with that (for all of us not using Docker containers) is how/where to define the `PGTZ` environment variable only for Grafana, since that depends on the method used for launching the Grafana server dæmon. Unfortunately, Grafana lacks (I think) a way to set the timezone as one the parameters of a PostgreSQL data source.

**Comment by DrMichael** [comment]
> What I am proposing is to continue storing all dates in UTC, but as timestamps with timezone: i.e., `TIMESTAMPTZ '2021-01-16 15:42:00+00'` (declaring explicitly it's in UTC) rather than `TIMESTAMP '2021-01-16 15:42:00'` (whose interpretation depends on the `TimeZone` parameter).

I don't object to this. Would be definitely clearer. @adriankumpf What du you think?

> On the other hand, you mentioning PGTZ gave me an idea: maybe another solution could be running Grafana with `PGTZ` set to `Etc/UTC`. This is another way of setting `TimeZone` to `Etc/UTC`, but only for the Grafana's client session, independently of the PostgreSQL server's `TimeZone` general setting.

Hmmm, I got the statistics dashboard working correctly by setting PGTZ to my local timezone.

> Unfortunately, Grafana lacks (I think) a way to set the timezone (i.e. `PGTZ`) as one the parameters of a PostgreSQL data source.

Yes, that is indeed unfortunate. I searched for it for a while, but apparently it is not possible.

**Comment by SergioRius** [comment]
@DrMichael @adriankumpf
The affected SQL queries are located in the overview panel in the stats section. Those are supposed to only show the last values reported by the api.
```
SELECT
	$__time(date),
	convert_celsius(driver_temp_setting, '$temp_unit') as "Driver Temperature [°$temp_unit]"
FROM positions
WHERE driver_temp_setting IS NOT NULL AND car_id = $car_id AND date >= (NOw() - interval '10m')
ORDER BY date DESC
LIMIT 1;
```
The ORDER BY DESC alongside with the LIMIT statement works for getting the last stored value.
It is irrelevant the timezone, or even the interval for other than further limiting the registers to process.
Other stat graphs in the panel do filter time by the panel interval ```$__timeFilter(date)``` or nothing at all.

I've measured the time to process the query with and without time restriction on a testing table with 486585 registers
With TimeFilter = 433ms
Without any time restriction = 412ms
So it seems that ```LIMIT 1``` does a good job by himself in limiting the jobs weight. And the date column does not allow for null values that would sort first in descending sort order.

So to be consistent with the other queries I would recommend to replace the time restriction clause to be ```AND $__timeFilter(date)``` instead of ```AND date >= (NOw() - interval '10m')``` and avoid adding timezone processing to that query.
I have that modification in my setup and works as expected.

**Comment by DrMichael** [comment]
@SergioRius well, the intention behind `date >= (NOW() - interval '10m')` is, that values older than 10 minutes are regarded as too old and should not be shown (I think, 30 minutes would also be good enough though).

**Comment by jmalcaide** [comment]
>  (I think, 30 minutes would also be good enough though).

I agree. I think that readings up to 1 hour old would be acceptable. Besides, I would add information about how old are the temperature readings shown (something as "data from XX minutes ago" if there are recent values, or "no data in the last XX minutes" if there are not). This information could be shared by the three temperature readings.

**Comment by SergioRius** [comment]
> @SergioRius well, the intention behind `date >= (NOW() - interval '10m')` is, that values older than 10 minutes are regarded as too old and should not be shown (I think, 30 minutes would also be good enough though).

Please understand that I'm not trying to be rude, just being clear:
You are forgetting about this part of the query:
```
ORDER BY date DESC
LIMIT 1;
```
Please read the postgreSQL documentation: [https://www.postgresql.org/docs/8.1/queries-limit.html](https://www.postgresql.org/docs/8.1/queries-limit.html)

>LIMIT and OFFSET allow you to **retrieve just a portion of the rows** that are generated by the rest of the query

> When using LIMIT, it is important to use an **ORDER BY clause that constrains the result rows into a unique order**.

So here, we are ordering the records from the newest one to the oldest but then only getting the first one (The most recent)
Do you understand that it makes ```date >= (NOW() - interval '10m')``` redundant and it's nullified as for TZ effects and **only gets the last record** on the table?

Why you would want to get 10m or even increase it to 30m? It's totally futile. In fact, what it makes is that if there's no record in that interval, you don't get anything (10m or 10m+TZ that's irrelevant). That's the nature of the issue, and not a TZ.
The current state of the car could be found in the dashboards interval (24h) but you will lose it as the car has been sleeping for only an hour and a half.
It makes more sense to increase the interval to 24h, the one in the dashboard so you have a better chance of getting a result and also avoid travelling the whole table, but we could also get rid of the time restriction altogether.

Do you understand?

**Comment by DrMichael** [comment]
@SergioRius don't want to be rude, but have you read what I wrote?

**Comment by DrMichael** [comment]
Added to PR #1213

**Comment by adriankumpf** [comment]
> > What I am proposing is to continue storing all dates in UTC, but as timestamps with timezone: i.e., TIMESTAMPTZ '2021-01-16 15:42:00+00' (declaring explicitly it's in UTC) rather than TIMESTAMP '2021-01-16 15:42:00' (whose interpretation depends on the TimeZone parameter).
> 
> I don't object to this. Would be definitely clearer. @adriankumpf What du you think?

Yes, I agree. I will have to think about it in more detail, but that sounds like a good solution.

**Comment by DrMichael** [comment]
Fixed in https://github.com/adriankumpf/teslamate/commit/3c78c5af30bf7ea879e469f7b2a2daecf0cf054b

This could be closed here, I think?

**Comment by jmalcaide** [comment]
> Fixed in [3c78c5a](https://github.com/adriankumpf/teslamate/commit/3c78c5af30bf7ea879e469f7b2a2daecf0cf054b)
> 
> This could be closed here, I think?

I think so.

**Comment by DrMichael** [comment]
You could close it...

**Comment by jmalcaide** [comment]
Oh! I am sorry.

**Comment by DrMichael** [comment]
Thanks, good analysis btw...
