### ISSUE TITLE
random plugged_in events

### ISSUE THREAD

**Issue by brianmay** [adriankumpf/teslamate#1221]
**Describe the bug**

With the Tesla clearly plugged in, I can get a random mqtt message with `plugged_in = False`. Then a minute later, I get a message `plugged_in = True`.

During the entire time the Tesla app shows the car was never disconnected.

It doesn't appear connected with the car going to sleep or anything else I can think of.

**Expected behavior**

I shouldn't receive  `plugged_in = False` unless the car is unplugged.

**How to reproduce it (as minimally and precisely as possible)**:

1. Plug car in.
2. Monitor `plugged_in` mqtt queue.

**Relevant entries from the logs**

This bug has nothing to do with grafana.

The logs show:

```
[...]
2021-01-19 10:20:17.073 [info] GET /
2021-01-19 10:20:17.087 [info] Sent 200 in 13ms
2021-01-19 10:20:18.919 car_id=1 [info] Start / :online
2021-01-19 10:20:18.947 car_id=1 [info] Connecting ...
2021-01-19 10:20:20.383 [info] GET /
2021-01-19 10:20:20.395 [info] Sent 200 in 11ms
[...]
```

I deleted numerous GET requests, which are health checks.

Not sure if this is before or after this happened.

This is about the same time this happened "Start" seems to imply something died and got restarted. Is this correct?

But I don't see any other messages. Or errors. Or disconnection messages.

How do I check?

I will keep watching this, see if I can find/confirm patterns, etc.

Is there anything I can do to increase logging?

**Environment**

- TeslaMate version: 1.21.0
- Type of installation: Docker
- OS TeslaMate is installed on: Debian based Kubernetes cluster

**Comment by adriankumpf** [comment]
Can you get the vehicle state from the Tesla API when it shows `plugged_in = False`? Maybe it is because it is too cold weather (see https://github.com/adriankumpf/teslamate/issues/1060).

**Comment by brianmay** [comment]
Hmmm. My gut feeling is that this isn't the case here, as it isn't that cold here. Plus it generally comes good within about a minute.

But regardless this is a good lead... Will try to get the vehicle state data for you.

**Comment by brianmay** [comment]
Is this the data you require?

```
iex(7)> v["charge_state"]
%{
  "charge_miles_added_rated" => 0.0,
  "charge_current_request" => 32,
  "charger_power" => 0,
  "managed_charging_start_time" => nil,
  "charger_phases" => nil,
  "charge_energy_added" => 0.0,
  "charger_voltage" => 0,
  "fast_charger_type" => "ACSingleWireCAN",
  "time_to_full_charge" => 1.0,
  "ideal_battery_range" => 214.63,
  "usable_battery_level" => 82,
  "scheduled_charging_pending" => true,
  "charger_actual_current" => 0,
  "est_battery_range" => 164.61,
  "charge_limit_soc_min" => 50,
  "charge_port_door_open" => true,
  "managed_charging_active" => false,
  "charge_limit_soc_max" => 100,
  "fast_charger_present" => false,
  "fast_charger_brand" => "<invalid>",
  "scheduled_charging_start_time" => 1612015200,
  "conn_charge_cable" => "IEC",
  "timestamp" => 1611999228082,
  "user_charge_enable_request" => nil,
  "charge_port_cold_weather_mode" => nil,
  "charge_to_max_range" => false,
  "max_range_charge_counter" => 0,
  "charge_limit_soc_std" => 90,
  "charge_port_latch" => "Engaged",
  "managed_charging_user_canceled" => false,
  "charger_pilot_current" => 32,
  "minutes_to_full_charge" => 60,
  "trip_charging" => false,
  "battery_range" => 267.57,
  "charging_state" => "Stopped",
  "charge_rate" => 0.0,
  "not_enough_power_to_heat" => false,
  "charge_limit_soc" => 90,
  "charge_enable_request" => false,
  "charge_current_request_max" => 32,
  "battery_level" => 82,
  "charge_miles_added_ideal" => 0.0,
  "battery_heater_on" => false
}
```

Right now the Tesla is saying it is plugged in, but teslamate reports it is disconnected.

Might also be a problem with Tesla's API. See #1263.

I note that `charge_port_latch` == `engaged`. So this particular time not related to the other issue. Although this might be different this time also.

**Comment by brianmay** [comment]
Note despite the reference to the other bug, my teslamate seems to be connected and communicating fine. So far.

**Comment by brianmay** [comment]
Oh, eventually it did pick up the plugged in status. At 20:23:01. About 30 minutes after it was plugged in I think. Not sure if some delay here is normal or a sign of something not quite right.

**Comment by brianmay** [comment]
As some point it - most unexpectedly - changed back to false for plugged in. The above data is now:

```
%{
  "charge_miles_added_rated" => 0.0,
  "charge_current_request" => 24,
  "charger_power" => 0,
  "managed_charging_start_time" => nil,
  "charger_phases" => nil,
  "charge_energy_added" => 0.0,
  "charger_voltage" => 0,
  "fast_charger_type" => "ACSingleWireCAN",
  "time_to_full_charge" => 0.0,
  "ideal_battery_range" => 214.29,
  "usable_battery_level" => 82,
  "scheduled_charging_pending" => true,
  "charger_actual_current" => 0,
  "est_battery_range" => 164.35, 
  "charge_limit_soc_min" => 50,
  "charge_port_door_open" => true,
  "managed_charging_active" => false,
  "charge_limit_soc_max" => 100,
  "fast_charger_present" => false, 
  "fast_charger_brand" => "<invalid>",
  "scheduled_charging_start_time" => 1612015200,
  "conn_charge_cable" => "IEC",
  "timestamp" => 1612002873760,
  "user_charge_enable_request" => nil,
  "charge_port_cold_weather_mode" => nil,
  "charge_to_max_range" => false,
  "max_range_charge_counter" => 0, 
  "charge_limit_soc_std" => 90,
  "charge_port_latch" => "Engaged",
  "managed_charging_user_canceled" => false,
  "charger_pilot_current" => 24,
  "minutes_to_full_charge" => 0,
  "trip_charging" => false,
  "battery_range" => 267.15,
  "charging_state" => "Stopped",
  "charge_rate" => 0.0,
  "not_enough_power_to_heat" => false,
  "charge_limit_soc" => 90,
  "charge_enable_request" => false,
  "charge_current_request_max" => 24,
  "battery_level" => 82,
  "charge_miles_added_ideal" => 0.0,
  "battery_heater_on" => false
}
```

But `charge_port_latch` is still `engaged` so not sure what is going on here.

**Comment by brianmay** [comment]
I just noticed that when Teslamate it in "falling sleep" mode[1], which often seems to be the case with my car, it doesn't notice any events that occur with the car. Including driving the car a short distance. Even though the car is awake. So now, wondering if this is related. I can't think of it being responsible for the unwanted unplugged = false event however when it was previously unplugged = true. But might explain why it is sometimes very slow to notice being plugged in.

Tonight I said "cancel sleep attempt" and it immediately updated the plugged in status, the position of the vehicle, the charge status, etc.

I suspect normally the car should be in sleep mode, and when I plug the car in it will wake up and the software will notice that, and get an update. But this doesn't happen if Teslamate is trying to get the car to sleep.

If I am talking rubbish, please let me know :-)

[1] Not sure I understand why this happens yet, and yes I have tried some of the suggestions in other bug reports.

**Comment by brianmay** [comment]
Not sure if coincidence or not, but Teslamate ignoring events in "falling sleep" mode seems to have got a lot worse wince I upgraded from 1.21.0 to 1.21.1.

As in the Tesla now makes complete trips which are unobserved by teslamate. But as soon as a "cancel sleep attempt" it works out immediately what is happening.

**Comment by brianmay** [comment]
I have copied details of this into #1274, as I think it is likely an unrelated bug to what I initially opened here.

The original bug here was teslamate reporting that car was unplugged for a minute and then reporting it was plugged in. With no actual change to the car.

**Comment by MrMEScott** [comment]
Just want to say that I am seeing this behaviour also. The car is plugged in, and the Tesla app says it's plugged in, and Teslamate's web interface also says it's plugged in, but the MQTT feed into HomeAssistant indicates from time to time that it's unplugged - then shortly after it correctly detects that is plugged in after all.
This is irritating, as I have a Home Assistant automation that is designed to remind me if I forgot to plug in, and often it tells me the car is not plugged in when it actually is!

**Comment by brianmay** [comment]
@MrMEScott Yes, I have the exact same problem. My system tells me that the care was unplugged, when it wasn't. Then a minute later it says it is plugged in again.

Unfortunately, it tends to happen when I am not at my computer. And I am not inclined to stop what I am doing to gather the required evidence. Something I guess I need to rectify to fix this.

I did notice the last time it happened though the car changed from asleep to online. (No idea why it work up but that is not important here). Which looks like may have happened the first time this happened also (See the message: `Start / :online`). This is the source line:

https://github.com/adriankumpf/teslamate/blob/master/lib/teslamate/vehicles/vehicle.ex#L666

So I suspect the problem is something along the lines of:

1. Car wakes up.
2. teslamate notices this, and (incorrectly) sets default state of plug_in to false.
4. Eventually telsa supplies correct information - either via direct request or updated streaming data - and teslamate sets plug_in (and other data) to correct values.

But... I strongly suspect this isn't happening every time the car wakes up.

Unfortunately, I am somewhat hindered in that I don't really understand this code or how states are processed.

I also notice that my version is somewhat old, so I guess I should update. But none of the changes look related to this issue. Regardless, will upgrade as my next step.

**Comment by LelandSindt** [comment]
Assuming you are not in cold weather, plugged in it derived from a combination the position of the charge port door (open) and the charge port latch (engaged).

https://github.com/adriankumpf/teslamate/blob/5ed9131e1fb572f97fd4c097d894e92f63f2a3b2/lib/teslamate/vehicles/vehicle/summary.ex#L130-L136

It could be that the car is cycling the charge port latch which would cause TeslaMate to report the car as unplugged.

**Comment by brianmay** [comment]
Looking at this code:

https://github.com/adriankumpf/teslamate/blob/master/lib/teslamate/vehicles/vehicle/summary.ex#L126

plugged_in can have 4 states:

* `nil` - We don't have any data yet.
* `:unknown` - We have data, but the car reported `unknown`.
* `true`
* `false`

Which makes me immediately wonder if maybe `nil` or `:unknown` is being incorrectly mapped to "false" when sending the mqtt message.

I probably should double check what value was being sent. Pretty sure it was `False` though.

**Comment by brianmay** [comment]
I am going to experiment with the following code:

```
diff --git a/lib/teslamate_web/live/car_live/summary.html.leex b/lib/teslamate_web/live/car_live/summary.html.leex
index 7251d14..18dd57f 100644
--- a/lib/teslamate_web/live/car_live/summary.html.leex
+++ b/lib/teslamate_web/live/car_live/summary.html.leex
@@ -165,6 +165,11 @@
             <% end %>
           <% end %>
 
+          <tr>
+            <td class="has-text-weight-medium">Plugged In</td>
+            <td><%= inspect @summary.plugged_in %></td>
+          </tr>
+
           <%= if @summary.plugged_in do %>
             <%= unless @summary.scheduled_charging_start_time in [nil, :unknown] do %>
             <tr>
```

I notice that on restart, when car is asleep, it comes out as `:unknown`. But I haven't seen any mqtt message being published, which is good. But maybe this `:unknown` state is causing problems when the car awakes.

Ideally I would like to be able to log changes to the raw value. So I don't have to be constantly watching it. Might think about how to do this later.

**Comment by brianmay** [comment]
Forgot to say, I am assuming that `plugged_in` is not recorded to the database anywhere. If I got that wrong, please do tell me :-)

**Comment by brianmay** [comment]
I think this logic is suppose to prevent `:unknown` / nil values from getting published:

https://github.com/adriankumpf/teslamate/blob/v1.21.5/lib/teslamate/mqtt/pubsub/vehicle_subscriber.ex#L58

Which probably kills my theory. But will continue checking regardless.

**Comment by brianmay** [comment]
I am hoping this might help:

```
diff --git a/lib/teslamate/vehicles/vehicle/summary.ex b/lib/teslamate/vehicles/vehicle/summary.ex
index caf552e..6b96a11 100644
--- a/lib/teslamate/vehicles/vehicle/summary.ex
+++ b/lib/teslamate/vehicles/vehicle/summary.ex
@@ -5,6 +5,8 @@ defmodule TeslaMate.Vehicles.Vehicle.Summary do
   alias TeslaApi.Vehicle
   alias TeslaMate.Log.Car
 
+  require Logger
+
   defstruct ~w(
     car display_name state since healthy latitude longitude heading battery_level usable_battery_level
     ideal_battery_range_km est_battery_range_km rated_battery_range_km charge_energy_added
@@ -68,6 +70,12 @@ defmodule TeslaMate.Vehicles.Vehicle.Summary do
   defp get_car_attr(nil, _key), do: nil
 
   defp format_vehicle(%Vehicle{} = vehicle) do
+    case vehicle.charge_state do
+      %Charge{} = c -> Logger.info("charge_state #{inspect c}")
+      nil -> Logger.info("charge_state nil")
+    end
+    Logger.info("plugged_in #{inspect plugged_in(vehicle)}")
+
     %__MODULE__{
       # General
       display_name: vehicle.display_name,
```

Hopefully this will prove/disprove the "cycling the charge port latch" theory above too. Although I never saw anything like when monitoring the car with my (dumb) software.

**Comment by brianmay** [comment]
OK, here are the logs. From immediately before the disconnected event:

```
2021-03-08 09:39:25.054 [info] charge_state %TeslaApi.Vehicle.State.Charge{charge_current_request_max: 32, charge_limit_soc_min: 50, charge_rate: 0.0, usable_battery_level: 75, ideal_battery_range: 196.43, charge_limit_soc_max: 100, charge_energy_added: 0.0, est_battery_range: 185.18, fast_charger_brand: "<invalid>", charge_port_latch: "Engaged", charger_voltage: 0, charge_to_max_range: false, charge_limit_soc: 90, charge_current_request: 32, charge_limit_soc_std: 90, charge_port_cold_weather_mode: nil, scheduled_charging_pending: true, managed_charging_user_canceled: false, charger_phases: nil, timestamp: 1615191318734, fast_charger_present: false, scheduled_charging_start_time: 1615225500, charger_actual_current: 0, managed_charging_active: false, charge_miles_added_ideal: 0.0, fast_charger_type: "ACSingleWireCAN", user_charge_enable_request: nil, managed_charging_start_time: nil, charger_pilot_current: 32, conn_charge_cable: "IEC", not_enough_power_to_heat: false, charge_miles_added_rated: 0.0, battery_range: 244.89, battery_level: 75, time_to_full_charge: 1.75, charger_power: 0, charge_enable_request: false, charge_port_door_open: true, max_range_charge_counter: 0, battery_heater_on: false, charging_state: "Stopped", trip_charging: false}
2021-03-08 09:39:25.054 [info] plugged_in true
```

Immediately after the disconnected event:

```
2021-03-08 09:39:28.531 car_id=1 [info] Start / :online
2021-03-08 09:39:28.560 car_id=1 [info] Connecting ...
2021-03-08 09:39:28.562 [info] charge_state %TeslaApi.Vehicle.State.Charge{charge_current_request_max: 32, charge_limit_soc_min: 50, charge_rate: 0.0, usable_battery_level: 75, ideal_battery_range: 196.43, charge_limit_soc_max: 100, charge_energy_added: 0.0, est_battery_range: 185.18, fast_charger_brand: "<invalid>", charge_port_latch: "<invalid>", charger_voltage: nil, charge_to_max_range: false, charge_limit_soc: 90, charge_current_request: 32, charge_limit_soc_std: 90, charge_port_cold_weather_mode: nil, scheduled_charging_pending: true, managed_charging_user_canceled: false, charger_phases: nil, timestamp: 1615196366855, fast_charger_present: nil, scheduled_charging_start_time: 1615225500, charger_actual_current: nil, managed_charging_active: false, charge_miles_added_ideal: 0.0, fast_charger_type: "<invalid>", user_charge_enable_request: nil, managed_charging_start_time: nil, charger_pilot_current: nil, conn_charge_cable: "<invalid>", not_enough_power_to_heat: nil, charge_miles_added_rated: 0.0, battery_range: 244.89, battery_level: 75, time_to_full_charge: 0.0, charger_power: nil, charge_enable_request: false, charge_port_door_open: nil, max_range_charge_counter: 0, battery_heater_on: false, charging_state: "Stopped", trip_charging: nil}
2021-03-08 09:39:28.562 [info] plugged_in false
```

Then immediately after it came good again:

```
2021-03-08 09:39:59.176 [info] charge_state %TeslaApi.Vehicle.State.Charge{charge_current_request_max: 32, charge_limit_soc_min: 50, charge_rate: 0.0, usable_battery_level: 75, ideal_battery_range: 196.43, charge_limit_soc_max: 100, charge_energy_added: 0.0, est_battery_range: 184.85, fast_charger_brand: "<invalid>", charge_port_latch: "Engaged", charger_voltage: 0, charge_to_max_range: false, charge_limit_soc: 90, charge_current_request: 32, charge_limit_soc_std: 90, charge_port_cold_weather_mode: nil, scheduled_charging_pending: true, managed_charging_user_canceled: false, charger_phases: nil, timestamp: 1615196398873, fast_charger_present: false, scheduled_charging_start_time: 1615225500, charger_actual_current: 0, managed_charging_active: false, charge_miles_added_ideal: 0.0, fast_charger_type: "ACSingleWireCAN", user_charge_enable_request: nil, managed_charging_start_time: nil, charger_pilot_current: 32, conn_charge_cable: "IEC", not_enough_power_to_heat: false, charge_miles_added_rated: 0.0, battery_range: 244.89, battery_level: 75, time_to_full_charge: 1.75, charger_power: 0, charge_enable_request: false, charge_port_door_open: true, max_range_charge_counter: 0, battery_heater_on: false, charging_state: "Stopped", trip_charging: false}
2021-03-08 09:39:59.176 [info] plugged_in true
```

Based on this I think the solution is to completely ignore the `charge_port_latch` value - which is `"<invalid>"` and rely entirely on the `charging_state` value.

This is what I used before I moved to teslamate and it seemed to work 100% reliably for me.

**Comment by brianmay** [comment]
Sure would be nice to know why `charge_port_latch` is returning `"<invalid>"` but I suspect there is little hope here :-(

Looks like a Tesla bug to me.

**Comment by LelandSindt** [comment]
Ah, so the car was not physically cycling the charge port latch but instead logically cycling it.. :wink: 

What are the values of `charging_state` that can be used to derive  `plugged_in` ?

**Comment by LelandSindt** [comment]
.... checked my old code... 

https://github.com/gaussmeter/query/blob/14ee45faf04f2ae7be7c936e35ba3d7abde36b94/query.py#L166-L167

Looks like I was relying on `charging_state != "Disconnected"` to determined plugged in.

**Comment by brianmay** [comment]
I will submit a PR right after I test it.

**Comment by brianmay** [comment]
https://github.com/adriankumpf/teslamate/pull/1423
