### ISSUE TITLE
teslamate container dies...

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#1244]
**Describe the bug**

The teslamate container is waiting for the database, which has been started and is accepting connections. Then the teslamate container dies. I can access the database from the shell outside of the containers. Can I check the database connection within the teslamate container somehow?

This all on a raspberry pi 3+.

I deleted all containers, images and volumes to start from scratch. I used the docker-compose.yml, which is running on another machine without issues. It happened just now, was running without issues ever since...

**Expected behavior**

Teslamate container should find the database and use it.

**Relevant entries from the logs**

database:
database_1   | 2021-01-23 12:09:04.161 UTC [1] LOG:  starting PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 8.3.0-6) 8.3.0, 32-bit
database_1   | 2021-01-23 12:09:04.163 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1   | 2021-01-23 12:09:04.163 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1   | 2021-01-23 12:09:04.177 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1   | 2021-01-23 12:09:04.203 UTC [25] LOG:  database system was shut down at 2021-01-23 12:05:59 UTC
database_1   | 2021-01-23 12:09:04.232 UTC [1] LOG:  database system is ready to accept connections

teslamate:
teslamate_1  | waiting for postgres at database:5432 (2sec)
teslamate_1  | waiting for postgres at database:5432 (4sec)
teslamate_1  | waiting for postgres at database:5432 (8sec)
teslamate_1  | waiting for postgres at database:5432 (16sec)
teslamate_1  | waiting for postgres at database:5432 (32sec)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | waiting for postgres at database:5432 (2sec)
teslamate_1  | waiting for postgres at database:5432 (4sec)
teslamate_1  | waiting for postgres at database:5432 (8sec)
teslamate_1  | waiting for postgres at database:5432 (16sec)
teslamate_1  | waiting for postgres at database:5432 (32sec)
teslamate_1  | waiting for postgres at database:5432 (64sec)
teslamate_1  | waiting for postgres at database:5432 (128sec)
teslamate_1  | waiting for postgres at database:5432 (256sec)

**Data**

[docker-compose.zip](https://github.com/adriankumpf/teslamate/files/5860174/docker-compose.zip)

**Environment**

- TeslaMate version: 1.22.0-dev
- Type of installation: Docker
- OS TeslaMate is installed on: raspbian buster on RPI3+
- User OS & Browser: Win10, Chrome
- Others: -

**Comment by DrMichael** [comment]
Well, it only happens with a fresh `edge` installation not with a `latest` installation.

**Comment by adriankumpf** [comment]
This could be related to the alpine upgrade to v3.13. Can you try the the latest `edge` image?

**Comment by DrMichael** [comment]
Yes, indeed. With alpine v3.12 it works again. (It happened only on the RPI, not on other machines...)

**Comment by Kosta-Github** [comment]
I am seeing this again right now with `edge` on my `rpi`. `latest` is working...

**Comment by adriankumpf** [comment]
> I am seeing this again right now with `edge` on my `rpi`. `latest` is working...

Which Raspbian Version?

**Comment by Kosta-Github** [comment]
```shell
$ uname -a
Linux pi-home 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

$ docker -v
Docker version 20.10.12, build e91ed57
```
