### ISSUE TITLE
No Charge Details in Charge Details for Supercharger charges

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#1252]
**Describe the bug**

I don't get any graph anymore for Supercharger charges:
![image](https://user-images.githubusercontent.com/8087682/105742202-7d032780-5f3b-11eb-9ad1-230fa7fbbfe0.png)

AC charges are fine. I am sure, I had graphs there before, they also show nothing.

**Expected behavior**

Show the graph as in
![image](https://user-images.githubusercontent.com/8087682/105741854-12ea8280-5f3b-11eb-81c1-8fbb227ad5d5.png)

**Relevant entries from the logs**
teslamate_1  | 2021-01-25 13:33:06.277 car_id=1 [info] Start / :online
teslamate_1  | 2021-01-25 13:33:06.362 car_id=1 [info] Connecting ...
teslamate_1  | 2021-01-25 13:33:17.214 [info] Connection was closed (a:1|t:1|d:0). Reconnecting …
teslamate_1  | 2021-01-25 13:33:28.018 [info] Connection was closed (a:1|t:2|d:0). Reconnecting …
teslamate_1  | 2021-01-25 13:33:38.811 [info] Connection was closed (a:1|t:3|d:0). Reconnecting …
teslamate_1  | 2021-01-25 13:33:49.627 [info] Connection was closed (a:1|t:4|d:0). Reconnecting …
teslamate_1  | 2021-01-25 13:35:12.417 car_id=1 [info] Driving / Start
teslamate_1  | 2021-01-25 13:51:55.673 car_id=1 [info] Driving / Ended / 16 km – 17 min
teslamate_1  | 2021-01-25 13:51:55.673 car_id=1 [info] Start / :online
teslamate_1  | 2021-01-25 13:52:11.245 car_id=1 [info] Charging / SOC: 35% / Tesla Supercharger, Eschborn
teslamate_1  | 2021-01-25 13:52:11.245 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-01-25 14:20:48.154 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:21:07.555 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:21:43.205 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:22:02.637 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:22:22.094 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:22:41.494 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:23:11.896 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:24:28.608 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:24:45.478 car_id=1 [info] Derived efficiency factor: 136.1 Wh/km (12x confirmed)
teslamate_1  | 2021-01-25 14:24:45.478 car_id=1 [info] Charging / Stopped / 19.78 kWh – 33 min
teslamate_1  | 2021-01-25 14:24:45.480 car_id=1 [info] Start / :online
teslamate_1  | 2021-01-25 14:24:45.494 car_id=1 [info] Connecting ...
teslamate_1  | 2021-01-25 14:25:25.447 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:25:41.148 [info] Connection was closed (a:1|t:1|d:1). Reconnecting …
teslamate_1  | 2021-01-25 14:25:44.868 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:25:51.953 [info] Connection was closed (a:1|t:2|d:1). Reconnecting …
teslamate_1  | 2021-01-25 14:26:02.780 [info] Connection was closed (a:1|t:3|d:1). Reconnecting …
teslamate_1  | 2021-01-25 14:26:04.564 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:26:13.609 [info] Connection was closed (a:1|t:4|d:1). Reconnecting …
teslamate_1  | 2021-01-25 14:26:15.969 [warn] TeslaApi.Error / https://mothership-api.vn.teslamotors.com:443/vehicles/103221772/user_command/vehicle_data => {"error": "Get http://localhost:7654/vehicle_data?user_command=true&slow_query_time=15: read tcp 127.0.0.1:34636->127.0.0.1:7654: read: connection reset by peer"}
teslamate_1  | 2021-01-25 14:26:15.969 car_id=1 [error] Error / :unknown
teslamate_1  | 2021-01-25 14:26:30.254 car_id=1 [info] Received stream data: :inactive
teslamate_1  | 2021-01-25 14:26:30.416 [info] Connection was closed (a:1|t:5|d:1). Reconnecting …
teslamate_1  | 2021-01-25 14:26:36.582 car_id=1 [info] Driving / Start
teslamate_1  | 2021-01-25 14:26:48.535 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-01-25 14:27:01.059 [info] Stream.Timeout / 5
teslamate_1  | 2021-01-25 14:27:01.225 [info] Connection was closed (a:1|t:6|d:1). Reconnecting …
teslamate_1  | 2021-01-25 14:57:46.980 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2021-01-25 14:57:47.694 car_id=1 [info] Driving / Ended / 14 km – 31 min
teslamate_1  | 2021-01-25 14:57:47.694 car_id=1 [info] Start / :online
teslamate_1  | 2021-01-25 15:01:23.475 car_id=1 [info] Suspending logging
teslamate_1  | 2021-01-25 15:03:23.453 [info] Connection was closed (a:1|t:1|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:03:34.265 [info] Connection was closed (a:1|t:2|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:08:23.534 [info] Connection was closed (a:1|t:1|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:08:34.372 [info] Connection was closed (a:1|t:2|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:10:50.016 [info] Connection was closed (a:1|t:1|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:10:50.716 [info] control:hello – 0
teslamate_1  | 2021-01-25 15:11:00.880 [info] Connection was closed (a:1|t:2|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:11:01.532 [info] control:hello – 0
teslamate_1  | 2021-01-25 15:11:11.688 [info] Connection was closed (a:1|t:3|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:11:22.511 [info] Connection was closed (a:1|t:4|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:13:23.200 [info] Connection was closed (a:1|t:1|d:1). Reconnecting …
teslamate_1  | 2021-01-25 15:13:23.875 [info] control:hello – 0

**Environment**

- TeslaMate version: 1.22.0-dev
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu 
- User OS & Browser: Chrome
- Others:

**Comment by DrMichael** [comment]
Well, because charger_actual_current is 0 for supercharger (DC?) charging.

@SergioRius Why did you add `charger_actual_current > 0` to the WHERE clause?

**Comment by DrMichael** [comment]
Anyway, PR https://github.com/adriankumpf/teslamate/pull/1253

**Comment by SergioRius** [comment]
> Well, because charger_actual_current is 0 for supercharger (DC?) charging.
> 
> @SergioRius Why did you add `charger_actual_current > 0` to the WHERE clause?

Yes, I did. Let me see if something like ( charge_type='dc' AND `charger_actual_current > 0)
Can be added instead of remove it completely.

**Comment by DrMichael** [comment]
Could be done with `(charger_actual_current > 0 OR fast_charger_type='Combo')` or `(charger_actual_current > 0 OR fast_charger_present)`

@adriankumpf What du you think?

**Comment by adriankumpf** [comment]
Not sure if that covers all cases? I'll merge your PR. That's more important for now.
