### ISSUE TITLE
! Stopped recording data 

### ISSUE THREAD

**Issue by kocsenc** [adriankumpf/teslamate#1263]
Data stopped logging today - maybe new oath token must be used for auth? 
https://www.reddit.com/r/teslamotors/comments/l837jv/did_tesla_silently_deprecate_the_owners_api/

**Expected behavior**

Data is logged

**Logs**

```
Jan 29 23:12:48 teslamate.local docker-compose[796]: grafana_1              | t=2021-01-30T07:12:48+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= soc
ket=
Jan 29 23:13:13 teslamate.local docker-compose[796]: teslamate_1            | 07:13:13.514 [warn] Too many disconnects …
Jan 29 23:13:13 teslamate.local docker-compose[796]: teslamate_1            | 07:13:13.515 car_id=1 [info] Creating new connection …
Jan 29 23:13:13 teslamate.local docker-compose[796]: teslamate_1            | 07:13:13.515 car_id=1 [info] Disconnecting ...
Jan 29 23:13:13 teslamate.local docker-compose[796]: teslamate_1            | 07:13:13.521 car_id=1 [info] Connecting ...
Jan 29 23:13:23 teslamate.local docker-compose[796]: teslamate_1            | 07:13:23.762 [info] Connection was closed (a:1|t:1|d:0). Reconnecting …
Jan 29 23:13:34 teslamate.local docker-compose[796]: teslamate_1            | 07:13:34.019 [info] Connection was closed (a:1|t:2|d:0). Reconnecting …
```

**Environment**

- TeslaMate version: `1.20.1`
- Type of installation: Docker
- OS TeslaMate is installed on: Docker/Ubuntu
- User OS & Browser: Windows, Firefox
- Others:

**Comment by kocsenc** [comment]
![image](https://user-images.githubusercontent.com/2752396/106349854-32104980-6286-11eb-8437-91d5c0b3dbf1.png)

**Comment by kocsenc** [comment]
![image](https://user-images.githubusercontent.com/2752396/106349859-3dfc0b80-6286-11eb-9995-747f5465adb8.png)

**Comment by IMgoRt** [comment]
Mine's still recording, as are my other usages, but it appears when the token expires the refresh endpoint is no longer valid.
Expect everyone to fail over the next 45 days while the new endpoint is identified.

**Comment by brianmay** [comment]
Either I am going cross eyed, or something seems to be wrong with the Tesla get token API:

```
iex(1)> {:ok, token} = ExTesla.get_token(<email>, <censored>)
** (MatchError) no match of right hand side value: {:error, "http get error %Mojito.Error{message: nil, reason: %Mint.HTTPError{module: Mint.HTTP2, reason: :closed_for_writing}}"}
```

(as a side note, recently I noticed an issue where my Tesla reported full network signal, but wasn't actually talking on the network until I rebooted the center console - so check that also)

**Comment by IMgoRt** [comment]
It's all here: https://github.com/timdorr/tesla-api/issues/215

**Comment by brianmay** [comment]
@IMgoRt If I am reading this correctly, Teslamate needs to be updated to use another URL for refreshing tokens.

Have I understood this correctly? Is there anything else that needs to be changed?

**Comment by IMgoRt** [comment]
> @IMgoRt If I am reading this correctly, Teslamate needs to be updated to use another URL for refreshing tokens.
> 
> Have I understood this correctly? Is there anything else that needs to be changed?

There's a whole new auth process to get the token used.
It's being reverse-engineered, so watch that issue

**Comment by brianmay** [comment]
Oh, joy. If only Tesla actually supported 3rd party users of its API. But I think I am dreaming here.

At least existing tokens seem to be working still. For me at least anyway :-)

Is there any easy way to tell when my Token will expire?

**Comment by IMgoRt** [comment]
> Oh, joy. If only Tesla actually supported 3rd party users of its API. But I think I am dreaming here.
> 
> At least existing tokens seem to be working still. For me at least anyway :-)
> 
> Is there any easy way to tell when my Token will expire?

The full token has issue time and validity period within the object, I've got just over 21 days left on the one I use in my js, fingers crossed.

**Comment by discojon** [comment]
Mine must have expired today also.  Home screen is barren and for some reason the dashboards won't load either.  

![image](https://user-images.githubusercontent.com/11757824/106364347-4e4ecd80-62fc-11eb-934f-006d87095b0c.png)

**Comment by adriankumpf** [comment]
TeslaMate already support the new auth flow. Please update to v1.21 @kocsenc. 

Refreshing tokens only works with the latest development version. I'll release a new version soon.
