### ISSUE TITLE
latest docker image "teslamate/teslamate:edge" does not start on Raspi4

### ISSUE THREAD

**Issue by Kosta-Github** [adriankumpf/teslamate#1267]
With the current docker image `teslamate/teslamate:edge` I am seeing the following errors on startup on my Raspi4:

```
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __gmtime64_r: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __mktime64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __select_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __clock_getres_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __utime64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __fstat_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __ppoll_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __getrusage_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __clock_gettime64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __localtime64_r: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __stat_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __timerfd_settime64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __gettimeofday_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __lstat_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __dlsym_time64: symbol not found
teslamate_1          | Error relocating /opt/app/erts-11.1.7/bin/beam.smp: __ctime64: symbol not found
```

**Environment**

- TeslaMate version: teslamate:edge
- Type of installation: Docker
- OS TeslaMate is installed on: 2021-01-30 20:20:00 CET
- User OS & Browser: Raspberry 4

**Comment by adriankumpf** [comment]
Can you check again if this is still the case with the latest version? (`docker-compose pull`)

**Comment by Kosta-Github** [comment]
still not working:

```
$ docker inspect teslamate/teslamate:edge 
[
    {
        "Id": "sha256:e41586277e30ee443eee5b7c43442702b10491f6267e5bade713be488e17a7ed",
        "RepoTags": [
            "teslamate/teslamate:edge"
        ],
        "RepoDigests": [
            "teslamate/teslamate@sha256:b2064a7d2e02248b709cd4b5cba4b08a3a386e95fc4c88cea0e739ac7eebaca1"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-01-30T19:33:40.272317128Z",
...
```

**Comment by jmiverson** [comment]
Just went to upgrade and am now getting these same errors.  Same install/setup as Kosta.

**Comment by DrMichael** [comment]
Same here on RPI3+ and teslamate:edge

**Comment by adriankumpf** [comment]
I was also able to reproduce it on a Raspberry Pi 3 Model B. The problem is caused by the latest Alpine version:

> Therefore, the following platforms are not suitable as Docker hosts for 32-bit Alpine Linux 3.13.0, due to containing out-of-date libseccomp: Amazon Linux 1 or 2, CentOS 7 or 8, Debian stable without debian-backports, **Raspbian stable**, Ubuntu 14.04 or earlier, and Windows. This applies regardless of whether the Linux distribution Docker packages or separate Docker package repositories are used.

Source: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0

I've updated the Dockerfile to use Debian as a base iamge. The resulting image is unfortunately much larger than the one based on Alpine. But there is currently no alternative afaik.

**Comment by jmiverson** [comment]
teslamate:edge is now working for me!

**Comment by Kosta-Github** [comment]
What about staying with alpine 3.12.x?

**Comment by adriankumpf** [comment]
The official erlang/Elixir images are based on v3.13. And unofficial images are not available for all architectures. So in the end we would have to compile everything ourselves to stay on v3.12. That doesn't seem like a long-term solution to me.

**Comment by Kosta-Github** [comment]
works for me as well again! 👍
