### ISSUE TITLE
Tesla Auth Flow Change

### ISSUE THREAD

**Issue by rthomson83** [adriankumpf/teslamate#1268]
Looks like tesla has changed the auth flow today TM API now fails with this error:
`2021-01-30 21:32:46.492 [warn] Token refresh failed: %TeslaApi.Error{
  env: %Tesla.Env{
    __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []}
    __module__: TeslaApi,
    body: %{"response" => "endpoint_deprecated:_please_update_your_app."},`
    
   Looks like they've now migrated to SSO and deprecated direct auth on the owners API. 
   
Flow that works is detailed here https://tesla-api.timdorr.com/api-basics/authentication#post-https-auth-tesla-com-oauth-2-v-3-token

**Comment by wmaciel** [comment]
@rthomson83 have you found a workaround?
The link only redirects me to the API's documentation.

**Comment by wmaciel** [comment]
nevermind, the new version of teslamate seems to address this. I'll upgrade.

**Comment by rthomson83** [comment]
When I logged this I hadn't released there was an edge release in docker registry that contained all the updated changes. Once I discovered that I closed off this ticket but should've posted the resolution back here.
