### ISSUE TITLE
Geo-Fence Distance

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#127]
For some reason, teslamate seems to love to think I park at my neighbors home 50% of the time I arrive at home. I've set a geo-fence location for home for my lat/long and it's showing up fine. Is there a way to combine the destinations so it will combine/think that they are both the same destination? I've tried to set the geo-fence radius to include the radius of my neighbors home but that doens't seem to do the trick.

**Comment by adriankumpf** [comment]
Try to increase the radius even further. Geo-fences are evaluated before the address lookup happens.

**Comment by natrlhy** [comment]
Just an update. I tried increasing it to the max and it never combined the two addresses (mine and one 30ft away)

![image](https://user-images.githubusercontent.com/19696424/64185330-cc662680-ce21-11e9-8e98-b9f6db079fd7.png)

**Comment by adriankumpf** [comment]
It won't update past entries

**Comment by adriankumpf** [comment]
The next release will allow to pick geo-fences from a map and it'll also make it what area the geo-fence covers

**Comment by DrMichael** [comment]
Wouldn't it be great, if the links in Grafana, which now lead to Google Maps would lead to /geo-fences/new with long and lat filled out and Google Maps ambedded? Ideally with the location marked and the radius around it?

**Comment by adriankumpf** [comment]
Whoa, that's a really good idea! This part: "Ideally with the location marked and the radius around it?" is already implemented.
