### ISSUE TITLE
Ignores events in "falling sleep" mode

### ISSUE THREAD

**Issue by brianmay** [adriankumpf/teslamate#1274]
**Describe the bug**

I just noticed that when Teslamate it in "falling sleep" mode, which often seems to be the case with my car, it doesn't notice any events that occur with the car. Including driving the car a short distance. Even though the car is awake. As in the Tesla now makes complete trips which are unobserved by teslamate. But as soon as a "cancel sleep attempt" it works out immediately what is happening.

e.g. on several occasions I have "cancel sleep attempt" and it immediately updated the plugged in status, the position of the vehicle, the charge status, etc.

Not sure if coincidence or not, but Teslamate ignoring events in "falling sleep" mode seems to have got a lot worse since I upgraded from 1.21.0 to 1.21.1.

I have copied this from #1221 is this is likely an unrelated bug.

**Expected behavior**

teslamate should notice when state of car has changed, or if somebody starts trip. Otherwise it is kind of pointless :-)

**How to reproduce it (as minimally and precisely as possible)**:

1. Wait for teslamate to enter "falling sleep" mode, but not actual go to sleep.
2. Go for drive.
3. Notice teslamate still hasn't change and reports car as being locked, at the start point.

**Relevant entries from the logs**

Don't think this really helps. But log entries at time I canceled the sleep attempt:

```
2021-01-31 23:35:23.049 car_id=1 [info] Resuming logging
2021-01-31 23:35:25.466 car_id=1 [info] Driving / Start
2021-01-31 23:35:27.641 [info] Stream.Timeout / 5
2021-01-31 23:35:27.836 [info] Connection was closed (a:1|t:6|d:7). Reconnecting …
```

**Environment**

- TeslaMate version: 1.21.1
- Type of installation: Docker
- OS TeslaMate is installed on: Kubernetes 1.20.0

**Comment by brianmay** [comment]
If I continue having problems here, will downgrade to 1.20.0 and see if that helps.

**Comment by jmiverson** [comment]
I experience this occasionally as well. I’ve mostly gotten into the habit of checking if I recently got home or something (within the time frame that it might be trying to fall asleep). 

What I don’t fully understand is why this functionality is still needed in Teslamate after moving to the Streaming API. Why does Teslamate ever stop listening to the car? Will the car not sleep if Teslamate doesn’t perform this “disconnect”?

**Comment by brianmay** [comment]
It seems to be constantly happening every time now for me that I upgraded to 1.21.1

I tried the "cancel sleep attempt" before the last trip, but it had already entered "falling asleep" before I left.

I am going to downgrade to 1.21.0, at least this will give confirmation if 1.21.1 actually made things worse or not.

**Comment by brianmay** [comment]
I believe the theory is that the car cannot go to sleep while teslamate is connected. But I am not entirely sure of my facts here.

**Comment by brianmay** [comment]
Last trip worked fine. Maybe just a string of bad luck?

I would like to think that the code could be improved somehow to solve this, but not really sure I know enough about the "falling asleep" mode to come up with a solution with won't prevent sleep from occuring.

**Comment by brianmay** [comment]
My attempt to downgrade to 1.21.0 was a failure, due to it constantly the token after unsuccessful renewal (approxish once an hour). Which unfortunately means I can't easily test this bug with 1.21.0.

I have not seen it ever miss any trips before I upgraded to 1.21.1 however.

I have not upgraded to 1.21.2

**Comment by brianmay** [comment]
If this is still a problem with 1.21.2 - and I have seen reports it is (https://github.com/adriankumpf/teslamate/discussions/1280#discussioncomment-330754) - I would like to be able to disable the sleep mode entirely.

If I get the time I might see if I can understand the code enough to to create an option to do this.

**Comment by adriankumpf** [comment]
The car can only fall asleep if no queries are made via the API. Therefore events CANNOT be detected during this time. However, using the streaming API, TeslaMate is permanently connected until the car goes to sleep. This way we can detect when you start driving or charging during this period. By the way, no other logger I know of does this. However, only very limited information can be received via this method. 

The crucial thing here is that TeslaMate is able to connect to the streaming API. If this is not the case, short trips can be missed – as with every other data logger. Keep in mind that TeslaMate is only the last link in the chain, so if the other systems are not working correctly or are not available, data will be missed.
