### ISSUE TITLE
Unable to start docker oci runtime error 

### ISSUE THREAD

**Issue by send2ali** [adriankumpf/teslamate#1276]
Hi, I've just notices that the docker is no longer running. 
I get the following error message when i try to run it.

```
failure oci runtime create failed container_linux.go:349 starting container process caused "exec:\"/sbin/tini\:stat /sbin/tini: no such file or directory": unknown
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version: 1.25.5
- Type of installation: Docker 
- OS TeslaMate is installed on: Pi4
- User OS & Browser: Chrome
- Others:

**Comment by adriankumpf** [comment]
Can you double check that you are running the latest version? Because there is no TeslaMate version: `1.25.5`.

**Comment by send2ali** [comment]
i'm running 1.21.2. I got the other version from docker:
com.docker.compose.version (1.25.5) which was wrong.

I resolved this issue just by just updating /re-creating it:

docker-compose up -d

I wanted to understand what had occurred but don't know docker enought.

all good now.
