### ISSUE TITLE
Missing charge data in v1.7.0

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#128]
Hi, just upgraded and I don't have a lot of data due to all the docker issues, but I see that some of the charge data isn't showing up anymore. Is this a bug in the dashboard?

![Capture](https://user-images.githubusercontent.com/3529468/64051993-d8a46800-cb31-11e9-9a0a-99c87b733dda.JPG)

**Comment by adriankumpf** [comment]
Is that maybe related to your docker issues? Please attach the docker logs of that time period.

**Comment by bahree** [comment]
I don't think so, this is a brand new installation, am running this on a pi and not using the Synology one. Attached is another screenshot. I don't know why this shows miles driven, for the charging? This isn't docker related is my gut - is there a way I can help debug this and provide any logs? Thanks.
<img width="1551" alt="Screen Shot 2019-09-02 at 5 31 15 PM" src="https://user-images.githubusercontent.com/3529468/64136784-021af900-cda9-11e9-933f-d59724b947cb.png">

**Comment by bahree** [comment]
And another screenshot and this is the correct number of charges - which also shows up in the other Charges dashboard, but there are additional entries in there, which don't seem to be accurate. Thanks again!

<img width="1551" alt="Screen Shot 2019-09-02 at 5 51 38 PM" src="https://user-images.githubusercontent.com/3529468/64137061-ac475080-cdaa-11e9-8b0a-ac9b3abe2b41.png">

**Comment by adriankumpf** [comment]
> This isn't docker related is my gut - is there a way I can help debug this and provide any logs? Thanks.

To fetch the logs of the `teslamate` container run this command:

```bash
docker-compose logs -f teslamate
```

> I don't know why this shows miles driven

`miles driven` = miles driven since the last charge session
