### ISSUE TITLE
2019.32 9d0d19a Update. Offline

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#129]
After getting the 2019.32 9d0d19a update on our Model 3 I notice the car goes offline

![88E92B6E-A484-496F-8680-B78389E7690A](https://user-images.githubusercontent.com/19696424/64068282-ebc73e80-cbea-11e9-8f90-c0d6c8cc97ab.jpeg)

Any other users seeing this?

I get in the car and it’s not in WiFi or cellular in the garage

**Comment by ghostreader86** [comment]
No Wifi or cellular data -> no connection to Tesla -> no connection from TeslaMate to Tesla thru Tesla Api

**Comment by natrlhy** [comment]
Never had the car go offline prior to this update

**Comment by adriankumpf** [comment]
That's perfectly normal behavior. Maybe `offline` indicates some kind of deep sleep. 

![](https://raw.githubusercontent.com/adriankumpf/teslamate/master/screenshots/states.png)
