### ISSUE TITLE
cannot save charging cost more than 9999

### ISSUE THREAD

**Issue by chaehyun2** [adriankumpf/teslamate#1323]
**Describe the bug**

In "Charges" page, we can set Cost of each charge. But if I input more than 9999 then the value is not saved. 

**Expected behavior**

Cost value should be saved

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version: 1.21.3
- Type of installation: Docker 
- OS TeslaMate is installed on: Synology NAS
- User OS & Browser:
- Others:

**Comment by adriankumpf** [comment]
Yes, all number input fields need to become less strict. I'll close this in favor of #1064, because both issues are related.
