### ISSUE TITLE
Grafana ChargeLevel Dashboard: Usable battery alterantes between usable battery and battery

### ISSUE THREAD

**Issue by pkuehnel** [adriankumpf/teslamate#1337]
**Describe the bug**
The usable battery graph in the ChargeLevel Grafana dashboard alternates between usable battery and battery. The reason is a wrong SQL statement which let the usable battery value be the battery value if usable battery is null.

**Expected behavior**

The usable battery values should be connected to each other directly

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to the Charge Level Grafana Dashboard
2. Go to a timespan of max 3 hours, where you drive while having a lower usable battery than battery value, to clearly see the issue
3. You see the usable battery graph alternating between usable battery and battery

**Screenshots**
current situation:
![oldDiagram](https://user-images.githubusercontent.com/35361981/107622867-cac8a100-6c58-11eb-9776-c44435ebd26e.JPG)

**Solution**
Replace `coalesce(usable_battery_level, battery_level)` in the second line of the SQL-statement with `usable_battery_level` and set `Stacking and null value` --> `null value` to `connected`

Then you will get the following:
![newDiagram](https://user-images.githubusercontent.com/35361981/107622952-ea5fc980-6c58-11eb-91a5-e542ac5f7896.JPG)

- TeslaMate version: 1.21.2
- Type of installation: Docker

**Comment by adriankumpf** [comment]
If I remember correctly, the SQL query is written this way for historical reasons. Initially, the usable battery range was not recorded, so this fallback was built in. By now, it should be no problem to adjust the query, though.

**Comment by pkuehnel** [comment]
Is there really an issue if you set null value to connected? I don't think so, I think if there are only null values, there is no 'usable battery' line in the diagram, so wouldn't be an issue, even if usable battery was not recorded earlier. But I am not 100% sure.
