### ISSUE TITLE
Align TR Start and TR End with Range from Vehicle Dashboard

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#134]
@adriankumpf  This is related to reporting the proper Range (Ideal, Estimated, Rated) for the corresponding vehicle in the various Grafana charts (Drive, Drive Details, Charge, Charge Details, etc.).  This is particularly useful for tracking/referencing efficiency for longer trips.

For my vehicle (S 90D), the Rated Range should be captured in the Grafana charts.  

Thanks,

J

**Comment by adriankumpf** [comment]
Resolved with v1.9.0

**Comment by jun3280net** [comment]
@adriankumpf Thank you!  Will give it a try ASAP!

**Comment by jun3280net** [comment]
@adriankumpf  - I'm not seeing this update.  In fact, I don't see Range (rated) anymore either on the main page.  My range on Tesla app is 228 km.

Thanks,

J
 
![v1 9 1_screenshot](https://user-images.githubusercontent.com/30555695/65655905-1aaeb580-dfdb-11e9-90d2-3f107ff69df0.PNG)

![v1 9 1_screenshot2](https://user-images.githubusercontent.com/30555695/65655979-5f3a5100-dfdb-11e9-936a-2e18ebed2266.PNG)

**Comment by krezac** [comment]
@jun3280net check the settings.

**Comment by jun3280net** [comment]
> @jun3280net check the settings.

@krezac thank you very much for pointing me to this implementation update.  @adriankumpf thanks again for the fix.  Everything lines up nicely now.

**Comment by patrice-ebr** [comment]
Just installed V1.10 with this change and all the range stats and graphs are in-synch with the app/in-car display for both Model 3 & Model S when using 'rated' range...which is the value available on Model 3 (in the app). Really good work to get this straighten out!!! Thanks.
