### ISSUE TITLE
Charge_Energy_used lower than charge_energy_added

### ISSUE THREAD

**Issue by pkuehnel** [adriankumpf/teslamate#1342]
**Describe the bug**
In some charging processes I get a lower charge_energy_used value than charge_energy_added value.

**Expected behavior**
The charge_energy_used value can never be lower than added because efficiency is never 100% or higher.

**How to reproduce it (as minimally and precisely as possible)**:

I do not really know how to reproduce the issue. It seems like the issue occurs when varying charging speed (different amps and different number of phases during charging session.

**Relevant entries from the logs**
no relevant logs but I attached the data of charges table as csv file.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/35361981/107820266-c85e6800-6d7a-11eb-9b6f-4fdfbb24ce3a.png)
 
it is no grafana issue, screenshot just for illustration

**Data**
The relevant charging process is the one with id 220
[charges.txt](https://github.com/adriankumpf/teslamate/files/5974228/charges.txt)
[charging_processes.txt](https://github.com/adriankumpf/teslamate/files/5974229/charging_processes.txt)

**Environment**

- TeslaMate version: 1.21.2
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu 18.04.4 LTS

**Comment by BabyYeggie** [comment]
The "extra" energy added is from the battery warming up while charging a cold battery. Efficiency was capped at 100% as per #234.

**Comment by pkuehnel** [comment]
Ok, I saw today, that charge_energy_added was increasing while SOC was standing still because all the power went into heating up the battery. (In my opinion this is a bug on Tesla's side. Why would I be intrested in this information, I actually want to know how much energy of the power I use went into thy battery (by charging not heating up) but OK it is like it is. Although in today's charging session charge energy added is lower than charge energy Used. There are two differences to the charging session yesterday:
1. There was no phase change and no pilot Amp change
2. The car was preheating during the whole charging session.

So I'm not quite sure what's the reason. I'll investigate more and reopen the issue when needed.

**Comment by micku7zu** [comment]
If anyone is reading this old thread, I just wanted to add that there is also this issue with "charge_energy_added": https://github.com/teslamate-org/teslamate/issues/3095#issuecomment-3073335201
