### ISSUE TITLE
Trackmap plugin not working with Grafana 7.4.1

### ISSUE THREAD

**Issue by ampjunkie** [adriankumpf/teslamate#1360]
When displaying the drives on a map (with the Grafana Trackmap plugin as part of Teslamate), it does not show the blue dot as you move through the data.  This is a known issue with the latest version of the plugin with Grafana 7.4.1. It does not have an issue with Grafana 7.3.7 which was the version used in Teslamate 1.21.3. See here for more details: https://github.com/pR0Ps/grafana-trackmap-panel/issues/50

**Expected behavior**

When looking at a drive and a map, as you move your cursor through the data on the other tables, you should see a blue dot on the map tracing the position. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to the Drives dashboard
2. Click on any drive
3. Move the cursor through the Drive table
4. See the issue that there is no blue dot tracing the route on the map

**Relevant entries from the logs**

```
Bug seems to be in Grafana and/or the TrackMap plugin
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version: 1.21.4
- Type of installation: Docker
- OS TeslaMate is installed on: Linux Mint 19.3
- User OS & Browser: Linux Mint 19.3 and Brave

**Comment by ampjunkie** [comment]
Note: the trackmap plugin has supposedly been fixed and closed within the last 12 hours,  but I have not verified whether it is working.

**Comment by ampjunkie** [comment]
Thanks for the fix!  Trackmap v2.1.1 is now available (https://github.com/pR0Ps/grafana-plugin-repository/tree/update/pr0ps-trackmap-panel-v2.1.1)  but not yet directly from grafana. I have not personally tested it yet, but it is supposed to work with Grafana 7.4+ and have fixes, including the hover issue here.  Perhaps on the next TeslaMate release, if Grafana 7.4+ is needed to update, you can update Trackmap as well.

**Comment by adriankumpf** [comment]
Yeah, I briefly tested v2.1.1 but the map failed to load with an error. I'll wait until it is officially available and try again.

**Comment by ampjunkie** [comment]
> Yeah, I briefly tested v2.1.1 but the map failed to load with an error. I'll wait until it is officially available and try again.

Thanks for fixing this issue with the downgrade. Appreciate your work on TeslaMate!

**Comment by precks72** [comment]
Sorry for my ignorance, I am working at macOS Catalina & grafana 7.4.3 I am suffering exactly the same problem regarding no hover over the course. Unfortunately i have been trying during several days to install TrackMap 2.1.1 with no luck. I will really appreciate if you could help me giving me some dumb-for guidelines to isntall TrackMap 2.1.1.

Thanks and best regards, 

Antonio Varela.

**Comment by ampjunkie** [comment]
Hi Adrian,

I just noticed that trackmap has been updated to 2.1.2. I tested it with
Grafana 7.5.4 within Home Assistant and it seems to work.  So hopefully
this allows you to update to the latest version of Grafana with TeslaMate
and keep this feature.

Regards,
Joe
