### ISSUE TITLE
SRTM elevation data not available for 60N and above

### ISSUE THREAD

**Issue by jalkanen** [adriankumpf/teslamate#137]
The elevation data is a great addition, but unfortunately the SRTM data is not available for 60N latitude and northwards, therefore rendering the feature useless for many users in the Nordic countries (and everyone in Finland).

In addition, the log files have warnings like 

```
teslamate_1  | 07:20:35.993 [warn] Elevation query failed: %SRTM.Error{message: "Could not find HGT file: N61E025", reason: :file_not_found}
teslamate_1  | 07:20:35.993 [warn] Elevation query failed: %SRTM.Error{message: "Could not find HGT file: N61E025", reason: :file_not_found}
teslamate_1  | 07:20:35.993 [warn] Elevation query failed: %SRTM.Error{message: "Could not find HGT file: N61E025", reason: :file_not_found}
```

Suggestion: use an alternative elevation source for 60N and above, or at least handle the error gracefully, as this is unfixable when it comes to SRTM data.

**Comment by adriankumpf** [comment]
That sucks! I didn't know that the SRTM is not available outside these boundaries. The warnings will be fixed with the next release.

As for alternatives sources, I only found this: https://tiedostopalvelu.maanmittauslaitos.fi/tp/kartta?lang=en But there's no option to download the actual .hgt files apparently. Feel free to propose or implement an alternative solution.

**Comment by jalkanen** [comment]
I think they are available in GeoTIFF or ASCII grid formats, but this is something that I have no experience on unfortunately.

How about https://open-elevation.com/?

**Comment by Helmi** [comment]
I'm not an expert on this type of data and formats but I did a little research and thought I'd drop some links even if they might be not suitable.

https://asterweb.jpl.nasa.gov/gdem.asp
http://www.viewfinderpanoramas.org/dem3.html

**Comment by adriankumpf** [comment]
If someone finds an SRTM data provider for 60N+ and wants to contribute this repository contains the code: https://github.com/adriankumpf/srtm

**Comment by lignumaqua** [comment]
Amazon Web Services hosts an Open Data elevation dataset in an S3 bucket which covers the entire globe. It's created from a combination of SRTM, USGS, and other sources. https://registry.opendata.aws/terrain-tiles/

Formats available are here: https://github.com/tilezen/joerd/blob/master/docs/formats.md

**Comment by adriankumpf** [comment]
Nice! I'll check it out.
