### ISSUE TITLE
Start, stop and restart of teslamate

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#138]
1. What is the proper way to start, stop, restart teslamate?
2. How do you start teslamate at boot time?

**Comment by adriankumpf** [comment]
Please take the time to grasp the basics of docker / docker-compose: https://docs.docker.com/compose/gettingstarted/ We can't answer every question related to the  technologies used by this project.

To summarize:

```bash
# Start all services in the docker-compse file in the background
docker-compose up -d

# Stop all services
docker-compose down

# Restart all services
docker-compose restart
```

**Comment by DrMichael** [comment]
Thanks, will do.

**Comment by normalfaults** [comment]
Also if you want to learn more try https://play-with-docker.com 

Nirmal Mehta

**Comment by DrMichael** [comment]
:-) Or https://training.play-with-docker.com

**Comment by sebmartin** [comment]
Is there a way to shut it down without stopping the container? I'm running TeslaMate in Kubernetes and I'm following the instructions to [restore a DB backup](https://docs.teslamate.org/docs/maintenance/backup_restore/#restore) so I was hoping to just SSH into the testlamate container and stop the service while I restore the DB. 

I suppose I could remote the container from the k8s pod while I do that but I was curious if there was an easier way.
