### ISSUE TITLE
 [error] Mounting XXXXXX failed while verifying session with: :invalid

### ISSUE THREAD

**Issue by smazzucato** [adriankumpf/teslamate#139]
Started getting this error after the Tesla network was down last night.  The message is showing every 10 seconds.

**Comment by pinguozzo** [comment]
Hi,
I've got the same.

**Comment by adriankumpf** [comment]
Nothing to worry about:

> The session error can be resolved by reloading the browser tab with the TeslaMate web interface that was opened before restarting. (To never see that error again set both env vars SECRET_KEY_BASE and SIGNING_SALT)

(https://github.com/adriankumpf/teslamate/issues/130#issuecomment-527166057)
