### ISSUE TITLE
Error: :authorization_request_failed

### ISSUE THREAD

**Issue by uhthomas** [adriankumpf/teslamate#1398]
**Describe the bug**

Can't log in.

**Expected behavior**

Should be able to log in.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a fresh instance of teslamate
2. Login

**Relevant entries from the logs**

```
teslamate_1  | 2021-02-25 23:30:21.576 [info] GET /
teslamate_1  | 2021-02-25 23:30:21.581 [info] Sent 302 in 5ms
teslamate_1  | 2021-02-25 23:30:21.587 [info] GET /sign_in
teslamate_1  | 2021-02-25 23:30:21.592 [info] Sent 200 in 4ms
teslamate_1  | 2021-02-25 23:30:33.822 [error] GET https://auth.tesla.com/oauth2/v3/authorize -> 403 (65.237 ms)
```

**Screenshots**

![](https://kipp.6f.io/qpjBz-Wio-NM.png)

**Data**

**Environment**

- TeslaMate version: latest
- Type of installation: Docker compose
- OS TeslaMate is installed on: Ubuntu
- User OS & Browser: Windows 10 & Chrome
- Others:

**Comment by zschmid** [comment]
can confirm same exact behavior, however this was on a ```docker-compose pull``` to update to latest version and ```docker-compose up -d``` to restart.  
Upon updating i'm prompted with a login screen and receive an authorization_request_failed. Prior to updating I was receiving a 'health check failure' message on the teslamate dashboard (which is what prompted me to update)

**Comment by hemang249** [comment]
I can confirm that on my end I am seeing the same timeouts that were there a couple of days back when Tesla Firewall broke. From what i have seen, the firewall seems to be back up and is causing issues.

**Comment by nsicko42** [comment]
+1 me neither

**Comment by ronan-guillamet** [comment]
Confirm. When I try manually to authenticate using the API, on the first step (obtain authorization code), I have a 403 issue.

**Comment by hemang249** [comment]
I was able to have some success by adding a "audience" parameter in the GET request for the Auth form. I am able to get the auth form but it is still getting stuck further down the line on the POST request for authorization.

**Comment by ToniA** [comment]
I also got this, but the problem went away a few hours later. I got this when I tried to restart TeslaMate and sign out / sign in, as I have no 'Drives' data logged since Feb 23rd (it's Feb 26th today). This could of course be a problem with the car, maybe the MCU1 should be rebooted? It has a new daughterboard, so it's not a problem with failing eMMC.

Early morning today (all timestamps in UTC) when attempting to sign in:
```
teslamate_1  | 2021-02-26 07:41:18.478 [error] GET https://auth.tesla.com/oauth2/v3/authorize -> 403 (315.888 ms)
```

A short while ago everything was OK, don't know about drives data logging though:
```
teslamate_1  | 2021-02-26 10:16:30.748 [info] GET https://auth.tesla.com/oauth2/v3/authorize -> 200 (590.352 ms)
teslamate_1  | 2021-02-26 10:16:31.111 [info] POST https://auth.tesla.com/oauth2/v3/authorize -> 302 (338.853 ms)
teslamate_1  | 2021-02-26 10:16:31.352 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (240.862 ms)
teslamate_1  | 2021-02-26 10:16:32.295 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (949.803 ms)
teslamate_1  | 2021-02-26 10:16:32.402 [info] Scheduling token refresh in 5 wk 5 d
teslamate_1  | 2021-02-26 10:16:32.702 [info] GET /
```

**Comment by zschmid** [comment]
I attempted to authenticate again this AM and was successful. For me this issue is now resolved and I have a new token. Seems like potentially a temporary issue with Telsla's auth service.

**Comment by uhthomas** [comment]
As @zschmid has said, testing again this morning works... Looks like Tesla is playing with the WAF at mercy of non-official apps.

**Comment by uhthomas** [comment]
Looks like this is back as of 18:50 09/03/2021 UTC.

The official Tesla apps still work, so we must be missing something in the requests.

**Comment by adriankumpf** [comment]
Hey @uhthomas can you try the latest release (v1.21.6)?

**Comment by eN0Rm** [comment]
> Hey @uhthomas can you try the latest release (v1.21.6)?

Worked for me now.

**Comment by uhthomas** [comment]
Thanks @adriankumpf 

That seems to have resolved it 😄
