### ISSUE TITLE
Time since last upgrade is wrong

### ISSUE THREAD

**Issue by MarcFinns** [adriankumpf/teslamate#1409]
For some reasons my Model 3 has not updated since 23 January 2021. (already opened a case with Tesla...)
Today it is March 1st and the teslaMate updates dashboard shows "time since last update: 2 weeks"

**Expected behavior**

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by adriankumpf** [comment]
Can you get the latest updates that were stored in the database and post them here?

```   
$ docker-compose exec database psql teslamate teslamate -c \
      "COPY (  select * from updates where start_date > '2020-10-01') TO STDOUT WITH CSV HEADER" > updates.csv
```

**Comment by MarcFinns** [comment]
Hi, i run the script:
id,start_date,end_date,version,car_id
1,2020-10-13 19:33:30.863,2020-10-13 19:33:30.863,2020.36.11 ccacdb181f16,1
2,2020-10-13 20:06:52.418,2020-10-13 20:20:49.019,2020.40.4 ffa5212dba76,1
3,2020-10-22 20:27:08.888,2020-10-22 20:38:41.395,2020.40.8 9744d0c0d399,1
4,2020-11-03 07:31:17.072,2020-11-03 07:48:48.24,2020.40.9 507cb67a95c8,1
5,2020-11-09 07:32:06.38,2020-11-09 08:06:37.457,2020.44.10.1 955dc1dd145e,1
6,2020-11-22 16:27:33.555,2020-11-22 16:27:33.555,2020.44.15 19675f719e84,1
7,2020-12-02 21:06:51.867,2020-12-02 21:16:27.218,2020.44.25 0ba7ea36671e,1
8,2020-12-11 08:15:23.33,2020-12-11 08:28:36.381,2020.48.10 f8900cddd03a,1
9,2020-12-22 07:40:56.35,2020-12-22 08:01:32.304,2020.48.12.1 3095698c8a55,1
10,2020-12-28 06:25:27.332,2020-12-28 06:50:29.932,2020.48.26 e3178ea250ba,1
11,2021-01-07 07:12:27.513,2021-01-07 07:31:56.987,2020.48.30 040912887bad,1
12,2021-01-23 22:14:23.188,2021-01-23 22:35:43.092,2020.48.35.5 842a95863251,1

**Comment by dyxyl** [comment]
Is this just a confusing column title?  I think it should be changed to "Since Previous Update" ("Last" means the most recent one, but the column shows the duration between updates).

**Comment by adriankumpf** [comment]
> Is this just a confusing column title? I think it should be changed to "Since Previous Update" ("Last" means the most recent one, but the column shows the duration between updates).

Yup, that is correct. It refers to the duration between updates, so in your case the duration between "2020.48.30" and "2020.48.35.5".
