### ISSUE TITLE
Is there a way to re-enter credentials?

### ISSUE THREAD

**Issue by sbeaudette** [adriankumpf/teslamate#141]
It seems that there was a recent outage on Tesla's side.  The only way to fix my Tesla app was to re-enter my credentials.  How do I do that with 'teslamate' ?

Also, it appears that the teslamate_web (port 4000) is unaware of the connectivity problem.  It simply shows the most recent state that it polled.

Thanks,
-Steve

**Comment by netnem** [comment]
Same issue.  Trying to restore logging after tesla outage last night.  Some saying that vehicle IDs may have changed as well, but I can't figure out how to regenerate a token/re-log back in on the port 4000 page.

**Comment by adriankumpf** [comment]
Have a look at the teslamate logs. If there are no authentication issues it should be able to poll the API with the previous token. It will prompt you to re-enter the credentials if no tokens could be obtained. Also try to restart TeslaMate if you haven't already and see if the authentication still works.

**Comment by EvanMcEwen** [comment]
@adriankumpf Tesla regenerated all the vehicle IDs and I think it's causing an error in your app. I keep crashing on boot now.

**Comment by EvanMcEwen** [comment]
https://www.reddit.com/r/teslamotors/comments/cyxbtm/tesla_app_down_for_maintenance/eyvh70p/

**Comment by EvanMcEwen** [comment]
teslamate_1            |     ** (EXIT) an exception was raised:
teslamate_1            |         ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{eid: X, name: "X", vid: X, vin: "X"}, errors: [vid: {"has already been taken", [constraint: :unique, constraint_name: "cars_vid_index"]}], data: #TeslaMate.Log.Car<>, valid?: false>}
teslamate_1            |             (teslamate) lib/teslamate/vehicles.ex:71: TeslaMate.Vehicles.create_or_update!/1

I redacted my personal info.

**Comment by adriankumpf** [comment]
https://github.com/adriankumpf/teslamate/issues/136

**Comment by EvanMcEwen** [comment]
@adriankumpf Thanks I'll update the postgres table myself.

**Comment by adriankumpf** [comment]
Closing this for now. v1.8 should handle the ID change automatically.

**Comment by bahree** [comment]
I honestly think, just having a button or something to reenter credentials might just be simpler. When we change the password, or want to invalidate everything - just reenter it and it will overwrite it.
