### ISSUE TITLE
Consumption & Efficiency not calculated for all drives

### ISSUE THREAD

**Issue by cleanev** [adriankumpf/teslamate#1418]
Consumption and efficiency are not calculated for all drives - grafana chart

**Expected behavior**
In the past, there are drives missing consumption & efficiency numbers, & am not sure if this is supposed to be, what the reason could be for missing calculations

Not sure about exactly how to recreate this issue, just see that the calculations are missing 

**Screenshots**
![29C7804D-ADDD-4491-BF5D-DCA9F6360C96](https://user-images.githubusercontent.com/45519661/110227139-32be8000-7ec3-11eb-96fc-e8de04830666.jpeg)

**Environment**

- TeslaMate version: 1.21.5
- Type of installation: Docker
- OS TeslaMate is installed on: Raspberry Pi 3B+
- User OS & Browser: iPadOS, Safari
- Others:

**Comment by BabyYeggie** [comment]
Same as #1380. Perhaps this needs to be stickied here.

**Comment by adriankumpf** [comment]
Link to thread: https://github.com/adriankumpf/teslamate/discussions/1411#discussioncomment-422265
