### ISSUE TITLE
MQTT `teslamate/cars/+/geofence` received every ~30-60 seconds with the same value

### ISSUE THREAD

**Issue by ramonsmits** [adriankumpf/teslamate#1420]
**Describe the bug**

When subscribing to the MQTT topic `teslamate/cars/+/geofence` I receive a value roughly every 30 to 60 seconds with the same value while parked.

**Expected behavior**

I expected to only receive an event when the zone is actually updated. Especially because the message is with retain which makes it unneeded to publish this value while the value is unchanged.

**How to reproduce it (as minimally and precisely as possible)**:

Just subscribe to the `teslamate/cars/+/geofence` topic.

**Relevant entries from the logs**

Not relevant

**Screenshots**

**Data**

Not relevant

**Environment**

- TeslaMate version:1.21.5
- Type of installation: Docker
- OS TeslaMate is installed on: Synology
- User OS & Browser: WIndows 10 / Chrome
- Others:

**Comment by LelandSindt** [comment]
For what it's worth, I have seen this behavior as well. In my case it resulted in "spam" in my logs so I coded around it... 

https://github.com/gaussmeter/retractor/blob/3c2e931cc535b1015b7758ad776f1c97d414af22/main.go#L63-L66

**Comment by ramonsmits** [comment]
I'm applying the same workaround (if equal to last received value, discard) it's just that this shouldn't need to be happening for any message with a retain flag set.
