### ISSUE TITLE
Stuck in Drive

### ISSUE THREAD

**Issue by ADebelius** [adriankumpf/teslamate#144]
Seems the whole API change/shutdown happened while I was driving. Since then, it only thinks I'm driving and Grafana is not showing the drive as ended properly.

I have updated to 1.8
I have restarted all the services/docker containers
Teslamate properly shows it as charging or whatever state

![Capture](https://user-images.githubusercontent.com/843407/64303716-f2d5b000-cf4e-11e9-9a32-bb6ea0e0d3e2.JPG)

Any idea how to force it to end thinking its driving?

**Comment by adriankumpf** [comment]
Yes, to end it properly using the existing drive data search run the following commands:

```bash
# connect to the running teslamate instance
docker-compose exec teslamate bin/teslamate remote
```

```elixir
iex> import Ecto.Query
iex> [drive_id] = TeslaMate.Log.Drive |> where([d], is_nil(d.end_date)) |> TeslaMate.Repo.all()
iex> TeslaMate.Log.close_drive(drive_id)
```

**Comment by ADebelius** [comment]
You da man! Got it closed out, should go back to logging like a champ. Making me want to learn elixir, seems like it is quite powerful.

**Comment by adriankumpf** [comment]
Glad it worked!

I can only recommend Elixir. It's a joy to work with while also being really productive.
