### ISSUE TITLE
Feature request: No sleep mode

### ISSUE THREAD

**Issue by ToniA** [adriankumpf/teslamate#1442]
**Describe the bug**

Add a feature into Teslamate settings to disable sleep mode altogether. In this mode Teslamate should make no attempts to put the car into sleep, but instead continue polling it. This would benefit those older (prior to 3/2018) Model S and Model X owners who have MCU1 and do not want to use the energy saving mode as it significantly slows down the instrument cluster startup time.

The problem at the moment is that if the car refuses to fall asleep when Teslamate expects it to do so, large amount of time is spent in a state where Teslamate attempts to put the car asleep and does no logging while doing so. Having the streaming mode turned on (see #1359) does not help.

A minimal implementation could be:
* a toggle in settings, like 'Car with MCU1, Display -> Energy Saving is OFF'
* when set, the `car_settings` in the database would be like this
   *  `use_streaming_api: f`
   * `suspend_after_idle_min: <some very large value>`
   * `suspend_min: 1`

This could probably be implemented with the streaming API as well. I have experimented with the settings above, and it works well. 

Some background: https://teslamotorsclub.com/tmc/threads/cluster-restarting-every-time-i-go-to-the-car-is-this-normal.219583/#post-5383875

> This week I did a small survey on the Finnish Tesla Owner's FB group. I got 80 answers from Model S owners having older than 3/2018 car with MCU1:
> * 2 people say they have energy saving turned on, and generally no problems with slow IC startup
> * 32 people say they have energy saving on, and have at least sometimes slow IC startup
> * 46 people say they have turned energy saving off because of this problem

Problems with logging scheduled charges:
* I have scheduled charging to start at 00:00
* I switched Teslamate to polling settings described above on 2021-03-09, see the difference...

![image](https://user-images.githubusercontent.com/2128464/111116455-ba188d00-856e-11eb-8591-f5d15cae64ea.png)

**Expected behavior**

Teslamate should be able to capture all drives and charges also when the car does not fall asleep. Currently this does not work well with MCU1 cars with energy saving turned off.

**Comment by adriankumpf** [comment]
The issue tracker is for bugs only. Moving to Discussions.
