### ISSUE TITLE
Projected Range : division by zero

### ISSUE THREAD

**Issue by pierresou** [adriankumpf/teslamate#1460]
Hello,

After having my SOC at 0%, I have an exception in the report "Projected Range".
Now my SOC is > 0%, but I still have this issue, not possible to have my projected range report working.

![teslamate](https://user-images.githubusercontent.com/11191829/111599976-30b4c500-87d1-11eb-8056-eccbf0d9d12b.png)

**Comment by adriankumpf** [comment]
You completely deleted the bug report template, so now the following information is missing. Please add.

```
**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:
```

**Comment by pierresou** [comment]
- TeslaMate version: 2021.4.11
- Type of installation: Docker
- OS TeslaMate is installed on: Synology DSM
- User OS & Browser: Windows 10 / Android - Chrome 89

**Comment by adriankumpf** [comment]
`2021.4.11` is not a TeslaMate version :) You can find that information on the TeslaMate settings page. It's just important to know whether you are using the latest version.

**Comment by pierresou** [comment]
Indeed 😁
The version is 1.21.6

**Comment by Dulanic** [comment]
PR submitted. I am guessing this was a API issue, but still having the SQL account for this possibility isnt bad.

**Comment by adri-k** [comment]
I get the same error 'db query error: pq: division by zero' on the 'Updates' page.

**Comment by Dulanic** [comment]
> I get the same error 'db query error: pq: division by zero' on the 'Updates' page. I am using TeslaMate 1.27.2.

PR submitted for Updates page.
