### ISSUE TITLE
After upgrade to 1.22 - settings page shows: Internal Server Error

### ISSUE THREAD

**Issue by pinguozzo** [adriankumpf/teslamate#1465]
**Describe the bug**

After upgrade to 1.22 - settings page shows: Internal Server Error

**Expected behavior**

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
teslamate_1  | Request: GET /settings
teslamate_1  | ** (exit) an exception was raised:
teslamate_1  |     ** (UndefinedFunctionError) function nil.id/0 is undefined
teslamate_1  |         nil.id()
teslamate_1  |         (teslamate 1.22.0) lib/teslamate_web/live/settings_live/index.ex:184: anonymous fn/2 in TeslaMateWeb.SettingsLive.Index.prepare/1
teslamate_1  |         (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |         (teslamate 1.22.0) lib/teslamate_web/live/settings_live/index.ex:16: TeslaMateWeb.SettingsLive.Index.mount/3
teslamate_1  |         (phoenix_live_view 0.15.4) lib/phoenix_live_view/utils.ex:320: anonymous fn/4 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/4
teslamate_1  |         (telemetry 0.4.2) /opt/app/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3
teslamate_1  |         (phoenix_live_view 0.15.4) lib/phoenix_live_view/static.ex:306: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
teslamate_1  |         (phoenix_live_view 0.15.4) lib/phoenix_live_view/static.ex:131: Phoenix.LiveView.Static.render/3```



**Environment**

- TeslaMate version: 1.22
- Type of installation: Docker
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by adriankumpf** [comment]
Have you modified or deleted data in the database yourself? I can't see any connection with the changes made in v1.22 right now.

**Comment by pinguozzo** [comment]
Hi, thanks for the feedback. 
I just deleted from the DB a state which was reporting errors. I followed the procedure described in one of the git issues comment to correctly delete it. 

But this happened 2 updates ago. 
Thanks for your feedback and amazing work!!

**Comment by adriankumpf** [comment]
I'm not sure what you mean by a state that was reporting errors. From the error message it looks like a car was deleted from the `cars` table but the corresponding entry in the `car_settings` is still present. 

I'll move this to the Q&A section for now because I don't see any signs of a bug so far.
