### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by MarcFinns** [adriankumpf/teslamate#1478]
Hi, it appears as the only filtering is time based. Therefor it is a bit cumbersome to answer questions like “what did I do since last charge”. A specific filter/button would be very useful. 
My 2c. Thanks for the great work, by the way.

**Comment by adriankumpf** [comment]
Moving this to [💡 Ideas](https://github.com/adriankumpf/teslamate/discussions/categories/ideas)
