### ISSUE TITLE
[error] Mounting lv:phx - with Teslamate v1.8

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#148]
Hi there,

I'm ran into this problem originally using V1.7 beta, but that was quickly resolved by simply closing all open instances of the Teslamate webpage that I had open on my different computers on the network, and reloading a single instance of the webpage.  

That said, I've updated to V1.8, and I'm getting the same error.  However, I have no instances of the Teslamate webpage open.  I've tried docker-compose down , but no luck either.  Right now the error persists every 10 seconds or so in the log.  Also, I've noticed my webpage does not have the button to force my car to "wake" or "sleep" anymore.  Any ideas?  

Thanks,

J

 
![image](https://user-images.githubusercontent.com/30555695/64401655-13753700-d02f-11e9-9a29-c72f73fd7131.png)

![image](https://user-images.githubusercontent.com/30555695/64401946-66032300-d030-11e9-9a45-732915f619b7.png)

**Comment by jun3280net** [comment]
Wow.....disregard.  It turns out I had a laptop running even with the lid closed for the past two weeks.  I didn't even realize this until I noticed this computer online in my remote desktop (Teamviewer) list.

That said - is there a way to prevent this from occurring or way to kick out instances that are connected to Teslamate?  I suppose if the changing the IP might work?

**Comment by adriankumpf** [comment]
Yep, there is an undocumented way: add these two variables to the environment of the `teslamate` container to never see the warning again: 

```YAML
...

  teslamate:
    image: teslamate/teslamate:latest
    environment:
      - SECRET_KEY_BASE=your-secret-key
      - SIGNING_SALT=your-secret-salt

...
```

**Comment by DrMichael** [comment]
Hi Adrian, which secret key and salt must I use there?

**Comment by adriankumpf** [comment]
You can use whatever (random) string you want.

**Comment by DrMichael** [comment]
But I still get those errors.
