### ISSUE TITLE
Efficiency/Range inaccuracy

### ISSUE THREAD

**Issue by drklain** [adriankumpf/teslamate#149]
#143  
**Describe the bug**
The system appears to be using an incorrect value for efficiency when calculating range on the car.  As a result, the ranges are all inflated.  For my 2017 Model S, 90D it is saying that:

- at 60% charge, the car has a range of 210 miles (equates to a full battery range of 350 miles)
- degradation chart shows max range of around 348 miles (at normal battery capacity on a new battery it should be around 293  #miles)
- Efficiency chart says it is using an efficiency factor of .189 (which I believe is the model 3 factor).  Derived efficiency factors are .142, 1.34 and .129 respectively.  I believe if the lower efficency factors were used, the ranges displayed would be more accurate, but I'm not sure as I don't know exactly which range data the grafana charts in question are using to calculate the car's range.

Screen captures attached.

![Screen Shot 2019-09-06 at 9 22 02 AM](https://user-images.githubusercontent.com/54458446/64431549-ad1d0280-d088-11e9-9b0e-be282c3b5c72.png)
![Screen Shot 2019-09-06 at 9 22 37 AM](https://user-images.githubusercontent.com/54458446/64431567-b312e380-d088-11e9-89ab-debd188180cc.png)
![Screen Shot 2019-09-06 at 9 23 27 AM](https://user-images.githubusercontent.com/54458446/64431571-b60dd400-d088-11e9-8d4b-5237fb310bfb.png)

```

**Operating environment (please complete the following information):**
 - OS: [e.g. Synology]
 - Version [e.g. v1.8.0]

**Comment by adriankumpf** [comment]
I will look into it later. A little background information in advance for you to dig into if you want:


> Rated Range  The car's estimate of remaining range based on a fixed energy consumption in Watt-hours/mile (whpm). The fixed whpm is different for different vehicles (85kWh / 60kWh) and in different markets based on the regulatory test for that vehicle in that market. 
> * US: The fixed whpm is based on EPA 5-cycle Standard
> * Europe: The fixed whpm is based on NEDC range in accordance with regulation ECE101
> * Canada: Unknown
>
> Estimated Range  The car's predicted remaining range based on energy consumption during recent driving. This is based on a dynamic Watt-hours/mile (whpm) value that is based on recent driving habits. This is not country-specific. 
> 
> Ideal Range  The car's estimate of remaining range based on a fixed energy consumption in Watt-hours/mile (whpm) at a specified average speed. The fixed whpm is a figure determined by Tesla and is not country specific. The average speed is a figure determined by Tesla and is not country specific.

Rightnow TeslaMate used the ideal range everywhere.

**Comment by drklain** [comment]
No disagreement.  I think the problem is that for these cars in question, Teslamate is still pulling data for a Model3 number instead of a ModelS number (hence the .189 efficiency rating).  I know you said that Teslamate is now identifying the car as a Model S (90D) but are you sure that the charts in question are using that ID, or are they still keying in on the MDL3 code?

**Comment by adriankumpf** [comment]
https://github.com/adriankumpf/teslamate/blob/9c61150bd5614728447e21789ab6edc5169b631e/lib/teslamate/vehicles/identification.ex#L44

**Comment by adriankumpf** [comment]
If you have a list of all the efficiency factors let me know.

**Comment by drklain** [comment]
OK so the problem isn’t that.  Somehow else the wrong range is thus being calculated, but I’m not sure why or how.

**Comment by adriankumpf** [comment]
Okay, regarding your initial concerns:

1. The deviation of the range is due to this: https://github.com/adriankumpf/teslamate/issues/143#issuecomment-528941200

2. I find the derived factor of ` .142` rather low. It's lower than the one used by the Model 3. Let's see how the estimation change after a few more charge sessions. Plus, it's important to know what your mileage is. I believe the battery degradation falsifies the measurement a bit.

**Comment by drklain** [comment]
I wonder if we have a problem because I'm displaying range in miles vs. kilometers?  IN response to your #143 comment, is there a way to force the grafana dashboards to use the other range numbers?

**Comment by adriankumpf** [comment]
You can change the units at any time via the web interface. Or if you want to override it for a particular dashboard you could update the dashboard variables.

**Comment by drklain** [comment]
I have the units selected as miles in the teslamate option and everything in grafana shows in miles.  I was just wondering if the incorrect TR range for the car was coming from a math error there...

**Comment by adriankumpf** [comment]
Nope, it just displaying the ideal range :)

**Comment by adriankumpf** [comment]
https://www.youtube.com/watch?v=eG2ZdYGDQOY

**Comment by drklain** [comment]
So instead of ideal, could we not display Typical (which is more realistic)?

**Comment by adriankumpf** [comment]
The different names are really confusing but that's exactly what I meant here https://github.com/adriankumpf/teslamate/issues/143#issuecomment-528941200

**Comment by drklain** [comment]
I see the referencd, but how do we shift from ideal to rated?  I don’t see an option to do so…

**Comment by adriankumpf** [comment]
> In  the medium term, **it will be possible to switch** from ideal to rated  range within TeslaMate. The rated range is already recorded. That means  you won't lose any data until then.

with rated range I'm referring to the `battery_range` from the [API](https://tesla-api.timdorr.com/vehicle/state/chargestate) which is the more realistic one your case. That is NOT possible at the moment.

Closing this ....

**Comment by drklain** [comment]
Understood.  I’ll look forward to the update!
