### ISSUE TITLE
Smoother management of geofences

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#150]
**Is your feature request related to a problem? Please describe.**
The new interface in /geo-fences/new is great. Being able to define a geofence interactively is a great feature. Unfortunately that does not work for editing, besides changing the radius.
Nevertheless it might be also helpful sometimes to input lat/long.
And one cannot add a geofence from inside Grafana.

**Describe the solution you'd like**
1. add lat/long to the /geo-fences/new screen and show changes to them in the map
2. allow editing also of the location when editing a geofence
3. Replace the Google Maps links in Grafana by links to /geo-fences/new
optional 4. add button in /geo-fences/new to jump to Google Maps.

**Describe alternatives you've considered**
This is just a feature idea / request.

**Additional context**
in Grafana e.g. in this screen:
![2019-09-06 15_43_32-Window](https://user-images.githubusercontent.com/8087682/64432685-4ebe4700-d0bd-11e9-9c5b-794f842a0c37.png)

**Comment by adriankumpf** [comment]
I like the third option in particular. 

Editing geo-fences is currently not allowed because it requires a few more things to be implemented but in the long term, of course, this would be nice to have.

I wonder what's the reason for 1. and 4.? Have you already discovered that there is a way to search for addresses / POIs?

**Comment by DrMichael** [comment]
1: well, no, I was just used to that..
4: just for convenience
3: oh, please, that would be great!!!!
2: umm, yes, thought so. But please keep that in mind for the future.

**Comment by DrMichael** [comment]
> I wonder what's the reason for 1. and 4.? Have you already discovered that there is a way to search for addresses / POIs?

Eh, yes, you can get the coordinates from Google Maps...

**Comment by adriankumpf** [comment]
Resolved by the latest commits on master :-)

**Comment by DrMichael** [comment]
Hoooray! Excellent. Perhaps worth mentioning somewhere (README?), that you have to set the base URL in the settings to a publicly accessible URL of teslamate?

**Comment by adriankumpf** [comment]
Yep, will do 👍 It should initialize the base URL on first start. Did that work in your case?

**Comment by DrMichael** [comment]
No, it didn't. I was thinking about it also. But which initial value are you setting?

**Comment by adriankumpf** [comment]
It uses the URL reported by `window.location.origin`. The call is triggered when visiting the home page / status screen for the first time after restarting.

**Comment by DrMichael** [comment]
Any chance to test it again, after I have set the base URL?

**Comment by adriankumpf** [comment]
Only by settings the `base_url` in the settings table to NULL. Afterwards visit the home page again. I'd be very interested to hear the results!

**Comment by DrMichael** [comment]
Ok, that did the job. Great work!
(might be, that I jumped earlier directly to the settings page...)

**Comment by adriankumpf** [comment]
Thanks! Good to know. Maybe I'll tweak that part a little.
