### ISSUE TITLE
Standalone Grafana support

### ISSUE THREAD

**Issue by Xe138** [adriankumpf/teslamate#151]
Is it possible to import the included grafana dashboards into a standalone instance of grafana?  I've been trying without success.

**Comment by adriankumpf** [comment]
Yep, that's possible. However, it makes the update process a bit more complicated. To manually import the dashboards follow the steps [here](https://github.com/adriankumpf/teslamate/wiki/Manual-Installation#importing-dashboards).

**Comment by Xe138** [comment]
I'm still having difficulty.  I have the datasource set up with the same name.  I can use that data to make my own dashboards, so I know it works.  When I import the provided dashboards, there is no datasource selected and the queries are the default "random walk".  Am I missing a step?

**Comment by adriankumpf** [comment]
Ah, gotcha! There is an open pull request: https://github.com/adriankumpf/teslamate/pull/146 

Can you explicitly select the data source for now?

**Comment by Xe138** [comment]
I can select it, but the queries are reset when I do.  I was trying to grab the queries out of the JSON, but that was tedious and I could never get it working.

**Comment by Xe138** [comment]
Just tested a dashboard from [andrewhunt12's pull request](https://github.com/andrewhunt12/teslamate) and it's working.  That looks like the fix.

**Comment by adriankumpf** [comment]
Yeah, that's quirk of Grafana. I'll try to review and merge the PR soon. Maybe use its modified dashboards in the meantime.
