### ISSUE TITLE
Stuck from 1 week

### ISSUE THREAD

**Issue by Willy8484** [adriankumpf/teslamate#1524]
**Describe the bug**
teslamate show "asleep from 1 week and 4 hours", despite using the car on a daily basis
i have no information from one week. i have my car stucked in a gps location that is change many many times until now.
I no have any kind of informaton updated. Charge, trips, etc.
I tried to restart doker many times, i tried to sign out and re sign in, i tried to reset api changing my tesla account password, i tried to update to the last version 1.22.00
Any of those doesn't work.

**Expected behavior**

i don't know why happen. sometimes happened in the past that miss some trips, but i resolved with docker restart.
The only thing different is that I have been pending the tesla software update for a month which I only ran today, but teslamate hasn't worked for more than a week.

**Relevant entries from the logs**

```

teslamate_1  | 2021-04-06 18:38:35.075 [info] Migrations already up
teslamate_1  | 2021-04-06 18:38:37.888 [info] Version: 1.22.0
teslamate_1  | 2021-04-06 18:38:38.837 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (880.944 ms)
teslamate_1  | 2021-04-06 18:38:39.625 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (787.492 ms)
teslamate_1  | 2021-04-06 18:38:39.627 [info] Refreshed api tokens
teslamate_1  | 2021-04-06 18:38:39.657 [info] Scheduling token refresh in 5 wk 5 d
teslamate_1  | 2021-04-06 18:38:39.670 [info] Running TeslaMateWeb.Endpoint with cowboy 2.8.0 at :::4000 (http)
teslamate_1  | 2021-04-06 18:38:39.672 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2021-04-06 18:38:39.895 [info] Starting logger for '******'
teslamate_1  | 2021-04-06 18:38:39.914 [info] MQTT connection has been established
teslamate_1  | 2021-04-06 18:38:40.192 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-04-06 18:38:41.432 [info] GET /
teslamate_1  | 2021-04-06 18:38:41.477 [info] Sent 200 in 44ms
teslamate_1  | 2021-04-06 18:38:54.641 [info] GET /
teslamate_1  | 2021-04-06 18:38:54.650 [info] Sent 200 in 8ms
teslamate_1  | 2021-04-06 18:39:01.549 [info] GET /
teslamate_1  | 2021-04-06 18:39:01.564 [info] Sent 200 in 14ms
teslamate_1  | 2021-04-06 18:39:01.586 [info] GET /
teslamate_1  | 2021-04-06 18:39:01.600 [info] Sent 200 in 14ms
teslamate_1  | 2021-04-06 18:39:14.890 [info] GET /
teslamate_1  | 2021-04-06 18:39:14.899 [info] Sent 200 in 8ms
teslamate_1  | 2021-04-06 18:39:21.477 [info] GET /
teslamate_1  | 2021-04-06 18:39:21.492 [info] Sent 200 in 15ms
teslamate_1  | 2021-04-06 18:39:30.541 [info] GET /
teslamate_1  | 2021-04-06 18:39:30.552 [info] Sent 200 in 11ms
teslamate_1  | 2021-04-06 18:39:35.519 [info] GET /
teslamate_1  | 2021-04-06 18:39:35.534 [info] Sent 200 in 14ms
teslamate_1  | 2021-04-06 18:39:42.716 [info] GET /
teslamate_1  | 2021-04-06 18:39:42.727 [info] Sent 200 in 11ms
teslamate_1  | 2021-04-06 18:39:42.798 [info] GET /
teslamate_1  | 2021-04-06 18:39:42.809 [info] Sent 200 in 11ms

```

**Environment**

- TeslaMate version: 1.22.0
- Type of installation: Docker
- OS TeslaMate is installed on: QNAP 653 PRO
- User OS & Browser: 
- Others:

**Comment by adriankumpf** [comment]
Maybe the API tokens expired?  With v1.21.2 and subsequent releases, many changes were needed because Tesla changed the authentication. See the [v1.21.2](https://github.com/adriankumpf/teslamate/releases/tag/v1.21.2) release notes: 

> > **⚠️ NOTE**: Any previously stored API refresh tokens will no longer function, as Tesla has deprecated the existing authentication endpoint. Existing access tokens will continue to work **until they expire**. Eventually, a full login will be needed to obtain new refresh tokens.
> >
> > **To immediately obtain new tokens after upgrading**, go to the TeslaMate settings page, **sign out via the button** at the bottom of the page and then sign in again.

In any case, the error cannot be narrowed down based on the logs. I would need the logs before you restarted.

**Comment by adriankumpf** [comment]
I'll close this until more information is available.
