### ISSUE TITLE
Do not display energy consumption data

### ISSUE THREAD

**Issue by aishlai** [adriankumpf/teslamate#1529]
Do not display energy consumption data

**Expected behavior**

show energy consumption data

**Relevant entries from the logs**
Attaching to teslamate_teslamate_1
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | 2021-04-09 04:50:55.883 [info] Migrations already up
teslamate_1  | 2021-04-09 04:50:58.982 [info] Version: 1.22.0
teslamate_1  | 2021-04-09 04:51:00.129 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (1087.941 ms)
teslamate_1  | 2021-04-09 04:51:03.780 [info] tzdata release in place is from a file last modified Tue, 22 Dec 2020 23:35:21 GMT. Release file on server was last modified Sun, 24 Jan 2021 19:35:23 GMT.
teslamate_1  | 2021-04-09 04:51:03.825 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (3695.102 ms)
teslamate_1  | 2021-04-09 04:51:03.825 [info] Refreshed api tokens
teslamate_1  | 2021-04-09 04:51:03.829 [info] Scheduling token refresh in 5 wk 5 d
teslamate_1  | 2021-04-09 04:51:03.831 [info] Running TeslaMateWeb.Endpoint with cowboy 2.8.0 at :::4000 (http)
teslamate_1  | 2021-04-09 04:51:03.833 [info] Access TeslaMateWeb.Endpoint at http://XXXXXXXXXXXX
teslamate_1  | 2021-04-09 04:51:05.196 [info] Starting logger for 'XXXXXXXXXXXX'
teslamate_1  | 2021-04-09 04:51:05.210 [info] MQTT connection has been established
teslamate_1  | 2021-04-09 04:51:05.915 [info] Tzdata has updated the release from 2020e to 2021a
teslamate_1  | 2021-04-09 04:51:07.441 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-04-09 04:53:53.347 [info] GET /
teslamate_1  | 2021-04-09 04:53:53.365 [info] Sent 200 in 17ms
teslamate_1  | 2021-04-09 04:54:09.781 [info] GET /settings
teslamate_1  | 2021-04-09 04:54:09.787 [info] Sent 200 in 5ms
teslamate_1  | 2021-04-09 04:54:25.892 [info] GET https://nominatim.openstreetmap.org/lookup -> 200 (912.658 ms)
teslamate_1  | 2021-04-09 04:54:37.316 [info] GET /settings
teslamate_1  | 2021-04-09 04:54:37.318 [info] Sent 200 in 1ms
teslamate_1  | 2021-04-09 04:54:40.137 [info] GET /
teslamate_1  | 2021-04-09 04:54:40.139 [info] Sent 200 in 1ms
teslamate_1  | 2021-04-09 04:54:40.439 [info] GET /
teslamate_1  | 2021-04-09 04:54:40.441 [info] Sent 200 in 1ms
teslamate_1  | 2021-04-09 04:59:57.915 [info] GET /
teslamate_1  | 2021-04-09 04:59:57.917 [info] Sent 200 in 1ms
teslamate_1  | 2021-04-09 04:59:59.183 [info] GET /settings
teslamate_1  | 2021-04-09 04:59:59.187 [info] Sent 200 in 4ms
teslamate_1  | 2021-04-09 05:40:51.703 car_id=1 [info] Start / :online
teslamate_1  | 2021-04-09 05:40:51.720 car_id=1 [info] Connecting ...
teslamate_1  | 2021-04-09 05:44:02.988 car_id=1 [info] Suspending logging

**Screenshots**

![image](https://user-images.githubusercontent.com/2181146/114124897-ff3e9d80-9927-11eb-86e4-1893d5f8d5e4.png)
![image](https://user-images.githubusercontent.com/2181146/114125724-98ba7f00-9929-11eb-9b52-31e03b30ee46.png)

**Data**

[data.zip](https://github.com/adriankumpf/teslamate/files/6283019/data.zip)

**Environment**

- TeslaMate version:  1.22.0
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu 20.04 VPS
- User OS & Browser: MacOS & Chrome
- Others: Tesla version 2021.4.12

**Comment by marteb** [comment]
Yep, I can confirm this issue. I'm also using TeslaMate 1.22.0 via Docker but on a RaspberryPi. Tesla software version ist 2021.4.12 as well.

**Comment by aishlai** [comment]
> Yep, I can confirm this issue. I'm also using TeslaMate 1.22.0 via Docker but on a RaspberryPi. Tesla software version ist 2021.4.12 as well.

Same bugs?

**Comment by marteb** [comment]
And it's gone. I haven’t changed anything but now it's working as it should. 🤷‍♂️

**Comment by aishlai** [comment]
> And it's gone. I haven’t changed anything but now it's working as it should. 🤷‍♂️

maybe some problem with tesla's api service

**Comment by adriankumpf** [comment]
The answer can be found here: [Why are no consumption values displayed in Grafana?#](https://docs.teslamate.org/docs/faq#why-are-no-consumption-values-displayed-in-grafana) 🙂
