### ISSUE TITLE
Drives missing

### ISSUE THREAD

**Issue by terasankka** [adriankumpf/teslamate#1533]
**Describe the bug**

Teslamate should log the drives automatically, but today I am missing all the drives from the afternoon

**How to reproduce it (as minimally and precisely as possible)**:
No Drives info for the last drives from today in Grafana

**Relevant entries from the logs**

```
Attaching to root_teslamate_1
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | 2021-04-12 10:29:32.745 [info] Migrations already up
teslamate_1  | 2021-04-12 10:29:36.712 [info] Version: 1.22.0
teslamate_1  | 2021-04-12 10:29:37.253 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (460.368 ms)
teslamate_1  | 2021-04-12 10:29:38.125 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (870.589 ms)
teslamate_1  | 2021-04-12 10:29:38.126 [info] Refreshed api tokens
teslamate_1  | 2021-04-12 10:29:38.137 [info] Scheduling token refresh in 5 wk 5 d
teslamate_1  | 2021-04-12 10:29:38.144 [info] Running TeslaMateWeb.Endpoint with cowboy 2.8.0 at :::4000 (http)
teslamate_1  | 2021-04-12 10:29:38.150 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2021-04-12 10:29:38.931 [info] Starting logger for 'X-Wing'
teslamate_1  | 2021-04-12 10:29:38.975 [info] MQTT connection has been established
teslamate_1  | 2021-04-12 10:29:39.790 car_id=1 [info] Start / :online
teslamate_1  | 2021-04-12 10:29:39.852 car_id=1 [info] Connecting ...
teslamate_1  | 2021-04-12 10:29:45.037 [info] GET /
teslamate_1  | 2021-04-12 10:29:45.051 [info] Sent 200 in 13ms
teslamate_1  | 2021-04-12 10:31:21.069 [info] GET /
teslamate_1  | 2021-04-12 10:31:21.087 [info] Sent 200 in 17ms
teslamate_1  | 2021-04-12 10:31:22.315 [info] GET /
teslamate_1  | 2021-04-12 10:31:22.335 [info] Sent 200 in 19ms
teslamate_1  | 2021-04-12 10:31:23.146 [info] GET /
teslamate_1  | 2021-04-12 10:31:23.153 [info] Sent 200 in 6ms
teslamate_1  | 2021-04-12 10:31:23.788 [info] GET /
teslamate_1  | 2021-04-12 10:31:23.803 [info] Sent 200 in 14ms
teslamate_1  | 2021-04-12 10:31:24.316 [info] GET /
teslamate_1  | 2021-04-12 10:31:24.323 [info] Sent 200 in 6ms
teslamate_1  | 2021-04-12 10:31:29.669 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  | 2021-04-12 10:32:05.446 [info] GET /settings
teslamate_1  | 2021-04-12 10:32:05.467 [info] Sent 200 in 20ms
teslamate_1  | 2021-04-12 10:36:16.594 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-04-12 10:36:16.594 car_id=1 [info] Creating new connection … 
teslamate_1  | 2021-04-12 10:36:16.594 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-04-12 10:36:16.605 car_id=1 [info] Connecting ...

```

**Screenshots**

**Data**
The last drives data is at 10:31 and I have driven after that: 

112007,1,105,2021-04-12 07:27:33.389,26,3,1,995.862067,,,,60,,,,,,,,,,,,
112010,1,105,2021-04-12 07:27:35.39,26,2,1,995.862067,,,,60,,,,,,,,,,,,
112017,1,105,2021-04-12 07:27:40.14,26,3,1,995.862067,,,,60,,,,,,,,,,,,
112041,1,105,2021-04-12 07:28:16.184,26,3,6,995.862067,,,,60,,,,,,,,,,,,
112055,1,105,2021-04-12 07:28:20.434,26,5,2,995.862067,,,,60,,,,,,,,,,,,
112062,1,105,2021-04-12 07:28:23.434,27,5,1,995.862067,,,,60,,,,,,,,,,,,
112027,1,105,2021-04-12 07:27:46.14,26,0,1,995.862067,,,,60,,,,,,,,,,,,
112045,1,105,2021-04-12 07:28:17.184,26,5,3,995.862067,,,,60,,,,,,,,,,,,
112052,1,105,2021-04-12 07:28:19.434,26,6,1,995.862067,,,,60,,,,,,,,,,,,
112061,1,105,2021-04-12 07:28:22.934,27,5,1,995.862067,,,,60,,,,,,,,,,,,
112070,1,105,2021-04-12 07:28:29.949,,0,1,995.861047,319.49,308.09,319.49,60,60,,f,f,20.5,10.0,3,20.5,20.5,t,f,f
112072,1,,2021-04-12 07:31:51.71,,,0,995.861047,319.49,308.09,319.49,60,60,,f,f,18.3,10.0,0,20.5,20.5,f,f,f
112080,1,,2021-04-12 08:34:13.903,,,0,995.861047,318.71,307.35,318.71,60,60,,f,f,13.6,13.5,0,20.5,20.5,f,f,f
112051,1,105,2021-04-12 07:28:19.123,,6,1,995.850047,319.49,308.09,319.49,60,60,,f,f,20.5,10.0,3,20.5,20.5,t,f,f
112066,1,105,2021-04-12 07:28:25.684,27,2,1,995.862067,,,,60,,,,,,,,,,,,
112078,1,,2021-04-12 08:23:59.822,,,0,995.861047,318.71,307.35,318.71,60,60,,f,f,13.7,13.5,0,20.5,20.5,f,f,f
112068,1,105,2021-04-12 07:28:26.684,27,0,1,995.862067,,,,60,,,,,,,,,,,,
112075,1,,2021-04-12 08:09:10.98,,,0,995.861047,318.71,307.35,318.71,60,60,,f,f,14.3,13.5,0,20.5,20.5,f,f,f
112079,1,,2021-04-12 08:29:07.023,,,0,995.861047,318.71,307.35,318.71,60,60,,f,f,13.6,13.5,0,20.5,20.5,f,f,f
112083,1,,2021-04-12 08:46:32.786,,,0,995.861047,317.19,305.87,317.19,60,59,,f,f,15.8,13.5,0,20.5,20.5,f,f,f
112084,1,,2021-04-12 09:17:05.719,,,0,1006.195047,307.22,301.29,307.22,58,58,,f,f,20.5,9.5,0,20.5,20.5,f,f,f
112081,1,,2021-04-12 08:38:50.385,,,0,995.861047,318.71,307.35,318.71,60,60,,f,f,13.5,13.5,0,20.5,20.5,f,f,f
112087,1,,2021-04-12 10:29:39.074,,,0,1010.667049,301.09,302.25,301.09,57,56,,f,f,20.2,7.5,0,20.5,20.5,f,f,f
112088,1,,2021-04-12 10:31:28.939,,,0,1010.667049,301.09,302.25,301.09,57,56,,f,f,20.7,7.5,0,20.5,20.5,f,f,f

**Environment**

- TeslaMate version: Newest
<img width="1687" alt="Screenshot 2021-04-12 at 13 42 20" src="https://user-images.githubusercontent.com/49198341/114382338-eedf2a80-9b94-11eb-938a-0672c3b7951a.png">

- Type of installation: Docker
- OS TeslaMate is installed on: DietPi

**Comment by adriankumpf** [comment]
Do you have more information about this? The logs only cover a period of 7 minutes. This is not enough if your trips took place in the afternoon.

**Comment by chatcat100** [comment]
I'm having some issues after an update (to support captcha) that drives seem to be suddenly missing large portions of the drive after months of pretty solid capture. How do I capture the logs you would need?

**Comment by adriankumpf** [comment]
> I'm having some issues after an update (to support captcha) that drives seem to be suddenly missing large portions of the drive after months of pretty solid capture. How do I capture the logs you would need?

The process is outlined here: https://github.com/adriankumpf/teslamate/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by adriankumpf** [comment]
Closing this until more information is provided.
