### ISSUE TITLE
Proposed: regen vs braking

### ISSUE THREAD

**Issue by MarcFinns** [adriankumpf/teslamate#1541]
This is a proposed feature, not sure how to do it apart from opening a bug...

The idea came after a heated conversation with some naysayers about the fact that with a Tesla brakes are used hardly ever. I was wondering whether it is possible to display the use of brakes vs regen. It might not be available from APIs, but perhaps it can be inferred?

**Describe the bug**

**Expected behavior**

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by adriankumpf** [comment]
Feature suggestions belong here: [💡 Ideas](https://github.com/adriankumpf/teslamate/discussions/categories/ideas)
