### ISSUE TITLE
Teslamate records 2phases on 11kw AC charging, should be 3

### ISSUE THREAD

**Issue by fzahn** [adriankumpf/teslamate#1545]
Hi,

when I look into the "Charge details" dashboard, I can see, that Teslamate records charging with 2 phases, but it should be three. I do not know, if this is a bug of Teslamate or of the Tesla-API.

Regards,
Florian

**Comment by adriankumpf** [comment]
If in doubt, opening a [discussion](https://github.com/adriankumpf/teslamate/discussions) first is right approach.

For this specific issue see the existing issues/questions, e.g. this one: https://github.com/adriankumpf/teslamate/issues/414
