### ISSUE TITLE
Vehicle reset causes location shift to Tesla HQ

### ISSUE THREAD

**Issue by kingppeb** [adriankumpf/teslamate#1550]
**Describe the bug**

When a vehicle is factory reset the location defaults to Tesla HQ until the car has been driven enough to allow it to pick up the correct location 

**Expected behavior**

Ideally an option in the UI when this location is picked up to clear it from the database so as not to skew teslamate data

**How to reproduce it (as minimally and precisely as possible)**:

1. Factory reset the vehicle attached to teslamate
2. Check back into teslamate 
3. See that the API is now showing the location as Tesla HQ
4. View teslamate to see that location data is showing as Tesla HQ
-->

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by wooter** [comment]
This is not a bug on Teslamate's level, and a solution is available in the documentation: https://docs.teslamate.org/docs/maintenance/manually_fixing_data

**Comment by larskochhansen** [comment]
I have the same problem. I followed the intructions mentioned by @wooter and deleted the drive/charge in palo alto, but the visited maps still looks crazy (which kind of ruins the overview - check attached overview - my country is marked in orange 😁).

I really hope that this is possible to fix.
![Skærmbillede 2021-04-18 kl  19 00 24](https://user-images.githubusercontent.com/17578995/115153905-78e93080-a078-11eb-9297-d7252bd8b7e8.png)

**Comment by ddjj181** [comment]
Same issue here, deleted drive/address, restarted docker, still showing this crazy straight line, am I missing anything in the database? would be good to have an option to delete it in web interface, thanks

**Comment by adriankumpf** [comment]
You can find all entries with a location near the Tesla HQ with the following SQL query:

```sql
SELECT *
FROM positions
WHERE 
  earth_distance(
    ll_to_earth(latitude, longitude), 
    ll_to_earth(37.394229560763236, -122.1502025306691)
  ) < 10000
```

To run it, connect to the database as described in the link above. If you really wan to delete the entries, replace `SELECT *` with `DELETE`.

**Comment by larskochhansen** [comment]
I've tried the suggested solution (see attached) but the problem remains. As if the "visited map" gets its data somewhere else :) 

![Skærmbillede 2021-05-17 kl  17 40 39](https://user-images.githubusercontent.com/17578995/118517220-51e55380-b737-11eb-8e30-956786f205af.png)

**Comment by DrMichael** [comment]
Is there a ";" missing at the end perhaps?

**Comment by larskochhansen** [comment]
> Is there a ";" missing at the end perhaps?

Thank you very much... I ran the
`DELETE
FROM positions
WHERE 
  earth_distance(
    ll_to_earth(latitude, longitude), 
    ll_to_earth(37.394229560763236, -122.1502025306691)
  ) < 10000;`

... and now the "TESLA HQ" has disappeared. THANK you very much 👍

**Comment by ddjj181** [comment]
> Is there a ";" missing at the end perhaps?

worked like a charm, thanks

**Comment by DrMichael** [comment]
@kingppeb Please close this...

**Comment by kingppeb** [comment]
Closer as per above

**Comment by kingppeb** [comment]
>
