### ISSUE TITLE
Consider using postgres:13-alpine image in docs for reduced bloat

### ISSUE THREAD

**Issue by angryziber** [adriankumpf/teslamate#1563]
**Describe the bug**

Not really a bug, but a suggestion.
Also, both docker-compose.yml files could be in git.

**Expected behavior**

```
postgres              13-alpine           e43172f9204f        10 days ago         160MB
postgres              13                  26c8bcd8b719        2 weeks ago         314MB
```

**Comment by adriankumpf** [comment]
Pull requests are welcome! I'll move this to [Ideas 💡](https://github.com/adriankumpf/teslamate/discussions/categories/ideas).
