### ISSUE TITLE
Error / :unkown

### ISSUE THREAD

**Issue by espenu** [adriankumpf/teslamate#157]
For some reason I get "`teslamate_1  | 20:49:39.157 car_id=1 [warn] Error / :unknown`" every 30 seconds. I'm not getting any new data from the car in the web interface. It has been like this since yesterday.

Running version v1.8.0

Any ideas on what could be wrong?

**Comment by adriankumpf** [comment]
This may sound too obvious but have you tried to restart the `teslamate` container to see if the error disappears / changes?

**Comment by espenu** [comment]
That was the first thing I tried, but it did not help. However, since you mentioned it, I now tried again. And I now got a sign in error. Signed in again and now it works fine :-). I have no idea why restarting the second time helped..

**Comment by sascha-egerer** [comment]
I've got the same error. Lost some days of data :-/
