### ISSUE TITLE
Drive details duration rounds down and is misleading

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#1584]
I went on a drive today - nearly 2 hours, but when the drive details shows this - it seems to just use the 'hour' component and not the minutes and displays that. This should be more precise and show the complete duration. As shown in the screenshot the time shows this was an hour and forty minutes.

I am on the latest release of Teslamate (1.22.0).

![image](https://user-images.githubusercontent.com/3529468/116767282-12530380-a9e4-11eb-9d99-8181c7cce016.png)

Thanks!

**Comment by Dulanic** [comment]
PR in place to correct.
