### ISSUE TITLE
Raspberry pi 1b

### ISSUE THREAD

**Issue by Try2Fly** [adriankumpf/teslamate#160]
Would this also work on a rapberry pi 1b? I have some collecting dust, so this would be a great application. Also how big is the data that is collected?

**Comment by adriankumpf** [comment]
Yeah, that should work. A lot of data is collected over time. But it should not take up too much space.

**Comment by michaeltal** [comment]
> Would this also work on a rapberry pi 1b? I have some collecting dust, so this would be a great application. Also how big is the data that is collected?

So far I've been unable to get it to work on a pi 1b. But I guess my failure has more to do with me being a Linux/Docker noob.

What did I try?
1) Running it on an [https://blog.hypriot.com/](https://blog.hypriot.com/) image --> Docker containers wouldn't start up properly
2) I then set up a new Raspbian image on which docker would't even install.
3) Got it up and running on a virtual Ubuntu machine though. (Hosted on Azure, not on the Pi)

If you are more successful than me, I'd be very much interested to learn about your setup process.

**Comment by krezac** [comment]
I don't think docker runs on raspi 1 (some cpu features missing). But don't take it for granted ;)
you should be able to make in run "on metal", though. You may also hit memory size.

In general, I'd dump it and buy raspi 3 (I also have couple of 1's catching dust at home. But they are slow, power hungry and so...

**Comment by adriankumpf** [comment]
@krezac is right. The model 1's and Zeros have the ARMv6 architecture. There are no base images for that architecture. That's why TM cannot support it, unfortunately. But as mentioned, manual installation should still be possible.

**Comment by michaeltal** [comment]
Thanks for your input! 
Yeah, just getting a newer Pi also would have been my next step :)
