### ISSUE TITLE
Add support for automatic cost for charging

### ISSUE THREAD

**Issue by waylonis** [adriankumpf/teslamate#1619]
**Describe the bug**

Teslamate doesn't automatically calculate the cost for charges. It would be great if it did.

**Expected behavior**

In the Settings, it would be nice to add support for two styles of charging:
1. Constant cost charging (e.g., same $/KWH)
2. Time of use charging (e.g., $/KWH changes during the day). Typically there's one time range for one cost, and then another cost outside that range.

**How to reproduce it (as minimally and precisely as possible)**:

Add the charging style to settings. I think a radio buttons with two options: Fixed cost and Time-of-use cost. The first will just provide a text field to enter the cost. The second would have three text fields: start time, end time, and cost

**Comment by bikeymouse** [comment]
Have you seen that the session-cost and per kWh-cost settings can already be made in the Geofence edit screen? 
So you just have to make a Geofence for all the locations where you are charging.

**Comment by waylonis** [comment]
@bikeymouse Thanks for the response! I didn't know about that. It's a really good solution and should take care of my needs. I'm going to close the issue.
