### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Sebbo69** [adriankumpf/teslamate#162]
I have one more request and several questions. Could you describe the creation of password etc. in the Wiki even more exactly? I did not understand it. Or can I make the wake-up call over another port?

How can I back up data? Is it possible to take over more choices from Teslalogger?

**Comment by adriankumpf** [comment]
Are you referring to the "Manual Installation" article in the wiki? Which password do you mean? To get started quickly I'd recommend using the docker-compose setup described in the README. With it you only need to change the `VIRTUAL_HOST` variable.

Backing up data can be done by dumping the whole database e.g. with `pg_dump` or `pg_dumpall`.

TeslaMate's database schema is different from TeslaLogger's. But they don't differ too much. There is no migration script yet. Someone would have to write one.

**Comment by Sebbo69** [comment]
Es läuft alles. Es geht um Passwortschutz von außen.

**Comment by adriankumpf** [comment]
Okay. Für welches Setup hast du dich jetzt entschieden? Sind noch Fragen offen?

**Comment by Sebbo69** [comment]
Oh, hab ich in deutsch geantwortet. Also es läuft jetzt docker compose. Aber ich würde gerne den weckruf von aussen erreichen können ohne das System zu öffnen. Oder irgendwie mit Passwort. Aber ich verstehe den Ablauf der im Wiki erklärt ist nicht.

**Comment by adriankumpf** [comment]
Um TM von Außen passwortgeschützt erreichbar zu machen, brauchst du eine eigene Domain, für die du dir dann mit Let's Encrypt ein kostenloses Zertifikat holen kannst. Dann braucht es noch einen "reverse-proxy" (das ist der `proxy` Part im Wiki), der für die Terminierung des verschlüsselten Traffics sowie für den Passwortschutz zuständig ist.

Das _docker-compose_ File im Wiki macht das quasi alles für dich. Es müssen nur noch die Variablen in der  _.env_  Datei angepasst werden. Die wichtigste Voraussetzung ist aber wie gesagt, die vorhandene Domain.

**Comment by Sebbo69** [comment]
Danke, soweit habe ich es auch verstanden. Domain usw ist auch vorhanden. Aber welche ports müssen dafür geöffnet werden? Bekomme mit dem fertigen setup Fehler.

**Comment by Sebbo69** [comment]
Danke, soweit habe ich es auch verstanden. Domain usw ist auch vorhanden. Aber welche ports müssen dafür geöffnet werden? Bekomme mit dem fertigen setup Fehler.

**Comment by adriankumpf** [comment]
Wenn alles soweit läuft, müsste nur noch eine Portweiterleitung auf `80` und `443` erstellt werden.

**Comment by Sebbo69** [comment]
Okay, versuche ich heute abend nochmal. Könnte ich die ports auch ändern?

Großes Danke! Bin von teslalogger gewechselt weil schlafen nahezu nicht mehr geklappt hat ohne das ich teslalogger neu gestartet hab. Leider bin ich damit schon 20.000km gefahren und hatte die Daten gerne gehabt... 

Spende kommt.

**Comment by adriankumpf** [comment]
Jo, die Ports kannst du beliebig ändern. Im `docker-compose` einfach den Teil hier anpassen (jeweils den ersten Part, vor dem `:`):

```YAML
  ports:
      - 80:80
      - 443:443
```

Ja, ich hätte auch gerne eine Möglichkeit, Daten aus verschiedenen Quellen zu importieren. Vielleicht geht das ja jemand in Zukunft an.
Alternativ kannst du ja die bestehenden Daten weiter nutzten bspw. mit einer zweiten "data source" in Grafana. Damit ließe sich zwischen alten und neuen Daten hin- und herschalten.

Danke dir!

**Comment by Sebbo69** [comment]
Kannst du mir vielleicht genauer erklären wie ich die Datenbank sichern kann? Wo gebe ich den Befehl ein. Und wie spiele ich es auf einem anderen Raspi wieder ein? Mit welchem Befehl?

Danke für die Hilfe!

**Comment by adriankumpf** [comment]
Das hat eigentlich nichts mit TM zu tun. Docker macht den Prozess aber zugegebenermaßen etwas indirekter. Such mal nach "docker postgres backup" o.Ä. So stößt man z.B. hier drauf:

https://stackoverflow.com/questions/24718706/backup-restore-a-dockerized-postgresql-database/29913462#29913462
