### ISSUE TITLE
Feature request: combine short stationary charges into a single line/session?

### ISSUE THREAD

**Issue by bikeymouse** [adriankumpf/teslamate#1623]
Hi, 
I'm using TWCManager to charge my car with Solar energy.  On a cloudy day this means that the charging can be started and stopped a couple times during a charging session.

This causes the Charges report in Teslamate to show a lot of individual charges:
<img width="1353" alt="charges" src="https://user-images.githubusercontent.com/34967010/118285329-9f608700-b4d1-11eb-814d-1e1dd9028253.png">

So the question is, could these be combined into 1 single line in the Charges-report and into 1 single Charge-details report, based on the fact that the car was stationary and was plugged-in all the time? 

That would make the Charges-overview much more comprehensive and also would help to see in the Charge-details report what the totals for that "single session" are.

**Comment by adriankumpf** [comment]
Feature requests belong here: [💡 Ideas](https://github.com/adriankumpf/teslamate/discussions/categories/ideas). I'll move it.
