### ISSUE TITLE
[Question] What is range typical/est?

### ISSUE THREAD

**Issue by scottismyname** [adriankumpf/teslamate#163]
Mine seem to be off by quite a bit.  For instance, right now I show:

(Model 3)

Range (typical) | 145.3 mi
Range (est.) | 184.7 mi

**Comment by adriankumpf** [comment]
What's your reference value? All range values come straight from the API.

> **Rated Range**  The car's estimate of remaining range based on a fixed energy consumption in Watt-hours/mile (whpm). The fixed whpm is different for different vehicles and in different markets based on the regulatory test for that vehicle in that market.
> 
> **Estimated Range**  The car's predicted remaining range based on energy consumption during recent driving. This is based on a dynamic Watt-hours/mile value that is based on recent driving habits. This is not country-specific.
> 
> **Ideal Range**  The car's estimate of remaining range based on a fixed energy consumption in Watt-hours/mile (whpm) at a specified average speed. The fixed whpm is a figure determined by Tesla and is not country specific. The average speed is a figure determined by Tesla and is not country specific.

The typical range means "ideal" here.

**Comment by scottismyname** [comment]
Thanks for the great explanation!
