### ISSUE TITLE
Cost on trip dashboard shows costs from other car(s)

### ISSUE THREAD

**Issue by alexeiw123** [adriankumpf/teslamate#1641]
**Describe the bug**

With more than one vehicle available on the account, the trip dashboard for an individual car is showing charging costs from other vehicles that charge during the trip times.

**Expected behavior**

Charge costs should be limited to the vehicle that is being reported on.

**How to reproduce it (as minimally and precisely as possible)**:

1. Drive car A
2. Charge car B while car A is driving
3. Go to trips dashboard
4. See charge costs showing for car A, due to car B charging session

**Screenshots**

![image](https://user-images.githubusercontent.com/77809797/119419413-8e1f4200-bd3d-11eb-8bec-87679a00f8a1.png)

![image](https://user-images.githubusercontent.com/77809797/119419423-95465000-bd3d-11eb-9cf4-2703e35ba680.png)

**Environment**

- TeslaMate version: 1.22.0
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian GNU/Linux 10 (buster)
- User OS & Browser: Windows 10 - chrome

**Comment by DrMichael** [comment]
Yes, there is a " AND car_id = $car_id" missing for Cost...
