### ISSUE TITLE
Installed version displayed twice in the Updates dashboard

### ISSUE THREAD

**Issue by fatbasstard** [adriankumpf/teslamate#1648]
Got my latest version in the Updates overview twice:

![image](https://user-images.githubusercontent.com/35613489/119636951-6f8c7a00-be15-11eb-93ef-998b48af9a47.png)

**Comment by fatbasstard** [comment]
Got a new version pending `2021.4.18` so that might be in the way

**Comment by fatbasstard** [comment]
Ah, actually have 2 entries in the database:

```
29	2021-05-21 17:55:58	2021-05-21 17:56:18	2021.4.15.12 c65e2c0ab1ff	1
28	2021-05-21 17:55:58	2021-05-21 17:55:58	2021.4.15.12 c65e2c0ab1ff	1
```

**Comment by adriankumpf** [comment]
Interesting. It is not supposed to be possible that two identical entries are created. If someone is experiencing the same problem, the logs at the time of the update would be helpful.

**Comment by tobiasehlert** [comment]
> Interesting. It is not supposed to be possible that two identical entries are created. If someone is experiencing the same problem, the logs at the time of the update would be helpful.

@adriankumpf,
this happened to me when I initially setup my TeslaMate installation.. but I just removed the faulty entry and it never happened again.

> ```
> 29	2021-05-21 17:55:58	2021-05-21 17:56:18	2021.4.15.12 c65e2c0ab1ff	1
> 28	2021-05-21 17:55:58	2021-05-21 17:55:58	2021.4.15.12 c65e2c0ab1ff	1
> ```

@fatbasstard,
just remove the entry with ID 28 and it should look good again 👍

**Comment by adriankumpf** [comment]
I am temporarily closing this until more information is available or someone else reports back with this bug.
