### ISSUE TITLE
Column headers missing

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#165]
On my iPad I’ve tried viewing several of the graphs in Safari and Chrome. I’m not able to see the column names/headers.

![F6A1919C-23B7-4752-9A5D-DC4B6CE08FCF](https://user-images.githubusercontent.com/19696424/64915637-59618780-d720-11e9-9ed3-88b55281755b.jpeg)

Is there a way around this?

**Comment by cwanja** [comment]
I think this is an issue of Grafana not supporting mobile devices (smaller screens) the best. I have the same issues.

**Comment by adriankumpf** [comment]
Yep, there are a couple of bugs related to Grafana e.g. https://github.com/grafana/grafana/issues/16005

**Comment by lignumaqua** [comment]
Safari in iPadOS 13.1 fixes this issue as Safari now is seen as and behaves like a desktop browser.

**Comment by natrlhy** [comment]
Good to know! Thanks!

**Comment by Gauravshah** [comment]
the problem persists on iphone atleast. even on iOS 13.1.x

**Comment by cleanev** [comment]
Problem persists in iPadOS 13.4 & 13.5
