### ISSUE TITLE
Lost connection and logging in gives Error: :mfa_input_not_found

### ISSUE THREAD

**Issue by chatcat100** [adriankumpf/teslamate#1651]
Stopped logging four days ago. All attempts to login now give

"Error: :mfa_input_not_found"

* Enabling and Disabling MFA in tesla.com produces same error
* Used Tesla Auth App to get API and Refresh key - returns invalid key error.

**Comment by chatcat100** [comment]
Version 1.22.0

**Comment by Powerbook001** [comment]
Same to me, happened today

**Comment by DariBer** [comment]
same to me, didn't have this problem before

**Comment by alexsapran** [comment]
Just found the project and tried to use it and faced the same issue, at some forums, I show people reporting that they disable/enabled the MFA on their Tesla accounts, and then later it worked. I tried doing the same but I keep getting this error.

**Comment by chatcat100** [comment]
> Just found the project and tried to use it and faced the same issue, at some forums, I show people reporting that they disable/enabled the MFA on their Tesla accounts, and then later it worked. I tried doing the same but I keep getting this error.

Same. Hence why I tried enable/disable. It certainly seems like it has something to do with the evolution of the Tesla API that they are rolling out.

**Comment by adriancleung** [comment]
Error is because Tesla implemented a captcha to the authentication flow that would break every third-party services. Until developers can bypass/work with the captcha, every service will face similar issues with logging in unfortunately.

**Comment by Powerbook001** [comment]
This means that we can forget Teslamate?

**Comment by alexsapran** [comment]
> Error is because Tesla implemented a captcha to the authentication flow that would break every third-party services. Until developers can bypass/work with the captcha, every service will face similar issues with logging in unfortunately.

Have you got any references for this, if that's the case from what I understand no one will be able to use any other service, similar like `teslascope`, `teslafi`, ... etc ... which seems a bit strange to me, I am new to this Tesla API stuff, it can be the case indeed but It seems to be strange, that's all.

Initially, I saw a PR [fixing a typo](https://github.com/adriankumpf/teslamate/pull/1571) in the auth process which was a eureka moment, but after trying the `1.23.0-dev` version I got the same issue, so indeed it seems as not related to the app itself.

**Comment by denouche** [comment]
Same thing for my in my Android app, users raise me login fail problem since today.

**Comment by kongomongo** [comment]
https://twitter.com/ycorsair/status/1398160096325111808?s=20

**Comment by adriancleung** [comment]
> > Error is because Tesla implemented a captcha to the authentication flow that would break every third-party services. Until developers can bypass/work with the captcha, every service will face similar issues with logging in unfortunately.
> 
> Have you got any references for this, if that's the case from what I understand no one will be able to use any other service, similar like `teslascope`, `teslafi`, ... etc ... which seems a bit strange to me, I am new to this Tesla API stuff, it can be the case indeed but It seems to be strange, that's all.
> 
> Initially, I saw a PR [fixing a typo](https://github.com/adriankumpf/teslamate/pull/1571) in the auth process which was a eureka moment, but after trying the `1.23.0-dev` version I got the same issue, so indeed it seems as not related to the app itself.

Proof:
https://github.com/mseminatore/TeslaJS/issues/247
https://github.com/timdorr/tesla-api/issues/392 (not sure why it's closed)
And personal experience with authentication flow and captcha?

**Comment by alexsapran** [comment]
Thanks, @adriancleung 🙇🏼

**Comment by joepalexander** [comment]
Such a shame. As a solo developer utilising the unofficial API, this has ruined a long-term project of mine

**Comment by Powerbook001** [comment]
If you use API token to access, it's working fine

**Comment by joepalexander** [comment]
> If you use API token to access, it's working fine

can you help me to generate an API token? a bit rusty on this atm

**Comment by adriancleung** [comment]
> > If you use API token to access, it's working fine
> 
> can you help me to generate an API token? a bit rusty on this atm

If you have iOS, you can use the [Auth app for Tesla](https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613#?platform=iphone). You're accepting the risk of using these third-party services.

**Comment by joepalexander** [comment]
> > > If you use API token to access, it's working fine
> > 
> > 
> > can you help me to generate an API token? a bit rusty on this atm
> 
> If you have iOS, you can use the [Auth app for Tesla](https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613#?platform=iphone). You're accepting the risk of using these third-party services.

Does this bypass the captcha?

**Comment by adriancleung** [comment]
> > > > If you use API token to access, it's working fine
> > > 
> > > 
> > > can you help me to generate an API token? a bit rusty on this atm
> > 
> > 
> > If you have iOS, you can use the [Auth app for Tesla](https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613#?platform=iphone). You're accepting the risk of using these third-party services.
> 
> Does this bypass the captcha?

Does not bypass captcha but uses a webview in the app to sign in directly through Tesla's auth server and then captures the access token and refresh token.

**Comment by joepalexander** [comment]
> > > > > If you use API token to access, it's working fine
> > > > 
> > > > 
> > > > can you help me to generate an API token? a bit rusty on this atm
> > > 
> > > 
> > > If you have iOS, you can use the [Auth app for Tesla](https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613#?platform=iphone). You're accepting the risk of using these third-party services.
> > 
> > 
> > Does this bypass the captcha?
> 
> Does not bypass captcha but uses a webview in the app to sign in directly through Tesla's auth server and then captures the access token and refresh token.

I'll give this a go by writing a script and trying to catch the tokens. thanks!

**Comment by Powerbook001** [comment]
this app works fine and generates a correct API, but will last for juts more than a month.
Then you will have ti renew it.

**Comment by joepalexander** [comment]
It just concerns me giving a third party the token. Don't really want someone gaining access to the company fleet!

**Comment by chatcat100** [comment]
> If you use API token to access, it's working fine

Was that with the IOS Tesla App? The API Key and Return Key it has seem huge compared to what is stored in my teslamate pgsql. Using the Teslamate web page or directly dropping them in didn't seem to work. Do you have MFA on or off in Tesla.com?

**Comment by chatcat100** [comment]
Confirmed I can now login with the API login.

**Comment by joepalexander** [comment]
> Confirmed I can now login with the API login.

How did you manage to do this?

**Comment by basmeerman** [comment]
Using Auth App for Tesla you can generate api tokens and use them to login.

Op zo 30 mei 2021 om 03:13 schreef joepalexander ***@***.***>

**Comment by chatcat100** [comment]
For those using the Auth App for Tesla realize the results it gives you are BACKWARDS. It gives you the Return Key and then API Key but the login page on Teslamate wants API Key followed by return key. Don't reverse them as I did... for several hours =(

**Comment by alexsapran** [comment]
So from what I can understand the current situation is that, either buy an iPhone so that I can use the `Auth app for Tesla` or wait until someone creates something for Android, or Tesla removes the captcha.
This is sad :(

**Comment by Powerbook001** [comment]
Try and check if this app is also for Android

Authla

**Comment by alexsapran** [comment]
> Try and check if this app is also for Android
> 
> Authla

I tried but my Android store -fu did not reveal anything.

**Comment by stu073** [comment]
SOLVECAPTCHA.com api also works well to solve the captcha. You will need an account with solvecaptcha and they do charge for each solve but its <$1 for every 1000 captcha requests...pretty minor.

**Comment by henryhm0** [comment]
API token working fine with me. I used AuthAppForTesla

**Comment by adriankumpf** [comment]
Version [v1.23.0](https://github.com/adriankumpf/teslamate/releases/tag/v1.23.0) is out and supports the new captcha verification. 

I'm going to close this one. For the discussion around the new release there is this thread: [v1.23.0](https://github.com/adriankumpf/teslamate/discussions/1653)

**Comment by JudgeDreddKLC** [comment]
@adriankumpf just wanted to let you know that I think this issue came back. I'm a brand new tesla owner and had the same error, I'm running teslamate 1.24.0. I was able to get in using "auth for tesla" app

**Comment by adrianmace** [comment]
@adriankumpf I've just deployed Teslamate for the first time and am noticing the same thing.

`teslamate/teslamate:latest` docker container.

**Comment by RasCav** [comment]
@adriankumpf I think that I'm facing the same issue, MFA is currently active in my profile, but I can't log in.

**Comment by prog1407** [comment]
Installed teslamate and enabled MFA. Receiving the same error as above...
