### ISSUE TITLE
Connect to own MQTT broker

### ISSUE THREAD

**Issue by Try2Fly** [adriankumpf/teslamate#166]
I have an seperate MQTT broker running on Home Assistant. Is it also possible to connect to this broker? And how? should I just insert its IP after "- MQTT_HOST=" and add user and password?

**Comment by virtualm2000** [comment]
I'm using my own MQTT broker. As per instructions you need to set:

MQTT_HOST
MQTT_USERNAME 
MQTT_PASSWORD

**Comment by Try2Fly** [comment]
Ok thanks,

I added the IP of my broker after MQTT_USERNAME and added user and password and that worked

**Comment by chilman408** [comment]
> d

Hello, 

Sorry to bother you but how to make these changes?

**Comment by jun3280net** [comment]
@chilman408 @Try2Fly would you mind sharing your setup?  I'm looking to connect to my Home Assistant MQTT server.  Thanks

**Comment by lolento** [comment]
> @chilman408 @Try2Fly would you mind sharing your setup? I'm looking to connect to my Home Assistant MQTT server. Thanks

You have to edit your docker-compose.xml to point to your MQTT Broker on your HomeAssistant.  Assuming that is running.  Just like Virtualm2000's instructions
