### ISSUE TITLE
Show additional state info on the "states" dashboard?

### ISSUE THREAD

**Issue by sbeaudette** [adriankumpf/teslamate#168]
The localhost:4000 web interface shows some useful info about the current state of the car.  Is it possible to include this same info within the "states" grafana dashboard?

**Comment by adriankumpf** [comment]
The basic idea of the Grafana dashboards is to display historical data. What is shown on the web interface is therefore not stored in the database and cannot be shown within the "states" dashboard.

I think it's possible to display an iframe with the web interface within Grafana. But I haven't tried that yet.
