### ISSUE TITLE
JSON format MQTT messages

### ISSUE THREAD

**Issue by Try2Fly** [adriankumpf/teslamate#169]
I'm using Home Assistant, and it would be nice to view the status of my tesla on my home assistant.
I can use MQTT to share the data with Home Assistant, however the data need to be in a JSON format. Would it be possible to also have a topic with all info in a JSON format?

**Comment by adriankumpf** [comment]
You don't need JSON for that :) Take a look at this part of my Home Assistant configuration:  

https://github.com/adriankumpf/HomeAssistant-Config/blob/master/config/includes/sensors/teslamate.yaml

**Comment by Try2Fly** [comment]
Oh Wow, thanks for that! Will do a straight copy paste!
I wasn’t aware that you can just take the value, the home assistant docs clearly say it must be in JSON format. Learned something today!
