### ISSUE TITLE
Grafana Headers Don't Scroll Horizontally

### ISSUE THREAD

**Issue by tcm0116** [adriankumpf/teslamate#1694]
Using version 1.22.0, the take headers in Grafana's mobile view don't scroll with the data. I believe it may be [this issue](https://github.com/grafana/grafana/issues/4157)  that should be resolved by using an updated table panel.

**Comment by adriankumpf** [comment]
Yup, this is a known issue. However, we cannot migrate to new table component is blocked until this is implemented: https://github.com/grafana/grafana/issues/24092
