### ISSUE TITLE
Docker Manifest for Windows Server 2016

### ISSUE THREAD

**Issue by injector22** [adriankumpf/teslamate#171]
I'm trying to create the Docker image on Windows Server 2016 running Docker for Windows, but it looks like the TeslaMate doesn't have a manifest entry for Windows/amd64. See below:

PS E:\Docker-Images\TeslaMate> docker-compose up
Creating network "teslamate_default" with the default driver
Creating volume "teslamate_teslamate-db" with default driver
Creating volume "teslamate_teslamate-grafana-data" with default driver
Creating volume "teslamate_mosquitto-conf" with default driver
Creating volume "teslamate_mosquitto-data" with default driver
Pulling teslamate (teslamate/teslamate:latest)...
latest: Pulling from teslamate/teslamate
**ERROR: no matching manifest for windows/amd64 10.0.14393 in the manifest list entries**
PS E:\Docker-Images\TeslaMate> docker-compose --version
docker-compose version 1.24.1, build 4667896b
PS E:\Docker-Images\TeslaMate> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.1.0-8c33de7)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.2
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 14393 (14393.3024.amd64fre.rs1_release.190530-2002)
 Operating System: Windows Server 2016 Standard Version 1607 (OS Build 14393.3025)
 OSType: windows
 Architecture: x86_64
 CPUs: 24
 Total Memory: 35.96GiB
 Name: Host1-Hyper-V
 ID: 24EW:5672:3Q2X:T4HV:IZKS:LXWL:453B:Y5ME:PQCX:PJ6F:YIIT:GDWR
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by normalfaults** [comment]
The docker images that are built on docker hub for teslamate are Linux based containers. You are running docker for windows in windows container mode. There are currently no windows based container images being built .... you can see the existing builds and architectures here: https://hub.docker.com/r/teslamate/teslamate/tags

if you want to get teslamate images running on your server I would suggest switching to linux container mode in docker for windows

**Comment by injector22** [comment]
I deployed it on a RPi instead.
