### ISSUE TITLE
Stats not being updated

### ISSUE THREAD

**Issue by scottismyname** [adriankumpf/teslamate#172]
About 3 days ago, both my wife and I got notifications on our phones that our account was logged out.  Opening up the app wouldn't update any of the details (mileage left, location, etc), but clicking on the controls would stuff function properly.  I solved this by signing out of my account in the Tesla app and logging back in.  I just checked in and it turns out that Teslamate hasn't been logging any of my drives or anything since then either....however, the main status page DOES seem to be updated with current mileage, temperature, lock state, etc.

I don't see any obvious errors in the logs.  I was getting the unknown error every 30 seconds or so, but those seem to have gone away since I restarted the docker containers, however my car still shows that it's been online for amost 4 days. 

Not sure if this is some sort of token problem or what.  Any advice would be appreciated.

**Comment by krezac** [comment]
I'd try to delete the credentials from DB to force fresh access token generation. I'm not 100% sure you can do it from UI.

**Comment by scottismyname** [comment]
This did indeed fix the weird problem.  It might be nice to add an option to reforce a login without having to delete credentials.

**Comment by adriankumpf** [comment]
Signing in without restarting or having to delete credentials is on the roadmap 👍
