### ISSUE TITLE
Set different kwh cost for day/night 

### ISSUE THREAD

**Issue by thunder2k** [adriankumpf/teslamate#1720]
**Describe the bug**

It would be great to be able to set a different kwh cost in relation to the time. I have a tariff which is different between day and night, so every time I charge the car during daytime, I have to manually fix the records with the day tariff. 

**Expected behavior**

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by tobiasehlert** [comment]
Hi @thunder2k,

You should checkout the **TeslaMateAgile** project, which might be exactly doing what you want to do..
TeslaMateAgile supports that energy providers / tarriffs are either Octopus Agile, Tibber or **fixed pricing** (manually specified).

Link to [TeslaMate docs of projects](https://docs.teslamate.org/docs/projects#teslamateagile)
Link to [TeslaMateAgile on Github](https://github.com/MattJeanes/TeslaMateAgile)

Regards,
Tobias

**Comment by adriankumpf** [comment]
This is not a bug. Feature requests belong here: [💡 Ideas](https://github.com/adriankumpf/teslamate/discussions/categories/ideas). I'll move it.
