### ISSUE TITLE
Charge level graph showing an error

### ISSUE THREAD

**Issue by jherby2k** [adriankumpf/teslamate#1723]
Starting this week some time, i get an error on the "Charge Level" graph.

`convert frame from rows error: sql: Scan error on column index 2, name "Usable Battery Level [%]": converting NULL to int16 is unsupported`

**Expected behavior**
Proper display of the graph

**How to reproduce it (as minimally and precisely as possible)**:

Just view the Charge Level graph in grafana. I'm running this in Home Assistant add-ins. The current versions are TeslaMate 1.23.3 and Grafana 8.0.1. Issue may have cropped up when updating one of these recently - not sure. I'm scared to downgrade as I don't want to lose data points!

-->

**Relevant entries from the logs**

pretty sure its an issue with Grafana

**Screenshots**

Not that useful - i provided the error.

**Data**

Gotta investigate how to export this from a home assistant container.

**Environment**

- TeslaMate version: 1.23.3
- Type of installation: Docker
- OS TeslaMate is installed on: Home Assistant OS
- User OS & Browser: Edge / Home Assistant console
- Others: Grafana 8.0.1

**Comment by adriankumpf** [comment]
We don't support Grafana 8.0 yet. Can you downgrade to Grafana v7 to see if the issue persists?

**Comment by jherby2k** [comment]
Yep, that fixes it. Sorry didn't even really notice they'd upgraded the HA add-in to 8.0 until I went checking version #s.
