### ISSUE TITLE
Long charges do not show in "Charges"

### ISSUE THREAD

**Issue by manuelkamp** [adriankumpf/teslamate#1759]
I think that I miss some long charges in the "Charges" view in the past, but was not sure about it. Now I have the evidence, for the last days. See the "Charge Level", where you can see clearly 4 charges since 23.06. (plus one active charge).

![level](https://user-images.githubusercontent.com/48356947/123522856-75010c80-d6c0-11eb-8a53-e3f5fb1e7bcc.PNG)

And now see the "Charges", where the charge from 25.06. (yesterday) is missing.

![charges](https://user-images.githubusercontent.com/48356947/123522889-bd202f00-d6c0-11eb-939b-61a6435c88bb.PNG)

The missing charge is also visible in "States":

![states](https://user-images.githubusercontent.com/48356947/123523221-9cf16f80-d6c2-11eb-9b79-b8895fb1c47d.png)

It is missing in the Timeline too:

![missing](https://user-images.githubusercontent.com/48356947/123523311-1ee19880-d6c3-11eb-94f6-cae605332c6e.PNG)

**Comment by manuelkamp** [comment]
Maybe another Bug, but related to this one I am also missing a few other long charges, you can see it here: There is a jump from SOC end 33% to start SOC of next charge of 79% - this was also one long charge and is missing completely.
![missing](https://user-images.githubusercontent.com/48356947/123523066-a8906680-d6c1-11eb-98bd-43c234bbf66d.PNG)

**Comment by adriankumpf** [comment]
You'll have to use the "Bug Report" template when creating a new issue if you think you've encountered a bug in TeslaMate. 

We cannot tell pretty much nothing  from a few screenshots. Most important are the logs of the given period and your environment. Please fill out the template as completely as possible.
