### ISSUE TITLE
vehicle_not_found

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#176]
**Describe the bug**
I get vehicle_not_found at the moment (perhaps because tesla server is down? The app does not work either) and teslamate crashes then:

**Expected behavior**
If it is crashing because of the unavailability of the tesla server, t should handle that more gracefully.

**Relevant entries from the logs**
teslamate_1  | 09:54:50.616 [info] Converted exit {{%RuntimeError{message: ":vehicle_not_found"}, [{TeslaMate.Vehicles.Vehicle, :handle_event, 4, [file: 'lib/teslamate/vehicles/vehicle/vehicle.ex', line: 220]}, {:gen_statem, :loop_state_callback, 11, [file: 'gen_statem.erl', line: 1147]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}, {:gen_statem, :call, [:"1", :summary, :infinity]}} to 500 response
teslamate_1  | 09:54:50.617 [error] #PID<0.3587.0> running TeslaMateWeb.Endpoint (connection #PID<0.3586.0>, stream id 1) terminated
teslamate_1  | Server: amigo.schmidt-schmitten.com:4000 (http)
teslamate_1  | Request: GET /
teslamate_1  | ** (exit) exited in: :gen_statem.call(:"1", :summary, :infinity)
teslamate_1  |     ** (EXIT) an exception was raised:
teslamate_1  |         ** (RuntimeError) :vehicle_not_found
teslamate_1  |             (teslamate) lib/teslamate/vehicles/vehicle/vehicle.ex:220: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |             (stdlib) gen_statem.erl:1147: :gen_statem.loop_state_callback/11
teslamate_1  |             (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | 09:54:50.797 [error] GenStateMachine :"1" terminating
....
teslamate_1  | 09:54:53.845 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (RuntimeError) :vehicle_not_found
teslamate_1  |     (teslamate) lib/teslamate/vehicles/vehicle/vehicle.ex:220: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib) gen_statem.erl:1147: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | 09:54:54.866 [info] Application teslamate exited: shutdown
teslamate_1  | {"Kernel pid terminated",application_controller,"{application_terminated,teslamate,shutdown}"}
teslamate_1  | Kernel pid terminated (application_controller) ({application_terminated,teslamate,shutdown})
teslamate_1  |
teslamate_1  | Crash dump is being written to: erl_crash.dump...done

**Operating environment (please complete the following information):**
 - OS: Ubuntu 18.04.3
 - Version 1.8.0

**Comment by adriankumpf** [comment]
Fixed on master with 239ae61f47d5cd8aa828dd3293d77c5638f5d900. I saw the same error a few days ago for roughly 15 minutes, probably due to a server failure.

**Comment by DrMichael** [comment]
Yes, it disappeared later on...

**Comment by krezac** [comment]
How about logging the API/servers/connectivity problems as new status, like "unreachable"?
