### ISSUE TITLE
Docker install on Synology - teslamate cannot connect to database(postgres)

### ISSUE THREAD

**Issue by safetyguy14** [adriankumpf/teslamate#1761]
**Describe the bug**

I attempted to install the latest of TeslaMate using the latest settings for docker-compose.yml (https://docs.teslamate.org/docs/installation/docker/).  All 4 packages install and start running without issue.  The database log shows the database is ready to accept connections.

**Expected behavior**

Teslamate should connect to the database and begin running the backend for the web interface.

**How to reproduce it (as minimally and precisely as possible)**:

1. SSH into Synology NAS, obtain root, and navigate to @docker
2. install teslamate using docker-compose up -d

![docker_database_1](https://user-images.githubusercontent.com/25259031/123552220-cb129600-d73a-11eb-87a6-b511c0bc74aa.jpg)

**Environment**
- TeslaMate version: teslamate/teslamate:latest, postgres:13, teslamate/grafana:latest, eclipse-mosquitto:2
- Type of installation: Docker
- OS TeslaMate is installed on: Synology NAS - Docker 18.09.0-0519
- User OS & Browser: Windows 10 & Microsoft Edge

**Comment by Orbedk** [comment]
@safetyguy14 I just wanna make sure that you have seen this: https://github.com/adriankumpf/teslamate/issues/113
I followed that guide and it worked perfectly for me.

**Comment by adriankumpf** [comment]
Check out the TeslaMate container logs to see why it cannot connect to the database. I’ll move this to a discussion as there is not indication of a TeslaMate bug.
