### ISSUE TITLE
Charge Heatmap displays less sessions after an upgrade

### ISSUE THREAD

**Issue by petariga** [adriankumpf/teslamate#1767]
After the upgrade of TeslaMate from 1.22.0 to 1.23.4 the **Charge Heatmap graph** in the Charging Stats lost many displayed charging sessions, whereas Charge Delta stayed the same. See the screenshots below. However, it seems that all charging sessions are still present in the db, at least according to the list in Charges.

**Correct graph** before the update:
![teslamate_1](https://user-images.githubusercontent.com/64809507/123695597-086e4500-d85b-11eb-8e77-ab16def0e3bd.jpg)

**Incorrect graph** after the update:
![teslamate_2](https://user-images.githubusercontent.com/64809507/123695614-0c01cc00-d85b-11eb-9791-b94b7e0d1227.jpg)

**Comment by adriankumpf** [comment]
The last change to the Charging Stats dashboard was made in v1.21.5: #1355

**Comment by petariga** [comment]
So any idea why the graph has changed? In my opinion it is the same graph, just the granularity has been raised, so only levels with more charges during the same time are displayed.

**Comment by adriankumpf** [comment]
> If it is about the bucket size (mentioned in the #1355 ), can you make it configurable or revert it back?

You can duplicate and customize every dashboard yourself. However, in my opinion, the new representation with the updated bucket size is the correct one.

**Comment by petariga** [comment]
I tried to change Bucket size from 10 to different values including auto and it has no effect on the above mentioned change. So the cause will be somewhere else... Any idea what to change or try? Why the Charge Heatmap lost squares?

**Comment by dyxyl** [comment]
I've tracked this problem down to a bug fix in grafana (https://github.com/grafana/grafana/issues/24849), which means that the colors now start from the lowest count in the heatmap rather than from 0. This effectively darkens all of the cards, and makes the cards with the lowest count have the same color as the background.

**Comment by petariga** [comment]
Outstanding work @dyxyl ! I have not expected to have this bug sourced from Grafana...
