### ISSUE TITLE
system restart during a charge messes up charging stats

### ISSUE THREAD

**Issue by M5M400** [adriankumpf/teslamate#1785]
I noticed that the entry in the "charges" dashboard does not accurately reflect my last charge. I added 48kWh over the course of 4,5h, but the "charges" dashboard lists it as a very short charge, starting with the timestamp of the system reboot

I noticed that the charging_processes table has two entries in that time frame. one with correct starting time that is missing some values - one starting at 00:17 (gmt+2) with all values propagated. csv export attached.

**Expected behavior**

merge pre/post reboot charge into one. the data is there, just parts of it are dismissed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to 'charges' dashboard
2. find wrong stats :)

**Relevant entries from the logs**

```
teslamate_1  | 2021-07-01 18:38:53.249 car_id=1 [info] Charging / SOC: 17% / xxx
teslamate_1  | 2021-07-01 18:38:53.249 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-07-01 20:22:56.620 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9337.039 ms)
teslamate_1  | 2021-07-01 20:22:56.831 car_id=1 [warn] Discarded incomplete fetch result
teslamate_1  | 2021-07-01 22:13:52.864 [info] SIGTERM received - shutting down
teslamate_1  |
teslamate_1  | 2021-07-01 22:17:00.152 [info] Migrations already up
teslamate_1  | 2021-07-01 22:17:00.966 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2021-07-01 22:17:00.966 [info] Version: 1.23.4
teslamate_1  | 2021-07-01 22:17:01.353 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (371.538 ms)
teslamate_1  | 2021-07-01 22:17:02.350 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (996.970 ms)
teslamate_1  | 2021-07-01 22:17:02.351 [info] Refreshed api tokens
teslamate_1  | 2021-07-01 22:17:02.371 [info] Scheduling token refresh in 5 wk 5 d
teslamate_1  | 2021-07-01 22:17:02.375 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2021-07-01 22:17:02.377 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2021-07-01 22:17:05.251 [info] Starting logger for 'Sonic'
teslamate_1  | 2021-07-01 22:17:05.269 [info] MQTT connection has been established
teslamate_1  | 2021-07-01 22:17:06.143 car_id=1 [info] Start / :online
teslamate_1  | 2021-07-01 22:17:06.177 car_id=1 [info] Connecting ...
teslamate_1  | 2021-07-01 22:17:06.427 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (246.217 ms)
teslamate_1  | 2021-07-01 22:17:06.454 car_id=1 [info] Charging / SOC: 69% / xxx
```

**Screenshots**

![image](https://user-images.githubusercontent.com/22886679/124264114-5ffb0200-db34-11eb-82f9-9f2e777ef206.png)

notice that the displayed charge starts at 00:17 (GMT+2), while the actual charging started around 3,5h earlier at 20:39

![image](https://user-images.githubusercontent.com/22886679/124264314-9a649f00-db34-11eb-8f64-cfc9eb19da7b.png)

**Data**

relevant contents from charges and charging_processes tables

[data.zip](https://github.com/adriankumpf/teslamate/files/6754322/data.zip)

**Environment**

- TeslaMate version: v1.23.4
- Type of installation: Docker 
- OS TeslaMate is installed on: Ubuntu 21.04
- User OS & Browser: irrelevant
- Others:

**Comment by adriankumpf** [comment]
If a charging session could not be recorded because TeslaMate did not run e.g. because of a reboot the corresponding charge is shown as incomplete. A new charge is started once its running again. How would it know whether you continued or temporarily stopped charging while TeslaMate could not record anything?

You can, however, manually fix those charges as described in the docs: https://docs.teslamate.org/docs/maintenance/manually_fixing_data

> merge pre/post reboot charge into one. the data is there, just parts of it are dismissed.

TeslaMate deliberately doesn't automatically merge charges because it's hard to get right, might not be desired in every case and could also produce incorrect data.

**Comment by M5M400** [comment]
alright, if it's not feasible to auto-detect this, I'll just manually fix it for this instance.
