### ISSUE TITLE
Migration failed?  docker_teslamate_1 exited with code 1 after upgrade to 1.23.4

### ISSUE THREAD

**Issue by seabie** [adriankumpf/teslamate#1788]
[teslamate_exit_logs.txt](https://github.com/adriankumpf/teslamate/files/6758388/teslamate_exit_logs.txt)
### Discussed in https://github.com/adriankumpf/teslamate/discussions/1763

<div type='discussions-op-text'>

<sup>Originally posted by **seabie** June 27, 2021</sup>
I just ran the update procedure to move to 1.23.4 (I think I was on the previous release but it is possible I was one more behind?).  I'm now seeing the following trying to bring everything up (abbreviated log for what looks like the first error):
<br>
`teslamate_1  | 2021-06-28 00:43:39.474 [info] Application telemetry exited: :stopped
teslamate_1  | 2021-06-28 00:43:39.543 [info] Application eex exited: :stopped
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, {:decimal, {{:case_clause, {:ok, []}}, [{:application_controller, :make_appl, 1, [file: 'application_controller.erl', line: 1461]}, {:application_controller, :do_load_application, 2, [file: 'application_controller.erl', line: 1273]}, {:application_controller, :handle_call, 3, [file: 'application_controller.erl', line: 628]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 721]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 750]}]}}}
teslamate_1  |     (ecto_sql 3.6.2) lib/ecto/migrator.ex:132: anonymous fn/2 in Ecto.Migrator.with_repo/3
teslamate_1  |     (elixir 1.12.1) lib/enum.ex:3865: Enum.flat_map_list/2
teslamate_1  |     (ecto_sql 3.6.2) lib/ecto/migrator.ex:131: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.23.4) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  |     (elixir 1.12.1) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |     (teslamate 1.23.4) lib/teslamate/release.ex:8: TeslaMate.Release.migrate/0
teslamate_1  |     (stdlib 3.15.1) erl_eval.erl:685: :erl_eval.do_apply/6
docker_teslamate_1 exited with code 1`
<br>
After looking at the latest docker-compose.yml file I noticed that Postgres was updated from v12 (what I was on) to v13.  I executed the backup->Postgres docker-compose change to 13->docker-compose pull->Restore->docker-compose down->docker-compose up sequence and I'm still seeing the same issue.<br>

Any advice?  We just bought our second Tesla recently if that has any bearing on the issue.  Was the first time I went to use Teslamate after the purchase, noticed I was behind a revision, which started this issue.</div>

**Comment by adriankumpf** [comment]
I cannot reproduce this on a Raspberry Pi 3 Model B running the v1.23.4 TeslaMate Docker container.

**Comment by seabie** [comment]
Unfortunately I did not run a backup just before this update attempt 😢 That said it sounds like if I grab the data, and then attempt to restore after a fresh installation is my best course of action, or is there a better approach?

Thank you!

**Comment by seabie** [comment]
Sorry for not following up sooner but this morning I finally got a chance to re-image my Raspberry Pi.  Happy to report that after setting up Teslamate from scratch, I was able to restore the backup referenced before and other than missing a couple of weeks of data while it was not running everything seems happy (and our new car is there!).
