### ISSUE TITLE
wizzy export of dashboards looks in wrong place during manual install

### ISSUE THREAD

**Issue by SigLinJo** [adriankumpf/teslamate#179]
**Describe the bug**

I have a manual install inside a FreeNAS jail and have everything working ok, but I have over the last couple of updates been stopped by the following error messages while trying to use wizzy export:

$ for d in grafana/dashboards/*.json; do wizzy export dashboard $(basename $d .json); done
✘ Dashboard file dashboards/charge-details.json does not exist.
✘ Dashboard file dashboards/charges.json does not exist.
✘ Dashboard file dashboards/charging-stats.json does not exist.
✘ Dashboard file dashboards/degradation.json does not exist.
✘ Dashboard file dashboards/drive-details.json does not exist.
✘ Dashboard file dashboards/drives.json does not exist.
✘ Dashboard file dashboards/efficiency.json does not exist.
✘ Dashboard file dashboards/locations.json does not exist.
✘ Dashboard file dashboards/mileage.json does not exist.
✘ Dashboard file dashboards/position.json does not exist.
✘ Dashboard file dashboards/states.json does not exist.
✘ Dashboard file dashboards/updates.json does not exist.
✘ Dashboard file dashboards/vampire-drain.json does not exist.
✘ Dashboard file dashboards/visited.json does not exist.

Just to test I tried to copy the dashboards directory to the teslamate directory out of the grafana directory:

$ cp -r grafana/dashboards dashboards

That made the export work as intended:

$ for d in grafana/dashboards/*.json; do wizzy export dashboard $(basename $d .json); done
Output:
{
  "id": 14,
  "slug": "charge-details",
  "status": "success",
  "uid": "BHhxFeZRz",
  "url": "/d/BHhxFeZRz/charge-details",
  "version": 4
}
✔ Dashboard charge-details export successful.

and so on for all dashboards.

I don't know how it works but I imagine that there are a script somewhere that just need to be updated to include grafana/ in the file path?

I really like how the application works even on my not standard installation! I think it is a really good fit for FreeNAS with the possibility to have the data stored securely and even replicated to offsite backup. I only regret that I'm not better at programming so I could compile it in to a real FreeBSD package, right now I have to manually start teslamate every time I reboot the server, and it was a bit fiddly to get all the environment variables set up properly.

Thank you so much for building and maintaining this really wonderful program! I really like to be able to log everything with my car and at the same time keep all my data at home. 

**Operating environment (please complete the following information):**
 - OS: [FreeBSD 11.2 in an FreeNAS iocage jail]
 - Version [e.g. v1.9.1]

**Comment by krezac** [comment]
I run (from grafana folder, grafana removed from in):
`for d in dashboards/*.json; do wizzy export dashboard $(basename $d .json); done`
However the problem is the dashboards end up in the root, not in Grafana, I assume sth with the env variables DASHBOARD_FOLDER and DASHBOARD_FOLDER_UID. 

Also, you have typo in script name: update_dashbAOrds.sh ;) And this script returns some weird error (I didn't have time to dig deeper):
`jq: error (at <stdin>:0): Cannot index string with string "type"`

**Comment by adriankumpf** [comment]
Thanks for reporting the issue. Great to hear that it's running on FreeBSD as well.

The steps mentioned in the import guide were a bit outdated. I updated them accordingly.

@krezac Fixed. The script works for me :P But it's not really needed anyway.

**Comment by SigLinJo** [comment]
Thank you, another great improvement! For us not using the docker version updating the dashboards is a lot easier now! Tried the new command and it seemed to work great! All dashboards where already updated so hard to know for sure, but I got a very promising message after running it :)

✔ 14 dashboards exported successfully.

Thank you again!
