### ISSUE TITLE
Login after Installation not Working

### ISSUE THREAD

**Issue by fynnsh** [adriankumpf/teslamate#1806]
Hello,

the Login-Window is frozen at visit. Some weird bugs with the tesla api are showing up? Did Tesla Change something or is my Setup wrong? Tested on Ubuntu 20.04 on Raspberry Pi and vServer. Same issue for TeslaLogger

regards

![image](https://user-images.githubusercontent.com/24509725/124849559-49730180-df9f-11eb-998f-c7d6532bcc11.png)

2021-07-08 01:44:58.850 [info] GET https://auth.tesla.com/oauth2/v3/authorize -> 200 (216.916 ms)
2021-07-08 01:44:58.868 [error] GenServer TeslaMate.Api terminating
** (FunctionClauseError) no function clause matching in Regex.match?/2
    (elixir 1.12.1) lib/regex.ex:279: Regex.match?(~r/^https?:\/\//i, ["/captcha"])
    (tesla 1.4.1) lib/tesla/middleware/core.ex:34: Tesla.Middleware.BaseUrl.apply_base/2
    (tesla 1.4.1) lib/tesla/middleware/core.ex:29: Tesla.Middleware.BaseUrl.call/3
    (teslamate 1.23.4) lib/tesla_api/middleware/follow_redirects.ex:51: TeslaApi.Middleware.FollowRedirects.redirect/4
    (teslamate 1.23.4) lib/tesla_api/auth.ex:194: TeslaApi.Auth.load_captcha_image/2
    (teslamate 1.23.4) lib/tesla_api/auth.ex:183: TeslaApi.Auth.load_form/2
    (teslamate 1.23.4) lib/tesla_api/auth.ex:97: TeslaApi.Auth.prepare_login/0
    (teslamate 1.23.4) lib/teslamate/api.ex:122: TeslaMate.Api.handle_call/3
Last message (from #PID<0.2427.0>): :prepare_sign_in
2021-07-08 01:44:58.871 [error] GenServer #PID<0.2427.0> terminating
** (stop) exited in: GenServer.call(TeslaMate.Api, :prepare_sign_in, 120000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Regex.match?/2
            (elixir 1.12.1) lib/regex.ex:279: Regex.match?(~r/^https?:\/\//i, ["/captcha"])
            (tesla 1.4.1) lib/tesla/middleware/core.ex:34: Tesla.Middleware.BaseUrl.apply_base/2
            (tesla 1.4.1) lib/tesla/middleware/core.ex:29: Tesla.Middleware.BaseUrl.call/3
            (teslamate 1.23.4) lib/tesla_api/middleware/follow_redirects.ex:51: TeslaApi.Middleware.FollowRedirects.redirect/4
            (teslamate 1.23.4) lib/tesla_api/auth.ex:194: TeslaApi.Auth.load_captcha_image/2
            (teslamate 1.23.4) lib/tesla_api/auth.ex:183: TeslaApi.Auth.load_form/2
            (teslamate 1.23.4) lib/tesla_api/auth.ex:97: TeslaApi.Auth.prepare_login/0
            (teslamate 1.23.4) lib/teslamate/api.ex:122: TeslaMate.Api.handle_call/3
    (elixir 1.12.1) lib/gen_server.ex:1024: GenServer.call/3
    (teslamate 1.23.4) lib/teslamate_web/live/signin_live/index.ex:121: TeslaMateWeb.SignInLive.Index.handle_info/2
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:248: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :prepare_sign_in
2021-07-08 01:45:00.711 [info] GET /sign_in
2021-07-08 01:45:00.720 [info] Sent 200 in 8ms
2021-07-08 01:45:03.885 [info] Application teslamate exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,teslamate,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,teslamate,shutdown})

Crash dump is being written to: erl_crash.dump...done
2021-07-08 01:45:09.701 [info] Migrations already up
2021-07-08 01:45:12.707 [info] System Info: Erlang/OTP 24 (emu)
2021-07-08 01:45:12.707 [info] Version: 1.23.4
2021-07-08 01:45:12.771 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
2021-07-08 01:45:12.773 [info] Access TeslaMateWeb.Endpoint at http://localhost
2021-07-08 01:45:12.787 [info] MQTT connection has been established

**Comment by fynnsh** [comment]
gn

**Comment by zoomerbot101** [comment]
having this issue as well

**Comment by Android-BRUCE** [comment]
having this issue as well

**Comment by adriankumpf** [comment]
Looks like Tesla have re-enabled the captcha.

**Comment by adriankumpf** [comment]
Can you try the latest release (v1.23.5) and see if that fixes the login issue?

**Comment by Android-BRUCE** [comment]
> Can you try the latest release (v1.23.5) and see if that fixes the login issue?
After logging in, red font prompts
The following:
Error: An unexpected error occurred

**Comment by adriankumpf** [comment]
Chinese account?

**Comment by Android-BRUCE** [comment]
> Chinese account?

yep.Chinese account does not work?

**Comment by adriankumpf** [comment]
Yeah, it looks like with v1.23.5 only Chinese accounts cannot login. v1.23.6 will be out in a few minutes. That hopefully fixes that issue as well but it's hard to test because I don't have a valid account to verify.

**Comment by fynnsh** [comment]
Working again. Thanks
