### ISSUE TITLE
The login page cannot display properly

### ISSUE THREAD

**Issue by Android-BRUCE** [adriankumpf/teslamate#1807]
![9201625729464_ pic](https://user-images.githubusercontent.com/18898962/124881669-33e2f380-e002-11eb-8f0c-cd907322e7cb.jpg)
Always refresh automatically until 502 error ,unable to enter account password and click the login button

**Environment**

- TeslaMate version:1.23.4
- Type of installation: Docker 
- OS TeslaMate is installed on: alliyun os
- User OS & Browser: Browser
- Others:

**Comment by adriankumpf** [comment]
Duplicate of #1806
