### ISSUE TITLE
Add MQTT Topics

### ISSUE THREAD

**Issue by ngardiner** [adriankumpf/teslamate#182]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. I'm working on replacing the official Tesla component in HomeAssistant with the MQTT topics published by teslamate for my installation. This process is documented in the following gist:

https://gist.github.com/ngardiner/0cbb6b87142aba044596426c8a21581c

Working on the initial steps of this process, I've identified a few values provided by the component which aren't currently published by teslamate, it would be fantastic to have these published to MQTT topics.

**Describe the solution you'd like**
If possible, it would be useful to have the following data:

  - teslamate/cars/$car_id/position_lat (Last polled position in Latitude)
  - teslamate/cars/$car_id/position_lon (Last polled position in Longitude)
  - teslamate/cars/$car_id/elevation (nice to have)
  - teslamate/cars/$car_id/odometer (Last polled mileage/odometer)
  - teslamate/cars/$car_id/park_brake (Status of park brake)
  - teslamate/cars/$car_id/charger_door_lock (Boolean status of charger door lock)

**Describe alternatives you've considered**
Alternatives considered:
  - Porting of connection logic from teslamate to HASS component (difficult due to the port from erlang to python but certainly doable. still results in double polling)
  - Offering API via teslamate using cached values: Not core functionality of teslamate, unlikely to be offered

**Additional context**
Screenshots to show the presentation of the data in HomeAssistant are available in the gist linked above.

**Comment by adriankumpf** [comment]
Awesome, I'm very interested in the final component!

Publishing the elevation might be a bit tricky. The other topics are easy to add (`door_lock` gets already published as `locked`).

**Comment by ngardiner** [comment]
Thanks @adriankumpf! It looks like the locking part will be less of a challenge than I thought, in fact I think it's only the climate controls that might be a bit tricky, and only because I'm not entirely sure how many of the details that HASS uses (such as HVAC power state, current temp, target temp, etc) are actually available via the API and whether they'd plug straight in or need some translation. I'll take it one sensor value at a time and test it out, eventually it will fall into place. Much appreciate your help! It's awesome to have so much visibility/control over our cars.

**Comment by thomas70** [comment]
I like to see these 
- teslamate/cars/$car_id/time_to_full_charge
- teslamate/cars/$car_id/charger_phases
- teslamate/cars/$car_id/charger_actual_current
- teslamate/cars/$car_id/charger_voltage
