### ISSUE TITLE
dashboards not updating anymore

### ISSUE THREAD

**Issue by pinguozzo** [adriankumpf/teslamate#183]
My dashboards are not updating anymore. How do I force the re-login and get a new token? Thanks

**Comment by adriankumpf** [comment]
What have you done so far? Did restarting TeslaMate help?

**Comment by pinguozzo** [comment]
Hi, thanks for the immediate reply. 
Yes, I did restart Teslamate: docker-compose down && docker-compose up -d. 

I even did a docker-compose pull and restarted afterwards. What I noticed was only that my Tesla car name was just the numeric one instead of the usual one. 
I drove for some 20-30 km but no drive was logged. 
I did check before if Teslamate was running and it was correctly. No errors in the logs whatsoever.

Thanks for you help and for your great work.

**Comment by adriankumpf** [comment]
If restarting doesn't help you'll need to delete the entry in the database table `tokens`. The next release will add an option to force a re-login.

If the error occurs again, please save the logs before restarting the container.

**Comment by BabyYeggie** [comment]
It looks to be a problem with Traefik. My dash stopped updating on Friday evening around 19h00 Mountain.

This is the last error before the process ends.
command traefik error: flag needs an argument: -docker.watch

Looks like the docker-compose file needs to be updated with new settings for Traefik as already discussed in that thread.

**Comment by pinguozzo** [comment]
> If restarting doesn't help you'll need to delete the entry in the database table `tokens`. The next release will add an option to force a re-login.
> 
> If the error occurs again, please save the logs before restarting the container.

Hi, just checked that the token was updated_at 2019-09-29. I'm not sure why my trip was not logged.
Will let you know if tomorrow I see something different. Hard to tell/debug in this way, I know. 

Cheers,
Gian

**Comment by BabyYeggie** [comment]
Restarting the container seems to work.
