### ISSUE TITLE
Cannot get elevation data for drives

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#184]
Hi,
This is new, and it was not happening earlier - but it seems now TeslaMate cannot pull the elevation details for all the drives in the last few days.

I was out doing errands this morning and see this in the logs as a recent example. Do you know what site / API is it using to pull that information so I can make sure it is not being blocked? I run PiHole on the home network, and it might be blocking it. Is it using either ip-api.com and/or ipapi.co? I can't seem to find anything else at this time.

Thanks.

`
11:37:05.640 [info] Querying location for elevation takes longer than 50ms ...,
11:37:37.930 [warn] Elevation query failed: %SRTM.Error{message: "HTTP request failed", reason: %Mint.TransportError{reason: :timeout}},
11:37:39.727 [info] Querying location for elevation takes longer than 50ms ...,
11:38:13.841 [info] Querying location for elevation takes longer than 50ms ...,
11:39:26.833 [info] [alarm_handler: {:set, {TeslaMate.Mapping, :fuse_blown}}],
11:38:46.109 [warn] Elevation query failed: %SRTM.Error{message: "HTTP request failed", reason: %Mint.TransportError{reason: :timeout}},
11:38:12.007 [warn] Elevation query failed: %SRTM.Error{message: "HTTP request failed", reason: %Mint.TransportError{reason: :timeout}}`

**Comment by bahree** [comment]
Also poking around a little I saw that the STRM reference and saw in [https://github.com/adriankumpf/srtm/blob/master/lib/source/esa.ex](https://github.com/adriankumpf/srtm/blob/master/lib/source/esa.ex) that it was linking to [this](http://step.esa.int/auxdata/dem/SRTMGL1/) -if that's the source then that is not blocked and I can get to it. I don't know why it stopped when it was working earlier.

Thanks.

**Comment by cwanja** [comment]
Have you tried disabling Pi hole and seeing if it can retrieve them? That would tell you if it is a Pi hole issue. Unfortunately I am away at the moment, cannot report if I am experiencing the same. However, there is no chance (or very very little) our blocklists are 100% the same.

**Comment by adriankumpf** [comment]
I wouldn't worry too much about those timeout errors. They could be caused by anything ... TM will retry to fetch the missing elevation data every 6 hours.

**Comment by bahree** [comment]
OK - so I went back and checked - don't have elevation data for the last ~2 weeks. And I see a ton of these errors on timeouts. I did disable PiHole to eliminate other variables - and this morning's drive - the drive itself is captured as expected - everything except elevation.

@adriankumpf - which process tries to update this - could it be that there are too many missing elevations and it is just trying to get a whole bunch together and timing out? When I goto https://dds.cr.usgs.gov/ - I can see the site is up, but its not rendering much - don't know if they changed anything. 

And not very helpful, but here are some of the errors from the logs (there as you can imagine are tons of these as it seems to be trying every 3-4 seconds).

`
08:33:19.208 [info] Querying location for elevation takes longer than 50ms ...,
08:33:22.534 [info] Querying location for elevation takes longer than 50ms ...,
08:33:25.471 [info] Querying location for elevation takes longer than 50ms ...,
08:33:28.279 [info] Querying location for elevation takes longer than 50ms ...,

`

**Comment by adriankumpf** [comment]
>  could it be that there are too many missing elevations and it is just trying to get a whole bunch together and timing out

The site just doesn't seem to be very responsive right now. When their servers start working again, TM will add the missing elevation data.
