### ISSUE TITLE
New feature request: stats while charging

### ISSUE THREAD

**Issue by Spera15** [adriankumpf/teslamate#1847]
First of all thank you for this amazing project! It is really well done and helpful!

**Request - Charge monitor**
Using TM I can basically track every single aspect of my Tesla, except a single one: the charging process. There is a huge amount of stats related to completed charges (and it is probably the page I use the most), but at the moment there is no way to track a charge while it is being done.

It would be great if a new page could be added, that includes:
- a chart like the one in "overview", showing the undergoing charge
- battery level
- charging voltage
- charging kW
- charging Amps
- kWh added
- elapsed time
- estimated time left (if provided through Tesla API, I don't know if it does)
- estimated cost (if geofencing is available)
- estimated range
- estimated range added
- any other applicable stat

**Comment by adriankumpf** [comment]
Feature requests belong here: [💡 Ideas](https://github.com/adriankumpf/teslamate/discussions/categories/ideas). I'll move it.
