### ISSUE TITLE
Feature request: Add costs to chargings session

### ISSUE THREAD

**Issue by toerb** [adriankumpf/teslamate#185]
Hi, thank you very much for this great project!

One feature I am missing is keeping track of my charging costs. I am relying completely on public infrastructure and get charged per session or based on my consumption.

I would like to be able to annotate the automatically recorded charging sessions with the amount I was charged from my charging operator.
From my point of view only one more field per charging session for the total cost would be required in the database. Everything else (price per kWh, ...) can be calculated in the dashboards.

The interface to input the charging cost could probably be located in the same part of the project where also the geo-fence settings are located (port 4000 in default installation).

Have a great time!
toerb

**Comment by ngardiner** [comment]
Could I just add to this suggestion - I suspect what will take the most time here would be the UI to update the charging cost, however if we could put in a database field for cost for charging sessions into an upcoming schema change, those of us comfortable with updating it via the SQL interpreter could start logging these values until a UI solution exists. At the moment, I (and likely others) are recording the details elsewhere in anticipation that we might have an interface for it in the future.

At simplest, I would think it would just be a double precision field named cost. I've got a bit of spare time now, so I will see if I can submit a PR for this.
