### ISSUE TITLE
New car state: shutdown treated as unknown state

### ISSUE THREAD

**Issue by virtualm2000** [adriankumpf/teslamate#186]
With new V10 there is a new state reported by the car.

10:47:06.641 car_id=1 [warn] **Error / unkown vehicle state**: %TeslaApi.Vehicle{api_version: 6, backseat_token: nil, backseat_token_updated_at: nil, calendar_enabled: true, charge_state: nil, climate_state: nil, color: nil, display_name: "*******", drive_state: nil, gui_settings: nil, id: ****************, in_service: false, option_codes: ["AD15", "MDL3", "PBSB", "RENA", "BT37", "ID3W", "RF3G", "S3PB", "DRLH", "DV2W", "W39B", "APF0", "COUS", "BC3B", "CH07", "PC30", "FC3P", "FG31", "GLFR", "HL31", "HM31", "IL31", "LTPB", "MR31", "FM3B", "RS3H", "SA3P", "STCP", "SC04", "SU3C", "T3CA", "TW00", "TM00", "UT3P", "WR00", "AU3P", "APH3", ...], **state: "shutdown"**, tokens: ["****************", "********************"], vehicle_config: nil, vehicle_id: ****************, vehicle_state: nil, vin: "********************"}}

I'm not sure what this means. Is the car already sleeping? Or attempting? 
Teslamate kept trying to let the car to sleep but it didn't succeed. However when I went to the car, it was sleeping. I could tell by the instrument cluster display booting.

I'll monitor the car this evening and get the status manually to see what is the difference.

Best regards,
Mihai

**Comment by adriankumpf** [comment]
> I'll monitor the car this evening and get the status manually to see what is the difference.

Let me know how it goes! Is state is only visible for a short time or it is reported as long as the car is asleep?

**Comment by adriankumpf** [comment]
Interesting. If it's a temporary state we don't need to change much. I'll try to improve the error message for now.
