### ISSUE TITLE
Trip total driving time is too low

### ISSUE THREAD

**Issue by khorton** [adriankumpf/teslamate#1860]
**Describe the bug**

The displayed total driving time for a trip (below the pie chart) is much too low.  On a recent 7 day long road trip, the displayed driving time was 22 hours, 38 minutes.  The total distance is displayed as 1692 miles, which matches the trip meter in the car.  1692 miles driven in 22 hours, 38 minutes implies an average speed of 75 mph, which is much too high.  The trip page displays an average speed (excluding breaks) of 50.0 mph, which seems much more reasonable for the mix of road types driven. 1692 miles driven at an average speed of 50 mph implies a total driving time of 33.84 hr, which matches my written daily notes.

**Expected behavior**

Provide an accurate total driving time on the trip display.

**How to reproduce it (as minimally and precisely as possible)**:

Conduct a drive with several segments of varying length, ranging from a few minutes long to over two hours long.  Display those drives on the Trip Dashboard.  Note that the total driving time is unreasonably low, and implies an average speed that is too high.

**Relevant entries from the logs**
[logs.txt](https://github.com/adriankumpf/teslamate/files/6873011/logs.txt)

**Screenshots**

![Image 7-24-21 at 7 25 AM](https://user-images.githubusercontent.com/77668/126879926-e7774944-1837-41ca-a3b3-159394d145a8.jpg)

**Data**

docker-compose exec db psql teslamate teslamate -c \
      "COPY (select * from drives where start_date > '2021-07-17') TO STDOUT WITH CSV HEADER" > drives.csv
      
id,start_date,end_date,outside_temp_avg,speed_max,power_max,power_min,start_ideal_range_km,end_ideal_range_km,start_km,end_km,distance,duration_min,car_id,inside_temp_avg,start_address_id,end_address_id,start_rated_range_km,end_rated_range_km,start_position_id,end_position_id,start_geofence_id,end_geofence_id
3798,2021-07-17 16:48:33.802271,,,,,,,,,,,,1,,,,,,,,,
3795,2021-07-17 14:55:47.083,2021-07-17 16:20:54.543,22.1,138,217,-75,400.53,251.88,61834.054234,61968.210944,134.156709999996,85,1,20.8,1,294,400.53,251.88,4983980,4997492,1,18
3797,2021-07-17 16:32:03.856019,,,,,,,,,,,,1,,,,,,,,,
3799,2021-07-17 18:10:45.574,2021-07-17 18:21:13.213,27.6,121,61,-70,67.45,51.61,62159.551953,62175.440953,15.8889999999956,10,1,23.0,496,92,67.45,51.61,5010490,5012112,,
3800,2021-07-17 18:50:09.203,2021-07-17 21:05:24.826,27.4,121,138,-74,344.11,116.31,62175.396096,62379.450963,204.054867000006,135,1,22.2,92,497,344.11,116.31,5012122,5030721,,
3801,2021-07-17 21:16:47.214,2021-07-17 22:18:21.454,29.0,122,149,-75,260.83,155.53,62379.460915,62477.158967,97.6980519999997,62,1,21.5,497,498,260.83,155.53,5030728,5039502,,
3803,2021-07-17 22:50:13.853,2021-07-17 23:00:21.644,30.5,106,194,-63,388.14,379.19,62477.148096,62485.100967,7.95287100000132,10,1,23.0,498,499,388.14,379.19,5039530,5041291,,
3827,2021-07-19 17:59:55.055576,,,,,,,,,,,,1,,,,,,,,,
3842,2021-07-20 15:48:40.547343,,,,,,,,,,,,1,,,,,,,,,
3804,2021-07-17 23:15:39.548,2021-07-17 23:16:36.83,30.5,13,9,3,378.52,378.52,62485.033882,62485.179968,0.146085999993375,1,1,31.4,499,500,378.52,378.52,5041296,5041393,,
3805,2021-07-17 23:20:03.399,2021-07-17 23:21:19.608,30.5,14,9,1,377.83,377.83,62485.194816,62485.273968,0.0791519999984303,1,1,29.1,500,499,377.83,377.83,5041395,5041576,,
3806,2021-07-18 14:48:45.634,2021-07-18 15:56:50.666,14.1,100,109,-76,353.04,247.07,62485.273968,62581.693973,96.4200049999999,68,1,21.3,499,501,353.04,247.07,5041763,5053000,,
3807,2021-07-18 16:03:52.986,2021-07-18 16:07:00.169,16.2,80,89,-58,245.68,241.56,62581.755456,62584.727972,2.97251600000163,3,1,21.3,501,502,245.68,241.56,5053003,5053575,,
3808,2021-07-18 16:21:58.058,2021-07-18 16:24:56.639,16.1,97,83,-13,240.18,234.67,62584.652275,62588.323973,3.67169799999829,3,1,21.3,502,503,240.18,234.67,5053579,5054057,,
3809,2021-07-18 18:29:56.17,2021-07-18 19:33:54.156,20.4,117,117,-73,214.04,134.91,62608.655974,62696.108978,87.4530039999954,64,1,21.2,504,488,214.04,134.91,5054059,5065457,,
3826,2021-07-19 17:32:41.84,2021-07-19 17:42:09.621,17.8,82,66,-58,265.67,258.09,63079.364621,63085.949997,6.58537600000273,9,1,21.0,518,519,265.67,258.09,5102620,5103967,,
3810,2021-07-18 20:09:37.071,2021-07-18 20:15:56.778,20.0,97,81,-70,407.45,401.27,62696.179814,62701.818978,5.63916400000016,6,1,21.9,488,505,407.45,401.27,5065468,5066533,,
3812,2021-07-18 20:50:23.94,2021-07-18 21:28:28.004,20.8,101,194,-65,360.64,309.03,62744.138266,62796.758983,52.620716999998,38,1,20.5,506,507,360.64,309.03,5072469,5076755,,
3811,2021-07-18 20:17:15.832,2021-07-18 20:48:00.271,21.0,132,223,-74,401.93,360.64,62701.812518,62744.18498,42.3724619999994,31,1,20.4,505,506,401.93,360.64,5066535,5072467,,
3814,2021-07-18 22:50:47.782,2021-07-18 22:52:52.152,14.5,97,48,-31,212.67,211.29,62890.121987,62892.841651,2.71966400000383,2,1,21.2,508,509,212.67,211.29,5086714,5086867,,
3817,2021-07-19 00:46:14.925,2021-07-19 00:51:04.197,19.7,72,72,-49,390.27,386.81,63006.622272,63009.420992,2.79871999999887,5,1,21.1,511,512,390.27,386.81,5093052,5093941,,
3821,2021-07-19 15:24:00.932,2021-07-19 15:27:15.328,14.8,55,65,-39,355.13,353.77,63010.001894,63011.708993,1.70709899999929,3,1,20.7,513,514,355.13,353.77,5094562,5095117,,
3830,2021-07-19 19:10:23.931,2021-07-19 19:24:07.247,17.3,66,47,-39,358.58,353.77,63157.095936,63161.692,4.59606400000484,14,1,21.9,511,521,358.58,353.77,5110350,5112393,,
3834,2021-07-19 22:12:56.967,2021-07-19 22:17:08.776,16.0,40,25,-19,417.80,416.42,63294.855782,63295.939006,1.08322400000179,4,1,22.8,522,523,417.80,416.42,5120049,5120713,,
3857,2021-07-22 16:03:29.32,2021-07-22 16:24:24.913,18.5,119,185,-134,167.94,123.89,63634.405022,63664.856024,30.4510020000016,21,1,21.5,538,539,167.94,123.89,5155673,5158199,,
3860,2021-07-22 19:42:13.806,2021-07-22 20:00:03.989,24.7,66,98,-52,120.44,103.24,63883.922034,63892.982036,9.06000199999835,18,1,21.9,541,542,120.44,103.24,5178916,5181764,,
3870,2021-07-23 19:56:21.586749,,,,,,,,,,,,1,,,,,,,,,
3876,2021-07-24 16:06:40.026,2021-07-24 16:19:28.783,25.6,106,188,-72,397.06,381.93,64557.225216,64571.246067,14.0208510000011,13,1,21.2,1,118,397.06,381.93,5245971,5248359,1,
3813,2021-07-18 21:32:15.774,2021-07-18 22:48:27.018,17.7,122,202,-74,309.03,212.67,62796.761983,62890.121987,93.3600040000019,76,1,21.1,507,508,309.03,212.67,5076758,5086712,,
3815,2021-07-18 23:34:36.344,2021-07-19 00:09:42.967,17.1,113,80,-44,140.42,79.84,62955.80499,63006.528993,50.724003000003,35,1,20.9,510,511,140.42,79.84,5086869,5092983,,
3816,2021-07-19 00:16:43.883,2021-07-19 00:17:09.043,18.5,6,8,1,123.89,123.89,63006.461338,63006.544993,0.0836550000021816,0,1,21.0,511,511,123.89,123.89,5092989,5093042,,
3819,2021-07-19 01:00:22.964,2021-07-19 01:01:07.634,20.0,11,10,0,386.15,386.11,63009.427993,63009.465993,0.0380000000004657,1,1,23.9,512,512,386.15,386.11,5093966,5094028,,
3820,2021-07-19 15:08:24.898,2021-07-19 15:10:35.142,15.0,40,23,-16,357.89,355.83,63009.519091,63010.030993,0.511901999998372,2,1,20.7,512,513,357.89,355.83,5094199,5094558,,
3828,2021-07-19 18:18:50.773,2021-07-19 18:47:05.449,17.3,117,86,-69,218.18,155.54,63111.377997,63157.032,45.654002999996,28,1,21.2,520,511,218.18,155.54,5105470,5110292,,
3831,2021-07-19 19:27:46.794537,,,,,,,,,,,,1,,,,,,,,,
3839,2021-07-20 00:43:46.938,2021-07-20 00:45:35.725,20.5,40,22,-15,405.38,404.72,63301.132224,63301.750006,0.617782000001171,2,1,25.2,523,526,405.38,404.72,5122779,5123098,,
3847,2021-07-20 20:24:56.694,2021-07-20 20:42:12.721,31.7,77,73,-52,371.68,357.92,63487.011456,63499.057016,12.0455599999987,17,1,21.6,531,532,371.68,357.92,5139538,5142535,,
3849,2021-07-21 17:16:49.728,2021-07-21 17:18:01.568,23.0,60,53,-9,322.79,322.79,63507.656016,63508.044016,0.38799999999901,1,1,21.2,533,534,322.79,322.79,5143733,5143780,,
3865,2021-07-23 15:01:52.184169,,,,,,,,,,,,1,,,,,,,,,
3871,2021-07-23 20:29:55.003,2021-07-23 20:31:10.447,31.0,27,16,-21,108.05,108.05,64421.178059,64421.299059,0.120999999999185,1,1,20.4,294,294,108.05,108.05,5230513,5230626,,18
3872,2021-07-23 20:32:35.551,2021-07-23 20:33:34.594,31.0,8,8,1,110.13,109.44,64421.235648,64421.33106,0.0954119999951217,1,1,20.9,294,294,110.13,109.44,5230628,5230739,18,18
3875,2021-07-23 22:37:09.615,2021-07-23 22:38:16.863,31.5,32,20,-8,72.97,72.97,64556.903347,64557.266066,0.362718999997014,1,1,21.1,6,1,72.97,72.97,5245605,5245784,11,1
3878,2021-07-24 16:55:15.455,2021-07-24 16:56:08.634,26.0,2,3,1,376.43,377.10,64572.553067,64572.563067,0.0100000000020373,1,1,21.2,374,374,376.43,377.10,5248431,5248435,,
3822,2021-07-19 15:27:55.778,2021-07-19 15:58:53.37,13.7,113,81,-66,353.07,289.76,63011.772173,63061.880996,50.1088230000023,31,1,21.0,514,515,353.07,289.76,5095119,5100573,,
3838,2021-07-19 23:34:20.896,2021-07-19 23:38:40.227,18.1,71,138,-35,409.55,406.79,63298.879142,63301.127007,2.24786500000482,4,1,20.8,525,523,409.55,406.79,5121999,5122764,,
3845,2021-07-20 18:30:14.515,2021-07-20 18:31:06.961,27.0,14,16,-1,388.90,388.90,63478.320998,63478.390015,0.0690169999943464,1,1,23.7,529,530,388.90,388.90,5137519,5137656,,
3848,2021-07-21 17:04:03.339557,,,,,,,,,,,,1,,,,,,,,,
3823,2021-07-19 16:03:32.822,2021-07-19 16:08:11.558,14.4,80,81,-62,289.07,284.93,63061.822771,63065.879995,4.05722400000377,5,1,21.0,515,516,289.07,284.93,5100575,5101276,,
3832,2021-07-19 20:17:43.915848,,,,,,,,,,,,1,,,,,,,,,
3836,2021-07-19 22:43:03.941,2021-07-19 22:48:15.08,16.9,53,48,-35,415.02,412.30,63296.304192,63298.767007,2.46281499999895,5,1,22.2,524,525,415.02,412.30,5120978,5121896,,
3840,2021-07-20 00:50:01.572,2021-07-20 00:53:33.102,18.6,63,43,-40,404.01,402.63,63301.775962,63303.450006,1.67404399999941,4,1,23.7,526,525,404.01,402.63,5123100,5123712,,
3852,2021-07-21 20:39:07.498,2021-07-21 20:47:14.801,28.1,79,61,-55,258.11,253.99,63550.451019,63556.038019,5.58699999999953,8,1,21.9,535,536,258.11,253.99,5147288,5147883,,
3853,2021-07-21 22:03:25.673,2021-07-21 22:47:57.405,30.0,137,312,-74,251.23,206.49,63556.038019,63604.422021,48.3840019999989,45,1,21.0,536,537,251.23,206.49,5147902,5151748,,
3864,2021-07-23 14:29:32.59,2021-07-23 14:37:49.852,15.4,108,102,-66,386.11,377.86,63901.900339,63909.087035,7.18669599999703,8,1,20.9,543,544,386.11,377.86,5184582,5186056,,
3866,2021-07-23 15:27:23.39,2021-07-23 16:11:50.375,18.3,135,98,-56,321.42,218.18,63954.347038,64032.323041,77.9760030000034,44,1,21.0,545,492,321.42,218.18,5189631,5196530,,
3824,2021-07-19 16:32:09.885,2021-07-19 16:41:52.656,14.8,68,72,-45,282.87,273.23,63065.846131,63075.059996,9.21386500000517,10,1,20.1,516,517,282.87,273.23,5101282,5101499,,
3825,2021-07-19 16:58:04.045,2021-07-19 17:04:00.373,16.4,79,70,-41,272.54,267.73,63075.019392,63079.349997,4.33060499999556,6,1,20.4,517,518,272.54,267.73,5101504,5102611,,
3841,2021-07-20 00:53:37.569,2021-07-20 00:53:44.766,18.5,0,3,1,402.66,402.66,63303.385306,63303.451007,0.0657010000068112,0,1,22.3,525,525,402.66,402.66,5123714,5123723,,
3844,2021-07-20 16:57:00.714,2021-07-20 18:04:30.357,25.1,121,94,-74,271.19,172.76,63388.0368,63478.279015,90.2422149999984,67,1,21.5,528,529,271.19,172.76,5127824,5137509,,
3856,2021-07-22 15:49:10.692628,,,,,,,,,,,,1,,,,,,,,,
3862,2021-07-22 20:47:38.794,2021-07-22 21:04:25.253,25.5,64,68,-47,101.86,99.80,63893.048947,63901.816035,8.76708800000051,17,1,21.3,542,543,101.86,99.80,5181875,5184266,,
3869,2021-07-23 18:38:59.17131,,,,,,,,,,,,1,,,,,,,,,
3873,2021-07-23 20:48:51.548,2021-07-23 22:15:41.094,31.2,143,302,-74,216.79,87.40,64421.396582,64543.277065,121.880483000001,87,1,21.2,294,9,216.79,87.40,5230746,5243362,18,
3833,2021-07-19 21:12:03.472615,,,,,,,,,,,,1,,,,,,,,,
3835,2021-07-19 22:19:27.439,2021-07-19 22:21:22.526,16.0,29,26,-10,416.40,415.71,63295.982323,63296.262006,0.279683000000659,2,1,23.3,523,524,416.40,415.71,5120715,5120972,,
3851,2021-07-21 19:33:35.172,2021-07-21 20:05:04.355,26.6,121,208,-64,306.97,266.38,63517.106189,63550.443019,33.3368300000002,31,1,21.8,532,535,306.97,266.38,5144929,5147280,,
3874,2021-07-23 22:22:58.856,2021-07-23 22:35:48.879,32.0,103,69,-73,87.40,72.95,64543.277065,64556.952067,13.6750019999963,13,1,21.2,9,6,87.40,72.95,5243366,5245603,,11
3881,2021-07-24 17:18:00.949,2021-07-24 17:19:11.99,20.2,18,5,-6,374.35,374.35,64572.653067,64572.800067,0.146999999997206,1,1,25.6,374,129,374.35,374.35,5248453,5248458,,
3837,2021-07-19 22:54:59.078,2021-07-19 22:56:03.077,17.5,8,8,1,412.30,412.30,63298.767007,63298.823007,0.0559999999968568,1,1,25.2,525,525,412.30,412.30,5121899,5121989,,
3843,2021-07-20 16:50:46.93,2021-07-20 16:54:46.552,22.5,100,41,-62,274.63,271.19,63383.886011,63388.029011,4.14299999999639,4,1,21.6,527,528,274.63,271.19,5127249,5127822,,
3846,2021-07-20 19:32:50.788,2021-07-20 19:42:29.935,30.3,114,160,-51,386.11,375.12,63478.320998,63487.066016,8.74501799999416,10,1,23.1,530,531,386.11,375.12,5137671,5139528,,
3858,2021-07-22 16:51:41.075,2021-07-22 18:56:40.82,21.7,135,141,-76,379.23,130.78,63664.982024,63883.915035,218.933011000001,125,1,21.1,540,541,379.23,130.78,5158209,5178890,,
3859,2021-07-22 18:57:24.581,2021-07-22 18:57:28.859,23.0,2,3,1,130.78,130.78,63883.875686,63883.915035,0.0393489999987651,0,1,21.5,541,541,130.78,130.78,5178892,5178905,,
3867,2021-07-23 16:29:39.69698,,,,,,,,,,,,1,,,,,,,,,
3877,2021-07-24 16:31:02.855,2021-07-24 16:48:35.457,25.9,58,31,-16,381.24,377.79,64571.289067,64572.553067,1.26400000000285,18,1,21.8,81,374,381.24,377.79,5248363,5248428,,
3883,2021-07-24 18:02:23.049,2021-07-24 18:13:13.512,25.2,105,73,-74,370.23,357.84,64574.928,64585.928067,11.0000670000009,11,1,21.5,16,1,370.23,357.84,5248692,5249540,,1
3850,2021-07-21 18:01:15.726,2021-07-21 18:12:41.834,25.2,87,86,-67,320.73,309.03,63508.093862,63517.033017,8.93915500000003,11,1,22.5,534,532,320.73,309.03,5143791,5144910,,
3854,2021-07-21 23:09:09.444,2021-07-21 23:24:00.278,28.9,98,93,-59,216.12,200.97,63604.422021,63618.546022,14.1240010000038,15,1,21.6,537,532,216.12,200.97,5151754,5153139,,
3863,2021-07-22 21:05:21.165,2021-07-22 21:06:04.81,26.5,6,6,1,99.10,99.10,63901.820035,63901.858034,0.0379990000001271,1,1,21.2,543,543,99.10,99.10,5184268,5184348,,
3868,2021-07-23 17:36:41.564,2021-07-23 18:19:58.118,25.9,121,80,-72,250.53,177.58,64142.054046,64214.45705,72.4030039999998,43,1,21.0,546,92,250.53,177.58,5207541,5214580,,
3880,2021-07-24 17:11:27.35,2021-07-24 17:12:49.195,21.4,3,2,1,375.04,375.04,64572.573066,64572.598067,0.0250010000017937,1,1,21.6,374,374,375.04,375.04,5248444,5248450,,
3882,2021-07-24 17:43:09.769,2021-07-24 17:49:16.915,20.3,66,40,-54,372.98,370.23,64572.810066,64574.998068,2.1880020000026,6,1,23.9,129,16,372.98,370.23,5248464,5248687,,

**Environment**

- TeslaMate version: 1.23.7
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu 20.04.2 LTS 
- User OS & Browser: macOS 11.5.  Safari 14.1.2
- Others:

**Comment by dyxyl** [comment]
It looks like data is missing from the drives table, because some of the drives are not terminated and the start_km is sometimes much larger than the previous recorded end_km. The total drive time is calculated from the drives table, so missing data will make this too low. Probably either the car or TeslaMate had connections problems with the Tesla servers.

**Comment by khorton** [comment]
We did make a few stops in places with no cell service, so that may explain this.  I would have hoped that the car would buffer output when it lost connectivity to the Tesla server, and then got caught up with data upload once connectivity is back.  Do we know how such conditions are handled by Tesla?

**Comment by dyxyl** [comment]
From my experience, the data generated when there is no cell service is just discarded (or at least TeslaMate doesn't see it).
