### ISSUE TITLE
Update release notes: new source required as Teslascope no longer providing

### ISSUE THREAD

**Issue by pmboothby** [adriankumpf/teslamate#1866]
The Updates page currently links to teslascope.com for release notes, but they seem to have stopped keeping the notes after 2020.48.35.5.  The only other site that I can find which keeps the release notes is notateslaapp.com. Their URLs include the release number so would be just as easy to link to as teslascope. 

Here's an example:
[https://www.notateslaapp.com/software-updates/version/2021.12.25/release-notes](https://www.notateslaapp.com/software-updates/version/2021.12.25/release-notes)

If anyone knows of a better source, please let me know or this weekend I'll create a Grafana code change + pull request with the new URL.

**Comment by tillepille** [comment]
For me the links still work:
<https://teslascope.com/teslapedia/software/2021.12.25.6> 
has release notes. 

I personally find the notateslapp notes a little unclear because they add up features from several versions in one post.

**Comment by pmboothby** [comment]
I've scrolled through teslsascope's release notes page https://teslascope.com/teslapedia/software/timeline. There are a lot of notes missing. I also think that the other site can be cumbersome to read, but it has most of the content.
