### ISSUE TITLE
How can I export teslameta data 

### ISSUE THREAD

**Issue by victorxys** [adriankumpf/teslamate#1867]
Hi guys , there are tow server that run teslameta ( the old one is server A  & the new one is server B). How can I transfer my old data from server A to server B  ?
Thank you!

**Comment by pmboothby** [comment]
Here is what I have used with Teslamate running on Docker. If you are not using Docker, remove `docker-compose exec -T database` from the beginning of each Postgres command. Note that the example below assumes the Postgres user is named _teslamate_ with the password _teslamate_. Edit as required.

On source machine, a 2-line script `dumpdb.sh` to export the data:
```
:
TIMESTAMP=`date +%Y%m%d%H%M`
docker-compose exec -T database pg_dump -U teslamate teslamate|gzip -cv > teslamate-${TIMESTAMP}.bck.gz`
```

On the target machine, the shell script `restoredb.sh` to import the data. The argument to this script is the name of the dump file that you created on the source server (e.g. `restoredb.sh teslamate-202106202038.bck.gz`).
```
:
docker-compose exec -T database psql -d teslamate -U teslamate << _EOF_
drop schema public cascade;
create schema public;
create extension cube;
create extension earthdistance;
CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
    RETURNS public.earth
    LANGUAGE SQL
    IMMUTABLE STRICT
    PARALLEL SAFE
    AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
_EOF_

# Restore
gunzip -c $1 | docker-compose exec -T database psql -d teslamate -U teslamate
```

**Comment by victorxys** [comment]
> Here is what I have used with Teslamate running on Docker. If you are not using Docker, remove `docker-compose exec -T database` from the beginning of each Postgres command. Note that the example below assumes the Postgres user is named _teslamate_ with the password _teslamate_. Edit as required.
> 
> On source machine, a 2-line script `dumpdb.sh` to export the data:
> 
> ```
> :
> TIMESTAMP=`date +%Y%m%d%H%M`
> docker-compose exec -T database pg_dump -U teslamate teslamate|gzip -cv > teslamate-${TIMESTAMP}.bck.gz`
> ```
> 
> On the target machine, the shell script `restoredb.sh` to import the data. The argument to this script is the name of the dump file that you created on the source server (e.g. `restoredb.sh teslamate-202106202038.bck.gz`).
> 
> ```
> :
> docker-compose exec -T database psql -d teslamate -U teslamate << _EOF_
> drop schema public cascade;
> create schema public;
> create extension cube;
> create extension earthdistance;
> CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
>     RETURNS public.earth
>     LANGUAGE SQL
>     IMMUTABLE STRICT
>     PARALLEL SAFE
>     AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
> _EOF_
> 
> # Restore
> gunzip -c $1 | docker-compose exec -T database psql -d teslamate -U teslamate
> ```

Vrey Nice!
I got it and succeed!
Thank you very much!

**Comment by binarious** [comment]
@pmboothby I get an error starting the container after the restore, because it tries to run the database migrations and fails, because functions, types and tables already exist. Any idea?

**Comment by pmboothby** [comment]
Hi @binarious. Was the application upgraded between dump and restore? I don't know the code well enough to answer, but that seems like an explanation.

**Comment by binarious** [comment]
I think I've imported the dump while the application was initializing. Tried a second time after some time of the first start and it worked. Thanks.
