### ISSUE TITLE
Feature request: config which items should be sent to mqtt

### ISSUE THREAD

**Issue by thomas70** [adriankumpf/teslamate#187]
**Describe the solution you'd like**
Should be possible to choose which items mqtt exposes

**Comment by adriankumpf** [comment]
Any particular reason why you need that? Do you want to disable existing topics or expose new topics?

**Comment by thomas70** [comment]
Expose new topics :-)

**Comment by adriankumpf** [comment]
Ok. It'd be easier If you could explicitly name the topics you need here: #182

**Comment by thomas70** [comment]
ok. I do that
