### ISSUE TITLE
Adjusting the drive timeperiod doesn’t change all graphs

### ISSUE THREAD

**Issue by gaardiolor** [adriankumpf/teslamate#1877]
Hello,

When going to grafana > drives > clicking a drive, after manually adjusting the end time, the top graph and map do update. But the distance, duration, energy used and consumption do not. 

I expect all graphs to update.

Please let me know if you see this too or if you need logs.

**Environment**

- TeslaMate version: 1.23.7
- Type of installation: Docker, graphana and postgres manual.
- OS TeslaMate is installed on: fedora core 34
- User OS & Browser: IOS Safari
- Others:

**Comment by hierro1981** [comment]
I think that other data and graphs are read from the drives table that have a summary of the trip stats, so when you change the start/end time of a drive it still look at that data and doesn't recalculate it.
I have different trip with wrong start time and so wrong stats, altought all data are present if you change the times.
A way to fix trip stats would be nice.

**Comment by DrMichael** [comment]
You're not supposed to update the time interval. :-)

The drive details is intended to give you an overview over **one** drive, given by the car_id in the URL.

( I think, we had that already. Suggestion was to use the Trip dashboard... @adriankumpf didn't we discuss to disable the interval selection?)

**Comment by gaardiolor** [comment]
Aah.. ok. In that case it could be nice to, in the trip dashboard:

- Graph speed and power, just like in the 'drive' dashboard 
- Move the bottom 2 graphs up, so the map can be shown in the same screen. That way when hovering over a graph, you can see the corresponding location on the map. (The standard laptopscreens are not big enough to display all the information)

**Comment by adriankumpf** [comment]
> ( I think, we had that already. Suggestion was to use the Trip dashboard... @adriankumpf didn't we discuss to disable the interval selection?)

I don't remember, probably, yes :D 

The only drawback with disabling the time picker entirely is that you can still zoom the graph with your mouse. The only way to undo that is to go back one page. Still a sensible approach though.
