### ISSUE TITLE
Error: column "base_url" and start_address.geofence_id does not exist

### ISSUE THREAD

**Issue by zelluz** [adriankumpf/teslamate#188]
Hello,

having a slight issue with postgresql (and therefore nothing will display in some of the Grafana views).

Getting the following messages in postgresql:

```
2019-10-02 16:59:31.496 CEST [50] ERROR: column "base_url" does not exist at character 8
2019-10-02 16:59:31.496 CEST [50] STATEMENT: select base_url from settings limit 1;
2019-10-02 16:59:32.382 CEST [50] ERROR: column start_address.geofence_id does not exist at character 2488
```
It seems that teslamate cant update the database with the new columns added in some of the newest version(s) somehow? I have added the teslamate database user as a superuser. Even tried running: 

```
/opt/app/bin $ ./teslamate eval "TeslaMate.Release.migrate"
17:11:16.823 [info] Already up
/opt/app/bin $
 ```

Everything else is working fine.

Thank you for a great software :)

edit: ah, I may have found out why this has happened. I am running version 1.9.1, not 1.10 - but the Grafana views I have are running the newest straight from github. Doh! I guess everything will be alright when 1.10 will be released :)

**Comment by adriankumpf** [comment]
I was really wondering how this could have happened. I'm glad you found the solution! :D
