### ISSUE TITLE
Error: Captcha does not match

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#1888]
Hi there,

Noticed teslamate information had not updated since yesterday.   Ran docker-compose pull to update, now I see the following error.  Confirmed login and password are correct by logging into the Tesla website.  

 Version 1.23.7.  Running docker installation on Linux Mint VM - which has been working properly for a over a year.

![image](https://user-images.githubusercontent.com/30555695/128494926-6bdfae15-e971-48c3-a2a8-ae0b0c40b4ab.png)

Log is as follows : 

Creating network "teslamate_default" with the default driver
Creating teslamate_grafana_1   ... done
Creating teslamate_database_1  ... done
Creating teslamate_teslamate_1 ... done
Creating teslamate_pgadmin_1   ... done
Attaching to teslamate_teslamate_1, teslamate_grafana_1, teslamate_database_1, teslamate_pgadmin_1
database_1   | 
database_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1   | 
database_1   | 2021-08-06 09:47:12.070 UTC [1] LOG:  starting PostgreSQL 12.7 (Debian 12.7-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
database_1   | 2021-08-06 09:47:12.071 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1   | 2021-08-06 09:47:12.072 UTC [1] LOG:  listening on IPv6 address "::", port 5432
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Starting Grafana" logger=server version=7.5.9 commit=cbffb81cab branch=HEAD compiled=2021-06-23T08:15:47+0000
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana-plugins"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana-plugins"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_ANALYTICS_REPORTING_ENABLED=FALSE"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_USER=admin"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_DISABLE_GRAVATAR=true"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ALLOW_EMBEDDING=true"
database_1   | 2021-08-06 09:47:12.076 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1   | 2021-08-06 09:47:12.098 UTC [27] LOG:  database system was shut down at 2021-08-06 09:46:15 UTC
database_1   | 2021-08-06 09:47:12.109 UTC [1] LOG:  database system is ready to accept connections
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_USERS_ALLOW_SIGN_UP=false"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ENABLED=true"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_AUTH_BASIC_ENABLED=false"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana-plugins
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="App mode production" logger=settings
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=/var/lib/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Starting DB migrations" logger=migrator
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=279 duration=711.119µs
database_1   | 2021-08-06 09:47:12.526 UTC [34] FATAL:  password authentication failed for user "odoo"
database_1   | 2021-08-06 09:47:12.526 UTC [34] DETAIL:  Role "odoo" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
grafana_1    | t=2021-08-06T09:47:11+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana_1    | t=2021-08-06T09:47:12+0000 lvl=info msg="Registering plugin" logger=plugins id=input
grafana_1    | t=2021-08-06T09:47:12+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-piechart-panel
grafana_1    | t=2021-08-06T09:47:12+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-map-panel
grafana_1    | t=2021-08-06T09:47:12+0000 lvl=info msg="Registering plugin" logger=plugins id=natel-discrete-panel
grafana_1    | t=2021-08-06T09:47:12+0000 lvl=info msg="Registering plugin" logger=plugins id=pr0ps-trackmap-panel
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386086Z","queryType":"exponential_heatmap_bucket_data"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386218Z","queryType":"linear_heatmap_bucket_data"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386292Z","queryType":"random_walk"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386565Z","queryType":"predictable_pulse"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386636Z","queryType":"predictable_csv_wave"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386714Z","queryType":"random_walk_table"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386782Z","queryType":"slow_query"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386903Z","queryType":"no_data_points"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.386973Z","queryType":"datapoints_outside_range"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387043Z","queryType":"manual_entry"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387111Z","queryType":"csv_metric_values"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387180Z","queryType":"streaming_client"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387196Z","queryType":"live"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387204Z","queryType":"grafana_api"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387211Z","queryType":"arrow"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387216Z","queryType":"annotations"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387221Z","queryType":"table_static"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387225Z","queryType":"random_walk_with_error"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387230Z","queryType":"server_error_500"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387234Z","queryType":"logs"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type handler","@timestamp":"2021-08-06T09:47:12.387246Z","queryType":"node_graph"}
grafana_1    | {"@level":"debug","@message":"datasource: registering query type fallback handler","@timestamp":"2021-08-06T09:47:12.387251Z"}
grafana_1    | t=2021-08-06T09:47:12+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
database_1   | 2021-08-06 09:47:13.119 UTC [36] FATAL:  password authentication failed for user "kong"
database_1   | 2021-08-06 09:47:13.119 UTC [36] DETAIL:  Role "kong" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:13.680 UTC [37] FATAL:  password authentication failed for user "root"
database_1   | 2021-08-06 09:47:13.680 UTC [37] DETAIL:  Role "root" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
pgadmin_1    | [2021-08-06 09:47:13 +0000] [1] [INFO] Starting gunicorn 19.9.0
pgadmin_1    | [2021-08-06 09:47:13 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pgadmin_1    | [2021-08-06 09:47:13 +0000] [1] [INFO] Using worker: threads
pgadmin_1    | [2021-08-06 09:47:13 +0000] [88] [INFO] Booting worker with pid: 88
teslamate_1  | 2021-08-06 09:47:13.948 [info] Migrations already up
database_1   | 2021-08-06 09:47:14.248 UTC [40] FATAL:  password authentication failed for user "admin"
database_1   | 2021-08-06 09:47:14.248 UTC [40] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:14.847 UTC [41] FATAL:  password authentication failed for user "test"
database_1   | 2021-08-06 09:47:14.847 UTC [41] DETAIL:  Role "test" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:15.450 UTC [42] FATAL:  password authentication failed for user "stolon"
database_1   | 2021-08-06 09:47:15.450 UTC [42] DETAIL:  Role "stolon" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:16.048 UTC [43] FATAL:  password authentication failed for user "developer"
database_1   | 2021-08-06 09:47:16.048 UTC [43] DETAIL:  Role "developer" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:16.637 UTC [44] FATAL:  password authentication failed for user "postgres"
database_1   | 2021-08-06 09:47:16.637 UTC [44] DETAIL:  Role "postgres" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:17.247 UTC [45] FATAL:  password authentication failed for user "odoo"
database_1   | 2021-08-06 09:47:17.247 UTC [45] DETAIL:  Role "odoo" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
teslamate_1  | 2021-08-06 09:47:17.413 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2021-08-06 09:47:17.413 [info] Version: 1.23.7
database_1   | 2021-08-06 09:47:17.822 UTC [56] FATAL:  password authentication failed for user "kong"
database_1   | 2021-08-06 09:47:17.822 UTC [56] DETAIL:  Role "kong" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
teslamate_1  | 2021-08-06 09:47:18.029 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (484.460 ms)
database_1   | 2021-08-06 09:47:18.406 UTC [57] FATAL:  password authentication failed for user "root"
database_1   | 2021-08-06 09:47:18.406 UTC [57] DETAIL:  Role "root" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
teslamate_1  | 2021-08-06 09:47:18.528 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (498.621 ms)
teslamate_1  | 2021-08-06 09:47:18.528 [info] Refreshed api tokens
teslamate_1  | 2021-08-06 09:47:18.531 [info] Scheduling token refresh in 5 wk 5 d
teslamate_1  | 2021-08-06 09:47:18.535 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2021-08-06 09:47:18.537 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2021-08-06 09:47:18.734 [info] Starting logger for 'Quicksilver'
teslamate_1  | 2021-08-06 09:47:18.760 [info] MQTT connection has been established
teslamate_1  | 2021-08-06 09:47:18.954 car_id=1 [info] Start / :asleep
database_1   | 2021-08-06 09:47:19.011 UTC [60] FATAL:  password authentication failed for user "admin"
database_1   | 2021-08-06 09:47:19.011 UTC [60] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:19.621 UTC [63] FATAL:  password authentication failed for user "test"
database_1   | 2021-08-06 09:47:19.621 UTC [63] DETAIL:  Role "test" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:20.226 UTC [64] FATAL:  password authentication failed for user "stolon"
database_1   | 2021-08-06 09:47:20.226 UTC [64] DETAIL:  Role "stolon" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
teslamate_1  | 2021-08-06 09:47:20.731 [info] tzdata release in place is from a file last modified Tue, 22 Dec 2020 23:35:21 GMT. Release file on server was last modified Sun, 24 Jan 2021 19:35:23 GMT.
database_1   | 2021-08-06 09:47:20.786 UTC [65] FATAL:  password authentication failed for user "developer"
database_1   | 2021-08-06 09:47:20.786 UTC [65] DETAIL:  Role "developer" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:21.355 UTC [66] FATAL:  password authentication failed for user "postgres"
database_1   | 2021-08-06 09:47:21.355 UTC [66] DETAIL:  Role "postgres" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
teslamate_1  | 2021-08-06 09:47:21.595 [info] Tzdata has updated the release from 2020e to 2021a
database_1   | 2021-08-06 09:47:21.935 UTC [67] FATAL:  password authentication failed for user "odoo"
database_1   | 2021-08-06 09:47:21.935 UTC [67] DETAIL:  Role "odoo" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:22.518 UTC [68] FATAL:  password authentication failed for user "kong"
database_1   | 2021-08-06 09:47:22.518 UTC [68] DETAIL:  Role "kong" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:23.088 UTC [69] FATAL:  password authentication failed for user "root"
database_1   | 2021-08-06 09:47:23.088 UTC [69] DETAIL:  Role "root" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:23.652 UTC [70] FATAL:  password authentication failed for user "admin"
database_1   | 2021-08-06 09:47:23.652 UTC [70] DETAIL:  Role "admin" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:24.220 UTC [71] FATAL:  password authentication failed for user "test"
database_1   | 2021-08-06 09:47:24.220 UTC [71] DETAIL:  Role "test" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:24.801 UTC [72] FATAL:  password authentication failed for user "stolon"
database_1   | 2021-08-06 09:47:24.801 UTC [72] DETAIL:  Role "stolon" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:25.384 UTC [73] FATAL:  password authentication failed for user "developer"
database_1   | 2021-08-06 09:47:25.384 UTC [73] DETAIL:  Role "developer" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
database_1   | 2021-08-06 09:47:25.986 UTC [74] FATAL:  password authentication failed for user "postgres"
database_1   | 2021-08-06 09:47:25.986 UTC [74] DETAIL:  Role "postgres" does not exist.

**Comment by jun3280net** [comment]
Just an update, I used pgAdmin and queried the Tokens table (select * from tokens) table to get the ACCESS and REFRESH codes.  I then logged in using the "existing API tokens"

![image](https://user-images.githubusercontent.com/30555695/128568082-340db962-0bf3-4890-8e3c-b322e4964edc.png)

**Comment by withanhdammit** [comment]
How do you log into pgadmin?  I installed using the instructions for the docker container, then found a docker container for pgadmin4 https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html

But I don't know what username/password to use. I tried 'teslamate' and 'secret', but it says not valid
![image](https://user-images.githubusercontent.com/16404870/128608660-08f3719a-cbc6-49e4-8317-a8c113989d65.png)

**Comment by denrou** [comment]
Same here, fresh install with docker and impossible to connect.

**Comment by RaceMouse-of-Denmark** [comment]
Same here. Fresh Docker install. Anyone with great ideas?

**Comment by jun3280net** [comment]
I've never used these apps before, but apparently it works and is recommended by Teslascope : 
[https://teslascope.com/help/generating-tokens](https://teslascope.com/help/generating-tokens)

I hope that helps.

**Comment by qohjjang** [comment]
Same, fresh install - Error: Captcha does not match
Thought I did something wrong but seems it doesn't matter if right or wrong password.

**Comment by RaceMouse-of-Denmark** [comment]
@jun3280net : 
Thanks for the insanely fast response. Yu suggestion worked for me. I had to wake up the car first using the app before the tokens wew accepted... Have a nice day :-)

**Comment by withanhdammit** [comment]
> I've never used these apps before, but apparently it works and is recommended by Teslascope :
> https://teslascope.com/help/generating-tokens
> 
> I hope that helps.

That worked perfectly, thanks so much for replying!

**Comment by originalprime** [comment]
Wanted to chime in to say I'm seeing the same thing. I've had an install running for about nine months now and I haven't experienced this issue before updating the docker container to 1.23.7.

I can pull logs if it's helpful, but I am not sure how to do that inside a container.

**Comment by alt064** [comment]
I could be wrong, but I just logged in direct to tesla site and it is (now) prompting for a captcha, whereas it did not do this last time I logged in a few days/weeks ago. I expect that may be the cause? teslamate may need a code update to handle that additional prompt. I disabled MFA on my Tesla account (temporarily) but that doesn't change the captcha behaviour, just removed the subsequent authy / token request.

**Comment by withanhdammit** [comment]
> I could be wrong, but I just logged in direct to tesla site and it is (now) prompting for a captcha, whereas it did not do this last time I logged in a few days/weeks ago. I expect that may be the cause? teslamate may need a code update to handle that additional prompt. I disabled MFA on my Tesla account (temporarily) but that doesn't change the captcha behaviour, just removed the subsequent authy / token request.
> [Edit] plus one for the teslascope work-around, as long as you're comfortable with installing an unknown app and then submitting Tesla credentials using it!

Interesting.  I just logged into the tesla.com site and did not get prompted for a Captcha.  Of course, I may have already done that, and my TeslaMate install is on a Debian VM, so it would not have the Captcha cookie.

**Comment by alt064** [comment]
@withanhdammit - nor does mine, now, if I log out and back in to tesla.com. As you say, it may be a cookie is now stored so the captcha step is skipped. When I have some more time I will flush my (firefox) browser cache and retry.

**Comment by martangelo** [comment]
Got the same issue here, with a fresh install (so can't use the API tockens :( ).
Did some tests:
- Logged into tesla.com from my laptop and no captcha was requested
- Logged into tesla.com from a raspberrypi and yes the captcha was requested
- Installed Teslamate both on laptop and raspberry and both had the same issue
- Installed 1.23.6 and still got captcha error
- Tried with and without MFA and as expected there is no difference

**Comment by alt064** [comment]
@withanhdammit @a1btd @adriankumpf
So, restarting firefox with cleared cache causes tesla.com to prompt for a new captcha, confirming it is storing a cookie or similar, once completed. This would seem to suggest that the other API log ins (teslamate, etc) need to cope with that requirement as well. Tesla seem determined to keep third party apps on the hop, it seems! Meantime, if you can aquire the API token, via the Tesla Tokens app or similar, that work-around is effective for now.

**Comment by fynnsh** [comment]
Same error here on new installation...

**Comment by chrispontiga** [comment]
To work around the "Error: Captcha does not match." issue, generate a new token with a third party app and then input that in lieu of your account credentials.

**Comment by SiNaPsEr0x** [comment]
when will the teslamate bug be fixed?

**Comment by clarsen** [comment]
> Is there any solution to this issue, or do we have to resort to generating our own tokens to access? If someone can comment on the best way to LOCALLY generate a token or refresh token, that would be appreciated. I am not sure about trusting 3rd party apps to generate the token.

I can confirm that using https://github.com/tdorssers/TeslaPy to login and list vehicles for example (and in the process doing captcha authentication) and then taking the ownerapi access token and SSO refresh token out of the cache.json will work.

As noted here https://tesla-api.timdorr.com/api-basics/authentication#refreshing-an-access-token the refresh token must be from the SSO interaction.

Probably a UI dialog to show the captcha would be the more elegant option.

**Comment by ampjunkie** [comment]
> > Is there any solution to this issue, or do we have to resort to generating our own tokens to access? If someone can comment on the best way to LOCALLY generate a token or refresh token, that would be appreciated. I am not sure about trusting 3rd party apps to generate the token.
> 
> I can confirm that using https://github.com/tdorssers/TeslaPy to login and list vehicles for example (and in the process doing captcha authentication) and then taking the ownerapi access token and SSO refresh token out of the cache.json will work.
> 
> As noted here https://tesla-api.timdorr.com/api-basics/authentication#refreshing-an-access-token the refresh token must be from the SSO interaction.
> 
> Probably a UI dialog to show the captcha would be the more elegant option.

So I installed TeslaPy and it seems to be working, but have not logged in yet. Once I do, where is the cache.json located (path), and does it still exist after I logout?

**Comment by clarsen** [comment]
> > > Is there any solution to this issue, or do we have to resort to generating our own tokens to access? If someone can comment on the best way to LOCALLY generate a token or refresh token, that would be appreciated. I am not sure about trusting 3rd party apps to generate the token.
> > 
> > 
> > I can confirm that using https://github.com/tdorssers/TeslaPy to login and list vehicles for example (and in the process doing captcha authentication) and then taking the ownerapi access token and SSO refresh token out of the cache.json will work.
> > As noted here https://tesla-api.timdorr.com/api-basics/authentication#refreshing-an-access-token the refresh token must be from the SSO interaction.
> > Probably a UI dialog to show the captcha would be the more elegant option.
> 
> So I installed TeslaPy and it seems to be working, but have not logged in yet. Once I do, where is the cache.json located (path), and does it still exist after I logout?

cache.json is written into the current working directory.  you can use `jq` to pretty print the contents.  I don't think it is ever explicitly removed.

**Comment by ampjunkie** [comment]
Great -- thanks very much for your help!

**Comment by macener** [comment]
Yes, at the moment, the way to get tokens worked for me as follows:

`python -m pip install teslapy`

Then I a very small python script: 
import teslapy

with teslapy.Tesla('your-mail@example.com', 'password') as tesla:
	tesla.fetch_token()
	print("access token: ", tesla.sso_token["access_token"])
	print("refresh token: ", tesla.sso_token["refresh_token"])

Copy paste tokens.

**Comment by adriankumpf** [comment]
The docker image published under the `edge` tag includes a fix for Tesla's updated login flow. Feel free to test that until v1.24 is officially released.

**Comment by dirkjanm** [comment]
tested that version, works fine for me!

**Comment by a1btd** [comment]
I have also tested it and works perfectly 😃

**Comment by sam-jeffs** [comment]
Me 3! Thanks for the fast fix!

**Comment by way0utwest** [comment]
FWIW, installed and ran latest today (22 Sep 21) and got the captcha error. Composed down, changed to "edge" and still go the error.

I downloaded the Tesla Tokens app, used that, and was able to log in with the tokens returned to me. The tokens are long, so I used messages.google.com to text them to myself ;)

**Comment by jwall87** [comment]
> 
> 
> > I've never used these apps before, but apparently it works and is recommended by Teslascope :
> > https://teslascope.com/help/generating-tokens
> > I hope that helps.
> 
> That worked perfectly, thanks so much for replying!

Worked, thanks! Make sure you copy in the correct order. They are flipped in the app.
