### ISSUE TITLE
(ArgumentError) nil given for :vin

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#189]
Hi @adriankumpf.  I haven't changed any password, and aside from Teslamate - I don't think there are any other services that use the tokens. On a separate note, I did a docker-compose pull.....and now when I try and run Teslamate, I get the following.  It is asking that I sign in again-is there a way to force my credentials/auth token in - prior to running docker-compose up?

:00.632 [info] Access TeslaMateWeb.Endpoint at http://192.168.14.50
teslamate_1 | 21:30:00.677 [info] Adding elevation to 512 positions ...
teslamate_1 | 21:30:00.728 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1 | 21:30:01.085 [warn] Please sign in again.
teslamate_1 |
teslamate_1 | %TeslaApi.Error{
teslamate_1 | env: %Tesla.Env{
teslamate_1 | client: %Tesla.Client{
teslamate_1 | adapter: {Tesla.Adapter.Hackney, :call, [[recv_timeout: 30000]]},
teslamate_1 | fun: nil,
teslamate_1 | post: [],
teslamate_1 | pre: [
teslamate_1 | {Tesla.Middleware.BaseUrl, :call,
teslamate_1 | ["https://owner-api.teslamotors.com/"]},
teslamate_1 | {Tesla.Middleware.Headers, :call,
teslamate_1 | [[{"user-agent", "github.com/mgwidmann/tesla_api"}]]},
teslamate_1 | {Tesla.Middleware.JSON, :call, [[]]},
teslamate_1 | {Tesla.Middleware.Headers, :call,
teslamate_1 | [
teslamate_1 | [
teslamate_1 | {"Authorization",
teslamate_1 | "Bearer xxx"}
teslamate_1 | ]
teslamate_1 | ]}
teslamate_1 | ]
teslamate_1 | },
teslamate_1 | module: Tesla,
teslamate_1 | body: %{
teslamate_1 | "error" => "invalid_grant",
teslamate_1 | "error_description" => "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
teslamate_1 | },
teslamate_1 | headers: [
teslamate_1 | {"server", "nginx"},
teslamate_1 | {"date", "Wed, 02 Oct 2019 03:30:01 GMT"},
teslamate_1 | {"content-type", "application/json; charset=utf-8"},
teslamate_1 | {"transfer-encoding", "chunked"},
teslamate_1 | {"connection", "keep-alive"},
teslamate_1 | {"x-frame-options", "SAMEORIGIN"},
teslamate_1 | {"x-xss-protection", "1; mode=block"},
teslamate_1 | {"x-content-type-options", "nosniff"},
teslamate_1 | {"cache-control", "no-store"},
teslamate_1 | {"pragma", "no-cache"},
teslamate_1 | {"www-authenticate",
teslamate_1 | "Bearer realm="Doorkeeper", error="invalid_grant", error_description="The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.""},
teslamate_1 | {"x-request-id", "yyy"},
teslamate_1 | {"x-runtime", "0.007053"}
teslamate_1 | ],
teslamate_1 | method: :post,
teslamate_1 | opts: [],
teslamate_1 | query: [],
teslamate_1 | status: 401,
teslamate_1 | url: "https://owner-api.teslamotors.com/oauth/token"
teslamate_1 | },
teslamate_1 | error: :authentication_failure,
teslamate_1 | message: "Failed to authenticate."
teslamate_1 | }
teslamate_1 | 21:30:01.095 [info] Found ''
teslamate_1 | 21:30:01.114 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Vehicles
teslamate_1 | ** (EXIT) an exception was raised:
teslamate_1 | ** (ArgumentError) nil given for :vin. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.vin)
teslamate_1 | (ecto) lib/ecto/query/builder/filter.ex:128: Ecto.Query.Builder.Filter.kw!/7
teslamate_1 | (ecto) lib/ecto/query/builder/filter.ex:121: Ecto.Query.Builder.Filter.kw!/3
teslamate_1 | (ecto) lib/ecto/query/builder/filter.ex:103: Ecto.Query.Builder.Filter.filter!/6
teslamate_1 | (ecto) lib/ecto/query/builder/filter.ex:115: Ecto.Query.Builder.Filter.filter!/7
teslamate_1 | (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.get_by/4
teslamate_1 | (teslamate) lib/teslamate/vehicles.ex:72: TeslaMate.Vehicles.create_or_update!/1
teslamate_1 | (teslamate) lib/teslamate/vehicles.ex:26: anonymous fn/2 in TeslaMate.Vehicles.init/1
teslamate_1 | (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
teslamate_1 | {"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{#{'exception' => true,'struct' => 'Elixir.ArgumentError',message => <<"nil given for :vin. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.vin)">>},[{'Elixir.Ecto.Query.Builder.Filter','kw!',7,[{file,"lib/ecto/query/builder/filter.ex"},{line,128}]},{'Elixir.Ecto.Query.Builder.Filter','kw!',3,[{file,"lib/ecto/query/builder/filter.ex"},{line,121}]},{'Elixir.Ecto.Query.Builder.Filter','filter!',6,[{file,"lib/ecto/query/builder/filter.ex"},{line,103}]},{'Elixir.Ecto.Query.Builder.Filter','filter!',7,[{file,"lib/ecto/query/builder/filter.ex"},{line,115}]},{'Elixir.Ecto.Repo.Queryable',get_by,4,[{file,"lib/ecto/repo/queryable.ex"},{line,40}]},{'Elixir.TeslaMate.Vehicles','create_or_update!',1,[{file,"lib/teslamate/vehicles.ex"},{line,72}]},{'Elixir.TeslaMate.Vehicles','-init/1-fun-0-',2,[{file,"lib/teslamate/vehicles.ex"},{line,26}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1336}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
teslamate_1 | Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Vehicles',{#{'exception' => true,'struct' => 'Elixir.Ar
teslamate_1 |
teslamate_1 | Crash dump is being written to: erl_crash.dump...done
db_1 | 2019-10-02 03:30:04.762 UTC [53] LOG: incomplete startup packet

**Comment by adriankumpf** [comment]
Okay, this should not have happened and I'm not sure how the VIN could become `nil`. I'll include a fix in the next release that will be released shortly.

To quickly work around the bug, could you manually update the database entry of your car? I will be happy to assist if you'd like.

**Comment by jun3280net** [comment]
> Okay, this should not have happened and I'm not sure how the VIN could become `nil`. I'll include a fix in the next release that will be released shortly.
> 
> To quickly work around the bug, could you manually update the database entry of your car? I will be happy to assist if you'd like.

@adriankumpf  thanks as always for your help.  If you have any steps to update the DB ... I'm happy to give it a try.  Is there anyway to backup the DB to make sure I can restore it if I've broken anything?  I'd like to keep the data I've compiled so far.

Thanks,

J

**Comment by adriankumpf** [comment]
You won't break anything!

Run the following commands in the same directory as the `docker-compose.yml` file:

1. Connect to the database container:

```bash
docker-compose exec db psql teslamate teslamate
```

2. Set a temporary VIN:

```sql
SELECT * from cars;
UPDATE cars SET vin = '0';
```

**Comment by jun3280net** [comment]
> You won't break anything!
> 
> Run the following commands in the same directory as the `docker-compose.yml` file:
> 
> 1. Connect to the database container:
> 
> ```shell
> docker-compose exec db psql teslamate teslamate
> ```
> 
> 1. Set a temporary VIN:
> 
> ```sql
> SELECT * from cars;
> UPDATE cars SET vin = '0';
> ```
> 
> 1. Restart

@adriankumpf I've run 1.  Unfortunately I get the error : No container found for db_1

For context my YML file is in my Desktop/Teslamate/ Folder

**Comment by adriankumpf** [comment]
Do you use the "Advanced setup"? In this case the database container was named "database" so the first command should look like this:

```bash
docker-compose exec database psql teslamate teslamate
```

**Comment by jun3280net** [comment]
> Do you use the "Advanced setup"? In this case the database container was named "database" so the first command should look like this:
> 
> ```shell
> docker-compose exec database psql teslamate teslamate
> ```

@adriankumpf  I used your suggested YML method.  This is what I see in my YML file : 
services : 
     teslamate : 
          image: teslamate/teslamate:latest
          restart: unless-stopped
          environment : 
               -DATABASE_USER=teslamate
               -DATABASE_PASS=secret
               -DATABASE_NAME=teslamate
               -DATABASE_HOST=db
               -MQTT_HOST=mosquitto
               -VIRTUAL_HOST=192.168.86.50

**Comment by adriankumpf** [comment]
I overlooked that the containers aren't running right now.

Try to run this first:

```bash
docker-compose up -d db
```

**Comment by jun3280net** [comment]
> I overlooked that the containers aren't running right now.
> 
> Try to run this first:
> 
> ```shell
> docker-compose up -d db
> ```

@adriankumpf -Perfect!  Server is back up, and I was able to login to 192.168.86.50:4000.  I think that means I'm back up and running.  Hope to see some fresh data being captured when I drive home shortly! Thanks!

**Comment by adriankumpf** [comment]
Awesome! 👍

**Comment by jun3280net** [comment]
> Awesome! 👍

@adriankumpf - there is one issue though.  It appears all my past data points are missing.  Is there anyway to confirm whether the data still exists somewhere?  Thanks
