### ISSUE TITLE
Once again Tesla breaks token refresh and new token generation

### ISSUE THREAD

**Issue by IMgoRt** [adriankumpf/teslamate#1910]
Happily running for 2 years, upgrading regularly.
Yesterday my token expired and the internal refresh function has broken.
I tried manually signing back into my tesla account (in TM) without success, also failed is adding known good tokens to the advanced page.
I have MFA enabled on my account but never get prompted for this in TM, I don't get presented with captcha when signing into my account on tesla.com

Version 1.23.7 running on my own server behind a random VPN exiting in the UK

**Comment by corbosman** [comment]
I moved my home install from docker-compose to Kubernetes yesterday and could not login anymore, even with a 100% correct login/pass. The trick for me was to get an Auth app for tesla (literally called "Auth App For Tesla". That gives you a token and refresh token, and with that I could login again.

**Comment by IMgoRt** [comment]
> I moved my home install from docker-compose to Kubernetes yesterday and could not login anymore, even with a 100% correct login/pass. The trick for me was to get an Auth app for tesla (literally called "Auth App For Tesla". That gives you a token and refresh token, and with that I could login again.

I already tried using tokens generated elsewhere, I've tried that again without success.
Externally generated tokens work fine on my nodered instance, but are "invalid" in TM, the log shows this
`2021-08-16 07:26:15.753 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "timeout" (60280.580 ms)`

**Comment by dmelliott20** [comment]
Same here. Getting non existent domain on the cred login and Error: Tokens are invalid on the token login

**Comment by aiden-cat** [comment]
New TeslaMate user that just getting things set up... got this error that I believe is related (although could be due to me not setting it up correctly?):
![adb76e4f63ee8b1e6669dc2ce5a798a](https://user-images.githubusercontent.com/63931544/129664639-e8a57a54-32b1-491f-b241-da94ad8ea1c5.png)

**Comment by bahree** [comment]
So I had to reinstall a pi, and with a fresh install, I am getting this error now. I know the setup is correct. I have another instance running on the same network (on another machine) which is working OK, so something Tesla has changed on their back end. 

Anything I can help try and debug and share the logs?

Here is what I see in the docker logs:
![image](https://user-images.githubusercontent.com/3529468/129843178-95a29356-a0a9-439a-984b-4256193dac81.png)

And I get the same error.

**Comment by bfoz** [comment]
FWIW, I'm also seeing the "Error: Captcha does not match" problem with version 1.23.7

**Comment by aiden-cat** [comment]
> FWIW, I'm also seeing the "Error: Captcha does not match" problem with version 1.23.7

@bfoz Using API access/refresh token I was able to log in!

**Comment by IMgoRt** [comment]
> > FWIW, I'm also seeing the "Error: Captcha does not match" problem with version 1.23.7
> 
> @bfoz Using API access/refresh token I was able to log in!

When was that as it isn't working for me?
Thanks

**Comment by aiden-cat** [comment]
> > > FWIW, I'm also seeing the "Error: Captcha does not match" problem with version 1.23.7
> > 
> > 
> > @bfoz Using API access/refresh token I was able to log in!
> 
> When was that as it isn't working for me?
> Thanks

As of two days ago I generated the token using the Auth App for Tesla.  If you know of a process to generate token ourselves without relying on an app that'd be appreciated!  Def would like to not rely on an app for token generation... for all the other solution I googled didn't work

**Comment by IMgoRt** [comment]
> > > > FWIW, I'm also seeing the "Error: Captcha does not match" problem with version 1.23.7
> > > 
> > > 
> > > @bfoz Using API access/refresh token I was able to log in!
> > 
> > 
> > When was that as it isn't working for me?
> > Thanks
> 
> As of two days ago I generated the token using the Auth App for Tesla. If you know of a process to generate token ourselves without relying on an app that'd be appreciated! Def would like to not rely on an app for token generation... for all the other solution I googled didn't work

That doesn't work for me - I can generate a new token that TM rejects but I can then use in my own code or I can try a token that I've been using but that also gets rejected by TM.
(Separately my code has been unable to get refresh working so I have to generate a new token every 45 days)

**Comment by p2cardon** [comment]
> > > > FWIW, I'm also seeing the "Error: Captcha does not match" problem with version 1.23.7
> > > 
> > > 
> > > @bfoz Using API access/refresh token I was able to log in!
> > 
> > 
> > When was that as it isn't working for me?
> > Thanks
> 
> As of two days ago I generated the token using the Auth App for Tesla. If you know of a process to generate token ourselves without relying on an app that'd be appreciated! Def would like to not rely on an app for token generation... for all the other solution I googled didn't work

I confirm that auth app works fine for me … there is no captcha error or display … I don't know if this app handles captcha requests …
In my case, I have not enabled the 2 factors authentification with my Tesla account … is this "detail" important ?

**Comment by IMgoRt** [comment]
> > > > > FWIW, I'm also seeing the "Error: Captcha does not match" problem with version 1.23.7
> > > > 
> > > > 
> > > > @bfoz Using API access/refresh token I was able to log in!
> > > 
> > > 
> > > When was that as it isn't working for me?
> > > Thanks
> > 
> > 
> > As of two days ago I generated the token using the Auth App for Tesla. If you know of a process to generate token ourselves without relying on an app that'd be appreciated! Def would like to not rely on an app for token generation... for all the other solution I googled didn't work
> 
> I confirm that auth app works fine for me … there is no captcha error or display … I don't know if this app handles captcha requests …
> In my case, I have not enabled the 2 factors authentification with my Tesla account … is this "detail" important ?

MFA could be the issue as I have that enabled (but have done since Tesla first added the feature)

**Comment by IMgoRt** [comment]
OK, so I stopped routing via my VPN and have been able to get authorised, very strange

**Comment by bfoz** [comment]
> > FWIW, I'm also seeing the "Error: Captcha does not match" problem with version 1.23.7
> 
> @bfoz Using API access/refresh token I was able to log in!

I finally got it working too. I'm not sure what the problem was.

For posterity, I used the Teslascope instructions linked in the comments of #1888 (https://teslascope.com/help/generating-tokens).

**Comment by zombieregime** [comment]
> OK, so I stopped routing via my VPN and have been able to get authorised, very strange

Its not uncommon for backends to be picky about IP blocks known to belong to VPN services since they can be used by ne'er do wells and ban evaders and the like. "But Im a good guy, not some hacker!" which may be true, but how would any node along the path, including the destination service, know bad guy traffic from good guy traffic coming out of the same exit node without running a transparent proxie attack and inspecting each packet? Answer: you dont. If its a known VPN provider routing you through an exit node that is filtered on some level by either tesla or the virtual compute farms/'cloud' their services run on for some reason (either due to a blanket rule towards VPN providers, or trouble with some s'kiddy using that provider before to cause issues) that could be a reason for the connection over the VPN failing to authenticate. Or possibly something to do with how they generate the authentication, like using your public facing IP (which from your end might be the router IP to the internet, not the VPNs exit node depending on how your network and computer are configured) or some other thing finger-printable to compute a token which doesnt end up passing muster once its decoded on the other side. I noticed on the old solarcity login they check what fonts are installed, and if the page can run various audio and video file types as (what I imagine to be) part of the finger printing process to uniquely identify devices, for some reason (IIRC the script file name in chrome inspector was 'twinkle'). I have no special knowledge of teslas security, just passing along some areas of interest regarding internet security practices to look into if anyone wants to poke at the issue more.
