### ISSUE TITLE
Can' receive data of Tesla_shift_state from MQTT

### ISSUE THREAD

**Issue by crathyd** [adriankumpf/teslamate#1912]
Listen the topic with "teslamate/cars/1/shift_state" but no data response;
but other topics are good like "teslamate/cars/1/vision"
<img width="620" alt="截屏2021-08-17 下午6 07 15" src="https://user-images.githubusercontent.com/13013658/129707508-11cbe60a-178b-4a97-b16a-29716e492c18.png">

**Comment by cryptelli** [comment]
I'm also encountering this issue, where MQTT reports the shift_state when set to something like D, P, R etc but when it stops, the value is wiped and the previous value can no longer be seen.
