### ISSUE TITLE
Grafana not loading in v1.10.0

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#193]
Hi, @adriankumpf just pulled the latest, and when I start with docker-compose, saw that Grafana wasn't starting. And here is what the error I get:

grafana_1    | /run.sh: line 75: /usr/share/grafana/bin/grafana-cli: No such file or directory
teslamate_grafana_1 exited with code 127

And pulling it again doesnt' fix it - any ideas on what is missing?

Thanks,
Amit.

**Comment by bahree** [comment]
I tried restarting a few times, and rebooting too but each time I get the following error:

```
/run.sh: line 75: /usr/share/grafana/bin/grafana-cli: No such file or directory
/run.sh: line 75: /usr/share/grafana/bin/grafana-cli: No such file or directory
/run.sh: line 75: /usr/share/grafana/bin/grafana-cli: No such file or directory
/run.sh: line 75: /usr/share/grafana/bin/grafana-cli: No such file or directory
/run.sh: line 75: /usr/share/grafana/bin/grafana-cli: No such file or directory
/run.sh: line 75: /usr/share/grafana/bin/grafana-cli: No such file or directory
/run.sh: line 75: /usr/share/grafana/bin/grafana-cli: No such file or directory

```

**Comment by adriankumpf** [comment]
The latest Grafana docker image seems to have issues on ARM: grafana/grafana#19585. I downgraded to v6.3.5 and published a new image to DockerHub. Does it work after pulling the latest image?

**Comment by DBemis** [comment]
> The latest Grafana docker image seems to have issues on ARM: [grafana/grafana#19585](https://github.com/grafana/grafana/issues/19585). I downgraded to v6.3.5 and published a new image to DockerHub. Does it work after pulling the latest image?

I was getting the same errors. Just pulled latest and it all works now - thank you @adriankumpf !

**Comment by mapchen** [comment]
> The latest Grafana docker image seems to have issues on ARM: [grafana/grafana#19585](https://github.com/grafana/grafana/issues/19585). I downgraded to v6.3.5 and published a new image to DockerHub. Does it work after pulling the latest image?

works thanks @adriankumpf

**Comment by bahree** [comment]
OK, that fixed it - many thanks!
