### ISSUE TITLE
Buggy "Charge Level" diagram

### ISSUE THREAD

**Issue by Kosta-Github** [adriankumpf/teslamate#1935]
**Describe the bug**

The graph for current `Charge Level` shows weird data:

![image](https://user-images.githubusercontent.com/2526664/131255454-a5a4934c-1501-4db3-9faf-f4512f29eee8.png)

This is because the DB is returning values not properly ordered by timestamp:

![image](https://user-images.githubusercontent.com/2526664/131255573-1c815f5e-88de-4db0-a9c7-8a6cbc734a11.png)

**Expected behavior**

A clean looking graph :-)

![image](https://user-images.githubusercontent.com/2526664/131255651-496c6c89-737d-4241-a4bc-aadfb7107c7c.png)

This can be achieved by adding `ORDER BY Time ASC` to the actual query.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure, how to reproduce this, since this only happens for my 2nd car; the first car hasn't shown this behaviour for the last year...

**Environment**

- TeslaMate version: `1.24.0-dev`
- Type of installation: `Docker`
- OS TeslaMate is installed on: `raspi`
- User OS & Browser: `chrome on MacOS`
- Others: ...

**Comment by DrMichael** [comment]
I created a PR https://github.com/adriankumpf/teslamate/pull/1936
