### ISSUE TITLE
Grafana stopped working after update

### ISSUE THREAD

**Issue by Dominoo** [adriankumpf/teslamate#1939]
Hello, 

I ran update after a while (I have docker setup) with
down / pull / up

and from then grafana stopped working, 

Templating [car_id]
Error updating options: pq: column "display_priority" does not exist

it seems like i have to run migrations manually? Or I jumped through many versions?

**Comment by justinharringa** [comment]
@Dominoo did you figure out the resolution to this? I'm assuming you may have run a migration or changed queries?

**Comment by yhfy2006** [comment]
Hi, could you please let me know how did you fix this?

**Comment by justinharringa** [comment]
@yhfy2006 Typically the database migrations should fix it up for you. Are you using docker-compose? https://docs.teslamate.org/docs/upgrading should work. I don't use docker-compose and just restarted the app again.

**Comment by yhfy2006** [comment]
awesome thank you!
