### ISSUE TITLE
Sign in page not working over SSL tunnel

### ISSUE THREAD

**Issue by krezac** [adriankumpf/teslamate#194]
**Describe the bug**

I§m not sure if this is bug or feature.

I'm using SSL tunnel to access teslamate from outside of home network. The gateway server is different machine than docker server running teslamate.
(screenshot from putty on win, the same issue with command line ssh on mac).

![image](https://user-images.githubusercontent.com/16595657/66265583-5d616080-e819-11e9-93c9-4dce962b8b22.png)

When I reach http://localhost:40000/sign_in
I see spinner overlay and sign in is blocked. In console, I see following error:
WebSocket connection to 'ws://localhost:40000/live/websocket?baseUrl=http%3A%2F%2Flocalhost%3A40000&vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403

![image](https://user-images.githubusercontent.com/16595657/66265627-158f0900-e81a-11e9-98ad-eab0088fe51b.png)

I don't think it's caused by ssh setting. Some anti-XSS protection, maybe?
Thanks for checking.

**Comment by adriankumpf** [comment]
The logs have the answer to your question ;)

```
teslamate_1  | [error] Could not check origin for Phoenix.Socket transport.
teslamate_1  |
teslamate_1  | Origin of the request: http://localhost:40000
teslamate_1  |
teslamate_1  | This happens when you are attempting a socket connection to
teslamate_1  | a different host than the one configured in your config/
teslamate_1  | files. For example, in development the host is configured
teslamate_1  | to "localhost" but you may be trying to access it from
teslamate_1  | "127.0.0.1". To fix this issue, you may either:
teslamate_1  |
teslamate_1  |   1. update [url: [host: ...]] to your actual host in the
teslamate_1  |      config file for your current environment (recommended)
teslamate_1  |
teslamate_1  |   2. pass the :check_origin option when configuring your
teslamate_1  |      endpoint or when configuring the transport in your
teslamate_1  |      UserSocket module, explicitly outlining which origins
teslamate_1  |      are allowed:
teslamate_1  |
teslamate_1  |         check_origin: ["https://example.com",
teslamate_1  |                        "//another.com:888", "//other.com"]
```

I'll try to make the :check_origin option configurable via en env variable in a future release.

**Comment by krezac** [comment]
Env variable sounds great, thanks (I use both ways/hosts to access it).
