### ISSUE TITLE
Update steps out of order

### ISSUE THREAD

**Issue by withanhdammit** [adriankumpf/teslamate#1953]
**Describe the bug**

1. Update steps in documentation out of order https://docs.teslamate.org/docs/upgrading/
2. Environment variables needed in step 2

**Expected behavior**

1. Step 1, line 5 says to remove the '_build' folder, however step 2 says if you need to update the database you have to run a command from the '_build' folder.  Removing the '_build' folder should be at the end of the steps, maybe as a separate Step 4

2. When running Step 2, I had to include environment variables for the command to complete:
DATABASE_USER=teslamate DATABASE_PASS=super_secret_password DATABASE_NAME=teslamate DATABASE_HOST=localhost MQTT_HOST=your_MQTT_host(HomeAssistant in my case) _build/prod/rel/teslamate/bin/teslamate eval "TeslaMate.Release.migrate"

**How to reproduce it (as minimally and precisely as possible)**:

Visit update page at https://docs.teslamate.org/docs/upgrading/

**Environment**

- TeslaMate version: upgrade to 1.24
- Type of installation: Manual
- OS TeslaMate is installed on: Debian 11 Bullseye
- User OS & Browser: Windows 10/Edge
- Others:

**Comment by adriankumpf** [comment]
> Step 1, line 5 says to remove the '_build' folder, however step 2 says if you need to update the database you have to run a command from the '_build' folder. Removing the '_build' folder should be at the end of the steps, maybe as a separate Step 4

In line  6 (`MIX_ENV=prod mix do phx.digest, release --overwrite`) the `_build` folder gets recreated.

> When running Step 2, I had to include environment variables for the command to complete:
DATABASE_USER=teslamate DATABASE_PASS=super_secret_password DATABASE_NAME=teslamate DATABASE_HOST=localhost MQTT_HOST=your_MQTT_host(HomeAssistant in my case) _build/prod/rel/teslamate/bin/teslamate eval "TeslaMate.Release.migrate"

Do you want to maybe create a PR to add a note to the [documentation](https://github.com/adriankumpf/teslamate/blob/master/website/docs/upgrading.mdx)?

**Comment by withanhdammit** [comment]
OK, I took the plunge.  I'm a bit of a rookie doing changes like this.  It's my first, I'm no longer a "pull request virgin" LOL

It's also gonna cost me a case of beer.  That's a skydiver thing, I can explain if you want.

In any case, I believe I did the PR correctly and submitted my recommended change.  Hope I did it right.

**Comment by adriankumpf** [comment]
Nice! Great job and congrats on your first PR 👏

Closed by #2043
