### ISSUE TITLE
Charged amount shows 0.0 kWh & Charges don't appear in Charge history

### ISSUE THREAD

**Issue by cmchauvin** [adriankumpf/teslamate#1962]
**Describe the bug**

While charging, the SoC changes on both the Web App view as well as Charging Details dashboard and the Current [A] and Charging Voltage [V] show values, however the kWh added remains at 0.0

When the charge is complete, I can see the SoC has increased as expected but no records are added to the Charge history view since the energy added is "0". The charges do appear in the logs (see below)

Model Y on firmware 2021.24.10 and TeslaMate version 1.24.0

**Expected behavior**

Would expect to see kWh added > 0 for both charging details as well as on the Web App view. Would also expect the charge to appear in the history.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start a charging session
2. Navigate to Web App view and observe the vehicle go into charging status and confirm that SoC has increased
3. See that kWh added remains at 0.0 during the entire charge cycle
4. When charge is complete, move over to the charge history view and notice that the charge was not added despite change in SoC

**Relevant entries from the logs**

```
teslamate_1  | 2021-09-09 02:18:31.134 car_id=1 [info] Charging detected: -3 kW
teslamate_1  | 2021-09-09 02:18:32.212 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (690.508 ms)
teslamate_1  | 2021-09-09 02:18:33.901 car_id=1 [info] Charging / SOC: 72% / 🏡 Home
teslamate_1  | 2021-09-09 02:18:33.902 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-09-09 02:21:14.481 [info] GET /
teslamate_1  | 2021-09-09 02:21:14.499 [info] Sent 200 in 18ms
teslamate_1  | 2021-09-09 02:21:28.457 [info] GET /
teslamate_1  | 2021-09-09 02:21:28.473 [info] Sent 200 in 16ms
teslamate_1  | 2021-09-09 02:22:29.445 [info] GET /
teslamate_1  | 2021-09-09 02:22:29.463 [info] Sent 200 in 17ms
teslamate_1  | 2021-09-09 02:22:31.229 [info] GET /
teslamate_1  | 2021-09-09 02:22:31.592 [info] Sent 200 in 363ms
teslamate_1  | 2021-09-09 02:23:36.397 [info] GET /
teslamate_1  | 2021-09-09 02:23:36.412 [info] Sent 200 in 14ms
teslamate_1  | 2021-09-09 02:23:42.794 [info] GET /
teslamate_1  | 2021-09-09 02:23:42.811 [info] Sent 200 in 16ms
teslamate_1  | 2021-09-09 02:23:44.147 [info] GET /
teslamate_1  | 2021-09-09 02:23:44.159 [info] Sent 200 in 12ms
teslamate_1  | 2021-09-09 02:23:44.811 [info] GET /
teslamate_1  | 2021-09-09 02:23:44.828 [info] Sent 200 in 16ms
teslamate_1  | 2021-09-09 02:24:51.568 [info] GET /
teslamate_1  | 2021-09-09 02:24:51.588 [info] Sent 200 in 19ms
teslamate_1  | 2021-09-09 02:24:54.724 [info] GET /
teslamate_1  | 2021-09-09 02:24:54.740 [info] Sent 200 in 16ms
teslamate_1  | 2021-09-09 02:26:33.634 [info] GET /
teslamate_1  | 2021-09-09 02:26:33.649 [info] Sent 200 in 15ms
teslamate_1  | 2021-09-09 02:28:00.795 [info] GET /settings
teslamate_1  | 2021-09-09 02:28:00.819 [info] Sent 200 in 24ms
teslamate_1  | 2021-09-09 02:29:07.301 [info] GET /
teslamate_1  | 2021-09-09 02:29:07.316 [info] Sent 200 in 15ms
teslamate_1  | 2021-09-09 02:29:07.341 [info] GET /
teslamate_1  | 2021-09-09 02:29:07.356 [info] Sent 200 in 14ms
teslamate_1  | 2021-09-09 02:29:35.611 [info] GET /
teslamate_1  | 2021-09-09 02:29:35.629 [info] Sent 200 in 16ms
teslamate_1  | 2021-09-09 02:36:32.854 [info] GET /settings
teslamate_1  | 2021-09-09 02:36:32.880 [info] Sent 200 in 25ms
teslamate_1  | 2021-09-09 02:37:49.776 car_id=1 [info] Derived efficiency factor: 148.5 Wh/km (22x confirmed)
teslamate_1  | 2021-09-09 02:37:49.776 car_id=1 [info] Charging / Complete / 0.00 kWh – 19 min
teslamate_1  | 2021-09-09 02:37:49.780 car_id=1 [info] Start / :online

```

**Screenshots**

![0052941F-5B4C-46EE-AF1A-A4E4D603A382_1_101_o](https://user-images.githubusercontent.com/17072686/132700065-fcab9f9f-745f-4c55-a0be-e31bb1602e3e.jpeg)

**Data**

[charges.xlsx](https://github.com/adriankumpf/teslamate/files/7137171/charges.xlsx)

**Environment**

- TeslaMate version: 1.24.0
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian Lite
- User OS & Browser: MacOS / Edge
- Others:

**Comment by adriankumpf** [comment]
That charges with 0.0 kWh added are not shown on the dashboard is expected because those are hidden by design. 

However, I'm not sure if the charge_energy_added was just incorrectly reported by the Tesla API or if TeslaMate interpreted it wrong. Can you provide the CSV file as described in the bug template? The dates in the attached file are formatted strangely when I open that file.

**Comment by cmchauvin** [comment]
Sure, I've added the raw .csv export here. 

[charges.csv](https://github.com/adriankumpf/teslamate/files/7137410/charges.csv)

**Comment by adriankumpf** [comment]
OK here we go – these are the relevant rows for that charging session:

|id   |date                   |battery_heater_on|battery_level|charge_energy_added|charger_actual_current|charger_phases|charger_pilot_current|charger_power|charger_voltage|fast_charger_present|conn_charge_cable|fast_charger_brand|fast_charger_type|ideal_battery_range_km|not_enough_power_to_heat|outside_temp|charging_process_id|battery_heater|battery_heater_no_power|rated_battery_range_km|usable_battery_level|
|-----|-----------------------|-----------------|-------------|-------------------|----------------------|--------------|---------------------|-------------|---------------|--------------------|-----------------|------------------|-----------------|----------------------|------------------------|------------|-------------------|--------------|-----------------------|----------------------|--------------------|
|61656|2021-09-09 02:18:31.273|f                |72           |0.00               |11                    |1             |32                   |3            |230            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |354.72                |                        |26.0        |298                |f             |                       |354.72                |72                  |
|61657|2021-09-09 02:18:39.112|f                |72           |0.00               |20                    |1             |32                   |5            |228            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |354.72                |                        |26.0        |298                |f             |                       |354.72                |72                  |
|61658|2021-09-09 02:18:59.592|f                |72           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |354.72                |                        |26.0        |298                |f             |                       |354.72                |72                  |
|61659|2021-09-09 02:19:20.072|f                |72           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |354.72                |                        |26.0        |298                |f             |                       |354.72                |72                  |
|61660|2021-09-09 02:19:40.552|f                |72           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |354.72                |                        |26.0        |298                |f             |                       |354.72                |72                  |
|61661|2021-09-09 02:20:00.948|f                |72           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |356.13                |                        |26.0        |298                |f             |                       |356.13                |72                  |
|61662|2021-09-09 02:20:21.513|f                |72           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |356.13                |                        |26.0        |298                |f             |                       |356.13                |72                  |
|61663|2021-09-09 02:20:42.197|f                |72           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |355.42                |                        |26.0        |298                |f             |                       |355.42                |72                  |
|61664|2021-09-09 02:21:02.68 |f                |72           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |356.82                |                        |26.0        |298                |f             |                       |356.82                |72                  |
|61665|2021-09-09 02:21:23.157|f                |72           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |356.82                |                        |26.0        |298                |f             |                       |356.82                |72                  |
|61666|2021-09-09 02:21:47.115|f                |73           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |356.82                |                        |26.0        |298                |f             |                       |356.82                |72                  |
|61667|2021-09-09 02:22:10.064|f                |73           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |357.53                |                        |26.0        |298                |f             |                       |357.53                |73                  |
|61668|2021-09-09 02:22:30.537|f                |73           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |357.53                |                        |26.0        |298                |f             |                       |357.53                |73                  |
|61669|2021-09-09 02:22:51.839|f                |73           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |357.53                |                        |26.0        |298                |f             |                       |357.53                |73                  |
|61670|2021-09-09 02:23:14.158|f                |73           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |358.24                |                        |26.0        |298                |f             |                       |358.24                |73                  |
|61671|2021-09-09 02:23:34.639|f                |73           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |358.24                |                        |26.0        |298                |f             |                       |358.24                |73                  |
|61672|2021-09-09 02:23:55.118|f                |73           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |358.24                |                        |26.0        |298                |f             |                       |358.24                |73                  |
|61673|2021-09-09 02:24:15.804|f                |73           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |358.95                |                        |26.0        |298                |f             |                       |358.95                |73                  |
|61674|2021-09-09 02:24:37.512|f                |73           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |359.66                |                        |25.5        |298                |f             |                       |359.66                |73                  |
|61675|2021-09-09 02:24:58.196|f                |73           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |358.95                |                        |25.5        |298                |f             |                       |358.95                |73                  |
|61676|2021-09-09 02:25:22.57 |f                |73           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |358.95                |                        |25.5        |298                |f             |                       |358.95                |73                  |
|61677|2021-09-09 02:25:43.06 |f                |73           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |360.36                |                        |25.5        |298                |f             |                       |360.36                |73                  |
|61678|2021-09-09 02:26:03.529|f                |73           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |360.36                |                        |25.5        |298                |f             |                       |360.36                |73                  |
|61679|2021-09-09 02:26:24.01 |f                |73           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |360.36                |                        |25.5        |298                |f             |                       |360.36                |73                  |
|61680|2021-09-09 02:26:44.489|f                |73           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |361.06                |                        |25.5        |298                |f             |                       |361.06                |73                  |
|61681|2021-09-09 02:27:05.172|f                |73           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |361.06                |                        |25.5        |298                |f             |                       |361.06                |73                  |
|61682|2021-09-09 02:27:25.657|f                |73           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |361.06                |                        |25.5        |298                |f             |                       |361.06                |73                  |
|61683|2021-09-09 02:27:46.132|f                |73           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |361.76                |                        |25.5        |298                |f             |                       |361.76                |73                  |
|61684|2021-09-09 02:28:06.816|f                |73           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |361.76                |                        |25.5        |298                |f             |                       |361.76                |73                  |
|61685|2021-09-09 02:28:27.299|f                |74           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |361.76                |                        |25.5        |298                |f             |                       |361.76                |73                  |
|61686|2021-09-09 02:28:47.782|f                |74           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |362.47                |                        |25.5        |298                |f             |                       |362.47                |74                  |
|61687|2021-09-09 02:29:08.259|f                |74           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |362.47                |                        |25.5        |298                |f             |                       |362.47                |74                  |
|61688|2021-09-09 02:29:28.736|f                |74           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |362.47                |                        |25.5        |298                |f             |                       |362.47                |74                  |
|61689|2021-09-09 02:29:53.111|f                |74           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |362.47                |                        |25.5        |298                |f             |                       |362.47                |74                  |
|61690|2021-09-09 02:30:13.592|f                |74           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |363.89                |                        |25.5        |298                |f             |                       |363.89                |74                  |
|61691|2021-09-09 02:30:34.478|f                |74           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |363.89                |                        |25.5        |298                |f             |                       |363.89                |74                  |
|61692|2021-09-09 02:30:56.802|f                |74           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |363.89                |                        |25.5        |298                |f             |                       |363.89                |74                  |
|61693|2021-09-09 02:31:17.283|f                |74           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |364.60                |                        |25.5        |298                |f             |                       |364.60                |74                  |
|61694|2021-09-09 02:31:37.967|f                |74           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |364.60                |                        |25.5        |298                |f             |                       |364.60                |74                  |
|61695|2021-09-09 02:31:58.447|f                |74           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |364.60                |                        |25.5        |298                |f             |                       |364.60                |74                  |
|61696|2021-09-09 02:32:18.927|f                |74           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |365.29                |                        |25.5        |298                |f             |                       |365.29                |74                  |
|61697|2021-09-09 02:32:39.61 |f                |74           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |365.29                |                        |25.5        |298                |f             |                       |365.29                |74                  |
|61698|2021-09-09 02:33:00.095|f                |74           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |365.29                |                        |25.5        |298                |f             |                       |365.29                |74                  |
|61699|2021-09-09 02:33:20.696|f                |74           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |365.29                |                        |25.5        |298                |f             |                       |365.29                |74                  |
|61700|2021-09-09 02:33:41.255|f                |74           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |366.00                |                        |25.5        |298                |f             |                       |366.00                |74                  |
|61701|2021-09-09 02:34:02.146|f                |75           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |366.71                |                        |25.5        |298                |f             |                       |366.71                |74                  |
|61702|2021-09-09 02:34:22.627|f                |75           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |366.00                |                        |25.5        |298                |f             |                       |366.00                |74                  |
|61703|2021-09-09 02:34:43.105|f                |75           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |367.41                |                        |25.5        |298                |f             |                       |367.41                |75                  |
|61704|2021-09-09 02:35:03.587|f                |75           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |367.41                |                        |25.5        |298                |f             |                       |367.41                |75                  |
|61705|2021-09-09 02:35:24.069|f                |75           |0.00               |32                    |1             |32                   |7            |225            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |367.41                |                        |25.5        |298                |f             |                       |367.41                |75                  |
|61706|2021-09-09 02:35:44.551|f                |75           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |368.12                |                        |25.5        |298                |f             |                       |368.12                |75                  |
|61707|2021-09-09 02:36:05.028|f                |75           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |368.12                |                        |25.5        |298                |f             |                       |368.12                |75                  |
|61708|2021-09-09 02:36:25.506|f                |75           |0.00               |32                    |1             |32                   |7            |224            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |368.12                |                        |25.5        |298                |f             |                       |368.12                |75                  |
|61709|2021-09-09 02:36:46.19 |f                |75           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |368.12                |                        |25.5        |298                |f             |                       |368.12                |75                  |
|61710|2021-09-09 02:37:06.673|f                |75           |0.00               |32                    |1             |32                   |7            |223            |f                   |SAE              |<invalid>         |MCSingleWireCAN  |368.81                |                        |25.5        |298                |f             |                       |368.81                |75                  |
|61711|2021-09-09 02:37:49.485|f                |75           |0.00               |0                     |1             |32                   |0            |2              |f                   |SAE              |<invalid>         |MCSingleWireCAN  |368.81                |                        |25.5        |298                |f             |                       |368.81                |75                  |

The `charge_energy_added` values remain constant at 0.0 the whole time. This value is reported by the Tesla API. TeslaMate just records it while the car is charging. So it looks like there was an issue on Tesla's side that caused that value to not change. That's quite strange, but it is not uncommon that sometimes wrong values are reported.

**Comment by cmchauvin** [comment]
Makes sense. Thanks for the quick turnaround!
