### ISSUE TITLE
'Error: non-existing domain' on sign-in

### ISSUE THREAD

**Issue by lemmerk** [adriankumpf/teslamate#1966]
**Describe the bug**

just upgraded to version 1.24.0. when trying to sing in using my tesla account i get:
Error: non-existing domain

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to '.../sing_in'
2. Enter email address and password of tesla account
3. See error: Error: non-existing domain

**Relevant entries from the logs**

only relevant log entry i can find:
```
teslamate_1  | 2021-09-10 22:32:03.757 [error] GET https://auth.tesla.com/oauth2/v3/authorize -> error: "non-existing domain" (8031.664 ms)
```

**Environment**

- TeslaMate version: 1.24.0
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian GNU/Linux 10 (buster)
- User OS & Browser: gentoo & qutebrowser / firefox
- Others:

**Comment by Deanbau** [comment]
Have you got 2FA?

**Comment by lemmerk** [comment]
no i haven't should i?
