### ISSUE TITLE
Add custom geofence location to mqtt

### ISSUE THREAD

**Issue by Try2Fly** [adriankumpf/teslamate#197]
Is it possible to add the custom geofence location as mqtt message? Now only longitude and latitude are published, but it is not possible to use this in for example home assistant. If it would publish for example “home” or “work” it would be possible to make automations based on these locations.

**Comment by ngardiner** [comment]
Hi @Try2Fly, just an alternative approach to think about. HomeAssistant has built in zone support which allows you to do geofencing based on your proximity to those zones, and to execute automations as a result. One option would be to publish geofencing info out from teslamate, but another would be to do it on the HASS side. I am just about to publish a document which explains how to do this using a device_tracker and the mqtt lat/lon topics, if you are interested in having a read, you can see it before it's merged here:

https://github.com/ngardiner/teslamate/blob/patch-1/docs/HomeAssistantIntegration.md

**Comment by Try2Fly** [comment]
@ngardiner you are a hero. This is exactly what I was looking for. I could not find how to make a device tracker out of longitude and latitude. I was not familiar with option of device_tracker.see. 

I have the same setup with teslamate sensors and also want to try to use the HA component (with minimum polling) for climate control. But I still need to test if that works.

I want to make automations for pre heating on workdays or custom times like an alarm clock. 

I also just made a Lovelace setup which I think is very nice.  Will try to share it with you on your github. Thanks for sharing!

**Comment by ngardiner** [comment]
That would be great @Try2Fly! Would be awesome to have a nice HASS dashboard documented. TeslaMate and HASS work together really well, I think there will be some great automation opportunities coming up

**Comment by Try2Fly** [comment]
@ngardiner 
Well I finaly had the time to write some automations. I wrote some automations for smart charging and heating.

 They have not been tested yet as my home charger still needs to be installed. Feel free to use this:
[https://github.com/Try2Fly/teslamate-automation/blob/master/README.md](https://github.com/Try2Fly/teslamate-automation/blob/master/README.md)
