### ISSUE TITLE
letsencrypt certificates - DST Root CA expiry on Sep 30th

### ISSUE THREAD

**Issue by brianmay** [adriankumpf/teslamate#1977]
See: https://elixirforum.com/t/psa-preventing-outages-due-to-dst-root-ca-expiry-on-sep-30th/42247

Will affect people who use Let’s Encrypt certificates for mqtt. Like me.

I believe the fix is to use Erlang version 24.0.4 or above.

I think the latest released image - version 1.24 - uses 24.0.3.

It looks like the image with the tag edge is fine however.

**Comment by brianmay** [comment]
I believe my personal setup should be OK, as I have configured the preferred chain for my certificates to use "ISRG Root X1".

Which I believe won't work for older browsers, but I don't care. Especially not for mqtt.

Trying to understand this makes my head spin: https://letsencrypt.org/certificates/

Regardless, people might get caught out by the so probably a good idea to leave this bug open until a new image is built with a newer version of erlang.

**Comment by adriankumpf** [comment]
Thanks for the heads-up! I've published new images for version 1.24.1.
