### ISSUE TITLE
Support running dashboards.sh from inside teslamate container

### ISSUE THREAD

**Issue by PhracturedBlue** [adriankumpf/teslamate#1980]
**Describe the issue**

I use the teslamate docker container along with watchtower in order to keep the container updated.  However, I do not use the teslamate grafana container (because I have other grafana dashboards as well).  So when watchtower fetches a new telsamate container, I would like to be able to use its update hook to run dashboards.sh.  However, watchtower can only run hooks within the context of the container it updates, so I need to be able to run dashbaords.sh from the teslamate container.  I'd rather not extend the teslamate container myself, since that will break watchtower's ability to detect updates.

The current issues:
  * dashboards.sh requires curl and jq which are not available in the image
  * the grafana subdir is not included in the teslamate container

Ideally I would like both of the above addressed, but even just adding curl and jq could make things much easier.

Today, to work around this, I mount a volume on /grafana/update with curl and jq and the following script as the watchtower update hook:

```
#!/bin/bash
URL=<grafana url>
LOGIN=<grafana login>
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# add jq and curl to the path
export PATH=${PATH}:${SCRIPT_DIR}

release=$(/bin/ls -1 /opt/app/releases | grep -e '^\([0-9]*\.\)*[0-9]*[0-9]$')
rm -rf /tmp/teslamate-* /tmp/${release}
curl https://github.com/adriankumpf/teslamate/archive/refs/tags/v${release}.tar.gz | tar -C /tmp -xzf -
cd /tmp/teslamate-${release}
./grafana/dashboards.sh restore
```

For reference (although not relevant to the request) I use the following for a static curl/jq:
  * curl: https://github.com/moparisthebest/static-curl
  * jq: https://stedolan.github.io/jq/download/

As the above solution is working for me, feel free to close this request if you don't think it has enough broad appeal.  If you are interested and would prefer a pull-request, I'll be happy to file one.

**Comment by adriankumpf** [comment]
I'm afraid this is a rather niche use case. Since you already have a working solution, I would not like to install dependencies just for this purpose.  On the one hand because of the image size, on the other hand so that people don't start to expect that those dependencies are present and thus preventing us to make changes to the image in the future.
