### ISSUE TITLE
Teslamate Not Loading - But Grafana Loads

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#199]
@adriankumpf  In addition to getting the Earth does not exist error, I'm getting the following error as well.  My Grafana ends up loading, but I can not get to Teslamate at port 4000.  It looks like my late data point was from Oct 7, 2019.  Thanks!

teslamate_1  | 17:21:17.286 car_id=1 [warn] Error / upstream timeout
teslamate_1  | 17:21:32.369 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 17:21:32.369 car_id=1 [warn] Error / upstream timeout
teslamate_1  | 17:26:19.909 car_id=1 [info] Driving / Start
teslamate_1  | 17:28:03.185 [error] TeslaApi.Error / 502 – "<!DOCTYPE html>\n<html>\n<head>\n  <title>We're sorry, but something went wrong (500)</title>\n  <style type=\"text/css\">\n    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }\n    div.dialog {\n      width: 25em;\n      padding: 0 4em;\n      margin: 4em auto 0 auto;\n      border: 1px solid #ccc;\n      border-right-color: #999;\n      border-bottom-color: #999;\n    }\n    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }\n  </style>\n</head>\n\n<body>\n  \n  <div class=\"dialog\">\n    <h1>We're sorry, but something went wrong.</h1>\n  </div>\n</body>\n</html>\n"
teslamate_1  | 17:28:03.185 car_id=1 [error] Error / :unknown
teslamate_1  | 17:32:09.593 car_id=1 [info] Driving / Ended / 4 km – 6 min
teslamate_1  | 17:32:09.593 car_id=1 [info] Start / :online
teslamate_1  | 20:52:48.945 [info] SIGTERM received - shutting down
teslamate_1  | 
teslamate_1  | 20:52:48.958 [warn] Connection has been dropped

**Comment by jun3280net** [comment]
I shut down services (CTRL + C) then sudo docker-compose pull, sudo docker-compose up and things look like its working again.

**Comment by adriankumpf** [comment]
Okay, those `TeslaApi.Error` errors may come up now and then. They show you when the Tesla servers were having problems.
