### ISSUE TITLE
Back-up possibility

### ISSUE THREAD

**Issue by Try2Fly** [adriankumpf/teslamate#201]
Hi, I just had a crash of my sd card, and my Pi won't start anymore.
I'm able to acces the documents on the card on another comp. Is there a way to restore all the data so it is not lost? If so what should I copy from where?

**Comment by spacecosmos** [comment]
Yes, this concerns me as well. An easy backup solution would be super helpful!

Now I have activated the backup feature that DigitalOcean provides. It takes a backup of the virtual machine (Droplet) four times a week. But having something else, preferably built into the Dashboard somehow would be awesome!

Just my two cents. :)

**Comment by adriankumpf** [comment]
I don’t see it that way. Offering a backup solution is not the job of the application in my opinion. All data is stored in a Postgres database for which there are various backup options. Self-hosting also means taking care of e.g. operating system updates and application backups. In the future, however, we will add documentation on this topic and link to the corresponding resources.

To answer your original question, @Try2Fly, if you used the default docker-compose file your data is stored in a [docker volume](https://docs.docker.com/storage/volumes/) named `teslamate-db`. A Volume can be inspected with the following command to find out its location: 

```bash
pi@raspberrypi:~ $ docker volume inspect teslamate_teslamate-db
[
    {
        "CreatedAt": "2019-10-12T13:44:06+02:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "teslamate",
            "com.docker.compose.version": "1.24.1",
            "com.docker.compose.volume": "teslamate-db"
        },
        "Mountpoint": "/var/lib/docker/volumes/teslamate_teslamate-db/_data", # <----
        "Name": "teslamate_teslamate-db",
        "Options": null,
        "Scope": "local"
    }
]
```

It would probably be best to copy the directory containing all docker volumes (`/var/lib/docker/volumes`) to a new SD card and then setup TeslaMate again.

**Comment by spacecosmos** [comment]
That's an excellent point @adriankumpf. I think I'll fint a solution with a script or something. :)

**Comment by Try2Fly** [comment]
@adriankumpf Thanks for your help. I've copied over the directories, unfortunately, no data shows up in grafana. I guess I'll have to bite the bullet and start over with collecting data of my trips.

**Comment by adriankumpf** [comment]
I'm sorry it didn't work out :/ It is difficult to give a step by step guide. Maybe they can help you over on the docker forum or slack channel.

**Comment by Try2Fly** [comment]
I understand, I really appreciate all the time you have put into this project!

**Comment by petebocken** [comment]
Here is a great option using rclone to Google Drive: https://www.teslaev.co.uk/how-to-perform-an-automatic-teslamate-backup-to-google-drive/
