### ISSUE TITLE
Restarting every minute

### ISSUE THREAD

**Issue by r4mses** [adriankumpf/teslamate#2018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Since the latest upgrade, the teslamate docker instance is restarting every minute, in a loop.
Restarted, updated my Pi + docker, cleaned everything with prune, remove the image and pulled it again, removed the database = same issue.

### Relevant log output

```shell
teslamate_1  |     (ecto 3.7.1) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
teslamate_1  |     (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
teslamate_1  |     (teslamate 1.24.2) lib/teslamate/terrain.ex:121: TeslaMate.Terrain.handle_event/4
teslamate_1  |     (stdlib 3.16) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2021-10-01 09:55:09.462 [info] Adding elevation to 484 positions ...
teslamate_1  | 2021-10-01 09:55:09.506 [error] GenStateMachine TeslaMate.Terrain terminating
teslamate_1  | ** (Ecto.StaleEntryError) attempted to update a stale struct:
teslamate_1  | 
teslamate_1  | %TeslaMate.Log.Position{__meta__: #Ecto.Schema.Metadata<:loaded, "positions">, battery_heater: false, battery_heater_no_power: nil, battery_heater_on: false, battery_level: 65, car: #Ecto.Association.NotLoaded<association :car is not loaded>, car_id: 1, date: ~U[2021-09-28 16:33:59.698000Z], drive: #Ecto.Association.NotLoaded<association :drive is not loaded>, drive_id: 361, driver_temp_setting: #Decimal<22.0>, elevation: nil, est_battery_range_km: #Decimal<277.19>, fan_status: 4, id: 1268445, ideal_battery_range_km: #Decimal<293.16>, inside_temp: #Decimal<30.5>, is_climate_on: true, is_front_defroster_on: false, is_rear_defroster_on: false, latitude: #Decimal<43.321276>, longitude: #Decimal<5.374244>, odometer: 47550.775258, outside_temp: #Decimal<28.5>, passenger_temp_setting: #Decimal<22.0>, power: 5, rated_battery_range_km: #Decimal<293.16>, speed: 6, usable_battery_level: 65}
teslamate_1  | 
teslamate_1  |     (ecto 3.7.1) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
teslamate_1  |     (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
teslamate_1  |     (teslamate 1.24.2) lib/teslamate/terrain.ex:121: TeslaMate.Terrain.handle_event/4
teslamate_1  |     (stdlib 3.16) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2021-10-01 09:55:09.520 [info] GET /sign_in
teslamate_1  | 2021-10-01 09:55:09.603 [info] Sent 200 in 81ms
teslamate_1  | 2021-10-01 09:55:10.642 [info] Adding elevation to 484 positions ...
teslamate_1  | 2021-10-01 09:55:10.682 [error] GenStateMachine TeslaMate.Terrain terminating
teslamate_1  | ** (Ecto.StaleEntryError) attempted to update a stale struct:
teslamate_1  | 
teslamate_1  | %TeslaMate.Log.Position{__meta__: #Ecto.Schema.Metadata<:loaded, "positions">, battery_heater: false, battery_heater_no_power: nil, battery_heater_on: false, battery_level: 65, car: #Ecto.Association.NotLoaded<association :car is not loaded>, car_id: 1, date: ~U[2021-09-28 16:33:59.698000Z], drive: #Ecto.Association.NotLoaded<association :drive is not loaded>, drive_id: 361, driver_temp_setting: #Decimal<22.0>, elevation: nil, est_battery_range_km: #Decimal<277.19>, fan_status: 4, id: 1268445, ideal_battery_range_km: #Decimal<293.16>, inside_temp: #Decimal<30.5>, is_climate_on: true, is_front_defroster_on: false, is_rear_defroster_on: false, latitude: #Decimal<43.321276>, longitude: #Decimal<5.374244>, odometer: 47550.775258, outside_temp: #Decimal<28.5>, passenger_temp_setting: #Decimal<22.0>, power: 5, rated_battery_range_km: #Decimal<293.16>, speed: 6, usable_battery_level: 65}
teslamate_1  | 
teslamate_1  |     (ecto 3.7.1) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
teslamate_1  |     (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
teslamate_1  |     (teslamate 1.24.2) lib/teslamate/terrain.ex:121: TeslaMate.Terrain.handle_event/4
teslamate_1  |     (stdlib 3.16) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2021-10-01 09:55:15.757 [info] Application teslamate exited: shutdown
teslamate_1  | {"Kernel pid terminated",application_controller,"{application_terminated,teslamate,shutdown}"}
teslamate_1  | Kernel pid terminated (application_controller) ({application_terminated,teslamate,shutdown})
teslamate_1  | 
teslamate_1  | Crash dump is being written to: erl_crash.dump...done
```

### Type of installation

Docker

### Version

v1.24.2

**Comment by adriankumpf** [comment]
> removed the database = same issue.

Do you mean the same error occurs when you use a clean database? 

Can you double-check that there is only one TeslaMate instance running? -> `docker ps`

Did you do any manual changes to the database? Deleting drives, for example?

**Comment by r4mses** [comment]
Yes, fresh database = same behavior.

Only one instance running : 
CONTAINER ID   IMAGE                        COMMAND                  CREATED       STATUS                          PORTS                                                    NAMES
e41999c0f965   postgres:13                  "docker-entrypoint.s…"   4 hours ago   Up 2 hours                      5432/tcp                                                 pi_database_1
d93373e03ce6   teslamate/grafana:latest     "/run.sh"                4 hours ago   Up 2 hours                      0.0.0.0:3000->3000/tcp                                   pi_grafana_1
ab4a6e843228   eclipse-mosquitto:1.6        "/docker-entrypoint.…"   4 hours ago   Up 2 hours                      0.0.0.0:1883->1883/tcp                                   pi_mosquitto_1
e268a13a0e07   teslamate/teslamate:latest   "tini -- /bin/sh /en…"   4 hours ago   Restarting (1) 22 seconds ago                                                            pi_teslamate_1

I didn't start my pgadmin to manipulate the content, I'll try.

**Comment by adriankumpf** [comment]
> Yes, fresh database = same behavior.

I'm asking because according to the logs there are at least 484 rows in the positions table. With a fresh database this error cannot happen because said table should be empty. 

Can you try if this helps:

```sql
update positions set elevation = 0 where drive_id = 361;
```

If not, please provide the logs from application start until the errors occur.

**Comment by r4mses** [comment]
Thanks for answering ; since the blanck DB didn't improve my situation, I've rolled-back to my prevous DB (that explains the number of rows).

Here is the full log from startup : 

waiting for postgres at database:5432
waiting for postgres at database:5432
waiting for postgres at database:5432
2021-10-01 12:44:07.083 [info] Migrations already up
2021-10-01 12:44:13.171 [info] System Info: Erlang/OTP 24 (emu)
2021-10-01 12:44:13.171 [info] Version: 1.24.2
2021-10-01 12:44:14.067 [error] POST https://auth.tesla.com/oauth2/v3/token -> 401 (769.308 ms)
2021-10-01 12:44:14.072 [warn] Token refresh failed: %TeslaApi.Error{
  env: %Tesla.Env{
    __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
    __module__: TeslaApi.Auth,
    body: %{
      "error" => "login_required",
      "error_description" => "Login required",
      "error_uri" => "https://auth.tesla.com/error/reference/738825bf-6d85-48df-9e2e-557d77148da4-1633092282961"
    },
    headers: [
      {"content-type", "application/json"},
      {"content-length", "167"},
      {"x-dns-prefetch-control", "off"},
      {"x-frame-options", "DENY"},
      {"strict-transport-security", "max-age=15552000; includeSubDomains"},
      {"x-download-options", "noopen"},
      {"x-content-type-options", "nosniff"},
      {"x-xss-protection", "1; mode=block"},
      {"x-request-id", "738825bf-6d85-48df-9e2e-557d77148da4"},
      {"x-correlation-id", "738825bf-6d85-48df-9e2e-557d77148da4"},
      {"cache-control", "no-store"},
      {"access-control-allow-origin", "*"},
      {"x-response-time", "15.228ms"},
      {"x-edgeconnect-midmile-rtt", "71"},
      {"x-edgeconnect-origin-mex-latency", "88"},
      {"date", "Fri, 01 Oct 2021 12:44:43 GMT"},
      {"connection", "close"},
      {"permissions-policy", "interest-cohort=()"},
      {"set-cookie",
       "_abck=1EDC94ACFF2F5B598F3580C04369FE9A~-1~YAAQbrcQAtoL/QJ8AQAAnKriOwa9rtpSxQXou2D9COLxat7yBdgR9SLOatGq01ywj0ME/iSo8HoI49B0COjrDm4AYqwTcJRVAaQUepcaOqLHJc21EdD9ABzaRbZ9gPLeCpSjCeL1WaXAM6rbFBPiSQxdQ/meegJcFqravhe/U7fIi/YMgxjuBcjkkHG/80EnAxUg3jdWAFpS9zCOXqtuS8dLP8o61xCRRHpB5FRVEpltYxdIRaINBODrOyo4iIUYJV7cwMVnp+J30Y69jxsU98ahj7LvdTF1LpWhmGkOcCDWzyKGpHEL9TI1LCzha+jjHxY/Y54oDksPX3kbxLb1nqyIzjWCEUuKA5dee7/hnsZcMtx3DYwq0w==~-1~-1~-1; Domain=.tesla.com; Path=/; Expires=Sat, 01 Oct 2022 12:44:43 GMT; Max-Age=31536000; Secure"},
      {"set-cookie",
       "bm_sz=9A4A2C94D37D2E2F16642B0C515C4959~YAAQbrcQAtsL/QJ8AQAAnKriOw31eTsoTY5X5h6tlY4T+hs3s/Nlv0tfKxOqpwIVA8V7AnHsJz1shMHs/oRwz0h35eBiDu++32vUwP3S0SieuKBfCiNv45CWHgizmbYTP22Aux0+spLtJPBVoWP99Isuna97b0nkDNyHl5r5IWSlxnfuywBVZ+NWuK7Wmq/j/goU+M6ZDKnFo5vOdzJVqKyYtPfDEihqGBtcR87/OxcgqKiuaSiWygyXPfgAdSq0JQWbzMsk90o1v+xcbEZr39FHuUOrU0Fz4/J7w0xEfyx3pA==~4273987~4339010; Domain=.tesla.com; Path=/; Expires=Fri, 01 Oct 2021 16:44:42 GMT; Max-Age=14399"}
    ],
    method: :post,
    opts: [],
    query: [],
    status: 401,
    url: "https://auth.tesla.com/oauth2/v3/token"
  },
  message: nil,
  reason: :token_refresh
}
2021-10-01 12:44:14.073 [info] Scheduling token refresh in 1 h
2021-10-01 12:44:14.087 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
2021-10-01 12:44:14.091 [info] Access TeslaMateWeb.Endpoint at http://localhost
2021-10-01 12:44:14.492 [info] GET https://owner-api.teslamotors.com/api/1/vehicles -> 401 (398.271 ms)
2021-10-01 12:44:14.521 [warn] Using fallback vehicles:

[
  %TeslaApi.Vehicle{
    api_version: nil,
    backseat_token: nil,
    backseat_token_updated_at: nil,
    calendar_enabled: nil,
    charge_state: nil,
    climate_state: nil,
    color: nil,
    display_name: "Cheetah",
    drive_state: nil,
    gui_settings: nil,
    id: 31141227531150211,
    in_service: false,
    option_codes: [],
    state: "unknown",
    tokens: [],
    vehicle_config: nil,
    vehicle_id: 923938384,
    vehicle_state: nil,
    vin: "5YJ3E7EB3KF516780"
  }
]
2021-10-01 12:44:14.521 [info] Starting logger for 'Cheetah'
2021-10-01 12:44:14.574 [error] Error / unauthorized
2021-10-01 12:44:15.447 [info] Adding elevation to 481 positions ...
2021-10-01 12:44:15.548 [info] Querying location for elevation takes longer than 100ms ...
2021-10-01 12:44:18.348 [info] tzdata release in place is from a file last modified Tue, 22 Dec 2020 23:35:21 GMT. Release file on server was last modified Sat, 25 Sep 2021 00:10:42 GMT.
2021-10-01 12:44:36.025 [info] Tzdata has updated the release from 2020e to 2021b
2021-10-01 12:44:36.329 [info] GET /sign_in
2021-10-01 12:44:37.534 [info] Sent 200 in 1204ms
2021-10-01 12:44:41.965 [error] GenStateMachine TeslaMate.Terrain terminating
** (Ecto.StaleEntryError) attempted to update a stale struct:

%TeslaMate.Log.Position{__meta__: #Ecto.Schema.Metadata<:loaded, "positions">, battery_heater: false, battery_heater_no_power: nil, battery_heater_on: false, battery_level: 66, car: #Ecto.Association.NotLoaded<association :car is not loaded>, car_id: 1, date: ~U[2021-09-28 16:34:35.709000Z], drive: #Ecto.Association.NotLoaded<association :drive is not loaded>, drive_id: 362, driver_temp_setting: #Decimal<22.0>, elevation: nil, est_battery_range_km: #Decimal<273.69>, fan_status: 3, id: 1268449, ideal_battery_range_km: #Decimal<292.47>, inside_temp: #Decimal<27.6>, is_climate_on: true, is_front_defroster_on: false, is_rear_defroster_on: false, latitude: #Decimal<43.320882>, longitude: #Decimal<5.373369>, odometer: 47550.911259, outside_temp: #Decimal<28.0>, passenger_temp_setting: #Decimal<22.0>, power: 2, rated_battery_range_km: #Decimal<292.47>, speed: 6, usable_battery_level: 65}

    (ecto 3.7.1) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
    (teslamate 1.24.2) lib/teslamate/terrain.ex:158: TeslaMate.Terrain.handle_event/4
    (stdlib 3.16) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
    (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-10-01 12:44:43.166 [info] Adding elevation to 481 positions ...
2021-10-01 12:44:43.268 [info] Querying location for elevation takes longer than 100ms ...
2021-10-01 12:44:43.277 [error] GenStateMachine TeslaMate.Terrain terminating
** (Ecto.StaleEntryError) attempted to update a stale struct:

%TeslaMate.Log.Position{__meta__: #Ecto.Schema.Metadata<:loaded, "positions">, battery_heater: false, battery_heater_no_power: nil, battery_heater_on: false, battery_level: 66, car: #Ecto.Association.NotLoaded<association :car is not loaded>, car_id: 1, date: ~U[2021-09-28 16:34:35.709000Z], drive: #Ecto.Association.NotLoaded<association :drive is not loaded>, drive_id: 362, driver_temp_setting: #Decimal<22.0>, elevation: nil, est_battery_range_km: #Decimal<273.69>, fan_status: 3, id: 1268449, ideal_battery_range_km: #Decimal<292.47>, inside_temp: #Decimal<27.6>, is_climate_on: true, is_front_defroster_on: false, is_rear_defroster_on: false, latitude: #Decimal<43.320882>, longitude: #Decimal<5.373369>, odometer: 47550.911259, outside_temp: #Decimal<28.0>, passenger_temp_setting: #Decimal<22.0>, power: 2, rated_battery_range_km: #Decimal<292.47>, speed: 6, usable_battery_level: 65}

    (ecto 3.7.1) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
    (teslamate 1.24.2) lib/teslamate/terrain.ex:158: TeslaMate.Terrain.handle_event/4
    (stdlib 3.16) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
    (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-10-01 12:44:44.497 [info] Adding elevation to 481 positions ...
2021-10-01 12:44:44.598 [info] Querying location for elevation takes longer than 100ms ...
2021-10-01 12:44:44.609 [error] GenStateMachine TeslaMate.Terrain terminating
** (Ecto.StaleEntryError) attempted to update a stale struct:

%TeslaMate.Log.Position{__meta__: #Ecto.Schema.Metadata<:loaded, "positions">, battery_heater: false, battery_heater_no_power: nil, battery_heater_on: false, battery_level: 66, car: #Ecto.Association.NotLoaded<association :car is not loaded>, car_id: 1, date: ~U[2021-09-28 16:34:35.709000Z], drive: #Ecto.Association.NotLoaded<association :drive is not loaded>, drive_id: 362, driver_temp_setting: #Decimal<22.0>, elevation: nil, est_battery_range_km: #Decimal<273.69>, fan_status: 3, id: 1268449, ideal_battery_range_km: #Decimal<292.47>, inside_temp: #Decimal<27.6>, is_climate_on: true, is_front_defroster_on: false, is_rear_defroster_on: false, latitude: #Decimal<43.320882>, longitude: #Decimal<5.373369>, odometer: 47550.911259, outside_temp: #Decimal<28.0>, passenger_temp_setting: #Decimal<22.0>, power: 2, rated_battery_range_km: #Decimal<292.47>, speed: 6, usable_battery_level: 65}

    (ecto 3.7.1) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
    (teslamate 1.24.2) lib/teslamate/terrain.ex:158: TeslaMate.Terrain.handle_event/4
    (stdlib 3.16) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
    (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-10-01 12:44:45.808 [info] Adding elevation to 481 positions ...
2021-10-01 12:44:45.905 [error] GenStateMachine TeslaMate.Terrain terminating
** (Ecto.StaleEntryError) attempted to update a stale struct:

%TeslaMate.Log.Position{__meta__: #Ecto.Schema.Metadata<:loaded, "positions">, battery_heater: false, battery_heater_no_power: nil, battery_heater_on: false, battery_level: 66, car: #Ecto.Association.NotLoaded<association :car is not loaded>, car_id: 1, date: ~U[2021-09-28 16:34:35.709000Z], drive: #Ecto.Association.NotLoaded<association :drive is not loaded>, drive_id: 362, driver_temp_setting: #Decimal<22.0>, elevation: nil, est_battery_range_km: #Decimal<273.69>, fan_status: 3, id: 1268449, ideal_battery_range_km: #Decimal<292.47>, inside_temp: #Decimal<27.6>, is_climate_on: true, is_front_defroster_on: false, is_rear_defroster_on: false, latitude: #Decimal<43.320882>, longitude: #Decimal<5.373369>, odometer: 47550.911259, outside_temp: #Decimal<28.0>, passenger_temp_setting: #Decimal<22.0>, power: 2, rated_battery_range_km: #Decimal<292.47>, speed: 6, usable_battery_level: 65}

    (ecto 3.7.1) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
    (ecto 3.7.1) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
    (teslamate 1.24.2) lib/teslamate/terrain.ex:121: TeslaMate.Terrain.handle_event/4
    (stdlib 3.16) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
    (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-10-01 12:44:51.165 [info] Application teslamate exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,teslamate,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,teslamate,shutdown})

Crash dump is being written to: erl_crash.dump...done

**Comment by r4mses** [comment]
I think it's coming from the network interface from the container, I'm losing connectivity :
64 bytes from 172.18.0.3: icmp_seq=48 ttl=64 time=0.201 ms
64 bytes from 172.18.0.3: icmp_seq=49 ttl=64 time=0.168 ms
64 bytes from 172.18.0.3: icmp_seq=50 ttl=64 time=0.183 ms
64 bytes from 172.18.0.3: icmp_seq=51 ttl=64 time=0.203 ms
From 172.18.0.1 icmp_seq=59 Destination Host Unreachable
From 172.18.0.1 icmp_seq=60 Destination Host Unreachable
From 172.18.0.1 icmp_seq=61 Destination Host Unreachable
From 172.18.0.1 icmp_seq=62 Destination Host Unreachable
From 172.18.0.1 icmp_seq=63 Destination Host Unreachable
From 172.18.0.1 icmp_seq=64 Destination Host Unreachable
From 172.18.0.1 icmp_seq=65 Destination Host Unreachable
From 172.18.0.1 icmp_seq=66 Destination Host Unreachable
From 172.18.0.1 icmp_seq=67 Destination Host Unreachable
64 bytes from 172.18.0.3: icmp_seq=68 ttl=64 time=252 ms
64 bytes from 172.18.0.3: icmp_seq=69 ttl=64 time=0.189 ms
64 bytes from 172.18.0.3: icmp_seq=70 ttl=64 time=0.194 ms
64 bytes from 172.18.0.3: icmp_seq=71 ttl=64 time=0.268 ms
64 bytes from 172.18.0.3: icmp_seq=72 ttl=64 time=0.243 ms

Not sure if I don't have connectivity because teslamate is restarting or if because of the network interuption I'm losing teslamate.....

**Comment by adriankumpf** [comment]
I still don't understand what causes this, but try the following:

```sql
update positions set elevation = 0 where elevation is null;
```

**Comment by r4mses** [comment]
Here is the result : 

pi@RaspberryPiNico:~ $ docker-compose exec database psql teslamate teslamate -c "update positions set elevation = 0 where elevation is null;"
ERROR:  duplicate key value violates unique constraint "positions_pkey"
DETAIL:  Key (id)=(1254993) already exists.
ERROR: 1

**Comment by adriankumpf** [comment]
OK this shows that there is no bug here. The database is in a corrupt state. Since you're using a rpi would strongly recommend to restore a backup on a new SD card. I'll convert this to a discussion.
