### ISSUE TITLE
Unexpected car model display - likely API update

### ISSUE THREAD

**Issue by rmyadsk** [adriankumpf/teslamate#2030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Earlier today I noticed one of my vehicles (a 2018 Long-Range Model 3) began being displayed as a "Model 3 74" on my Teslamate front page. Later this evening I noticed my other Model 3, a 2019 Standard-Range Plus, is now being displayed as a "Model 3 50".

Can anyone else replicate this? If so, it sounds likely Tesla updated their API with new styles/trims we may be able to derive display names from these various number codes.

### Expected Behavior

Formerly, Teslamate displayed both of my vehicles as simply "Model 3".

### Steps To Reproduce

1. Go to your Teslamate front page.
2. Observe your vehicle's model/trim notation.

### Relevant log output

```shell
There do not appear to be any relevant log lines - no errors are invoked.
```

### Screenshots

![Screen Shot 2021-10-04 at 8 51 49 PM](https://user-images.githubusercontent.com/820865/135943841-63abd933-d79b-403b-87b6-b9bc4a999507.png)

### Type of installation

Docker

### Version

v1.24.2

**Comment by natrlhy** [comment]
Ah mine shows Model 3 P74D

![image](https://user-images.githubusercontent.com/19696424/135953085-d9168ec4-0641-421c-9ff5-6ac7ee3b0072.jpeg)

**Comment by rmyadsk** [comment]
@natrlhy  I would suspect P74d might be Performance Dual-Motor?

**Comment by natrlhy** [comment]
Correct. We have a Model 3 Performance Dual Motor. 74 signifies the Dual Motor/Long Range (74kW battery pack)

**Comment by rmyadsk** [comment]
@adriankumpf I believe we may have the beginnings of an index for "friendly" names for models?

**Comment by adriankumpf** [comment]
> @adriankumpf I believe we may have the beginnings of an index for "friendly" names for models?

Yep, looks like it. The API now returns `trim_badging: "p74d"` in case of the Model 3, for example. 

Personally, I don't mind the trim being displayed. Maybe the way it is styled could be slightly adjusted.

**Comment by olexs** [comment]
I like it as well. Maybe a mapping to the "marketing" names could be added - "50" to "SR+", "74" to LR, "74d" to LR AWD etc, and show the "technical" badge in a mouseover.

Also could be interesting to see whether the newer 3 and Y models show the 82 kWh packs in the trim, and what the Plaid S shows, if somebody actually uses TeslaMate with one.

**Comment by rmyadsk** [comment]
> I like it as well. Maybe a mapping to the "marketing" names could be added - "50" to "SR+", "74" to LR, "74d" to LR AWD etc, and show the "technical" badge in a mouseover.

Excellent idea - that, or perhaps a switch available under Settings where the user can toggle marketing names on/off.
