### ISSUE TITLE
Copy Data From Different DBs

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#204]
Hi @adriankumpf I've been doing alot of testing to get a Teslamate working properly.  As I've been spinning multiple VMs up - data has been captured in different DBs.  I was wondering if there is a way to import the data into my main Teslamate instance?  

Conversely, if the aforementioned cannot be done - I was wondering if there is a way preserve the original Teslamate DB, while upgrading from your recommended docker implementation to the advanced docker solution (SSL, FQDN, password).

As always - many thanks!

**Comment by adriankumpf** [comment]
> I was wondering if there is a way to import the data into my main Teslamate instance?

Good question. I haven't tried that yet. From a technical point of view, that's definitely possible. However, depending on the amount of data, it would be quite a lot of manual work.

> Conversely, if the aforementioned cannot be done - I was wondering if there is a way preserve the original Teslamate DB, while upgrading from your recommended docker implementation to the advanced docker solution (SSL, FQDN, password).

If the original DB is located on the same VM it should work out-of-the-box. Both docker-compose file reference the same docker volume (`teslamate-db`). If you plan to migrate to a different VM I'd backup to whole postgres db and restore it on the new machine.

**Comment by jun3280net** [comment]
@adriankumpf - for importing data - I have about a month and a half worth of data.  

With regards to the second question - for whatever reason, when I try and upgrade an existing DB it complains about incorrect login/password - which I noted in the original thread #153 - password failed to authenticate for user teslamate.

I even tried matching the logins/password from your original Docker - literally (teslamate/secret) and it wouldn't work.  Were you able to get it to work?

@spacecosmos stated he needed to start from scratch to get it to work - which I ended up doing as well.

**Comment by adriankumpf** [comment]
> "password failed to authenticate for user teslamate." 

When starting TeslaMate is loads the api token from the database and refreshes it (i.e. it gets a new token). This invalidates the previous token. So if two installations use the same docker volume / api token and are running simultaneously it won't work. Either delete the tokens from the database before starting the new container or make sure  there aren't two `teslamate` containers that use the same database running at the same time. Then it should work.

**Comment by patrice-ebr** [comment]
I also ended having two TeslaMate DBs after my Windows desktop power supply blew and I had to spin up a new TeslaMate on my laptop Mac in a rush just before going on vacation.

You mention "it would be quite a lot of manual work"... I haven't look at the DB model yet, but I presume a lot of that would be around generated unique record IDs that were probably seeded off the same value on both systems?

**Comment by jun3280net** [comment]
> > "password failed to authenticate for user teslamate."
> 
> When starting TeslaMate is loads the api token from the database and refreshes it (i.e. it gets a new token). This invalidates the previous token. So if two installations use the same docker volume / api token and are running simultaneously it won't work. Either delete the tokens from the database before starting the new container or make sure there aren't two `teslamate` containers that use the same database running at the same time. Then it should work.

@adriankumpf How do I tell if I have two docker containers?  I literally took the new YML from the advanced setup and pasted over the YML from your original recommended setup.  I can only assume its trying to write to the same DB given the error messages.

On that note, as I'm very new to Linux world - I'm learning by trial by fire, and recording the steps/commands as I go along the way.  How do I go about delete the tokens from the original database?

Thanks a bunch

**Comment by adriankumpf** [comment]
> I haven't look at the DB model yet, but I presume a lot of that would be around generated unique record IDs that were probably seeded off the same value on both systems?

Yep. That's exactly what I was referring to. With a lot of data, it is probably worth writing a small script to do this.

@jun3280net `docker ps` lists all running containers. But with your approach it should have worked I think. Before you delete the token from the db, could you start the docker-compose stack (the advanced setup) one more time? I wonder what the exact log message looks like.

**Comment by jun3280net** [comment]
> @jun3280net `docker ps` lists all running containers. But with your approach it should have worked I think. Before you delete the token from the db, could you start the docker-compose stack (the advanced setup) one more time? I wonder what the exact log message looks like.

@adriankumpf thanks for looking into this for me.  I've attached my log per your request.  

On a separate note, in spinning up this new VM with this new advanced setup I am unable to to access Teslamate / Grafana page via the FQDN's I was previously able to access.  Do you see anything in the log?

When running the server, I can confirm that both port 80 & 443 have been forwarded properly, and show up as OPEN on CANYOUSEEME.  

The two subdomains no longer work.  
https://grafana.xyz123.dynu.com
https://teslamate.xyz123.dynu.com

However, http://xyz123.dynu.com returns the "404 page not found" - which I believe shows the server is working.  

[FQDN_Setup_Log.txt](https://github.com/adriankumpf/teslamate/files/3727644/FQDN_Setup_Log.txt)

Thanks

**Comment by adriankumpf** [comment]
I got it wrong. I initially thought the Error was related to the API authentication but it seems the database credentials are the issue. After replacing the YAML files and it worked right away. I used those environment variables: 

```
   1   │ TM_DB_USER=teslamate
   2   │ TM_DB_PASS=secret
   3   │ TM_DB_NAME=teslamate
```

As for your other question, I am afraid this has nothing to do with the actual application and I don't have time to look at it more closely. Sorry.

**Comment by jun3280net** [comment]
> I got it wrong. I initially thought the Error was related to the API authentication but it seems the database credentials are the issue. After replacing the YAML files it worked right away. I used these environment variables:
> 
> ```
>    1   │ TM_DB_USER=teslamate
>    2   │ TM_DB_PASS=secret
>    3   │ TM_DB_NAME=teslamate
> ```
> 
> As for your other question, I am afraid this has nothing to do with the actual application and I don't have time to look at it more closely. Sorry.

@adriankumpf thanks I started from scratch and used the above settings and it worked.  No more error messages - although I am still unable to access the server.  I had used "secret" when creating the .htpasswd file and left TM_DB_PASS as "yourdbpass" per your Wiki. 

Given that you've solved this issue - your wiki should be updated to allow others to upgrade from recommended to advanced more seamlessely :)

Thanks!
