### ISSUE TITLE
Range data missing from Grafana Charges/Charge Details for Charges prior to 2019-10-11

### ISSUE THREAD

**Issue by patrice-ebr** [adriankumpf/teslamate#208]
I've been running TeslaMate since Sept 4th (don't quite remember which version I pulled at the time) and I've been enjoying it a lot. Many thanks for quality work.
I updated to most recent version on Oct 11th and 14th.

Charge Table & Charge Details captured with these two versions are showing with all details in Grafana.
Charges prior to that date are missing range data (circle in red on screenshots).
I know I have seen these missing values previously before these last two updates, so the data was captured and is likely still present in the DB put not showing anymore in Grafana.

Is it possibly linked to the addition of 'Preferred Range' settings? 
Looking at Grafana JSON, I'm seeing the select statement seems to be using this new setting and that did not exist before these last two releases.

Charge Table:
<img width="872" alt="Screen Shot 2019-10-17 at 10 08 28 PM" src="https://user-images.githubusercontent.com/54874971/67060641-bb504b00-f12b-11e9-9c38-e51efd4bf3fc.png">
Charge Detail:
<img width="768" alt="Screen Shot 2019-10-17 at 10 16 59 PM" src="https://user-images.githubusercontent.com/54874971/67060745-04080400-f12c-11e9-829e-50901475e5be.png">

Thanks for the help.

**Comment by adriankumpf** [comment]
Yes, with the introduction of the "preferred range" setting with version 1.9.0 TeslaMate started recording the rated range in addition the the ideal range. To see the range data for all charges you'd need to change the preferred range back to "ideal".

**Comment by patrice-ebr** [comment]
Indeed, that worked to see all of the 'ideal' range values. Thanks.

Before the introduction of 'Preferred', I remember the Grafana charge detail graphs were showing two range value lines. So, some other 'range' value was recorded before. 
I think for Model S, it actually was 'rated' while Model 3 was more 'estimated'. I remember the discrepancy between both set of values but I was just getting familiar with TeslaMate so I hadn't raised any issue here yet. 
Is this second value still in the DB if we customize Grafana? Column name? Thanks.
