### ISSUE TITLE
grafana segfault during "docker-compose up" startup  on RPI

### ISSUE THREAD

**Issue by etroulland** [adriankumpf/teslamate#209]
**Describe the bug**
Grafana crash on startup

**To Reproduce**
docker-compose up gives :

grafana_1    | /run.sh: line 68:    11 Segmentation fault      grafana-cli --pluginsDir "${GF_PATHS_PLUGINS}" plugins install ${plugin}

 docker-compose ps
        Name                       Command                State             Ports
------------------------------------------------------------------------------------------
teslamate_db_1          docker-entrypoint.sh postgres    Up         5432/tcp
teslamate_grafana_1     /run.sh                          Exit 139
teslamate_mosquitto_1   /docker-entrypoint.sh /usr ...   Up         0.0.0.0:1883->1883/tcp
teslamate_teslamate_1   /bin/sh /entrypoint.sh bin ...   Up         0.0.0.0:4000->4000/tcp

```
 sudo docker-compose up
[1] 22620
Starting teslamate_mosquitto_1   ... done
Recreating teslamate_grafana_1   ... done
Starting teslamate_db_1          ... done
Recreating teslamate_teslamate_1 ... done
Attaching to teslamate_mosquitto_1, teslamate_db_1, teslamate_grafana_1, teslamate_teslamate_1
mosquitto_1  | 1571392850: mosquitto version 1.6.7 starting
mosquitto_1  | 1571392850: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto_1  | 1571392850: Opening ipv4 listen socket on port 1883.
mosquitto_1  | 1571392850: Opening ipv6 listen socket on port 1883.
grafana_1    | /run.sh: line 68:    11 Segmentation fault      grafana-cli --pluginsDir "${GF_PATHS_PLUGINS}" plugins install ${plugin}
db_1         | 2019-10-18 10:00:51.052 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2019-10-18 10:00:51.053 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2019-10-18 10:00:51.101 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2019-10-18 10:00:54.125 UTC [23] LOG:  database system was shut down at 2019-10-18 09:55:54 UTC
db_1         | 2019-10-18 10:00:54.206 UTC [1] LOG:  database system is ready to accept connections
db_1         | 2019-10-18 10:00:55.643 UTC [30] LOG:  incomplete startup packet
teslamate_grafana_1 exited with code 139
teslamate_1  | 12:01:10.683 [info] Already up
teslamate_1  | 12:01:57.876 [info] Running TeslaMateWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)
teslamate_1  | 12:01:57.883 [info] Access TeslaMateWeb.Endpoint at http://192.168.1.34
teslamate_1  | 12:01:57.976 [info] Adding elevation to 1 positions ...
teslamate_1  | 12:01:58.027 [info] Querying location for elevation takes longer than 50ms ...
teslamate_1  | 12:01:59.373 [info] Found 'Dolores'
teslamate_1  | 12:01:59.427 [info] Initializing handler
teslamate_1  | 12:01:59.429 [info] Connection has been established
teslamate_1  | 12:02:00.677 car_id=1 [info] Start / :online


```

**Screenshots**

**Operating environment (please complete the following information):**
 - OS: Debian 9.11 on RP (Model 2 B Revision 1.1 1GB, (Sony))
 - Version [e.g. v1.7.0]

** 
docker-compose.yaml is the example except : 
      - VIRTUAL_HOST=192.168.1.34

**Comment by adriankumpf** [comment]
Thanks for the detailed report! Does this issue persist after restarting Grafana? It looks similiar to [this bug](https://github.com/grafana/grafana/issues/6256) Grafana had a while ago.

**Comment by etroulland** [comment]
Nope it crashes at the first start. It's a clean install.

**Comment by etroulland** [comment]
Work from a fresh install (raspbian / docker / docker-compose )

**Comment by adriankumpf** [comment]
Okay 👍 Grafana 6.5 will further improve the compatibility with ARM platforms.
