### ISSUE TITLE
404 to query the vehicle in China when Teslamate is hosted outside China

### ISSUE THREAD

**Issue by Au8ust** [adriankumpf/teslamate#2124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After Tesla build the datacenter in China, my teslamate hosted in HK was unable to find the car in my account. 404 is returned.

### Relevant log output

```shell
teslamate_1  | 2021-11-02 16:16:57.377 [info] Scheduling token refresh in 1 h
teslamate_1  | 2021-11-02 16:16:57.379 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2021-11-02 16:16:57.384 [info] Access TeslaMateWeb.Endpoint at httptp://tesla.eastasia.cloudapp.azure.com
teslamate_1  | 2021-11-02 16:16:59.390 [info] Starting logger for 'XXX' teslamate_1  | 2021-11-02 16:16:59.437 [info] MQTT connection has been established
teslamate_1  | 2021-11-02 16:17:00.382 [info] GET https://owner-api.teslamotors.om/api/1/vehicles/xxxxx-> 404 (947.097 ms)
teslamate_1  | 2021-11-02 16:17:00.382 car_id=1 [error] Error /:vehicle_not_found
```

### Type of installation

Manual

### Version

v1.24.2

**Comment by ddjj181** [comment]
You can try pull again the latest version of TeslaMate, either stable or dev

**Comment by ddjj181** [comment]
You can try pull again the latest version of TeslaMate
https://github.com/adriankumpf/teslamate/issues/2102

**Comment by Au8ust** [comment]
> You can try pull again the latest version of TeslaMate
> #2102

Tried it but still no luck.

**Comment by Au8ust** [comment]
It seems fixed without changes.
