### ISSUE TITLE
Grafana data empty

### ISSUE THREAD

**Issue by JunniH** [adriankumpf/teslamate#215]
I've just setup Teslamate on my local docker environment. Everything seems to be running fine, Teslamate is returning my car data (online, location, Sentry/Locked states, etc), but Grafana doesn't display any data, except for my car's name.

During composer up I don't get any errors, only info statements but everything seems to be running well.

Running Teslamate on docker on MacOS Mojave 10.14.6.

**Comment by adriankumpf** [comment]
Your vehicle does not provide data from the past. Expect data to be displayed after the first trip, charging or the installation of an update etc.

**Comment by JunniH** [comment]
Thanks Adrian for your quick response, and I feel a little bit silly now! I will review the dashboard this evening after my ride home.

**Comment by adriankumpf** [comment]
No worries!
