### ISSUE TITLE
Statistics - the last two columns are displayed as long int value

### ISSUE THREAD

**Issue by petariga** [adriankumpf/teslamate#2153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The last two columns in the Statistics dashboard, named "date_from" "date_to", are displayed as probably long int time value, for example "1635724800000" "1638316800000" for November 2021. It seems that they might be forgotten from some debugging, otherwise I don't see the purpose of these two columns. "date_from" is already present in the second column "Starting at" and "date_to" can be read in connection with the first column "Period". These two columns "date_from" "date_to" are also a bit hidden at/behind the right end of the table/screen.

### Expected Behavior

Either do not display these two columns or display them in a human readable form (not a longint #).

### Relevant log output

```shell
n/a
```

### Screenshots

![image](https://user-images.githubusercontent.com/64809507/141818464-321a85dd-4164-4fc5-a145-8f37406747d9.png)

### Type of installation

Docker

### Version

v1.24.2

**Comment by DrMichael** [comment]
Well, the simple answer is, they are used in th elinks and should be hidden. That was not possible so far.
https://github.com/grafana/grafana/issues/24092#issuecomment-951557730 appears to have fixed that.
@adriankumpf shall we give grafana-8.2.0 a try?

**Comment by adriankumpf** [comment]
I have started working on a branch for Grafana 8 (https://github.com/adriankumpf/teslamate/tree/grafana-8). Although https://github.com/grafana/grafana/issues/24092 was implemented on Grafana main it's still  buggy.  So as long as this feature is not stable, Grafana 8 is on hold.
