### ISSUE TITLE
Email Login Error Authorization Failed

### ISSUE THREAD

**Issue by hoang51** [adriankumpf/teslamate#2159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I set up Teslamate for the first time (USA user), chose to login Tesla via email/password instead of using existing API tokens. The error given was: 

> Error: :authorization_failed

In the SSH console, I see the following log:

> teslamate_1  | 2021-11-17 16:40:27.614 [info] GET /sign_in
> teslamate_1  | 2021-11-17 16:40:27.619 [info] Sent 200 in 5ms
> teslamate_1  | 2021-11-17 16:41:47.463 [info] GET https://auth.tesla.com/oauth2/v3/authorize -> 200 (415.139 ms)
> teslamate_1  | 2021-11-17 16:41:47.607 [error] POST https://auth.tesla.com/oauth2/v3/authorize -> 403 (138.538 ms)

If I go to the link https://auth.tesla.com/oauth2/v3/authorize given in the log via Chrome, it shows that the website reported an error:

> Error has occurred
> Bad Request 

### Expected Behavior

Expected to successfully log into my Tesla account via email/password to begin capturing data from my Tesla vehicle.

### Steps To Reproduce

1. Go to public FQDN address.
2. Once at Teslamate log in screen, instead of using Access Token & Refresh Token, click "Use email and password" link at the bottom.
3. Once at the email and password screen log in, enter in credentials as the same as Tesla.com.
4. Click Sign in button.
5. Get a red banner displaying "Error: :authorization_failed".

### Relevant log output

```shell
teslamate_1  | 2021-11-17 16:40:27.614 [info] GET /sign_in
teslamate_1  | 2021-11-17 16:40:27.619 [info] Sent 200 in 5ms
teslamate_1  | 2021-11-17 16:41:47.463 [info] GET https://auth.tesla.com/oauth2/v3/authorize -> 200 (415.139 ms)
teslamate_1  | 2021-11-17 16:41:47.607 [error] POST https://auth.tesla.com/oauth2/v3/authorize -> 403 (138.538 ms)
```

### Type of installation

Docker

### Version

1.25.0

**Comment by adriankumpf** [comment]
Tesla now returns a page saying

> Access Denied
> You don't have permission to access "http://auth.tesla.com/oauth2/v3/authorize" on this server.

Until a few days ago you would have received an error message "Recaptcha is required" because Tesla require a Google reCAPTCHA to generate API tokens. See https://github.com/adriankumpf/teslamate/issues/1945#issuecomment-913684723.

The bottom line is that currently logging in is only possible with manually generated tokens.

**Comment by hoang51** [comment]
Thanks for reviewing issue and providing greater clarity on the login issue. I was reluctant to use a Tesla token generating app, but since this leaves me no other choice, I've gone ahead and downloaded Tesla Tokens app for Android. I successfully logged in with the tokens generated and data are starting to be logged to Teslamate. Thanks for everything. :)

**Comment by ogbrugge** [comment]
The docker image that is currently available is still giving this error when logging in with email/password, please disable logging in with email/password completely or warn that it is currently not possible to do so.

**Comment by IKyriazis** [comment]
^Agreed plz note that email/password login is currently unavailable

**Comment by techlogik** [comment]
Ok great, so now we can't login to Teslamate without generating tokens on the install and email login isn't supported? Get rid of the login for email then please.

**Comment by petariga** [comment]
Just to let others know - yesterday a big number (probably tens of thousands globally) of old tokens have been revoked by Tesla. There seems to be a security issue ongoing. Thus, a lot of Teslamate users will need to relogin/authenticate again and they might be confused by not functioning login with e-mail/password in Teslamate.

https://twitter.com/tezlabapp/status/1481180064926547969?s=21
