### ISSUE TITLE
Feature Request: Position Dashboard : indicator too small

### ISSUE THREAD

**Issue by dwilasnd** [adriankumpf/teslamate#218]
The Grafana position indicator on the Position Dashboard is showing up as a very small red dot. Almost like a bad pixel on the screen. Can this dot be thicker, or an image of a pushpin, or maybe the Tesla logo?

**Comment by adriankumpf** [comment]
That's not possible right now. The author of the Grafana map plugin[1] would first have to implement a function that would allow this.

[1] https://github.com/pR0Ps/grafana-trackmap-panel
