### ISSUE TITLE
A potential `division by zero` error in db

### ISSUE THREAD

**Issue by Ma233** [adriankumpf/teslamate#2183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, I'm not familiar with ecto, so I might be wrong.

This line is from https://github.com/adriankumpf/teslamate/blob/0a127f60a98b6fbe9a429e8df4ba115e6014064d/lib/teslamate/log.ex#L493

It will become `avg(c.charger_power * 1000.0 / 0)` if `c.charger_actual_current * c.charger_voltage` is null.
In that situation, a division by zero in database might be raised.

### Relevant log output

```shell
no log
```

### Type of installation

Manual

### Version

v1.25.0

**Comment by gryghst72** [comment]
Possibly reported here:
https://github.com/adriankumpf/teslamate/issues/2063

**Comment by adriankumpf** [comment]
If `charger_actual_current` or `charger_voltage` are NULL it will divide by `NULL`, resulting in `NULL`. If `c.charger_actual_current * c.charger_voltage` is `0` the division by zero is prevented by the `NULLIF(.., 0)`, therefore also resulting in `NULL`.
