### ISSUE TITLE
Charging Double Counting

### ISSUE THREAD

**Issue by mapchen** [adriankumpf/teslamate#219]
I think I have some double counting on my charges today. I was charging two times and I had the cable always plugged in. First I charged to 78%. Then some hours later I charged to 90%. It seems that the second charge is not correct as I was always charging with 16-17KW and for 48 min.

![image](https://user-images.githubusercontent.com/56200461/67594067-d6dad780-f763-11e9-8d76-7e07fc651ab8.png)

First Charge:
![image](https://user-images.githubusercontent.com/56200461/67594090-e2c69980-f763-11e9-8044-48fe05a24441.png)

Second Charge:
![image](https://user-images.githubusercontent.com/56200461/67594139-ff62d180-f763-11e9-9d00-df3cdf23b84d.png)

State Change seems to be fine:
![image](https://user-images.githubusercontent.com/56200461/67594213-228d8100-f764-11e9-9023-fb7b7f14610a.png)

**Comment by adriankumpf** [comment]
Could you please add the data of those charges to this issue?

```bash
docker-compose exec db psql teslamate teslamate -c \
   "COPY (select * from charges where date > '2019-10-24') TO STDOUT WITH CSV" > charges.csv
```

**Comment by mapchen** [comment]
here we go. converted to xlsx because upload of csv not supported. thanks for your efforts

[charges.xlsx](https://github.com/adriankumpf/teslamate/files/3774476/charges.xlsx)

**Comment by adriankumpf** [comment]
The problem was that the car reset the charge twice, i.e. the reported added energy was reset to zero. I have added an additional check for now that tries to detect these anomalies. This is not a real fix, but since the problem seems to be a firmware bug in the end, this has to be enough for now.
