### ISSUE TITLE
Adding 'remaining time' while charging in Teslamate webapp

### ISSUE THREAD

**Issue by vkarthikbalaji** [adriankumpf/teslamate#221]
When the vehicle is charging, the Teslamate webapp shows the status as 'charging for 1hr', however it would be handy to show the remaining time until charge complete.

I have used docker based advanced setup on my VPS. Thanks.

**Comment by vkarthikbalaji** [comment]
API help -

`curl --request GET --header 'Authorization: Bearer $TOKEN$' 'https://owner-api.teslamotors.com/api/1/vehicles/19044034947918470/data_request/charge_state'
{"response":{"battery_heater_on":false,"battery_level":67,"battery_range":154.48,"charge_current_request":13,"charge_current_request_max":13,"charge_enable_request":true,"charge_energy_added":8.69,"charge_limit_soc":80,"charge_limit_soc_max":100,"charge_limit_soc_min":50,"charge_limit_soc_std":90,"charge_miles_added_ideal":39.5,"charge_miles_added_rated":39.5,"charge_port_cold_weather_mode":false,"charge_port_door_open":true,"charge_port_latch":"Engaged","charge_rate":12.4,"charge_to_max_range":false,"charger_actual_current":13,"charger_phases":1,"charger_pilot_current":13,"charger_power":3,"charger_voltage":228,"charging_state":"Charging","conn_charge_cable":"IEC","est_battery_range":138.36,"fast_charger_brand":"<invalid>","fast_charger_present":false,"fast_charger_type":"MCSingleWireCAN","ideal_battery_range":154.48,"managed_charging_active":false,"managed_charging_start_time":null,"managed_charging_user_canceled":false,"max_range_charge_counter":0,**"minutes_to_full_charge":140**,"not_enough_power_to_heat":null,"scheduled_charging_pending":false,"scheduled_charging_start_time":null,**"time_to_full_charge":2.33**,"timestamp":1572254693581,"trip_charging":false,"usable_battery_level":67,"user_charge_enable_request":null}}`

**Comment by vkarthikbalaji** [comment]
Thanks :)
![image](https://user-images.githubusercontent.com/41284844/68087932-99a8d080-fe5a-11e9-90f5-084f2ef1d7a6.png)

**Comment by adriankumpf** [comment]
oops, one too many :D
