### ISSUE TITLE
[FR] DietPi automated deployment/update

### ISSUE THREAD

**Issue by fiveangle** [adriankumpf/teslamate#223]
DietPi is a lightweight distro and deployment system designed for deploying packages similar to teslamate with focus on hyper lightweight deployment for resource-limited environments like RPi, etc.

It would be extremely useful if support was implemented to allow Teslamate deployment via the DietPi software deployment mechanism.  I did a little research and I believe this is the basic process in adding support:

https://github.com/MichaIng/DietPi/issues/490#issuecomment-244416570

I have a DietPi deployment running Pi-Hole and PiVPN and am working on implimenting Teslamate by hand on the device.  I will note here what (if any) issues I run into.

Thanks for considering !

**Comment by JakobLichterfeld** [comment]
Can you give some hints what would be the benefit compared to current docker deployment?

**Comment by fiveangle** [comment]
Haven’t forgot. Will circle back in a couple weeks. Thx !

**Comment by fiveangle** [comment]
Sorry for the delay, but obiviously life priorities have pushed this backseat.  There has been some changes in the dietpi support for containers so I will review the resource usage discrepancy (if any still) and if it still makes sense to deploy natively, I will open a new issue.  Thanks again !

**Comment by adriankumpf** [comment]
All right, thanks for the update.
