### ISSUE TITLE
Chinese accounts: Drives are seperated to multiple blank records

### ISSUE THREAD

**Issue by em91** [adriankumpf/teslamate#2239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Question 1:

After Decemeber 25, drives are not properly logged any more. Multiple blank records are shown in grafana timeline instead.

Is this Tesla api broblem? I found frequent "start of drive" log when i was still driving:

teslamate_1  | 2021-12-26 20:31:18.285 [info] Start of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: xxx, heading: 344, latitude: xxx, longitude: xxx, native_latitude: xxx, native_location_supported: 1, native_longitude: xxx, native_type: "gcj", power: 1, shift_state: "D", speed: 0, timestamp: xxx}

Question 2:

BTW, charge records is missing too, i found this error in docker log after charge ended:

teslamate_1  | 2021-12-26 20:28:41.572 car_id=1 [info] Charging / Stopped / 0.00 kWh – 0 min
teslamate_1  | 2021-12-26 20:28:41.574 car_id=1 [info] Start / :online
teslamate_1  | 2021-12-26 20:28:41.579 car_id=1 [info] Connecting ...
teslamate_1  | 2021-12-26 20:28:41.580 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.8885.1>}}
teslamate_1  |     (teslamate 1.25.0) lib/teslamate/vehicles/vehicle.ex:708: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.16.1) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

Question 3:

Do you have any way to merge these annoying blank records to the original normal drive record.. 

### Relevant log output

```shell
Driving Log:
teslamate_1  | 2021-12-26 20:31:18.285 [info] Start of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: xxx, heading: 344, latitude: xxx, longitude: xxx, native_latitude: xxx, native_location_supported: 1, native_longitude: xxx, native_type: "gcj", power: 1, shift_state: "D", speed: 0, timestamp: xxx}


Charge Log:
teslamate_1  | 2021-12-26 20:28:41.572 car_id=1 [info] Charging / Stopped / 0.00 kWh – 0 min
teslamate_1  | 2021-12-26 20:28:41.574 car_id=1 [info] Start / :online
teslamate_1  | 2021-12-26 20:28:41.579 car_id=1 [info] Connecting ...
teslamate_1  | 2021-12-26 20:28:41.580 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.8885.1>}}
teslamate_1  |     (teslamate 1.25.0) lib/teslamate/vehicles/vehicle.ex:708: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.16.1) gen_statem.erl:1196: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Screenshots

![image](https://user-images.githubusercontent.com/1333368/147409360-19e4b9ca-ce35-4c9f-8fb7-aedfef4bab66.png)

### Type of installation

Docker

### Version

v1.25.0

**Comment by DrMichael** [comment]
You should probably make an update...
https://github.com/adriankumpf/teslamate/issues/1996

**Comment by em91** [comment]
> 

teslamate_1  | 2021-12-26 22:40:24.016 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2021-12-26 22:40:24.016 [info] Version: 1.25.0

Already latest version, sorry provided wrong version at first (modified)

**Comment by jjzxmmx** [comment]
I also had the same problem, but I found it from the time I upgraded 2021.44.25.2

**Comment by aishlai** [comment]
I also had the same problem, but I found it from the time I upgraded 2021.44.25.2 （china user）

**Comment by madswaord** [comment]
Same issue, but I got 44.25 updated yesterday morning, all trips since updated yesterday are shown correct, but all trips today blank, and road-trip still shown on maps.

**Comment by sempliciy** [comment]
I also had the same problem, since 26th night（china user）

**Comment by summergeorge** [comment]
> I also had the same problem, since 26th night（china user）

same problem

**Comment by tangweiji** [comment]
I also had the same problem, since 26th night（china user）

**Comment by tangweiji** [comment]
I also had the same problem, since 27h （china user）
![image](https://user-images.githubusercontent.com/34420702/147567382-b28639ef-9951-4e70-b54f-a11304a1cba8.png)
![image](https://user-images.githubusercontent.com/34420702/147567419-d043c6b9-7177-457b-9deb-45f5777daa06.png)
![image](https://user-images.githubusercontent.com/34420702/147567435-28010620-f19a-461e-8f94-7b1147160b4a.png)

**Comment by torobucks** [comment]
No problem after upgrade to the 44.25.(China User)

**Comment by chenkehxx** [comment]
same problem(China User)
<img width="1602" alt="Screen Shot 2021-12-28 at 22 01 31" src="https://user-images.githubusercontent.com/5397691/147574167-2646d526-93a4-44b8-ba18-baf28cadff15.png">

**Comment by martin0607** [comment]
Same issue. After updated to V11(2021.44.25.2), everything is fine except Drives data(No Drives data was recorded).
![屏幕截图 2021-12-28 215340](https://user-images.githubusercontent.com/32560181/147575044-cd475b78-3409-4555-add6-d2ae7cb9a58d.jpg)

**Comment by tangweiji** [comment]
reboot car computer it's work![image](https://user-images.githubusercontent.com/34420702/147576661-9f87de9c-95c8-4a5f-b183-5c4feea08376.png)

**Comment by martin0607** [comment]
reboot didnt work for me:(

**Comment by wg-cn** [comment]
> user

me too

**Comment by madswaord** [comment]
> reboot car computer it's work![image](https://user-images.githubusercontent.com/34420702/147576661-9f87de9c-95c8-4a5f-b183-5c4feea08376.png)

reboot didnt work for me

**Comment by yaksazq** [comment]
I also had the same problem, since 27h （china user）

**Comment by summergeorge** [comment]
reboot didnt work for me (china user)

**Comment by martin0607** [comment]
Any one tried update to edge version(maybe 1.26.0)?

**Comment by wg-cn** [comment]
> Any one tried update to edge version(maybe 1.26.0)?

如何升级edge版本？

**Comment by martin0607** [comment]
> > Any one tried update to edge version(maybe 1.26.0)?
> 
> 如何升级edge版本？

replace 'teslamate/teslamate:latest' with 'teslamate/teslamate:edge' in compose yml

**Comment by madswaord** [comment]
> > > Any one tried update to edge version(maybe 1.26.0)?
> > 
> > 
> > 如何升级edge版本？
> 
> replace 'teslamate/teslamate:latest' with 'teslamate/teslamate:edge' in compose 

yml

i tried to update the edge version, but still blank records, one trip separated to dozens black trips.
<img width="1480" alt="截屏2021-12-30 下午3 17 14" src="https://user-images.githubusercontent.com/86275875/147729954-af0cfc9e-2ac3-4771-9b8a-eddd89bebca9.png">

**Comment by summergeorge** [comment]
中国用户解决了这个问题，我的处理方式是：
1. 关闭Tesla串流接口。（理论上关了就好了）
![image](https://user-images.githubusercontent.com/5298923/147761220-50dad00c-a2c2-4e2b-bae3-e0de4ca37a73.png)
2. 保险起见把原来docker yml 中的extra_hosts去掉。（因为中国的ip地址变了，如果网络环境在国外，必须设置host，建议ping 一下最新的服务器地址。看起来tesla中国的ip地址变化挺频繁的，最好能够把服务器部署在国内网络环境中。）
![image](https://user-images.githubusercontent.com/5298923/147761395-1d8d0d49-b0ca-4193-8cc8-949da9cd6abe.png)

看起来已经正常了，明天再开车验证下。
![image](https://user-images.githubusercontent.com/5298923/147761644-d029abe3-0a2a-4c36-a54c-77d05952c7ab.png)

**Comment by summergeorge** [comment]
> 中国用户解决了这个问题，我的处理方式是：
> 
> 1. 关闭Tesla串流接口。（理论上关了就好了）
>    ![image](https://user-images.githubusercontent.com/5298923/147761220-50dad00c-a2c2-4e2b-bae3-e0de4ca37a73.png)
> 2. 保险起见把原来docker yml 中的extra_hosts去掉。（因为中国的ip地址变了，如果网络环境在国外，必须设置host，建议ping 一下最新的服务器地址。看起来tesla中国的ip地址变化挺频繁的，最好能够把服务器部署在国内网络环境中。）
>    ![image](https://user-images.githubusercontent.com/5298923/147761395-1d8d0d49-b0ca-4193-8cc8-949da9cd6abe.png)
> 
> 看起来已经正常了，明天再开车验证下。 ![image](https://user-images.githubusercontent.com/5298923/147761644-d029abe3-0a2a-4c36-a54c-77d05952c7ab.png)

顺便说一下，我之前重启过tesla的车机，当时重启是没有解决这个问题的。从关闭串流接口后，好像记录就正常了。

**Comment by aishlai** [comment]
i found this problem is fixed on 1.26.0-dev, try to use tag on edge

**Comment by aishlai** [comment]
> i tried to update the edge version, but still blank records, one trip separated to dozens black trips.

may be old data can't fix

**Comment by sempliciy** [comment]
After update the edge version, it's work
![微信图片_20211231090816](https://user-images.githubusercontent.com/7747634/147797298-4fa0cfba-8fe2-4a64-874b-841106941bdf.png)

**Comment by wg-cn** [comment]
> > > Any one tried update to edge version(maybe 1.26.0)?
> > 
> > 
> > 如何升级edge版本？
> 
> replace 'teslamate/teslamate:latest' with 'teslamate/teslamate:edge' in compose yml

tks, my teslamate work ok after replace to edge version and reboot the carpc.

**Comment by Rainsho** [comment]
Are there any ways to remove the dirty data? It logged i had driven 70000 times in Jan.2022. I'm a little OCD.

**Comment by jjzxmmx** [comment]
> 有没有办法去除脏数据？它记录了我在 2022 年 1 月驾驶了 70000 次。我有点强迫症。

This is the answer.[https://github.com/adriankumpf/teslamate/issues/1996#issuecomment-927101331](url)

**Comment by vls** [comment]
> I use edge verion,and the log output as this: (I am china user) ![0](https://user-images.githubusercontent.com/6425805/148151191-705c0b49-006e-4a4f-83df-b413d550dd84.png)

same here. Teslamate has been deployed on JP machine. It seems that the Region determine function is not working correctly.  

https://github.com/adriankumpf/teslamate/blob/9c9564ecc75fa697f244b2c763c0c756bf251fd6/lib/tesla_api/auth.ex#L44

Maybe need an environment variable the determine Global/CHINA @adriankumpf

**Comment by adriankumpf** [comment]
> > I use edge verion,and the log output as this: (I am china user) ![0](https://user-images.githubusercontent.com/6425805/148151191-705c0b49-006e-4a4f-83df-b413d550dd84.png)
> 
> same here. I'm china user but my Teslamate has been deployed on JP machine. It seems that the Region determine function is not working correctly.
> 
> https://github.com/adriankumpf/teslamate/blob/9c9564ecc75fa697f244b2c763c0c756bf251fd6/lib/tesla_api/auth.ex#L44
> 
> Maybe need an environment variable the determine Global/CHINA @adriankumpf

The region detection is based on the access token. Can you try to log out and log in again? Did you do any modifications to the *docker-comose.yml* like adding `extra_hosts`?

**Comment by yhq34** [comment]
I have the same issue, I am currently using teslamate:edge, didn't add extra_hosts to the docker-compose.yml. If I log out and I cannot log in.
