### ISSUE TITLE
Add separate "Charge Level" view in Grafana Dashboard?

### ISSUE THREAD

**Issue by spacecosmos** [adriankumpf/teslamate#224]
Is there a way to add the **Charge Level** view on the Dashboard as a separate choice? Or maybe under **Charge Details** perhaps?

![SmartSelect_20191029-003813_Opera](https://user-images.githubusercontent.com/55928670/67726155-398ed600-f9e5-11e9-86af-53f21495de48.jpg)

Currently it's only available under the **Overview** section. But it's locked to the last 24 hours. It would be very useful to see the drop in charge during any given period. (As an alternative to **Vampire Drain**.)

**Comment by tucopup** [comment]
Agree, this would be great.

**Comment by spacecosmos** [comment]
Maybe **@DBemis** can shed some light, since he is the one that created the awesome **Overview** section?

**Comment by dopeghoti** [comment]
you could maybe take the query used in the Degredation dashboard and replace the calculated range with the SoC for SoC over time overall?

**Comment by spacecosmos** [comment]
Anyone here up for the task in creating the **Charge Level** view on the _Dashboard_?

**Comment by ctraber** [comment]
I‘ll try. 
Just a new, separate Dashboard with battery level where you can select the time period. Right?

**Comment by spacecosmos** [comment]
> I‘ll try.
> Just a new, separate Dashboard with battery level where you can select the time period. Right?

Yes. Something like that, would be great.

**Comment by ctraber** [comment]
Here an example:

<img width="1135" alt="Bildschirmfoto 2020-01-16 um 19 39 08" src="https://user-images.githubusercontent.com/24205688/72552823-f9c6e480-3897-11ea-85f1-da916c0f56cf.png">

**Comment by spacecosmos** [comment]
Wow @ctraber! Awesome work! It now needs to be implemented in the next release. :)

PS! If you have any more cool ways to present graphs and other ideas, please create some!

**Comment by adriankumpf** [comment]
I couldn't agree more. More graphs and other cool ideas are always welcome :)

**Comment by ctraber** [comment]
I noticed only now that there are also datapoints in charges and not only in positions. I will also try to add usable_battery_level to charges now. Once I have to charge my car I‘ll test it.

**Comment by ctraber** [comment]
Also did some tests with my "Projected Range" dashboard with other combinations.

**Projected Range - Battery Level**
<img width="755" alt="Bildschirmfoto 2020-01-17 um 14 13 51" src="https://user-images.githubusercontent.com/24205688/72615084-1fa1c700-3934-11ea-80f6-616f004bbcd3.png">

**Projected Range - Outdoor Temp and Projected Range using estimated range instead of rated range.**
<img width="725" alt="Bildschirmfoto 2020-01-17 um 14 15 11" src="https://user-images.githubusercontent.com/24205688/72615133-3f38ef80-3934-11ea-9c19-bbea98e27769.png">

But I'm not really sure if it would be helpful...

**Comment by adriankumpf** [comment]
Since the estimated range depends on the driving style one cannot draw conclusions about degradation from this. Still interesting to see the real-world range though.

**Comment by DBemis** [comment]
> I noticed only now that there are also datapoints in charges and not only in positions. I will also try to add usable_battery_level to charges now. Once I have to charge my car I‘ll test it.

The charge graph on the overview dash is pulling data from both locations if you want a reference point (you could probably copy that query). Sorry - flagged the original request a while ago about splitting it, then completely forgot about it :P Good work on the new one!

**Comment by ctraber** [comment]
Sure, i used the union. But when I added usable_battery_level to the logger, I only did it for positions and not yet for charges😬
