### ISSUE TITLE
Add car "direction" value to mqtt publish

### ISSUE THREAD

**Issue by bradsjm** [adriankumpf/teslamate#225]
Would you be able to add the "heading" value from the API data to the MQTT feed to complement the latitude, longitude and speed values already captured.

**Comment by adriankumpf** [comment]
I haven't played with the streaming API yet which seems to be the only way to get the "heading". There's not much (unofficial) documentation about it but I'll check it out.

**Comment by bradsjm** [comment]
Thanks. It is in there under "heading" with latitude and longitude, I was using custom code to pull it using tesla api but it would be better to grab it from MQTT:

```
   "shift_state": null,
    "speed": null,
    "power": 0,
    "latitude": 40.459728,
    "longitude": -79.923447,
    "heading": 340
```

**Comment by adriankumpf** [comment]
You're right, of course. I overlooked that. If the streaming API is not required to get it, it's really easy to publish it to an MQTT topic.
