### ISSUE TITLE
Inconsistency between states and drives

### ISSUE THREAD

**Issue by krezac** [adriankumpf/teslamate#226]
**Describe the bug**
30 minute drive shown as online on States chart. The drive itself seems to be recorded properly, see screenshot. I think I've seen the same issue before, but when checking later, it was fine (driving status), so consider it unconfirmed. The states gets updated later, maybe?
If you need to check something in the db, let me know.
Thanks

**Screenshots**
<img width="1546" alt="tm_states" src="https://user-images.githubusercontent.com/16595657/67747398-e474b380-fa28-11e9-9d49-b9150ccb9fab.png">

<img width="1546" alt="tm_drives" src="https://user-images.githubusercontent.com/16595657/67747414-ec345800-fa28-11e9-9139-1919566a1306.png">

<img width="1546" alt="tm_drive" src="https://user-images.githubusercontent.com/16595657/67747424-f5bdc000-fa28-11e9-85ff-53925122df9d.png">

**Operating environment (please complete the following information):**
 - Version teslamate: 1.11.1 (updated to 1.12 today)
 - Version car: 2019.32.11.1

**Comment by adriankumpf** [comment]
That's tough to debug without the actual data. Could you export your data for that day from the following db tables?

* `states`
* `drives` (only `start_date` and `end_date` are required)
* `charging_processes` (only `start_date` and `end_date` are required)

Thanks!

**Comment by krezac** [comment]
Here are the exports for that day:
[tm_inconsistency.zip](https://github.com/adriankumpf/teslamate/files/3802246/tm_inconsistency.zip)

**Comment by adriankumpf** [comment]
Thank you.

> EDIT: The difference I see for the "wrong" period is that drive starts at the same time as the online. For the others the time is different.

Good catch! Changing the sort order to ascending helped with that.
