### ISSUE TITLE
Gross Consumption seems high?

### ISSUE THREAD

**Issue by ADebelius** [adriankumpf/teslamate#228]
How is the Consumption (gross) tab calculated? Seems awfully high.

Charging via Tesla Wall Connector @ 240V/48A, displays 1 phase. Not sure if that is correct or associated with the high consumption (gross) value. Thanks

![Annotation 2019-10-29 215940](https://user-images.githubusercontent.com/843407/67825532-964ac900-fa97-11e9-80ba-6bebe1501199.png)

**Comment by adriankumpf** [comment]
The consumption (gross) is the calculated consumption (per 100 mi/km) since the last charge. 

It's calculated as follows:

```
range_loss = (Range after last charge) - (Range before this charge)
energy = range_loss * (efficiency factor of the vehicle) 

energy / distance_driven * 100
```
