### ISSUE TITLE
Issues trying to add home geofence

### ISSUE THREAD

**Issue by muffstic** [adriankumpf/teslamate#2295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

***This can be deleted. Issue was fixed by running delete * from geofences where id is not null then by creating a home geofence again.***

All locations disappeared after 9-29 so I updated Teslamate to current version. Somehow I delected my home goefence and all home locations are showin an address 2 number different from mine which doesn't exist and shows up as my backyard. When I try to add my home geolocation it works as long as it's not too clost to my backyard.  If I expand the geolocation to get the home data to show up correctly I get the popu in the screenshot that just disappears after clicking on Add costs retroactively without adding the costs. 

Logs were too long the first time so I copied the bottom portion only. 

```


### Screenshots

![image](https://user-images.githubusercontent.com/42457775/148990142-c43d1bb9-d0f6-4269-b07e-d3ef044cb277.png)


### Additional data

_No response_

### Type of installation

Docker

### Version

1.25.0

**Comment by muffstic** [comment]
I was able to inch the geofence slightly closer to where I charge and capture some of the data, but if I move it any closer it still times out.

**Comment by adriankumpf** [comment]
> This can be deleted. Issue was fixed by running delete * from geofences where id is not null then by creating a home geofence again.
