### ISSUE TITLE
Cannot start v1.25.1 teslamate container: `GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by kb122** [adriankumpf/teslamate#2300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Updated to the latest teslamate image (v1.25.1) in Portainer, teslamate container is failing to start.  The rest of the containers within the stack have no issues.

### Relevant log output

```shell
/opt/app/erts-12.2/bin/beam.smp: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/app/erts-12.2/bin/beam.smp)
```

### Type of installation

Docker

### Version

v1.25.1

**Comment by ampjunkie** [comment]
I have the same issue.  Portainer says the container is started, but the logs say:

/opt/app/erts-12.2/bin/beam.smp: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/app/erts-12.2/bin/beam.smp)

Due to this, the web interface does not come up at port 4000.

**Comment by dkny1123a** [comment]
The same thing happened.
waiting for postgres at database:5432
/opt/app/erts-12.2/bin/beam.smp: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /opt/app/erts-12.2/bin/beam.smp)

**Comment by parkr** [comment]
Looking at the Dockerfile, is it possible that the `builder` and the `app` images have different versions of glibc? @adriankumpf

**Comment by parkr** [comment]
For now, downgrade to `1.25` (just for the teslamate container if needed).

**Comment by xnaas** [comment]
Confirmed downgrading only the TeslaMate container to `:1.25.0` seems to work fine for the time being.

**Comment by ampjunkie** [comment]
Kind of a newbie here on docker commands. What commands do I run to downgrade only the Teslamate container?

**Comment by JPHoesch** [comment]
I'm using Docker on a Synology, but this might translate. I exported the container settings for docker_teslamate_1 (not the entire container, just settings) and then deleted the container. This should create a json file. Edit that to replace teslamate/teslamate:latest with teslamate/teslamate:1.25.0. Then import and select the json file.

**Comment by drive-c** [comment]
Downgrade to 1.25.0 for just the TeslaMate container looks good. Works well without rolling back Grafana or other containers.

**Comment by dkny1123a** [comment]
Rolled back to 1.25.0

**Comment by bslime85** [comment]
I've same issue.
teslamate container rolled back to 1.25.0, now it's working.

**Comment by CrazyMouse** [comment]
me too Linux ubuntu18 4.15.0-167-generic

**Comment by Hruuttila** [comment]
Same issue here.

**Comment by spacecosmos** [comment]
I'm also seeing this. But I actually think it happened _before_ the upgrade itself. Because I tried accessing the Dashboard and couldn't log in at all. 

```
teslamate_1  | /opt/app/erts-12.2/bin/beam.smp: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/app/erts-12.2/bin/beam.smp)
proxy_1      | time="2022-01-12T06:06:44Z" level=error msg="unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-XxXxXxXxXxXx
database_1   | 2022-01-12 06:06:57.233 UTC [39] LOG:  incomplete startup packet
root_teslamate_1 exited with code 1 
```
For those of you who downgraded just the TeslaMate container, what command did you use? I'm guessing you first have to shut down with `docker-compose down`, but then what?

**Comment by bslime85** [comment]
> I'm also seeing this. But I actually think it happened _before_ the upgrade itself. Because I tried accessing the Dashboard and couldn't log in at all.
> 
> ```
> teslamate_1  | /opt/app/erts-12.2/bin/beam.smp: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/app/erts-12.2/bin/beam.smp)
> proxy_1      | time="2022-01-12T06:06:44Z" level=error msg="unable to find the IP address for the container \"/root_teslamate_1\": the server is ignored" providerName=docker container=teslamate-root-XxXxXxXxXxXx
> database_1   | 2022-01-12 06:06:57.233 UTC [39] LOG:  incomplete startup packet
> root_teslamate_1 exited with code 1 
> ```
> 
> For those of you who downgraded just the TeslaMate container, what command did you use? I'm guessing you first have to shut down with `docker-compose down`, but then what?

Edit that to replace in 'docker-compose.yml'

    image: teslamate/teslamate:**latest** -> image: teslamate/teslamate:**1.25.0**

and execute update command.

$ sudo docker-compose pull
$ sudo docker-compose up -d

**Comment by brianmay** [comment]
The most likely reason why this is broken is because this line is wrong:

https://github.com/adriankumpf/teslamate/blob/master/Dockerfile#L40

The OS used needs to match that of the `elixir:1.13` environment from this line:

https://github.com/adriankumpf/teslamate/blob/master/Dockerfile#L1

I am guessing that the recent push to the elixir repo changed the OS spec required. But I have never been really sure where you get this information from.

(I often have this same problem with my own personal Elixir projects).

**Comment by spacecosmos** [comment]
Guide for those who doesn't know how to downgrade:

1. Log in to your Linux-box
2. Shut down TeslaMate with the command: `docker-compose down`
2. Edit the file _docker-compose.yml_ with the command: `nano docker-compose.yml`
3. Replace the string that states: **_image: teslamate/teslamate:latest_** with **_image: teslamate/teslamate:1.25.0_**
4. Before: 
<img width="277" alt="change-from" src="https://user-images.githubusercontent.com/55928670/149081134-9f42337b-6a5f-4df2-9cf6-1265275918f5.png">

5. After:
<img width="276" alt="change-to" src="https://user-images.githubusercontent.com/55928670/149081174-26da6e9d-265a-436d-9c47-4ce2785c8f62.png">

6. Save the file by pressing Ctrl+X and pressing Y.
<img width="456" alt="save" src="https://user-images.githubusercontent.com/55928670/149081246-12a5174b-5228-4b22-9181-dea554fee19c.png">

7. Confirm the filename by pressing ENTER
<img width="283" alt="overwrite" src="https://user-images.githubusercontent.com/55928670/149081261-f770086a-97a1-4d27-b540-e2f15fa34bbc.png">

8. To download the previous 1.25.0 version, use this command: `docker-compose pull`
<img width="268" alt="pull" src="https://user-images.githubusercontent.com/55928670/149081743-963bb03b-193d-4728-9730-0b2978176f72.png">

9. When finished, you can start TeslaMate with the command: `docker-compose up -d`

**That's it!**

**Comment by adriankumpf** [comment]
[v1.25.2](https://github.com/adriankumpf/teslamate/releases/tag/v1.25.2) is out with a fix this error.

**Comment by sven3** [comment]
Wow, that was fast. Many thanks!

**Comment by drees** [comment]
I get error in the logs repeatedly after updating to v1.25.2:

```
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
```

**Comment by adriankumpf** [comment]
> I get error in the logs repeatedly after updating to v1.25.2:
> 
> ```
> teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
> teslamate_1  | Aborted (core dumped)
> ```

This could be caused by an outdated Docker version. The recent  20.10 does not seem to have this issue. 

By the way, v1.25.1 only makes changes to the Grafana image. So if you are only interested in getting those, you can temporarily use the `teslamate/grafana:latest` tag for Grafana and pin TeslaMate to `teslamate/teslamate:1.25.0`

**Comment by dkny1123a** [comment]
> > I get error in the logs repeatedly after updating to v1.25.2:
> > ```
> > teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
> > teslamate_1  | Aborted (core dumped)
> > ```
> 
> This could be caused by an outdated Docker version. The recent 20.10 does not seem to have this issue.
> 
> By the way, v1.25.1 only makes changes to the Grafana image. So if you are only interested in getting those, you can temporarily use the `teslamate/grafana:latest` tag for Grafana and pin TeslaMate to `teslamate/teslamate:1.25.0`



> I get error in the logs repeatedly after updating to v1.25.2:
> 
> ```
> teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
> teslamate_1  | Aborted (core dumped)
> ```

This is same as using edge edition.

**Comment by rbswift** [comment]
```
Aborted (core dumped)
clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
```

here too

**Comment by drees** [comment]
> This could be caused by an outdated Docker version. The recent 20.10 does not seem to have this issue.

Running on a RaspberryPi 4 running Raspbian Buster:
```
$ docker --version
Docker version 20.10.12, build e91ed57
$ docker-compose --version
docker-compose version 1.29.2, build unknown
```

Have rolled back to 1.25.0 for the time being...

**Comment by rbswift** [comment]
```
pi@pi4:~/teslamate $ docker -v
Docker version 20.10.12, build e91ed57
```

**Comment by dranreb38** [comment]
> > > I get error in the logs repeatedly after updating to v1.25.2:
> > > ```
> > > teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
> > > teslamate_1  | Aborted (core dumped)
> > > ```
> > 
> > 
> > This could be caused by an outdated Docker version. The recent 20.10 does not seem to have this issue.
> > By the way, v1.25.1 only makes changes to the Grafana image. So if you are only interested in getting those, you can temporarily use the `teslamate/grafana:latest` tag for Grafana and pin TeslaMate to `teslamate/teslamate:1.25.0`
> 
> > I get error in the logs repeatedly after updating to v1.25.2:
> > ```
> > teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
> > teslamate_1  | Aborted (core dumped)
> > ```
> 
> This is same as using edge edition.

Idem !

**Comment by adriankumpf** [comment]
20.10.12 works fine on a Raspberry Pi 3 here.

```
> cat /sys/firmware/devicetree/base/model
Raspberry Pi 3 Model B Rev 1.2
> docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:28 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:45 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by dranreb38** [comment]
`cat /sys/firmware/devicetree/base/model
Raspberry Pi 4 Model B Rev 1.1root@teslamate:~/Docker/TeslaMate

docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:14 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:32 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`

**Comment by kb122** [comment]
> [v1.25.2](https://github.com/adriankumpf/teslamate/releases/tag/v1.25.2) is out with a fix for this error.

Thanks!  I updated to 1.25.2 and everything looks good so far.

**Comment by thunder2k** [comment]
> > [v1.25.2](https://github.com/adriankumpf/teslamate/releases/tag/v1.25.2) is out with a fix for this error.
> 
> Thanks! I updated to 1.25.2 and everything looks good so far.

Are you on Raspberry Pi 4?

**Comment by leewillis77** [comment]
Confirmed that 1.25.2 fails for me here:

```
$ docker --version
Docker version 20.10.12, build e91ed57
$ docker-compose --version
docker-compose version 1.26.2, build unknown
$ cat /sys/firmware/devicetree/base/model
Raspberry Pi 4 Model B Rev 1.2
```

As others have reported, the errors are clock related:
```
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
```

**Comment by leewillis77** [comment]
The issue appears to be an incompatibility with the version of `libseccomp2` installed on Raspbian GNU/Linux 10 (buster). 

My guess is that people who it's working for are on Raspberry Pi OS 11 (Based on Debian Bullseye), and those with problems are on 10. 

For me, grabbing the backports version of `libseccomp2` from `https://packages.debian.org/buster-backports/armhf/libseccomp2/download` and installing that got 1.25.2 up and running. Other people may be able to do something similar.

**Comment by cwanja** [comment]
Unhappy to report that my TeslaMate will not start after updating.

It is actually hosing my entire Pi. CPU and memory is getting hosed. Trying to pull some of the versions, but typing takes three to five minutes each time.

**Comment by ampjunkie** [comment]
Thanks everybody for the instructions on downgrading, and the fast response for the fix! I managed to downgrade with no issues, and just updated with the latest, also no issues running latest HassOS in latest VB on a Linux machine.

**Comment by kb122** [comment]
> > > [v1.25.2](https://github.com/adriankumpf/teslamate/releases/tag/v1.25.2) is out with a fix for this error.
> > 
> > 
> > Thanks! I updated to 1.25.2 and everything looks good so far.
> 
> Are you on Raspberry Pi 4?

No, I'm running it on an Intel-based Linux server, so different architecture.  My docker version is 20.10.10, build b485636.

**Comment by cwanja** [comment]
Not to compound or hijack the thread, but here is the error that my logs are throwing:

```
teslamate_1  | =ERROR REPORT==== 12-Jan-2022::17:12:06.303755 ===
teslamate_1  | erts_poll_wait() failed: eperm (1)
teslamate_1  | 
teslamate_1  | 
teslamate_1  | =ERROR REPORT==== 12-Jan-2022::17:12:06.303778 ===
teslamate_1  | erts_poll_wait() failed: eperm (1)
teslamate_1  | 
teslamate_1  | 
teslamate_1  | =ERROR REPORT==== 12-Jan-2022::17:12:06.303792 ===
teslamate_1  | erts_poll_wait() failed: eperm (1)
teslamate_1  | 
teslamate_1  | 
teslamate_1  | =ERROR REPORT==== 12-Jan-2022::17:12:06.303805 ===
teslamate_1  | erts_poll_wait() failed: eperm (1)
teslamate_1  | 
teslamate_1  | 
teslamate_1  | =ERROR REPORT==== 12-Jan-2022::17:12:06.303819 ===
teslamate_1  | erts_poll_wait() failed: eperm (1)
```

Have decided to rollback to 1.25 for the time being.

**Comment by petebocken** [comment]
> Unhappy to report that my TeslaMate will not start after updating.
> 
> It is actually hosing my entire Pi. CPU and memory is getting hosed. Trying to pull some of the versions, but typing takes three to five minutes each time.
> 
> ```
> pi@teslapi:~/Documents/teslamate $ docker-compose --version
> docker-compose version 1.29.2, build unknown
> pi@teslapi:~/Documents/teslamate $ docker --version
> Docker version 20.10.6, build 370c289
> pi@teslapi:~/Documents/teslamate $ cat /sys/firmware/devicetree/base/model 
> Raspberry Pi 3 Model B Plus Rev 1.3
> ```

similar setup here and same issue. I cannot load teslamate at port 4000.  Grafana on 3000 loads to a login window.

pi@teslamate:~ $ docker-compose --version
docker-compose version 1.29.2, build unknown
pi@teslamate:~ $ docker --version
Docker version 20.10.12, build e91ed57
pi@teslamate:~ $ cat /sys/firmware/devicetree/base/model
Raspberry Pi 3 Model B Plus Rev 1.3
