### ISSUE TITLE
Build fails with compilation error in lib/teslamate_web/cldr.ex

### ISSUE THREAD

**Issue by rtega** [adriankumpf/teslamate#2301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

mix fails on compiling lib/teslamate_web/cldr.ex.

### Expected Behavior

Should just compile.

### Steps To Reproduce

I tried removing the _build directory and doing rm -rf priv/cldr/locales/* per issue #761 but it still fails. Would upgrading npm do something? It is at version 6.14.15.

### Relevant log output

```shell
== Compilation error in file lib/teslamate_web/cldr.ex ==
** (FunctionClauseError) no function clause matching in IO.read/2    
    
    The following arguments were given to IO.read/2:
    
        # 1
        #PID<0.6635.0>
    
        # 2
        :eof
    
    Attempted function clauses (showing 3 out of 3):
    
        def read(device, :all)
        def read(device, :line)
        def read(device, count) when is_integer(count) and count >= 0
    
    (elixir 1.13.0-dev) lib/io.ex:150: IO.read/2
    (elixir 1.13.0-dev) lib/file.ex:1421: File.open/3
    (ex_cldr 2.24.1) lib/cldr/locale/loader.ex:128: Cldr.Locale.Loader.read_locale_file!/1
    (ex_cldr 2.24.1) lib/cldr/locale/loader.ex:101: Cldr.Locale.Loader.do_get_locale/3
    (ex_cldr 2.24.1) lib/cldr/locale/cache.ex:110: Cldr.Locale.Cache.do_get_locale/2
    (ex_cldr 2.24.1) lib/cldr/locale/loader.ex:49: anonymous fn/2 in Cldr.Locale.Loader.known_rbnf_locale_names/1
    (elixir 1.13.0-dev) lib/enum.ex:3796: Enum.filter_list/2
    (stdlib 3.10) erl_eval.erl:680: :erl_eval.do_apply/6
zsh: exit 1     MIX_ENV=prod mix do phx.digest, release --overwrite
```

### Type of installation

Manual

### Version

v1.25.2

**Comment by rtega** [comment]
And also did rm -rf priv/cldr/* per issue #2154

**Comment by brianmay** [comment]
What version of Elixir are you using?

Suspect this may not matter, but can't hurt to check.

**Comment by rtega** [comment]
Elixir 1.13.0-dev (7eab0cb) (compiled with Erlang/OTP 22)

**Comment by adriankumpf** [comment]
> Elixir 1.13.0-dev (7eab0cb) (compiled with Erlang/OTP 22)

Can you givve v1.13 stable and a more recent OTP version a try?

**Comment by rtega** [comment]
Didn't notice I was on a dev-version of elixir. Using v1.13 stable solved it. Thanks a lot @adriankumpf !
