### ISSUE TITLE
map does not show the drive route anymore, although location info exists

### ISSUE THREAD

**Issue by markusdd** [adriankumpf/teslamate#2305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The map is not showing the route anymore, although start/end info is shown in drives table.
Plugins updated to latest, Teslamate also updated to 1.25.2 .

![grafik](https://user-images.githubusercontent.com/25175069/149235033-674a083f-fd78-4c71-ab6a-cf4ce3861e73.png)

### Expected Behavior

Route is shown as it has worked in the past

### Steps To Reproduce

Pick a drive from the Drives list and click on it to be taken to the drive details.

### Relevant log output

```shell
where do I get these logs (if relevant) in a non-docker installation?
```

### Additional data
also applies to the 'Visited' map, it just shows the world map without any entries.

### Type of installation

Manual

### Version

v1.25.2

**Comment by coreGreenberet** [comment]
I've found a workaround for that issue a few days ago (i forgot where, so sorry for missing credits)

You can change the map panel to get the longitude and latitude over different queries instead of one.
![grafik](https://user-images.githubusercontent.com/3853374/149332482-b75d93d9-25fb-4958-ab0d-c11c91eabb7e.png)

A: 
````SQL
SELECT "latitude" as value, $__time(date) FROM "positions" WHERE $__timeFilter(date) ORDER BY date ASC
```

B: 
````SQL
SELECT "longitude" as value, $__time(date) FROM "positions" WHERE $__timeFilter(date) ORDER BY date ASC
```

**Comment by markusdd** [comment]
ok, that indeed worked around the problem for the drives, the visited map is still broken

**Comment by markusdd** [comment]
ok cool, thanks so much!

Should this be delievered as a patch or is it known why this is necessary?

**Comment by adriankumpf** [comment]
Which version of Grafana are you using? Currently we only support v7.

**Comment by markusdd** [comment]
ah! that might be the reason then.

My instance is running on 8.3.3 .

Although besides that map thing everything else looks pretty good. So everything else seems to be in order for me at least as far as I can tell. So the remaining graphs are displaying fine for me, it does not look as bad as in that ticket.

So with the fixes displayed above Grafana 8 seems to be fine for me.

**Comment by markusdd** [comment]
Hi @adriankumpf , thanks for the quick fix!

I see your commit covers the charge and drive details dashboards. Does this then also apply to the 'visited' dashboard?
Because this one was broken as well.
