### ISSUE TITLE
Difference between suspended state and sleep?

### ISSUE THREAD

**Issue by chilman408** [adriankumpf/teslamate#231]
Had been using this for the last couple days.  The software is very well implemented with enough sophistication.  So thanks so much!

Just a question about the difference between suspended state and sleep state.  My Model X seem to never go to sleep (as reported by Teslamate), it is always in suspended state when idle.  But there is little to no vampire drain.  It is showing less drain than my Model 3 which Teslamate report as asleep...

**Comment by adriankumpf** [comment]
Thanks! [This page](https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md) explains what's going on if teslamate reports the suspended/"falling asleep" state. And [this section](https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md#vehicle-side-configuration) lists some parameters which are tunable on some vehicles. I hope this will help.

**Comment by chilman408** [comment]
> Thanks! [This page](https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md) explains what's going on if teslamate reports the suspended/"falling asleep" state. And [this section](https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md#vehicle-side-configuration) lists some parameters which are tunable on some vehicles. I hope this will help.

Thank you.  In reading the documentation, I'm guessing that the "Time to try Sleeping" of 21 minutes is NOT working for my Model X but is for my Model 3?  I'll try experimenting.  But let me know if this understanding is wrong...

If this is true, then I think a good feature request should be to have individual time to sleep for each car...

**Comment by adriankumpf** [comment]
> I'm guessing that the "Time to try Sleeping" of 21 minutes is NOT working for my Model X but is for my Model 3? I'll try experimenting. But let me know if this understanding is wrong...

Yes, that's right. Either the time is too short or something else prevents it from falling asleep. 

However, we saw issues with some vehicles before and I'm not very familiar with the first hardware generations. So I'm not sure if there are (older) vehicles that will simply not report the "asleep" state or if those cases just require to tune the vehicle settings (like 'Energy savings').

> If this is true, then I think a good feature request should be to have individual time to sleep for each car...

Yes, that feature is definitely coming.
