### ISSUE TITLE
docker-compose now issues an illegal instruction upon starting.. on Pi zero

### ISSUE THREAD

**Issue by shavermcspud** [adriankumpf/teslamate#2312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

docker-compose up -d gives an illegal instruction and terminates. 

### Relevant log output

```shell
pi@raspberrypi:~ $ docker-compose
Illegal instruction
pi@raspberrypi:~ $
```

### Type of installation

Docker

### Version

v1.24

**Comment by seeethi** [comment]
Hi, I have the same problem. How did you solve it?

**Comment by DrMichael** [comment]
Try `docker compose -d`
