### ISSUE TITLE
TMY - Efficiency is not correct

### ISSUE THREAD

**Issue by CAEck** [adriankumpf/teslamate#2316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,
After having searched in the issues, i report my problem.

In the tables CARS, value(Efficiency) = '0. 148' where my car : value(model)='Y'
But the Rated Consumption of the model Y is 169 Wh/km.

Can you fix it ?

Is it possible to update the value?
If yes, will this update be taken into account by Grafana?

Thx for all !!!

Cyril

### Relevant log output

```shell
teslamate=# select model, efficiency from cars;
 model | efficiency 
-------+------------
 Y     |      0.148
(1 row)
```

### Type of installation

Docker

### Version

v1.25.2

**Comment by adriankumpf** [comment]
Each charging session will a recalculation of the efficiency, which is applied retroactively to all data. In other words, the longer you use TeslaMate, the more accurate the efficiency value will become.
