### ISSUE TITLE
bridge between teslamate and Scan m﻿y Tesla

### ISSUE THREAD

**Issue by the1mrk** [adriankumpf/teslamate#232]
Maybe it's possible to merge datas from scan my tesla's csv in Teslamate
https://sites.google.com/view/scanmytesla/menus?authuser=0

Manually or automatically, it should be possible as log can be uploaded to Gdrive:
https://sites.google.com/view/scanmytesla/reccommended-software?authuser=0

Thanks for the great work

**Comment by adriankumpf** [comment]
I'm not using the Scan my Tesla, so I can't (and don't want to) support/maintain an integration. I am open to suggestions though. If anybody wants to work on that we'll find a way to integrate it into teslamate.

**Comment by ic9888** [comment]
Perhaps a collaboration with Teslalogger to use their scanmytesla implemetation?

**Comment by ngardiner** [comment]
What would be the benefit? Is there a feature Scan my Tesla has that TeslaMate doesn't?

**Comment by ic9888** [comment]
It takes all of the obd port data via the app and uploads it so you can overlay all of that data on the API sourced data. I can show you on my set up sometime if you would like.

**Comment by ngardiner** [comment]
Interesting stuff, although given it's collected via bluetooth and not streamed over the Internet, it seems more like a parallel set of data you would log to csv and import later. Personally I'd be importing it into a separate DB and then setting up grafana to overlay the data over TeslaMate.

**Comment by pkuehnel** [comment]
Is there a way to extend the TeslaMate grafana image? I am willing to create an app (docker container as well) which imports CSV files from Scan My Tesla to a new database. But I am not sure how to add these data to the existing grafana image 🤔 @adriankumpf can you help me in this point?

**Comment by ngardiner** [comment]
> Is there a way to extend the TeslaMate grafana image? I am willing to create an app (docker container as well) which imports CSV files from Scan My Tesla to a new database. But I am not sure how to add these data to the existing grafana image.

That's really the basis of how Docker works, you later images on top of each other. It's as simple as creating your own Dockerfile, using the TeslaMate image as the base image and then adding your own customisations on top.

**Comment by pkuehnel** [comment]
Yes but all the Dashboards are based on one json file. To add additional Data to the Dashboards I would have to edit existing files.

**Comment by panaut0lordv** [comment]
@adriankumpf do you think you'd start using it if you'd have app+adapter+OBD dongle or you're just not interested in diving that deep into technical stats of the car/don't like the hassle of phone requirement?

**Comment by pkuehnel** [comment]
As I used SMT a few weeks now, I won't make that integration to TeslaMate. My plan was to let a phone permanently log to a file and upload that file to my server at home but the SMT app is way to buggy. Very often it can't establish a Bluetooth connection, so no data is logged. As I am only interested in things that run in background and I do not take care of it after initial set up, I won't do that integration.

**Comment by panaut0lordv** [comment]
Fair point, if it's truly like you describe I'd avoid that as well. My concern is if it is possible that the issues you are encountering are in fact due to OBD adapter you are using? Do you mind mentioning what device is that?

**Comment by pkuehnel** [comment]
It's an ELM 327 adapter but I am pretty sure, that the app is the issue. Reason: Every time this issue occurs, disabling and reenabling Bluetooth does not help, flight mode does not help, unplug and plugin obd adapter does not help, only killing the app helps. After killing the app Bluetooth is connected within a few seconds, every single time so far.

**Comment by faekz0r** [comment]
> It's an ELM 327 adapter but I am pretty sure, that the app is the issue. Reason: Every time this issue occurs, disabling and reenabling Bluetooth does not help, flight mode does not help, unplug and plugin obd adapter does not help, only killing the app helps. After killing the app Bluetooth is connected within a few seconds, every single time so far.

I would not blame SMT still. There are countless users who use it without any of such issues. Try it with another phone or a proper OBD adapter (obdlink for example).

I would very much be interested in an integration with scan my tesla with TeslaMate. It would give us a lot more data for statistics (battery temperature for example).
