### ISSUE TITLE
Upgrade to 1.25.2 from 1.25.0 kills grafana - new default login will not accept the default grafana user / password.

### ISSUE THREAD

**Issue by sparkstack1** [adriankumpf/teslamate#2329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Working instance of teslamate, grafana, mosquito running on Synology NAS.

Full backup taken via docker-compose exec -T database pg_dump -U teslamate teslamate >
Updated to 1.25.2 by running docker-compose pull
Start instance by running docker-compose up -d

Upon attempting to access any dashboard be greeted with a new login prompt for grafana.

Use the default admin / admin credentials.  Find that the credentials are invalid.

### Expected Behavior

Access any dashboard and be greeted with a new login prompt for grafana.

Use the default admin / admin credentials.  Be prompted to change the password.
Change the password.
Access the dashboards.

### Steps To Reproduce

1: Have working instance of teslamate, grafana, mosquito running on Synology NAS.
2: Update to 1.25.2 by running docker-compose pull

### Relevant log output

```shell
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | 2022-01-16 04:36:04.886 [info] Migrations already up
teslamate_1  | 2022-01-16 04:36:06.740 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2022-01-16 04:36:06.740 [info] Version: 1.25.2
teslamate_1  | 2022-01-16 04:36:07.057 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (279.429 ms)
teslamate_1  | 2022-01-16 04:36:07.057 [info] Refreshed api tokens
teslamate_1  | 2022-01-16 04:36:07.211 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-01-16 04:36:07.214 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2022-01-16 04:36:07.215 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2022-01-16 04:36:07.916 [info] Starting logger for 'Old Red'
teslamate_1  | 2022-01-16 04:36:07.927 [info] MQTT connection has been established
teslamate_1  | 2022-01-16 04:36:08.418 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-16 04:36:08.450 car_id=1 [info] Connecting ...
teslamate_1  | 2022-01-16 04:36:09.006 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (553.145 ms)
teslamate_1  | 2022-01-16 04:36:09.047 car_id=1 [info] Charging / SOC: 67% / Home
teslamate_1  | 2022-01-16 04:36:09.047 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-01-16 04:37:38.538 [info] GET /
teslamate_1  | 2022-01-16 04:37:38.556 [info] Sent 200 in 17ms
teslamate_1  | 2022-01-16 04:38:59.292 [info] GET /settings
teslamate_1  | 2022-01-16 04:38:59.302 [info] Sent 200 in 10ms
teslamate_1  | 2022-01-16 04:49:02.949 [info] GET /
teslamate_1  | 2022-01-16 04:49:02.954 [info] Sent 200 in 4ms
teslamate_1  | 2022-01-16 04:49:08.317 [info] OPTIONS /
teslamate_1  | 2022-01-16 04:49:08.317 [info] Sent 404 in 193µs
teslamate_1  | 2022-01-16 04:49:10.869 [info] GET /
teslamate_1  | 2022-01-16 04:49:10.875 [info] Sent 200 in 5ms
teslamate_1  | 2022-01-16 04:49:38.348 [info] GET /nice%20ports%2C/Tri%6Eity.txt%2ebak
teslamate_1  | 2022-01-16 04:49:38.348 [info] Sent 404 in 217µs
teslamate_1  | 2022-01-16 04:50:24.319 [info] GET /
teslamate_1  | 2022-01-16 04:50:24.324 [info] Sent 200 in 4ms
teslamate_1  | 2022-01-16 04:50:33.356 [info] GET /settings
teslamate_1  | 2022-01-16 04:50:33.364 [info] Sent 200 in 8ms
```

### Screenshots

<img width="1045" alt="Screen Shot 2022-01-15 at 10 51 11 PM" src="https://user-images.githubusercontent.com/97652274/149647923-83fa5b98-4f15-407e-8522-8c839192128a.png">

### Type of installation

Docker

### Version

1.25.2

**Comment by refrain** [comment]
I think the default credentials are actually admin / teslamate

**Comment by BriCo84** [comment]
I am having the same problem after updating yesterday. Now all my dashboards want a login

**Comment by sparkstack1** [comment]
I resolved my issue by adding the following to the Grafana section of docker-compose.yml

> GF_AUTH_ANONYMOUS_ENABLED=true

However, i am not hosting this publicly so i am OK with allowing anonymous access.

Example:

grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=[database user]
      - DATABASE_PASS=[database pass]
      - DATABASE_NAME=[database name]
      - DATABASE_HOST=[database host]
      - GF_AUTH_ANONYMOUS_ENABLED=true



In effect i followed the second bullet point of the release notes - but according to point one i should not have needed to....

> ### v1.25.1
> Disable anonymous logins to Grafana by default (when using the teslamate/grafana Docker image)
>
> - The first time you visit Grafana, you will be asked to log in. Use the default user admin with the password admin. After successful login, you will be prompted to change the password.
>
> - To allow anonymous logins set the environment variable of the Grafana image GF_AUTH_ANONYMOUS_ENABLED to true (use only if your Grafana instance is not exposed to the internet!)

**Comment by cwanja** [comment]
Tried resetting the password via the CLI?

https://sleeplessbeastie.eu/2019/12/11/how-to-reset-admin-password-in-grafana-container/

**Comment by sparkstack1** [comment]
I have not. In case unclear, I never set a password and the update is not respecting the documentation.  Hence the issue being reported.

**Comment by sparkstack1** [comment]
> I think the default credentials are actually admin / teslamate

Documentation says admin with the password admin

**Comment by cwanja** [comment]
I can confirm admin / admin works. Just tried. 

>

**Comment by henryhm0** [comment]
admin/admin worked with me and changed password.. thank you for all the hard work.

**Comment by Marcoqwerty78** [comment]
Im still stuck, any password combination works, all updated: Docker (im using windows version) and Teslamate

Car its correctly viewed by Teslamade and and connected.

**Comment by adriankumpf** [comment]
The default password is definitely `admin` if you are using the image and have not set a different password in the past. If a login is not possible, you can reset the password as suggested by @cwanja in https://github.com/adriankumpf/teslamate/issues/2329#issuecomment-1014096467.
