### ISSUE TITLE
After the newest teslamate update, the vehicle azimuth is no showed, whereas it was before.

### ISSUE THREAD

**Issue by woyteck1** [adriankumpf/teslamate#2341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After the newest teslamate update, the vehicle azimuth is not showed on the home screen, whereas it was before.
Before, the vehicle position was shown using an arrow, so you could determine which way the front is pointing.
We know that Tesla API provides it as it's visible on the app, and it was in the v1.25.0, but now, in v1.25.2 it's just a dot :(

### Relevant log output

```shell
no relevant output, I think
```

### Type of installation

Docker

### Version

v1.25.2

**Comment by adriankumpf** [comment]
Can you post a screenshot? I don't quite understand what you mean. If your car is not online after a restart of TeslaMate only a blue dot is displayed instead of an arrow. Once the car is online, the direction is known and as a result an arrow can be displayed.

**Comment by woyteck1** [comment]
Hah, you're right! Wasn't aware of this. Closing the issue myself.
