### ISSUE TITLE
Add Grafana link on TeslaMate Dashboard

### ISSUE THREAD

**Issue by spacecosmos** [adriankumpf/teslamate#235]
It would be great to be able to access **Grafana** from the TeslaMate Dashboard _directly_. Is there a way to add the URL on the **Settings** page for instance and display the link at the top on the front page? 

**Define the Grafana URL:**

![SmartSelect_20191104-062043_Opera-01](https://user-images.githubusercontent.com/55928670/68101414-d366ef00-fecd-11e9-8a20-a04ca2dab4f8.jpeg)

**Example link to Grafana on the front page:**

![SmartSelect_20191104-062202_Opera-01](https://user-images.githubusercontent.com/55928670/68101438-e679bf00-fecd-11e9-9712-3fe33c3c4e93.jpeg)

**Comment by adriankumpf** [comment]
I like 👍
