### ISSUE TITLE
Dark mode on TeslaMate Dashboard

### ISSUE THREAD

**Issue by spacecosmos** [adriankumpf/teslamate#236]
The title kind of says it all. Any way to implement it? :)

I think it would look good with Grafana already being in **dark mode** as well. (Just a thought and not a very important feature of course.)

**Comment by adriankumpf** [comment]
Yeah, a dark mode would be awesome! Shouldn't be that difficult to implement. I'll see what I can do.

**Comment by tobiasehlert** [comment]
This should maybe be not too hard to implement with the [CSS media feature prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by Niek** [comment]
Fixed in https://github.com/adriankumpf/teslamate/pull/461

**Comment by roadrash2108** [comment]
PR #461 never got merged, so this issue is still open. Is this issue still worked on?
