### ISSUE TITLE
Merging drives/charges

### ISSUE THREAD

**Issue by krezac** [adriankumpf/teslamate#237]
Hi,
this is by no means critical thing ;)

It would be nice to be able to merge "artifficialy splitted" drives ( i.e. when I stop for coffee/pee/pick up someone). 
The same for charges (updating teslamate while car is charging splits the charge into two).
If I expand this idea, another level could be having entity "trip" with multiple drives and charges.
All of above either manually or "automatically" (end date and start date differs by less than 5 minutes or so).
Thanks for considering. Maybe I'll learn elixir one day...

**Comment by adriankumpf** [comment]
I thought about this in the past and leaned more towards introducing a new entity, like you proposed. But I later postponed the idea because I didn't see a clear benefit anymore. 

That's why I'm curios – which information would be useful to you if there was a "trip" entity that combined multiple drives? Stats like average speed/consumption would not be that meaningful, I guess?

Would it make sense to create a new dashboard "trips" that only lists these or would you prefer that trips completely replace their containing drives to get a "clean" drive history?

**Comment by krezac** [comment]
@adriankumpf what bugs me personally is that I like to see the altitude profile and it's splitted into multiple drives/graphs. The idea of "trip" entity came later (mostly for convenience, if you surf thru data from vacation, there would be less records on trip level. 

But I understand the messed up stats could be more pain for majority of users. I'd say ignore it for now, I'll keep it for long winter nights to suggest/code some acceptable approach.

**Comment by cwanja** [comment]
Could you adjust the timeline on the Drive Details dashboard to see the multiple trips? It is not clean directly from the Drives dashboard, but possibly a current solution.

**Comment by timguy99** [comment]
This would certainly help in cases like mine where I stopped to open the gate to my residence and I have an entry like this. I certainly wouldn't consider this a separate trip. It is most definitely part of my drive home:

`

End | Start | Destination | Duration | km | TR Loss | Ø Speed | Ø Consumption | Consumed | Efficiency | Ø Outdoor T. | Ø Indoor T. | max Speed | max Power | min Power | Ø Power | TR Start | TR End | km Start | km End
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2019-11-27 16:39:09 | 2019-11-27 16:41:02 | Home | Home | 2 min | 0.15 km | 0 km | 4 km/h

`

**Comment by cwanja** [comment]
Not sure how complicated this is, but could you present a dashboard in TeslaMate that offers the ability to merge trips? Checkbox individual trips and merge. 

Drop the start, end time, mileage in the middle, etc. and have the computed values still completed in Grafana. Just thinking out loud.

**Comment by qwijib0** [comment]
My use case for this would be a little bit different-- but I think it falls in the same general category.  I semi-regularly take a 200 mile or so trip during which there is very little cell coverage in the middle, so I end up with a ~60 mile drive, a few 5 milers where the car saw cell for a moment, then a ~10 mile drive at the end.  I wish there was a way to make them a "journey" where the computed consumption/efficiency, temperature, etc, could be estimated from start/end data values.
