### ISSUE TITLE
Efficiency Dashboard / Temperature-Efficiency Table / LCD gauge not scaled correctly

### ISSUE THREAD

**Issue by Vic-Y** [adriankumpf/teslamate#2372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading from v1.25.0 to v1.26.0, I noticed the LCD gauge in the Temperature-Efficiency Table of the Efficiency Dashboard is poorly scaled. (Not sure if this change was caused by the upgrade or just coincidental.) See attached screenshot.

### Expected Behavior

The LCD gauge would be more appropriately scaled with a minimum value of 0, which I believe was previously the case.

### Steps To Reproduce

1. Go to Efficiency Dashboard

### Relevant log output

```shell
I don't think log output is required.
There is an override property set for Standard options > Max = 1.15.
LCD gauge would scale better if override property were set for Standard options > Min = 0
```

### Screenshots

![Temperature-Efficiency](https://user-images.githubusercontent.com/62916399/151102880-59ac374c-bcc2-4b63-8ef5-454b3f05fa4b.PNG)

### Type of installation

Docker

### Version

v1.26.0

**Comment by metawatchkalle** [comment]
The min. and max. calculation is set to "auto". It should be set to "0" and "100". After this adaption, the display is scaled correctly.
![image](https://user-images.githubusercontent.com/4587701/151491213-0c1d3253-be4c-4d6f-a150-cefe244286cf.png)

**Comment by DrMichael** [comment]
Created PR https://github.com/adriankumpf/teslamate/pull/2395
