### ISSUE TITLE
Chinese Account: Token refresh failed repeatedly

### ISSUE THREAD

**Issue by yhq34** [adriankumpf/teslamate#2378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrade to new version Token refresh failed error repeatedly occur in the log, below was my docker yml config file.

teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - CHECK_ORIGIN=true
      - TZ=${TM_TZ}
    volumes:
      - ./import:/opt/app/import
    ports:
      - 127.0.0.1:4000:4000
    cap_drop:
      - all

### Relevant log output

```shell
2022-01-27 00:26:32.142 [info] Refreshing access token ...,
2022-01-27 00:26:32.548 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (405.115 ms),
2022-01-27 00:26:34.023 [error] POST https://owner-api.teslamotors.com/oauth/token -> 404 (1475.030 ms),
2022-01-27 00:26:34.024 [warning] Token refresh failed: %TeslaApi.Error{,
  env: %Tesla.Env{,
    __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},,
    __module__: TeslaApi.Auth,,
    body: %{,
      "error" => "not found",,
      "error_description" => "",,
      "response" => nil,
    },,
    headers: [,
      {"x-xss-protection", "1; mode=block"},,
      {"x-accel-redirect-region", "qts"},,
      {"content-type", "application/json; charset=utf-8"},,
      {"x-request-id", "3c627a3b-59fc-46c3-a713-ade04f443a42"},,
      {"x-envoy-upstream-service-time", "801"},,
      {"x-envoy-upstream-cluster", "owner-api"},,
      {"x-frame-options", "DENY"},,
      {"x-content-type-options", "nosniff"},,
      {"strict-transport-security", "max-age=31536000; includeSubDomains"},,
      {"cache-control", "no-cache, no-store, private, s-max-age=0"},,
      {"date", "Wed, 26 Jan 2022 16:26:33 GMT"},,
      {"server", "envoy"},,
      {"transfer-encoding", "chunked"},
    ],,
    method: :post,,
    opts: [],,
    query: [],,
    status: 404,,
    url: "https://owner-api.teslamotors.com/oauth/token",
  },,
  message: nil,,
  reason: :api_token_error,
},
```

### Type of installation

Docker

### Version

1.26.0

**Comment by adriankumpf** [comment]
Can you change the TeslaMate image to `teslamate/teslamate:edge` and see if that helps?

**Comment by yhq34** [comment]
I have done a fresh installation,  after change to "teslamate/teslamate:edge", I can logout and login, before I even cannot login, but have below error, not sure will effect where?

teslamate_1  | 2022-01-27 20:15:24.584 [warning] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/1126095248155383/vehicle_data -> 540 (2564.976 ms)
teslamate_1  | 2022-01-27 20:15:24.584 [warning] TeslaApi.Error / vehicle error: it is online but not responsive
teslamate_1  | 2022-01-27 20:15:24.584 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-27 20:15:44.979 car_id=1 [info] Suspending logging

**Comment by adriankumpf** [comment]
OK great! 

Wait a bit and see if this 540 error disappears. It is not uncommon that the Tesla API temporarily can't report data about your car.

**Comment by yhq34** [comment]
It seems 540 error disappeared, but got some below 408 error;

teslamate_1  | 2022-01-28 09:43:14.514 [info] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/1126095248155383/vehicle_data -> 408 (9201.051 ms)
teslamate_1  | 2022-01-28 09:43:14.514 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-28 09:43:14.514 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-28 09:44:05.269 car_id=1 [info] Suspending logging

**Comment by wuhan321** [comment]
I have encountered it too, but I don't have any data. Could you tell me how to solve it .

**Comment by bawfnje** [comment]
I have encountered it too. Could you tell me how to solve it .

2022-12-16 13:49:26.548 [info] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/366711543804871/vehicle_data -> 408 (9143.739 ms)
2022-12-16 13:49:26.548 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-12-16 13:49:26.549 car_id=2 [error] Error / :unknown
2022-12-16 13:52:10.668 [notice]     :alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_2_api_error}

**Comment by wuhan321** [comment]
> I have encountered it too. Could you tell me how to solve it .
> 
> 2022-12-16 13:49:26.548 [info] GET [owner-api.vn.cloud.tesla.cn/api/1/vehicles/366711543804871/vehicle_data](https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/366711543804871/vehicle_data) -> 408 (9143.739 ms) 2022-12-16 13:49:26.548 [warning] TeslaApi.Error / %{"error" => "{"error": "timeout"}", "error_description" => "", "response" => nil} 2022-12-16 13:49:26.549 car_id=2 [error] Error / :unknown 2022-12-16 13:52:10.668 [notice] :alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_2_api_error}

I've worked it out. I've worked it out.

**Comment by bawfnje** [comment]
how?

**Comment by bawfnje** [comment]
how did you do this?

**Comment by bawfnje** [comment]
> > I have encountered it too. Could you tell me how to solve it .
> > 2022-12-16 13:49:26.548 [info] GET [owner-api.vn.cloud.tesla.cn/api/1/vehicles/************/vehicle_data](https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/366711543804871/vehicle_data) -> 408 (9143.739 ms) 2022-12-16 13:49:26.548 [warning] TeslaApi.Error / %{"error" => "{"error": "timeout"}", "error_description" => "", "response" => nil} 2022-12-16 13:49:26.549 car_id=2 [error] Error / :unknown 2022-12-16 13:52:10.668 [notice] :alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_2_api_error}
> 
> I've worked it out. I've worked it out.

how did you do this?

**Comment by wuhan321** [comment]
> > > I have encountered it too. Could you tell me how to solve it .
> > > 2022-12-16 13:49:26.548 [info] GET [owner-api.vn.cloud.tesla.cn/api/1/vehicles/************/vehicle_data](https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/366711543804871/vehicle_data) -> 408 (9143.739 ms) 2022-12-16 13:49:26.548 [warning] TeslaApi.Error / %{"error" => "{"error": "timeout"}", "error_description" => "", "response" => nil} 2022-12-16 13:49:26.549 car_id=2 [error] Error / :unknown 2022-12-16 13:52:10.668 [notice] :alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_2_api_error}
> > 
> > 
> > I've worked it out. I've worked it out.
> 
> how did you do this?

$10 to help you operate remotely .

**Comment by yhq34** [comment]
Add two server (name I forgot, search other issue) ip in  teslamate: docker-compose.yml, should be fixed
