### ISSUE TITLE
MQTT integration crashes main app after upgrade to v1.12.1

### ISSUE THREAD

**Issue by olexs** [adriankumpf/teslamate#238]
**Describe the bug**
TeslaMate main container crashes after being called from a browser after starting. See error in the "logs" section below. 

**To Reproduce**
This morning I updated my TeslaMate stack as usual, running these command to pull the latest versions of all Docker images on the system and restart Teslamate:
``` 
sudo docker images |grep -v REPOSITORY|awk '{print $1}'|xargs -L1 sudo docker pull
cd teslamate && sudo docker-compose down && sudo docker-compose up -d
```
Afterwards, the frontend failed to respond in browser. Checking the logs, I found the crash message listed below.

Since the error seemed related to MQTT, first thing I tried was disabling it via `DISABLE_MQTT=true` in my `docker-compose.yml`. As suspected, TeslaMate starts and runs just fine with MQTT disabled. It appears there is a bug introduced in MQTT code in TM with v1.12.1 (it worked just fine on v1.12), since `eclipise-mosquitto` is still running version 1.6 as before.

My Mosquitto configuration is almost identical to the default `docker-compose.yml` config.

**Expected behavior**
TeslaMate should not crash independent of whether MQTT integration is enabled or not :)

**Relevant entries from the logs**
```10:57:10.567 [info] Already up
10:57:24.751 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
10:57:24.763 [info] Access TeslaMateWeb.Endpoint at http://admin.teslamate.olex.biz
10:57:24.896 [info] Adding elevation to 2 positions ...
10:57:24.948 [info] Querying location for elevation takes longer than 50ms ...
10:57:25.034 [info] Querying location for elevation takes longer than 50ms ...
10:57:25.797 [info] Found '215014'
10:57:25.811 [info] Initializing handler
10:57:25.812 [info] Connection has been established
10:57:29.880 car_id=1 [info] Start / :online
10:57:30.813 [error] Process #PID<0.3584.0> on node :teslamate@49b755664e62 raised an exception
** (MatchError) no match of right hand side value: nil
    (elixir) lib/task/supervised.ex:517: Task.Supervised.stream_monitor_loop/2
10:57:32.610 [info] GET /
10:57:35.815 [info] Converted exit {:shutdown, {GenServer, :call, [TeslaMate.Vehicles, :which_children, :infinity]}} to 500 response
10:57:35.818 [error] #PID<0.3626.0> running TeslaMateWeb.Endpoint (connection #PID<0.3625.0>, stream id 1) terminated
Server: admin.teslamate.olex.biz:80 (http)
Request: GET /
** (exit) exited in: GenServer.call(TeslaMate.Vehicles, :which_children, :infinity)
    ** (EXIT) shutdown
10:57:35.828 [info] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Mqtt
    ** (EXIT) shutdown: failed to start child: TeslaMate.Mqtt.PubSub
        ** (EXIT) exited in: Task.Supervised.stream(5000)
            ** (EXIT) time out
{"Kernel pid terminated",application_controller,"{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Mqtt',{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Mqtt.PubSub',{timeout,{'Elixir.Task.Supervised',stream,[5000]}}}}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Mqtt',{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Mqtt.P

Crash dump is being written to: erl_crash.dump...done
```

**Operating environment (please complete the following information):**
 - OS: Ubuntu
 - Version: v1.12.1

**Comment by adriankumpf** [comment]
Thank you for the detailed report. 

Looking at the logs it seems to me that a relatively low default timeout prevented the app from starting. Something must have slowed down the process that is responsible for the vehicle which in turn caused some kind of chain reaction. It could have been an unresponsive database, for example.

I therefore assume that MQTT is not the real issue here. I could be wrong though. Could you please try to start the application once again with the MQTT feature enabled?

**Comment by olexs** [comment]
You're right. Initially (before writing the bug report) I restarted the stack several times, and each time it crashed with the above message. During this, the car was charging in underground parking with very bad cellular reception.

Now I've enabled MQTT again, and restarted the stack. It fired up normally, and MQTT works. The car was offline during this startup (asleep in another underground parking, it always goes completely offline when sleeping there). I've since woken it up, everything seems to work as it should, and data is being pumped into MQTT as well. 

Quite weird. Any other ideas how I can help diagnose/debug this?

**Comment by adriankumpf** [comment]
All right, that makes sense. Good to know! I did not expecting that an unresponsive vehicle process could cause problems like that. But parking in a place with poor reception is not so unusual after all :) Making some internal calls asynchronous should fix this.

**Comment by adriankumpf** [comment]
Fixed on master

**Comment by vkarthikbalaji** [comment]
@adriankumpf , Could you make an intermediate fix/release to address this?  Thanks.

**Comment by adriankumpf** [comment]
Actually, I would like to test the changes for a while. How are you affected by this?

**Comment by vkarthikbalaji** [comment]
I am running docker images on digitalocean droplet and not using mqtt perse. Teslamate container seems to have been constantly restarting every 30 seconds, which I didnot notice until later this evening. Then I came across this bug and the log was similar on mine as well. So missed few drives and charging. Now came home and restarted the containers. After few crash-restart attempts (failing to start child mqtt process), now back on track. If you are testing, then it can wait. On hindsight, planning to dropoff at a bodyshop for some paint work and would like to avoid joy riding mechanics taking the car for spin ;)

**Comment by adriankumpf** [comment]
I see. Is disabling mqtt via  `DISABLE_MQTT=true` an option for you? Another possibility would be to build the images from the master yourself.  I need to test the fix for a while because it changed critical parts of the app.

**Comment by vkarthikbalaji** [comment]
Thanks @adriankumpf , I will go with DISABLE_MQTT=true, No problem. Keep up the good work.
