### ISSUE TITLE
2022.4 showing as 2022.40

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#2381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When viewing the `Updates` dashboard, the first 2022 update is showing as 2022.40 instead of 2022.4. 

### Expected Behavior

Reflect the true software version. TeslaMate web interface reflects the right version. 

### Steps To Reproduce

1. Update to 2022.4
2. Open Updates dashboard
3. See the error

### Relevant log output

```shell
NA
```

### Screenshots

![D8D6783E-7402-4E68-BE2A-1F951EE09776](https://user-images.githubusercontent.com/54645561/151286883-b6cf7723-e678-4dd2-8661-c391929472d2.jpeg)
![88C8CC63-58C6-4171-BAC6-892E6FD408D1](https://user-images.githubusercontent.com/54645561/151286885-97cbc964-dc03-4d17-a51a-2b69e84506e7.jpeg)

### Type of installation

Docker

### Version

1.26

**Comment by DrMichael** [comment]
Timewarp...:-)

**Comment by cwanja** [comment]
@adriankumpf looks like it is doing the reverse on the `Overview` dashboard. Showing only 2022. 
![Screen Shot 2022-01-27 at 8 29 58 AM](https://user-images.githubusercontent.com/54645561/151378877-8e933ac3-2233-4ffd-98ef-e83cdd0d986d.png)

**Comment by adriankumpf** [comment]
Good catch, thanks. It should also be fixed on master.
