### ISSUE TITLE
TeslaApi.Error after updating to the last version

### ISSUE THREAD

**Issue by ismcan** [adriankumpf/teslamate#2413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After updating to the last version the application is not able to connect to the API anymore with error 408 as below:
I'm in NA so it's using this API endpoint https://owner-api.teslamotors.com/api

I also regenerated the API token and I'm able to login with it

docker-compose.yml file

> version: "3"
>services:
>  teslamate:
>    image: teslamate/teslamate:latest
>    restart: always
>    environment:
>      - DATABASE_USER=${TM_DB_USER}
>      - DATABASE_PASS=${TM_DB_PASS}
>      - DATABASE_NAME=${TM_DB_NAME}
>      - DATABASE_HOST=database
>      - MQTT_HOST=mosquitto
>\#      - VIRTUAL_HOST=${FQDN_TM}
>\#      - CHECK_ORIGIN=false
>      - TZ=${TM_TZ}
>    ports:
>      - 4000:4000
>\#      - 127.0.0.1:4000:4000
>    volumes:
>      - ./import:/opt/app/import
>    cap_drop:
>      - all

### Expected Behavior

TeslaMate should be able to connect and pull data for the car.

### Relevant log output

```shell
teslamate_1  | 2022-01-31 12:54:49.637 [info] GET /
teslamate_1  | 2022-01-31 12:54:49.641 [info] Sent 200 in 3ms
teslamate_1  | 2022-01-31 12:55:39.160 [info] GET /settings
teslamate_1  | 2022-01-31 12:55:39.173 [info] Sent 200 in 13ms
teslamate_1  | 2022-01-31 12:55:45.689 [info] GET /
teslamate_1  | 2022-01-31 12:55:45.693 [info] Sent 302 in 3ms
teslamate_1  | 2022-01-31 12:55:45.697 [info] GET /sign_in
teslamate_1  | 2022-01-31 12:55:45.703 [info] Sent 200 in 5ms
teslamate_1  | 2022-01-31 12:56:04.915 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (371.681 ms)
teslamate_1  | 2022-01-31 12:59:03.062 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (208.466 ms)
teslamate_1  | 2022-01-31 13:00:24.663 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (370.797 ms)
teslamate_1  | 2022-01-31 13:00:24.698 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-01-31 13:00:24.979 [info] GET /
teslamate_1  | 2022-01-31 13:00:25.824 [info] Starting logger for 'Tesly'
teslamate_1  | 2022-01-31 13:00:25.834 [info] Sent 200 in 855ms
teslamate_1  | 2022-01-31 13:00:26.729 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-31 13:00:26.753 car_id=1 [info] Connecting ...
teslamate_1  | 2022-01-31 13:01:05.969 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxxxxx/vehicle_data -> 408 (9213.542 ms)
teslamate_1  | 2022-01-31 13:01:05.969 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 13:01:05.969 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 13:01:35.165 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxxxxx/vehicle_data -> 408 (9194.396 ms)
teslamate_1  | 2022-01-31 13:01:35.165 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 13:01:35.165 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 13:02:37.050 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxxxxx/vehicle_data -> 408 (9184.722 ms)
teslamate_1  | 2022-01-31 13:02:37.050 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 13:02:37.050 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 13:03:06.262 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxxxxx/vehicle_data -> 408 (9210.451 ms)
teslamate_1  | 2022-01-31 13:03:06.262 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 13:03:06.262 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 13:03:35.511 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxxxxx/vehicle_data -> 408 (9248.095 ms)
teslamate_1  | 2022-01-31 13:03:35.511 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 13:03:35.512 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 13:03:46.910 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
teslamate_1  | 2022-01-31 13:04:04.737 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxxxxx/vehicle_data -> 408 (9223.314 ms)
teslamate_1  | 2022-01-31 13:04:04.737 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 13:04:04.737 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 13:04:33.932 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxxxxx/vehicle_data -> 408 (9193.574 ms)
teslamate_1  | 2022-01-31 13:04:33.932 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 13:04:33.932 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 13:05:03.367 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxxxxx/vehicle_data -> 408 (9433.937 ms)
teslamate_1  | 2022-01-31 13:05:03.368 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 13:05:03.368 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 13:05:28.365 car_id=1 [info] Suspending logging
teslamate_1  | 2022-01-31 13:08:21.631 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-01-31 13:08:21.801 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-01-31 13:08:21.820 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-01-31 13:10:46.917 [notice]     :alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_1_api_error}
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by cwanja** [comment]
`408` would seem like a timeout error. Did the errors continue after the sleep session? Does the Tesla app work?

**Comment by ismcan** [comment]
I kept seeing them since the update.
Tesla app on the phone works... I use it to "wake up" the car while monitoring the teslamate logs.

I haven't driven the car since the update but I'll go out later today... I'll check after if details are reported in the app.

The way I manage to trigger these errors is by signing out of TeslaMate and re-login with the API token & Refresh token. After login, the errors are reported in the logs. 
TeslaMate landing page shows the car info but also shows that the "Health Check failed"

![image](https://user-images.githubusercontent.com/6743463/151867189-b5f3585a-f40c-4584-b825-f22a175bf6f1.png)

**Comment by cwanja** [comment]
The health check errors are related to the `408` errors I am pretty sure - can see that here https://github.com/adriankumpf/teslamate/blob/29bbf7a67c55afe2d7f2048b3ee0249e0effd6ef/lib/tesla_api/vehicle.ex#L83. I would think your device running TeslaMate connecting to the internet, but it seems to authenticate just fine. Have you tried rebooting the device running TeslaMate?

**Comment by ismcan** [comment]
Looks like the "Health check failed" notification went away when car went back to sleep.

I did a test earlier 

### Recycled Docker container
Attaching to teslamate_teslamate_1
teslamate_1  | 2022-01-31 14:22:36.345 [info] Migrations already up
teslamate_1  | 2022-01-31 14:22:38.058 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2022-01-31 14:22:38.058 [info] Version: 1.26.1
teslamate_1  | 2022-01-31 14:22:38.387 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (304.167 ms)
teslamate_1  | 2022-01-31 14:22:38.388 [info] Refreshed api tokens
teslamate_1  | 2022-01-31 14:22:38.417 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-01-31 14:22:38.420 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2022-01-31 14:22:38.421 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2022-01-31 14:22:38.691 [info] GET /
teslamate_1  | 2022-01-31 14:22:40.526 [info] Starting logger for 'Tesly'
teslamate_1  | 2022-01-31 14:22:40.539 [info] MQTT connection has been established
teslamate_1  | 2022-01-31 14:22:40.540 [info] Sent 200 in 1848ms
teslamate_1  | 2022-01-31 14:22:41.724 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-31 14:22:41.751 car_id=1 [info] Connecting ...
teslamate_1  | 2022-01-31 14:25:45.290 car_id=1 [info] Suspending logging
teslamate_1  | 2022-01-31 14:34:05.766 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-01-31 14:34:06.243 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-01-31 14:34:06.272 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-01-31 14:38:49.277 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-31 14:38:49.309 car_id=1 [info] Connecting ...

### Went to car to attempt a drive. Switched to Reverse then Parked the car.
teslamate_1  | 2022-01-31 14:42:47.436 [info] Start of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: xxx, heading: xxx, latitude: xxx, longitude: xxx, native_latitude: xxx, native_location_supported: 1, native_longitude: xxx, native_type: "wgs", power: 1, shift_state: "R", speed: 0, timestamp: 1643658164867}
teslamate_1  | 2022-01-31 14:42:47.437 car_id=1 [info] Driving / Start
teslamate_1  | 2022-01-31 14:42:59.855 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: xxx, heading: xxx, latitude: xxx, longitude: xxx, native_latitude: xxx, native_location_supported: 1, native_longitude: xxx, native_type: "wgs", power: 1, shift_state: "P", speed: 0, timestamp: 1643658179399}
teslamate_1  | 2022-01-31 14:42:59.855 car_id=1 [info] Driving / Ended / 0 km – 0 min
teslamate_1  | 2022-01-31 14:42:59.855 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-31 14:46:34.976 car_id=1 [info] Suspending logging

### Car goes to sleep
teslamate_1  | 2022-01-31 15:03:49.319 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-01-31 15:05:07.404 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-01-31 15:05:07.838 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-01-31 15:05:07.857 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-01-31 15:06:21.308 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-31 15:06:21.339 car_id=1 [info] Connecting ...
teslamate_1  | 2022-01-31 15:09:25.519 car_id=1 [info] Suspending logging

### Logout from TeslaMate
teslamate_1  | 2022-01-31 15:14:45.980 [info] GET /settings
teslamate_1  | 2022-01-31 15:14:45.995 [info] Sent 200 in 14ms
teslamate_1  | 2022-01-31 15:14:49.295 [info] GET /
teslamate_1  | 2022-01-31 15:14:49.300 [info] Sent 302 in 4ms
teslamate_1  | 2022-01-31 15:14:49.303 [info] GET /sign_in
teslamate_1  | 2022-01-31 15:14:49.308 [info] Sent 200 in 4ms

### Login back to TeslaMate which triggers the error
teslamate_1  | 2022-01-31 15:15:18.797 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (302.995 ms)
teslamate_1  | 2022-01-31 15:15:18.813 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-01-31 15:15:19.087 [info] GET /
teslamate_1  | 2022-01-31 15:15:29.382 [info] Starting logger for 'Tesly'
teslamate_1  | 2022-01-31 15:15:29.389 [info] Sent 200 in 10301ms
teslamate_1  | 2022-01-31 15:15:30.136 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-31 15:15:30.155 car_id=1 [info] Connecting ...
teslamate_1  | 2022-01-31 15:15:52.106 [info] GET /
teslamate_1  | 2022-01-31 15:15:52.114 [info] Sent 200 in 8ms
teslamate_1  | 2022-01-31 15:16:09.369 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9211.685 ms)
teslamate_1  | 2022-01-31 15:16:09.369 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:16:09.369 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:16:38.611 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9240.785 ms)
teslamate_1  | 2022-01-31 15:16:38.611 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:16:38.611 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:17:07.892 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9278.817 ms)
teslamate_1  | 2022-01-31 15:17:07.892 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:17:07.892 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:17:37.069 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9174.655 ms)
teslamate_1  | 2022-01-31 15:17:37.069 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:17:37.069 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:17:38.021 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
teslamate_1  | 2022-01-31 15:18:06.267 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9197.104 ms)
teslamate_1  | 2022-01-31 15:18:06.267 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:18:06.267 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:18:35.444 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9174.557 ms)
teslamate_1  | 2022-01-31 15:18:35.444 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:18:35.444 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:19:04.631 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9185.774 ms)
teslamate_1  | 2022-01-31 15:19:04.631 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:19:04.631 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:19:33.861 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9229.291 ms)
teslamate_1  | 2022-01-31 15:19:33.861 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:19:33.861 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:20:02.984 car_id=1 [info] Suspending logging
teslamate_1  | 2022-01-31 15:21:19.343 [info] GET /
teslamate_1  | 2022-01-31 15:21:19.348 [info] Sent 200 in 5ms
teslamate_1  | 2022-01-31 15:21:20.973 [info] GET /
teslamate_1  | 2022-01-31 15:21:20.980 [info] Sent 200 in 6ms
teslamate_1  | 2022-01-31 15:24:38.028 [notice]     :alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_1_api_error}

Does this line mean that TeslaMate was still able to connect to the car to get the details?
**Start of drive initiated by: %TeslaApi.Vehicle.State.Drive**
...
 **End of drive initiated by: %TeslaApi.Vehicle.State.Drive**

**Comment by ismcan** [comment]
I'll try later today to call that Tesla Owner API URL ( https://owner-api.teslamotors.com/api/1/...) from PostMan to see if it works from there...

**Comment by cwanja** [comment]
> I'll try later today to call that Tesla Owner API URL ( https://owner-api.teslamotors.com/api/1/...) from PostMan to see if it works from there...

Just make sure you run it from the same device that has TeslaMate or at least the test would narrow it down to the device having network issues. 

I just checked my logs and woke up the car. There **were** errors present earlier in the logs similar to yours, but it is fine now. Old school, but maybe flush the DNS cache on the device? 

This was six hours ago:
```
teslamate_1  | 2022-01-31 14:05:42.893 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/vehicleID/vehicle_data -> 408 (9138.269 ms)
teslamate_1  | 2022-01-31 14:05:42.894 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 14:05:42.894 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 14:06:12.036 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/vehicleID/vehicle_data -> 408 (9138.420 ms)
teslamate_1  | 2022-01-31 14:06:12.037 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}

```

**Comment by cwanja** [comment]
Alright, never mind. Looks like the endpoint API is having issues. Seeing the same thing now:
```
teslamate_1  | 2022-01-31 20:45:18.437 [warning] GET https://owner-api.teslamotors.com/api/1/vehicles/vehicleID/vehicle_data -> 540 (2724.840 ms)
teslamate_1  | 2022-01-31 20:45:18.438 [warning] TeslaApi.Error / vehicle error: it is online but not responsive
teslamate_1  | 2022-01-31 20:45:18.438 car_id=1 [error] Error / :unknown
```

**Comment by ismcan** [comment]
I think what's happening it that I signed out and signed it to TeslaMate while the car was sleeping... In that instance it seems it's throwing that error.

I woke up the car, then signed out and signed back in into TeslaMate and the fewer errors this time:

### Car asleep
teslamate_1  | 2022-01-31 15:28:18.055 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-01-31 15:28:18.545 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-01-31 15:28:18.566 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-01-31 15:32:14.370 [info] GET /
teslamate_1  | 2022-01-31 15:32:14.377 [info] Sent 200 in 6ms

### Car online
teslamate_1  | 2022-01-31 15:43:21.195 [info] GET /
teslamate_1  | 2022-01-31 15:43:21.202 [info] Sent 200 in 6ms
teslamate_1  | 2022-01-31 15:43:36.314 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-31 15:43:36.341 car_id=1 [info] Connecting ...
teslamate_1  | 2022-01-31 15:43:42.581 [info] GET /settings
teslamate_1  | 2022-01-31 15:43:42.591 [info] Sent 200 in 9ms
teslamate_1  | 2022-01-31 15:43:44.673 [info] GET /
teslamate_1  | 2022-01-31 15:43:44.678 [info] Sent 302 in 4ms

### Sign in again
teslamate_1  | 2022-01-31 15:43:44.681 [info] GET /sign_in
teslamate_1  | 2022-01-31 15:43:44.685 [info] Sent 200 in 4ms
teslamate_1  | 2022-01-31 15:44:06.344 car_id=1 [error] Error / not_signed_in
teslamate_1  | 2022-01-31 15:44:07.833 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (274.496 ms)
teslamate_1  | 2022-01-31 15:44:07.860 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-01-31 15:44:08.122 [info] GET /
teslamate_1  | 2022-01-31 15:44:08.533 [info] Starting logger for 'Tesly'
teslamate_1  | 2022-01-31 15:44:08.540 [info] Sent 200 in 417ms
teslamate_1  | 2022-01-31 15:44:09.505 car_id=1 [info] Start / :online
teslamate_1  | 2022-01-31 15:44:09.561 car_id=1 [info] Connecting ...

### 3 minutes without an error vs. ~20s before. And only 3 errors this time vs. 8 reports before
teslamate_1  | 2022-01-31 15:47:23.744 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9166.676 ms)
teslamate_1  | 2022-01-31 15:47:23.744 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:47:23.744 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:47:53.037 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9290.693 ms)
teslamate_1  | 2022-01-31 15:47:53.037 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:47:53.037 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:48:22.213 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxx/vehicle_data -> 408 (9174.522 ms)
teslamate_1  | 2022-01-31 15:48:22.213 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-01-31 15:48:22.213 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-01-31 15:48:22.968 [info] GET /
teslamate_1  | 2022-01-31 15:48:22.974 [info] Sent 200 in 6ms
teslamate_1  | 2022-01-31 15:48:24.031 [info] GET /
teslamate_1  | 2022-01-31 15:48:24.035 [info] Sent 200 in 4ms
teslamate_1  | 2022-01-31 15:48:42.986 car_id=1 [info] Suspending logging

I'll check tonight if the drives/SoC is reported in TeslaMate once I go out driving.

**Comment by cwanja** [comment]
Per a Discord channel chat, `408` is polling the car while the car is asleep. So it would be the indication that the car is asleep. Seems to be working as intended.

**Comment by ismcan** [comment]
Yes it's working fine, I'm confirming that after the last drive, the data IS reported in TeslaMate. This is a non-issue.

I updated the software, then worked to make it available externally through a proxy and started checking the logs in the process... saw those errors and thought it's a problem.
