### ISSUE TITLE
Redirect fails when accessing docker containers in network

### ISSUE THREAD

**Issue by elipongr** [adriankumpf/teslamate#2414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

So if i start the docker container on my raspberry pi everything works fine. But in my case i want it to be accesiible in the whole network where my raspberry pi is in it, which works without issues.¨

The problem coms when i try to navigate in the teslamate app which redirects me always to localhost:3000 and not <ip of my raspberry pi>:3000.

### Expected Behavior

redirect to <ip of raspberry pi>:3000

### Steps To Reproduce

1. Start the containers
2. Open the ports
3. Go on another device in the network
4. Go on <ip of raspberry>:4000
5. Try the navbar out

### Relevant log output

```shell
not needed
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/36076242/151877572-f96c05d2-0ea7-48d9-9b58-e20f323eef22.png)

### Type of installation

Docker

### Version

3

**Comment by metaben** [comment]
":3000" is not a valid URL
What did you configure the Web App URL to in Settings?

**Comment by elipongr** [comment]
kept in on default settings from the compose file.

**Comment by metaben** [comment]
And did you try setting it?

**Comment by elipongr** [comment]
Through which env variable? I  went through the list but didnt found anything i would have called used for that.

**Comment by cwanja** [comment]
TeslaMate runs on `:4000` and Grafana runs on `:3000`. You would have a conflict with Grafana if you wanted TeslaMate to be accessible from port `:3000`.
