### ISSUE TITLE
Misc. data points missing in Grafana

### ISSUE THREAD

**Issue by airmaxx** [adriankumpf/teslamate#242]
**Describe the bug**
Some fields in Grafana show only a minus "-"
- in Drives: avg Consumption and Consumed
- in Vampire Drain: Consumption and avg. Power
- in Location: City
In Overview: Charging voltage and Charging kW show 0V/kW, even though the car is currently in charging.

**Relevant entries from the logs**
not sure if the'd help - I can add them per request.

<img width="611" alt="Teslamate" src="https://user-images.githubusercontent.com/20067957/68307459-8e98af00-00ab-11ea-96b4-66e02e45ebd3.png">
**Operating environment (please complete the following information):**
 - OS: Ubunutu
 - Version: Git head, manually compiled

**Comment by adriankumpf** [comment]
That's fine. See [FAQ: Why are no consumption values displayed in Grafana?](https://github.com/adriankumpf/teslamate/blob/master/docs/faq.md#why-are-no-consumption-values-displayed-in-grafana)
