### ISSUE TITLE
Detection of Refresh Model X (2022)

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#2454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Teslamate Web UI does not detect the make/model of the Model X/Model X Plaid

### Expected Behavior

Display the make/model of the car below the vehicle name

### Steps To Reproduce

1. Go to http://teslamate:4000
2. View car(s) listed
3. No make/model for the 2022 Model X

### Relevant log output

```shell
N/A
```

### Screenshots

![PNG image](https://user-images.githubusercontent.com/19696424/153037885-e2229350-44d2-4c2d-8226-440690377bd2.png)

### Type of installation

Docker

### Version

1.26.1

**Comment by cwanja** [comment]
Had the same issue in my refreshed Model S - https://github.com/adriankumpf/teslamate/issues/2193#issuecomment-993406286

We had to update the detection in TeslaMate reading the owners API. Do you know how to query the owners API and get the returned value?

**Comment by natrlhy** [comment]
Yep..

`"car_type": "tamarind"`

@adriankumpf can this be added as well?

Thanks!

**Comment by cwanja** [comment]
Created a PR for it. #2455

**Comment by natrlhy** [comment]
Thanks!
