### ISSUE TITLE
Vampire Drain: Do not display periods during which the vehicle has been preheated

### ISSUE THREAD

**Issue by shaun72** [adriankumpf/teslamate#248]
I have my Tesla now for over a month. After the first month of pure fun, I start looking a little deeper into the physics and Technology. 
Using your tool made me realise, that there could be some improvement for less Vampire drain during night and office times.
Now as the nights get colder, we start to heat the car in the morning.

But then we realised that teslamate does not realise the heating. So the Vampire Drains went sky high.
Is there any chance to exclude them from vampire losses or maybe split it into the 3 phases
# try to sleep
# sleeping
# conditioning/heating

Shaun

**Comment by timguy99** [comment]
I was just about to enter a new issue with this same thing cause I noticed that the Vampire Drain numbers seemed to be way overstated based on my own observations outside of TeslaMate. I suspected that they were including the pre-heat periods as those were the times that the numbers seemed to be WAY WAY higher than I noticed myself.

SO, I vote this up otherwise the Vampire Drain stats are practically useless.

**Comment by markusdd** [comment]
I do not know if this is a real remedy, but you may consider using the REST API approach to resume logging and set the car online when starting the pre-heat. Will it then be included in the vampire drain?

I'm using this method and pre-heat every morning, but my installation is very new. Will report back if I experience this. If not we may have a work-around.

**Comment by adriankumpf** [comment]
> I do not know if this is a real remedy, but you may consider using the REST API approach to resume logging and set the car online when starting the pre-heat. Will it then be included in the vampire drain?

At the moment the dashboard queries the range loss between two dives This would therefore make no difference. The query could of course be adapted so that only the loss during the sleep phases is determined.

**Comment by markusdd** [comment]
And it should include the climate control If it is on it should not be included. 
The problem is that the car can wakeup intermittendly, so just looking on sleep is probably not enough or even wrong.

**Comment by timguy99** [comment]
> > I do not know if this is a real remedy, but you may consider using the REST API approach to resume logging and set the car online when starting the pre-heat. Will it then be included in the vampire drain?
> 
> At the moment the dashboard queries the range loss between two dives This would therefore make no difference. The query could of course be adapted so that only the loss during the sleep phases is determined.

The point here is that we DO NOT WANT the pre-heat to be included in the vampire drain. Consider it as part of the drive or as suggested another "status" like preheating if possible.

**Comment by timguy99** [comment]
Any further decisions on this?

**Comment by adriankumpf** [comment]
Sorry, the @github-actions bot should have ignored this issue. The status has not changed - it is still on the To-Do list.

**Comment by espenu** [comment]
Would it be possible to modify this request to include all temp/climate states? I don't think pre-cooling the car should be considered vampire drain either. Maybe add AC/heating as states? I was camping in the car last night and had camping mode on all night, but this only shows up as vampire drain.
