### ISSUE TITLE
Requesting an automatic update method for Teslamate

### ISSUE THREAD

**Issue by mikec-design** [adriankumpf/teslamate#2482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Each time I update Teslamate I find that it completely breaks the application. I then have to spend hours, days, or longer to diagnose the problems and test solutions.

I've repeatedly been caught off guard by updates to the config file for new versions. The need to check review the config file isn't mentioned in the "Upgrading to a new version" documentation.

A friendlier method comparable to PiHole's "pihole -up" would be incredibly helpful.

### Expected Behavior

Updates to Teslamate should progress smoothly, updating any necessary components or config files as needed with a minimum of manual editing or configuration.

### Relevant log output

```shell
N/A
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by BabyYeggie** [comment]
You can use Ouroboros, but change interval to 604800 (1 week):
`version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=604800
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=America/Chicago
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock`

https://github.com/pyouroboros/ouroboros

**Comment by init6-git** [comment]
This is not an issue. Never had a problem upgrading and even the bullseye was a Pi OS issue rather than a Teslamate one. Are you expecting Adrian to test Teslamate on every conceivable version of hardware and OS? As Cwanja says above, docker gets rid of a lot of the hassle, but you are responsible for the OS. Perhaps Teslafi would be a better fit for you.

**Comment by adriankumpf** [comment]
Since good hints and suggestions have already been posted, I'll move this thread to a discussion.
