### ISSUE TITLE
Link from dashboard to Grafana

### ISSUE THREAD

**Issue by ilkkao** [adriankumpf/teslamate#249]
**Is your feature request related to a problem? Please describe.**
There's no simple way to navigate from dashboard to Grafana

**Describe the solution you'd like**
Link named "Grafana" or "Graphs" in the top bar. Destination URL of this link would be set in settings. By default the URL could be unset and in that case the link could trigger an alert saying that you need to enter the destination URL in settings. This is because Grafana URL I believe is not really standardized. But if it's known that most people host grafana at `/grafana` then that could be the default. But then again, if it's not there, 404 will not indicate how to fix it.

**Comment by spacecosmos** [comment]
It's already in the works (I hope?): #235 
:)

**Comment by ilkkao** [comment]
Great, I should have checked the PRs before. You can consider this as a plus one.

**Comment by ilkkao** [comment]
Duplicate of #235
