### ISSUE TITLE
Consumption figures suddenly went to zero

### ISSUE THREAD

**Issue by jalkanen** [adriankumpf/teslamate#250]
All consumption figures are suddenly zero, including past ones. Teslamate is installed with docker-compose pull && docker-compose up, so version is latest released. Restart was attempted but it didn't change anything.

Nothing changed, everything worked a couple of days ago, there was no upgrade. No error logs visible in console.

However, Grafana still displays efficiency figures for all drives, so all data seems to be in the database, so I suspect something odd with Grafana.
<img width="595" alt="Screen Shot 2019-11-10 at 12 48 46" src="https://user-images.githubusercontent.com/220043/68542754-8cd73000-03b8-11ea-8e08-15d759ef8e65.png">

**Comment by jalkanen** [comment]
Also noticed that the current ideal efficiency figures are zero. Related?

<img width="1353" alt="Screen Shot 2019-11-12 at 22 55 26" src="https://user-images.githubusercontent.com/220043/68710144-ad151380-059f-11ea-8239-1ea8edd21ba7.png">

**Comment by jalkanen** [comment]
Okay, didn't find the root cause, but got to fix the symptoms. Efficiency in the car table had been set to zero; resetting it to a known figure helped.

So it seems to me that the new code which estimates the new efficiency figures dynamically is somewhat broken as it may end up inserting a zero for efficiency.

```
teslamate=# select id, model, name, efficiency from cars;
 id | model |  name  | efficiency 
----+-------+--------+------------
  1 | 3     | TARDIS |          0
(1 row)

teslamate=# update cars set efficiency=0.153 where id=1;                                                                                                                                                                                                                                          
UPDATE 1
teslamate=# select id, model, name, efficiency from cars;
 id | model |  name  | efficiency 
----+-------+--------+------------
  1 | 3     | TARDIS |      0.153
(1 row)
```

**Comment by adriankumpf** [comment]
I'm glad you found the (temporary) fix! The next release will reject efficiencies of zero.
