### ISSUE TITLE
kWh and Consumption missing from Drives

### ISSUE THREAD

**Issue by gck303** [adriankumpf/teslamate#2515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My drives data is missing the kWh and Consumption values. 

It is a fresh install on Docker and everything is working correctly. Just that this data is missing! I have check in teh database and the relevent fields are empty. 

### Expected Behavior

I would expect that the kWh and Consumption fields are populated. 

### Steps To Reproduce

Can be seen by viewing the "Teslamate/Drives" dashboard. 

### Relevant log output

```shell
no log details.
```

### Screenshots

![2022-03-02 21_31_52-Drives - Grafana](https://user-images.githubusercontent.com/30334661/156453613-5b963b82-b513-4b7e-ad35-ab281a44a41a.png)

### Type of installation

Docker

### Version

1.26.1

**Comment by cwanja** [comment]
https://docs.teslamate.org/docs/faq#why-are-no-consumption-values-displayed-in-grafana

Give it time to populate. You need to have charging sessions in there as well.

**Comment by gck303** [comment]
Thank you. I will give it a go with two charging sessions. I tried so hard and did not see it in the FAQ. Oooops. 

The efficidency dashboard is also has empty consumption values.

**Comment by cwanja** [comment]
Yep, same issue I hit earlier. And I used the software for two years before. So it happens. Enjoy the car and TeslaMate!

**Comment by huacius** [comment]
I have two cars, model X and y.
Model X has kWh and consumption. Model y doesn't.
If necessary, I can provide an account for debugging

**Comment by sknsean** [comment]
Same here.
Our Model 3 LR 19' is with consumption and our new Modem 3 SR 22' is without.. :/

**Comment by azzarri** [comment]
Same issue here.  I've been running teslamate for years.

I have three cars. 3 and Y shows up fine. X has always been without consumption.
