### ISSUE TITLE
 visit http://IP:4000 How to add a password

### ISSUE THREAD

**Issue by huacius** [adriankumpf/teslamate#2531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 visit http://IP:4000 How to add a password?

### Relevant log output

```shell
null
```

### Type of installation

Docker

### Version

1.26.1

**Comment by cwanja** [comment]
Look at the advance installation options https://docs.teslamate.org/docs/guides/traefik or https://docs.teslamate.org/docs/guides/apache

Or possible Portainer could be a solution. https://docs.teslamate.org/docs/guides/portainer
