### ISSUE TITLE
Disable sleep attempts when sentry mode is on.

### ISSUE THREAD

**Issue by thouchin** [adriankumpf/teslamate#254]
I lost data today when driving home from the gym.  The car was parked for 1.5 hours at the gym with sentry mode on so it did not sleep.  But Teslamate still paused its polling in an attempt to allow the sleep mode.   If the car will never sleep then there is no need to risk losing data as a result of the TeslaMate logging pause.

I dont yet know how to determine if the Sentry mode status is available in the API. If it is, that could be used to disable the Sleep feature.

If Sentry mode status is not available it is more complicated but still doable.  We can manually tell TeslaMate how it is configured.  It would consist of 4 checkboxes that mirror the cars config: Sentry mode on, Exclude Home, exclude work, exclude favorites.  This would require the use of geofences around home and work (easy) and also for ALL favorites (not as easy if there are alot).
Sudo code...
If (SentryMode == off || 
   (ExcludeHome && atHome) ||
   (ExcludeWork && atWork) ||
   (ExcludeFavorite && atFavorite))
Then enableSleepMode

I personally dont have "exclude favorites" checked I only turn off sentry at home and at work.

**Comment by adriankumpf** [comment]
What you are saying seems very deterministic. The thing is Teslamate does not halt polling if sentry mode is on. It does know how to read the sentry mode status from the API and uses it accordingly.

I’m assuming you’ve read [the documentation](https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md) on how the sleep mechanism works and therefore you know of the possible interfaces to instruct the logger to expect the vehicle to wake up. I’d recommend to use these wake-up hints or tune the sleep configuration to suit your needs if you want to really make sure that Teslamate catches all of you drives.

If you still feel that something is not working as intended, open a Github issue via “New issue” > “Bug report” and provide the relevant entries from the application logs as the bug report template requires.

**Comment by thouchin** [comment]
Thanks for clarifying that polling continues while in sentry mode.  I did read the documentation on sleep but didnt see it in there.  I will look into other reasons why the data would have been lost.
