### ISSUE TITLE
All Dashboards failing after updating Grafana to v8.4.3

### ISSUE THREAD

**Issue by TheDK** [adriankumpf/teslamate#2546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Updated Grafana (used as Home Assistant add-on) to v8.4.3 all dashboard / panel stop working, typical error:

```
origin not allowed {"results":{"A":{"error":"db query error: pq: Syntaxfehler bei »ORDER«","frames":[{"schema":{"refId":"A","meta":{"executedQueryString":"(SELECT battery_level, date\nFROM positions\nWHERE car_id = \nORDER BY date DESC\nLIMIT 1)\nUNION\nSELECT battery_level, date\nFROM charges c\nJOIN charging_processes p ON p.id = c.charging_process_id\nWHERE date BETWEEN '2022-03-17T07:02:08.978Z' AND '2022-03-18T07:02:08.978Z' AND p.car_id = \nORDER BY date DESC\nLIMIT 1"},"fields":[]},"data":{"values":[]}}]}}} 
```

Roll-back to  v8.3.4 solves the problem. Tested on two different instances, same result.

Also reported the issue with the TeslaMate HA add-on.

### Expected Behavior

Show values... :)

### Steps To Reproduce

1. Update Grafana to the current release
2. Open any dashboard

### Relevant log output

```shell
No log output from TM relevant - Grafana error see above.
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/5020623/158953565-9d7260fb-b449-47b9-8ce0-2e19aa8eb1dc.png)

### Type of installation

Manual

### Version

v1.26.1

**Comment by TheDK** [comment]
Update: Also, lots of "origin not allowed" errors which seem to point to proxy problem. Strange... Will continue to investigate...

**Comment by TheDK** [comment]
Issue is with Grafana and NGINX, has nothing to do with TeslaMate, sorry for confusion...

**Comment by svcGitHubLfcmgmt** [comment]
Configure your reverse proxy to keep the original Host header.

```
For nginx: proxy_set_header Host $http_host;
For Apache2: ProxyPreserveHost On
```

**Comment by ngeorgieff** [comment]
Configure your reverse proxy to keep the original Host header.

For nginx: proxy_set_header Host $http_host;
For Apache2: ProxyPreserveHost On

**Comment by TheDK** [comment]
I use it as part of Home Assistant where this is already the case. The problem only turns up with Win10 and FireFox, Chrome is working fine. I therefore just ignored it as I can’t reproduce it anymore on my test system.

**Comment by thibault-ml** [comment]
@ngeorgieff thank you for that answer, that really helped.
