### ISSUE TITLE
Overview Dashboard -> Battery Level -> Make more relevant

### ISSUE THREAD

**Issue by marcogabriel** [adriankumpf/teslamate#255]
The Battery Level Gauge on the Overview Dashboard currently shows following values/colors:

* 0 to 25 -> red
* 25 to 60 -> yellow
* 60 to 100 -> green

I'd like to see this gauge being changed to real world recommendations:

* 0 to 10 -> red
* 10 to 20 -> yellow
* 20 to 80 -> green
* 80 to 90 -> yellow
* 90 to 100 -> red

There may be different favorites as tesla recommends keeping the charge between 20% and 80% of the battery, setting it to 90/100 before starting a long range trip. 

There is even a recommendation to keep charge between 35% and 65% for a longer battery life. If not considered too much colors, then this could inserted as well by using a deep green between 35 and 65%.

**Comment by adriankumpf** [comment]
Fixed with 14ceefd906c9f7e076f597ef4a85fc1e74ae716f

**Comment by adriankumpf** [comment]
Sorry if I closed this too quickly - your PR changed the thresholds very moderately, but you also proposed another solution, right? Changing the threshold to reflect real world recommendations definitely makes sense. More PRs are welcome :-)

**Comment by marcogabriel** [comment]
Maybe there's some more. I saw a few dashboards recently that I found interesting. I'll try to adapt them when I have time and make some more PRs.
