### ISSUE TITLE
'epmd' process listening on all interfaces although TeslaMate isn't. Bug?

### ISSUE THREAD

**Issue by jensb** [adriankumpf/teslamate#2554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed TeslaMate without docker, since I already have instances of Grafana, Postgres, etc. running. I intentionally hid Teslamate behind a SSL-tunnelling, authenticating proxy (Caddyserver), to secure it, so I set up a systemd script with

Environment="HOST=127.0.0.1"
Environment="PORT=4100"
Environment="HTTP_BINDING_ADDRESS=127.0.0.1"

However, after startup I noticed that an `epmd` process is listening on all interfaces on port 4369. This seems to be a PubSub client.

Is this intentional and necessary? It seems to be a (potential) security issue.

### Expected Behavior

Restricting TeslaMate to the local interface in the systemd startup scripts should apply to all processes TM spawns, not just the main webserver process.

### Relevant log output

```shell
screen pi@raspberry64:~ $ sudo netstat -tulpn|grep LISTEN|grep 0.0.0.0 |grep epmd
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      3908530/epmd        
screen pi@raspberry64:~ $ ps axuuw|grep epmd
teslama+ 3908530  0.0  0.0   2832  1356 ?        S    21:25   0:00 /home/teslamate/tm/_build/prod/rel/teslamate/erts-12.2.1/bin/epmd -daemon
```

### Type of installation

Manual

### Version

v1.26.1

**Comment by adriankumpf** [comment]
EPMD is the `Erlang Port Mapper Daemon`: https://www.erlang.org/doc/man/epmd.html It gets started by default but  it is not needed for TeslaMate. I've disabled it in [8bf913a](https://github.com/adriankumpf/teslamate/commit/8bf913a06bd5be964fae5312e79cc3a47bda9a73).

**Comment by Obihoernchen** [comment]
@adriankumpf are you sure about this?
For me 1.27.0 does not work without epmd running. I'm using a manual install with systemd service.

Environment vars look like this:
```
Environment="HOME=/opt/teslamate"
Environment="LANG=en_US.UTF-8"
Environment="LC_CTYPE=en_US.UTF-8"
Environment="TZ=Europe/Berlin"
Environment="HTTP_BINDING_ADDRESS=127.0.0.1"
Environment="PORT=4000"
Environment="ENCRYPTION_KEY=XXXXXXX"
Environment="DATABASE_USER=teslamate"
Environment="DATABASE_PASS=XXXXXXX"
Environment="DATABASE_NAME=teslamate"
Environment="DATABASE_HOST=127.0.0.1"
Environment="DISABLE_MQTT=true"
Environment="VIRTUAL_HOST=XXX.XXXX.XXX"
Environment="CHECK_ORIGIN=true"
```

I get the following error during startup:
```
teslamate[798497]: Protocol 'inet_tcp': register/listen error: econnrefused
```

Starting epmd manually or via systemd service and everything works fine again.
