### ISSUE TITLE
Consumption reported incorrectly in cold weather (with "snowflake" icon on screen)

### ISSUE THREAD

**Issue by olexs** [adriankumpf/teslamate#257]
**Describe the bug**
Energy consumption and estimated range is reported incorrectly during a drive when the battery is very cold and the car shows the "snowflake" icon on screen.

**To Reproduce**
1. Let the car sit in the cold for a while.
2. Start driving and note the "snowflake" icon showing near the battery state on screen.
3. Drive for a while, until the battery is warmed up and the "snowflake" icon is gone.
4. Compare reported consumption during the drive on the car's screen and in TeslaMate. TM reports a significantly lower consumption (e.g. 120 Wh/km in TM vs. 180 in the car).

**Expected behavior**
Reported consumption should be close to what the car itself reports, and not affected by the cold.

**Relevant entries from the logs**
Nothing specifically interesting in the logs. Drive looks like this:
```
07:30:11.606 car_id=1 [info] Start / :online
07:30:11.622 car_id=1 [info] Driving / Start
07:30:11.680 [info] Querying location for elevation takes longer than 50ms ...

### Above message repeats ~50 times during the drive. 

### At the end of the drive, car is parked underground with bad reception and a couple minutes later plugged in to charge.

07:52:45.578 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
07:52:45.579 car_id=1 [warn] Error / upstream timeout
07:52:59.717 car_id=1 [info] Driving / Ended / 23 km – 23 min
07:52:59.718 car_id=1 [info] Start / :online
08:02:06.628 car_id=1 [info] Charging / SOC: 15% / Arbeit (Oval)
08:13:06.704 [info] GET /
08:13:06.711 [info] Sent 200 in 6ms
```

**Screenshots**
![image](https://user-images.githubusercontent.com/650941/68924638-9201f980-0781-11ea-923f-c13f99b29b26.png)
Note how the overall consumption during the drive is only 16km of range, while I drove for 23km on a very cold morning, mostly on the highway. Consumption reported by the car is 179 Wh/km. Same thing happened last evening, too:
![image](https://user-images.githubusercontent.com/650941/68924747-c2e22e80-0781-11ea-9a76-55f466c8fc0b.png)

Before both drives, the "vampire drain" display shows a significant range drop, even though the car was asleep as usual and shouldn't have consumed any more than typical power:
![image](https://user-images.githubusercontent.com/650941/68924987-4ac83880-0782-11ea-85a3-0713eeff0176.png)

What I think is happening: when the car shows the snowflake, a percentage of SoC is "locked away" for thermal management and under-discharge prevention. This can be seen as a blue-marked portion of the battery in the Charging screen in the car. The range reported by the car is probably reduced by this "reservation". This causes the "vampire drain" to show increased consumption during the standby period, because the reserved capacity is added to the actual drained amount. During the drive, the reserved percentage reduces and eventually goes away completely as the battery warms up. To TeslaMate this looks like the car has regained some range over the drive, thus reducing the shown consumption.

**Operating environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Version: v1.12.1

**Comment by adriankumpf** [comment]
> What I think is happening: when the car shows the snowflake, a percentage of SoC is "locked away" for thermal management and under-discharge prevention. This can be seen as a blue-marked portion of the battery in the Charging screen in the car. The range reported by the car is probably reduced by this "reservation". This causes the "vampire drain" to show increased consumption during the standby period, because the reserved capacity is added to the actual drained amount. During the drive, the reserved percentage reduces and eventually goes away completely as the battery warms up. To TeslaMate this looks like the car has regained some range over the drive, thus reducing the shown consumption.

Yes, that's exactly what is happening. API-based loggers don't have access to all information that is available from inside the car. For example, the consumption is not reported directly, but derived from the range difference. With the current state of the API we have to live with that limitation, I guess.

As a workaround a snowflake icon could be displayed to indicate that these drives or vampire drain periods may be inaccurate. Other than that I don't see how to "fix" this.

**Comment by olexs** [comment]
I was afraid of that. I guess this is a limitation of working with a non-official, undocumented API. Thank you for the confirmation. Maybe at some point the Tesla app will be updated to show the snowflake icon and reserved battery capacity - then they'd need to add the data to the API, making it possible for TeslaMate and others to account for this.

**Comment by adriankumpf** [comment]
Yeah, that would be great.

**Comment by olexs** [comment]
This morning while sitting in traffic on the way to work I noticed the snowflake icon again, and decided to look in the app. And what do you know:

![IMG_0102](https://user-images.githubusercontent.com/650941/70504543-3d566200-1b26-11ea-8032-f06bd5aee423.png)

So the API does provide information that the reservation is there, in some way. I haven't taken enough samples to see whether the blue area changes size - the snowflake went away soon after this first screenshot.

Is there a way to log Tesla API responses in full with TeslaMate? I could produce this situation again, and with the car's exact API responses at the time, maybe something could be reverse-engineered here.

**Comment by adriankumpf** [comment]
AFAIK the app uses the [`usable_battery_level`](https://tesla-api.timdorr.com/vehicle/state/chargestate). We need the more precise `ideal_battery_range`/`rated_battery_range` which behaves like the `usable_battery_level`.  However, there is no `real_battery_range` or something like that.

**Comment by ctraber** [comment]
I was watching my `ideal_battery_range/rated_battery_range` during cold weather and they also go down while cold and come back when getting warmer. 
Is it possible that `ideal_battery_range/rated_battery_range` already behaves like  `usable_battery_level`?
This would mean all calculations using `ideal_battery_range/rated_battery_range` should also use `usable_battery_level` instead of `battery_level`.

Might explain e.g. spikes with low projected 100% range in Degradation chart during cold weather.

**Comment by adriankumpf** [comment]
> Is it possible that ideal_battery_range/rated_battery_range already behaves like usable_battery_level?

Yes, absolutely. What I meant is that there seems to be no way to precisely infer the actual range in those situations.
