### ISSUE TITLE
Wrong elevation values when driving in tunnel

### ISSUE THREAD

**Issue by spacecosmos** [adriankumpf/teslamate#260]
I got this interesting bug from a friend yesterday. The elevation seems to report wrong value when driving in a tunnel. The correct elevation here should be approx 20 to 30 meters, but it reports over 320 meters.

![image002](https://user-images.githubusercontent.com/55928670/69042763-18247700-09f2-11ea-8869-cf18d388f759.png)

Any insight on how this is actually calculated and measured?

**Comment by adriankumpf** [comment]
The elevation is not directly reported by the Tesla API. TeslaMate uses an open dataset providing terrain heights (SRTM data). The great thing about this is that querying locations for elevation data takes place locally on your machine. Therefore, no third party gets your location data. The drawback is that for routes with bridges or tunnels, the elevation cannot be determined correctly.
