### ISSUE TITLE
Add tire pressure information

### ISSUE THREAD

**Issue by tomS3210** [adriankumpf/teslamate#2604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It's not a bug but I don't know how to make a proposal so I'm doing it here.

Tire pressure information is now available in TeslaFi, so it needs to be uploaded by the car's API.
What do you think about adding a "Tyre pressure" table with measurements ?

Thanks :-)

### Relevant log output

```shell
None
```

### Screenshots

![tirepressure](https://user-images.githubusercontent.com/949584/162816918-36b80c3c-c253-4fde-96d9-7fd9d67b1c2d.png)

### Type of installation

Docker

### Version

1.26.1

**Comment by adriankumpf** [comment]
Closing this in favour of #2501 and #1484

**Comment by tomS3210** [comment]
Ok thanks Adrian.
