### ISSUE TITLE
Map empty in app view

### ISSUE THREAD

**Issue by virtualm2000** [adriankumpf/teslamate#262]
**Describe the bug**
After the first load, the car's location on the map is correct. After the first TriggerChange hook event the map card is empty.

**To Reproduce**
Load the app page and wait 10 seconds or if the car is moving it's instant.

**Expected behavior**
Car's position should be plotted on the map

**Relevant entries from the logs**
When the map is visible:
class="map leaflet-container leaflet-safari leaflet-fade-anim"

When the map is empty:
class="map"

So it seems that the new rendered page is missing the proper styling.
If I manually insert the styling back in the browser the map becomes visible again.

**Screenshots**
![Screenshot 2019-11-19 at 12 13 33](https://user-images.githubusercontent.com/24257689/69145692-20e67d00-0ac6-11ea-8e51-5b66124c51f1.png)

**Operating environment (please complete the following information):**
Manual install Debian buster/sid

**Comment by adriankumpf** [comment]
Fixed on master. Thanks!
