### ISSUE TITLE
Interrupted charging sessions

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#264]
**Describe the bug**
When charging is interrupted (for my example, a software update), the initial charging session is recorded in TeslaMate plus when the charging session restarts (e.g. there are two rows for a single charging session). However, if you go into the details for the initial charging session, it includes all of the details from start to finish plus the interruption. It also has a weird bug where it keeps recording indefinitely (noted by the "few seconds ago" in the screenshot).

There is also another charging record that includes only the details _after_ charging restarts. 

**To Reproduce**
1. Start a charging session
2. Verify TeslaMate is recording
3. Interrupt the session somehow (mine was a software update)
4. Begin charging again
5. Review charts in Grafana.

**Expected behavior**
A single record for the charging session including the interrupted period and a completion of the charging session when it is done.

**Screenshots**
Charging dashboard
![Screen Shot 2019-11-20 at 5 00 36 PM](https://user-images.githubusercontent.com/54645561/69285905-9d0cbd80-0bb7-11ea-8cb1-1150371efd66.png)

Original charging session, note the underlined dashboard time and circle gap in the session
![Screen Shot 2019-11-20 at 5 01 11 PM](https://user-images.githubusercontent.com/54645561/69285945-abf37000-0bb7-11ea-9672-af34110d8b73.png)

Second session after being interrupted
![Screen Shot 2019-11-20 at 5 00 22 PM](https://user-images.githubusercontent.com/54645561/69285966-b9105f00-0bb7-11ea-910f-399e2fba037c.png)

**Operating environment (please complete the following information):**
 - OS: [Rasbian]
 - Version [TeslaMate V1.1.12]

**Comment by cwanja** [comment]
As follow up, I completed a full round of charging and the interrupted session is still going. Is there any way to stop a that session from recording.
![Screen Shot 2019-11-22 at 11 48 39 AM](https://user-images.githubusercontent.com/54645561/69448382-09093600-0d1e-11ea-8dee-e82996161dfa.png)

**Comment by adriankumpf** [comment]
The underlying problem is that immediately before the charging session is stopped during the software update, the car reports invalid data , e.g. no charger power. This caused the recorded charging session to be interrupted unexpectedly. That bug has already been fixed on the master branch. The next release will include the fix.

To repair the incomplete charging session run the following command:

```bash
docker-compose exec teslamate bin/teslamate rpc "import Ecto.Query; from(c in TeslaMate.Log.ChargingProcess, where: is_nil(c.end_date)) |> TeslaMate.Repo.all() |> Enum.map(&TeslaMate.Log.complete_charging_process/1)"
```
