### ISSUE TITLE
Laptop battery died and after starting it up again I have no data.  Need help

### ISSUE THREAD

**Issue by thouchin** [adriankumpf/teslamate#267]
Once I booted up the laptop again I went into a terminal and tried to start everything up again with docker-compose up.  I got some errors about not being able to bind to 0.0.0.0:3000 ect.  I tried rebooting and bringing container down and then up again. I also tried to start it all with a change to the YML (setting the ports to 4000 instead of 4000:4000)  And I finally got it working with a simple reboot (it seems the containers all start at boot time) but all my data is gone.  I only have 2 hours worth now.

One other thing... The setting in Teslamate GUI are all set bscl to default after all this.

Can anyone talk me through how to check the database and or restore the last month of data?  AM I just SOL?

**Comment by thouchin** [comment]
So know understand that the Docker containers were probably running in a different instance and when I opened a terminal and tried to bring the server down and then up it wasn't acting in the same instance so I wasnt actually bringing it down.  Then since it was still running it was still allocating the ports and hense the Bind errors I got.   I did try to list the running containers but it didn't understand what it was telling me.

So I'm still very unsure what my current situation is and what happened to all the data.  I don't know how to link to the container that is running the database.  I don't know how to check the connection to that datbase and why it seems I have created a new empty database now.

**Comment by ilkkao** [comment]
It depends how you have set up your docker volumes. If you don't have a db volume, the data might be still inside the old stopped db container if it's not deleted. This is not really a teslamate specific question. 

I personally recommend you buy a cheap VM from e.g. digital ocean and keep teslamate running there.
