### ISSUE TITLE
‘Energy used’ is null , display "N/A".

### ISSUE THREAD

**Issue by ArthurZangCN** [adriankumpf/teslamate#2713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the drive details panel, ‘Energy used’ is null , display "N/A".  In database , the efficiency is null in table car.

### Relevant log output

```shell
teslamate_1  | 2022-06-24 07:21:17.540 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-06-24 08:34:08.351 [info] GET /
teslamate_1  | 2022-06-24 08:34:08.358 [info] Sent 200 in 6ms
teslamate_1  | 2022-06-24 08:37:36.976 [info] GET /
teslamate_1  | 2022-06-24 08:37:36.984 [info] Sent 200 in 8ms
teslamate_1  | 2022-06-24 08:46:31.089 [info] GET /
teslamate_1  | 2022-06-24 08:46:31.095 [info] Sent 200 in 6ms
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by adriankumpf** [comment]
Is this a new installation? If so https://docs.teslamate.org/docs/faq#why-are-no-consumption-values-displayed-in-grafana explains why consumption values displayed

**Comment by ArthurZangCN** [comment]
> Is this a new installation? If so https://docs.teslamate.org/docs/faq#why-are-no-consumption-values-displayed-in-grafana explains why consumption values displayed

yes, this is a new installation .  so i wait for next Charging.
thank you!

**Comment by cker321** [comment]
> ArthurZangCN

你好 请问你的现在能正确显示能耗了么  我已经充了好几次了 现在还是显示不出来能耗

**Comment by ArthurZangCN** [comment]
> 



> > ArthurZangCN
> 
> 你好 请问你的现在能正确显示能耗了么 我已经充了好几次了 现在还是显示不出来能耗

我的显示出来了，你可以尝试一下有那么两三次别充满到100%，我目前总里程2900公里一共充电16次，期间有两次是冲到60%开了一趟然后又回来充满的，也是巧合，不确定和总里程有关系还是和充电方式有关系。你可以试一试。

**Comment by ArthurZangCN** [comment]
> > ArthurZangCN
> 
> 你好 请问你的现在能正确显示能耗了么 我已经充了好几次了 现在还是显示不出来能耗

另外，你也设置上你充电位置的费用（每度电多少钱，添加收藏点设置），可能也和这个有关系。

**Comment by gyrex** [comment]
I'm also having the same issue where if I go into 'Drives' and click on one of my drives, the Energy Used shows 'N/A'. I've read the info in the link above but I've charged the car at least 5 times now. Any ideas?
