### ISSUE TITLE
Phases count on charging detail not correct again

### ISSUE THREAD

**Issue by rgrae81** [adriankumpf/teslamate#2733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I found 2 Reports for this issue one from 2020 but they are closed ( #414 ) is the original Report.
There was a Bugix, but in the actual version 1.26.1 the Error exists again as you can see at my Screenshot.
16 amps on 2 phases can never be 11KW ;)
It was definitly using all 3 phases.
my car is a model y performance mig

### Relevant log output

```shell
no log
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/36889990/176996801-f3d5b4fc-bdcc-438a-b246-8f37c21d77bc.png)

### Type of installation

Docker

### Version

v1.26.1

**Comment by adriankumpf** [comment]
Fixed in [v1.27.0](https://github.com/adriankumpf/teslamate/releases/tag/v1.27.0)
