### ISSUE TITLE
When choosing drive or charging details, the chosen car doesn't show up. Must manually chose car to get graph.

### ISSUE THREAD

**Issue by spacecosmos** [adriankumpf/teslamate#274]
**Describe the bug**
I just added my parents Model 3 to my App and it shows up in TeslaMate. It records correctly and everything seems fine (except for showing firmware value #265). But when choosing drive or charging details, the chosen car doesn't show up. I must manually chose the car to get the correct graphs presented. 

**To Reproduce**
Steps to reproduce the behavior (_must have more than one car_):
1. Go to 'Drives'
2. Click on a 'trip date'
3. Car value says '2,1'
4. Must manually chose correct car from list under 'Car'

**Expected behavior**
Jump directly to correct car and correct drive details.

**Screenshots**
<img width="349" alt="Screenshot 2019-11-26 at 15 10 01" src="https://user-images.githubusercontent.com/55928670/69641795-1cd7d380-1061-11ea-9735-f325ec29512a.png">

<img width="422" alt="Screenshot 2019-11-26 at 15 11 23" src="https://user-images.githubusercontent.com/55928670/69641820-25300e80-1061-11ea-9ad4-8dacc1d28022.png">

<img width="444" alt="Screenshot 2019-11-26 at 15 12 29" src="https://user-images.githubusercontent.com/55928670/69641838-2b25ef80-1061-11ea-8c20-89bfb5939c17.png">

**Request**
It would be great to choose which car to be presented first. Now, I think it sorts the cars by name. When using TeslaMate from a phone, you have to scroll down and/or minimize the top car to get to the details of the different cars below. So any way to prioritise or select a primary car would be great.

**Operating environment**
 - OS: Docker Ubuntu (DigitalOcean)
 - Version: v1.13

**Comment by adriankumpf** [comment]
Thanks for the detailed report! I believe this used to work in the past and broke with a Grafana update.
