### ISSUE TITLE
tpms_pressure_fl column missing

### ISSUE THREAD

**Issue by koolsb** [adriankumpf/teslamate#2740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When viewing drives summary, the tire pressure graph shows no data and gives me the following error: 

db query error: pq: column "tpms_pressure_fl" does not exist

I've confirmed in the Postgres db that the column is indeed missing. I am running the latest version (1.26.1) and the latest tag from docker hub that was just installed this week. 

### Relevant log output

```shell
2022-07-07 14:10:01.159 UTC [2849] ERROR:  column "tpms_pressure_fl" does not exist at character 56
	    date AS "time",
2022-07-07 14:10:01.159 UTC [2849] STATEMENT:  SELECT
	    convert_tire_pressure(tpms_pressure_fl,'bar') AS tpms_pressure_front_left_bar,
	    convert_tire_pressure(tpms_pressure_fr,'bar') AS tpms_pressure_front_right_bar,
	    convert_tire_pressure(tpms_pressure_rl,'bar') AS tpms_pressure_rear_left_bar,
	    convert_tire_pressure(tpms_pressure_rr,'bar') AS tpms_pressure_rear_right_bar
	FROM
	    positions
	WHERE
	    car_id = 1 AND
	    date BETWEEN '2022-07-06T21:03:33Z' AND '2022-07-06T21:41:05Z' AND
	    tpms_pressure_fl is not null
	ORDER BY
	    date ASC
```

### Screenshots

<img width="868" alt="Screen Shot 2022-07-07 at 9 27 31 AM" src="https://user-images.githubusercontent.com/14332595/177798232-22612717-df46-4014-bac8-2983fddfb636.png">

### Type of installation

Docker

### Version

v1.26.1

**Comment by cwanja** [comment]
If your YML is on `latest`, that is why you are getting an error. You would need to be on `edge` to get all of the data coming in. It has not been formally released into "production". Or fork it and run a duplicate copy from your own repo.
