### ISSUE TITLE
Drive data missing in TeslaMate, but showing in TeslaFi

### ISSUE THREAD

**Issue by vadikcoma** [adriankumpf/teslamate#2743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm using TeslaMate for a week now, thank you for a great project!

I'm using it simultaneously with TeslaFi and few other apps just to see which app I like the best. 

I had multiple drives today, and the longest one is completely missing from Drives tab.
What is interesting, is that I can see this drive on the Trip dashboard map, but not in Trip dashboard stats that are below the map

On TeslaFi everything is displaying correctly

Is there a way to pull data from Tesla again? Or the only way is to sync everything with TeslaFi? I wouldn't like this option because I plan to leave TeslaFi and other apps and keep only Teslamate

### Relevant log output

```shell
teslamate_1  | 2022-07-11 21:05:15.814 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-07-11 21:05:15.831 car_id=1 [info] Connecting ...
teslamate_1  | 2022-07-11 21:11:53.738 [warning] Too many disconnects from strea                                                                                                        ming API
teslamate_1  | 2022-07-11 21:11:53.738 car_id=1 [info] Creating new connection …          

teslamate_1  | 2022-07-12 22:43:58.999 [error] ** (RuntimeError) Client Error: %                                                                                                        {"error_type" => "client_error", "msg_type" => "data:error", "tag" => "168912072                                                                                                        1236355", "value" => "Can't validate token. "}

teslamate_1  | 2022-07-11 22:26:45.654 [warning] TeslaApi.Error / %{"error" => "                                                                                                        {\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
```

### Type of installation

Docker

### Version

v.1.24.1

**Comment by adriankumpf** [comment]
The `(RuntimeError) Client Error: ` error shown in the logs was fixed in [v1.27.0](https://github.com/adriankumpf/teslamate/releases/tag/v1.27.0).

> Is there a way to pull data from Tesla again? Or the only way is to sync everything with TeslaFi? I wouldn't like this option because I plan to leave TeslaFi and other apps and keep only Teslamate

That's not possible. A full [import from TeslaFi](https://docs.teslamate.org/docs/import/teslafi) is only supported on a fresh installation.

**Comment by vadikcoma** [comment]
Thanks, I was on version 1.26.x. I just updated to 1.27.0

Could you please clarify what I did wrong and why my drive was not recorded properly? Was it my mistake or a bug?

**Comment by adriankumpf** [comment]
You didn't do anything wrong. Missing data is almost always caused by hiccups of the Tesla API. As far as I know TeslaFi and TeslaMate use different methods to retrieve data from the API. So one or the other can retrieve data under certain circumstances while the other cannot.

**Comment by vadikcoma** [comment]
I will keep comparing data in both.

I searched manual for "adding drive data manually", but I could only find an option to terminate or delete data.

I see this drive in the Timeline table, its just empty. I can add numbers manually, but I don't know how

![Timeline-Grafana](https://user-images.githubusercontent.com/15925904/179214620-bd359c1e-bab5-4344-b2e1-2016ec55ee87.png)

**Comment by pkuehnel** [comment]
Just try terminating the drive like described here: https://docs.teslamate.org/docs/maintenance/manually_fixing_data#terminate-a-drive-or-charge

**Comment by vadikcoma** [comment]
@pkuehnel I'm not sure what "termination" will do apart from deleting drive at all. My ultimate goal would be an ability to add missing data manually. As start and end points are there. And I know duration and length.

**Comment by pkuehnel** [comment]
Terminating does end the drive. There are two tables: drives and Positions. In the positions table ever x seconds the position and everything you see (elevation, temperature,...) is saved. And there is the drives table. One entry is created when you shift from P do D, so on ever start of a drive. When you finish the drive, the entry in the drives table is updated (set start address, end address, avg temperature, km driven,...). If during a drive the contact to Tesla crashes unhandled, the drive is not finished properly and not showing up in Grafana although all Positions are there. If you manually terminate the drive all missing values in the drive table are added, assuming the last known position is the end of the drive.

**Comment by vadikcoma** [comment]
Ah, actually terminating the drive will get back the data, I will try that, thank you!

**Comment by pkuehnel** [comment]
It won't really get it back, they always have been there but it makes them viable.

**Comment by myModelY** [comment]
hi. i missing also drives until 2 weeks. charges are ok, but drives all missing. can you help me?

**Comment by myModelY** [comment]
same by me. charges would save, but drives not until 2 weeks. import with console show this
docker compose exec teslamate bin/teslamate rpc     "TeslaMate.Repo.get!(TeslaMate.Log.Drive, 1945) |> TeslaMate.Log.close_drive()"
** (Postgrex.Error) ERROR 57014 (query_canceled) canceling statement due to user request
    lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3
    lib/teslamate/log.ex:292: TeslaMate.Log.close_drive/2
    (stdlib 3.17.2.1) erl_eval.erl:685: :erl_eval.do_apply/6

**Comment by dominikmeier** [comment]
Having the same issue. For me, random drives don't get closed. My suspicion is, that if whenever my docker server (Synology) is too busy it misses to finish the drive. If I look back in Teslamate I have a lot of unfinished drives. If I close them like discribed [here](https://docs.teslamate.org/docs/maintenance/manually_fixing_data/) they will show up with starting and end location.

Is there a DB command to close all unfinished drives?
There are too many to do it manually.
