### ISSUE TITLE
Drive Stats Dashboard

### ISSUE THREAD

**Issue by marcogabriel** [adriankumpf/teslamate#275]
I'd like to see a Drive Stats Dashboard, just like the Charging Stats Dashboard. Here are my ideas for the values/numbers I'd like to see. I haven't done any work, it's just an idea at the moment.

For example, the following numbers would be interesting:

* Daily driven range (median, not average, to be closer to the daily usage and take single long trips into account less)
* Daily used kWh (median, see above)
* Monthly driven range (average)
* Yearly driven range (average)
* Number of Trips
* kWh used
* Top Destinations
* Extrapolated Values of driven ranges within a month, a year, 2 years, 3 years, 4 years, 5 years (may be useful for people with leasing contracts)

Any additions or ideas?

**Comment by timguy99** [comment]
Same here. Is this the kind of thing where data already exists and its just a matter of configuring the right Grafana dashboard?

**Comment by marcogabriel** [comment]
As far as I can see, all data is already there and just needs to go into a proper grafana dashbard with some fancy queries :-).
