### ISSUE TITLE
Voltage, Phases and Current look strange

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#276]
**Describe the bug**
In the Charge Details view, voltage is 1 or 2, Phases does not show anything and Current is 0. This is a DC charging session. Is that correct?

**Screenshots**
![2019-11-27 17_23_48-Window](https://user-images.githubusercontent.com/8087682/69741431-51b85900-113b-11ea-9bd9-56426cb1743f.png)

**Operating environment (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Version v1.13

**Comment by adriankumpf** [comment]
Well, it's displayed as it is reported by the API. There are definitely some quirks. For example, some firmwares always report 2 phase charging regardless of whether that's really true or not.
