### ISSUE TITLE
"No data" after upgrade to 1.27.0

### ISSUE THREAD

**Issue by billerby** [adriankumpf/teslamate#2762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upgraded docker installation of teslamate from 1.26.1 to 1.27 after first adding an encryption key in the docker-compose.yml.

After upgrade all queries in Grafana seems to get a HTTP 403 Response code with "origin not allowed" as error message.

![image](https://user-images.githubusercontent.com/123237/179358601-8693a1e6-d1e6-40eb-b213-8ca9072a122c.png)

docker-compose logs reveals nothing. No errors or warnings only info with successful database migrations etc.

### Expected Behavior

Well, my data :)

### Relevant log output

```shell
mosquitto_1  | 1657980724: New connection from 172.18.0.3:57926 on port 1883.
mosquitto_1  | 1657980724: New client connected from 172.18.0.3:57926 as TESLAMATE_302E3333393 (p2, c1, k60).
teslamate_1  | 2022-07-16 16:12:00.222 [info] Migrations already up
teslamate_1  | 2022-07-16 16:12:03.185 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2022-07-16 16:12:03.185 [info] Version: 1.27.0
teslamate_1  | 2022-07-16 16:12:04.317 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (1085.827 ms)
teslamate_1  | 2022-07-16 16:12:04.317 [info] Refreshed api tokens
teslamate_1  | 2022-07-16 16:12:04.321 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-07-16 16:12:04.323 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2022-07-16 16:12:04.324 [info] Access TeslaMateWeb.Endpoint at http://teslamate.billerby.com
teslamate_1  | 2022-07-16 16:12:04.833 [info] Starting logger for 'MyTesla'
teslamate_1  | 2022-07-16 16:12:04.841 [info] MQTT connection has been established
teslamate_1  | 2022-07-16 16:12:05.227 car_id=1 [info] Start / :online
teslamate_1  | 2022-07-16 16:12:05.244 car_id=1 [info] Connecting ...
teslamate_1  | 2022-07-16 16:12:05.331 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (75.451 ms)
teslamate_1  | 2022-07-16 16:12:05.348 car_id=1 [info] Charging / SOC: 84% / Theplacetobe
teslamate_1  | 2022-07-16 16:12:05.348 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-07-16 16:12:06.864 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Wed, 16 Mar 2022 13:36:02 GMT.
teslamate_1  | 2022-07-16 16:12:08.873 [info] Tzdata has updated the release from 2021e to 2022a
grafana_1    | logger=http.server t=2022-07-16T13:59:17.1+0000 lvl=info msg="HTTP Server Listen" address=[::]:3000 protocol=http subUrl= socket=
grafana_1    | logger=ngalert t=2022-07-16T13:59:17.1+0000 lvl=info msg="warming cache for startup"
grafana_1    | logger=ngalert.multiorg.alertmanager t=2022-07-16T13:59:17.1+0000 lvl=info msg="starting MultiOrg Alertmanager"
grafana_1    | logger=grafanaStorageLogger t=2022-07-16T13:59:17.13+0000 lvl=info msg="storage starting"
[ec2-user@ip-172-26-7-85 ~]$
```

### Type of installation

Docker

### Version

v1.27.0

**Comment by jalkanen** [comment]
Same issue. Twiddling with different values of CHECK_ORIGIN does not seem to help at all (true, false, comma-separated list.)

**Comment by davidhewing** [comment]
Found a similar problem regarding grafina.  Looks like you need to add a line in the Apache configuration file in the same area as the Proxy directives.  It solved the problem for my configuration:

**ProxyPreserveHost On**

**Comment by rouji4** [comment]
Is there use nginx proxy? Grafana related configuration enable cross-origin settings

**Comment by kentfitch** [comment]
> ProxyPreserveHost

For nginx reverse proxy, after 1.27.0 upgrade, needed to change nginx config as described here: https://grafana.com/tutorials/run-grafana-behind-a-proxy/

**Comment by billerby** [comment]
Thanks! Solved by adding` ProxyPreserveHost On` to the apache virtual hosts config

**Comment by billerby** [comment]
A bit fast, turned out I already hade ProxyPreserveHost on in my virtual hosts config file...

**Comment by billerby** [comment]
Sorry, that was only for TeslaMate configuration, now also for grafana and it works!
