### ISSUE TITLE
Teslamate says I did not provide an encryption key (I did) and will not accept my tokens (generated using Tesla Auth)

### ISSUE THREAD

**Issue by krelltunez** [adriankumpf/teslamate#2763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I added an encryption key to docker-compose.yml, pulled the latest version, and started Teslamate.

There was an initial issue as the encryption key had a "$" which I didn't know would cause issues.  I fixed that by replacing "$" with "*" and it seemed to start up fine in Docker.

Upon navigating to Teslamate, I get the "No encryption key provided" message.  Is this perhaps because I initially had an issue, and I'm not using the auto-generated key, but my own?  Can I change the key or do I have to use the one that was generated?

And why won't it accept my Tesla tokens?

### Expected Behavior

See above.

### Steps To Reproduce

See above.

### Relevant log output

```shell
All I see in the logs that's relevant is the following:

teslamate_1  | 2022-07-16 11:00:22.915 [warning] Could not decrypt API tokens!
```

### Type of installation

Docker

### Version

v1.27

**Comment by natrlhy** [comment]
What was your fix?

**Comment by krelltunez** [comment]
I'm not sure.  I nuked my Teslamate containers and volumes and did a fresh install of 1.27.  Then I restored a backup of my database.  This caused me to lose 5 days of data (because I only run backups once per week), but I'm just glad to be back up and running.  I have everything tied into Home Assistant for automations and don't think I could live without that for very long!

**Comment by natrlhy** [comment]
I'm still having issues with the `ENCRYPTION_KEY=` line in the docker file. Is everyone encolsing it in "" or '' and using any fancy characters they like?

**Comment by krelltunez** [comment]
I did not, just a space after the = if I recall correctly.

**Comment by natrlhy** [comment]
So your entry in the yml file looks like:

`ENCRYPTION_KEY= some(@*$)(*#@$DSKSALKDJFKLstringhere`
?

**Comment by krelltunez** [comment]
I just got home and checked the file.  Turns out I lied, it's like this:

`environment:`
  - ENCRYPTION_KEY=stringoftextsymbolsandnumbers

I guess the space I was thinking of was around the "-"

SORRY!

**Comment by natrlhy** [comment]
Yep, thanks. I wonder if my KEY was just too long (64 characters). I created a new one (no space or quotes before/after it):

```
teslamate_1  | 2022-07-17 22:45:35.169 [warning] Could not decrypt API tokens!
...
teslamate_1  | 2022-07-17 22:45:35.242 car_id=1 [error] Error / not_signed_in
teslamate_1  | 2022-07-17 22:45:35.251 car_id=5 [error] Error / not_signed_in
teslamate_1  | 2022-07-17 22:45:35.265 [info] MQTT connection has been established
teslamate_1  | 2022-07-17 22:45:38.111 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Wed, 16 Mar 2022 13:36:02 GMT.
teslamate_1  | 2022-07-17 22:45:43.444 [info] Tzdata has updated the release from 2021e to 2022a
teslamate_1  | 2022-07-17 22:45:54.927 [info] GET /settings
teslamate_1  | 2022-07-17 22:45:54.960 [info] Sent 200 in 32ms
teslamate_1  | 2022-07-17 22:46:34.338 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
teslamate_1  | 2022-07-17 22:46:34.338 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_5_api_error, :fuse_blown}}
teslamate_1  | 2022-07-17 22:50:01.790 [info] GET /
teslamate_1  | 2022-07-17 22:50:01.795 [info] Sent 302 in 5ms
teslamate_1  | 2022-07-17 22:50:01.827 [info] GET /sign_in
teslamate_1  | 2022-07-17 22:50:01.838 [info] Sent 200 in 10ms
teslamate_1  | 2022-07-17 22:50:10.301 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (367.950 ms)
teslamate_1  | 2022-07-17 22:50:10.321 [info] Scheduling token refresh in 6 h
```
I'm guessing this means it took it and it shouldn't prompt for a key again?

**Comment by krelltunez** [comment]
That's similar to what happened to me even after my initial mistake of having an "$". It also wouldn't accept my tokens. I had to wipe it and do a clean install.

**Comment by Stokel** [comment]
I'm having the same problem. Just updated my docker instance and was told to add an encryption key.
I first added it to my env and inserted the variable in my docker-compose file. That did not work. I then added it directly in the docker-compose file, which also did not work. I then created my own simple password and put it in the docker-compose file and I'm still getting the "
 No encryption key provided"...
 
 So my install and data is hosed now?
 
 I should be able to get my database from my daily backup. Still not sure what the best way forward is.

**Comment by krelltunez** [comment]
Pretty simple (albeit annoying) to nuke your install and restore your last backup. I don't know why but it seems like if you do anything wrong with the encryption key the whole thing goes wonky.

**Comment by Stokel** [comment]
I just wanted to add, that I shouldn't debug something late at night...

I added the encryption key to my teslamate_db service instead of my teslamate..

Luckily I saved the first key that teslamate generated for me the first time. After inserting it at the correct position it seems to be up and working without needing to restore from backup.

**Comment by krelltunez** [comment]
Nice! I tried to find the key generated by Teslamate but I had no idea where it was. How did you find it?

**Comment by cwanja** [comment]
> Nice! I tried to find the key generated by Teslamate but I had no idea where it was. How did you find it?

It is in the container logs.

**Comment by krelltunez** [comment]
That's what I looked at but couldn't find it. I'm not very skilled at reading logs though!

**Comment by cwanja** [comment]
> That's what I looked at but couldn't find it. I'm not very skilled at reading logs though!

It's at the very top of the logs. In its own block. If it helps, send the logs to a text file and open in your preferred text reader application. 

`docker-compose logs teslamate > logs.txt`

**Comment by petebocken** [comment]
I added the auto-generated encryption key from the logs and then used [this site](https://tesla-info.com/tesla-token.php) to grab my tokens (I guess maybe I had to do this originally when I installed TeslaMate, I forgot). After that the Home Screen loads fine and my data is all there. I tested a reboot and I'm still logged in. So I'm good to go?
