### ISSUE TITLE
Grafana "Drives" and "Efficiency" dashboard giving "n is not a function" error

### ISSUE THREAD

**Issue by kylehendricks** [adriankumpf/teslamate#277]
**Describe the bug**
Going to the "Drives" or "Efficiency" Dashboard gives an error "n is not a function".

**To Reproduce**
1. Go to Drives dashbaord
2. See the red exclamation point in the top left corner of the "Drive" table.

**Expected behavior**
I expected to see a table showing my recent drives on the Drives dashboard and, on the Efficiency dashboard, a table showing my temperature efficiency.

**Screenshots**
![image](https://user-images.githubusercontent.com/981958/69754149-2a559200-1123-11ea-83df-1af1417dc84d.png)

**Operating environment (please complete the following information):**
 - OS: Arch/Docker
 - Version: v1.13

**Comment by spacecosmos** [comment]
Could you try to upgrade to **v1.13.1** and see if the problem persist? Could be the new Grafana version introduced on v1.13 which causes the error you are experiencing.

**Comment by kylehendricks** [comment]
That fixed it.  Thanks!
