### ISSUE TITLE
Drive Graph/Map correlation broken.

### ISSUE THREAD

**Issue by LelandSindt** [adriankumpf/teslamate#2770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As of 1.27.0 the correlation between Graphs and the Map are broken. Pre 1.27.0 in the `Drive Details` Dashboard when you mouse over a portion of the Graph a dot would show the corresponding position on the Map. 

### Expected Behavior

In the `Drive Details` Dashboard when you mouse over a portion of the Graph a dot should show the corresponding position on the Map. 

### Steps To Reproduce

1. open the `Drive Details` dashboard in grafana.
2. mouse over any one of the graphs.
3. ... you will see no correlating dot on the map.

### Relevant log output

```shell
.
```

### Type of installation

Manual

### Version

1.27.0

**Comment by LelandSindt** [comment]
https://github.com/adriankumpf/teslamate/discussions/2759

**Comment by ktsenvolt** [comment]
Same issue for me as well. That's a bug on 1.27.0.?

**Comment by kktoo21** [comment]
I also encountered this problem...

**Comment by snoof** [comment]
i have the same problem

**Comment by MrPaulAR** [comment]
Instead of "me too" posts there is a "subscribe" button on the top right of this page which will get you notifications.

Please do comment if you are adding some useful debug info for the developers to see/use.

**Comment by snbdot** [comment]
same.  docker installation.

**Comment by adriankumpf** [comment]
The timesyncing support of the [TrackMap plugin](https://github.com/pR0Ps/grafana-trackmap-panel) only works with the deprecated [`Graph (old)`](https://grafana.com/docs/grafana/latest/visualizations/graph-panel/) panel in Grafana. That panel is going to be removed in future Grafana releases. In Grafana 8 is still present but cannot be selected anymore when changing the panel type.

There is another trackmap plugin called [alexandra-trackmap-panel](https://github.com/alexandrainst/alexandra-trackmap-panel) but it does not support timesyncing either: https://github.com/alexandrainst/alexandra-trackmap-panel/issues/87

So we could either try downgrade to the old Graph panel or wait for a fix in one of the trackmap plugins.

**Comment by snbdot** [comment]
> The timesyncing support of the [TrackMap plugin](https://github.com/pR0Ps/grafana-trackmap-panel) only works with the deprecated [`Graph (old)`](https://grafana.com/docs/grafana/latest/visualizations/graph-panel/) panel in Grafana. That panel is going to be removed in future Grafana releases. In Grafana 8 is still present but cannot be selected anymore when changing the panel type.
> 
> There is another trackmap plugin called [alexandra-trackmap-panel](https://github.com/alexandrainst/alexandra-trackmap-panel) but it does not support timesyncing either: [alexandrainst/alexandra-trackmap-panel#87](https://github.com/alexandrainst/alexandra-trackmap-panel/issues/87)
> 
> So we could either try downgrade to the old Graph panel or wait for a fix in one of the trackmap plugins.

if downgrade to the old Graph panel can do: 
1. dot show the corresponding position on the Map
2. show tire pressure
definitely downgrade to the old Graph panel is GREAT ideal

**Comment by sargue** [comment]
So it seems that the reason to upgrade the Grafana panel is because it's going to be removed in a future version.

That's ok, but meanwhile it still works. So why not revert the change and wait until we are forced to upgrade it? That would give some time for the plugins to catch up.

**Comment by ktsenvolt** [comment]
I agree. But how?

**Comment by DrMichael** [comment]
Any chance, that the alexandra plugin will support timesyncing?

**Comment by LiamWangjy** [comment]
Well, any instructions for downgrading the Grafana? And what was the version back then?

**Comment by snbdot** [comment]
you can use docker-compose aim grafana 1.26> Well, any instructions for downgrading the Grafana? And what was the version back then?

**Comment by LiamWangjy** [comment]
> you can use docker-compose aim grafana 1.26> Well, any instructions for downgrading the Grafana? And what was the version back then?

Successfully downgraded, thanks

**Comment by snbdot** [comment]
only for docker install user.

1.backup your data
2.delete teslamate (4 container)
3.edit docker-compose.xml ( line grafana lestest to 1.26)
4.reinstall ( docker-compose up -d)
5.restore data
________________________________
发件人: LiamWangjy ***@***.***>
发送时间: Tuesday, October 18, 2022 1:05:41 PM
收件人: adriankumpf/teslamate ***@***.***>
抄送: snbdot ***@***.***>; Comment ***@***.***>
主题: Re: [adriankumpf/teslamate] Drive Graph/Map correlation broken. (Issue #2770)


you can use docker-compose aim grafana 1.26> Well, any instructions for downgrading the Grafana? And what was the version back then?

Successfully downgraded, thanks

―

**Comment by ironjing** [comment]
This bug has been fixed?

**Comment by djpalmis** [comment]
> This bug has been fixed?

Still waiting for a fix..

**Comment by CrowMash** [comment]
> > This bug has been fixed?
> 
> Still waiting for a fix..

It might take a while since the issue in plugin's repo is not very active https://github.com/pR0Ps/grafana-trackmap-panel/issues/67

**Comment by pesintta** [comment]
I've made a PR to the trackmap-panel plugin to support new hover event types of Grafana which seem to fix this issue for me: https://github.com/pR0Ps/grafana-trackmap-panel/pull/77

Hopefully the plugin gets updated and the update eventually lands into teslamate too.

**Comment by olexs** [comment]
> I've made a PR to the trackmap-panel plugin to support new hover event types of Grafana which seem to fix this issue for me: [pR0Ps/grafana-trackmap-panel#77](https://github.com/pR0Ps/grafana-trackmap-panel/pull/77)
> 
> Hopefully the plugin gets updated and the update eventually lands into teslamate too.

The PR has been merged, so the current master branch of the TrackMap plugin contains the fix. However, it hasn't yet been released as a new version to Grafana Labs.

Is it possible to install the plugin into Teslamate's Grafana directly from the master branch (or a defined commit hash) instead of the outdated released version?

**Comment by pR0Ps** [comment]
Hey all, @pesintta's fix for this issue has been released in [v2.1.3](https://github.com/pR0Ps/grafana-trackmap-panel/releases/tag/v2.1.3) of [pR0Ps/grafana-trackmap-panel](https://github.com/pR0Ps/grafana-trackmap-panel). Not sure when it'll be updated in the Grafana plugin repo but the signed release is currently available via an attachment on the GitHub release.

**Comment by ironjing** [comment]
@adriankumpf hi，look here. the bug has been fixed. May i trouble you update teslamate tag...

**Comment by adriankumpf** [comment]
hey, I updated the trackmap panel to [v2.1.3](https://github.com/pR0Ps/grafana-trackmap-panel/releases/tag/v2.1.3)  in 160d0a2fd44736e6108248a619c195f1c930c03e
