### ISSUE TITLE
Cannot start teslamate after update to 1.27.0

### ISSUE THREAD

**Issue by jat255** [adriankumpf/teslamate#2777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I thought perhaps I had the same issue as #2760, but clearing my tokens did not help, so I'm creating a separate issue here to track down what's going on.

My teslamate install is on an LXC container following the "bare metal" installation/upgrade instructions with a postgreSQL database on the same container, which I manage via a systemd service:

```
# cat /etc/systemd/system/teslamate.service
[Unit]
Description=TeslaMate
After=network.target
After=postgresql.service

[Service]
Type=simple
# User=username
# Group=groupname

Restart=on-failure
RestartSec=5

Environment="HOME=/usr/src/teslamate"
Environment="LANG=en_US.UTF-8"
Environment="LC_CTYPE=en_US.UTF-8"
Environment="TZ=America/Denver"
Environment="PORT=4000"
Environment="DATABASE_USER=teslamate"
Environment="DATABASE_PASS=XXXXXXXXXXXXXXXXXXXXXXX"
Environment="DATABASE_NAME=teslamate"
Environment="DATABASE_HOST=127.0.0.1"
#Environment="IMPORT_DIR=/teslafi-import"
Environment="DISABLE_MQTT=true"
Environment="ENCRYPTION_KEY=XXXXXXXXXXXXXXXXXXXX"

WorkingDirectory=/usr/src/teslamate

ExecStartPre=/usr/src/teslamate/_build/prod/rel/teslamate/bin/teslamate eval "TeslaMate.Release.migrate"
ExecStart=/usr/src/teslamate/_build/prod/rel/teslamate/bin/teslamate start
ExecStop=/usr/src/teslamate/_build/prod/rel/teslamate/bin/teslamate stop

[Install]
WantedBy=multi-user.target
```

My install is working on v1.26.1, but upon upgrading to v1.27.0 and then wiping tokens via `DELETE FROM tokens;`, I receive an error upon starting my systemd service related to the encrypted token migration (so likely coming from the `ExecStartPre` of the systemd unit). Indeed, if I run the `teslamate eval "TeslaMate.Release.migrate"` command, I get the same error as below.

### Expected Behavior

I would expect there to not be an error.

### Steps To Reproduce

Update to v1.27.0 following "bare metal" instructions, and then restart Teslamate

### Relevant log output

```shell
Jul 18 21:36:11 teslamate systemd[1]: Starting TeslaMate...
Jul 18 21:36:13 teslamate teslamate[1667]: ** (UndefinedFunctionError) function Code.ensure_loaded!/1 is undefined or private. Did you mean one of:
Jul 18 21:36:13 teslamate teslamate[1667]:       * ensure_compiled/1
Jul 18 21:36:13 teslamate teslamate[1667]:       * ensure_loaded/1
Jul 18 21:36:13 teslamate teslamate[1667]:       * ensure_loaded?/1
Jul 18 21:36:13 teslamate teslamate[1667]:     (elixir 1.11.3) Code.ensure_loaded!(TeslaMate.Vault)
Jul 18 21:36:13 teslamate teslamate[1667]:     _build/prod/rel/teslamate/lib/teslamate-1.27.0/priv/repo/migrations/20220123131732_encrypt_api_tokens.exs:4: (module)
Jul 18 21:36:13 teslamate teslamate[1667]:     (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
Jul 18 21:36:13 teslamate systemd[1]: teslamate.service: Control process exited, code=exited, status=1/FAILURE
Jul 18 21:36:13 teslamate systemd[1]: teslamate.service: Failed with result 'exit-code'.
Jul 18 21:36:13 teslamate systemd[1]: Failed to start TeslaMate.
```

### Type of installation

Manual

### Version

v1.27.0

**Comment by jat255** [comment]
I suppose I should add the following:

```
$ erl

Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Eshell V11.0
```

```
$ elixir --version
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
```

**Comment by ArthurZangCN** [comment]
login database docker and run `delete from tokens;`

**Comment by adriankumpf** [comment]
`Code.ensure_loaded!/1` was introduced in Elixir 1.12.0: https://hexdocs.pm/elixir/1.12/Code.html#ensure_loaded!/1

Try installing a newer version of Elixir. The current version is 1.13.4.

**Comment by jat255** [comment]
I got it all working after updating Elixir to 1.13. I also ran into #2771, and so installed the latest `master`, rather than v1.27.0, which resolved the EPMD issue. Thanks for your help!
