### ISSUE TITLE
Upgrade Process

### ISSUE THREAD

**Issue by timguy99** [adriankumpf/teslamate#279]
Hi all,

I'm not entirely familiar with Docker but I have everything running nicely with Docker so far.

I'm ready to upgrade to the latest and I see that the upgrade process specifies the following:
```
docker-compose pull

docker-compose up
```

Should the containers be stopped first or does the "pull" do that. Or is it not required?

And way more important, how does it migrate data that I have stored so far? Aren't these just new images overwritten over my current images? Wouldn't my entire DB image be overwritten therefore losing all data? I'm confused probably because I don't know how Docker works.

**Comment by henroFall** [comment]
It's so easy. Just go to the folder with your docker-compose folder and run
the commands just as you say.

don't forget the -d after the up... so

docker-compose up -d

Everything is automatic.

**Comment by timguy99** [comment]
Is this true even if I'm jumping a few versions? I'm confused how it would do this automatically considering there are likely DB table changes etc etc. I would think there would be migration scripts that need to be run or something. Or perhaps those are all contained within the docker images and run automatically??!!

I've been going over all the docker documentation but nothing really describes any of this that I have found yet.

**Comment by spacecosmos** [comment]
Yes, everything should be upgraded and taken care of.

This is what I do:
```
docker-compose down
docker-compose pull
docker-compose up -d
```
Make sure you wait a little while before trying to connect to the sites after the *up -d* command. I sometimes use it *without* the *-d* option, to make sure everything works as it should. It will then display all the updates and progress on the screen. 

After it has fully loaded and ready for connection, press *Ctrl+C* to cancel and stop the Docker Image. Then start it up again with the *-d* option.

**Comment by timguy99** [comment]
Thanks for the feedback guys. I think I finally figured out how docker toolbox (yes, I'm running this on a Win 7 box) works in some ways and especially where and how the filesystems are stored. So at least I can also make sure I have a backup in case I need to revert back to a good working system!!!

I'll close this for now because I'm pretty sure my question has been answered. I haven't done it yet but will within the next few days when I have time.

**Comment by timguy99** [comment]
Finally got around to doing an update and thanks to the instructions here all worked really well. I would update the docs based on @spacecosmos comment above. That is the best way to see that everything updated properly etc.
