### ISSUE TITLE
New installation not presenting any data

### ISSUE THREAD

**Issue by SpicaThor** [adriankumpf/teslamate#2803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'we used docker based installation. Logged in and saw basically nothing. After some investigation found out, that there's no data at all in the cars table in db.

### Expected Behavior

Car data will be gathered from Tesla after login and the system will work.

### Steps To Reproduce

1. Use docker installation from https://docs.teslamate.org/docs/installation/docker
2. Login with Tesla account

### Relevant log output

```shell
database_1 | 2022-07-22 20:48:12.876 UTC [107] ERROR: syntax error at or near "ORDER" at character 216
database_1 | 2022-07-22 20:48:12.876 UTC [107] STATEMENT: SELECT
database_1 | date AS "time",
database_1 | battery_level AS "Battery Level",
database_1 | usable_battery_level AS "Usable Battery Level"
database_1 | from positions
database_1 | WHERE date BETWEEN '2022-07-15T20:48:12.455Z' AND '2022-07-22T20:48:12.456Z' AND car_id =
database_1 | ORDER BY Time ASC
database_1 | ;
```

### Type of installation

Docker

### Version

v1.27.1

**Comment by cwanja** [comment]
It seems like you need to re-initialize the database. As you said it’s a new install, should lose no data. https://docs.teslamate.org/docs/maintenance/backup_restore

**Comment by adriankumpf** [comment]
Relevant previous question: https://github.com/adriankumpf/teslamate/discussions/1780

**Comment by SpicaThor** [comment]
I've tried re-initializing - no luck.
Restarting container while the car is awake produce following log:

```
2022-07-23 02:47:53.460 [info] Migrations already up
2022-07-23 02:47:55.414 [info] System Info: Erlang/OTP 24 (jit)
2022-07-23 02:47:55.414 [info] Version: 1.27.1
2022-07-23 02:47:55.951 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (447.270 ms)
2022-07-23 02:47:55.953 [info] Refreshed api tokens
2022-07-23 02:47:55.963 [info] Scheduling token refresh in 6 h
2022-07-23 02:47:55.969 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
2022-07-23 02:47:55.970 [info] Access TeslaMateWeb.Endpoint at http://localhost
2022-07-23 02:47:56.440 [info] GET /
2022-07-23 02:47:56.484 [info] Sent 200 in 44ms
2022-07-23 02:47:56.487 [info] MQTT connection has been established
```

**Comment by SpicaThor** [comment]
I've tried to reset the installation (a.k.a stop containers and remove all volumes). Then logged in from scratch. From logs it seems like teslamate don't even go to Tesla for the cars list...

**Comment by adriankumpf** [comment]
Is this a new car? Does the Tesla APP show the car?

Try querying the Tesla API directly. What does it return?

```curl
curl -H 'Authorization: Bearer $access_token' 'https://owner-api.teslamotors.com/api/1/vehicles'
```

**Comment by SpicaThor** [comment]
Hmm.. Although the car is one year old and definitely shows up in the Tesla app, this request returns empty list.

**Comment by SpicaThor** [comment]
Ok, I figured it out. Logged in with different account that has no cars in it. Forgot I have it. Gmail handling accounts with or without dots in it is handy for gmail, but may sometimes create issues with other services... 🤦‍♂️
