### ISSUE TITLE
Page not found 404 error

### ISSUE THREAD

**Issue by ktsenvolt** [adriankumpf/teslamate#2807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Page not found 404 error after a click on the ❄️ of Vampire Drain page.

### Expected Behavior

Unknown.

### Steps To Reproduce

1. Go to Vampire Drain on the dashboard
2. Click on the "SnowFlake"

### Relevant log output

```shell
n/a
```

### Screenshots

![snowflake](https://user-images.githubusercontent.com/80360674/180658990-1082b14f-f61a-4566-a53d-c76a0aef1baa.jpg)
![page not found](https://user-images.githubusercontent.com/80360674/180659009-5a9a02c7-6d44-4e2e-86f5-56d0d2268b10.jpg)
![temperature](https://user-images.githubusercontent.com/80360674/180659019-a5f80915-23db-43b6-86cf-2c7fc683f140.jpg)

### Type of installation

Docker

### Version

V 1.27.1

**Comment by adriankumpf** [comment]
https://github.com/adriankumpf/teslamate/issues/2411
