### ISSUE TITLE
Add to Charge Stats: Supercharger/Fast Chargers vs Standard Chargers Ratio

### ISSUE THREAD

**Issue by marcogabriel** [adriankumpf/teslamate#281]
It would be nice to see what percentage or part of charging is done by using Superchargers or even Fast Chargers and what part comes from Standard / Slow chargers as this is interesting for battery life estimation.

As a basis, the kw average of a charging session can be used to differentiate between fast and slow charging:

* Average Charging is > 25 kW => Fast/SuperCharger (like Tesla, IONITY or 40kW+ DC CCS Chargers)
* Average Charging is < 25 kW => Slow/StandardCharger (like the Wallbox or 230V Chargers)

Now calculate the percentage of Supercharging compared to all charging sessions and get a percentage. The lower, the better. 

Maybe this can be displayed as a Single Stat on Charging Stats Dashboard.

**Comment by adriankumpf** [comment]
To differentiate between chargers the columns `fast_charger_present`, `conn_charge_cable`, `fast_charger_brand` and `fast_charger_type` in the `charges` table might be useful as well.

**Comment by marcogabriel** [comment]
AFAIK, this is already implemented.
