### ISSUE TITLE
Skip login, Use refresh & access token

### ISSUE THREAD

**Issue by emazzotta** [adriankumpf/teslamate#282]
I just started all docker containers with the default settings as per the readme.

When browsing to http://localhost:4000/ I'm prompted for my user/password credentials, however I'd prefer entering my access token & refresh token manually (partially because I'm currently locked out of my Tesla account due to circumstances outside of my control).

How can I achieve this?

**Comment by adriankumpf** [comment]
There's no GUI for that. However, you can manually create an entry in the database table `tokens` with your access and refresh token.

**Comment by emazzotta** [comment]
Thanks for the fast response!

I actually tried creating the entry manually, however when browsing to http://localhost:4000/ I'm still redirected to http://localhost:4000/sign_in is this expected?

**Comment by emazzotta** [comment]
Nevermind, restarting the containers did the trick 👍
