### ISSUE TITLE
Ideal range listed as 999mi

### ISSUE THREAD

**Issue by holman** [adriankumpf/teslamate#284]
**Describe the bug**
Ever since install, my ideal range has been showing as 999mi. Which I mean, I get it... 1k mile range would definitely be *ideal*, but I don’t think it’s quiteeeee accurate, hah.

I’m on the current released Model S. Shows that way in both TeslaMate and in Grafana.

**Expected behavior**
Shouldn’t be 999mi.

**Relevant entries from the logs**
Happy to dig into the logs here, but sounds like it’s maybe something on initialization or something similar? Haven’t looked at the code at all, but point me in the right direction and I can dig into things.

**Operating environment (please complete the following information):**
Ubuntu.

**Comment by holman** [comment]
I see something about an “option code fiasco” mentioned in #143, but no real information beyond that.

**Comment by adriankumpf** [comment]
TeslaMate only makes visible what is reported by the API. This oddity has previously been seen by @cwanja. I wonder if a solution has been found in the meantime? You'll probably want to change the 'preferred range' on the settings page to 'rated' if you haven't already done so.

**Comment by cwanja** [comment]
I can re-poll the API when I get home, but when @adriankumpf introduced the option to change the preferred range via TeslaMate I never looked back. I tried to get Tesla on the hook "officially" stating that it is reporting correctly (_which I still feel it is not_), but the email correspondence stopped. Obliviously, they do not support the API and I can recognize that. The car **fully** functions even with the junk data reported.

**Comment by cwanja** [comment]
Looking at the API again, it is still reporting the "ideal_battery_range" at 999. 

- 2019 (Raven) Model S, built in May/2019
- Tesla version 2019.36.2.2 186de86

**Comment by adriankumpf** [comment]
Thanks @cwanja

**Comment by LanceSandino** [comment]
I have a 2021 (dec 2020 build) model X and it is saying 999 as well.
