### ISSUE TITLE
Driven Stat on Charges Grafana page

### ISSUE THREAD

**Issue by timguy99** [adriankumpf/teslamate#286]
Can someone explain the "Driven" stat column on the Charges page? I'm thinking it is attempting to show how much was "actually" driven since the last charge or something. But doesn't seem to be accurate. If I know what it is intending to show I can look into the details further.

**Comment by adriankumpf** [comment]
It's just like you thought, the column shows how much was driven since the last (**recorded**) charge. Or in other words it's the calculated difference between the odometer at the time of the the respective charge and the previous charge.

**Comment by timguy99** [comment]
Ok, I'll keep an eye on it and see if it makes sense. I may have been adding up something incorrectly so perhaps it is on point!! Sorry for asking dumb questions.
