### ISSUE TITLE
Cost price separator

### ISSUE THREAD

**Issue by bjarneabraham** [adriankumpf/teslamate#2864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When entering the cost for a charge, I'm not able to use comma as separator which is normal in Denmark.

### Relevant log output

```shell
I cannot save the cost value when entering it with a comma instead a dot
```

### Type of installation

Docker

### Version

v1.24.1

**Comment by Macrisu** [comment]
![comma_dot](https://user-images.githubusercontent.com/16325429/187267736-611149f5-9f8b-4d86-9a19-dfc72e2d1099.jpg)

iphone, latest IOS, cannot add cost, as it asks for a dot, but on the keyboard is comma and => error.

**Comment by DrMichael** [comment]
You could try to set the LOCALE for the teslamate service in docker-compose.yml. I have set LOCALE=DE and get commas accepted... (I think :-))

**Comment by bjarneabraham** [comment]
Changed the language of the application to Danish and now I can use commas.
