### ISSUE TITLE
In drive details, When the mouse moves in the axis, it will be positioned in the map. Why is it not updated to 1.27.1?

### ISSUE THREAD

**Issue by yeserson** [adriankumpf/teslamate#2866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In drive details, When the mouse moves in the axis, it will be positioned in the map. Why is it not updated to 1.27.1?

### Relevant log output

```shell
none
```

### Type of installation

Docker

### Version

1.27.1

**Comment by CrowMash** [comment]
Duplicate #2770
