### ISSUE TITLE
Incorrect 'kWh used' in 127/230V three-phase networks

### ISSUE THREAD

**Issue by rtega** [adriankumpf/teslamate#290]
**Describe the bug**
The formula on line https://github.com/adriankumpf/teslamate/blob/382a63de15dca5837acb807c8a2dc969b6a58889/priv/repo/migrations/20191026185642_calculate_charge_energy_used.exs#L81
```
c.charger_actual_current * c.charger_voltage * c.charger_phases / 1000.0
```
should be
```
c.charger_actual_current * c.charger_voltage * sqrt(c.charger_phases) / 1000.0
```
as per https://www.engineeringtoolbox.com/three-phase-electrical-d_888.html.

In any case it probably is incorrect. I charged yesterday evening. I measured 8.51 kWh on the Watt-counter for my tesla charging station. Teslamate tells me that for 8.48 kWh added charge, 15.44 kWh electricity was used. If I divide 15.44 kWh by sqrt(3) I get to 8.914 kWh which would be really close to what was measured.

**Comment by adriankumpf** [comment]
I'm not an expert on the subject but the phase to phase voltage is different from the phase to neutral voltage. E.g. in Europe the phase to phase voltage is 400V, which gives 230V phase to neutral voltage: `400/sqrt(3) = 230`. That is why the used formula works.

Of course, that doesn't explain the discrepancy you're seeing. I can think of a few causes of error:

- There was no stable internet connection at the charge location (missing data)
- There was an incorrectly configured 'phase correction' for the geo-fence at the charge location
- The API has (temporarily) reported wrong values

What's the reported 'energy used' for your other charges?

**Comment by rtega** [comment]
I just started using it now so I only have one charge. The technician who installed my wall box assured me that I don't have 400V, only 230V. 400V is only for industrial users. I'll see how my other charges are being reported and report back.

**Comment by rtega** [comment]
Well, now this is not so correct. After my second charge, I see the attached in charges:
![charges](https://user-images.githubusercontent.com/2451345/70414059-41687e00-1a59-11ea-96a7-8a59937919c2.png)
I started charging at 18:24 with SOC about 16% or something. My counter reads 56.64kWh.

**Comment by rtega** [comment]
In my teslamate output:


```
> 18:46:48.793 [info] GET /
> 18:46:48.871 [info] Sent 200 in 77ms
> 20:01:22.371 car_id=1 [warn] Error / upstream timeout
> 20:06:29.853 [error] Task #PID<0.11235.8> started from :"1" terminating
> ** (stop) exited in: GenServer.call(TeslaMate.Api, {:get_with_state, 30688981065359560}, 35000)
>     ** (EXIT) time out
>     (elixir) lib/gen_server.ex:1009: GenServer.call/3
>     (teslamate) lib/teslamate/vehicles/vehicle.ex:727: TeslaMate.Vehicles.Vehicle.fetch_with_reachable_assumption/2
>     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
>     (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
>     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Function: #Function<2.116134789/0 in TeslaMate.Vehicles.Vehicle.handle_event/4>
>     Args: []
> 20:07:00.794 car_id=1 [warn] Error / upstream timeout
> 20:07:36.955 car_id=1 [warn] Error / upstream timeout
> 20:08:20.209 car_id=1 [warn] Error / upstream timeout
> 20:08:56.183 car_id=1 [warn] Error / upstream timeout
> 20:09:20.447 car_id=1 [info] Start / :online
> 20:09:20.556 [info] Querying location for elevation takes longer than 100ms ...
> 20:09:23.400 car_id=1 [info] Charging / SOC: 34% / Home
> 20:10:51.767 car_id=1 [warn] Error / upstream timeout
> 20:11:27.856 car_id=1 [warn] Error / upstream timeout
> 20:52:28.122 [info] GET /geo-fences/new
> 
```

**Comment by rtega** [comment]
Another charge and again wildly off the mark. I measured 40.04 kWh. It says used 70.41 kWh.

![charge3](https://user-images.githubusercontent.com/2451345/70689978-eaabb000-1cb5-11ea-8855-2cedb13c31f0.png)

**Comment by adriankumpf** [comment]
> In my teslamate output:
> 
> ...

It looks like the internet connection wasn't very good at the time/location. The estimation of the kWh used relies on a stable connection. So that could be the issue.

I'll need your charge data and the application logs at the time of your last charge(s) to find out more. To export the data run these commands (while the database container is running):

```bash
docker-compose exec db psql teslamate teslamate -c \
   "COPY (select * from charges) TO STDOUT WITH CSV" > charges.csv && \
docker-compose exec db psql teslamate teslamate -c \
   "COPY (select * from charging_processes) TO STDOUT WITH CSV" > charging_processes.csv
```

**Comment by rtega** [comment]
Hi, the charge yesterday was with a perfect connection so that should not have been an issue. The second charge indeed had an interrupted internet connection twice which you see in the charges.

[charges.zip](https://github.com/adriankumpf/teslamate/files/3956207/charges.zip)

**Comment by adriankumpf** [comment]
Something is wrong with the reported data. It doesn't add up. For example, your car reports 
`218V * 19A * 3 Phases = 12426W` but it effectively charges with 7 kW. You can see for yourself in the Charge Details. If the input values are incorrect, the result can of course not be correct. I guess there's nothing we can do about that, unfortunately.

**Comment by rtega** [comment]
Hi Adrian, that's why I think the used formula is incorrect. 218V * 19A * sqrt(3) phases = 7174.
Also the measured charge (40.04) almost exactly matches the reported charge (70.41) / sqrt(3) = 40.65.

I'm quite sure that it charges at 19A (that's reported on the screen in my car) and I'm also sure that it's three phases @ 220 V. 

Do you have anybody else charging at home with a wall charger at 3 phases?

**Comment by adriankumpf** [comment]
> Do you have anybody else charging at home with a wall charger at 3 phases?

Well, I am ;) And I know of others TM users who also have a 3-phase charger at home. And the estimates are accurate in all of these cases (some Model 3 owners need to manually enable the phase correction). If anyone with more expertise on this subject could explain the measurements you are seeing, I'd like to know.

**Comment by rtega** [comment]
At what wattage and voltage are you charging?

**Comment by adriankumpf** [comment]
Looking into it, Belgium (and other countries) have 127/230V three-phase networks. You're effectively charging with 127V and that's why dividing by `sqrt(3)` gives you the correct result. To me, it feels like the car should report 127V instead of 220V then? But there's probably a good reason for that ...

I don't have the time to implement a country-specific workaround at the moment. You can, however, customize the dashboard and do the calculation yourself:

  1.  sign in with the default user admin (password is admin)
  2. Click edit on the table and update the SQL query
  3. Save the dashboard as JSON and import it as a new dashboard

**Comment by rtega** [comment]
Mmm, indeed but this is only going to work for my home set up. I would probably have to code it in https://github.com/adriankumpf/teslamate/blob/382a63de15dca5837acb807c8a2dc969b6a58889/priv/repo/migrations/20191026185642_calculate_charge_energy_used.exs#L81

Should there not be a way to recover from bad internet connections during charging?

**Comment by adriankumpf** [comment]
Good news: I had the idea for an automatic and generic phase/voltage correction mechanism. I used your charge data to test it and It turned out to work surprisingly well. It'll ship with the next release.

**Comment by rtega** [comment]
Thanks!
