### ISSUE TITLE
Percentage drive on AP

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#291]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Not sure if the API reports this or not while driving, but curious if there is a way to visualize, track and or review the percentage of an individual drive and overall drive history drive on Autopilot. If possible, differentiate between Navigate on Autopilot. 

Think it would skew the graphs in drive details to have a 0 or 1 trending line in any of the individual drives, but maybe in the overall drives table each drive has a percentage (if available). 

**Describe alternatives you've considered**
N/A

**Additional context**
If not possible, close the "issue" :)

**Comment by adriankumpf** [comment]
I would be interested in this information as well, but unfortunately it is not available through the API.
