### ISSUE TITLE
Database backup yields 0 byte file

### ISSUE THREAD

**Issue by fligi7** [adriankumpf/teslamate#2949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Attempting to perform a database backup per the [docs ](https://docs.teslamate.org/docs/maintenance/backup_restore/) yields a 0 byte file:

`$ docker-compose exec -T database pg_dump -U teslamate teslamate > teslamate.bak`

I've also tried adding a `-d` parameter like the below mentioned in the thread [here](https://github.com/adriankumpf/teslamate/issues/2405) to no avail:

`$ docker-compose exec -T database pg_dump -U teslamate -d teslamate > teslamate.bak`

I installed using the installation [docs](https://docs.teslamate.org/docs/installation/docker), only changing the passwords as denoted, and left the database names as they existed.

Perhaps the database or name(s) are different for my installation? (See Screenshot)

### Expected Behavior

Expected behavior would be a non-zero byte file with the database backup.

### Steps To Reproduce

`$ docker-compose exec -T database pg_dump -U teslamate teslamate > teslamate.bak`

### Relevant log output

```shell
Docker PS shows the following for the running containers (see Screenshots).
```

### Screenshots

![image](https://user-images.githubusercontent.com/7141181/196048099-2c042823-ece4-466f-97be-8830db9d1b9f.png)

### Type of installation

Docker

### Version

Uncertain, installed a couple weeks ago

**Comment by ktsenvolt** [comment]
Are you on the correct path?
This is my backup setup:

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
now=`date +"%A"`
cd /home/pi/tmbackup
sudo /usr/local/bin/docker-compose exec -T database pg_dump -U teslamate teslamate > /home/pi/tmbackup/teslamate.bck_${now}
rclone copy --max-age 24h /home/pi/tmbackup --include 'teslamate.*' gdrive:TeslaMate

**Comment by fligi7** [comment]
Correct path for what?

**Comment by ktsenvolt** [comment]
The first step is to find the file 'docker-compose.yml'
then run 'sudo docker-compose exec -T database pg_dump -U teslamate teslamate >teslamate.bck'

**Comment by fligi7** [comment]
I'm running this within the directory containing the docker-compose.yml file.

**Comment by fligi7** [comment]
Here is the output of the command with the `--verbose` option:

```
$ sudo docker-compose --verbose exec -T database pg_dump -U teslamate teslamate > teslamate.bak
compose.config.config.find: Using configuration files: ./docker-compose.yml
compose.cli.docker_client.get_client: docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
compose.cli.docker_client.get_client: Docker base_url: http+docker://localhost
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('downloads_default')
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- ('downloads_teslamate-db')
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- ('downloads_teslamate-grafana-data')
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- ('downloads_mosquitto-conf')
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- ('downloads_mosquitto-data')
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=downloads', 'com.docker.compose.service=database', 'com.docker.compose.oneoff=False', 'com.docker.compose.container-number=1']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=downloads', 'com.docker.compose.service=database', 'com.docker.compose.oneoff=False', 'com.docker.compose.container-number=1']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
```

**Comment by fligi7** [comment]
Never mind, figured it out. I was running it from a directory with the docker-compose.yml file in it but not the original directory from which I deployed the file with docker-compose. Lesson learned.
