### ISSUE TITLE
Missing a drive immediately after charging

### ISSUE THREAD

**Issue by timguy99** [adriankumpf/teslamate#297]
I'm curious how TeslaMate can miss a drive immediately after charging at a supercharger? Obviously TeslaMate is continuously polling during the charge right? How would it miss the drive immediately following?

Can / should I look for something in the logs?

**Comment by adriankumpf** [comment]
Yes, please provide the application logs.

**Comment by timguy99** [comment]
Yeah ok to close this. I never got around to getting you the logs. If it happens again and I get the logs will reopen this.
