### ISSUE TITLE
Trend Lines on Degradation Chart

### ISSUE THREAD

**Issue by rickbassham** [adriankumpf/teslamate#299]
Anyone have any ideas on how to easily add trend lines to the degradation chart? It's been a while since I've worked with Grafana.

Thanks, and great project!

**Comment by marcogabriel** [comment]
There is a blog article here https://grafana.com/blog/2019/02/14/visualizing-the-future-with-grafana/

You search for something like a moving average function. AFAIK; Grafana just shows the values, but does not have anything like a moving_average function. InfluxDB can do that, postgres can do it aswell (https://www.compose.com/articles/metrics-maven-calculating-a-moving-average-in-postgresql/) and Grafana can be used to show it.
