### ISSUE TITLE
Ø Speed - Erroneous Value in Efficiency Dashboard

### ISSUE THREAD

**Issue by khorton** [adriankumpf/teslamate#301]
**Describe the bug**
The entry for 40°F on my Efficiency Dashboard shows 283 miles with an Ø Speed of 91 mph.  The Ø Speed value must be wrong, as the highest speed limit in this area is 70 mph, and I typically travel 75 mph on the highway.  The speed on secondary roads is slower.  How are these average values calculated?

**Screenshots**
<img width="1185" alt="Screen Shot 2019-12-10 at 8 37 17 PM" src="https://user-images.githubusercontent.com/77668/70592055-3a428c80-1b8d-11ea-8f7f-3769438851a3.png">

**Operating environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version: v1.13.2 running in Docker

**Comment by adriankumpf** [comment]
Good catch! The speed values weren't converted from kmh to mph.
