### ISSUE TITLE
Vampire Drain way higher since 2019.36.2.4

### ISSUE THREAD

**Issue by timguy99** [adriankumpf/teslamate#303]
I don't think this is a bug with TeslaMate but anyone else notice that the car will not go to sleep since the 2019.36.2.4 update? Since that update my Vampire Drain Standbye %age has been sitting at 0%. NOT GOOD. And no, Sentry mode is not turned on.

**Comment by chilman408** [comment]
No, I'm on the same version but I haven't notice much difference.

**Comment by nottheedge** [comment]
As reported by Teslamate the car seems to be more in state online with less at sleep. But it doesn’t consume that much... Not sure if this is caused by new firmware or if the state is not correctly recognised by Teslamate

**Comment by timguy99** [comment]
Its definitely the car that is NOT going to sleep as confirmed by Vampire Drain. It would normally be showing high 80's %age to 90's %age of standby. Now it is showing 0 and draining a LOT more. Easy to see just by looking at the app the next morning as well. I look at it all the time so I know when something is out of whack.

What is odd is there was one time period where it seemed to go to sleep for a day but now back to not sleeping. I also just updated to 2019.40.2.1 just yesterday so will see if that makes a difference but so far I don't think it has.

I may have to report this to Tesla to see if they have anything to say about it.

**Comment by netkruzer** [comment]
I've noticed the same. My online state is way higher than it used to be since 2010.36.2.4. Since Nov 24, my ONLINE time is 81% of the time. I don't have Sentry on during those times.

Just updated Teslamate to newest version from v1.12 today to v1.13.2. Hope that will fix it. Vampire drain is definitely there.

**Comment by chilman408** [comment]
I really don't see any appreciable difference.  Attached are data from my M3 from the "States" panel for 18Nov to 22Nov and 05Dec to 09Dec.  I received the 36.2.4 update on 04Dec and upgraded to version 40 on 10Dec (attached "Upgrades" panel as well.
![Screen Shot 2019-12-16 at 8 59 09 AM](https://user-images.githubusercontent.com/44660877/70927004-06c78e00-1fe3-11ea-9a93-c867ed86ada5.png)
![Screen Shot 2019-12-16 at 9 00 03 AM](https://user-images.githubusercontent.com/44660877/70927009-0a5b1500-1fe3-11ea-9df4-9255e357d305.png)
![Screen Shot 2019-12-16 at 9 00 41 AM](https://user-images.githubusercontent.com/44660877/70927014-0c24d880-1fe3-11ea-9fa8-a636b4bdd892.png)

**Comment by timguy99** [comment]
Some are just lucky it seems while others like myself are screwed. My graph has no green in it for a week now. Actually there was one day it went green for maybe half a day and that is it. Certainly some sort of issue but again I don't think it is with TeslaMate.

**Comment by timguy99** [comment]
Ok, I noticed in geofences that "enable sleep mode" was enabled for my home location. I thought, maybe this checkbox was backwards so I shut that off and now back at the Teslamate screen on port 4000 the "try to sleep" button is greyed out. Although I found you can still click it. When I do so it reports that "sleep mode is disabled at current location".

Why is this? Why would any location be set for disabled sleep mode? Could this be breaking something? Again doesn't seem to be because the car is still not sleeping at just about any location.

**Comment by netkruzer** [comment]
Newest update to Teslamate 1.13.2 seemed to allow sleep again for me. I also unchecked "Vehicle must be locked". I'm now on firmware 2019.40.2.1

![Screen Shot 2019-12-17 at 8 52 05 AM](https://user-images.githubusercontent.com/7841302/71016800-8cfad780-20aa-11ea-944d-999099ed3955.png)

Bug fixed itself?

**Comment by timguy99** [comment]
Unfortunately didn't help me. I did the same thing. Updated to 1.13.2 and also unchecked "Vehicle must be locked". No difference. I "had" a service request into Tesla. They unfortunately don't know what they are talking about. They tried to tell me that 30-50km range loss overnight (like a 12 hours period) is NORMAL and that if it happened after an update it is because they are making the car more efficient. Obviously they don't have a clue what they are talking about. They also cancelled my service request and I've been going back and forth with them via text. I told them I can provide data to show they can't possibly be correct.

**Comment by timguy99** [comment]
Ahhh, finally got around to "rebooting" the car. Seems like that did the trick!!!! I will still have to educate the Tesla technicians because they are COMPLETELY out to lunch with this.

Last 30 days. You can see a sliver of green at the far right.

![Screen Shot 2019-12-18 at 9 08 25 PM](https://user-images.githubusercontent.com/44981994/71138794-93886c80-21da-11ea-8a5c-d1af633c25f5.png)

**Comment by adriankumpf** [comment]
I can assure you that those random wake-ups were/are not caused by TeslaMate. It cannot and does not wake up the car. The latest (vehicle) software versions seem to have caused those problems. But the recent updates should've solved the issue.
