### ISSUE TITLE
bug htpasswd grafana

### ISSUE THREAD

**Issue by SiNaPsEr0x** [adriankumpf/teslamate#3054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When it is configured with traefik the authentication is requested on the home but not on /grafana

I have already followed all the steps and everything works -> https://docs.teslamate.org/docs/guides/traefik

But authentication if I go directly to the url: mioteslamate.domain.net/grafana doesn't ask me for any htpasswd authentication

### Relevant log output

```shell
teslamate_1  | 2023-01-10 13:05:51.788 [info] Migrations already up
teslamate_1  | 2023-01-10 13:05:55.371 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2023-01-10 13:05:55.371 [info] Version: 1.27.1
teslamate_1  | 2023-01-10 13:05:56.355 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (498.528 ms)
teslamate_1  | 2023-01-10 13:05:56.355 [info] Refreshed api tokens
teslamate_1  | 2023-01-10 13:05:56.361 [info] Scheduling token refresh in 6 h
teslamate_1  | 2023-01-10 13:05:56.363 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2023-01-10 13:05:56.367 [info] Access TeslaMateWeb.Endpoint at http://tomcat.anondns.net
teslamate_1  | 2023-01-10 13:05:57.097 [info] Starting logger for 'Kyra'
teslamate_1  | 2023-01-10 13:05:57.217 [info] MQTT connection has been established
teslamate_1  | 2023-01-10 13:05:57.641 car_id=1 [info] Start / :asleep
teslamate_1  | 2023-01-10 13:06:09.125 [info] GET /
teslamate_1  | 2023-01-10 13:06:09.227 [info] Sent 200 in 101ms
teslamate_1  | 2023-01-10 13:18:15.358 [info] GET /
teslamate_1  | 2023-01-10 13:18:15.529 [info] Sent 200 in 170ms
teslamate_1  | 2023-01-10 13:18:17.926 [info] GET /settings
teslamate_1  | 2023-01-10 13:18:18.104 [info] Sent 200 in 177ms
```

### Type of installation

Docker

### Version

1.27.1

**Comment by dyxyl** [comment]
That seems to be working as documented:

- The TeslaMate service is protected by HTTP Basic Authentication
- Grafana is configured to require a login

The "login" is Grafana's own authentication, not HTTP Basic Authentication.

**Comment by SiNaPsEr0x** [comment]
Is it possible to add this other layer to it? Since via docker is not constantly updated it would be safer

**Comment by dyxyl** [comment]
Yes, it should be possible, but I don't know about traefik.  I do it with Apache similar to how Grafana document it: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/
