### ISSUE TITLE
Suggestion - Manual Software Update entry/pull

### ISSUE THREAD

**Issue by drklain** [adriankumpf/teslamate#306]
My car updated software while Teslamate was offline for some reason.  As a result, it shows previous software version for the car and I see no way to force it to check for new software and believe it will show the incorrect software version until the next software update takes place.  Any way to create an option to manually update the software?

**Comment by timguy99** [comment]
I've gone through 2 software updates since installing TeslaMate and it has failed to pickup both of them.

**Comment by adriankumpf** [comment]
I assume you're referring to the Overview Dashboard which display the previous software version? The web interface will always display the currently installed version. I would recommend reading the version from there if the logger did not notice the installation of an update.

**Comment by timguy99** [comment]
Yeah, it is correct there but is there a way to debug why it doesn't update in the Overview Dashboard. I'm finding other stuff is not updating there either like current temp etc. Some do, some don't.

**Comment by adriankumpf** [comment]
The overview dashboard was added later, although Grafana is actually intended for historical data. It can only display data that is stored in the database. The web interface on the other hand always shows the current data.

After logging in with the default admin user you can debug the dashboard e.g. by editing SQL queries.

**Comment by timguy99** [comment]
I'll take a look there and do some debugging when I get a chance. However, isn't the interface updating the DB with latest internal car temp etc? It seemed to show that on the Overview page up to just recently.
