### ISSUE TITLE
Disconnect between States and Drives

### ISSUE THREAD

**Issue by khorton** [adriankumpf/teslamate#308]
**Describe the bug**
I stopped at our mailbox on the way home to check the mail, and note that the subsequent short drive from the mailbox to home is not shown in the Drives dashboard, but it does appear in the States dashboard.  Why should these two dashboards be inconsistent?

**Relevant entries from the logs**
_You **have to** provide the logs of the teslamate container / application unless the bug is limited to Grafana only. To fetch the logs of the teslamte container run the following command:_ `docker-compose logs teslamate`

```
teslamate_1  | 11:33:54.613 [info] Sent 200 in 2ms
teslamate_1  | 17:28:19.946 [info] GET /
teslamate_1  | 17:28:19.949 [info] Sent 200 in 2ms
teslamate_1  | 17:28:22.827 [info] GET /
teslamate_1  | 17:28:22.829 [info] Sent 200 in 1ms
teslamate_1  | 17:28:24.039 car_id=1 [info] Start / :online
teslamate_1  | 17:30:41.756 [info] GET /
teslamate_1  | 17:30:41.758 [info] Sent 200 in 2ms
teslamate_1  | 17:33:13.950 [info] GET /
teslamate_1  | 17:33:13.953 [info] Sent 200 in 2ms
teslamate_1  | 17:33:17.135 car_id=1 [info] Driving / Start
teslamate_1  | 17:40:09.596 car_id=1 [info] Driving / Ended / 6 km – 7 min
teslamate_1  | 17:40:09.596 car_id=1 [info] Start / :online
teslamate_1  | 17:41:42.130 car_id=1 [info] Driving / Start
teslamate_1  | 17:42:02.602 [info] GET /
teslamate_1  | 17:42:02.605 [info] Sent 200 in 2ms
teslamate_1  | 17:42:49.536 car_id=1 [warn] Vehicle went offline while driving
teslamate_1  | 17:42:54.956 car_id=1 [info] Vehicle is back online
teslamate_1  | 17:42:56.664 car_id=1 [info] Driving / Ended / 0 km – 1 min
teslamate_1  | 17:42:56.664 car_id=1 [info] Start / :online
teslamate_1  | 17:43:54.771 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 17:43:54.772 car_id=1 [warn] Error / upstream timeout
teslamate_1  | 17:53:47.705 car_id=1 [info] Suspending logging
```

**Screenshots**

Last drive in Drives is from Work to our mailbox.  The subsequent drive from the mailbox to Home is not shown:
<img width="508" alt="Screen Shot 2019-12-13 at 8 45 40 PM" src="https://user-images.githubusercontent.com/77668/70843634-5858f880-1dea-11ea-806f-5238cc5f852a.png">

States shows both drives:
<img width="1199" alt="Screen Shot 2019-12-13 at 8 45 06 PM" src="https://user-images.githubusercontent.com/77668/70843643-81798900-1dea-11ea-952c-b5cc217aef36.png">

**Operating environment (please complete the following information):**
 - OS: Ubuntu 19.10 via Docker
 - Version: v1.13.2

**Comment by adriankumpf** [comment]
The drive dashboard only displays drives longer than one minute. I will consider removing this condition.

**Comment by khorton** [comment]
Thanks for the explanation.  I did not realize that short drives were not included in the Drive Dashboard by design.
