### ISSUE TITLE
Paypal donation link in German by default

### ISSUE THREAD

**Issue by abienvenu** [adriankumpf/teslamate#309]
Hello,

When I click on the "Donate with Paypal" button from https://github.com/adriankumpf/teslamate I am redirected to a Paypal page written in German. Hopefully there is a link at the bottom right to switch from "Deutsch" to "English".

I think the Paypal donation link should lead to a page in the same language as the origin page (English).

My browser is Firefox 71.0, my preferred locales are "fr" then "en", but the problem persists even if "en" is set a my first preferred locale.

![paypal](https://user-images.githubusercontent.com/4340135/70851197-9a3d7980-1e92-11ea-9fd8-7dbf8d8abdc9.png)

**Comment by adriankumpf** [comment]
Thank you so much for pointing that out! I assumed that PayPal would use the preferred language based on the browser settings. I have now configured the country in addition to the preferred language, so hopefully English will now be used by default.

**Comment by abienvenu** [comment]
Perfect, now the displayed language is the one I configure in my Paypal account.
