### ISSUE TITLE
All the URLs in the 'Dashboards' menu are absolute pathed.

### ISSUE THREAD

**Issue by Slyke** [adriankumpf/teslamate#3096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running on a Synology NAS inside Docker

My URL is: http://10.1.2.3:8888/admin/index.php?carid=2

All the URLs in the Dashboard menu (pointing to Grafana) are set to raspberry. Eg: http://raspberry:3000/d/Mlc06BiRk/Akku%20Trips

Potentially related issue: https://github.com/adriankumpf/teslamate/issues/2273

### Expected Behavior

URL should use my current domain: 10.1.2.3 (or whatever it is)

### Steps To Reproduce

1. Setup in docker.
2. Setup your credentials
3. Mouse over the 'Dashboard' menu.
4. Before clicking on a link, take note of the URL, then click.
5. Connection refused.

### Relevant log output

```shell
Not required
```

### Screenshots

![image](https://user-images.githubusercontent.com/6442613/215459976-233919c5-c4d4-4cd5-ae42-f20b452fdddd.png)

### Type of installation

Docker

### Version

v1.54.10

**Comment by cwanja** [comment]
I think you are looking for this project? https://github.com/bassmaster187/TeslaLogger

**Comment by Slyke** [comment]
Yes, sorry!
