### ISSUE TITLE
Disable polling

### ISSUE THREAD

**Issue by kinteseay** [adriankumpf/teslamate#311]
I recently added another vehicle to my account and am getting inconsistent results in sleeping.  Is there a way to disable polling on an individual vehicle?  I would like to stop polling so I can troubleshoot but don't want to stop polling on my other vehicles.

**Comment by adriankumpf** [comment]
This is not directly possible. As a workaround, you could set a really high value for "Time to Try Sleeping". During this time the polling is halted.

**Comment by kinteseay** [comment]
Okay.  Thank you

**Comment by bahree** [comment]
> I recently added another vehicle to my account

Sorry I had a question, how did you add the 2nd vehicle? Once added to your Tesla account, does it automatically show up here on Teslamate when it polls?

Thanks.

**Comment by kinteseay** [comment]
Yes, it will show up automatically
