### ISSUE TITLE
Access to MQTT topics with Docker (advanced) setup

### ISSUE THREAD

**Issue by mboerma** [adriankumpf/teslamate#312]
I'm a noob when it comes to containers and networking. I easily got Teslamate started using the advanced setup on Ubuntu x86 18.x Now I would like to access the MQTT topic for teslamate from another machine in my home network. Teslamate also runs locally. 

How can I do this?

**Comment by denverquane** [comment]
I didn't encounter any problems when just using the IP of the broker's host machine (192.168.1.8 in my network), and the default port of 1883. The docker-compose.yml of this teslamate project exposes this port on the host machine by default. Then the topics resemble those described in the README of this project, e.g: `teslamate/cars/1/battery_level` (assuming car # 1). 

Probably depends on the MQTT library you use, if any, but the IP:PORT and topics should be the important bits. In my case, I'm using [MQTT.js](https://github.com/mqttjs/MQTT.js).

Hope this helps!

**Comment by mboerma** [comment]
Wonderful. That worked. Adding the ports to the yml file. Not sure that is a wise thing without setting a username and password and some ssh because now MQTT is exposed via the proxy to the internet. It did the trick.

Thanks!
