### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by Apisathan** [adriankumpf/teslamate#3120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have been out driving for about 3~ hours ago, went to check if it was logged, found out it wasn't.

The original battery procentage is still there, and it says the state of the car has been asleep for 1 day now.

### Relevant log output

```shell
GET https://owner-api.teslamotors.com/api/1/vehicles/[removed]-> error: "non-existing domain" (8007.344 ms)
```

### Type of installation

Docker

### Version

v1.27.2

**Comment by cwanja** [comment]
Seems like a network issue and not TeslaMate related. Can the device hosting TeslaMate access the internet?

**Comment by Apisathan** [comment]
Yes i just pinged google, no packet loss.

And when i installed it a few days ago, it was able to get the battery procentage

**Comment by Apisathan** [comment]
> Seems like a network issue and not TeslaMate related. Can the device hosting TeslaMate access the internet?

Yes i just pinged google, no packet loss.

And when i installed it a few days ago, it was able to get the battery procentage - And it did a few hours later pick up that the car was online

**Comment by cwanja** [comment]
> > Seems like a network issue and not TeslaMate related. Can the device hosting TeslaMate access the internet?
> 
> 
> 
> Yes i just pinged google, no packet loss.
> 
> 
> 
> And when i installed it a few days ago, it was able to get the battery procentage - And it did a few hours later pick up that the car was online
> 
> 

Restart the Docker container.

**Comment by Apisathan** [comment]
Seems like it worked for a couple of hours and then went back to same error.
Also should i be worried about this? `:alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}`

**Comment by Apisathan** [comment]
I solved it by adding the following line to /etc/network/interfaces:
`dns-nameservers 8.8.8.8`
