### ISSUE TITLE
v.1.27.2 container issue on synology

### ISSUE THREAD

**Issue by letienne** [adriankumpf/teslamate#3125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the v1.27.2 container does not start on my synology nas. It keeps repeating:

/opt/app/erts-12.2/bin/beam.smp: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/app/erts-12.2/bin/beam.smp

I'm guessing this has something to do with the wrong elixir base image being referenced in the Dockerfile?

This looks similar to the issue that was present in 1.25: https://github.com/adriankumpf/teslamate/issues/2300 

Thanks !

### Expected Behavior

container should start

### Relevant log output

```shell
/opt/app/erts-12.2/bin/beam.smp: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/app/erts-12.2/bin/beam.smp
```

### Type of installation

Docker

### Version

v1.27.2

**Comment by letienne** [comment]
the syno in question:

```
ash-4.4# docker --version
Docker version 20.10.3, build 55f0773
ash-4.4# cat /sys/firmware/devicetree/base/model
synology_geminilake_720+
```

**Comment by hanjuq** [comment]
Same docker build, synology_geminilake_920+

Teslamate starts without any problem. I start it with attached JSON import file
[teslamate.1.27.2 - Kopie.json.txt](https://github.com/adriankumpf/teslamate/files/10782460/teslamate.1.27.2.-.Kopie.json.txt)

**Comment by letienne** [comment]
Thank you for your confirmation.
I have no idea what I did wrong the other day, but I just retried and it works as expected... 
Sorry for disturbing everyone.
