### ISSUE TITLE
kubernetes helm chart

### ISSUE THREAD

**Issue by billimek** [adriankumpf/teslamate#313]
Hi @adriankumpf, I already run an mqtt broker and grafana stack in kubernetes and wanted to run teslamate there as well.

So, based on the documentation and examples in this repo, I created a Helm Chart for teslamate, in case you're interested: https://github.com/billimek/billimek-charts/tree/master/teslamate (also on helm hub [here](https://hub.helm.sh/charts/billimek/teslamate))

**Comment by adriankumpf** [comment]
Pretty cool! Thanks for sharing. I'll add a link in the docs.
