### ISSUE TITLE
Possible to pull Sentry videos?

### ISSUE THREAD

**Issue by eoren1** [adriankumpf/teslamate#315]
This may be a very dumb question but since TeslaMate can pull stats/data from the Tesla over WiFi, can it also be made to pull sentry videos (off connected SSD)?
I realize there is a way to use a Raspberry Pi to push data to my Synology but wondered if this app could be an 'all in one' and pull the videos.
Thanks

**Comment by Tigwin** [comment]
TeslaMate is pulling data from the Tesla API. It isn't connecting directly to your car. So it wouldn't have a way to grab local files off your SSD.

**Comment by adriankumpf** [comment]
Just like @Tigwin  said, sentry videos cannot be pulled from the Tesla API. What’s possible is documented here: https://tesla-api.timdorr.com/
