### ISSUE TITLE
Advanced Setup - Port change

### ISSUE THREAD

**Issue by eagappanath** [adriankumpf/teslamate#318]
Hello All, 
The ports 80 and 443 are occupied by homeassistant in my network. Could anyone provide me directions on how to change the port for advanced Setup? Thank you for the help!

**Comment by adriankumpf** [comment]
It widely depends on your setup but in general you’d need to change the port mapping in the docker-compose file. For example, to expose port 8080 and 8443 instead:

```yaml
 ports:
      - 8080:80
      - 8443:443
```

**Comment by DrMichael** [comment]
I am not sure, that that works with Letsencrypt using httpchallenge. That would be great.

**Comment by eagappanath** [comment]
@adriankumpf  I did try that and again I did today after your reply, it still puts me to the homeassistant login. 

@DrMichael True, any help?

Thank you Guys!

**Comment by DrMichael** [comment]
I don't see a simple way, tslchallange and dnschallenge are not generally applicable. One could, of course, put letsencrypt aside and use either an own certificate (and install it in the container) or none at all (and accepting the unsecure host warnings).

**Comment by adriankumpf** [comment]
> @adriankumpf I did try that and again I did today after your reply, it still puts me to the homeassistant login.

Did you try to access the custom port, e.g. `http://your-ip-address:8080/`? You should  at least be able to connect to it, even if the certificate check fails afterwards.

To acquire a Let's Encrypt with the  default httpchallenge you'll need to use port 80 though, like @DrMichael said. To expose homeassistant and teslamate on the same port a reverse proxy could be used which terminates TLS traffic and forwards the it to either HA or teslamate, depending on e.g. the domain. That requires a custom setup.

Maybe it would be an alternative not to expose teslamate and use a VPN to your home network instead?
