### ISSUE TITLE
Issue with MQTT connectivity in v1.14.0

### ISSUE THREAD

**Issue by ngardiner** [adriankumpf/teslamate#319]
Since upgrading to v1.14.0, I am getting a lot of MQTT timeout messages in the log:

```
17:25:20.954 [info] MQTT connection has been established
17:25:23.973 car_id=1 [info] Start / :online
17:40:33.724 car_id=1 [info] Suspending logging
17:52:45.568 car_id=1 [info] Start / :asleep
18:20:05.287 car_id=1 [info] Start / :online
18:31:26.224 [error] GenServer {Tortoise.Registry, {Tortoise.Connection,
"TESLAMATE_302E3137333"}} terminating
** (stop) :ping_timeout
Last message: :ping
18:31:26.230 [error] GenServer {Tortoise.Registry, {Tortoise.Connection.S
upervisor, "TESLAMATE_302E3137333"}} terminating
** (stop) :ping_timeout
Last message: {:EXIT, #PID<0.3683.0>, :ping_timeout}
18:35:13.087 car_id=1 [info] Suspending logging
18:35:18.088 [warn] MQTT publishing failed: :timeout
18:35:18.088 [warn] MQTT publishing failed: :timeout
18:35:18.089 [warn] MQTT publishing failed: :timeout
18:35:18.089 [warn] MQTT publishing failed: :timeout
18:35:18.089 [warn] MQTT publishing failed: :timeout
18:35:18.089 [warn] MQTT publishing failed: :timeout
18:35:18.089 [warn] MQTT publishing failed: :timeout
18:35:18.089 [warn] MQTT publishing failed: :timeout
18:35:18.089 [warn] MQTT publishing failed: :timeout
```

These messages continue with around 10 errors every 5 seconds in the log. I can also see from a netstat that a lot of MQTT connections have been established to my MQTT server:

```
tcp        5      0 192.168.24.23:54913     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:49869     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:53505     192.168.24.18:1883      CLOSE_WAIT
tcp        0      0 192.168.24.23:35813     192.168.24.18:1883      ESTABLISHED
tcp        5      0 192.168.24.23:55691     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:43091     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:44561     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:60341     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:41935     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:37353     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:58955     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:45529     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:44575     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:34091     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:54565     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:52759     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:49543     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:50941     192.168.24.18:1883      CLOSE_WAIT
tcp        0      0 192.168.24.23:55631     192.168.24.18:1883      ESTABLISHED
tcp        5      0 192.168.24.23:34063     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:45535     192.168.24.18:1883      CLOSE_WAIT
tcp        5      0 192.168.24.23:47631     192.168.24.18:1883      CLOSE_WAIT
```

This is only a subset of the overall connections:

```
# netstat -an | grep -c 1883
339
```

**To Reproduce**

1. Upgrade to v1.14.0 (advanced installation)

**Operating environment**

 - OS: Ubuntu
 - TeslaMate Version: v1.14.0
 - Type of installation: Manual

**Comment by ngardiner** [comment]
Just a few updates:

- Restarting teslamate does not seem to help resolve the issue
- Unsetting the MQTT_HOST variable or setting it to an empty string per the docs at https://teslamate.readthedocs.io/en/latest/installation/debian.html result in a crash at startup (logs below)
- I'm currently pointing it at a nonexistant IP, which gives the same errors as pointing it to my actual MQTT server, but doesn't cause the large number of connections to be established repeatedly

Crash logs when MQTT_HOST is unset:

```
{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.ArgumentError',message=><<"could not fetch environment variable \"MQTT_HOST\" because it is not set">>},[{'Elixir.System','fetch_env!',1,[{file,"lib/system.ex"},{line,518}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,240}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,232}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,888}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,411}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]}]}}
init terminating in do_boot ({,[{Elixir.System,fetch_env!,1,[{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eva

Crash dump is being written to: erl_crash.dump...done
```

Errors if it is set to a blank string:
```
10:19:04.315 [error] GenServer {Tortoise.Registry, {Tortoise.Connection, "TESLAMATE_302E3334363"}} terminating
** (ArgumentError) argument error
    (kernel) gen_tcp.erl:167: :gen_tcp.connect/4
    (tortoise) lib/tortoise/connection.ex:583: Tortoise.Connection.do_connect/2
    (tortoise) lib/tortoise/connection.ex:385: Tortoise.Connection.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :connect
```

**Comment by adriankumpf** [comment]
> Unsetting the MQTT_HOST variable or setting it to an empty string per the docs at https://teslamate.readthedocs.io/en/latest/installation/debian.html result in a crash at startup (logs below)

The documentation was not quite correct :) The MQTT functionality can be disabled with `DISABLE_MQTT=true`. I’ve modified the sentence accordingly. 

Regarding the root issue I’m not convinced that those timeouts are actually caused by the upgrade to 1.14. Could you downgrade to the previous version or temporarily point to another MQTT broker to see if it improves things? Which MQTT broker are you using? Did you make any adjustments to its configuration?

**Comment by ngardiner** [comment]
I have disabled MQTT in the interim, and everything is fine without MQTT
support, other than the loss of functionality.

I will try a downgrade, however I can rule out MQTT configuration being an
issue. I have a mosquitto MQTT server, on which the configuration hasn't
been touched for 2 years (outside of adding users once or twice a year to
it) and which all of my MQTT devices talk to. Due to the nature of
HomeAssistant MQTT implementation, there is no multi-server configuration
(ie whilst you could have a federated design with multiple MQTT servers
replicating between each other, it will only connect to one) which means
for me, my MQTT setup is only useful if it is pointing at that particular
MQTT server - it would not really make sense for me to point it elsewhere
to test. as there is no usability beyond that if it were disabled.

I saw a number of MQTT commits as part of the v1.14.0 version after I
upgraded and it stopped working, and all are to do with MQTT connection
handling. I expect a downgrade will confirm if this is the cause - I will
report back shortly.

**Comment by ngardiner** [comment]
A downgrade doesn't resolve the issue, so it is clearly not those changes:

```
root@teslamate:/usr/src/teslamate-v1.13.2# _build/prod/rel/teslamate/bin/teslamate start
17:44:18.053 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
17:44:18.061 [info] Access TeslaMateWeb.Endpoint at URL
17:44:19.253 [info] Found 'Car'
17:44:19.519 car_id=1 [info] Start / :asleep
17:44:24.523 [warn] MQTT publishing failed: :timeout
17:44:24.523 [warn] MQTT publishing failed: :timeout
17:44:24.523 [warn] MQTT publishing failed: :timeout
17:44:24.523 [warn] MQTT publishing failed: :timeout
17:44:24.524 [warn] MQTT publishing failed: :timeout
17:44:24.524 [warn] MQTT publishing failed: :timeout
17:44:24.524 [warn] MQTT publishing failed: :timeout
17:44:24.524 [warn] MQTT publishing failed: :timeout
17:44:24.524 [warn] MQTT publishing failed: :timeout
17:44:24.525 [warn] MQTT publishing failed: :timeout
17:44:29.524 [warn] MQTT publishing failed: :timeout
17:44:29.524 [warn] MQTT publishing failed: :timeout
17:44:29.524 [warn] MQTT publishing failed: :timeout
17:44:29.525 [warn] MQTT publishing failed: :timeout
17:44:29.525 [warn] MQTT publishing failed: :timeout
17:44:29.525 [warn] MQTT publishing failed: :timeout
17:44:29.525 [warn] MQTT publishing failed: :timeout
17:44:29.525 [warn] MQTT publishing failed: :timeout
17:44:29.525 [warn] MQTT publishing failed: :timeout
```

It's certainly possible for me to state that the problem started after upgrade to v1.14.0 because I log all teslamate output and periodically rotate the logs. You can see here:

```
root@teslamate:/usr/src/teslamate-v1.14.1# grep -c 'MQTT publishing failed: :timeout' screenlog*
screenlog.0:126237
screenlog.01:32
screenlog.02:0
```

The 32 instances in screenlog.02 were caused during a brief network interruption while I was doing maintenance as can be seen by the nxdomain DNS results and brief errors:

```
04:16:25.800 [info] Querying location for elevation takes longer than 100ms ...
09:57:36.300 car_id=1 [warn] Error / upstream timeout
09:58:05.315 car_id=1 [error] Error / :nxdomain
09:58:59.322 car_id=1 [error] Error / :nxdomain
09:59:49.061 [error] GenServer {Tortoise.Registry, {Tortoise.Connection, "TESLAMATE_302E3035343"}} terminating
** (stop) :ping_timeout
Last message: :ping
09:59:49.089 [error] GenServer {Tortoise.Registry, {Tortoise.Connection.Supervisor, "TESLAMATE_302E3035343"}} terminating
** (stop) :ping_timeout 
Last message: {:EXIT, #PID<0.20643.23>, :ping_timeout}
09:59:53.329 car_id=1 [error] Error / :nxdomain
10:00:47.338 car_id=1 [error] Error / :nxdomain
10:00:52.350 [warn] MQTT publishing failed: :timeout
10:00:52.351 [warn] MQTT publishing failed: :timeout
10:00:52.351 [warn] MQTT publishing failed: :timeout
10:00:52.352 [warn] MQTT publishing failed: :timeout
10:00:52.352 [warn] MQTT publishing failed: :timeout
10:00:52.352 [warn] MQTT publishing failed: :timeout
10:00:52.352 [warn] MQTT publishing failed: :timeout
10:00:52.353 [warn] MQTT publishing failed: :timeout
10:00:52.353 [warn] MQTT publishing failed: :timeout
10:00:52.354 [warn] MQTT publishing failed: :timeout
10:00:57.351 [warn] MQTT publishing failed: :timeout
10:00:57.351 [warn] MQTT publishing failed: :timeout
10:00:57.352 [warn] MQTT publishing failed: :timeout
10:00:57.352 [warn] MQTT publishing failed: :timeout
10:00:57.353 [warn] MQTT publishing failed: :timeout
10:00:57.357 [warn] MQTT publishing failed: :timeout
10:00:57.358 [warn] MQTT publishing failed: :timeout
10:00:57.358 [warn] MQTT publishing failed: :timeout
10:00:57.358 [warn] MQTT publishing failed: :timeout
10:00:57.358 [warn] MQTT publishing failed: :timeout
10:01:02.352 [warn] MQTT publishing failed: :timeout
10:01:02.352 [warn] MQTT publishing failed: :timeout
10:01:02.355 [warn] MQTT publishing failed: :timeout
10:01:02.363 [warn] MQTT publishing failed: :timeout
10:01:02.363 [warn] MQTT publishing failed: :timeout
10:01:02.364 [warn] MQTT publishing failed: :timeout
10:01:02.364 [warn] MQTT publishing failed: :timeout
10:01:02.364 [warn] MQTT publishing failed: :timeout
10:01:02.364 [warn] MQTT publishing failed: :timeout
10:01:02.364 [warn] MQTT publishing failed: :timeout
10:01:07.353 [warn] MQTT publishing failed: :timeout
10:01:07.353 [warn] MQTT publishing failed: :timeout
10:01:09.673 [info] [alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}]
10:01:41.344 car_id=1 [error] Error / :nxdomain
10:02:35.353 car_id=1 [error] Error / :nxdomain
10:03:29.358 car_id=1 [error] Error / :nxdomain
10:04:23.363 car_id=1 [error] Error / :nxdomain
10:04:29.318 [info] Initializing handler
10:04:29.321 [info] Connection has been established
```

The 126,000 errors however started directly after starting v1.14.1:

```
10:11:10.228 [info] Version: 1.14.1
10:11:11.535 [info] Refreshed api tokens
10:11:11.545 [info] Scheduling token refresh in 40d
10:11:11.552 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
10:11:11.555 [info] Access TeslaMateWeb.Endpoint at URL
10:11:12.289 [info] Adding elevation to 7 positions ...
10:11:12.391 [info] Querying location for elevation takes longer than 100ms ...
10:11:12.508 [info] Starting logger for 'Car'
10:11:13.490 car_id=1 [info] Start / :offline
10:11:18.505 [warn] MQTT publishing failed: :timeout
10:11:18.505 [warn] MQTT publishing failed: :timeout
10:11:18.505 [warn] MQTT publishing failed: :timeout
10:11:18.505 [warn] MQTT publishing failed: :timeout
10:11:18.506 [warn] MQTT publishing failed: :timeout
10:11:18.506 [warn] MQTT publishing failed: :timeout
10:11:18.506 [warn] MQTT publishing failed: :timeout
10:11:18.506 [warn] MQTT publishing failed: :timeout
10:11:18.506 [warn] MQTT publishing failed: :timeout
10:11:18.506 [warn] MQTT publishing failed: :timeout
[SNIP]
```

A test of connectivity to MQTT works fine:

```
root@teslamate:/usr/src/teslamate-v1.14.1# mosquitto_sub -v -h $MQTT_HOST -u $MQTT_USERNAME -P $MQTT_PASSWORD -t 'teslamate/#'

teslamate/cars/1/sentry_mode false
teslamate/cars/1/since 2019-12-24T07:20:05.287891Z
teslamate/cars/1/state online
```

So I'm really not sure. I expected there would be other reports of this as it happened directly after an upgrade but nobody else has complained. I will do some more testing on my side, but I no longer suspect those commits in v1.14.0 to be the cause of the errors.

**Comment by ngardiner** [comment]
I'm now suspecting this is environment specific, since it's only my installation impacted. I'm going to try a setup where I run MQTT locally on the teslamate server, and bridge it to my main MQTT server so it more closely mimics the docker setup (which I can't use, as I use LXC containers already and can't run it inside a container).

**Comment by jun3280net** [comment]
Hi @ngardiner are you able to share how you solved this issue?  I'm seeing the same publishing error on my side.  I have HASSIO - Home Assistant Supervisor running in Docker on a Linux Mint Virtual Machine.  Mosquitto MQTT runs as an addon to HASSIO in my setup.  The default configuration is to allow for TCP connections on 1883, 1884, 8883, and 8884.  

![image](https://user-images.githubusercontent.com/30555695/82412828-8abdf000-9a31-11ea-9360-59ab5da619ad.png)

I've got light switches connecting to this MQTT server with the following parameters : 
![image](https://user-images.githubusercontent.com/30555695/82412987-d4a6d600-9a31-11ea-93aa-c521e2ab48e4.png)

As I did not want to run two separate VMs, I decided to migrate teslamate to the same VM using the docker-compose setup with the "Advanced Install with Traefik and Lets Encrypt" [https://docs.teslamate.org/docs/guides/traefik](https://docs.teslamate.org/docs/guides/traefik).  Everything works, but I had to comment out the MQTT Server/Container in the docker-compose file, as it was conflicting with the existing Mosquitto Server from Home Assistant.  That said, I pointed the MQTT_Host to 192.168.86.83:1883, but I get the **"[warn] MQTT publishing failed: :timeout"** error.

I can't tell whether teslamate is actually connecting to the MQTT server.  I've tested the following command : **sudo tcpdump -i any port <number>** and can confirm there is activity on 443, 4000, 3000, 1883.  I also used **sudo ngrep -W byline -d any port <number> -q** to see the specific IPs connecting to each port.  I can confirm on 1883, the light switches connecting.  I could not see teslamate connecting. 

As a test I decided to try out another MQTT port 8883 to isolate the problem.  I pointed one of the light switches to this port, and could confirm the connection using the commands above.  I changed the MQTT_Host on the docker-compose to 192.168.86.83:8883, but could not see any connection from teslamate on the port.

Any ideas on what could be the problem?  The only thing I can think of at this point is that somehow the Traefik is preventing the connection from leaving the container - but I don't fully understand how that networking magic works.

**Comment by shawwellpete** [comment]
Sorted it, 

if anybody else finds this I needed to change the docker-compose.yml file to this

    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=my mqqt ip address (in my case the same as my home assistant)
      - MQTT_USERNAME=mymqqtusername
      - MQTT_PASSWORD=mymqqtpassword

**Comment by gurmukhp** [comment]
I'm having the exact same issue, is there an issue with Tesla Mate? Even on a fresh install, I get the same issues...

**Comment by brianmay** [comment]
Curious if this PR might help: https://github.com/teslamate-org/teslamate/pull/3697

https://github.com/teslamate-org/teslamate/pkgs/container/teslamate/185359301?tag=pr-3697
