### ISSUE TITLE
battery_level vs. usable_battery_level

### ISSUE THREAD

**Issue by ctraber** [adriankumpf/teslamate#321]
Sorry, just saw that I added my first post regarding this topic to an already closed issue #257  
 
Recently I changed my setting in the car to % and was wondering why the Tesla App showed different % values than TeslaMate and other 3rd party apps.

After looking at the raw values of the API, it seems that the Telsa App and the display in the car are showing `usable_battery_level` and nor `battery_level`. In cold weather `usable_battery_level` is lower and once the difference is higher (>3%?) The app and car show the blue snowflake.

I also noticed that whenever I had the snowflake I also saw a spike down in degradation Grafana report.

I think the reason is that the degradation report is using  `battery_level` to calculate the projected 100% rated range:
`battery_range / battery_level * 100`

But I think that the range in the API is also affected by cold weather as you can see it going down/up when temperature is changing. So the behavior seems to be more related to `usable_battery_level` than to `battery_level`. Which would also explain the spikes in degradation report.

To get a better overview I would love to see `usable_battery_level` and the projected 100% ranges in addition to the `battery_level` on the status page.
Maybe it is also possible to add a second graph to the degradation report showing the line using the `usable_battery_level` for calculation.

If I find time I'll try to make a development setup to try it by myself...

**Thank you very much for all your effort! I love TeslaMate and I hope I'll be able to contribute in some way in the future.**

**Comment by ctraber** [comment]
I was able to setup the dev environment.

Now I see that usable_battery_level is not yet in the schema.
Would it be high effort to add additional api fields to the positions table?

**Comment by adriankumpf** [comment]
That would indeed be interesting!

> Would it be high effort to add additional api fields to the positions table?

The field would have to be added by a migration: https://devhints.io/phoenix-migrations I will look at it in the future (if you haven't prepared a PR by then :)

**Comment by ctraber** [comment]
Thanks for the hint!
Never used Elixir, Phoenix, erlang, ... But I'll try.
