### ISSUE TITLE
SSL not working

### ISSUE THREAD

**Issue by LeeHanYeong** [adriankumpf/teslamate#3247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
2023-06-15 06:14:11.395 
[error] Postgrex.Protocol (#PID<0.173.0>) failed to connect: ** (DBConnection.ConnectionError) ssl connect: Options (or their values) can not be combined: [{verify,verify_peer},
{cacerts,undefined}] - {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}
```

I am getting the error even though I have specified **DATABASE_SSL_CA_CERT_FILE**.
I tried with cert.pem and fullchain.pem issued by let's encrypt, but both give the same error. (cacerts: undefined)

In **DATABASE_SSL_CA_CERT_FILE** I specified the absolute path as follows:
/{paths...}/live/{domain}/cert.pem
/{paths...}/live/{domain}/fullchain.pem

docker-compose.yml looks like this:
```
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ...
      - DATABASE_SSL=true
      - DATABASE_SSL_CA_CERT_FILE=/{paths...}/live/{domain}/cert.pem
```

### Expected Behavior

Why do I need to specify CA_CERT_FILE?

### Relevant log output

```shell
2023-06-15 06:14:11.395 
[error] Postgrex.Protocol (#PID<0.173.0>) failed to connect: ** (DBConnection.ConnectionError) ssl connect: Options (or their values) can not be combined: [{verify,verify_peer},
{cacerts,undefined}] - {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}
```

### Type of installation

Docker

### Version

v1.27.3

**Comment by adriankumpf** [comment]
#3243
