### ISSUE TITLE
% of driven with FSD (Full Self Driving)

### ISSUE THREAD

**Issue by marcogabriel** [adriankumpf/teslamate#327]
Is it possible to extract and show a percentage/mileage that was driven by using FSD/AutoPilot?

**Comment by adriankumpf** [comment]
Not that I know of, unfortunately. What’s possible is documented here: https://tesla-api.timdorr.com/

**Comment by baylanger** [comment]
Tesla has access to this data and perhaps they want to keep their hands on it?

I did a 5000+ miles trip and was not happy about this metric not available.  How often was I on AP, I estimate ~99%.  It would be great to map location you have AP on / off.

**Comment by pirate21213** [comment]
Can this be reopened? Tessie recently added this feature so it's definitely possible.

**Comment by Anubis1971** [comment]
Data on FSD miles driven would be awesome to have.  Please see if this is now possible to integrate into Teslamate.

**Comment by cerw** [comment]
Yes to this please! (Australia)

**Comment by baylanger** [comment]
There’s no such expose value from Tesla API that clearly states if autopilot is active or not.

Tessie is possibly using a combination of 2 or all of the following values : 

- accel_pedal_position (0-100%)
- brake_pedal_status (Boolean)
- brake_pedal_position (0-100%)

The speed is probably used to confirm the car is moving and if none of the pedal is being pressed,  Tessie set FSD is on until one of the pedal is pressed.

Perhaps speed_limit_mode changes when FSD or autopilot is on but that would be too easy 🤔
