### ISSUE TITLE
No value for kWh or Consumption in recorded drives

### ISSUE THREAD

**Issue by gurmukhp** [adriankumpf/teslamate#3279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi there

I've noticed that I no longer get kWh or Consumption in the drives recorded on Teslamate. Usually I'm able to see the kWh used in a drive and the corresponding charge, but I'm not seeing that.

EDIT: Just checked the FAQs and saw this:
https://docs.teslamate.org/docs/faq/#why-are-no-consumption-values-displayed-in-grafana

How do other apps get this value?

**Comment by enoch85** [comment]
Maybe not much help, but this is on the latest release - 1.27.3:

![image](https://github.com/adriankumpf/teslamate/assets/4511254/0d6e6c48-95dc-42ae-b1b8-cc828b33915c)

In other words, it works.

**Comment by gurmukhp** [comment]
I guess you didn't read my issue thoroughly

**Comment by enoch85** [comment]
This was the question: 

> no longer get kWh or Consumption in the drives recorded on Teslamate


My screenshot:

![image](https://github.com/adriankumpf/teslamate/assets/4511254/1293d865-9d2a-4c56-8d96-bb02eb204634)

**Comment by gurmukhp** [comment]
There was also a bit underneath that:

> EDIT: Just checked the FAQs and saw this:
> https://docs.teslamate.org/docs/faq/#why-are-no-consumption-values-displayed-in-grafana
