### ISSUE TITLE
How can I access my containers on raspberry pi?

### ISSUE THREAD

**Issue by pimvdnoll** [adriankumpf/teslamate#331]
I had succesfully ran the docker containers on a AWS EC2 instance so I thought it would also work as easy on a Raspberry PI. The docker containers are running and everything is working but only if I connect a screen with HDMI and browse with a chromium browser to http://172.19.0.6:3000 but not if I point my browser from another laptop in my home network to the IP address of the raspberrypi (which is 192.168.3.49:3000).

How can I configure the docker configuration that 192.168.3.49:3000 will point to my 172.19.0.6:3000 docker container?

thnx for the help!

**Comment by adriankumpf** [comment]
AFAIK it does bind to 0.0.0.0 by default and therefore it should work out of the box. If `docker ps` indicates otherwise you could maybe try to explicitly bind to 0.0.0.0:

```yaml
 ports:
      - 0.0.0.0:4000:4000
```

Or maybe firewall rules prevent access? Did you double check the IP address? :)
