### ISSUE TITLE
Question again: Can I combine different backup files (.bck)?

### ISSUE THREAD

**Issue by lisankai93** [adriankumpf/teslamate#3310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have two backup files (bck) with different periods.
Can these two be restored to one teslamate?

The teslamate1.bck file that I backed up from 2021-2022 (700mb)
There is a teslamate2.bck file that backed up data from 2022-2023 by installing teslamate again.

I installed a new teslamate and restored teslamate1.bck 1 bck as guided.
Restored normally.

After that, execute the following command for another period of bck file.

So how to finish that? Thanks!

### Relevant log output

```shell
none
```

### Type of installation

Docker

### Version

v.1.27.3

**Comment by parkr** [comment]
I'm not a maintainer, but I think you'd get more help if you posted this as a Discussion on this repo since this isn't an issue/bug with Teslamate.

**Comment by lisankai93** [comment]
> I'm not a maintainer, but I think you'd get more help if you posted this as a Discussion on this repo since this isn't an issue/bug with Teslamate.

Ok thanks, I've start a new discussion because I found the previous discussion had no solution.
