### ISSUE TITLE
Unable to upgrade to 1.14.1 from 1.11

### ISSUE THREAD

**Issue by fyreflyt** [adriankumpf/teslamate#335]
I've been trying for several days to upgrade to 1.14.1 with no success.

I'm running Teslamate on a Raspberry Pi 3 that is also running Pi-Hole. The initial install went smoothly (once I got docker-compose installed), but now I'm getting the same timeout errors on every install attempt. Errors are below.

```
Removing teslamate_mosquitto_1
Removing teslamate_grafana_1
Removing teslamate_db_1
Removing teslamate_teslamate_1
Recreating 5843a1aa22e9_teslamate_mosquitto_1 ... 
Recreating c3bbde41b576_teslamate_grafana_1   ... 
Recreating 30bffeb9e5d0_teslamate_db_1        ... 
Recreating 1e71509ea93a_teslamate_teslamate_1 ... 

ERROR: for c3bbde41b576_teslamate_grafana_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for 30bffeb9e5d0_teslamate_db_1  UnixHTTPConnectionPool(host='localhost',Recreating 5843a1aa22e9_teslamate_mosquitto_1 ... done

ERROR: for 1e71509ea93a_teslamate_teslamate_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

ERROR: for teslamate  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

ERROR: for db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for grafana  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

I've tried changing the COMPOSE_HTTP_TIMEOUT to 200 seconds with the following command, but it just generated a new series of errors.

`COMPOSE_HTTP_TIMEOUT=200 docker-compose up`

Can anyone offer any suggestions on how to get Teslamate back up and running?

**Comment by fyreflyt** [comment]
Well, looks like the timeout of 200 was too much, I changed it to 100 and disabled the Pi Hole. After that it appears to have installed. I'm able to log in and see my previous data once again. Have to see if it records drives once again.

**Comment by adriankumpf** [comment]
Glad it works now! I can imagine that starting all services in the docker-compose file at once may overwhelm the Pi. It may help to start them sequentially next time:

```bash
docker-compose up -d mosquitto
docker-compose up -d db
docker-compose up -d grafana
docker-compose up -d teslamate
```
