### ISSUE TITLE
Charts imply values that aren't there

### ISSUE THREAD

**Issue by Tigwin** [adriankumpf/teslamate#337]
Many of the charts imply values when none exist. 

For example, the charging display needs to have values stay at zero until the first graphed value instead of going from the previous zero value to the current value. This results in angled slopes that are misleading:

Example, look at the orange lines on the charging display:

![image](https://user-images.githubusercontent.com/8354498/71701136-b9df0800-2d95-11ea-9bf5-9969867cbbdd.png)

**Describe the solution you'd like**

When the previous value is zero, the system needs to chart a second zero value before charting the new proper value so the times without values stays at zero instead of sloping upward. 

This issue is present on most charts.

**Comment by Tigwin** [comment]
If you change the draw mode from line to "points", the result is better:

https://i.imgur.com/BbGzyiZ.png

**Comment by adriankumpf** [comment]
It does look better with draw mode "points" when zoomed out but it looks worse in the normal view, doesn't it? As far as I know there is no Grafana setting to get the best of both worlds. 

But the dashboard is actually not intended to be used to directly :-) I don't know if you already know this, but you can click on the start date in the 'Charges'/'Drives' dashboard. You will then be taken to the detailed view.
