### ISSUE TITLE
Miles Preference

### ISSUE THREAD

**Issue by kinteseay** [adriankumpf/teslamate#341]
My mileage and degradation views are showing km and my other tabs are showing miles.  My preference is miles, but not sure why the others are showing km.  I'm not sure when this started happening or if it always happened.  My legend shows miles, but the actual value is km.

**Comment by Tigwin** [comment]
change that on the teslamate preference page (not grafana)

**Comment by kinteseay** [comment]
> change that on the teslamate preference page (not grafana)

I have the preference in teslamate preference.  What I'm saying is that the result is not consistent between my grafana pages.  Some show miles and a couple show km.

**Comment by kinteseay** [comment]
Looks like it's working now.  I'm not sure what was going on

**Comment by lux4rd0** [comment]
I just noticed this as well - and it's only in one place. If you're on the "Drives" page and the click down into of of the drives by the date link, it seems to be picking up "&var-temp_unit=C&var-length_unit=km" from somewhere even though I have it set to F and mi. Reloading that page with the parameter changes showed it correctly for me. I just haven't dug deeper into where the aliases are being dropped. :)
