### ISSUE TITLE
Tell TeslaMate docker instance use a specific CarID

### ISSUE THREAD

**Issue by brabidou** [adriankumpf/teslamate#348]
Use case: I would like to share an hosted EC2 instance of the TeslaMate stack with a few friends/family but I don't want to spin up new EC2 instances for each Tesla account.

I would like a way to tell the TeslaMate application to use a specific Car ID rather that he default of 1. This way I can run multiple instances of the TesaMate docker instance for different Tesla accounts but still use the same Postgres/MQTT/Grafana instance. I know TeslaMate supports multi cars in the same Tesla account so it should be a matter of exposing TeslaMate to use a specific CarID.

**Comment by adriankumpf** [comment]
Multi-tenancy or similar features are not planned as they are beyond the scope of the project. However, it is still possible to use the same Postgres instance _(w/ multiple databases)_ and Grafana instance _(w/ multiple data sources)_ as well as the same MQTT broker _(requires `MQTT_NAMESPACE`)_ with multiple teslamate instances on a single EC2 instance. See https://github.com/adriankumpf/teslamate/issues/403.
