### ISSUE TITLE
Two countries: Netherlands and The Netherlands

### ISSUE THREAD

**Issue by mboerma** [adriankumpf/teslamate#349]
In the Locations view in Grafana there are a couple of things happening which a bit strange in the context of Cities, Neighborhoods, States (we don't have those. We have provinces) etc. But the "bug" is that there are two different countries linked to locations in the Netherlands. See attached screenshot.

I'm not sure where this data is coming from but it is incorrect for the Netherlands.

Teslamate V1.14.3

<img width="949" alt="Screenshot 2020-01-08 at 00 30 54" src="https://user-images.githubusercontent.com/25712617/71937994-5a766300-31ae-11ea-9a3f-028b65528b90.png">

**Comment by adriankumpf** [comment]
The data comes from OpenStreetMap. There is a way to report/fix incorrect data: https://www.openstreetmap.org/fixthemap

Regarding the incorrect term "States": the data from OSM needs to be normalized to make querying/graphing feasible. Some information is therefore lost in the process. Hope that's not a huge issue :-)

**Comment by mboerma** [comment]
For The Netherlands and I think many other countries the way the columns are named are very awkward and inconsistent. If this is Openstreet maps or teslamate I don't know. Neighbourhood is often more city than a real neighbourhood but not always. 

I don't see any way of filling a bug with open street maps via that link.

**Comment by mboerma** [comment]
I checked this with OSM and local members of OSM. The data is consistent and correct for the addresses. I can thus only assume that for some reason teslamate is doing things a bit different.

As an example the address that shows Netherlands gives the following in OSM:

Abcoude, De Ronde Venen, Utrecht, Netherlands, 1391EH, The Netherlands

same build up as the address the one below it:

Bullewijk, Amsterdam, North Holland, Netherlands, 1101EE, The Netherlands

You can see that both "Netherlands" and "The Netherlands" are used.
