### ISSUE TITLE
SSL Cert / Traefik Question....?

### ISSUE THREAD

**Issue by DSDesign** [adriankumpf/teslamate#350]
Hello,

I recently installed the advanced version and had an issue with getting Let's Encrypt to generate the certs (403 error on challenge). I'm not too concerned about this part as I have a valid trusted cert that I can use with my domain. Currently, when calling the service Traefik is presenting the default self-signed cert so most browsers won't even let me access the page without an exception. I've searched everywhere in the container for this default cert or the config for Traefik to change it, but no luck. 

So my question is....how do I modify this default cert to use my own trusted cert? Where is the config file with this setting, or where is the default cert located for Traefik?

Thank you in advance for everyone's feedback/help on this issue!

**Comment by markusdd** [comment]
If you are using traefik 2 and above you will have to define a certificationprovider and link this to your router which points to the teslamate instance.

This cert provider can be acme (let's ecrypt) or a simple file which could be your cert.
have a look at the official traefik docs, it is quite comprehensive and should cover your case.
