### ISSUE TITLE
Incorrect trace markers on Battery Health -> Battery Capacity by Mileage graph

### ISSUE THREAD

**Issue by jalkanen** [adriankumpf/teslamate#3511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Graph displays a gradient from left to right.

### Expected Behavior

Graph should display a gradient from top to bottom.

Simple fix is to change Traces -> Markers -> metric to "kWh" instead of the current "id".

### Relevant log output

```shell
N/A
```

### Type of installation

Docker

### Version

1.28.1

**Comment by swiffer** [comment]
@jalkanen - it's a red line without gradient for me in the latest Grafana version?

![grafik](https://github.com/teslamate-org/teslamate/assets/2990373/b6895d48-7767-4331-b2bf-0e3ec650f398)

**Comment by jalkanen** [comment]
Yup, re-pulled this morning and the graph changed its form completely. Something funky going on there, but issue seems resolved for now!

**Comment by JakobLichterfeld** [comment]
Glad it is resolved with latest grafana image.
