### ISSUE TITLE
Please continue to support manual installs for Teslamate!

### ISSUE THREAD

**Issue by jensb** [adriankumpf/teslamate#3515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As per comment in PR#3439, I am repeating my request to continue to support manual installs here.
I am running Teslamate on a Raspberry Pi which already has instances of Grafana, Postgresql and a MQTT service running for a lot of services.
Duplicating all these for each service would totally overload the little machine and - IMHO - makes no sense.

So I would continue to need a supported way of installing either a *single* Teslamate-only docker image with hooks to existing Grafana / Postgres / MQTT services (and not duplicating the complete infrastructure), or (preferably) a manual installation option.

Thank you!

### Expected Behavior

-

### Steps To Reproduce

-

### Relevant log output

```shell
-
```

### Screenshots

-

### Additional data

-

### Type of installation

Manual

### Version

1.28

**Comment by brianmay** [comment]
My understanding is that the discussion was concerning the future of the documentation. Manual installs would continue to work even if the documentation is removed.

I don't think anybody was going to actually remove the documentation.

I think there was frustration that we have to keep multiple installation procedures tested and in sync. I don't think that is a good reason for removing documentation though.

If anything, I would like to see more installation methods documented, e.g. [nix](https://github.com/teslamate-org/teslamate/pull/3485).

**Comment by cwanja** [comment]
I am going to move this to a discussion for now, as I do not see an "issue" at the moment.
