### ISSUE TITLE
Charges dashboard shows km instead of miles

### ISSUE THREAD

**Issue by cleanev** [adriankumpf/teslamate#3533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Charges dashboard shows as kilometer in last column while everything else is set miles

### Expected Behavior

While settings for the car and all other dashboards shows miles, ‘Charges’ dashboard should show miles instead of kilometers in last column

### Relevant log output

```shell
Nothing relevant
```

### Type of installation

Docker

### Version

1.28.2

Edit:
Updated snapshot

**Comment by cleanev** [comment]
![IMG_1289](https://github.com/teslamate-org/teslamate/assets/45519661/a055b3d1-9ac3-479d-a753-191d768b1186)

**Comment by mechoriet** [comment]
seems like this https://github.com/teslamate-org/teslamate/blob/master/grafana/dashboards/charges.json#L771-L774 is causing your issues wrong unit type

**Comment by NirKli** [comment]
Nice catch! @mechoriet
