### ISSUE TITLE
Limited data in Grafana

### ISSUE THREAD

**Issue by DorDana91** [adriankumpf/teslamate#3549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After I installed the apps, I could see in both Grafana and DB that I had limited data.

### Relevant log output

```shell
log
```

### Type of installation

Docker

### Version

latest

**Comment by cwanja** [comment]
Going to need a lot more information, but let's start with what does "limited data" mean? Screenshots and logs help here. 

If you _just_ installed the apps, there will be near zero data there until you connect to your Tesla account and start scraping data.

**Comment by DorDana91** [comment]
I ran it locally, and visited localhost:4000 and now I need to fill the tokens.
I've generated tokens and succeed to log in, but I can see a very small amount of data
