### ISSUE TITLE
Macrodroid setup

### ISSUE THREAD

**Issue by markusdd** [adriankumpf/teslamate#355]
Hi,

this is probably again a documentation thing:

It seems to me the macrodroid setup section is only started, but I would like to know the complete setup to trigger a wakeup.

Could you provide it please?

**Comment by adriankumpf** [comment]
I am not an Android/Macrodroid user, so I can only describe it in general terms. 

In general you'll need to create an 'action' to send a HTTP request to your exposed Teslamate instance e.g. `http://ip-address:port/api/car/1/logging/resume`. Note that the request method needs to be `PUT`. 

Depending on your setup (e.g. [Advanced Docker Setup](https://teslamate.readthedocs.io/en/latest/installation/docker_advanced.html)) you may have protected the endpoint with HTTP basic authentication. If that's the case a HTTP header with the key `Authorization` and your base64 encoded credential is required. The value is constructed like this:

  * Your chosen username and the password are combined with a colon: `aladdin:opensesame`
  * The resulting string is base64 encoded: `YWxhZGRpbjpvcGVuc2VzYW1l`
  * The encoded string is prefix with "Basic ": `Basic YWxhZGRpbjpvcGVuc2VzYW1l`

MacroDroid may also offer the option to automatically encode a username and password.

Hope this helps!

**Comment by markusdd** [comment]
Thank you!

I was actually able to figure it out using the Android Tasker description you provided. Macrodroid integrates well with RESTasker which can also handle the basic HTTPauth behind my home traefik proxy.

Works like a charm now, built a trigger for bluetooth connection and when I open the phone app, because when I preheat in the morning I want the consumption and temperature to be logged as well.

Thanks again for providing this and the great dashboards, this is a true private replacement for Teslafi!

(will open another ticket though with a suggestion)

**Comment by adriankumpf** [comment]
Glad it works now! It would be nice if you could create a PR with your approach. That would certainly help others :-)

> Thanks again for providing this and the great dashboards, this is a true private replacement for Teslafi!

Thanks!
