### ISSUE TITLE
How to add documentation?

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#358]
I would like to add documentation for backup/restore and virtual host / reverse proxy setup with Apache.

How would I do that?

**Comment by adriankumpf** [comment]
That'd be great! We can't have enough documentation.

Here is a nice guide on how to create a pull request: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

Once you have cloned the repo, all you need to do is change (or add) the markdown files in [/docs](https://github.com/adriankumpf/teslamate/tree/master/docs)

**Comment by DrMichael** [comment]
Well, well, well. I tried my very best. Did it work? I am not sure, whether all three files made it into the PR.

**Comment by adriankumpf** [comment]
The PR included two files? :D But it looked pretty good to me 👍 I have just made a few adjustments so that both 'Advanced setups' are more similar.
