### ISSUE TITLE
Manually fixing data

### ISSUE THREAD

**Issue by holman** [adriankumpf/teslamate#360]
Hi! My Tesla has been way screwy lately, and it was finally just brought back to life after some Very Dark Days without all that precious *d a t a* in TeslaMate.

TeslaMate handled it basically like a champ. Looking at the data again now that it’s working again, there’s one awkward drive where it lasts four minutes and the GPS coordinates are all screwy- it basically teleports me 10 miles away and then back again.

Is there a process where I could basically manually nuke that one single drive? Would that completely mess up the data integrity for the rest of TeslaMate? If not, and it’s easy enough to just nuke that row... what’s the suggested way of making those changes?

Cheers!

**Comment by adriankumpf** [comment]
Yeah, that's not a big deal. Simply delete the trip and the corresponding rows from the `positions` table.

For example, to delete the drive with id 42:

```sql
BEGIN;
UPDATE drives SET start_position_id = NULL, end_position_id = NULL WHERE id = 42;
DELETE FROM positions WHERE drive_id = 42;
DELETE FROM drives WHERE id = 42;
COMMIT;
```

**Comment by bahree** [comment]
Curious - would it make sense to add a tools/utils page for things like these? As in add a drive ID, and it can delete the drives? Same thing possibly for a couple of other things. I don't know if there is a lot of value or better off to have this via discussions.

**Comment by DrMichael** [comment]
Or add it to the FAQ?

**Comment by holman** [comment]
Actually, now that I'm looking at it some more, what's the best way to access the db directly? Kinda unfamiliar with how everything is set up (using the docker-compose route).

**Comment by holman** [comment]
Ah, was able to do it from [this helpful comment](https://github.com/adriankumpf/teslamate/issues/132#issuecomment-549250855). Documenting that/adding to the FAQ (or making an easier way to get a db console) would be a +1 from me!

**Comment by holman** [comment]
Annnnnnd one last comment: that process that @adriankumpf nicely detailed worked great for me- the map looks great once again, thanks! Feel free to close this issue and/or keep it open for the FAQ/docs/what have you. 🚗🔋

**Comment by cwanja** [comment]
Is there a way to remove a rogue location as well? I seem to have been in China at one point with my car. There is no drives associated with that location either.

![Screen Shot 2020-01-18 at 11 41 01 AM](https://user-images.githubusercontent.com/54645561/72667986-79af9480-39e7-11ea-8a3f-8a54d39dcc9f.png)

**Comment by adriankumpf** [comment]
@cwanja sure, if there are no drives or charges associated to that location, [connect to the database container](https://teslamate.readthedocs.io/en/latest/maintenance/manually_fixing_data.html) and delete the address:

```sql
DELETE FROM addresses WHERE name LIKE '%Mêdog%';
```

**Comment by cwanja** [comment]
Worked like a champ @adriankumpf. Only update I would say is that the documentation mentions "databases" in the docker-compose connect statement. It should be db. Do not see a way to update that like I would on Github. 👍🏼

**Comment by durzel** [comment]
> Yeah, that's not a big deal. Simply delete the drive and the corresponding rows from the `positions` table.
> 
> For example, to delete the drive with id 42:
> 
> ```sql
> BEGIN;
> UPDATE drives SET start_position_id = NULL, end_position_id = NULL WHERE id = 42;
> DELETE FROM positions WHERE drive_id = 42;
> DELETE FROM drives WHERE id = 42;
> COMMIT;
> ```

I'm aiming to create a script that automatically deletes drives less than 1 mile / X minutes duration, since every time I move the car around with Summon a drive gets logged.

Can I ask - why is it that you set the start_position_id and end_position_id to NULL before deleting the drive entry?  Is this because setting those values to NULL triggers updates elsewhere?  

Thanks in advance.

**Comment by adriankumpf** [comment]
The comment is outdated. Simply deleting the drive works now.

**Comment by cwanja** [comment]
> The comment is outdated. Simply deleting the drive works now.

Could this just be built into the web interface? "Enter drive ID: ". Same for charge.

**Comment by WeBeRiO** [comment]
I can't to fix, event no found

_ash-4.3# docker-compose exec teslamate bin/teslamate rpc \ "TeslaMate.Repo.get!(TeslaMate.Log.Drive, 1948) |> TeslaMate.Log.close_drive()"
ash: !: event not found_

**Comment by WeBeRiO** [comment]
I can't to fix, event no found. I need help ...

```
ash-4.3# docker-compose exec teslamate bin/teslamate rpc \ "TeslaMate.Repo.get!(TeslaMate.Log.Drive, 1948) |> TeslaMate.Log.close_drive()"
ash: !: event not found
```
