### ISSUE TITLE
Convert from  basic to advanced install

### ISSUE THREAD

**Issue by mikeh2010** [adriankumpf/teslamate#363]
I've installed and its all working great.

Maybe it would be better to make it available on the internet so Tasker would work outside my network.

What is the best approach to upgrade from a basic to an advanced (Traefik, Let's Encrypt, HTTPS, HTTP Basic Auth) install without loosing the data I have?

**Comment by DrMichael** [comment]
Backup the data, make a fresh install and restore the data into it. See [here](https://teslamate.readthedocs.io/en/latest/maintenance/backup_restore.html)

**Comment by mikeh2010** [comment]
OK, thanks.
I wondered if there was another way because I'm getting 'ERROR: No such service: database' when I try that command...

**Comment by DrMichael** [comment]
Aaaah, I guess you have to change db to database in the docker-compose.yml

**Comment by shagberg** [comment]
I was also getting the same error as mikeh2010, and updated my docker-compose.yml file and that solved the issue.

Now, I'm getting an error `No container found for database_1`

Any ideas on how to solve that?

**Comment by adriankumpf** [comment]
Like @DrMichael said, the database service was previously named `db` in the docker-compose.yml. It has been renamed `database`. 

To upgrade to the advanced install (or  just to update the file with the latest version), you need to run `docker-compose down` **before** making changes to the compose file. Then proceed as usual. If you have already edited the file, change `database:` to the `db:` first.

> What is the best approach to upgrade from a basic to an advanced (Traefik, Let's Encrypt, HTTPS, HTTP Basic Auth) install without loosing the data I have?

You won't loose any data. Just make sure to not change the `volumes` section at the end of the file.

**Comment by IMgoRt** [comment]
> Aaaah, I guess you have to change db to database in the docker-compose.yml

Or change database to db in the back / restore commands ;-)
