### ISSUE TITLE
Add guard interval to charges to fix GPS display

### ISSUE THREAD

**Issue by markusdd** [adriankumpf/teslamate#366]
When looking at the charge details of a single charge, the map sometimes fails to display as last GPS info was transmitted evry shortly before charge started.
Zooming out just a little fixes this, so adding a few minutes of guard around the actual charge on the details dashboard should correct location display.

Example:

Location is correctly recorded:
![grafik](https://user-images.githubusercontent.com/25175069/72668282-85ba4700-3a25-11ea-8058-d8d908e8417b.png)

But when clicking on it I get this:
![grafik](https://user-images.githubusercontent.com/25175069/72668292-95d22680-3a25-11ea-9c35-42d89e0956e7.png)

Zooming out the timescale (not the map) just a little fixes location display:
![grafik](https://user-images.githubusercontent.com/25175069/72668326-d92c9500-3a25-11ea-91b7-b281ade64d2f.png)

Also, can the map location marker be made a little bit bigger? It is sometimes hard to see

**Comment by adriankumpf** [comment]
> Also, can the map location marker be made a little bit bigger? It is sometimes hard to see

The small red dot is already the best we can do with the map plugin. You can, however, move the mouse over the graph to get the blue marker.
