### ISSUE TITLE
Documentation Backup and Restore

### ISSUE THREAD

**Issue by GuBo88** [adriankumpf/teslamate#368]
I installed teslamate on a test raspberry and want to transfer now my collected data to my productive raspberry. I tried the Backup and Restore process.
In the backup script it is referred to database, I started with db. After changing database to db I get the error 'No container found for db_1'. How to solve this
Second point would be, can I change the name of 'db' to database at the restore?

It would be also good t have a documentation how t backup the database and restore it in general. Most people which use teslamate would like to keep there data and would like to store regularly a copy on other storage medium.

Thanks
GuBo

**Comment by shagberg** [comment]
To review the 'no container found' error, take a look at this issue (#363)

To review the instructions in the documentation on how to do a database backup and restore, review this link:
[https://teslamate.readthedocs.io/en/latest/maintenance/backup_restore.html](url)
