### ISSUE TITLE
Home dashboard: Grafana etc. strikethrough

### ISSUE THREAD

**Issue by GuBo88** [adriankumpf/teslamate#370]
Starting a newly installed teslamate. I got some timeout errors during installation. Finally anything seems to work well.
WhenI log in (Port 3000) I see on the Home Dashboard the the filling items a strikethrough:
Install Grafana
Create your firs data source
Create your first dashboard

What's wrong with the installation?

Thanks
GuBo

**Comment by shagberg** [comment]
The fact that the items on the Grafana dashboard have a strikethrough on them doesn't necessarily mean that there is anything wrong with your installation, mine has that as well.

If it is working, you would be able to view the Grafana dashboards in the top left corner, by clicking on the "Home" and then selecting the specific dashboard.

**Comment by adriankumpf** [comment]
This is the standard home dashboard you are looking at. It cannot be automatically customized by TeslaMate. If you are able to select the dashboards by clicking on "Home", then everything has been installed correctly, as @shagberg  has already said.
