### ISSUE TITLE
Re-opening https://github.com/adriankumpf/teslamate/issues/349

### ISSUE THREAD

**Issue by mboerma** [adriankumpf/teslamate#372]
Apparently one can not re-open an issue which you started... so here is the continuation of [https://github.com/adriankumpf/teslamate/issues/349](url)

I checked this with OSM and local members of OSM. The data is consistent and correct for the addresses. I can thus only assume that for some reason teslamate is doing things a bit different.

As an example the address that shows Netherlands gives the following in OSM:

Abcoude, De Ronde Venen, Utrecht, Netherlands, 1391EH, The Netherlands

same build up as the address the one below it:

Bullewijk, Amsterdam, North Holland, Netherlands, 1101EE, The Netherlands

You can see that both "Netherlands" and "The Netherlands" are used.

My only conclusion that in the case of "The Netherlands" or "Netherlands" there is something which creates this bug in teslamate or Grafana.

**Comment by adriankumpf** [comment]
TeslaMate reads the `country` from the [address struct](https://nominatim.org/release-docs/develop/api/Reverse/). If `country` does not exist it falls back to the `country_name`. No magic involved :-) You can actually see what was originally returned from OSM by looking at the `raw` column in `addresses` table. 

With the next release you'll be able to change the preferred language of the OSM results. I hope that the data is better maintained in the local language.

**Comment by mboerma** [comment]
Thanks for closing again without confirmation. Really weird. I checked with the community of OSM. The data is correct. Must be something else. Easy to say others are wrong. #teslamate_out
