### ISSUE TITLE
Teslamate errors in the log (408, 504)

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#374]
I get a lot of errors with code 504 and some with 408. For example:

```
teslamate_1  | 09:05:11.891 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 09:05:11.892 car_id=1 [warn] Error / upstream timeout
```
and
```
teslamate_1  | 16:31:33.769 [error] TeslaApi.Error / 408 – %{
teslamate_1  |   "error" => "vehicle unavailable: {:error=>\"vehicle unavailable:\"}",
teslamate_1  |   "error_description" => "",
teslamate_1  |   "response" => nil
teslamate_1  | }
```
Any chance to avoid that? Or is it just bad mobile reception resp. Tesla server hiccups?

**Comment by adriankumpf** [comment]
Yeah, these errors are occasionally returned by API for the reasons you mentioned. It's  not a big deal most of the time, and has no serious implications for logging.

If they occur over a longer period of time, parts of a drive _may_ be missing. But there is nothing that can be done about that ¯\_(ツ)_/¯
