### ISSUE TITLE
DB performance issues causing lots of small charges

### ISSUE THREAD

**Issue by gaardiolor** [adriankumpf/teslamate#377]
**Describe the bug**

Hello,

I got symptoms of #323 again, hundreds of small charges, on Version: 1.14.3 . It seems to be related to a database performance problem I am having (rebuilding my RAID).

**To Reproduce**

1. Make Postgres really slow
2. Charge
3. Observe many charges being created in grafana

**Expected behavior**

Would be nice though if a temporary database performance problem wouldn't result in 100's of small charges, especially since teslamate knows that the last known state was charging and the location didn't change. 

**Relevant entries from the logs**

```18:36:40.970 [error] Postgrex.Protocol (#PID<0.3514.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.25570.4> timed out because it queued and checked out the connection for longer than 15000ms
#PID<0.25570.4> was at location:
    :prim_inet.recv0/3
    (postgrex) lib/postgrex/protocol.ex:2837: Postgrex.Protocol.msg_recv/4
    (postgrex) lib/postgrex/protocol.ex:1879: Postgrex.Protocol.recv_bind/3
    (postgrex) lib/postgrex/protocol.ex:1771: Postgrex.Protocol.bind_execute/4
    (db_connection) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection) lib/db_connection.ex:539: DBConnection.parsed_prepare_execute/5
18:36:40.972 [error] GenStateMachine :"1" terminating
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto) lib/ecto/repo/schema.ex:656: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (teslamate) lib/teslamate/vehicles/vehicle.ex:795: TeslaMate.Vehicles.Vehicle.insert_charge/3
    (teslamate) lib/teslamate/vehicles/vehicle.ex:459: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib) gen_statem.erl:1161: :gen_statem.loop_state_callback/11
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
18:36:41.621 car_id=1 [info] Start / :online
18:37:11.007 car_id=1 [info] Charging / SOC: 68%
18:38:24.239 [error] Postgrex.Protocol (#PID<0.3515.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.25652.4> timed out because it queued and checked out the connection for longer than 15000ms
#PID<0.25652.4> was at location:
    :prim_inet.recv0/3
    (postgrex) lib/postgrex/protocol.ex:2837: Postgrex.Protocol.msg_recv/4
    (postgrex) lib/postgrex/protocol.ex:1879: Postgrex.Protocol.recv_bind/3
    (postgrex) lib/postgrex/protocol.ex:1771: Postgrex.Protocol.bind_execute/4
    (db_connection) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection) lib/db_connection.ex:539: DBConnection.parsed_prepare_execute/5
18:38:24.239 [error] GenStateMachine :"1" terminating
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto) lib/ecto/repo/schema.ex:656: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (teslamate) lib/teslamate/vehicles/vehicle.ex:795: TeslaMate.Vehicles.Vehicle.insert_charge/3
    (teslamate) lib/teslamate/vehicles/vehicle.ex:459: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib) gen_statem.erl:1161: :gen_statem.loop_state_callback/11
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
18:38:25.922 car_id=1 [info] Start / :online
```

**Screenshots**

See #323

**Data**
[teslamate_data.txt](https://github.com/adriankumpf/teslamate/files/4099527/teslamate_data.txt)

**Operating environment**

- TeslaMate Version: 1.14.3
- Type of installation: Mixed
- OS: Fedora 31

**Comment by adriankumpf** [comment]
The symptoms of #323 were definitely caused by a bug. This time could be different ... A reliable database connection is required to ensure stable operation. Otherwise we end up with database timeouts that are still handled but which can cause problems, especially when the car is driving or charging.

You mentioned a problem with database performance. What's that about?

**Comment by gaardiolor** [comment]
Well, I'm running btrfs raid1, added some disks and I needed to do a balance which, load-wise, can be compared with a rebuild. It makes things really slow. Teslamate apparently has a database connection timeout of 15 seconds, sometimes queries take longer. 

So assuming the small charges are linked to the DB performance (very likely imo): 
What, maybe, could be improved in teslamate, is handling such situations. The current way is causing data issues. What should happen is teslamate getting really slow, missing some charge updates, getting a little less fine-grained, but it should not result in the creation of many separate charging sessions. 

So possibly, under the hood, teslamate is checking in the database if there is an active session, if that query errors it creates a new one. I think it shouldn't do anything in that case and try again later?

**Comment by adriankumpf** [comment]
>  What should happen is teslamate getting really slow, missing some charge updates, getting a little less fine-grained, but it should not result in the creation of many separate charging sessions.

Well, easier said than done :-) That could be quite a hassle and lead to a number of problems elsewhere. If a handful of people come forward with the same problem, I'll think about it.

**Comment by gaardiolor** [comment]
@adriankumpf related (although not the same cause, it might require the same fix): container restarts during a charge session also create empty charges.

**Comment by adriankumpf** [comment]
Relevant: the default timeout was increased to 60 seconds and is configurable (via [`DATABASE_TIMEOUT`](https://teslamate.readthedocs.io/en/latest/configuration/environment_variables.html)) with the 1.16 release.
