### ISSUE TITLE
Diverse Browserbugs

### ISSUE THREAD

**Issue by albi** [adriankumpf/teslamate#381]
Hi Adrian,

habe soeben Teslamate installiert mit dem Advanced Docker install (Traefik) auf meinem Pi4 mit Buster. Alles ist aktuellster Stand (auf dem Pi und Mac), also alle Updates sind gemacht. Läuft bereits alles wunderbar. 

Mit Chrome habe ich soweit kein Problem, ich kann von aussen auf teslamate.meinedomain.de zugreifen, jedoch Safari macht hier Probleme. In der Console sehe ich die Fehlermeldung:

`WebSocket connection to 'wss://teslamate.meinedomain.de/live/websocket?baseUrl=https%3A%2F%2Fteslamate.meinedomain.de&referrer=&vsn=2.0.0' failed: Unexpected response code: 401`

Wobei ich sagen muss dass hier im Netzwerk auch noch Pi-Hole läuft. Aber selbst wenn ich das deaktiviere lädt das Login-Formular in Safari auch nicht. In Safari selbst laufen keine Plugins die irgendwas blocken könnten.

In Chrome bekomme ich in der Console aber folgende Fehlermeldung:

`GET https://teslamate.meinedomain.de/site.webmanifest?v=5AB53N3ALo 401`

Aber in Chrome scheint alles zu funktionieren.

Die Geofences laden keine Map. In keinem der beiden Browser. Wohlgemerkt alles ohne Pi-Hole aktiviert zu haben.

Gruss
Alex

**Comment by adriankumpf** [comment]
In Safari gibt/gab es einige Probleme (#261), die ich bisher allerdings nocht nicht reproduzieren konnte. In Chrome/Firefox sollte allerdings alles funktionieren. 

Da keine Map geladen wird, vermute ich, dass keine keine WebSocket-Verbindung hergestellt werden kann. Nutzt du eventuell vor Traefik noch einen weiteren Reverse-Proxy, der WS nicht durchlässt? Schau mal im Network Tab vom Browser nach, ob es irgendwelche Probleme in der Richtung gibt.

**Comment by albi** [comment]
Hmm ich blicke da nicht wirklich durch. Können wir privat chatten, dann kann ich dir alle Informationen zustellen.

**Comment by albi** [comment]
Hast du auch den Chrome Fehler mit dem Sitemanifest gesehen?

**Comment by adriankumpf** [comment]
> Hast du auch den Chrome Fehler mit dem Sitemanifest gesehen?

Der sollte bei einer regulären Installation eigentlich ebenfalls nicht auftreten, da die Datei existiert. 

Probier vielleicht erstmal die Basis-Installation und versuche direkt über Port 4000 auf die Weboberfläche zuzugreifen. Wenn dann die gleichen Fehler auftreten, muss die Fehlerquelle woanders liegen (Cookie-/Browsereinstellungen etc.)

**Comment by albi** [comment]
Also auf der regulären Installation tauchen die oben genannten Bugs nicht auf. Selbst die Geofences-Map lädt ohne Probleme mit Safari (latest).

**Comment by adriankumpf** [comment]
Ich schließe das mal, da der Fehler in #415 identifiziert wurde: https://github.com/adriankumpf/teslamate/issues/415#issuecomment-587158745 Als Alternative bleibt wohl vorerst nur, einen anderen Browser zu benutzen.
