### ISSUE TITLE
v1.15: Empty location for one line in "Top Charging Stations (Charged)"

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#382]
**Describe the bug**

With v1.5 I get an empty location in Top Charging Stations (Charged)"

**Expected behavior**

Location name should be there. I don't really know, which that could be.

**Screenshots**

![2020-01-23 15_36_36-Charging Stats - Grafana](https://user-images.githubusercontent.com/8087682/72993984-9805fd80-3df6-11ea-8f8b-71afa72eb87e.png)

**Data**

What should I pull from the database?

**Operating environment**

- TeslaMate Version: v1.5
- Type of installation: Docker
- OS: Ubuntu 18.04.3

**Comment by adriankumpf** [comment]
Has the migration mentioned in the changelog already been completed?

> ⚠️ Please note: Due to internal changes, all addresses will be recalculated on first startup. Depending on the amount of data, this process may take up to 30 minutes or longer.

If new entries like `Repairing drive #999` keep appearing in the log, it is still running.

**Comment by DrMichael** [comment]
You're right. The migration was still running. All is now correct.
