### ISSUE TITLE
Grafana piechart plugin missing

### ISSUE THREAD

**Issue by ctraber** [adriankumpf/teslamate#383]
Get an error in Charge-Stats dasboard in 1.15.

Seems a plugin is missing.

![0DD8B8DF-12DF-4743-8F0B-460B4B9487F4](https://user-images.githubusercontent.com/24205688/72994985-6b52e580-3df8-11ea-9349-ae06fbe5723b.jpeg)

**Comment by adriankumpf** [comment]
Docker or Manual install? If the latter is the case, you're gonna have to install the `grafana-piechart-panel` plugin.

**Comment by ctraber** [comment]
Docker, made a docker-compose pull.
Did the docker-compose.yml change?

**Comment by adriankumpf** [comment]
Hm. No changes made. Did you add any custom docker volumes? On startup usually Grafana (re)installs all plugins. Could you add the logs of the grafana container?

**Comment by ctraber** [comment]
According to the logs it is installed:
grafana_1    | installing grafana-piechart-panel @ 1.3.9
grafana_1    | from: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.3.9/download
grafana_1    | into: /var/lib/grafana/plugins
grafana_1    |
grafana_1    | ✔ Installed grafana-piechart-panel successfully
grafana_1    |


And after a reload of the page in the browser I get now this:
<img width="1019" alt="Bildschirmfoto 2020-01-23 um 16 29 17" src="https://user-images.githubusercontent.com/24205688/72998169-b15e7800-3dfd-11ea-8c29-580dd7183cf6.png">

**Comment by tobiasehlert** [comment]
had the same issue, but after restarting docker it magically appeared on one side, but not the other one.
also when hovering with the mouse, you can see values, but you don't see the pies.. kind of weird behavior.

**Comment by tucopup** [comment]
For what it's worth, I have 3 cars; car id 1 and 2 are missing the pie charts, though the labels can be seen with the mouse-hover.   Car id 3 pie charts are visible.  A manual restart had no effect.

**Comment by cwanja** [comment]
Had the same issue upon install - mouse over could provide the values. Restart of docker did not resolve the issue.

**Comment by MostDefiantly** [comment]
I see the same behavior as ctraber above, restart didn't help. 

"Could not draw pie with labels contained inside canvas"

**Comment by tucopup** [comment]
I notice that the pie chart displays when you click the dropdown "AC/DC -kwh" and select "view".  In my case, the two cars that don't display properly are >99% AC, while the one that does display properly is 56%/44% in AC/DC and 92%/8% in the duration.  More room in this one?

Can the labels be made to draw outside the pie?

**Comment by ctraber** [comment]
For my car the tooltips show 97,89 and 99,74 and both piecharts are not working with "Could not draw pie with labels contained inside canvas"

**Comment by MostDefiantly** [comment]
I figured it out, it's the fact the windows the pie charts are in are too small. If I drag the box containing the piechart to a larger size, then it then appears as expected.

It needs to be one "size" up from where it is to display properly at a minimum.

**Comment by twinor** [comment]
The legend position could be changed to be "Under graph" or "Right side" instead and it will always work regardless of window size and how thin the AC vs DC sliver is.

**Comment by adriankumpf** [comment]
Does anyone on v1.16 still have the problem?

**Comment by cwanja** [comment]
> Does anyone on v1.16 still have the problem?

Looks good @adriankumpf on v1.16

**Comment by ctraber** [comment]
The first one with kWh works now on my iPhone. The second with Durstion still not.

![8A0595CE-83B8-47CC-A3F7-A042AE334178](https://user-images.githubusercontent.com/24205688/74038500-9c1e4780-49c0-11ea-8c37-c7caee8cadf4.jpeg)
![502D8333-1088-45A7-A7D1-5D8155889818](https://user-images.githubusercontent.com/24205688/74038508-9e80a180-49c0-11ea-8969-27db9c3c8a45.jpeg)

**Comment by adriankumpf** [comment]
Okay, too bad. Then I guess the position of the legend has to be changed, as @twinor suggested, even though the current one looks slightly better imo.
