### ISSUE TITLE
1.15: dashboards not tagged correctly

### ISSUE THREAD

**Issue by holman** [adriankumpf/teslamate#384]
A minor thing, but these two dashboards didn't get slotted into my Teslamate bucket correctly:

<img width="1059" alt="Screen Shot 2020-01-23 at 9 20 24 AM" src="https://user-images.githubusercontent.com/2723/73007889-2f049280-3dc2-11ea-9b0e-d803d810ddd7.png">

Logs don't show any errors from the upgrade.

Tried to do a "move" on them in Grafana, but it gives me a `Access denied to save dashboard` error.

**Operating environment**

- TeslaMate Version: 1.15.0
- Type of installation: Docker
- OS: Ubuntu

**Comment by olexs** [comment]
I think this is intentional, because you're not supposed to manually navigate to these two boards - you only open them via detail links from "Charges" and "Drives". It's the same on my install.

**Comment by SigLinJo** [comment]
I have a related problem. Those two dashboards are placed in a subfolder in the guthub/teslamate/grafana/dashboards folder and making the wizzy export fail in my manual install. Moved Them out of the subfolder to make the wizzy export work again.

**Comment by adriankumpf** [comment]
@olexs already said it, this change was actually intended. I couldn't think of a better way to communicate that both dashboards should not be accesses directly but via the Charges/Drives dashbaord. If you have been using the dashboards regularly and/or you are now missing some information, we could create a dashboard for exactly this purpose.

**Comment by holman** [comment]
That makes sense! Just was worried it was something that didn’t get migrated properly in the update.

**Comment by adriankumpf** [comment]
Gotcha!
