### ISSUE TITLE
1.15: Grafana view Charges: Locations column some fields are empty

### ISSUE THREAD

**Issue by tobiasehlert** [adriankumpf/teslamate#385]
**Describe the bug**

The grafana dashboard Charges does not display the location anymore at some rows. It is both for locations, that I use goe-fencing on and some that I don't, are shown faulty.

In addition, the "Charging stats" do show top location without name, since it's calculating all locations it is missing the name on as one location.

**To Reproduce**

1. Go to 'Grafana'
2. Click on 'Charges' dashboard
3. See the column 'Location', which are blank at some of the locations you have charged.

**Expected behavior**

To show the correct location address.

**Relevant entries from the logs**

Nothing in the logs related to this as what I can see..

```
paste logs here
```

**Screenshots**

![screenshot-charges-missing-names](https://user-images.githubusercontent.com/4417850/73017476-3195d500-3e20-11ea-916c-8d0bb8685d88.png)

**Operating environment**

- TeslaMate Version: v1.15.0
- Type of installation: Advanced Docker Setup with Traefik
- OS: CentOS 7

**Comment by adriankumpf** [comment]
Related: https://github.com/adriankumpf/teslamate/issues/382#issuecomment-577713064 ?

**Comment by tobiasehlert** [comment]
Oh yeah.. sorry @adriankumpf it looks like it is that!
Now I see that two locations appeared.. so I guess that's it.

I just noticed two types of errors being thrown as well.

Error 1:

`teslamate_1  | 19:30:49.373 [info] Repairing drive #83 ...
teslamate_1  | 19:30:50.942 [error] GenServer #PID<0.6068.0> terminating
teslamate_1  | ** (FunctionClauseError) no function clause matching in Mojito.ConnServer.apply_resp/2
teslamate_1  |     (mojito) lib/mojito/conn_server.ex:113: Mojito.ConnServer.apply_resp(%{conn: %Mojito.Conn{conn: %Mint.HTTP2{buffer: "", client_settings: %{enable_push: true, max_concurrent_streams: 100, max_frame_size: 16384}, client_settings_queue: {[], []}, decode_table: %Mint.HTTP2.HPACK.Table{entries: [{"content-type", "application/json; charset=UTF-8"}, {"expect-ct", "max-age=0, report-uri=\"https://openstreetmap.report-uri.com/r/d/ct/reportOnly\""}, {"strict-transport-security", "max-age=31536000; includeSubDomains; preload"}, {"access-control-allow-methods", "OPTIONS,GET"}, {"access-control-allow-origin", "*"}, {"server", "Apache/2.4.29 (Ubuntu)"}, {"date", "Thu, 23 Jan 2020 19:31:25 GMT"}], length: 7, max_table_size: 4096, size: 551}, encode_table: %Mint.HTTP2.HPACK.Table{entries: [], length: 0, max_table_size: 4096, size: 0}, headers_being_processed: nil, hostname: "nominatim.openstreetmap.org", mode: :active, next_stream_id: 7, open_client_stream_count: 0, open_server_stream_count: 0, ping_queue: {[], []}, port: 443, private: %{}, ref_to_stream_id: %{}, scheme: "https", server_settings: %{enable_push: true, initial_window_size: 65535, max_concurrent_streams: 100, max_frame_size: 16384, max_header_list_size: :infinity}, socket: {:sslsocket, {:gen_tcp, #Port<0.618>, :tls_connection, :undefined}, [#PID<0.6415.0>, #PID<0.6414.0>]}, state: {:goaway, :no_error, "timeout"}, streams: %{}, transport: Mint.Core.Transport.SSL, window_size: 2147483647}, hostname: "nominatim.openstreetmap.org", port: 443, protocol: :https}, hostname: "nominatim.openstreetmap.org", port: 443, protocol: "https", reply_tos: %{#Reference<0.1241467445.3910926337.162274> => #PID<0.3687.0>}, response_refs: %{#Reference<0.1241467445.3910926337.162274> => #Reference<0.1241467445.3910926337.162265>}, responses: %{#Reference<0.1241467445.3910926337.162274> => %Mojito.Response{body: [], complete: false, headers: [], status_code: nil}}}, {:error, #Reference<0.1241467445.3910926337.162274>, %Mint.HTTPError{module: Mint.HTTP2, reason: :unprocessed}})
teslamate_1  |     (mojito) lib/mojito/conn_server.ex:110: Mojito.ConnServer.apply_resps/2
teslamate_1  |     (mojito) lib/mojito/conn_server.ex:85: Mojito.ConnServer.handle_info/2
teslamate_1  |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
teslamate_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.618>, :tls_connection, :undefined}, [#PID<0.6415.0>, #PID<0.6414.0>]}, <<0, 0, 15, 7, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 116, 105, 109, 101, 111, 117, 116>>}
teslamate_1  | 19:30:55.874 [warn] Address not found: :timeout`


Error 2:

`teslamate_1  | 19:40:03.580 [info] OK
teslamate_1  | 19:40:03.580 [error] GenServer TeslaMate.Repair terminating
teslamate_1  | ** (FunctionClauseError) no function clause matching in TeslaMate.Repair.handle_info/2
teslamate_1  |     (teslamate) lib/teslamate/repair.ex:29: TeslaMate.Repair.handle_info({#Reference<0.1241467445.3910926337.102913>, :ok}, nil)
teslamate_1  |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
teslamate_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: {#Reference<0.1241467445.3910926337.102913>, :ok}`

Maybe something that you want to dig in? :)

**Comment by adriankumpf** [comment]
It looks worse than it is :) Just timeouts thrown by OSM. After too many timeouts it'll stop for a while. But the migration will continue until every address was recomputed.

**Comment by tobiasehlert** [comment]
Awesome, thanks @adriankumpf
