### ISSUE TITLE
Feature request: cost calculation based on geo-fencing location

### ISSUE THREAD

**Issue by tobiasehlert** [adriankumpf/teslamate#386]
**Is your feature request related to a problem? Please describe.**

Most people charge at a few locations always, which are connected to a cost based on how many kWh you charge.

**Describe the solution you'd like**

I would like to be able to add to the geo-fencing feature, what the rate is for each kWh charged at that location. For example in Sweden, at a Supercharger location, that would be 2.56 SEK per kWh.

On this way, I don't need to add the cost on every charging session I do and the cost can automatically be calculated.

Geo-fencing locations that don't have a cost set, that would then not be rated at all. So you can still do a manual setting of your cost.

Then IF you for example charge at home, and have different rates on different times of the day, the cost could be faulty or course, when doing the calculation that way. So when changing at home at a lower rate and you want to adjust the cost, you should be able to override the cost by setting it in the gui.

**Describe alternatives you've considered**

Sitting and do a lot of manual adding of costs :)

**Additional context**

no

**Comment by cwanja** [comment]
Yes. please. 🙏

**Comment by shagberg** [comment]
When I first saw this feature, I assumed that this was the way that it was going to work - I was surprised when it didn't work this way.

+1 for this feature request

**Comment by olexs** [comment]
One problem I see is that the kWh reported by the charger is almost always slightly higher that what's reported as received by the car (due to charging losses). A calculated value would be slightly lower than what you are actually charged.

**Comment by bahree** [comment]
I have a clarifying question - how does the current implementation work? When I get to the charge cost page - is that amount per kwh or do I calculate the total myself and then enter it? And would I need to do it for every instance of that?

And another +1 for adding the charging cost per kwh in the geofence and use that - also. I suspect many folks are like me - and usually charge at a set location - be it at home or work or something and know the cost per kwh. And the odd time when on the road or another location - then the current implementation would work - where it might not be per kwh necessarily but part of a car park or similar.

Thanks.

**Comment by cwanja** [comment]
> is that amount per kwh or do I calculate the total myself and then enter it? 
Total cost. 
> And would I need to do it for every instance of that?
In the current implementation, yes.

**Comment by DrMichael** [comment]
+1

Set prices should only be used for future charges...

**Comment by ngardiner** [comment]
Cost per kWh is not the only basis on which costs might be calculated.

For some, different tariffs will apply. Some chargers charge by time connected and kWh tarrif, some charge a set amount per charge.

Whilst it would be a useful mechanism for a lot of people, it shouldn't be the only basis on which a charge cost is calculated. If it were, it would make a lot of the values I've input manually from invoices suddenly incorrect. It would be of little use for someone who wanted to record charging for business/work purposes if it didn't match, for example.

Whilst there is a vocal majority here it seems, I do want to put my voice to the point that it would not be universally correct to automatically calculate all charge costs and should be an option, not enforced.

**Comment by DrMichael** [comment]
Oh, right, cost per kWh, cost per time, one time cost. Any others?

And @ngardiner well it will never be 100% because there is a difference between what the car reports and what has been really withdrawn. So, it will be just an indication.

And, yes, sure, it should be optional. When nothing is set for a location, nothing is put in as costs. And, it should always be possible to set/change the cost manually.

**Comment by olexs** [comment]
> Oh, right, cost per kWh, cost per time, one time cost. Any others?
Some tariffs here in Germany apply an additional per minute cost starting after a certain time - e.g. Maingau charges 35c/kWh + 10c/minute starting after 4 hours AC or 1 hour DC. It's straightforward enough to model in software, but there are many possible variations, covering all possible tariff cases would get complicated eventually.

**Comment by ctraber** [comment]
Costs depending on daytime.
I pay less per kWh between 22:00h and 06:00h.

**Comment by shagberg** [comment]
I pay a cheaper electric rate in the summer versus the winter.

But I figure I could manually change the kWh rate in TeslaMate when the rates change.

**Comment by wishbone1138** [comment]
I agree that there are many possibilities with charging but a geofenced cost per kWh option seems like it would be the most convenient for the largest amount of people.  Plus, most of us try to only charge our vehicles at our home location while on the cheapest rate.

**Comment by tobiasehlert** [comment]
One thing that I just realize is, that it maybe should not be geo-location specific only, since if you got both a Model S with free Supercharge and an Model 3 with payment per kWh, the cost would end up differently at a Supercharger as well.
But that is maybe something that could be a conditional setting on a car that is flagging the car to have free supercharging and that it then adjusts the charing cost on that location.

**Comment by Tigwin** [comment]
I'd be more than happy with supercharger rate and level 2 charging rate. 28 cents and 13 cents for me.

**Comment by picard001** [comment]
I'd wager coding for geofence pricing would be a great start.  I primarily charge at home at night, and although I have hourly pricing, I would average the rate for the time I normally charge.  Then have a blanket AC charging rate (by checking phases?).

I can manually enter supercharger visits, or that could be a feature added at a later date as it's more complex to implement with free supercharging, kWh pricing, time based pricing (based on charge level), etc.

**Comment by ArnoPW** [comment]
+1 for geofence cost/kWh and count with that. If nothing is filled in than it should be good to be able to manually enter a charge cost. That way it's also possible to update it on occasional charge locations and for those who update costs after having received an invoice.

**Comment by DrMichael** [comment]
Uuuuh, krass. Danke @adriankumpf

**Comment by cwanja** [comment]
@adriankumpf is there a way to back fill previous charge cost once the geofence cost has been set? Or is the only way maybe through a database write?

**Comment by adriankumpf** [comment]
In the current implementation that would have to be done manually through a database query. For example for the geo-fence with the ID  `1` (visible in the URL when editing a geo-fence):

["Connect" to the database container](https://teslamate.readthedocs.io/en/latest/maintenance/manually_fixing_data.html). Then:

 ```SQL
  UPDATE charging_processes cp
  SET cost = (
    SELECT g.cost_per_kwh * c.charge_energy_used 
    FROM charging_processes c 
    JOIN geofences g ON g.id = c.geofence_id 
    WHERE cp.id = c.id
  )
  WHERE cp.geofence_id = 1 AND cp.cost IS NULL;
  ```

**Comment by natrlhy** [comment]
Thanks for this! Easy and now all costs are accounted for! Amazing release!

**Comment by nottheedge** [comment]
I think it would make sense also to add an option for flat-rate charging on some geofences.

**Comment by natrlhy** [comment]
How does one "filter" or only select say "Home" and gather a total of those charge? :)

**Comment by cwanja** [comment]
> How does one "filter" or only select say "Home" and gather a total of those charge? :)

@natrlhy - lower right hand corner of the Charging Stats dashboard?

**Comment by natrlhy** [comment]
> > How does one "filter" or only select say "Home" and gather a total of those charge? :)
> 
> @natrlhy - lower right hand corner of the Charging Stats dashboard. Confirmed it is there by location.

Awesome! Forgot about this dashboard! Thanks!

**Comment by Toasterme** [comment]
> In the current implementation that would have to be done manually through a database query. For example for the geo-fence with the ID `1` (visible in the URL when editing a geo-fence):
> 
> ["Connect" to the database container](https://teslamate.readthedocs.io/en/latest/maintenance/manually_fixing_data.html). Then:
> 
> ```sql
>  UPDATE charging_processes cp
>  SET cost = (
>    SELECT g.cost_per_kwh * c.charge_energy_used 
>    FROM charging_processes c 
>    JOIN geofences g ON g.id = c.geofence_id 
>    WHERE cp.id = c.id
>  )
>  WHERE cp.geofence_id = 1 AND cp.cost IS NULL;
> ```

You help me correct my cost.
At first i input the wrong value, and even if i changed it from the GUI, it didn't modify all the original value in the DB.

So step 1: put all cp.cost to null: 
`teslamate=# UPDATE charging_processes SET cost=NULL WHERE geofence_id=1;`

Then step 2, using your query, but with this motification of the g.cost_per_kwh to g.cost_per_unit because : 
`teslamate=# select * from geofences;
 id |  name  | latitude  | longitude  | radius |     inserted_at     |     updated_at      | cost_per_unit | session_fee | billing_type
----+--------+-----------+------------+--------+---------------------+---------------------+---------------+-------------+--------------
  1 | House | xxx | yyy |     35 | 2021-03-18 20:03:40 | 2021-09-27 13:24:28 |        0.1080 |             | per_kwh
(1 row)`

So  : 
`teslamate=#  UPDATE charging_processes cp
 SET cost = (
   SELECT g.cost_per_unit * c.charge_energy_used
   FROM charging_processes c
   JOIN geofences g ON g.id = c.geofence_id
   WHERE cp.id = c.id
 )
 WHERE cp.geofence_id = 1 AND cp.cost IS NULL;
UPDATE 82`
