### ISSUE TITLE
Can't move Grafana dashboards 

### ISSUE THREAD

**Issue by albi** [adriankumpf/teslamate#387]
Hi Adrian,

I can't move the two dashboards to teslamate. Don't know why they are in the wrong folder.

![Bildschirmfoto 2020-01-24 um 09 05 41](https://user-images.githubusercontent.com/89451/73054135-e7e1d480-3e89-11ea-979c-4dec1b78cd2a.png)

Alex

**Comment by olexs** [comment]
Duplicates #384 . See my answer there why this is intentional/not a bug.
