### ISSUE TITLE
Questions on the 'Manually fixing data' document

### ISSUE THREAD

**Issue by shagberg** [adriankumpf/teslamate#389]
I have two question on the 'Manually fixing data' document:
https://teslamate.readthedocs.io/en/latest/maintenance/manually_fixing_data.html

1) The instructions say to find the drive ID by opening the 'Drives' dashboard and clicking on the start date of the drive. When I do that, the URL is formatted like this:
`https://fqdn.zzzzz.com/d/zm7wN6Zgz/drive-details?orgId=1&from=1579570230000&to=1579570808000&var-car_id=1`, and there is no drive ID in the URL. Do the instructions need to be updated or am I doing something wrong?
2.) In the query example, you do an update statement on the drives table where the drive_id = 9999 and then you delete that same row afterwards. Is the update statement necessary, since you are deleting it?

[Edit: I'm on version 1.15]

Thanks!

**Comment by adriankumpf** [comment]
1. You did nothing wrong. The ID was missing if the length unit was set to miles. Fixed with v1.15.1.
2. Yup, it's necessary. To see why, just try it without committing the transaction :-)

**Comment by shagberg** [comment]
Confirmed working with v1.15.1, thanks Adrian!
