### ISSUE TITLE
Charge detail page shows "Internal"

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#391]
When navigating to the charge detail page, on the top left instead of Teslamate, it shows internal. Seems to be working OK, just the label/title. Minor issue, not a deal breaker. See attached image.

![Capture-charge detail](https://user-images.githubusercontent.com/3529468/73124852-0d87e000-3f55-11ea-923c-e6d5d3eb290c.JPG)

**Comment by cwanja** [comment]
See conversations in #384

**Comment by bahree** [comment]
Thanks @cwanja just saw that 👍; I did navigate to them via the charges page, to get to the details, and that is when this is showing. So not sure then if it is still supposed to show internal or not.

**Comment by cwanja** [comment]
I think the intention is that you never browse to those pages individually, but from the charge or drive table. As such, they are "buried" in their own folder out of the main dashboards. The "internal" is the folder that they are in. As such, it is displaying correctly. Best way I have seen to get back to the table view of charges or drives is just to swipe or click "back" in your browser of choice.
