### ISSUE TITLE
Battery health issue

### ISSUE THREAD

**Issue by zxerqw** [adriankumpf/teslamate#3990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Database query error

`db query error: pq: invalid input syntax for type json`

### Expected Behavior

Health stats should be displayed...

### Steps To Reproduce

Go to `Battery Health`

### Relevant log output

```shell
teslamate  | 2024-06-23 12:25:10.837 [info] Migrations already up
teslamate  | 2024-06-23 12:25:15.336 [info] No tzdata release files found in custom data dir. Copying release file from tzdata priv dir.
teslamate  | 2024-06-23 12:25:15.553 [info] System Info: Erlang/OTP 26 (jit)
teslamate  | 2024-06-23 12:25:15.553 [info] Version: 1.29.2
teslamate  | 2024-06-23 12:25:15.892 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (256.350 ms)
teslamate  | 2024-06-23 12:25:15.893 [info] Refreshed api tokens
teslamate  | 2024-06-23 12:25:15.945 [info] Scheduling token refresh in 6 h
teslamate  | 2024-06-23 12:25:15.959 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate  | 2024-06-23 12:25:15.961 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate  | 2024-06-23 12:25:16.126 [info] Starting logger for 'FalconX'
teslamate  | 2024-06-23 12:25:16.143 [info] MQTT connection has been established
teslamate  | 2024-06-23 12:25:16.157 [info] Repairing drive #260 ...
teslamate  | 2024-06-23 12:25:16.247 car_id=2 [info] Start / :offline
teslamate  | 2024-06-23 12:25:19.420 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 01 Feb 2024 18:40:48 GMT.
teslamate  | 2024-06-23 12:25:22.640 [info] Tzdata has updated the release from 2021e to 2024a
```

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/16666177/a72a9698-ef2e-4ee9-8e4c-08c17fd7c0f1)
![image](https://github.com/teslamate-org/teslamate/assets/16666177/8d18f777-e662-4d23-9373-48233830094d)
![image](https://github.com/teslamate-org/teslamate/assets/16666177/7c88509c-23a2-4dac-bb7e-9bf1593765e0)

### Additional data

Hello, 
`https://github.com/teslamate-org/teslamate/issues/3735`
I searched for similar questions and it looks like they were automatically restored, but my problem seems to persist, I've been having this problem for about a month now after installing teslamate, the error when I click edit seems to be a database problem,  I have a MODELY that Tesla gave me and they added it to my account but removed it after a few days, I'm not sure if that's what's causing the problem or not!

### Type of installation

Docker

### Version

v1.29.2

**Comment by odinms** [comment]
It needs 3 times of battery charge, each under 95% , to make the battery health dashboard work. Have u done that? 
Teals docs write this note very clearly..

**Comment by wangkang0726** [comment]
hi, Have you solved the problem?  
![5901731659013_ pic](https://github.com/user-attachments/assets/d79868d5-5bad-4909-a34e-4a20d712592b)
![5911731659098_ pic](https://github.com/user-attachments/assets/5dae84a7-af66-4523-98de-5cd562da2b22)
