### ISSUE TITLE
smtp settings

### ISSUE THREAD

**Issue by d33pa** [adriankumpf/teslamate#400]
I have been battling with this issue for a couple nights now, hoping someone can point me in the right direction. I am pretty green on this, but like to think I am quick learner.
I installed teslamate by means of Advanced Docker Setup with Traefik, followed instructions from ..readthedocs.io. I have it up and running on AWS, thanks for this! 
Now I am trying to get the notifications working, i need to setup email smtp settings. Since this is docker setup, I assume all the settings need to be on the docker-compose.yml; I think I cant get the format correct (maybe?).
Without any config I get the error when trying test notification:
"SMTP not configured, check your grafana.ini config file's [smtp] section"

since this is a docker image and not conventional install, I cant find the .ini files to edit (as I assume they are in the image of the container)

In server admin settings, all default:
smtp |  
-- | --
cert_file |  
ehlo_identity |  
enabled | false
from_address | admin@grafana.localhost
from_name | Grafana
host | localhost:25
key_file |  
password | ************
skip_verify | false
user

i have added to the docker-compose.yml as follows, but no love.
grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
      *****ADDED THE INFO BELOW*******
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=email-smtp.xxx-xxx-.amazonaws.com:25
      - GF_SMTP_USER=myusername
      - GF_SMTP_FROM_ADDRESS=grafana@mydomain.com
      - GF_SMTP_PASSWORD=mypassword
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=3000'
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana-insecure.rule=Host(`${FQDN_GRAFANA}`)"
      - "traefik.http.routers.grafana-insecure.middlewares=redirect"
      - "traefik.http.routers.grafana.rule=Host(`${FQDN_GRAFANA}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=tmhttpchallenge"

Any help to point me in the right direction would be greatly appreciated!

**Comment by adriankumpf** [comment]
Take a look at this post: https://community.grafana.com/t/smtp-configuration-for-docker-container/16370

To navigate the files in the docker container:

```
docker-compose exec grafana bash
```

You can also create a custom volume with your ini file (located at `/etc/grafana/grafana.ini`).

**Comment by d33pa** [comment]
Thanks for pointing me in the right direction! CLosing.
