### ISSUE TITLE
Vampire Drain details missing

### ISSUE THREAD

**Issue by timguy99** [adriankumpf/teslamate#404]
Vampire Drain dashboard missing TR Loss, kWh, Power, TR Loss / h.

These are all the latest ones that also have the new snowflake icon.

Is this the same issue as #390? If its the same sort of thing on the numbers not being accurate I would prefer to see them anyway. They always seemed to make sense to me whether it was under cold conditions or not.

**Comment by bpankz** [comment]
just checked my vampire drain and noticed the same thing. also my tr loss/h is in km instead of miles.
![image](https://user-images.githubusercontent.com/54423181/73232281-b77f8c00-4150-11ea-9b4b-231542f1bdfd.png)

**Comment by BabyYeggie** [comment]
Just change the SQL in the panel as follows:

CASE WHEN has_reduced_range THEN 1 ELSE 0 END as has_reduced_range,
	convert_km(~~CASE WHEN has_reduced_range THEN NULL ELSE~~ (v.start_range - v.end_range) ~~END~~, '$length_unit') AS range_diff_$length_unit,
  ~~CASE WHEN has_reduced_range THEN NULL ELSE~~ (v.start_range - v.end_range) * c.efficiency ~~END~~ AS consumption,
  ~~CASE WHEN has_reduced_range THEN NULL ELSE~~ ((v.start_range - v.end_range) * c.efficiency) / (v.duration / 3600) * 1000 ~~END~~ as avg_power,
  convert_km(~~CASE WHEN has_reduced_range THEN NULL ELSE~~ (v.start_range - v.end_range) / (v.duration / 3600) ~~END~~, '$length_unit') AS range_lost_per_hour_km

**Comment by bpankz** [comment]
worked for me. the last column shows km even though the visualization says miles but its enclosed in a convert_km so it should be miles right? just the label is wrong?

**Comment by timguy99** [comment]
to make it a little simpler to edit I changed mine to `CASE WHEN FALSE` so that it always triggers the true column. OR, you make it so that `has_reduced_range` is always false but then you lose the snowflake icon. In the Drives dashboard (for similar fix) I think it is `CASE WHEN TRUE` because its using reverse logic to display or not.

**Comment by adriankumpf** [comment]
The vampire drain is calculated based on the lost range. If the battery cools down due to cold weather and thus the range is artificially reduced, it is not possible to determine the Vampire drain accurately.

See #390 for solutions on how to display those values anyway. However, I would recommend to use the SOC difference if the consumption values cannot be determined instead of relying on incorrect data.
