### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by mikeh2010** [adriankumpf/teslamate#406]
I've just got the Advanced Docker install working with Apache2 - after a discovering which modules need to be loaded - woop!

However a couple of dashboard questions arise;

**Efficiency**
N/A in 'consumption (net)' so the rest doesn't work

**Drives**
No kWh recorded

**Drive Stats**
Again, no kWh recorded

**Charging Stats**
Total Charging Cost N/A
Both graphs _could not draw pie with labels contained inside canvas_
 
Also, **speed/distance** is in km/h NOT mph ?!

I'm not sure what I've done wrong or indeed how to fix it.
Any advice appreciated.

**Comment by adriankumpf** [comment]
You've done nothing wrong. Relevant issues: https://github.com/adriankumpf/teslamate/issues/390, https://github.com/adriankumpf/teslamate/issues/383 and [FAQ](https://teslamate.readthedocs.io/en/latest/faq.html)
