### ISSUE TITLE
Using Older Commit on Simple Docker Setup?

### ISSUE THREAD

**Issue by gursky** [adriankumpf/teslamate#407]
**Short question:** Using the Simple Docker Setup is it possible to get Teslamate up and running the first time using an older commit?  In the docker-compose.yml file could I specify the commit hash instead of _latest_ (example: teslamate:_0716569_ instead of :_latest_)?

```
services:
  teslamate:
    image: teslamate/teslamate:latest
```

**Additional details:** My original installation of Teslamate was done on a BeagleBone Black system.  I accidentally installed everything to the onboard storage and ran out of space after a few months.  I was unable to free up sufficient space to do further updates and while I tried to migrate the Docker image to a larger SD card my inexperience with Ubuntu and limited patience got the best of me. 

I will now be running Teslamate on a Raspberry Pi and ensuring I run everything off of a large enough SD card.  I have an export of the postgres database and will use that to migrate my driving data over.  I am hesitant on installing Teslamate with the latest branch in case there are DB changes that would prevent me from using my DB backup so I would like to start with an older version (v 1.12.2 is what I am currently running), import the DB backup and then upgrade Teslamate. 

Is this possible with the Simple Docker Setup or do I need to look at advanced installation options?  Do I need to reference older environment variables for postgres or mosquito?

Thanks!

**Comment by adriankumpf** [comment]
Take a look at the tags available on DockerHub: https://hub.docker.com/r/teslamate/teslamate/tags

Simply replace `latest` with the `1.12.2`, pull the image and restart.

**Comment by gursky** [comment]
Excellent, thanks for the quick response, this is exactly what I need!
