### ISSUE TITLE
Something better than basic auth?

### ISSUE THREAD

**Issue by wishbone1138** [adriankumpf/teslamate#413]
I'm looking for suggestions on using a docker on a non-trusted network.  I've got basic auth setup with Apache, but Tesla's web browser apparently does not support it.  At least I couldn't find a way to get it to work, common syntax of username:password@ in the URL didn't seem to work.  Should the project move to it's own auth model?  (already supported on the grafana side)

**Comment by ngardiner** [comment]
I've used an nginx reverse proxy with vouch-proxy (search on GitHub) for
auth. This works fine for me via the tesla browser.

**Comment by Tigwin** [comment]
I just disabled port 4000 on the firewall except when i need to access the teslamate service. not great but its a lot less work than the other options.

**Comment by adamrutt** [comment]
> I've used an nginx reverse proxy with vouch-proxy (search on GitHub) for auth. This works fine for me via the tesla browser.

+1 for vouch-proxy bit of mucking around to get set up with nginx but very elegant solution and many choices of identity provider

**Comment by marcogabriel** [comment]
I stumbled across Authelia a while ago. It looks promising, but I didn't manage to get it up and running. It has a huge list of dependencies what maybe makes it hard to integrate.

https://github.com/authelia/authelia

But there is already a docker image which may be easier to integrate. Need to try it... 

https://hub.docker.com/r/authelia/authelia

**Comment by skyfox14** [comment]
I'm usging Cloudflare Access. Very easy to setup and free for 5 users.

**Comment by tacotran** [comment]
After having a bad time accessing the BasicAuth setup (just logging in is a PITA) I played around a bit and set up a basic login page via html. It doesn't differ from the BasicAuth setup too much.

You just need mod_auth_form and a basic html login page.

**Comment by rtega** [comment]
I'm using https://username:password@hostname:port/ in the webbrowser of my tesla. It works like a charm. This is in a tesla model 3. Maybe this only works when you have SSL setup properly.
