### ISSUE TITLE
Incorrectly displays 2 phase charging (while really there are 3)

### ISSUE THREAD

**Issue by ArnoPW** [adriankumpf/teslamate#414]
When charging the car (Tesla Model 3 SR+) at home on a 3-phase 230V connection (in the Netherlands), the Internal - Charge Details shows 2 phases where there are really 3 phases. Charging is done at 8A max (out of 16) and is correctly displayed as charging at 6kW (just as shown in the car and in the Tesla app). I checked the kWh-meter connected to the charger and this has all three phases delivering power.

I saw in the release notes that a change has been made for this in version 1.14.0 but it looks like it is not working for me in version 1.15.1.

**Operating environment**

- TeslaMate Version: v1.15.1
- Type of installation: Docker
- OS: Synology NAS DSM version: 6.2.2-24922-4
![chargedetails](https://user-images.githubusercontent.com/52374663/73599252-db244700-4541-11ea-8ccd-9ff2d9e446e0.png)

**Comment by adriankumpf** [comment]
This is an issue with some cars, especially Model 3, that always report two-phase charging. For this reason an automatic phase correction was introduced with version v1.14.  Grafana displays the values only as they were originally reported by the car, i.e. the phase correction is independent of the displayed values.

**Comment by ArnoPW** [comment]
Okay thanks for explanation. In that case I think there's not a lot that can be done now so I'll close this ticket.

**Comment by woyteck1** [comment]
Can you do something that tells, "if phases=2 show as phases=3" ?

**Comment by woyteck1** [comment]
Suggested fix (only visual but that's good enough IMHO) in my pull request: https://github.com/adriankumpf/teslamate/pull/2527
