### ISSUE TITLE
Safari: Traefix + Teslamate default page not loading location - err 401 unauthorized

### ISSUE THREAD

**Issue by baylanger** [adriankumpf/teslamate#415]
[edit begin] 
MacOS Safari 13.0.5 has the below issue with latest Catalina 10.15.3 - not sure for previous versions.  Perhaps when opening the new tab some identity isn't pass properly?
MacOS Firefox seems to work just fine.
[edit end]

When I go to http://teslamate.xxxx.com:4000/ the page loads fine and shows my current car location.

But when I go to https://teslamate.xxxx.com:4443/ ... everything loads fine _except_ the current car location never load... the web-socket reports a 401.

**To Reproduce**

1. Configure Teslamate with docker+Traefix
2. Goto https://teslamate.xxxxxx.com:4443/
3. See car location not loading

**Expected behavior**

It should show the car's location.

Safari web console reports :

```WebSocket connection to
wss://teslamate.XXXXXX.com:4443/live/websocket?_csrf_token=SOME_LONG_TOKEN&baseUrl=https%3A%2F%2Fteslamate.XXXXXX.com%3A4443&referrer=&vsn=2.0.0
failed: Unexpected response code: 401
```

When going to port teslamte:4000 , that works fine.

**Screenshots**

In the screenshot, the spinning wheel doesn't appear like a spinning wheel.. but it is spinning :)

![2020-02-02_10-59-52](https://user-images.githubusercontent.com/5240348/73611171-0db75980-45ad-11ea-9315-86b7c534ff5e.png)

**Operating environment**

- TeslaMate Version: [e.g. v1.15.1]
- Docker w/ traefix
- OS: debian

Let me know if you need more information.

**Comment by Squachen** [comment]
Try clearing all cache for the domain in safari and then open the https site.

I've seen many problems with safari and websockets in other projects. Some of them could be
fixed by clearing cache.

**Comment by baylanger** [comment]
@Squachen thanx for the suggestion but that's not working.  Perhaps one f the latest Safari feature to protect identity might be causing that.  When I have time, I'll try to dig more.

**Comment by baylanger** [comment]
@adriankumpf this is dup to `ΩDiverse Browserbugs`  https://github.com/adriankumpf/teslamate/issues/381

**Comment by MattW-AltAtWork** [comment]
old old bug with Safari and websockets w/Basic Auth:   https://bugs.webkit.org/show_bug.cgi?id=80362   I can't believe they have never fixed this.

**Comment by MattTW** [comment]
old old bug with Safari and websockets w/Basic Auth: https://bugs.webkit.org/show_bug.cgi?id=80362 I can't believe they have never fixed this.

**Comment by baylanger** [comment]
Last night I noticed Safari 13.3.1 seems to fix this issue and before I could report back. this morning I wake up and bot closed it.  Can't re-open so added a comment.

![2020-04-26_09-56-14](https://user-images.githubusercontent.com/5240348/80309676-80973180-87a4-11ea-9686-48f075ffeab3.png)

**Comment by baylanger** [comment]
Never mind my previous comment, didn't realize the above is over http.  Tim didn't pay attention to my Tweet :D
