### ISSUE TITLE
Owner API returns 404 - vehicle_not_found

### ISSUE THREAD

**Issue by ivanovd** [adriankumpf/teslamate#4154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After updating to 2024.26.7 Teslamate stopped logging anything. I have two instances, one on my local NAS (manual install on FreeBSD) and one on Azure (Docker install) - both stopped showing data right after the update. I logged out and logged back in, restarted the instances ... nothing helped. Both are accessible via the Internet.

<img width="763" alt="image" src="https://github.com/user-attachments/assets/09312fb9-6c05-43bb-9988-131d7214697f">

### Expected Behavior

Teslamate to be logging my drives

### Relevant log output

```shell
teslamate-teslamate-1  | 2024-08-22 16:57:02.774 [info] Migrations already up
teslamate-teslamate-1  | 2024-08-22 16:57:06.221 [info] System Info: Erlang/OTP 26 (jit)
teslamate-teslamate-1  | 2024-08-22 16:57:06.221 [info] Version: 1.30.1
teslamate-teslamate-1  | 2024-08-22 16:57:06.750 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (442.971 ms)
teslamate-teslamate-1  | 2024-08-22 16:57:06.751 [info] Refreshed api tokens
teslamate-teslamate-1  | 2024-08-22 16:57:06.765 [info] Scheduling token refresh in 6 h
teslamate-teslamate-1  | 2024-08-22 16:57:06.772 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate-teslamate-1  | 2024-08-22 16:57:06.777 [info] Access TeslaMateWeb.Endpoint at http://xxxxxxxx.cloudapp.azure.com
teslamate-teslamate-1  | 2024-08-22 16:57:08.064 [info] Starting logger for 'XXX'
teslamate-teslamate-1  | 2024-08-22 16:57:08.112 [info] MQTT connection has been established
teslamate-teslamate-1  | 2024-08-22 16:57:08.159 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1493036967800483 -> 404 (47.983 ms)
teslamate-teslamate-1  | 2024-08-22 16:57:08.159 car_id=1 [error] Error / :vehicle_not_found
teslamate-teslamate-1  | 2024-08-22 16:57:14.462 [info] GET /
teslamate-teslamate-1  | 2024-08-22 16:57:14.480 [info] Sent 200 in 18ms
```

### Type of installation

Docker

### Version

v.1.30.1

**Comment by ivanovd** [comment]
When the update happened:
<img width="1611" alt="image" src="https://github.com/user-attachments/assets/6261b613-3032-489a-b592-efd4f0b95d1c">

Last recorded drive:
<img width="169" alt="image" src="https://github.com/user-attachments/assets/244f93f3-8dbd-42a4-a5fe-733c9e7b7192">

The car was driven extensively since then and nothing is recorded.

**Comment by cwanja** [comment]
> `teslamate-teslamate-1  | 2024-08-22 16:57:08.159 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1493036967800483 -> 404 (47.983 ms)`

The 404 makes me wonder if the .26.X branch moves to the new API endpoint. @swiffer @JakobLichterfeld @brianmay @jlestel

**Comment by JakobLichterfeld** [comment]
> The 404 makes me wonder if the .26.X branch moves to the new API endpoint. @swiffer @JakobLichterfeld @brianmay @jlestel

No, running 2024.26.7 since 6 days without any issues:
![image](https://github.com/user-attachments/assets/618a67c6-b56e-4b66-8686-cadce44f7390)

From the screenshot posted in OP it seems like the docker container does have DNS issues.

**Comment by ivanovd** [comment]
The docker container is in Azure and doesn't seem to have DNS issues, at least at the moment. The local installation on my NAS (FreeBSD) also doesn't seem to have DNS issues. 

What would be a good test?

**Comment by cwanja** [comment]
> > The 404 makes me wonder if the .26.X branch moves to the new API endpoint. @swiffer @JakobLichterfeld @brianmay @jlestel
> 
> 
> 
> No, running 2024.26.7 since 6 days without any issues:
> 
> ![image](https://github.com/user-attachments/assets/618a67c6-b56e-4b66-8686-cadce44f7390)
> 
> 
> 
> From the screenshot posted in OP it seems like the docker container does have DNS issues.
> 
> 
> 
> We had similar issues in the past, setting a DNS server for the docker daemon is the most elegant solution. Others keep rebooting till docker get correct DNS queries.

I would disagree with DNS. Two seconds before the 404 it can post for tokens. And the GET is a 404, which tells me the services can talk.

**Comment by JakobLichterfeld** [comment]
> What would be a good test?

`docker run busybox ping -c 1 192.203.230.10`

**Comment by JakobLichterfeld** [comment]
> I would disagree with DNS. Two seconds before the 404 it can post for tokens. And the GET is a 404, which tells me the services can talk.

different endpoints so different dns entries

**Comment by ivanovd** [comment]
> > What would be a good test?
> 
> `docker run busybox ping -c 1 192.203.230.10`

```
docker run busybox ping -c 1 192.203.230.10
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
ec562eabd705: Pull complete 
Digest: sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7
Status: Downloaded newer image for busybox:latest
PING 192.203.230.10 (192.203.230.10): 56 data bytes
64 bytes from 192.203.230.10: seq=0 ttl=50 time=11.274 ms

--- 192.203.230.10 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 11.274/11.274/11.274 ms
```

Nothing wrong with the DNS on both instances - local and cloud

**Comment by ivanovd** [comment]
<img width="540" alt="image" src="https://github.com/user-attachments/assets/78680171-4cb9-44f8-b0c0-325d2741482e">

**Comment by JakobLichterfeld** [comment]
> Is the API down?
> 
> <img alt="image" width="540" src="https://private-user-images.githubusercontent.com/4889583/360489159-78680171-4cb9-44f8-b0c0-325d2741482e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzY5MzYsIm5iZiI6MTcyNDMzNjYzNiwicGF0aCI6Ii80ODg5NTgzLzM2MDQ4OTE1OS03ODY4MDE3MS00Y2I5LTQ0ZjgtYjBjMC0zMjVkMjc0MTQ4MmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMTQyMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzk5MDdhYThiOTBiNDQ4N2Q0MmI3NjBmOWNiM2FjMTljMGIwZTkzODE5NjUyZWQ0ODU3MmNmNjZlMWM5YjZhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uHoyR2FYnNduqco8e8-dVGqwxcYPlmJ1cZcmqlK82JY">

This will never work

**Comment by cwanja** [comment]
> Is the API down?
> 
> <img alt="image" width="540" src="https://private-user-images.githubusercontent.com/4889583/360489159-78680171-4cb9-44f8-b0c0-325d2741482e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzY5MzYsIm5iZiI6MTcyNDMzNjYzNiwicGF0aCI6Ii80ODg5NTgzLzM2MDQ4OTE1OS03ODY4MDE3MS00Y2I5LTQ0ZjgtYjBjMC0zMjVkMjc0MTQ4MmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMTQyMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzk5MDdhYThiOTBiNDQ4N2Q0MmI3NjBmOWNiM2FjMTljMGIwZTkzODE5NjUyZWQ0ODU3MmNmNjZlMWM5YjZhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uHoyR2FYnNduqco8e8-dVGqwxcYPlmJ1cZcmqlK82JY">

Do not believe their API has a web-interface. This is expected.

**Comment by brianmay** [comment]
> GET https://owner-api.teslamotors.com/api/1/vehicles/1493036967800483 -> 404

To me this looks like Tesla is responding to the query and saying the vehicle does not exist. Or you do not have permission to access it.

Would be interested to know if the "get products" api returns the car. The command is something like:

```
curl -v --header 'Content-Type: application/json' \
  --header "Authorization: Bearer $token" \
  'https://owner-api.teslamotors.com/api/1/products'
```

But you do need the token to run this.

**Comment by ivanovd** [comment]
The issue seems to have resolved by itself (no docker or host restarts)... so, I am wondering whether it was an issue on Tesla's end ... I lost two days' worth of data though
<img width="189" alt="image" src="https://github.com/user-attachments/assets/4f2ddb62-744d-4e80-ba48-e457eeb4bec1">
