### ISSUE TITLE
Postgres restore advice needed

### ISSUE THREAD

**Issue by mikeh2010** [adriankumpf/teslamate#420]
I backed up the database previously and now I would like to restore those couple of weeks worth of missing drives.

So I don't want to drop the database and restore the backup but just restore the missing info. 
The backup is from v11.1 and obviously the current version is v12.1 if that matters.

I'm unsure about the dependencies between the tables or how to go about it.

Any advice appreciated.

**Comment by Tigwin** [comment]
The FAQ instructions on how to do a backup don't seem to work.

$ docker-compose exec database pg_dump -U teslamate tes
lamate > teslamate.bck
ERROR: No such service: database

From: https://teslamate.readthedocs.io/en/latest/import/teslafi.html

**Comment by ArnoPW** [comment]
type
$ docker-compose exec db pg_dump -U teslamate teslamate > teslamate.bck

(so db instead of database)

**Comment by DrMichael** [comment]
Or change "db" to "database" in your docker-compose.yml (first take it down, afterwards restart it). Then you're inline with the docs here.

**Comment by IMgoRt** [comment]
I think @mikeh2010 has a DB with missing data which is in a separate instance, he just wants to import that missing period, not backup the current db or restore the other version losing the current version.
I'm in a similar position post a server swap so am interested in a way of importing the missing data - does anyone have a document of the Teslafi export format used in the import here?

Thanks

**Comment by mikeh2010** [comment]
@IMgoRt How did you do it with the api scraper?

**Comment by IMgoRt** [comment]
> @IMgoRt How did you do it with the api scraper?

Sorry, I meant I could see the data structure used, I'll have to do some work to get the data into the correct format :-(
