### ISSUE TITLE
Overlapping Locations

### ISSUE THREAD

**Issue by Koofteh123** [adriankumpf/teslamate#421]
I don't know if I'm doing something wrong, but I have a problem with locations overlapping with each other.

For example i have my home as a geolocation tag that covers a large area but it still creates new tags with other nearby locations that are already covered in my home tag.

In general I can't seem to edit locations. In TeslaFi if you updated one location and it overlapped then the bigger radius tag would take precedence and that would be tagged as the location.

Thanks.

**Comment by adriankumpf** [comment]
What is the actual problem here? Please update the issue description with the filled out [bug report template](https://github.com/adriankumpf/teslamate/issues/new?assignees=&labels=&template=bug_report.md&title=
).  An example with affected addresses/geo-fences would be especially helpful to understand and reproduce the problem.

**Comment by Koofteh123** [comment]
> What is the actual problem here? Please update the issue description with the filled out [bug report template](https://github.com/adriankumpf/teslamate/issues/new?assignees=&labels=&template=bug_report.md&title=). An example with affected addresses/geo-fences would be especially helpful to understand and reproduce the problem.

My apologies, it looks like I was confusing geo-tags and addresses which I now realize are two different things.

I was creating new geo-tags and then looking in the address dashboard on the location page to see my changes.

**Comment by adriankumpf** [comment]
No worries. Addresses and geofences are indeed different. Even if a drive is assigned to a geofence, its start and end addresses are still determined. These are then displayed in the dashboard.
