### ISSUE TITLE
Storage of credentials

### ISSUE THREAD

**Issue by bizarro252** [adriankumpf/teslamate#423]
Hello!  Two questions:

Where are the credentials stored, and how are they stored (plain text??)  Is there a way we can use our tokens instead so we do not have have credentials stored off on a networked machine?  I see in issue #282 there is a way to enter tokens but unsure how to get into the table to enter them, any help on how to do that?

Where is the data stored?  I would like to be able to make backups since this is all stored on an SD card in my case, and not a high endurance one :)  I have been able to get into the docker and browse the filesystem within but unsure where the data is actually stored.

Thank you

**Comment by sotrajohnny** [comment]
Your username and password are not stored, they are only used to get the tokens. The tokens are stored in the tokens table in the database.

How to backup the database is documented in the docs here:
https://teslamate.readthedocs.io/en/latest/maintenance/backup_restore.html

**Comment by bizarro252** [comment]
Thank you!
