### ISSUE TITLE
Can't connect to http://my_ip:4000 or 3000

### ISSUE THREAD

**Issue by ki0w3** [adriankumpf/teslamate#424]
So I'm on a NAS - TNAS 4.0 Terramaster
I have a folder which contains my docker-compose.yml 
<details><summary>docker-compose.yml</summary>
<p>
> version: '3'

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: unless-stopped
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret # change this to whatever you like
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=192.168.1.251 # if you're going to access the UI from another machine replace
                               # "localhost" with the hostname / IP address of the Docker Droplet.
      - TZ=Europe/Berlin       # (optional) replace to use local time in debug logs. See "Configuration".
    ports:
      - 4000:4000
    cap_drop:
      - all

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=test # change this to whatever you like
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret # change this to whatever you like
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
</p>
</details>

That's my yml 
I SSHed into my NAS and navigated to the folder thant contains the docker-compose.
I run "docker-compose up" in the SSH and it creates the containers and everything.

<details><summary>Text from the SSH session</summary>
<p>
[root@NAS Container]# docker-compose up --remove-orphans
Pulling db (postgres:latest)...
latest: Pulling from library/postgres
Digest: sha256:5181eccc7c903e4f1beffa89a735cb7ed72e0c81d6c34c471552c3fa8bff0858
Status: Downloaded newer image for postgres:latest
Pulling mosquitto (eclipse-mosquitto:latest)...
latest: Pulling from library/eclipse-mosquitto
Digest: sha256:0324df5d17d3d93e62b3ded036ddbccec5d0a0d890e3f415712f0734cbf7c0ab
Status: Downloaded newer image for eclipse-mosquitto:latest
Starting container_teslamate_1   ... done                                                                               Recreating container_grafana_1   ... done                                                                               Recreating container_mosquitto_1 ... done                                                                               Recreating container_db_1        ... done                                                                               Attaching to container_teslamate_1, container_grafana_1, container_mosquitto_1, container_db_1
db_1         |
db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1         |
db_1         | 2020-02-07 07:09:50.230 UTC [1] LOG:  starting PostgreSQL 12.1 (Debian 12.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1         | 2020-02-07 07:09:50.258 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2020-02-07 07:09:50.258 UTC [1] LOG:  listening on IPv6 address "::", port 5432
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Starting Grafana" logger=server version=6.6.1 commit=21bf8b71bc branch=HEAD compiled=2020-02-06T09:53:10+0000
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="App mode production" logger=settings
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Initializing SqlStore" logger=server
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
grafana_1    | t=2020-02-07T07:09:48+0000 lvl=info msg="Starting DB migration" logger=migrator
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing HTTPServer" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing BackendPluginManager" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing PluginManager" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing HooksService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing OSSLicensingService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing InternalMetricsService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing RemoteCache" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing QuotaService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing ServerLockService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing UserAuthTokenService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing RenderingService" logger=server
mosquitto_1  | 1581059388: mosquitto version 1.6.8 starting
mosquitto_1  | 1581059388: Config loaded from /mosquitto/config/mosquitto.conf.
teslamate_1  | waiting for postgres at db:5432 (2sec)
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing AlertEngine" logger=server
mosquitto_1  | 1581059388: Opening ipv4 listen socket on port 1883.
mosquitto_1  | 1581059388: Opening ipv6 listen socket on port 1883.
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing DatasourceCacheService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing LoginService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing SearchService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing TracingService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing UsageStatsService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing CleanUpService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing NotificationService" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing provisioningServiceImpl" logger=server
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Backend rendering via phantomJS" logger=rendering renderer=phantomJS
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin." logger=rendering renderer=phantomJS
db_1         | 2020-02-07 07:09:50.384 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="Initializing Stream Manager"
grafana_1    | t=2020-02-07T07:09:49+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
db_1         | 2020-02-07 07:09:50.435 UTC [23] LOG:  database system was shut down at 2020-02-07 07:03:54 UTC
db_1         | 2020-02-07 07:09:50.473 UTC [1] LOG:  database system is ready to accept connections
teslamate_1  | 08:09:56.374 [info] Already up
teslamate_1  | 08:10:12.905 [info] Version: 1.15.1
teslamate_1  | 08:10:12.972 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
teslamate_1  | 08:10:12.974 [info] Access TeslaMateWeb.Endpoint at http://192.168.1.251
mosquitto_1  | 1581059412: New connection from 172.18.0.2 on port 1883.
mosquitto_1  | 1581059412: New client connected from 172.18.0.2 as TESLAMATE_302E3037333 (p2, c1, k60).
teslamate_1  | 08:10:12.988 [info] MQTT connection has been established
</p>
</details>
Anyone have any ideas/leads in the right direction?
Thanks!

**Comment by ki0w3** [comment]
Also - it worked flawlessly when I tested it on the desktop docker app.
I'm only having trouble on my NAS..

**Comment by ArnoPW** [comment]
On a synology NAS you need to type docker-compose up -d to make it work (so try it with adding the -d)

**Comment by ki0w3** [comment]
Thanks for the reply! 
I've tried that with no luck.

**Comment by ysalomongh** [comment]
I'm also having trouble connecting to the TeslaMate port.

**Comment by DrJohnM61** [comment]
Check the log file for grafana. I had the same issue and it was an ownership issue with the directories used for pulling the dashboard templates. Apparently there was a change to the ownership from earlier version of grafana.

Quote: Migrate to v5.1 or later

The Docker container for Grafana has seen a major rewrite for 5.1.

Important changes

File ownership is no longer modified during startup with chown.
Default user ID is now 472 instead of 104.

See: https://grafana.com/docs/grafana/latest/installation/docker/

**Comment by Highlander1694** [comment]
There is a good chance your NAS is blocking the docker network.  Make sure that all network connections are allowed in your networking security.  Often it only allows your local class-C network.
