### ISSUE TITLE
Noob question on the need for FQDN

### ISSUE THREAD

**Issue by pieterr94** [adriankumpf/teslamate#428]
I bought a Raspberry Pi especially for this project, so it is all new to me. Therfore, I have some questions I could not find answers for on the forum.

The docs state that if you want to make dashboards available to the internet you need two FQDN. (https://teslamate.readthedocs.io/en/latest/installation/docker_advanced.html)
I was wondering why this is necessary and how I should do this. Is it not enough if I just open the ports on my router and I go via the internet to my ip (xxx.xxx.xxx.xxx:4000)?

And if I buy two FQDN’s, since I do not have any. How do they get forwarded to my Raspberry Pi?
Thank in advance!!

**Comment by ArnoPW** [comment]
If you just open up ports 3000 and 4000 you may leak your Tesla account credentials so I wouldn't do this.
You need to obtain a domain name (or maybe something with a DDNS service) and have those point to your public IP for the desired hostnames.

**Comment by DrMichael** [comment]
You do not need to expose teslamate (on port 3000). And you can set passwords (and users) in Grafana (port 4000).
Btw, afaik no credentials are store by teslamate, only the aquired token.
