### ISSUE TITLE
cost / kW - Increase decimal precision from 2 to 3+

### ISSUE THREAD

**Issue by baylanger** [adriankumpf/teslamate#434]
Hi.

The new cost / kW change allows a precision of 2 digits but some electric companies use 3+ precision digits.

When the third precision digit is a 5 (ex: 0.065 / kWh), setting cost at 0.06 or 0.07 is either ~7.5% higher or lower to the real cost.  Where I live the electric company uses 4 precision digits - I didn't ask to increase the precision to 4 but it seems 3 should be the minimum.

If there's interest into this change, I can definitely try to make the PR.

```
def change do
   alter table(:geofences) do
     add(:cost_per_kwh, :decimal, precision: 6, scale: 2)
{noformat}
```

```
<%= text_input f, :cost_per_kwh, class: "input",
    type: :number, inputmode: :decimal, min: 0.0, step: 0.01,
    placeholder: "0.00",
```

**Comment by shagberg** [comment]
This would be a great addition. My electrical company charges me $0.08803 per kWh. Rounding up to $0.09 isn't the end of the world, but this would be a nice feature update.

**Comment by bahree** [comment]
I had a somewhat related question - I added the cost in the geofence record (home) - and I don't see the cost updated in the charges - would it take effect for the next set of charges or do I need to run some script?

Thanks.

**Comment by baylanger** [comment]
I didn’t need to charge yet.   Try it and if it do work, report back in another issue.

**Comment by DrMichael** [comment]
I don't think, that TM should update the past. Because, if costs change, it should only be valid for the future.

**Comment by ArnoPW** [comment]
+1 for more digits; my price at home is €0,22149/kWh.
No updates on previous data please, as DrMichael said, there might have been a price change.

**Comment by baylanger** [comment]
@bahree not sure why, on my iPhone I couldn't see your whole comment, the "script" part.  For past charges at a location, if the cost for was 0, those could be updated to the value set at for the location - but only if the cost previously was never set.  @DrMichael that would work, correct?

It's likely possible to connect to the database and make query to update charges for specific locations.

Since the cost is only added to the location, 3, 4, 5 or even 6 precision digits doesn't take much more place in the db.  I wrote 3 should be fine but if it doesn't take much place, why not make it 4 minimum or perhaps even support those locations that uses 5 digits?

@adriankumpf I started to setup my dev env to run tests, etc and this PR might take me another week cuz I'm quite busy.  I hope everyone is patient... it could take me another week, otherwise feel free to go ahead and make the change.

**Comment by DrMichael** [comment]
> For past charges at a location, if the cost for was 0, those could be updated to the value set at for the location - but only if the cost previously was never set. @DrMichael that would work, correct?

Probably not. The costs could have changed from 0 to something (e.g. Supercharger). But what about prepopulating the costs with the current costs, when you are going to change the costs? So, if it is 0 and you do a "set costs", it would get the current costs as default?

**Comment by baylanger** [comment]
> Probably not. The costs could have changed from 0 to something (e.g. Supercharger). But what about prepopulating the costs with the current costs, when you are going to change the costs? So, if it is 0 and you do a "set costs", it would get the current costs as default?

True - I forgot to cover the case of supercharger or charging stations that suddenly start to charge a fee.

When adding a fee in the geo-fence, should there be a box that the end user can check to apply the new set cost to previous charges that had a cost of 0?  Does that make more sense?

**Comment by DrMichael** [comment]
Right, and we also have quite some stations in Germany, where you can currently charge for free. I expect that to change in the future.
Sure, a check box or confirmation would do the job. The question is, whether it is worth the effort... 🙂 The past is the past...

**Comment by baylanger** [comment]
https://github.com/adriankumpf/teslamate/pull/440

**Comment by baylanger** [comment]
@bahree if you want to update previous charges cost, check out https://github.com/adriankumpf/teslamate/issues/386#issuecomment-583447734 to update charge cost
