### ISSUE TITLE
Update the mqtt_sensors.yaml guideline and the related website that hosts that info

### ISSUE THREAD

**Issue by stauffenberg2020** [adriankumpf/teslamate#4356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The https://docs.teslamate.org/docs/integrations/home_assistant website seems to be outdated and doesnt work as mentioned. Could the admin please update it so that it works for everyone by following the guideline/website?

### Relevant log output

```shell
There is no log for this issue
```

### Type of installation

Docker

### Version

v1.31.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting.

The Home Assistant doc got updated recently and tested successfully on multiple ends. #4247 --> PR #4257 

> Could the admin please update it so that it works for everyone by following the guideline/website?

If you find something specific please feel free to report or open a PR.
