### ISSUE TITLE
Charge cost based on geo location does not apply retrospectively

### ISSUE THREAD

**Issue by vkarthikbalaji** [adriankumpf/teslamate#442]
The charge cost based on geo location is one of the nicest features to be included. Thanks for contributors. While using this feature, the costs are not calculated retrospectively. For me work (0.23EUR/kWh) and home locations (0.34EUR/kWh) have fixed cost and inspite of setting them up in geo-fences, the costs are only calculated from the last few sessions (ie after teslamate update which has geo fence based cost/kWh).  It would be more useful, if the costs are added retrospecively per location.

![Screenshot from 2020-02-12 12-14-50](https://user-images.githubusercontent.com/41284844/74330173-7cf13280-4d91-11ea-85bd-7e09e3dc8f4b.png)

**Comment by ngardiner** [comment]
As mentioned by a few people (myself included) in prior conversations on this, this should be purely _optional_. You would not want a change in costs years from now to update past charging sessions, nor would you want a service that transitions from free to paid to then log charging costs for prior sessions. This would also mean that if you modified an incorrect charging session to the correct cost, it would revert back again (ie you could not do an estimated cost for supercharger and then update it from the invoice).

**Comment by vkarthikbalaji** [comment]
Sure it has to be optional, otherwise it is hard to keep track of changing costs over years or over different service providers in the same geo location. A toggle fixed <-> variable costs in the geo location settings could be useful to apply retrospectively or per session, I think.

**Comment by adriankumpf** [comment]
See  https://github.com/adriankumpf/teslamate/issues/386#issuecomment-583447734  for a manual interim solution.

**Comment by vkarthikbalaji** [comment]
@adriankumpf  Thx, indeed my bad to have not subscribed to that topic. Subscribed to all discussions on Teslamate :)
