### ISSUE TITLE
PostgreSQL - sslmode = required

### ISSUE THREAD

**Issue by scottrobertson** [adriankumpf/teslamate#447]
Is there a way of making this work over SSL? Digital Ocean DB service forces sslmode = required.

When i try and start teslamate, i get:

```
22:39:27.576 [error] Postgrex.Protocol (#PID<0.207.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "123.4.5.6", user "doadmin", database "defaultdb", SSL off
```

**Comment by adriankumpf** [comment]
This will be possible with the next release. You'll need to set `DATABASE_SSL=true`.

**Comment by scottrobertson** [comment]
Thank you. Would you be able to trigger a docker image build? Or does that only happen when a release is made?

**Comment by adriankumpf** [comment]
The next release will happen soon. Until then, you could run the master branch :)

**Comment by scottrobertson** [comment]
I don't know if it's related, so posting here, but it keeps getting to the following migration, and then just exiting and crashing the pod.

```
10:47:30.273 [info] == Running 20191008191431 TeslaMate.Repo.Migrations.FixLlToEarth.up/0 forward
10:47:30.277 [info] execute "CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)\nRETURNS public.earth\nLANGUAGE SQL\nIMMUTABLE STRICT\nPARALLEL SAFE\nAS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians($1))*cos(radians($2))),public.earth()*cos(radians($1))*sin(radians($2))),public.earth()*sin(radians($1)))::public.earth';\n"
** (Postgrex.Error) ERROR 42501 (insufficient_privilege) must be owner of function ll_to_earth
    (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.10.1) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:699: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (stdlib 3.11.2) timer.erl:166: :timer.tc/1
```

**Comment by adriankumpf** [comment]
It's not related. See the [installation guide](https://teslamate.readthedocs.io/en/latest/installation/debian.html#create-postgresql-database) – you'll need to temporally grant SUPERUSER rights. Not sure how that works with the managed DB service.

**Comment by scottrobertson** [comment]
Yeah, that aint gonna work sadly.

**Comment by adriankumpf** [comment]
Since you're already running the master branch, try deleting `priv/repo/migrations/20191008191431_fix_ll_to_earth.exs`. That function was replaced only because of a strange bug with Postures. It may not be necessary anymore with the latest versions.

**Comment by scottrobertson** [comment]
That worked :)

Scott

**Comment by scottrobertson** [comment]
Getting the SSL issue on grafana now ha

**Comment by LeeHanYeong** [comment]
> Getting the SSL issue on grafana now ha

Has this problem been resolved?
