### ISSUE TITLE
Also add fixed start fee on charging cost for geolocation

### ISSUE THREAD

**Issue by ArnoPW** [adriankumpf/teslamate#455]
I really like the addition of the auto cost calculation based on geolocation.
However on one of the charging points I frequently use, there's not only a price/kWh but also a start fee. 
Maybe it's possible to also add a start fee field to this geolocation cost/kWh screen. And add this startfee to the total charging session cost once.

For example:
Price/kWh €0,35
Start fee: €0,60
Price for adding 10kWh would be €0,60 + (10 x €0,35) = € 4,10

**Comment by olexs** [comment]
This would also allow to model chargers with a flat fee, like Ionity used to be before (and some others still are). Enter the flat fee as a starting price, and 0 per kWh.
