### ISSUE TITLE
Manual cost : total or per kW

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#457]
**Is your feature request related to a problem? Please describe.**
While editing charge sessions for manual costs, can it be implemented that you can put a cost per kW *or* the total cost. 

**Describe the solution you'd like**

While editing a charge, switch button to input total cost or per kW cost.

**Comment by ArnoPW** [comment]
If you create a geo-location for the charging location you can already enter a charge cost/kWh for the location and it will automatically calculate costs for every charging session on that charger in the future.

**Comment by gaLDWoRE** [comment]
> If you create a geo-location for the charging location you can already enter a charge cost/kWh for the location and it will automatically calculate costs for every charging session on that charger in the future.

How do you create a geo-location and enter the charging cost/kWh?

**Comment by cwanja** [comment]
> > If you create a geo-location for the charging location you can already enter a charge cost/kWh for the location and it will automatically calculate costs for every charging session on that charger in the future.
> 
> How do you create a geo-location and enter the charging cost/kWh?

TeslaMate user interface > Geolocations > add or edit and there is an entry form for cost.

My suggestion is around non-geolocated positions where costs are not captured.
