### ISSUE TITLE
DB failure after upgrade to 1.16.0

### ISSUE THREAD

**Issue by asdt1803** [adriankumpf/teslamate#462]
**Describe the bug**

Upgraded Teslamate from 1.15.1 to 1.16.0. After upgrade there seems to be missing data in table drives. 
Deleting the row from table positions doesn't help. There seem to be more rows missing in table drives. Teslamate terminates on another row after deleting 

docker-compose exec database psql teslamate teslamate -c   "DELETE from positions where drive_id = 392"

Is there any chance to rescue the logged data or do I have to initialize the database and start from scratch?

**Relevant entries from the logs**

```
teslamate_1  | 2020-02-17T17:42:54.760077827Z 
teslamate_1  | 2020-02-17T17:42:54.760116391Z     table: positions
teslamate_1  | 2020-02-17T17:42:54.760144329Z     constraint: positions_drive_id_fkey
teslamate_1  | 2020-02-17T17:42:54.760171392Z 
teslamate_1  | 2020-02-17T17:42:54.760196005Z Key (drive_id)=(392) is not present in table "drives".
teslamate_1  | 2020-02-17T17:42:54.760223768Z     (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  | 2020-02-17T17:42:54.760249719Z     (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  | 2020-02-17T17:42:54.760277182Z     (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:699: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  | 2020-02-17T17:42:54.760303196Z     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate_1  | 2020-02-17T17:42:54.760328521Z     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
teslamate_1  | 2020-02-17T17:42:54.760353497Z     (elixir 1.10.0) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  | 2020-02-17T17:42:54.760378885Z     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
teslamate_1  | 2020-02-17T17:42:54.760460475Z     (stdlib 3.11.2) timer.erl:166: :timer.tc/1
database_1   | 2020-02-17T17:43:57.814876749Z 2020-02-17 17:43:57.814 UTC [168] LOG:  incomplete startup packet
database_1   | 2020-02-17T17:44:04.841546677Z 2020-02-17 17:44:04.840 UTC [169] ERROR:  insert or update on table "positions" violates foreign key constraint "positions_drive_id_fkey"
database_1   | 2020-02-17T17:44:04.841692356Z 2020-02-17 17:44:04.840 UTC [169] DETAIL:  Key (drive_id)=(392) is not present in table "drives".
database_1   | 2020-02-17T17:44:04.841782733Z 2020-02-17 17:44:04.840 UTC [169] STATEMENT:  ALTER TABLE "positions" ALTER COLUMN "car_id" TYPE bigint, ADD CONSTRAINT "positions_car_id_fkey" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE CASCADE, ALTER COLUMN "car_id" SET NOT NULL, ALTER COLUMN "drive_id" TYPE bigint, ADD CONSTRAINT "positions_drive_id_fkey" FOREIGN KEY ("drive_id") REFERENCES "drives"("id") ON DELETE SET NULL
teslamate_teslamate_1 exited with code 1
```

**Operating environment**

- TeslaMate Version: v1.16.0
- Type of installation: Docker
- OS: Ubuntu 18.04

**Comment by adriankumpf** [comment]
You don't need to start from scratch. It looks like the data is in an inconsistent state. Was data manually deleted or modified in the past?

Can you check again if all rows with the drive_id=392 have been deleted from the positions table?

**Comment by asdt1803** [comment]
Hello Adrian,
Thanks for the fast reply.

id 392 is deleted from both tables:

docker-compose exec database psql teslamate teslamate -c    "select * from positions where drive_id = 392"
...
(0 rows)

docker-compose exec database psql teslamate teslamate -c    "select * from drives where id = 392"
...
(0 rows)

Now I receive the same failure at startup with id=68 (not found in table drives)

Thanks
Andre

**Comment by nikobh** [comment]
Hi

I'm getting similar errors when upgrading. I saw the same error as @asdt1803 but after a while it seemed to move on. Now I'm seeing the log below repeating over and over again:

`teslamate_1  | 19:30:21.906 [info] == Running 20200203120311 TeslaMate.Repo.Migrations.CascadeDelete.up/0 forward
teslamate_1  | 19:30:21.923 [info] drop constraint cars_settings_id_fkey from table cars
teslamate_1  | 19:30:21.936 [info] alter table cars
teslamate_1  | 19:30:21.962 [info] drop constraint charges_charging_process_id_fkey from table charges
teslamate_1  | ** (Postgrex.Error) ERROR XX001 (data_corrupted) could not read block 6 in file "base/16384/2606": read only 0 of 8192 bytes
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:699: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
teslamate_1  |     (elixir 1.10.0) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
teslamate_1  |     (stdlib 3.11.2) timer.erl:166: :timer.tc/1
tesla_teslamate_1 exited with code 0
teslamate_1  | 19:30:39.470 [info] == Running 20200203120311 TeslaMate.Repo.Migrations.CascadeDelete.up/0 forward
teslamate_1  | 19:30:39.487 [info] drop constraint cars_settings_id_fkey from table cars
teslamate_1  | 19:30:39.500 [info] alter table cars
teslamate_1  | 19:30:39.525 [info] drop constraint charges_charging_process_id_fkey from table charges
teslamate_1  | ** (Postgrex.Error) ERROR XX001 (data_corrupted) could not read block 6 in file "base/16384/2606": read only 0 of 8192 bytes
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:699: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
teslamate_1  |     (elixir 1.10.0) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
teslamate_1  |     (stdlib 3.11.2) timer.erl:166: :timer.tc/1
tesla_teslamate_1 exited with code 1
`

**Comment by asdt1803** [comment]
Checked how many rows in table drives are missing in my database:

...
docker-compose exec database psql teslamate teslamate -c "(select distinct drive_id from positions left join drives on positions.drive_id = drives.id where drives.id is null)"
 drive_id 
----------
       68
       72
       81
       88
      127
      157
      254
      306
      307
      315
      316
      317
      319
      322
      324
      335
      336
      394
      396
      403
      420
      421
         
(23 rows)
...

**Comment by adriankumpf** [comment]
I can't yet explain how that happened. But the most sensible solution is to simply set the drive_id of the respective positions to NULL, I think.

**Comment by asdt1803** [comment]
Thank you Adrian,
Setting the drive_id of the positions to NULL worked for me.
