### ISSUE TITLE
Tesla recommended that I disable teslamate

### ISSUE THREAD

**Issue by espenu** [adriankumpf/teslamate#464]
I've had some issues with my center screen blanking out (MCU1) which is most likely related to the rear camera.
However, when in discussion with Tesla support, they said the following:

> From the logs I see that there is a remote request for vehicle data every 5 seconds that slows down and crashes the system. From our experience this is usually caused by a 3rd party Mobile App. Please stop using this App.

After discussing a bit more and landing on the fact that the screen blanking is not caused by the logging, the following statement is made:

> I still recommend that you stop using the 3rd party App due to the heavy load it puts on the system.

Are there any official statements from Tesla regarding this? Has anyone seen actual issues relating to performance caused by logging software?
A request for data every 5 seconds does not seem to be very often for a computer, so I'm a bit baffled by the concept that this puts a high load on the system.

**Comment by ngardiner** [comment]
The API is not a published standard, it's reverse engineered from the app's communications.

We have to expect that if Tesla suspect these reverse engineered, unsupported API calls are causing an issue for the vehicle, they will ask us to disable them.

I can't imagine arguing this with them will get you anywhere, but it may bring unwanted attention to 3rd party apps and their use of the API.

Only Tesla can tell what the load is on the mothership, but remember that every API request is routed to their central system, for every vehicle. They are paying to process that load. I see nothing unreasonable about what they said to you, I suspect eventually they'll take some steps to dampen the load if these projects are indeed causing service issues for them.

**Comment by espenu** [comment]
> I can't imagine arguing this with them will get you anywhere, but it may bring unwanted attention to 3rd party apps and their use of the API.

I don't intend to argue with them. I'll disable the logging until my service visit is done. It was just a general question.
The argument you make regarding their server load is reasonable, but the comment from the tech made it sound like the load issue was with the computer in the car.

**Comment by Niek** [comment]
This is another case where [using the websocket API](https://github.com/adriankumpf/teslamate/issues/417) might be helpful. I'm not sure if it has less of an impact on the car, but certainly it has less impact on Tesla's API servers and it's less obvious you're using a 3rd party client.

**Comment by adriankumpf** [comment]
I'm closing this since v1.19 now uses the Streaming API by default.
