### ISSUE TITLE
ERROR:  could not find tuple for constraint 

### ISSUE THREAD

**Issue by smazzucato** [adriankumpf/teslamate#465]
**Describe the bug**

Performed a docker-compose pull this morning.
Now getting the following errors

```
teslamate_1  | 07:43:36.248 [info] == Running 20200203120311 TeslaMate.Repo.Migrations.CascadeDelete.up/0 forward
teslamate_1  | 07:43:36.266 [info] drop constraint cars_settings_id_fkey from table cars
teslamate_1  | 07:43:36.279 [info] alter table cars
db_1         | 2020-02-18 12:43:36.284 UTC [37] ERROR:  could not find tuple for constraint 41206
db_1         | 2020-02-18 12:43:36.284 UTC [37] STATEMENT:  ALTER TABLE "cars" ALTER COLUMN "settings_id" TYPE bigint, ADD CONSTRAINT "cars_settings_id_fkey" FOREIGN KEY ("settings_id") REFERENCES "car_settings"("id") ON DELETE CASCADE, ALTER COLUMN "settings_id" SET NOT NULL
teslamate_1  | ** (Postgrex.Error) ERROR XX000 (internal_error) could not find tuple for constraint 41206
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/adapters/sql.ex:699: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
teslamate_1  |     (elixir 1.10.0) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |     (ecto_sql 3.3.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
teslamate_1  |     (stdlib 3.11.2) timer.erl:166: :timer.tc/1
```

**To Reproduce**

docker-compose up

**Operating environment**

Raspbian

**Comment by adriankumpf** [comment]
Could you attach the output of the following commands?

```bash
docker-compose up -d database
docker-compose exec database psql teslamate teslamate -c "select n.nspname as schema_name, t.relname as table_name, c.conname as constraint_name from pg_constraint c join pg_class t on c.conrelid = t.oid join pg_namespace n on t.relnamespace = n.oid order by table_name;"
```

**Comment by smazzucato** [comment]
$ docker-compose up -d database 
ERROR: No such service: database

Same error for the exec database commands.

**Comment by adriankumpf** [comment]
Replace database with db.

**Comment by smazzucato** [comment]
I tried the reindex command first, but I get 
ERROR:  REINDEX DATABASE cannot run inside a transaction block

Here is the output of other command

 schema_name |          table_name           |                constraint_name                 
-------------+-------------------------------+------------------------------------------------
 public      | addresses                     | addresses_pkey
 public      | car_settings                  | car_settings_pkey
 public      | cars                          | cars_settings_id_fkey
 public      | cars                          | cars_pkey
 public      | charges                       | charges_charging_process_id_fkey
 public      | charges                       | charges_pkey
 public      | charging_processes            | charging_processes_address_id_fkey
 public      | charging_processes            | charging_processes_geofence_id_fkey
 public      | charging_processes            | charging_processes_pkey
 public      | charging_processes            | charging_processes_position_id_fkey
 public      | charging_processes            | charging_processes_car_id_fkey
 public      | drives                        | trips_car_id_fkey
 public      | drives                        | drives_end_geofence_id_fkey
 public      | drives                        | drives_start_geofence_id_fkey
 public      | drives                        | drives_end_position_id_fkey
 public      | drives                        | drives_start_position_id_fkey
 public      | drives                        | trips_end_address_id_fkey
 public      | drives                        | trips_start_address_id_fkey
 public      | drives                        | trips_pkey
 public      | geofence_sleep_mode_blacklist | geofence_sleep_mode_blacklist_pkey
 public      | geofence_sleep_mode_blacklist | geofence_sleep_mode_blacklist_car_id_fkey
 public      | geofence_sleep_mode_blacklist | geofence_sleep_mode_blacklist_geofence_id_fkey
 public      | geofence_sleep_mode_whitelist | geofence_sleep_mode_whitelist_pkey
 public      | geofence_sleep_mode_whitelist | geofence_sleep_mode_whitelist_geofence_id_fkey
 public      | geofence_sleep_mode_whitelist | geofence_sleep_mode_whitelist_car_id_fkey
 public      | geofences                     | geofences_pkey
 public      | positions                     | positions_car_id_fkey
 public      | positions                     | positions_drive_id_fkey
 public      | positions                     | positions_pkey
 public      | schema_migrations             | schema_migrations_pkey
 public      | settings                      | settings_pkey
 public      | states                        | states_car_id_fkey
 public      | states                        | positive_duration
 public      | states                        | states_pkey
 public      | tokens                        | tokens_pkey
 public      | updates                       | updates_pkey
 public      | updates                       | updates_car_id_fkey
 public      | updates                       | positive_duration
(38 rows)

**Comment by adriankumpf** [comment]
Using two commands instead should work:
```bash
docker-compose exec database psql teslamate teslamate -c "REINDEX DATABASE teslamate"
docker-compose exec database psql teslamate teslamate -c "REINDEX System teslamate"
```

**Comment by smazzucato** [comment]
It can reindex system teslamate, but for database teslamate I get

$ docker-compose exec db psql teslamate teslamate -c "REINDEX DATABASE teslamate"
ERROR:  could not create unique index "positions_pkey"
DETAIL:  Key (id)=(46475) is duplicated.

**Comment by adriankumpf** [comment]
I'm thinking that there is some underlying problem with your system or the SD card of your rpi. The data seems to be somewhat corrupted. One way would be to fix all errors, i.e. delete duplicate entries etc until re-indexing succeeds.

**Comment by smazzucato** [comment]
This is quite possible as I had a kernel panic.
How can I dump all the data out.
And how would I go about delete duplicate keys ?
Thank you

**Comment by adriankumpf** [comment]
Ok, that's probably the reason. Some SQL knowledge is required e.g. to delete the duplicate entry from the positions table 

```SQL
DELETE FROM positions
WHERE id = 46475;
```

The easiest way would be to restore a backup on a fresh installation, I guess.

**Comment by smazzucato** [comment]
The source of the problem was indeed SD card corruption.    I was able to get the data out and sacrifice some table rows that had bad data.   Thanks for your help.
