### ISSUE TITLE
Failed migration: 1.15.1 to 1.16

### ISSUE THREAD

**Issue by seabie** [adriankumpf/teslamate#470]
Migration failed with stack trace upgrading from 1.15.1 to 1.16

**To Reproduce**

- Migrate 1.15.1 to 1.16

**Relevant entries from the logs**

pi@raspberrypi:~/dev/teslamate $ _build/prod/rel/teslamate/bin/teslamate eval "TeslaMate.Release.migrate"
23:20:45.079 [info] == Running 20200203120311 TeslaMate.Repo.Migrations.CascadeDelete.up/0 forward
23:20:45.087 [info] drop constraint cars_settings_id_fkey from table cars
23:20:45.093 [info] alter table cars
23:20:45.105 [info] drop constraint charges_charging_process_id_fkey from table charges
23:20:45.108 [info] alter table charges
23:20:45.227 [info] drop constraint charging_processes_car_id_fkey from table charging_processes
23:20:45.230 [info] drop constraint charging_processes_address_id_fkey from table charging_processes
23:20:45.233 [info] drop constraint charging_processes_geofence_id_fkey from table charging_processes
23:20:45.236 [info] alter table charging_processes
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "charging_processes_car_id_index" already exists
    (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.10.0-dev) lib/enum.ex:1335: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:699: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.3.4) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.3.4) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.10.0-dev) lib/enum.ex:1947: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.3.4) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (stdlib 3.9) timer.erl:166: :timer.tc/1

**Operating environment**

- TeslaMate Version: 1.15.1
- Type of installation: Manual
- OS: raspberrypi

**Comment by Niek** [comment]
See https://github.com/adriankumpf/teslamate/issues/446 for fixes (simplest one is: upgrade to the latest PostgreSQL, for example 12.x).

**Comment by seabie** [comment]
Thanks Niek!  I should have done a better job searching for a duplicate issue
