### ISSUE TITLE
Templating init failed dial tcp 172.18.0.2:5432: connect: connection refused

### ISSUE THREAD

**Issue by fyreflyt** [adriankumpf/teslamate#471]
**Describe the bug**

It appears I have poor luck when updating Teslamate on my Raspberry Pi. Updating from 1.14.1 to 1.16 has caused several issues. The initial update appeared to retain my previous data, but some panels (Drive Details, Charge Details) displayed no data, and I was unable to load Teslamate on port 4000. 

Today, I once again tried starting each of the services sequentially, and all appeared to work properly with no errors. But logging into Grafana results in a "Templating init failed dial tcp 172.18.0.2:5432: connect: connection refused" error on all the charts, and no data is displayed. Port 4000 also does not load.

**To Reproduce**

1. Run the update process as described in the docs
2. Start the 4 services sequentially with a COMPOSE_HTTP_TIMEOUT set to 150
3. All services appear to launch successfully
4. Unable to load port 4000, port 3000 displays the above error

**Expected behavior**

Existing Data should appear, and I should be able to log into the config page on port 4000

**Relevant entries from the logs**

After running the logs command. I received the following:
```

teslamate_1 | waiting for postgres at db:5432 (2 sec)

```
That line repeated and doubled the time (2 sec) until it reached (512 sec). I'm uncertain where the logs have been saved.

**Operating environment**

- TeslaMate Version: 1.16
- Type of installation: Docker
- OS: Raspbian 9 Stretch

**Comment by adriankumpf** [comment]
Postgres uses port 5432. It just looks like the database is not running or failed to start. This has nothing to do with the update. To see which containers are currently running, the following command might be helpful: `docker ps`. Also, take a look at the database logs: `docker-compose logs database` (or `docker-compose logs db` depending on when the docker-compose.yml was last updated).

**Comment by fyreflyt** [comment]
Looks like PostgreSQL 11 isn't compatible with the version of Debian that my Raspberry pi is running. When running the command, I see this error

`The data directory was intialized by PostgreSQL version 11, which is not compatible with this version 12.2 (Debian 12.2-1.pgdg100+1)`

How can I install the 1.14 branch again?

**Comment by adriankumpf** [comment]
Okay, that makes sense. I wouldn't recommend downgrading to v1.14. You could either keep using Postgres 11 (replace `image: postgres:12 ` with `image:  postgres:11` in the docker-compose.yml) or upgrade to the latest Postgres version: https://teslamate.readthedocs.io/en/latest/maintenance/updating_postgres.html

**Comment by fyreflyt** [comment]
Switching back to Postgres 11 appears to have resolved all my issues. I was able to start all the processes, load settings, and Grafana. All my data appears to be intact as well! 

The upgrading process has been fairly painful for me both times I've tried it. I'd suggest adding some details about any changes to the .yml file or any other config changes to the documentation.

More broadly, an internal upgrade process would be wonderful!

**Comment by instantdreams** [comment]
Having this issue on Raspberry Pi with version 1.24.0

**Comment by instantdreams** [comment]
Amended docker-compose.yml to revert postgres 13 to postgres 11. Didn't fix the issue.

**Comment by instantdreams** [comment]
Did the following:
1. Backed up database
2. Shut down the docker image
3. Removed the database volume
4. Changed the docker-compose.yml to use the following:
```
  database:
    image: postgres:13.4
```
5. Started up the docker image
6. Followed the database restore instructions

Still having the same "Templating [temp_unit] | Error updating options: dial tcp :5432: connect: connection refused" error messages. Any other ideas?
