### ISSUE TITLE
1.17.0 overview dashboard odometer is kilometers only

### ISSUE THREAD

**Issue by bpankz** [adriankumpf/teslamate#472]
**Describe the bug**

overview dashboard Odometer singlestat only displays kilometers.
changed to this and got the output in miles
`select $__time(date), convert_km(odometer, '$length_unit') from positions where car_id = $car order by date desc limit 1;`

**To Reproduce**

1. Go to 'Overview' dashboard

**Expected behavior**

Should display in desired units set in settings

**Comment by adriankumpf** [comment]
Good catch! Adding the `convert_km` helper was indeed the solution.
