### ISSUE TITLE
Browser console throws error: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by tobiasehlert** [adriankumpf/teslamate#473]
**Describe the bug**

After upgrading to postgresql 12 and updating to 1.17, I get following issue on the frontend of teslamate in the Chrome console.

```
app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.<anonymous> (app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2)
    at o (app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2)
    at Module.<anonymous> (app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2)
    at o (app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2)
    at Object.<anonymous> (app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2)
    at o (app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2)
    at app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
    at app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
(anonymous) @ app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
o @ app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
(anonymous) @ app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
o @ app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
(anonymous) @ app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
o @ app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
(anonymous) @ app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
(anonymous) @ app-dde5b7e1a4c815b2e43908b393986751.js?vsn=d:2
```

**To Reproduce**

1. Go to 'Teslamate WebGUI'
2. Try to make login attempt
3. Open console of Chrome webbrowser

**Expected behavior**

When entering credentials.. the Sign In button should be enabled.. but it doesn't.

**Relevant entries from the logs**

There are no issues shown in the docker-compose logs output at all..

```
teslamate_1  | 21:08:36.697 [info] GET /sign_in
teslamate_1  | 21:08:36.699 [info] Sent 200 in 2ms
teslamate_1  | 21:08:37.201 [info] GET /sign_in
teslamate_1  | 21:08:37.203 [info] Sent 200 in 1ms
```

**Screenshots**

![Teslamate_console_error](https://user-images.githubusercontent.com/4417850/75120189-da3a8d00-5689-11ea-8ded-0e72562ad236.png)

**Data**

*nothing to export..*

**Operating environment**

- TeslaMate Version: v1.17.0
- Advanced Docker Setup with Traefik
- OS: CentOS 7

**Comment by brent112** [comment]
Same here, just performed a fresh installation and was wondering why i could not login in.

**Comment by dani190** [comment]
same here - any workaround?

**Comment by adriankumpf** [comment]
I will release v1.17.1 shortly.

**Comment by adriankumpf** [comment]
> I will release v1.17.1 shortly.

Done. Thanks for the report, @tobiasehlert! This error occurred if the Grafana URL was not yet set on the settings page. That's why this slipped through
