### ISSUE TITLE
Fail importing from Teslafi

### ISSUE THREAD

**Issue by PierreGode** [adriankumpf/teslamate#475]
Hi I am having issues importing history from Teslafi to teslamate. I succeeded importing 1 of 6 months and it shows in grafana. I have tried multiple times importing other months in a bundle and always get 1 green checkbox (false positive, not showing in grafana) and the rest of the files gets a blue status “looks a little like a WiFi logo”

When I try importing one file at the time I get a green checkbox but data is not showing in grafana.

I noticed from the logs I was first having issues with memory (raspberry pi) but it helped stopping grafana docker container wile importing.

00:20:01.722 [info] Already up
00:20:49.242 [info] Version: 1.16.0
00:20:50.679 [info] Refreshed api tokens
00:20:50.680 [info] Scheduling token refresh in 40d
00:20:50.752 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
00:20:50.766 [info] Access TeslaMateWeb.Endpoint at http://localhost00:21:42.216 [info] GET /
00:21:42.304 [warn] Elixir.Cldr.NoMatchingLocale: No configured locale could be matched to "sv-se"
00:21:42.319 [info] Sent 302 in 103ms
00:21:42.429 [info] GET /import
00:21:42.435 [warn] Elixir.Cldr.NoMatchingLocale: No configured locale could be matched to "sv-se"
00:21:42.571 [info] Sent 200 in 141ms
00:22:29.140 [info] Importing 3 file(s) ...
00:22:29.333 [info] Starting logger for 'Tezz'
00:29:00.425 [info] GET /import
00:29:00.434 [warn] Elixir.Cldr.NoMatchingLocale: No configured locale could be matched to "sv-se"
00:29:00.449 [info] Sent 200 in 22ms
00:29:02.618 [info] GET /import
00:29:02.623 [warn] Elixir.Cldr.NoMatchingLocale: No configured locale could be matched to "sv-se"
00:29:02.642 [info] Sent 200 in 23ms
00:38:59.704 [info] Import complete!
00:42:34.724 [info] GET /import
00:42:34.732 [warn] Elixir.Cldr.NoMatchingLocale: No configured locale could be matched to "sv-se"
00:42:34.755 [info] Sent 200 in 29ms
00:42:40.057 [info] GET /import
00:42:40.064 [warn] Elixir.Cldr.NoMatchingLocale: No configured locale could be matched to "sv-se"
00:42:40.093 [info] Sent 200 in 36ms

**Comment by adriankumpf** [comment]
The blue icon is meant to indicate that the file was skipped because data already exists for an earlier period. I'd recommend to restore the backup that was made before importing the first CSV file first. Afterwards import all CSV files at once.

**Comment by PierreGode** [comment]
Hi! thank you I have succedded importing all teslafi history. 
I just did a docker system prune and compose again and started off importing the data.
thank you!

**Comment by A-LAM-3** [comment]
Any idea why most of these TeslaFi imports are being skipped? I uploaded all of the CSV files to the import folder and ran the import, but it seems like it failed after the first two.

<img width="989" src="https://user-images.githubusercontent.com/49968005/78199231-e8758900-743f-11ea-8e60-8918b6393514.png">
