### ISSUE TITLE
Not understanding what is "Gross Consumption" calculation or what it means...?

### ISSUE THREAD

**Issue by chilman408** [adriankumpf/teslamate#479]
Having a difficult time understanding what this is...now, with the Trip dashboard it is even less clear...see attached screenshot.

I have a 75D Model X.  82.6kWh per 100mi seems off as I'm reading this to mean that I shouldn't have more than 90mi of range on a 75kWh battery?  Or am I misunderstanding this?

![Screen Shot 2020-02-24 at 10 35 22 AM](https://user-images.githubusercontent.com/44660877/75181180-887a1d00-56f2-11ea-9654-dd6d36a53032.png)

**Comment by adriankumpf** [comment]
The gross consumption describes how much energy is used in total (including sentry mode, vampire drain etc). The value is calculated based on the loss of range between charges i.e. it's an estimate. 80 kWh/100mi seems way off though. What is the value displayed in the efficiency dashboard? Also, which efficiency factor was determined?

**Comment by chilman408** [comment]
No, this is from the new Trip dashboard.  I assume this value is calculated the same way as the Efficiency dashboard but with less data.  In any case, the value on the Efficiency dashboard also seems to be off to me (although less so) - see below.

I'm interpreting that this means I'm spending ~4kWh/100mi on idling or 10% idling & 90% driving which seem excessive....

![Screen Shot 2020-02-24 at 11 23 57 AM](https://user-images.githubusercontent.com/44660877/75183964-6a172000-56f8-11ea-896e-96c1b3ca68c0.png)

**Comment by adriankumpf** [comment]
> I assume this value is calculated the same way as the Efficiency dashboard but with less data.

That's right.

> I'm interpreting that this means I'm spending ~4kWh/100mi on idling or 10% idling & 90% driving which seem excessive....

I cannot assess that. At first glance, it doesn't seem too far off to me. The first screenshot shows that your car often woke up from sleep mode. Maybe that's a reason? But as I said, the values are calculated based on the range and the range is also affected by the outside temperature. This must be taken into account.

**Comment by chilman408** [comment]
You're right about the first screenshot.  My Model X does that during sleep...  Below is a screenshot of the Trip dashboard from my Model 3.  You can see it doesn't have the sleep issue but the Gross consumption still look way off...

![Screen Shot 2020-02-24 at 12 06 42 PM](https://user-images.githubusercontent.com/44660877/75187157-58387b80-56fe-11ea-9cd4-4c5549d1f904.png)

**Comment by adriankumpf** [comment]
Okay, that looks fishy. Maybe there's some kind of conversion error. If you select other time periods in the past, is the difference as large?

**Comment by chilman408** [comment]
Yes, over time it is less.  For past 7 days range, the Gross is less than Net, is this possible?

![Screen Shot 2020-02-24 at 12 21 17 PM](https://user-images.githubusercontent.com/44660877/75188150-7a32fd80-5700-11ea-8591-8a3700dc3afc.png)

**Comment by adriankumpf** [comment]
Okay, then the high deviation of 25 kWh per 100 miles is more likely due to the fact that you only drove 12 miles that day. The absolute values look much less dramatic: circa 3,0 vs 5,9 kWh. About the other thing - less gross than net – this difference could be due to the different calculation methods. I will take a closer look at it later.
