### ISSUE TITLE
N/A in the site of the kWh consumed 

### ISSUE THREAD

**Issue by OnePerson10** [adriankumpf/teslamate#480]
Hello, I have put Teslamate and I have some bugs, in all the places where I put the consumption kWh it tells me N / A instead of the consumption of the car.

Here screenshots: 
![19835AFF-69CF-4469-A2D5-1084BC568E95](https://user-images.githubusercontent.com/39443401/75193170-f6a3fb80-5755-11ea-8f6f-2c70b26ecce3.jpeg)
![AC6D3F32-30A7-44CB-89FD-B3C8E28E98CE](https://user-images.githubusercontent.com/39443401/75193180-fb68af80-5755-11ea-97e1-d812064511cc.jpeg)

**Comment by adriankumpf** [comment]
This is explained here: https://teslamate.readthedocs.io/en/latest/faq.html
