### ISSUE TITLE
Unable to restore database

### ISSUE THREAD

**Issue by StachStach** [adriankumpf/teslamate#483]
I was following the [documentation](https://teslamate.readthedocs.io/en/latest/maintenance/updating_postgres.html) in order to upgrade Postgres from 11 to 12. First I took a snapshot of my VM (thankfully) and then tried performing a backup/restore, once again using the [documented process](https://teslamate.readthedocs.io/en/latest/maintenance/backup_restore.html). While the restore appears to work (no error message, but no messages whatsoever), when I navigate to a Teslamate graphana page, there is no data for any of the pages.

This isn't a ton of information to go on, but what could I be doing wrong? I followed the documentation to the letter (copying and pasting) and there are no messages produced when doing the following either:

# Drop existing data and reinitialize
docker-compose exec -T database psql -U teslamate << .
drop schema public cascade;
create schema public;
create extension cube;
create extension earthdistance;
CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
    RETURNS public.earth
    LANGUAGE SQL
    IMMUTABLE STRICT
    PARALLEL SAFE
    AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
.

Thanks in advance for your help!
Stach

**Comment by adriankumpf** [comment]
Hmm it's hard to figure out at which point it went wrong. Maybe you missed that last restore command? This is what I see when performing the upgrade. Hope this helps. 

```bash
$ docker-compose exec database pg_dump -U teslamate teslamate > teslamate.bck

$ head teslamate.bck
  --
  -- PostgreSQL database dump
  --

  -- Dumped from database version 11.7 (Debian 11.7-1.pgdg90+1)
  -- Dumped by pg_dump version 11.7 (Debian 11.7-1.pgdg90+1)

  SET statement_timeout = 0;
  SET lock_timeout = 0;
  SET idle_in_transaction_session_timeout = 0;

$ docker-compose down
  Stopping teslamate_teslamate_1 ... done
  Stopping teslamate_database_1  ... done
  Removing teslamate_teslamate_1 ... done
  Removing teslamate_database_1  ... done
  Removing teslamate_grafana_1   ... done
  Removing network teslamate_default

$ vim docker-compose.yml # Bump postgres version

$ docker volume rm teslamate_teslamate-db
  teslamate_teslamate-db

$ docker-compose up -d database
  Creating network "teslamate_default" with the default driver
  Creating volume "teslamate_teslamate-db" with default driver
  Pulling database (postgres:12)...
  12: Pulling from library/postgres
  bc51dd8edc1b: Already exists
  d2b355dbb6c6: Pull complete
  d237363a1a91: Pull complete
  ff4b9d2fde66: Pull complete
  646492d166e7: Pull complete
  828b1f103a3a: Pull complete
  2ab9e3c9583f: Pull complete
  4ab234e8a047: Pull complete
  71b084e0c62f: Pull complete
  bf30bd092a82: Pull complete
  2aa61e9feb4e: Pull complete
  aa5eca126d57: Pull complete
  7046b64d69a3: Pull complete
  a851dbb990ce: Pull complete
  Digest: sha256:c5423e0febf82c33b5dc69aacd70d64418144db7bd355fa4ca30e6e5430b4123
  Status: Downloaded newer image for postgres:12
  Creating teslamate_database_1 ... done

$ docker-compose exec -T database psql -U teslamate << .
> drop schema public cascade;
> create schema public;
> create extension cube;
> create extension earthdistance;
> CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
>     RETURNS public.earth
>     LANGUAGE SQL
>     IMMUTABLE STRICT
>     PARALLEL SAFE
>     AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
> .
  DROP SCHEMA
  CREATE SCHEMA
  CREATE EXTENSION
  CREATE EXTENSION
  CREATE FUNCTION

$ docker-compose exec -T database psql -U teslamate -d teslamate < teslamate.bck
  SET
  SET
  SET
  SET
  SET
   set_config
  ------------

  (1 row)

  SET
  SET
  SET
  SET
  CREATE EXTENSION
  COMMENT
  CREATE EXTENSION
  COMMENT
  CREATE TYPE
  ALTER TYPE
  CREATE TYPE
  ALTER TYPE
# ...
```

**Comment by StachStach** [comment]
Adrian, I love Teslamate and really appreciate the help. I followed your series of commands and I do believe that I got further, but it still didn't work.

**Since I am logged in as the user "stach", when I remove the database I have to issue the following slightly modified command in order for it to work.**

     docker volume rm stach_teslamate-db

**Do I need to adjust the last 2 commands as well, for my username of stach, because I get no output when I enter them: I tried changing the -U teslamate   to -U stach.   but that only produced an error**

stach@ubuntu:~$ docker-compose exec -T database psql -U teslamate << .
> drop schema public cascade;
> create schema public;
> create extension cube;
> create extension earthdistance;
> CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
>     RETURNS public.earth
>     LANGUAGE SQL
>     IMMUTABLE STRICT
>     PARALLEL SAFE
>     AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
> .
stach@ubuntu:~$ 
stach@ubuntu:~$ docker-compose exec -T database psql -U teslamate -d teslamate < teslamate.bck
stach@ubuntu:~$ 


**Thanks in advance for any help that you can give.
Stach**

**Comment by adriankumpf** [comment]
According to the `psql` man page `-U` specifies the database user name. Use what you chose during the initial installation :)

It might help to run the commands directly via the containers shell: `docker-compose exec database bash`.

This goes a bit beyond what the issue tracker is there for, honestly, since it’s not related to TeslaMate as an application. But I leave this open because others may have the same difficulties and can offer help.

**Comment by StachStach** [comment]
The command syntax you used is correct, since my backup worked with the same database name, username, etc... After a lot of reading, trial and error, my guess right now is that my older version of docker-compose (because I'm running it on Ubuntu) may be an issue (current version is 1.25.0). The restore command gives out no errors, but it also completes in about 1 second vs. the backup which took considerably longer. The backup file is valid and if I remove the -T option from the restore command, I can see all of the data go by (with errors). Here's my version info and I'm curious to hear your thoughts about this as well?

**stach@ubuntu:~$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
stach@ubuntu:~$**

**Comment by StachStach** [comment]
Well, I tried to update docker-compose on Ubuntu, but was never able to get it current. So I started looking around to see what the best options were for running docker-composer on vmWare Workstation. I ended up installing and using vmWare's Free Proton-OS and I got the latest version of docker / docker-compose up and running quickly.

The Big news is that the restore of my backup worked Flawlessly with Proton OS and the current version of Docker-Compose, so many thanks for showing me the backup/restore process and hopefully my new setup will help someone as well, as Proton OS is a great optimized / low resource way to run dockers!

**Comment by hoang51** [comment]
I similarly got stuck with the role issue while backup & restore. I figured it out that it needs both the designated database username (I renamed it from teslamate to a customized username in the .env file) and the teslamate database (I left this as default teslamate) for the first line in the command:
`docker-compose exec -T database psql -U teslamate << .`
to look like this:
`docker-compose exec -T database psql -U username teslamate<< .`

This resolved the error 2 with the role issue:
```
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "teslamate" does not exist
ERROR: 2
```

The documentation wasn't 100% clear on this, so hopefully this will help out anybody else in the future.
