### ISSUE TITLE
Addresses show obscure names instead of of towns/cities

### ISSUE THREAD

**Issue by rsiv** [adriankumpf/teslamate#489]
When reverse-resolving addresses with OpenStreetMap, TeslaMate gives hamlets higher rank than cities, so most of my drives show some obscure names instead of well-known ones.

For example, this shows on TeslaMate as 'IKEA, Pioneer Homes' instead of 'IKEA, Elizabeth': https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=29416243&class=shop

Pioneer Homes is a neighborhood 2 miles away which just happens to be the closest hamlet point.
OSM returns these closest hamlet points even if they are not related to the address at all. Cities and towns are enclosing polygons and should be much more relevant.

geocoder.ex module pulls the first available tag from OSM in this order:
```
  @city_aliases [
    "village",
    "hamlet",
    "locality",
    "croft",
    "city",
    "town",
    "municipality"
  ]
```

Would it make more sense to move town/city/municipality before village/hamlet, so hamlet names will be used only if there is no city/town name available?

**Comment by adriankumpf** [comment]
That definitely makes sense 👍
