### ISSUE TITLE
No charges after and including a charge with charge_energy_used  = 0

### ISSUE THREAD

**Issue by gaardiolor** [adriankumpf/teslamate#491]
**Describe the bug**

I'm not seeing new charges in Grafana.

**To Reproduce**

1. Make sure you have a charge with `charge_energy_used = 0` , the rest of the charge must satisfy the WHERE clause in the grafana Charges query
2. Observe you don't have any charges after the charge with `charge_energy_used = 0`
3. Go to Query inspector > Generated SQL. Execute the SQL in pgsql manually. Observe you get a `ERROR:  division by zero`

**Expected behavior**

Charges. 

Looks like a fix (or at least a workaround) is to change the Charges query line from 
`CASE WHEN charge_energy_used IS NULL THEN NULL ELSE LEAST(charge_energy_added / charge_energy_used, 1.0) END as charging_efficiency,`
to
`CASE WHEN charge_energy_used IS NULL THEN NULL ELSE LEAST(charge_energy_added / NULLIF (charge_energy_used, 0), 1.0) END as charging_efficiency,`

**Relevant entries from the logs**

N/A

**Screenshots**

N/A

**Data**

[charges.txt](https://github.com/adriankumpf/teslamate/files/4267881/charges.txt)

**Operating environment**

- TeslaMate Version: 1.16
- Type of installation: Mixed
- OS: Fedora

**Comment by adriankumpf** [comment]
This was already fixed in b67b6e6f43145def4443e7d71c3d32d99aa304a5 and released with 1.16. Make sure to re-import the dashboards after each update :)
