### ISSUE TITLE
Supercharger charge sessions consistently under-reporting usage

### ISSUE THREAD

**Issue by Niek** [adriankumpf/teslamate#492]
It seems like TeslaMate is consistently under-logging the used kWh at superchargers (maybe at regular chargers as well, but that's harder to check). Here is a sample of my last 5 SuC charging sessions:

* 36 kWh according to Tesla, 30.60 kWh used, 30.26 kWh charged according to TeslaMate
* 36 kWh according to Tesla, 35.80 kWh used, 34.45 kWh charged according to TeslaMate
* 49 kWh according to Tesla, 43.39 kWh used, 42.51 kWh charged according to TeslaMate
* 47 kWh according to Tesla, 41.12 kWh used, 40.84 kWh charged according to TeslaMate
* 11 kWh according to Tesla, 9.56 kWh used, 9.84 kWh charged according to TeslaMate (weird, > 100% efficiency?)

Is Tesla simply rounding up their kWh numbers like crazy? Or is there a bug in the charge start/stop detection or polling?

**Comment by adriankumpf** [comment]
This applies not only to superchargers, but also to fast chargers in general. When calculating the kWh used for DC charging sessions, the `charger_power` (an integer) must be used. Hence the inaccuracy.

In this regard, #432 is relevant to improve the accuracy of the charge cost.

**Comment by Niek** [comment]
I see, isn't it possible to use the (more accurate) ``charge_energy_added`` instead? Is it that value unset on fast chargers?

**Comment by adriankumpf** [comment]
`charge_energy_added` is still available (and also displayed in the dashboard). Does it actually make the calculation of the charge costs more accurate though? With regard to the recent updates to supercharger billing kWh used should produce a value that is close to the actual cost, at least in theory:

> Owners will also be billed for kWhs consumed by the car going toward the HVAC system, battery heater, and other HV loads during the session. Previously, owners were only billed for the energy used to charge the battery during the charging session.

Source: https://electrek.co/2020/01/13/tesla-updates-supercharger-billing/

Calculating the costs based on the maximum kWh "Added" (= `charge_energy_added`) and "Used" therefore seems to me to be a pragmatic solution?

**Comment by Niek** [comment]
But that would still mean the numbers are off sometimes around 20%, as you can see. For example my latest supercharger session:
<img width="500" alt="Screen Shot 2020-03-03 at 09 52 17" src="https://user-images.githubusercontent.com/213140/75758641-ad930f00-5d34-11ea-8906-0bae912243dd.png">

In the database:
```bash
$ echo "select *, greatest(charge_energy_used, charge_energy_added) from charging_processes where id = 57" | psql -hlocalhost -x teslamate teslamate
-[ RECORD 1 ]--------+------------------------
id                   | 57
start_date           | 2020-02-27 21:24:02.222
end_date             | 2020-02-27 21:59:07.417
charge_energy_added  | 30.26
start_ideal_range_km | 107.7
end_ideal_range_km   | 329.3
start_battery_level  | 29
end_battery_level    | 88
duration_min         | 35
outside_temp_avg     | 2.5
car_id               | 1
position_id          | 54701
address_id           | 99
start_rated_range_km | 107.7
end_rated_range_km   | 329.3
geofence_id          |
charge_energy_used   | 30.60309
cost                 |
greatest             | 30.60309
```

**Comment by adriankumpf** [comment]
Yeah, that seems inevitable. Due to e.g. transmission losses, battery heating etc. there will often be a more or less noticeable discrepancy between what the charging station measures and what actually goes into the car or battery.

If one wants to accurately track the actual charge costs, there is ultimately no way around manually checking and entering the cost for each charging session (except perhaps at home or at work, where one charges AC; there the "kWh used" are, in my experience, quite accurate).
