### ISSUE TITLE
Support URI base path for hosting behind reverse proxies (e.g. Home Assistant)

### ISSUE THREAD

**Issue by matt-FFFFFF** [adriankumpf/teslamate#494]
**Is your feature request related to a problem? Please describe.**

TeslaMate does not support the use of a base path element and expects all requests to be relative to the root ```/```. This causes problems when hosting behind a reverse proxy in a shared environment. My use case is integration with Home Assistant and wishing to use the ingress capability. The benefits of this are being able to leverage the existing TLS and AuthN capabilities of the HA platform.

**Describe the solution you'd like**

I would like to be able to specify a BASE_PATH system environment variable that is read at runtime. The TeslaMate endpoint would then respond to requests relative to this base path.

e.g.
```
docker run --env BASE_PATH=/my/custom/path teslamate/teslamate:1.17
```

The alternative with Home Assistant is to map the port onto the network and access TeslaMate directly, however this means there is no AuthN nor TLS. This makes porting the docker container to a HA addon much more complex as we need to implement these features independently.

I have tried to see if I could implement this myself and do a PR, but I cannot yet get my head around Elixir!

**Additional context**

[Home Assistant Ingress](https://developers.home-assistant.io/docs/hassio_addon_presentation#ingress)

**Comment by cowlinb6** [comment]
Has anyone found a solution to using subpaths yet?

**Comment by matt-FFFFFF** [comment]
Without support in the code there isn't a workaround I don't think. TM generates internal links that are based on the site root (/).

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by adriankumpf** [comment]
As a workaround, does your setup allow to run e.g. nginx in front of TeslaMate to rewrite the paths?

**Comment by matt-FFFFFF** [comment]
I did try this, I think some resources paths are generated by TM and the paths are all relative to the site root.

E.g. the CSS and the internal links within the admin interface


Matt White

Cloud Solution Architect | United Kingdom | +44 118 9094917 | +44 7971 600419 | matt.white@microsoft.com


________________________________

**Comment by matt-FFFFFF** [comment]
I have tried to explain the issue here @adriankumpf 

The ingress correctly rewrites the requests inbound but does not rewrite the references in the response. I could investigate using [sub_filter](http://nginx.org/en/docs/http/ngx_http_sub_module.html) but this seems messy.

![diagram](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgSG9tZSBBc3Npc3Rhbm50IEluZ3Jlc3MKCkJyb3dzZXItPkhBAA0IOiBHRVQgL2FkZG9ucy88AAMFaWQ-CgAYCi0-VGVzbGFNYXRlACYHCgAICQA8DkhUTUwgY29udGVudAA0DQBxBwATDwCBBQkAFglFdmFsdWF0ZSByZXNvdXJjZXMgKGUuZy4gQ1NTL2pzKQCBJhtjc3MvZmlsZS5jc3MAZhZFcnJvciA0MDQKCg&s=default)
