### ISSUE TITLE
Add Norwegian translation

### ISSUE THREAD

**Issue by spacecosmos** [adriankumpf/teslamate#496]
I want to add a **Norwegian translation**. But my skills with GitHub is rather poor, unfortunately.

I can see the PO files under here:
_teslamate/priv/gettext_

How exactly can I add it? Pull request and then add the file? Any guidance would be greatly appreciated.

**Comment by tabascoeye** [comment]
Normally you
# "fork" the repository so that you have a clone in your own repos
# add/change/delete whatever you want in that fork
# create a Pull-request from your fork and hope for the best

**Comment by Rfvgyhn** [comment]
If you're unfamiliar with git and not just github, you can also do it directly from your browser.
1. Navigate to [priv/gettext] and click the _Create new file_ button
2. Set the file name to `no/LC_MESSAGES/default.po` (assuming `no` is the correct language code)
3. Copy and paste the contents [priv/gettext/default.pot] into the text area and make your edits. Make sure to add the correct header lines like in existing translation files.
4. Add a commit message saying what you added and click the _Propose new file_ button

[priv/gettext]: https://github.com/adriankumpf/teslamate/tree/master/priv/gettext 
[priv/gettext/default.pot]: https://github.com/adriankumpf/teslamate/blob/master/priv/gettext/default.pot

**Comment by spacecosmos** [comment]
Thank you for your help guys. Not sure if I've done it correctly, but I managed to put inn two pull request:  #499 and #500 

Let me know if there is something else I need to do.(@adriankumpf)

**Comment by tabascoeye** [comment]
>     4\. Add a commit message saying what you added and click the _Propose new file_ button

whoa. I didn't know that works. Cool

**Comment by adriankumpf** [comment]
Merged into master. Thanks everyone!
