### ISSUE TITLE
Why is the Time to Try Sleeping different for older S/X?

### ISSUE THREAD

**Issue by Geitenijs** [adriankumpf/teslamate#497]
The default Time to Try Sleeping for 3 & S/X Raven is 12 minutes, whereas for older S/X it is 21.
I own a Model S from 2018 with MCU2. That's the same MCU as on the newer Raven S/X, so I'm wondering why this setting is different for my car.

Thanks in advance!

**Comment by adriankumpf** [comment]
The reason for this is that the Tesla API does not provide enough information about the hardware used (MCU1 vs MCU2; MCU retrofit etc). The distinction between Raven and older S/X, on the other hand, is easy to make.

**Comment by Geitenijs** [comment]
Ok great, thanks!
