### ISSUE TITLE
[Question] Anyone have it working on a Synology?

### ISSUE THREAD

**Issue by skaforey** [adriankumpf/teslamate#50]
I have docker installed on my Synology NAS, but while trying to get things configured, I am getting an error:

ERROR: for docker_db_1  Cannot start service db: driver failed programming external connectivity on endpoint docker_db_1 (a2649d4dc2c7ce59f684756281115ea6df883189a9b6d44b4e9923fc6b3848e0): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint docker_db_1 (a2649d4dc2c7ce59f684756281115ea6df883189a9b6d44b4e9923fc6b3848e0): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

5432 Seems to be the port that postgresql is listening on:

root@nas:/volume1/docker# netstat -an | grep 5432
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN
unix  2      [ ACC ]     STREAM     LISTENING     24238    /run/postgresql/.s.PGSQL.5432
unix  3      [ ]         STREAM     CONNECTED     46660660 /run/postgresql/.s.PGSQL.5432
unix  3      [ ]         STREAM     CONNECTED     46655926 /run/postgresql/.s.PGSQL.5432
unix  3      [ ]         STREAM     CONNECTED     46660662 /run/postgresql/.s.PGSQL.5432
unix  3      [ ]         STREAM     CONNECTED     190214   /run/postgresql/.s.PGSQL.5432

**Comment by ChromoX** [comment]
You probably already have a PostgreSQL instance running. If you instead change the environment variables to match the one you already have running you can use your existing one.

You could also try changing the port in the `docker-compose.yml` if you're using that. Remember to update the environment variables.

**Comment by mvaal** [comment]
I just tried and have the same issue. I am unfamiliar with elixir, but looks like it the config
https://github.com/adriankumpf/teslamate/blob/master/config/config.exs#L4
is using the default port (5432). I think something needs to be added here along the lines of
```
config :teslamate, TeslaMate.Repo,
  port: "5432" # Some configurable property here
```
Referencing this doc: https://github.com/elixir-ecto/ecto

Just changing the port on the docker-compose.yml I wouldn't think is enough because the application wouldn't know where to read it from.

**Comment by mvaal** [comment]
I have submitted a PR.
https://github.com/adriankumpf/teslamate/pull/52

**Comment by mvaal** [comment]
I attempted to change the port, but am getting the following error now:
```
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in TeslaApi.Auth.handle_response/1
            (tesla_api) lib/tesla_api/auth.ex:51: TeslaApi.Auth.handle_response({:ok, %Tesla.Env{__client__: %Tesla.Client{adapter: {Tesla.Adapter.Hackney, :call, [[recv_timeout: 30000]]}, fun: nil, post: [], pre: [{Tesla.Middleware.BaseUrl, :call, ["https://owner-api.teslamotors.com/"]}, {Tesla.Middleware.JSON, :call, [[]]}]}, __module__: Tesla, body: %{"response" => "authorization_required_for_txid_``"}, headers: [{"server", "nginx"}, {"date", "Sat, 27 Jul 2019 14:27:08 GMT"}, {"content-type", "application/json; charset=utf-8"}, {"transfer-encoding", "chunked"}, {"connection", "keep-alive"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"x-content-type-options", "nosniff"}, {"cache-control", "no-store"}, {"pragma", "no-cache"}, {"www-authenticate", "Bearer realm=\"Doorkeeper\", error=\"\", error_description=\"translation missing: en.doorkeeper.errors.messages\""}, {"x-request-id", "12d25e6c-1e5f-45e4-9ad2-c37cf593274d"}, {"x-runtime", "0.037536"}], method: :post, opts: [], query: [], status: 401, url: "https://owner-api.teslamotors.com/oauth/token"}})
            (teslamate) lib/teslamate/api.ex:47: TeslaMate.Api.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by adriankumpf** [comment]
It looks like your credentials are wrong? 

The error message is definitely a bug though. It should be clearly communicated what's going on.

**Comment by mvaal** [comment]
I got past that one after changing my password, new one
```
query: SELECT c0."id", c0."efficiency", c0."eid", c0."model", c0."vid", c0."inserted_at", c0."updated_at" FROM "cars" AS c0 WHERE (c0."eid" = $1)
            (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5
            (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
            (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
            (ecto) lib/ecto/repo/queryable.ex:67: Ecto.Repo.Queryable.one/3
            (teslamate) lib/teslamate/vehicles.ex:39: TeslaMate.Vehicles.create_new!/1
            (teslamate) lib/teslamate/vehicles.ex:25: anonymous fn/1 in TeslaMate.Vehicles.init/1
            (elixir) lib/enum.ex:1336: Enum
```

**Comment by adriankumpf** [comment]
It's really weird I'm also getting the same error (the first one) now

**Comment by mvaal** [comment]
I cleaned up my images and restarted from scratch with the new example from the README (https://github.com/adriankumpf/teslamate/pull/54) and it appears to be up and running now. Not sure what happened. Seems like the initial Auth failure might have corrupted the postgres database.

**Comment by adriankumpf** [comment]
Okay, great!

**Comment by mvaal** [comment]
The database issue I believe was because I missed the migration step. PR https://github.com/adriankumpf/teslamate/pull/51 fixed it after the latest update after I started from scratch.

I have no data in my Grafana, is this expected? Does it collect data from start time or should I expected to see legacy data show up as well?

**Comment by adriankumpf** [comment]
It cannot access legacy data but you should now see all trips, charging processes etc.

**Comment by skaforey** [comment]
If I use the docker compose file, do I need to do anything in postgres prior to running the commands? How about setting any variables outside the file? Sorry this is my first experience with docker so I'm a complete noob with it. Any help is appreciated

**Comment by mvaal** [comment]
You just need to change your TESLA_USERNAME and TESLA_PASSWORD in the docker-compose.yml file. With the latest changes it booted right up for me.

**Comment by skaforey** [comment]
Beautiful, I deleted everything and reinstalled and it's looking great!

@mvaal , I started it initially from the command line via ssh, but obviously that's not ideal as I don't want the window to remain open, so I ctrl-c out of that and then started each container via the GUI.  Is this how you do it?

Are you also getting a spinning circle via the web interface (http://nasip:4000) ?

**Comment by mvaal** [comment]
@skaforey no, I use the docker-compose file via ssh. Using
`docker-compose up -d` 
will run detached and leave the containers running
I am also getting the spinning circle, it looks to be because of some sort of cross-origin issue (most likely because we are on http://nasip:4000 and it is trying to hit a localhost url). I am attempting to get the code up and running, but I this is the first time I am looking at elixir so going to be slow. Maybe adriankumpf will have some ideas when he is back online.

**Comment by adriankumpf** [comment]
@mvaal, the solution is to set the `VIRTUAL_HOST` env variable like suggested here #60

**Comment by skaforey** [comment]
What is the best way to update using the docker-compose.yml file? In the instructions it says to just restart the container, but that didn't seem to do anything.  My yml file has the "latest" tag in it, so not sure if that's the issue where I need to re-pull the latest.  Just not sure how to do that.

**Comment by adriankumpf** [comment]
Yep, either explicitly set a specific version tag or use `latest` and run `docker-compose pull` before restarting.
