### ISSUE TITLE
Timeouts and late starts of drives

### ISSUE THREAD

**Issue by ArnoPW** [adriankumpf/teslamate#504]
Last few days I notice more and more that the starting point of drives only picks up a block or two from the real starting point. There are times that only a few minutes (less than 12) have passed since the last drive and also sometimes I'm sure Teslamate is not trying to let the car to go to sleep.

Also just this evening 2 drives have gone completely unnoticed. Grafana showed an incorrect SoC (must have been about the charge left after the last recorded drive). Car was online for more than 5 hours and pressing the button to try to go to sleep resulted in timeout every time.

I have now just executed a docker-compose pull followed by  docker-compose up -d and saw that MQTT and DB were updated. Teslamate and grafana both were untoched and are still running both for about 14 days now (I guess that's when I upgraded to 1.17.1

In the docker log there were a lot of messages like this one occuring about every 27 to 30 seconds.:

2020-03-09 17:39:01 | stdout | 18:39:01.083 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
-- | -- | --
2020-03-09 17:38:35 | stdout | 18:38:35.882 car_id=1 [error] Error / :timeout

Up until MQTT and DB were updated I could also not get a connection to the car from the Tesla app (maybe a coincidence that both started working after the upgrade, maybe a temporary fault in the Tesla servers). As soon as I did the upgrade however, all were working fine (grafana and teslamate after about 2 minutes just like after every upgrade).

Was this a temporary issue with Tesla's servers or could this have been a Teslamate issue? I didn't find any other messages on online forums about problems with the official Tesla app which in my case also didn't work for several hours.

**Comment by adriankumpf** [comment]
Yeah, for the past days there were some hiccups on the Tesla API side. That's why you couldn't get a connection from the app. Currently everything seems to be running smoothly again.
