### ISSUE TITLE
Overview with States

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#507]
I added the states bar to the overview screen:
![2020-03-11 17_35_58-Window](https://user-images.githubusercontent.com/8087682/76440980-fb57e900-63be-11ea-987c-38c00f6d3712.png)

(not sure, how to get the same times under the bar as in the two below. And how to get the blue "Last 24 hours"...)

Would it be interesting to add to the standard set? (Or replace the existing?)

**Comment by adriankumpf** [comment]
> (not sure, how to get the same times under the bar as in the two below. And how to get the blue "Last 24 hours"...)

In the "Queries" view you can set a "Relative time". 

> Would it be interesting to add to the standard set? (Or replace the existing?)

Sure, PRs are welcome! :) We would still need the "States" dashboard to be able to view more than 24 hours though. Maybe it would make sense to place the states graph under the other panels and then omit the "Relative time"?

**Comment by DrMichael** [comment]
> > (not sure, how to get the same times under the bar as in the two below. And how to get the blue "Last 24 hours"...)
> 
> In the "Queries" view you can set a "Relative time".
Ah, ok...
> > Would it be interesting to add to the standard set? (Or replace the existing?)
> Sure, PRs are welcome! :)
Shall I replace the current Overview then?
> We would still need the "States" dashboard to be able to view more than 24 hours though.
I did not intend to remove the States Dashboard. 
> Maybe it would make sense to place the states graph under the other panels and then omit the "Relative time"?
That looks good. Still, how could I possibly get the same time slots under the states bar?
![2020-03-11 19_24_55-Window](https://user-images.githubusercontent.com/8087682/76450705-87bdd800-63ce-11ea-9f48-e8337c87f791.png)

**Comment by adriankumpf** [comment]
Oh, then I misunderstood you. I thought you wanted to replace the States Dashboard in favor of the Overview + State dashboard (which I wouldn't object to btw). Anyway, feel free to create a PR with your extended Overview dashboard :)

> That looks good. Still, how could I possibly get the same time slots under the states bar? (And could I get German date format somehow?:-)

Good question ... I don't know if that can be changed.
