### ISSUE TITLE
Lets Encrypt doesn't auto renewal

### ISSUE THREAD

**Issue by robink2020** [adriankumpf/teslamate#510]
I use a rasp pi 3 with the software Teslamate.
So far I can see Lets Encrypt doesn't auto renewal.
How do i solve this problem?

Thanks

**Comment by Dulanic** [comment]
I use this container for all my letsencrypt stuff. Works very well and auto renews.

https://github.com/linuxserver/docker-letsencrypt

**Comment by adriankumpf** [comment]
The [Advanced Docker Setup with Traefik](https://teslamate.readthedocs.io/en/latest/installation/docker_advanced.html) in fact does auto renewal. For further information, also regarding customization options, please refer to the [Traefik docs](https://docs.traefik.io/https/acme/).
