### ISSUE TITLE
Dashboard links in kiosk mode

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#512]
**Describe the bug**

When clicking on a dashboardlink from the TeslaMate webpage, dashboard loads in kiosk mode. This prevents some dropdown options missing on the dashboard. 

**To Reproduce**

1. Load TeslaMate
2. Click on Dashboard, click on a dashboard you would like to review
3. Options are missing. (e.g. Vampire Drain dropdown)

**Expected behavior**

Dashboard opened from Dashboard link would mimic the dashboards opened directly in Grafana. 

**Screenshots**

Expected dashboard environment: 
![Screen Shot 2020-03-16 at 8 15 57 AM](https://user-images.githubusercontent.com/54645561/76762058-8ee23e80-675e-11ea-8bfe-1a9a7180392d.png)

Loaded dashboard environment; note the "kiosk" in the URL
![Screen Shot 2020-03-16 at 8 16 13 AM](https://user-images.githubusercontent.com/54645561/76762075-9a356a00-675e-11ea-811c-1030cd944807.png)

**Operating environment**

- TeslaMate Version: [v 1.17.1]
- Type of installation: [Docker]
- OS: [macOS]

**Comment by adriankumpf** [comment]
That's actually on purpose. Personally, I prefer the kiosk mode because it is clearer. Maybe it makes sense to make this optional …

Tip: You can leave kiosk mode by pressing `Esc`.

**Comment by cwanja** [comment]
I _figured_ there was a reason behind it. Makes sense and I agree, it does have a cleaner look. Is there any way to make the dropdown available in kiosk mode?

**Comment by adriankumpf** [comment]
That would be nice. But I don't know if that's possible with Grafana.
