### ISSUE TITLE
How to check TeslaMate Logs

### ISSUE THREAD

**Issue by tonyyng** [adriankumpf/teslamate#514]
A noobie question.  I'm running Teslamate using "docker-compose up -d".  How do you look at the logs?  I looked through the docs and didn't see it anywhere.  Perhaps it is something for FAQ or troubleshooting sections?

Specifically the configuration information for Tasker says:

Check your TeslaMate logs, and verify that you see something similar to the following:
![Image from docs](https://teslamate.readthedocs.io/en/latest/_images/teslamate-console-resume.png)

**Comment by DrMichael** [comment]
Try "docker-compose logs" or "docker-compose logs -f" to follow the logs. You also can restrict ist to individual services...

**Comment by tonyyng** [comment]
That's perfect.  Thanks.
