### ISSUE TITLE
Website link loop

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#515]
**Describe the bug**

When going into Grafana via TeslaMate, then back to TeslaMate to set the charging costs, you cannot get back into Grafana via the Dashboard links in the navigation header.

**To Reproduce**
1. Open TeslaMate
2. Navigation to Dashboard > Charges. Click to edit a charge
3. When back in TeslaMate, try to click on Dashboards and go back to Charges, or any other dashboard

**Expected behavior**

To be sent back into Grafana 

**Relevant entries from the logs**

Do not think these are needed, but let me know

**Operating environment**

- TeslaMate Version: [v1.71.1]
- Type of installation: [Docker]
- OS: [macOS, iOS]

**Comment by adriankumpf** [comment]
This is related to #431. It's a regression in Grafana. Starting with the next TM version we will open links in a new tab to work around this bug until Grafrana fixes it.
