### ISSUE TITLE
Mass Update of charging costs

### ISSUE THREAD

**Issue by drklain** [adriankumpf/teslamate#523]
version 1.18.0 says that a new feature is "Add option to calculate charging costs retroactively
Allow to enter total cost or cost per KWh used" but there is no information on where we do that.  I have a bunch of entries which are flagged as having charged at "Home" or "Work" and have entered in the costs for those locations, but that apparently is only picked up for future charges.  

How can we get that data inserted into past charges so that the total costs are accurate without manually going in and updating every charge session by hand?  The 1.18.0 announcement seems to indicate there is a way to do that, but I don't know where we do that (in Grafana or Teslamate Dashboard) or how.

**Comment by adriankumpf** [comment]
When creating/editing a geo-fence with a session fee or energy-based cost, you will be asked whether previous charges should be updated.

<img width="955" alt="Screenshot 2020-03-21 at 17 32 20" src="https://user-images.githubusercontent.com/8999358/77231244-00285400-6b9a-11ea-88b4-93b0cf320398.png">

With an existing geofence created before version 1.18, you would have to edit the "cost per kWh" and then save it. Then the modal is displayed.

**Comment by drklain** [comment]
Thanks.  Wasn’t obvious from the upgrade info and when you look at the charging costs for a geo fence, page looks the same until you change it to another value and hit “save”.

**Comment by adriankumpf** [comment]
Yeah, it's a little hard to find.

**Comment by picard001** [comment]
When I go to edit my Geofences the popup box briefly appears and fades away quickly.  There are many charges that are linked to the fence and have no cost reported.  I don't see anything in the browser console that indicates an error.  Any ideas?

**Comment by itsmjeu** [comment]
I dont see that on the 1.24 version how I can retroactively the prices update?

**Comment by vadikcoma** [comment]
I had issue with updating costs at one of my geo-fences. 

I got a popup, selected "update retroactively" and all my past charges in this location are still with the same costs. 

If I update costs now, I don't get popup anymore. 

I tried deleting geofence and adding new one with updated price - it doesn't update past charges

**Comment by warrenmr** [comment]
I have having the same problem as chrisgla and vadicoma:  I only get the "adjust prices retroactively" dialogue box when the geofence is first created.  Editing or deleting/recreating doesn't work.
