### ISSUE TITLE
A way to password protect the summary page in the manual install

### ISSUE THREAD

**Issue by rtega** [adriankumpf/teslamate#526]
I can't find a way to password protect the summary page in the manual install for ubuntu/debian. Is there a simple way to do this? Could a .htpasswd in the right location do this or is it more involved?

**Comment by adriankumpf** [comment]
It's a little bit more involved. You'd need a reverse proxy (e.g. nginx, traefik, Apache2) to do the authentication. Basically, what the "Advanced Docker Setup" from the TeslaMate docs does. In that case, you'll also want to use HTTPS so that the credentials aren't send in plain text.  Also make sure to to not expose port 4000 (and 3000) anymore. 

If possible, I'd recommend to use the [Advanced Docker Setup with Traefik](https://teslamate.readthedocs.io/en/latest/installation/docker_advanced.html).

**Comment by LostSoulfly** [comment]
I did this with Caddy very easily. Using a basic auth login. Works great. I also exposed teslastats.website.com with the same login.

```
tesla.website.com {
	basicauth / username password
	gzip
	log logs/tesla.access.log
		
	proxy / 192.168.10.156:4000 {
		websocket
		transparent
	} 
}
```

**Comment by timguy99** [comment]
@LostSoulfly are you running Caddy in docker? I would like to do that. If you can provide more info I will definitely setup Caddy as it looks damn slick.

**Comment by LostSoulfly** [comment]
No, sorry. I run Caddy on my Windows server and Teslamate via docker in a VM with Hyper-V. This looks like a popular Caddy docker solution: https://github.com/abiosoft/caddy-docker

The idea is pretty straightforward, though. Caddy acts as an intermediary with the outside world and proxies the connection back to your services. The connection externally is HTTPS secured, but the internal connection doesn't have to be. I also run multiple other services through the same Caddy instance (bitwarden_rs, plex, blueiris, gitea, etc). It's the easiest reverse proxy by far. 

Previously used nginx, but it gets complicated quickly. Caddy also automatically retrieves SSL certs from letsencrypt for your domain and subdomains.

**Comment by timguy99** [comment]
Yeah, I was going to run nginx and there was another one I looked into. But Caddy seems way more straight forward.

**Comment by rtega** [comment]
Trying to do this with lighttpd since I'm on a very limited system (pi zero) but can't seem to get the websockets to proxy correctly. I get:
`Error during WebSocket handshake: Unexpected response code: 400`

**Comment by LostSoulfly** [comment]
What does the console say? Is there an error or access denied? If you're using docker, try changing the VIRTUAL_HOST or CHECK_ORIGIN env variables. Personally, I'd just set CHECK_ORIGIN to false to make things easy.

**Comment by rtega** [comment]
Installed apache2 and now it works. You have to take care not to reverse the order in the statements though. This worked:
```
    ProxyPass /live/websocket ws://tata:4000/live/websocket
    ProxyPassReverse /live/websocket ws://tata:4000/live/websocket
    ProxyPass / http://tata:4000/
    ProxyPassReverse / http://tata:4000/

```
This not:
```
    ProxyPass / http://tata:4000/
    ProxyPassReverse / http://tata:4000/
    ProxyPass /live/websocket ws://tata:4000/live/websocket
    ProxyPassReverse /live/websocket ws://tata:4000/live/websocket
```

**Comment by bahree** [comment]
I hadn't heard of Caddy until now and possibly want to have a discussion around it - I did create a [message on the discord server](https://discordapp.com/channels/631168014540341268/631168014540341270) if that seems more appropriate.

**Comment by sumnerboy12** [comment]
Another Caddy user here (albeit only recently converted) - very impressive, and easy to use.

**Comment by JSaterdalen** [comment]
> I did this with Caddy very easily. Using a basic auth login. Works great. I also exposed teslastats.website.com with the same login.
> 
> ```
> tesla.website.com {
> 	basicauth / username password
> 	gzip
> 	log logs/tesla.access.log
> 		
> 	proxy / 192.168.10.156:4000 {
> 		websocket
> 		transparent
> 	} 
> }
> ```

Since this is an old post, do you have an updated Caddy config for teslamate? I can't get it working with Caddy v2.

```
tesla.{$MY_DOMAIN} {
	encode gzip
	log

	reverse_proxy teslamate:4000
}
```

**Comment by BradleyShaner** [comment]
> 
With v2 you have to use [caddy hash-password](https://caddyserver.com/docs/command-line#caddy-hash-password) to hash the password before adding it to the caddyfile. https://caddyserver.com/docs/caddyfile/directives/basicauth

Here's my current config, you can ignore any of it you don't need, such as wildcard certs, IP range blocking, and header options.

```


(wildcard_cert) {
  tls my.email.address@gmail.com {
    dns cloudflare fe1qJv6M4GhJghjTR6rDfgcvbhr745ghfghvvcDf
	resolvers 1.1.1.1
  }
}

(internal_only) {
	@blocked {
	not remote_ip 192.168.10.0/24
	not remote_ip 192.168.20.0/24
	not remote_ip 10.253.0.0/16
	}
	respond @blocked "nah, nice try tho lol" 403
}

(internal_blockiotguestsubnets) {
	@blocked {
	remote_ip 192.168.30.0/24
	remote_ip 192.168.40.0/24
	remote_ip 192.168.41.0/24
	}
	respond @blocked "nah, nice try tho" 403
}

teslastats.website.com {
	basicauth / {
		bob JDJhJDEwJEdkUjhMRi85Vkt0VWtudEpyLkl7821d2pkWnhXN3haWVJlQjZ2MGNzd2ZRZWEzNkFYQ1hH
	}
	encode gzip
	
	import wildcard_cert
	import internal_blockiotguestsubnets
	
	reverse_proxy 192.168.10.150:9017 {
		header_up X-Real-IP {remote_host}
		header_down X-Frame-Options "allow-from https://dash.website.com"
	} 
}

tesla.website.com {
	basicauth / {
		bob JDJhJDEwJEdkUjhMRi85Vkt0VWtudEpyLkl7821d2pkWnhXN3haWVJlQjZ2MGNzd2ZRZWEzNkFYQ1hH
	}
	encode gzip
	
	import wildcard_cert
	import internal_blockiotguestsubnets
	
	reverse_proxy 192.168.10.150:9016 {
		header_up X-Real-IP {remote_host}
		header_down X-Frame-Options "allow-from https://dash.website.com"
	} 
}
```

**Comment by JSaterdalen** [comment]
@BradleyShaner Great, thanks for that! Teslamate docs mention adding environment options to the container if proxying:

```
- VIRTUAL_HOST=${FQDN_TM}
- CHECK_ORIGIN=true
```

Your caddy config appears to work for me without doing that... Do you have those options in your compose file?

**Comment by BradleyShaner** [comment]
Glad it's working for you!

I had VIRTUAL_HOST set to my website subdomain and CHECK_ORIGIN=false, but I now run the [Unraid community app](https://github.com/simonsickle/unraid-templates/blob/main/teslamate/teslamate.xml) and didn't make such changes, it just works.

**Comment by JSaterdalen** [comment]
Do you happen to have an iOS device? This config works with teslamate on my desktop browser, but just shows a blank page on Safari on iOS.

**Comment by BradleyShaner** [comment]
Can't help you there, I'm Android only. But I also have internal DNS redirects on my LAN and wifi which bypasses the internet using Adguard DNS rewrites for my domains.

------- Original Message -------
