### ISSUE TITLE
Display Charged amount with kWh resolution in Top Charging Stations

### ISSUE THREAD

**Issue by SigLinJo** [adriankumpf/teslamate#528]
**Is your feature request related to a problem? Please describe.**
I really like the Charging Stats Dashboard but as my home charging has reached over 1 MWh it is only displayed as 1 MWh which is a bit low resolution to be really useful compared to the other that has kWh displayed.

**Describe the solution you'd like**

Best case solution would be if it is possible to get MWh to display with 3 decimals while kWh still displays with 0 decimals

**Describe alternatives you've considered**

Is it possible to force Grafana to only display as kWh even when total charged amount passes 1 MWh?

**Additional context**

Current look:
![Skärmavbild 2020-03-22 kl  22 58 29](https://user-images.githubusercontent.com/19478141/77261710-b3737480-6c90-11ea-9609-551bd9c7053a.png)

With 3 decimals. Good for MWh but looks bad for kWh
![Skärmavbild 2020-03-22 kl  22 56 00](https://user-images.githubusercontent.com/19478141/77261673-6bece880-6c90-11ea-99f4-a0b00df096a2.png)

**Comment by cwanja** [comment]
In the mean time, you can:

1. Login to Grafana (admin:admin if you have not changed it)
2. Click in the panel title and go to Edit
![image](https://user-images.githubusercontent.com/54645561/77548362-74097b80-6e7c-11ea-9eff-81b63dd7caff.png)
3. In the Edit screen, go to the Visualizations icon (middle icon, left hand side) and change the decimals to the desired amount. You can see in the screenshot above and below, I adjust it to three. 
![image](https://user-images.githubusercontent.com/54645561/77548483-9c917580-6e7c-11ea-8d83-1d83508ecbd2.png)

@adriankumpf this is a basic change, but I could do a pull request if you want? Also never done one, so that would be exciting.

**Comment by SigLinJo** [comment]
As you can see in my original post I did change it to 3 decimals but I think it looks a bit strange to display the kWh that way, only MWh needs to be changed to 3 decimals and that is outside my ability. But it is a good interim fix to actually be able to read out the amount charged when it goes above 1000 kWh :)

**Comment by cwanja** [comment]
Ah. I apologize, I missed that. Thought that second image is the _desired_ state. 🤦🏽‍♂️

**Comment by kongomongo** [comment]
Another solution would be to fix it to kWh with a custom unit...

![image](https://user-images.githubusercontent.com/5646390/79508514-ff200080-8039-11ea-9d30-d63eb47d5eda.png)

![image](https://user-images.githubusercontent.com/5646390/79508624-2bd41800-803a-11ea-93ff-2e67f452d6e7.png)

**Comment by cwanja** [comment]
> Another solution would be to fix it to kWh with a custom unit...
> 
> ![image](https://user-images.githubusercontent.com/5646390/79508514-ff200080-8039-11ea-9d30-d63eb47d5eda.png)
> 
> ![image](https://user-images.githubusercontent.com/5646390/79508624-2bd41800-803a-11ea-93ff-2e67f452d6e7.png)

Could you build logic into the custom unit to convert it from kWh to MWh once it exceeds a value?

**Comment by kongomongo** [comment]
i don't think so
https://grafana.com/blog/2020/01/27/grafana-v6.6-released/#custom-data-units

**Comment by Dulanic** [comment]
> > Another solution would be to fix it to kWh with a custom unit...
> > ![image](https://user-images.githubusercontent.com/5646390/79508514-ff200080-8039-11ea-9d30-d63eb47d5eda.png)
> > ![image](https://user-images.githubusercontent.com/5646390/79508624-2bd41800-803a-11ea-93ff-2e67f452d6e7.png)
> 
> Could you build logic into the custom unit to convert it from kWh to MWh once it exceeds a value?

No but you could do it in the SQL?

```
SELECT
	COALESCE(geofence.name, CONCAT_WS(', ', COALESCE(address.name, nullif(CONCAT_WS(' ', address.road, address.house_number), '')), address.city)) AS location,
      CASE
      WHEN SUM(charge_energy_added) BETWEEN 0 AND 999.999 THEN SUM(charge_energy_added)::NUMERIC(9, 3)::VARCHAR || ' kWh' 
      WHEN SUM(charge_energy_added) BETWEEN 1000 AND 999999.999 THEN (SUM(charge_energy_added) / 1000)::NUMERIC(9, 3)::VARCHAR || ' mWh' 
      WHEN SUM(charge_energy_added) >= 1000000 THEN (SUM(charge_energy_added) / 1000000)::NUMERIC(9, 3)::VARCHAR || ' gWh' 
   END AS charge_energy_added
FROM
	charging_processes c
LEFT JOIN addresses address ON c.address_id = address.id
LEFT JOIN geofences geofence ON geofence_id = geofence.id
WHERE
	$__timeFilter(end_date)
	AND car_id = $car_id
GROUP BY
	1
LIMIT 15;
```

**Comment by SigLinJo** [comment]
That looks very promising :) Thank you for looking into it! Just makes the M in MWh capital and it could be the solution we are looking for.

**Comment by Dulanic** [comment]
@SigLinJo  good catch, I'll put in a PR, it's a simple change and I like it.

**Comment by SigLinJo** [comment]
As soon as you do the PR I will test it :)

**Comment by SigLinJo** [comment]
Tested! I'm really happy about this! Makes this dashboard much more useful! Feel free to close this as soon as it's merged :)
