### ISSUE TITLE
Retroactive Charging Cost Disappears

### ISSUE THREAD

**Issue by picard001** [adriankumpf/teslamate#532]
When I go to edit my existing Geofence to add retroactive charging costs, the popup box briefly appears and fades away quickly. There are many charges that are linked to the fence and have no cost reported. I don't see anything in the browser console that indicates an error. Any ideas? v1.18

**Comment by adriankumpf** [comment]
Are there any errors in the logs? (The [bug report template](https://github.com/adriankumpf/teslamate/issues/new?assignees=&labels=&template=bug_report.md&title=) describes how to view the logs)

**Comment by picard001** [comment]
I walked through the steps again and checked the docker log, nothing but standard get/sent requests/responses for the geofence.  I've tried another browser and experienced the same issue.  Is there a reason it would show and then disappear?  It shouldn't show at all unless there are other charging sessions, correct?

**Comment by picard001** [comment]
I deleted and re-added the geofence and it prompted me to update all the charging sessions with the new rate.
