### ISSUE TITLE
Daily backup feature 

### ISSUE THREAD

**Issue by morten-holm** [adriankumpf/teslamate#533]
I would like teslamate to supply an automated backup feature. I'm running it off my Pi and the SD cards are known to fail at random times.

I would like that the daily backup supports sending the backup files to a remote location. This could be S3, ssh or something else.

**Comment by adriankumpf** [comment]
There are already several solutions to this problem: https://github.com/search?q=docker+postgres+s3+backup It does not require a built-in TeslaMate feature.
