### ISSUE TITLE
Charges not recorded properly since 1.18.1

### ISSUE THREAD

**Issue by rtfmjoey** [adriankumpf/teslamate#534]
Hi, 

I've updated from 1.18 to 1.18.1 and noticed that the charges aren't recorded properly anymore:

![teslamate_charges](https://user-images.githubusercontent.com/6972065/77616360-bb9e0f00-6f31-11ea-8085-0173da29b284.png)

I plugged the car in yesterday (25th) at 20:54 and had one charging session without breaks or pauses which lasted until 02:26.

As you can see there are multiple charges and only the last 27 minutes are recorded as a normal charge.

Also, I've pre-heated the car this morning and it charged a bit as the heater drained the battery, this charge is also not recorded, the same thing happened yesterday.

I'm also logging the charges directly from my EVSE and it used to match up with Teslamate:

![charge_log](https://user-images.githubusercontent.com/6972065/77616536-2cddc200-6f32-11ea-8c70-91dfdcc21409.png)

As you can see last night's charging session is recorded along the preheating/charging from this morning. The latter one doesn't seem te be recorded by Teslamate at all.

Any idea on what's happening?

**Comment by adriankumpf** [comment]
Can you please update the description of the issue according to the bug report template? 

> **Relevant entries from the logs**
> 
> You must provide the logs of the teslamate container/application unless the bug can be narrowed down to Grafana.
> To get the teslamate Docker container logs, for example, use the following command: `docker-compose logs teslamate`.
> 
> \```
> paste logs here
> \```

> **Data**
> 
> If applicable, add an export of the data for the given period.
> 
> For example, to export charge data after January 1, 2020:
> 
> ```bash
> docker-compose exec database psql teslamate teslamate -c \
>    "COPY (select * from charges where date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charges.csv
> 
> docker-compose exec database psql teslamate teslamate -c \
>    "COPY (select * from charging_processes where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charging_processes.csv
> ```
> 

 
> **Operating environment**
> 
> - TeslaMate Version: [e.g. v1.14.0]
> - Type of installation: [e.g. Docker or Manual]
> - OS: [e.g. Ubuntu]
>

**Comment by rtfmjoey** [comment]
Relevant entries from the logs
[teslamate_logs.txt](https://github.com/adriankumpf/teslamate/files/4388020/teslamate_logs.txt)

    Data

[charges.txt](https://github.com/adriankumpf/teslamate/files/4388024/charges.txt)
[charging_processes.txt](https://github.com/adriankumpf/teslamate/files/4388025/charging_processes.txt)


    Operating environment

        TeslaMate Version: 1.18.1
        Type of installation: Docker
        OS: Ubuntu 18.04.03 LTS


Looking through the logs it seems that the Tesla API/Servers have had serious issues last night. How is a car that's charging when it goes offline handled?

**Comment by adriankumpf** [comment]
Thanks! The car going offline when charging is not a problem, that case is already handled. However, the Tesla servers frequently returned invalid / incomplete data which caused troubles.

You can merge the corresponding charges by executing the following commands:

```bash
$ docker-compose exec database psql teslamate teslamate

  teslamate=# update charges set charging_process_id=262 where charging_process_id BETWEEN 248 AND 261;

  teslamate=# delete from charging_processes where id BETWEEN 248 AND 261;

$ docker-compose exec teslamate bin/teslamate rpc "TeslaMate.Repo.get!(TeslaMate.Log.ChargingProcess, 262) |> TeslaMate.Log.complete_charging_process()"
```

**Comment by rtfmjoey** [comment]
> 
> 
> Thanks! The car going offline when charging is not a problem, that case is already handled. However, the Tesla servers frequently returned invalid / incomplete data which caused troubles.
> 
> You can merge the corresponding charges by executing the following commands:
> 
> ```shell
> $ docker-compose exec database psql teslamate teslamate
> 
>   teslamate=# update charges set charging_process_id=262 where charging_process_id BETWEEN 248 AND 261;
> 
>   teslamate=# delete from charging_processes where id BETWEEN 248 AND 261;
> 
> $ docker-compose exec teslamate bin/teslamate rpc "TeslaMate.Repo.get!(TeslaMate.Log.ChargingProcess, 262) |> TeslaMate.Log.complete_charging_process()"
> ```

Worked like a charm, thanks!
