### ISSUE TITLE
After server reboot: Dashboards show data, web interface not

### ISSUE THREAD

**Issue by rakle** [adriankumpf/teslamate#535]
After updating to v1.18.1 all dashboards and the web interface worked well.
Then I had to reboot my server, and now the dashboards still show data but the web interface can not be accessed anymore (browser error: ERR_CONNECTION_REFUSED).

The log entries show a problem with the altering of a database column. The entry below repeats periodically every couple of seconds. Stopping and restarting the containers doesn't change anything.

Thank you very much for your help!

**Relevant entries from the logs**

```
teslamate_1  | 17:38:37.763 [info] == Running 20200306133847 TeslaMate.Repo.Migrations.AddFlatFee.change/0 forward
teslamate_1  | 17:38:37.771 [info] alter table geofences
teslamate_1  | ** (Postgrex.Error) ERROR 42701 (duplicate_column) column "session_fee" of relation "geofences" already exists
teslamate_1  |     (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:699: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.3.4) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate_1  |     (ecto_sql 3.3.4) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
teslamate_1  |     (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate_1  |     (ecto_sql 3.3.4) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
teslamate_1  |     (stdlib 3.12) timer.erl:166: :timer.tc/1
```

**Operating environment**

- TeslaMate Version: v1.18.1
- Type of installation: Docker
- OS: Ubuntu 19.10

**Comment by adriankumpf** [comment]
It looks like the update to 1.18 was not successful or the database was corrupted (e.g. by a bad SD card when using a Raspberry Pi).

Deleting the `session_fee` column from the `geofences` table and then restarting TeslaMate should solve this problem.

**Comment by rakle** [comment]
Deleting this column has solved the problem perfectly.
Thany you very much for your quick help!
