### ISSUE TITLE
Restoring backup on Windows not working

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#541]
Hi, I was testing the backup and restore, to get confidence it is working before upgrading postgres from v11 to v12. I am running Teslamate on a raspberry pi 4 (that is my primary) and to test this, I installed docker on windows and tried to restore it there but it fails I can get the following error.

Docker is setup as Linux containers on Windows and I can get Teslamate up and running (fresh install) and can login and see dashboards. Of course there isn't any data which is OK.

I created the backup, and copied over that file from the pi to my windows machine and when I tried to run the restore command as outlined in the [documentation here](https://teslamate.readthedocs.io/en/latest/maintenance/backup_restore.html), it fails because of multi-lines as shown below. 
![image](https://user-images.githubusercontent.com/3529468/77873640-6a2aa400-71ff-11ea-9cd7-8b37fb3ffe1c.png)

I tried to create a batch file and run that, I get the same error.

Any guidance on how I can try to restore on Windows?

Thanks.

**Comment by DrMichael** [comment]
Well, obviously redirection in PoerShell does not work as it does in a Unix shell. Can you run bash in the PowerShell?

**Comment by gaLDWoRE** [comment]
Running into the same issue. I've tried to setup bash, you can do so by enabling the Windows Subsystem for Linux under Programs and Features, and then installed Ubuntu, then just type bash in powershell inside TeslaMate directory, but it doesn't even think that docker-compose is installed. 
Trying to install docker-compose through bash says that it cannot locate package docker-compose.

**Comment by pratik5705** [comment]
Here is what I did: I ran a bash into the postgres database and directed typed in the database commands
drop schema public cascade;
..
one by one.
I am running portainer and used that interface to bash into postgres sql.
I believe that the latest instructions provide information on how to setup portainer. See https://docs.teslamate.org/docs/guides/portainer

I would highly recommend portainer generally as well.

**Comment by bahree** [comment]
Thanks, thats a good tip. I was running Portainer already and never thought of this. But I did restore the backup on my NAS and setup a cron job.

**Comment by aialles** [comment]
> Here is what I did: I ran a bash into the postgres database and directly typed in the database commands
> drop schema public cascade;
> ..
> one by one.
> I am running portainer and used that interface to bash into postgres sql.
> I believe that the latest instructions provide information on how to setup portainer. See https://docs.teslamate.org/docs/guides/portainer
> 
> I would highly recommend portainer generally as well.

Please help to advise more in detail, ive connected to  teslamate_database_1 postgres:13 via portainer. But it says command not found

`drop schema public cascade;
`
