### ISSUE TITLE
Hassio addon

### ISSUE THREAD

**Issue by Dominoo** [adriankumpf/teslamate#545]
Did you consider creating the hassio addon so TeslaMate could run on the same machine as my home assistant so I do not have to pay for the server? 

I might give you a help I just dont know if there is any limitation you would know off

**Comment by adriankumpf** [comment]
This proposal and potential challenges are discussed here: #467. Help is definitely needed. This feature could work well as a third party addon that would be maintained outside the main TeslaMate repo.
