### ISSUE TITLE
Create a Discourse site?

### ISSUE THREAD

**Issue by jomaxro** [adriankumpf/teslamate#546]
Continuing the discussion from #198:

Is here any need for long-form, searchable discussion? Discord is great for chat and quick discussions, but search isn't great and it can be hard to find things after time passes. I've found that the same questions tend to get asked over and over again.

As this is open source, you'd qualify for a free Discourse site: https://free.discourse.group/. Alternately, Discourse is open source so you could host it yourself.

Disclosure: I work for Discourse. I'm also a proud Tesla owner.

**Comment by bahree** [comment]
We already have one; see #198. Maybe we should add it to the docs and the overview.

**Comment by jomaxro** [comment]
That's Discord, a chat software, not Discourse, a discussion forum.

**Comment by adriankumpf** [comment]
Since GitHub Discussions are now available, we will move all discussions there.
