### ISSUE TITLE
Teslamate, Grafana & Database Exited with code 139 

### ISSUE THREAD

**Issue by NPSconsultingLLC** [adriankumpf/teslamate#547]
Hello - 

I'm hoping somebody can help me out, after install when I run 'compose up' I receive the same error over and over: 

pi_teslamate_1 exited with code 139
pi_grafana_1 exited with code 139
pi_database_1 exited with code 139

This is running on a raspberry pi w zero. I am not sure what details people would need, but I am happy to provide additional details upon request i

**Comment by adriankumpf** [comment]
The raspberry pi w zero is not supported  as it uses the ARMv6 instruction set architecture. But I suspect you wouldn't be happy with that hardware anyway. I would recommend a rpi 3 or 4 or, if possible, something even more performant.

**Comment by NPSconsultingLLC** [comment]
Thanks so much for the quick response. Awesome project BTW.
