### ISSUE TITLE
GET /sign in loop on Login page

### ISSUE THREAD

**Issue by jmsaham** [adriankumpf/teslamate#548]
I just completed a fresh install on Digital Ocean.

When i signin using the .htpasswd it takes me to the page to enter my Tesla credentials.
Here the sign-in button doesnt work. The page constantly refreshes. 
In the console i see the following:

teslamate_1  | 05:05:51.394 [info] Version: 1.18.2
teslamate_1  | 05:05:51.446 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
teslamate_1  | 05:05:51.448 [info] Access TeslaMateWeb.Endpoint at http://teslamate.c0mrade.net
mosquitto_1  | 1585717551: New connection from 172.19.0.6 on port 1883.
mosquitto_1  | 1585717551: New client connected from 172.19.0.6 as TESLAMATE_302E3031303 (p2, c1, k60).
teslamate_1  | 05:05:51.460 [info] MQTT connection has been established
teslamate_1  | 05:06:14.099 [info] GET /
teslamate_1  | 05:06:14.114 [info] Sent 302 in 15ms
teslamate_1  | 05:06:14.144 [info] GET /sign_in
teslamate_1  | 05:06:14.155 [info] Sent 200 in 11ms
teslamate_1  | 05:06:17.620 [info] GET /sign_in
teslamate_1  | 05:06:17.624 [info] Sent 200 in 3ms
teslamate_1  | 05:06:21.119 [info] GET /sign_in
teslamate_1  | 05:06:21.124 [info] Sent 200 in 5ms
teslamate_1  | 05:06:22.892 [info] GET /sign_in
teslamate_1  | 05:06:22.895 [info] Sent 200 in 2ms
teslamate_1  | 05:07:56.893 [info] GET /sign_in
teslamate_1  | 05:07:56.897 [info] Sent 200 in 3ms
teslamate_1  | 05:07:56.929 [info] GET /sign_in
teslamate_1  | 05:07:56.932 [info] Sent 200 in 2ms

**Comment by adriankumpf** [comment]
Which browser are you using and could you please try to sign in with another browser? And are there any additional error messages visible in the browser console?

**Comment by jmsaham** [comment]
The above was using the latest Safari.

When I use Chrome 80 - get a ERR_TOO_MANY_RETRIES

I ran Console in Safari on the mainpage and get:
WebSocket connection to 'wss://teslamate.c0mrade.net/live/websocket?_csrf_token=VmF4BSwhJAwVLQMuICgrJyQ-CyQxDjJgfYKHVMBcYdNBZJ_Thn_HTE_8&baseUrl=https%3A%2F%2Fteslamate.c0mrade.net&referrer=https%3A%2F%2Fteslamate.c0mrade.net%2Fsign_in&tz=America%2FLos_Angeles&vsn=2.0.0' failed: Unexpected response code: 401

**Comment by adriankumpf** [comment]
Thanks. Safari has a long-standing bug (see #415) that makes it impossible to use basic authentication. Chrome should work fine though. Do you run the [Advanced Docker Setup with Traefik](https://teslamate.readthedocs.io/en/latest/installation/docker_advanced.html)?

**Comment by jmsaham** [comment]
I get the below errors. But I set all these in my .env files which is stored at "/"

root@teslamate:~# docker-compose logs -f proxy
WARNING: The TM_DB_USER variable is not set. Defaulting to a blank string.
WARNING: The TM_DB_PASS variable is not set. Defaulting to a blank string.
WARNING: The TM_DB_NAME variable is not set. Defaulting to a blank string.
WARNING: The FQDN_TM variable is not set. Defaulting to a blank string.
WARNING: The TM_TZ variable is not set. Defaulting to a blank string.
WARNING: The GRAFANA_PW variable is not set. Defaulting to a blank string.
WARNING: The GRAFANA_USER variable is not set. Defaulting to a blank string.
WARNING: The FQDN_GRAFANA variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
Attaching to default_proxy_1

**Comment by jmsaham** [comment]
I moved my .env to ~/ (root directory) and that seemed to fix the issue
