### ISSUE TITLE
Importing large-ish dataset failed at one file

### ISSUE THREAD

**Issue by gilrim** [adriankumpf/teslamate#549]
**Describe the bug**

I've imported 17 files exported from teslafi, 285mb. The dataset covers December 18 to today, and failed at 27th of October 19. The error message are clear enough, but I figured I'd just retry to make sure before I'd remove the line in question. restarting the images seemed to work though and I went on to do this a few times as the import tool would just handle one file at a time. After this I restarted the image again after removing the import data, and are still missing any data after that date.  

**To Reproduce**

Configure images and import data from teslafi

**Expected behavior**

Resume the import on the next line after the erroneous one or allow for some way of fixing the import

**Relevant entries from the logs**
```
teslamate_1  | 18:40:49.514 [error] GenStateMachine :import_ELdar terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2019-10-27 01:14:42.000000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate_1  |     (teslamate 1.18.2) lib/teslamate/vehicles/vehicle.ex:425: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.12) gen_statem.erl:1120: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
teslamate_1  | 18:40:49.517 [warn] Import failed: {{:badmatch,
teslamate_1  |   {:error,
teslamate_1  |    #Ecto.Changeset<
teslamate_1  |      action: :update,
teslamate_1  |      changes: %{end_date: ~U[2019-10-27 01:14:42.000000Z]},
teslamate_1  |      errors: [
teslamate_1  |        end_date: {"end date must be after start date",
teslamate_1  |         [constraint: :check, constraint_name: "positive_duration"]}
teslamate_1  |      ],
teslamate_1  |      data: #TeslaMate.Log.State<>,
teslamate_1  |      valid?: false
teslamate_1  |    >}},
teslamate_1  |  [
teslamate_1  |    {TeslaMate.Vehicles.Vehicle, :handle_event, 4,
teslamate_1  |     [file: 'lib/teslamate/vehicles/vehicle.ex', line: 425]},
teslamate_1  |    {:gen_statem, :loop_state_callback, 11, [file: 'gen_statem.erl', line: 1120]},
teslamate_1  |    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
teslamate_1  |  ]}
```

**Screenshots**
First error
![Screenshot-20200402204431-931x940](https://user-images.githubusercontent.com/434698/78301675-bb0d0600-7539-11ea-8cab-348f355c3481.png)
Subsequent imports:
![Screenshot-20200402221952-947x388](https://user-images.githubusercontent.com/434698/78301687-bea08d00-7539-11ea-8685-f36c4abf706b.png)
![Screenshot-20200402224256-993x354](https://user-images.githubusercontent.com/434698/78301703-c4966e00-7539-11ea-8a80-7559e976ea5b.png)

**Data**
```
TeslaFi102019.csv:478476,"2019-10-27 01:14:41",True,,2032196445,Eldar,None,None,,VINNUMBER,None,47991870819368039,,,online,None,0.0,13,True,False,None,False,None,250.64,None,90,None,<invalid>,,None,False,<invalid>,86,False,90,None,87,27.04,None,0,100,200.51,False,Complete,None,None,False,None,178.87,0.0,None,13,True,84.0,50,105.0,None,10.260538,274,1572131681,59.83532,None,None,,,0,25.0,None,25.0,None,,False,,False,0,0,False,,,,,,,1,False,True,,True,None,0,75077.428831,False,0,,None,,False,True,0,0,None,0,6,0,0,SteelGrey,0,standby,unknown,True,Eldar,0,,model,Base19,True,0,,"2019.32.12.2 58f3b76",,,None,None,None,75077.4288,2393,0,0,0,,26,0,0,294.83,None,28.0,False,None,15.0,0,0,,,,
```

**Operating environment**

- TeslaMate Version:  v1.18.2
- Type of installation: Docker
- OS: qnap / qts

**Comment by gilrim** [comment]
Follow up as I've been trying to figure out what's causing this: 
Teslafi export files is identical to the ones created by the python script posted yesterday. Also tried purging data earlier than a given date (per comments to issue #529) and then reimport using v1.19-dev, unfortunately i'm still getting the same error messages. I've tried removing the lines in question from the export but that didn't resolve the issue. Could I send you the export for review?

**Comment by adriankumpf** [comment]
I haven't had time to look into it yet, but thanks to your bug report I have an idea what the issue is. It would still be great if you could send me the file (10/2019). This would make testing much easier. You can null/remove the latitude/longitude if you want.
