### ISSUE TITLE
Report imperial metrics

### ISSUE THREAD

**Issue by zklapow** [adriankumpf/teslamate#55]
obviously, the metric system is better but as someone living in the US it would be nice if there was a config to swap to reporting in Miles and Fahrenheit.

 I have started doing this by simply converting units in the queries on my Grafana dashboards but this is a bit of a hassle.

**Comment by adriankumpf** [comment]
Yeah, that's definitely on the roadmap. I guess most users of this logger would now prefer imperial metrics 😃

My approach would've also been to do the conversion in Grafana itself. We could add a dashboard variable that toggles between both systems.

**Comment by zklapow** [comment]
👍 I will keep slowly adding in conversions then, I'll try to PR some of those dashboards when/if they are more complete.

**Comment by adriankumpf** [comment]
Okay, cool!

**Comment by adriankumpf** [comment]
I've had some time to add support for imperial metrics. Please upgrade to the newest version and re-import the dashboards afterwards.
