### ISSUE TITLE
Grafana snapshots include data beyond specified time range

### ISSUE THREAD

**Issue by MaxG88** [adriankumpf/teslamate#553]
**Describe the bug**
When publishing snapshots of the Trip dashboard in Grafana, it seems like all the States data is pulled, instead of only the data for the specified time range. If someone changes the time range on a snapshot, they could get all the States data for whatever time range they want.
I've only noticed this with States and not for anything else.

I'm not 100% sure it's an issue with TeslaMate, but since everything else seems to work fine, I'm assuming it is.
I could send you an example snapshot in private if you want.

**To Reproduce**

1. Go to Trip dashboard on Grafana
2. Set Time Range to, for example, 2020/02/01-2020/02/02
3. Publish snapshot
4. Open created snapshot
5. Change the time range to, for example, 2019/10/01-2020/04/01
6. The States data should include data outside of the time range specified when the snapshot was created

**Expected behavior**
States data beyond specified time range should not be included in the snapshot.

**Operating environment**

- TeslaMate Version: v1.18.2
- Type of installation: Docker
- OS: Ubuntu 16.04

**Comment by adriankumpf** [comment]
Good catch. We still need to include data beyond specified time range, for example, to cover the case where there aren't any state changes for a few of days or even weeks. But it doesn't makes sense, of course, to include the entire states history.

**Comment by MaxG88** [comment]
Tested on 1.19.1 and the issue still exists. Could you reopen this issue or would you prefer that I open a new one?
