### ISSUE TITLE
Better documentation on MQTT Setup

### ISSUE THREAD

**Issue by Fr0sk** [adriankumpf/teslamate#556]
Hello. I'm trying to connect Teslamate with my HomeAssistant instalation. Both are running on the same hardware. I also have a MQTT Broker already configured (it is the HomeAssistant Mosquitto addon). However, I'm not able to connect to the MQTT Broker. Probably is my docker-fu that is not very good, but I think with a little improvement on the documentation to make it easier for docker-newbies like me would help a lot!

I am using the sismple docker install of Teslamate and already changed the enviroment variables of the docker-compose teslamate service to include the MQTT_HOST, MQTT_USERNAME and MQTT_PASSWORD. On the host I tried all variations of "mqtt://127.0.0.1:1883" (with and without the port and with and without the 'mqtt://'). I also tried to change the network_mode to host and change the DATABASE_HOST correspondingly. None of it worked, every time I get an error saying MQTT timed out.

Can you please clarify how to connect to an external broker using the simple docker install of Teslamate? 

Thank you in advance.

**Comment by adriankumpf** [comment]
`127.0.0.1` or `localhost` inside a container do not refer to the host. Try to use the host IP address (`ip route|awk '/default/ { print $3 }'`) as `MQTT_HOST`.

You'll see ` [info] MQTT connection has been established` in the logs right after startup if it worked.

**Comment by Fr0sk** [comment]
Using `ip route|awk '/default/ { print $3 }'` as host didn't worked either, but got me to a solution. The command as is has invalid interpolation format, and after searching for a bit I figured it should be `ip route|awk '/default/ { print $$3 }'` (correct me if I'm wrong). However, I found out that to use a literal `$`, two should be used, and my MQTT secret had one. So, using `network_mode: host` now works as intended, although not the desired solution since I have to open the databse port to the host.

Thank you for your help :)

**Comment by adriankumpf** [comment]
This should work if you want to pass the current host address.

```yaml
    environment:
      MQTT_HOST: $MQTT_HOST
      MQTT_PASSWORD: "your$$password"
```

```bash
$ MQTT_HOST=$(ip route|awk '/default/ { print $3 }') docker-compose config
```
