### ISSUE TITLE
docker-compose has no "down" for a single service

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#557]
**Describe the bug**

In the docs for "Backup and Restore" in the Restore part, it says: `docker-compose down teslamate`

That does not work for me, shouldn't it be `docker-compose stop teslamate`? Or is that not enough?

**To Reproduce**

Run "docker-compose down teslamate", and you get an error message. 

**Operating environment**

- TeslaMate Version: v1.18.2
- Type of installation: Docker, docker-compose 1.17.1 and 1.21.0
- OS: Ubuntu 18.04.4 LTS and Raspbian GNU/Linux 10

**Comment by adriankumpf** [comment]
Yeah, `docker-compose stop teslamate` is the correct one.

**Comment by bahree** [comment]
I think there is another 'bug' in the documentation - when restoring one also needs to make sure the database is running. So it would need this before running the restore:
`docker-compose up -d database`

I am not sure where I can do to edit and submit a change on the docs. Happy to do that if one of you can teach me how to fish. :)

**Comment by DrMichael** [comment]
Or `docker-compose start database`?

**Comment by bahree** [comment]
Technically in this case either would work. Of course the `start` expects a container to exist (which should not be a issue in the case of backup and restore), and the `up -d` would go ahead and build the image if required and create the container. 

Building the image might be needed when upgrading. I am more use to `up -d` and most documentation uses that and lean towards that. :)

**Comment by DrMichael** [comment]
Ah, yes, `docker-compose up -d database` would be on the safe side.
