### ISSUE TITLE
Drives not recorded

### ISSUE THREAD

**Issue by srivaths** [adriankumpf/teslamate#558]
Preface: This is not an issue per se.  It is more of a question to ensure that I am not doing something wrong.

Teslamate version: 1.18.2
I am a fairly recent user of Teslamate (1 week or so). It has been working flawlessly until yesterday.  This morning, I pulled up my Grafana site and noticed that none of my drives of yesterday were showing up.  I have verified that I have a live connection to the car (it shows the sleep state accurately, it shows that it is currently on charger & charging).

The one thing that _did_ change between when Teslamate was able to capture data and yesterday was that I upgraded the car to 2020.12.1 (which by the way Grafana shows on the Updates dashboard).

What am I doing wrong?  Any other data points you need to help diagnose the issue?

Sri

**Comment by adriankumpf** [comment]
> What am I doing wrong? Any other data points you need to help diagnose the issue?

The [Bug report template](https://github.com/adriankumpf/teslamate/issues/new?assignees=&labels=&template=bug_report.md&title=) lists relevant steps for diagnosing the problem, especially the evaluation of the log. Please update the issue description with this information.

**Comment by srivaths** [comment]
Thanks, will do.  Sorry for not doing that in the first place (wasn't aware of the template).
