### ISSUE TITLE
Drives not recorded

### ISSUE THREAD

**Issue by srivaths** [adriankumpf/teslamate#559]
**Describe the bug**

This morning, I pulled up Grafana site and noticed that none of my drives of yesterday were showing up. I have verified that I have a live connection to the car (it shows the sleep state accurately, it shows that it is currently on charger & charging).

The one thing that did change between when Teslamate was able to capture data and yesterday was that I upgraded the car to 2020.12.1 (which by the way Grafana shows on the Updates dashboard).

**To Reproduce**

1. Go to 'Grafana'
2. Click on 'Drives'
3. View list of drives
4. Drives are missing

**Expected behavior**

The listing of drives should include all the drives made with the car

**Relevant entries from the logs**

```
teslamate_1  | 07:31:14.454 car_id=1 [info] Start / :asleep
teslamate_1  | 07:57:09.718 car_id=1 [info] Start / :online
teslamate_1  | 08:12:24.213 car_id=1 [info] Suspending logging
teslamate_1  | 08:33:35.103 car_id=1 [info] Start / :asleep
teslamate_1  | 08:39:19.536 car_id=1 [info] Start / :online
teslamate_1  | 08:54:31.318 car_id=1 [info] Suspending logging
teslamate_1  | 09:15:34.321 car_id=1 [info] Suspending logging
teslamate_1  | 09:36:45.211 car_id=1 [info] Start / :offline
teslamate_1  | 11:38:43.968 car_id=1 [info] Start / :online
teslamate_1  | 11:45:44.431 car_id=1 [error] Error / :timeout
teslamate_1  | 11:53:47.353 car_id=1 [info] Suspending logging
teslamate_1  | 12:14:58.215 car_id=1 [info] Start / :asleep
teslamate_1  | 13:10:03.641 [info] Adding elevation to 11 positions ...
teslamate_1  | 14:12:49.661 car_id=1 [info] Start / :online
teslamate_1  | 14:12:49.773 [info] Querying location for elevation takes longer than 100ms ...
teslamate_1  | 14:13:43.269 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 14:13:43.269 car_id=1 [error] Error / :timeout
teslamate_1  | 14:14:08.656 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 14:14:08.657 car_id=1 [error] Error / :timeout
teslamate_1  | 14:14:34.065 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 14:14:34.065 car_id=1 [error] Error / :timeout
teslamate_1  | 14:14:49.468 [error] TeslaApi.Error / 408 – %{
teslamate_1  |   "error" => "vehicle unavailable: {:error=>\"vehicle unavailable:\"}",
teslamate_1  |   "error_description" => "",
teslamate_1  |   "response" => nil
teslamate_1  | }
teslamate_1  | 14:14:59.673 car_id=1 [info] Start / :offline
teslamate_1  | 15:40:30.516 car_id=1 [info] Start / :online
teslamate_1  | 15:55:42.486 car_id=1 [info] Suspending logging
teslamate_1  | 16:16:43.657 car_id=1 [info] Suspending logging
teslamate_1  | 16:37:44.824 car_id=1 [info] Suspending logging
teslamate_1  | 16:58:46.086 car_id=1 [info] Suspending logging
teslamate_1  | 17:19:47.279 car_id=1 [info] Suspending logging
teslamate_1  | 17:40:48.456 car_id=1 [info] Suspending logging
teslamate_1  | 18:01:59.090 car_id=1 [info] Start / :asleep
teslamate_1  | 20:12:49.787 [info] Adding elevation to 1 positions ...
teslamate_1  | 00:00:07.255 car_id=1 [info] Start / :online
teslamate_1  | 00:15:18.763 car_id=1 [info] Suspending logging
teslamate_1  | 00:36:29.653 car_id=1 [info] Start / :asleep
teslamate_1  | 06:11:05.301 car_id=1 [info] Start / :online
teslamate_1  | 06:11:05.410 [info] Querying location for elevation takes longer than 100ms ...
teslamate_1  | 06:11:26.850 car_id=1 [info] Charging / SOC: 67% / Home
teslamate_1  | 06:12:43.488 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 06:12:43.489 car_id=1 [error] Error / :timeout
teslamate_1  | 06:12:58.589 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 06:12:58.590 car_id=1 [error] Error / :timeout
teslamate_1  | 06:50:31.642 [info] GET /
teslamate_1  | 06:50:31.650 [info] Sent 200 in 8ms
teslamate_1  | 09:18:30.468 [info] GET /
teslamate_1  | 09:18:30.475 [info] Sent 200 in 7ms

```

**Screenshots**

N/A

**Data**

No issues with charging reports

Drive report only shows drives from before yesterday (4 in all).

**Operating environment**

- TeslaMate Version: 1.18.1
- Type of installation: Docker
- OS: Ubuntu

**Comment by adriankumpf** [comment]
When did these drives take place? But as there are no errors or API timeouts you're drives could not be recorded because logging was suspend to let the car fall asleep. Check out the documentation on that topic: https://teslamate.readthedocs.io/en/v1.18.1/configuration/sleep.html

Note: the next TeslaMate release which is currently in beta doesn't have that limitation anymore.

**Comment by srivaths** [comment]
@adriankumpf Thanks for the response.  I have read the docs on sleep settings.  Being a new user I have kept the system defaults until I learn the system better and tweak it.  This has worked fine for my other drives.  Yesterday's drives were around between 1300-1500.  There were 3 drives about 30 mins, 15 mins and 15 mins.

The logs _do_ report a few 504 errors in that time frame.  Actually it reports similar errors at 0600 today as well.

**Comment by adriankumpf** [comment]
The default sleep mode settings are fine most of the time but to catch every drive providing wake-up hints is still recommended (or wait for v1.19).

> The logs do report a few 504 errors in that time frame. Actually it reports similar errors at 0600 today as well.

Those timeouts only occurred in a time window of 2 minutes, so no big deal. However, if you were driving between 14:14:59 and 15:40:30, and thus the car was not offline, no API logger could have recorded the drive, because the car was simply reported offline (for whatever reason, but this happens in rare cases).
