### ISSUE TITLE
Consumption is not displayed

### ISSUE THREAD

**Issue by derseinermit** [adriankumpf/teslamate#560]
**Describe the bug**

I cant see the Consumption and used kW/h of my drives. Everything else works fine

**Screenshots**

![1](https://user-images.githubusercontent.com/63250308/78579633-84810500-7831-11ea-8ba4-7df898c31045.jpg)
![2](https://user-images.githubusercontent.com/63250308/78579648-88ad2280-7831-11ea-8fa4-c5bff08ae0ee.jpg)

**Operating environment**

- TeslaMate Version: v1.18.2
- Type of installation: Docker
- OS: Synology

**Comment by adriankumpf** [comment]
From the [FAQ](https://teslamate.readthedocs.io/en/v1.18.1/faq.html):

> **Why are no consumption values displayed in Grafana?**
> 
> Unfortunately the Tesla API does not return consumption values for a trip. In order to still be able to display values TeslaMate estimates the consumption on the basis of the recorded (charging) data. It takes at least two charging sessions before the first estimate can be displayed. Each charging session will slightly improve the accuracy of the estimate, which is applied retroactively to all data.
