### ISSUE TITLE
Please keep the version button on the homepage... :-)

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#565]
Hi @adriankumpf, I noticed in 1.19.0-dev, that you removed the version button on the home page in favour of having the info in the settings.

Couldn't we have both? I really liked it on the homepage...

(Btw, perhaps it would be good to have separate images for latest, testing, dev?)

**Comment by adriankumpf** [comment]
Why, though? 😄 Are you worried you'll miss an update? Starting with v1.19 you'll get an update notification. That's why I removed the version button.

**Comment by bahree** [comment]
+1 to this request.  @adriankumpf  how would the update notification work? I like the simplicity of being able to click on this and get to see if there is something new. Is the notification on the same page?

**Comment by DrMichael** [comment]
> Why, though? 😄 Are you worried you'll miss an update?

Eh, no. Having several instances installed, I soometimes get confused, which version is running where.

> Starting with v1.19 you'll get an update notification. That's why I removed the version button.

That is, of course, excellent. Any chance for automatic update? Or update by button push?

**Comment by adriankumpf** [comment]
I see. But most users probably have only one instance, right? ;-) I think the extra click needed to get to the version is okay for now.

**Comment by adriankumpf** [comment]
> +1 to this request. @adriankumpf how would the update notification work? I like the simplicity of being able to click on this and get to see if there is something new. Is the notification on the same page?

Wait and see! :)

**Comment by bahree** [comment]
Hey @adriankumpf - I wanted to understand how is this going to work? Upgraded to v1.19.0 yesterday, and saw this morning that v1.19.1 came out but didn't get any notification when I login. I got to know of the update because of github notifications. Is there a config change I need to do. I don't see anything on the settings page. So curious to know what I am missing.

Thanks.

**Comment by cwanja** [comment]
> Hey @adriankumpf - I wanted to understand how is this going to work? Upgraded to v1.19.0 yesterday, and saw this morning that v1.19.1 came out but didn't get any notification when I login. I got to know of the update because of github notifications. Is there a config change I need to do. I don't see anything on the settings page. So curious to know what I am missing.
> 
> Thanks.

@bahree - bottom of the home page is a subtle, gray text that lists that there is an update. Suggest making that more persistent and visible @adriankumpf

**Comment by bahree** [comment]
I don't see that. Any ideas on what is missing or blocking?

E.g here is the image from the bottom of the settings page:
![image](https://user-images.githubusercontent.com/3529468/80051958-5ad10a80-84ce-11ea-9aa2-6b3ecd057759.png)

And on TeslaMate's 'home page' - I only see the donate option.
 
![image](https://user-images.githubusercontent.com/3529468/80052039-8653f500-84ce-11ea-8a2b-5deebab5809d.png)

**Comment by adriankumpf** [comment]
The update check is performed 5 minutes after startup and every 72 hours:

https://github.com/adriankumpf/teslamate/blob/b670d2a4729f0dd236ba6e9c1e02e2c52c994243/lib/teslamate/updater.ex#L26-L27

If you do not see a notification after restarting/three days, as usual, check the logs to see if the request failed :)
