### ISSUE TITLE
advanced installation apache2 docker image?

### ISSUE THREAD

**Issue by DariBer** [adriankumpf/teslamate#567]
in the advanced installation version, is the appache2 in one of the docker images or do I need to install it separat in my OS, like Ubuntu?

**Comment by DrMichael** [comment]
In the docs it assumes a separate installation. It would be interesting though to have it also in a docker container. Any takers?

**Comment by adriankumpf** [comment]
We should a note to the docs to make that more clear.

**Comment by DrMichael** [comment]
PR done...

**Comment by DariBer** [comment]
great! 

last question, do you know what module should be used in Apache, is it modproxyhttp?

thanx

**Comment by DrMichael** [comment]
It is mod_proxy, mod_rewrite, mod_ssl. Can you try, whether that is sufficient?

**Comment by DrMichael** [comment]
Plus mod_proxy_http

**Comment by DariBer** [comment]
my knowledge in apache is limited, but in the file Include /etc/letsencrypt/options-ssl-apache.conf
it refers to a file "Include /etc/letsencrypt/options-ssl-apache.conf" I'm not using Let's encrypt, I'm generating my own cert from my own CA Root server. What does that file include, can I use it even if I'm not using Let's Encrypt cert?

**Comment by DrMichael** [comment]
> my knowledge in apache is limited, but in the file Include /etc/letsencrypt/options-ssl-apache.conf
> it refers to a file "Include /etc/letsencrypt/options-ssl-apache.conf"

I think you wanted to say something different... :-)

> I'm not using Let's encrypt, I'm generating my own cert from my own CA Root server. What does that file include, can I use it even if I'm not using Let's Encrypt cert?

Probably. You need to set the path to your certs in teslamate.conf for SSLCertificateFile and SSLCertificateKeyFile (and remove the Include).

**Comment by DariBer** [comment]
Sorry.. meant.. in the apache config file /etc/apache2/sites-available/teslamate.conf it refers to file "Include /etc/letsencrypt/options-ssl-apache.conf"

I'm not using Let's Encrypt..
in the "/etc/apache2/sites-available/teslamate.conf " it say:
SSLCertificateFile /etc/letsencrypt/live/teslamate.${MYDOMAIN}/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/teslamate.${MYDOMAIN}/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf

I have configured so that my cert file is in right folder, but not sure what the Include /etc/letsencrypt/options-ssl-apache.conf does, maybe that file is generic and I can use the same ssl-conf file even if I'm not using Let's....

**Comment by DrMichael** [comment]
You can put your files wherever you want as long as you give that path in teslamate.conf.

Regarding the include: remove it and check, whether it works.

**Comment by DariBer** [comment]
got it to work now, but I'm not sure if it's only my apache configuration or if the teslamate.conf example is wrong, but I couldn't get the rewrite from http to https to work, if I didn't add the line "   RewriteEngine on" to the 80 to 443 rewrite

this works for me.

<VirtualHost *:80>
    ProxyPreserveHost On
    ServerName teslamate.${MYDOMAIN}
    CustomLog /var/log/apache2/${LOG} combined
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =teslamate.${MYDOMAIN}
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

thanx for your help :-)

**Comment by DrMichael** [comment]
Hmmm, don't know, why it was missing. I added it to the doc.
