### ISSUE TITLE
SSL Certificates Not Generating

### ISSUE THREAD

**Issue by lapean111** [adriankumpf/teslamate#572]
Recently got my setup moved over to an SSL/Advanced setup.  Only issue I am having is that it won't generate the certs.

I get this error:
proxy_1      | time="2020-04-08T19:55:14Z" level=error msg="Unable to obtain ACME certificate for domains \"teslamate.klepean.com\": unable to generate a certificate for the domains [teslamate.klepean.com]: acme: Error -> One or more domains had a problem:\n[teslamate.klepean.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://teslamate.klepean.com/.well-known/acme-challenge/d4YFXm7S35pO6u74ug993nqTFzks_hNPvWs1M_tD9mc: Error getting validation data, url: \n" providerName=tmhttpchallenge.acme routerName=teslamate@docker rule="Host(`teslamate.klepean.com`)"

It is identical for both of my domains.

Any ideas?

**Comment by DrMichael** [comment]
Do you have something else running on port 80? Can you fetch  the mentioned URL in a browser?

**Comment by lapean111** [comment]
Nothing else on port 80.  No, the url doesn't seem to exist.

**Comment by lapean111** [comment]
I am using the 1.19 dev version if that matters.  I even made a clean instance with 1.19 dev, and I am getting the same errors.

**Comment by lapean111** [comment]
Just tried a clean instance with the official 1.18.2 release, same error...

**Comment by lapean111** [comment]
Is there a way to just manually generate the cert, and place it somewhere without having to rebuild my entire setup?

**Comment by tacotran** [comment]
> Nothing else on port 80. No, the url doesn't seem to exist.

You have to set up the DNS entry with your hosting provider or whatever DNS service you're using.

**Comment by adriankumpf** [comment]
For what it's worth, there are a few threads on the let's encrypt community forum that cover this error, for example:

https://community.letsencrypt.org/t/certificate-not-being-created-due-to-error-getting-validation-data/70863

**Comment by lapean111** [comment]
Thanks for the response.  I have dns records for my site, and the site itself works from the internet.  I have firewall setup to forward both 80 and 443.  The site works fine from the internet with the exception of saying the connection isn't secure.

**Comment by lapean111** [comment]
I have created a certificate manually, and I have it as a PEM file.  This one file contains my cert, as well as the full chain.  How can I use the advanced Docker configuration, but use this pem file instead of having it attempt to auto retrieve?

**Comment by lapean111** [comment]
Wow, got this figured out.  My NAS was redirecting the requests via UPNP.  Disabled that, and all is well.
