### ISSUE TITLE
SQL Database Efficency Improvements

### ISSUE THREAD

**Issue by Dulanic** [adriankumpf/teslamate#573]
As a DBA, I wanted to make the following recommendation to changes in the positions tables. This cut my table size in half. I wanted to make it more efficient with the extra rows being added now that we have additional polling records. Many of these fields were just unnecessarily large. Charges couild prob use some charges too, but this was by far the largest table. I am assuming it would need to be done in multiple places including possibly some of your code, so I copied the table and tried it and saw 50% space savings.

```ALTER TABLE positions
ALTER COLUMN id TYPE INT,
ALTER COLUMN latitude TYPE numeric(10,6),
ALTER COLUMN longitude TYPE numeric(10,6),
ALTER COLUMN power TYPE smallint,
ALTER COLUMN battery_level TYPE smallint,
ALTER COLUMN outside_temp TYPE numeric(5,1),
ALTER COLUMN elevation TYPE smallint,
ALTER COLUMN driver_temp_setting TYPE numeric(5,1),
ALTER COLUMN passenger_temp_setting TYPE numeric(5,1),
ALTER COLUMN car_id TYPE smallint,
ALTER COLUMN drive_id TYPE INT,
ALTER COLUMN inside_temp TYPE NUMERIC(5,1),
ALTER COLUMN est_battery_range_km TYPE smallint,
ALTER COLUMN rated_battery_range_km TYPE smallint,
ALTER COLUMN usable_battery_level TYPE smallint

```

For every column switched from BIGINT to INT you will save 4MB per million rows. If you do that for 5 columns, youll save 20MB per million rows. When I saw BIGINT for car_id I had to laugh a bit, as I don't think even if you counted every tesla in existence you could even use INT up.

**Comment by adriankumpf** [comment]
Nice! Thanks for the tips. In the end, I optimized all other tables as well. These are the changes:

https://github.com/adriankumpf/teslamate/blob/45d94d52b381f9183bdc6de1995f2c94c481b794/priv/repo/migrations/20200410112005_database_efficiency_improvements.exs#L5-L109

**Comment by bahree** [comment]
I wonder if we can also look into the indexes; @Dulanic  not sure if you had a opportunity to see that? I don't know if I am over thinking this. :)

**Comment by Dulanic** [comment]
There is plenty of indexing,it looked good to me.
