### ISSUE TITLE
Minor minor "bug": teslamate.readthedocs.io in settings

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#575]
**Describe the bug**

Extremely minor "bug": the about section in settings in 1.19.0-dev still mentions teslamate.readthedocs.io.

Suggestion: I would increase font size on Spenden/Donations. :-)

**Comment by tobiasehlert** [comment]
@DrMichael, I can't locate any string pointing to readthedocs in the code anymore.

Are you sure you are running the latest version of code?
Do a printscreen on the page where you find it :)

**Comment by DrMichael** [comment]
Yeah, I also could not locate it... (no too familiar with the application though). Hope this helps:
![2020-04-10 11_20_07-TeslaMate](https://user-images.githubusercontent.com/8087682/78980260-d79ed480-7b1d-11ea-8f9c-07c5dec161d7.png)

**Comment by tobiasehlert** [comment]
@DrMichael 
In [lib/teslamate_web/templates/settings/index.html.leex](https://github.com/adriankumpf/teslamate/blob/master/lib/teslamate_web/templates/settings/index.html.leex#L272) on line 272, it says the correct URL
Have you tried to pull the latest content and restart your application and see, if it gets fixed :)

**Comment by DrMichael** [comment]
Nay, pulled, restarted, same. I am pulling image: teslamate/teslamate:1.19.0-dev though. Perhaps it is only in the dev version and already fixed in master.
