### ISSUE TITLE
Websocket Error / Spinner

### ISSUE THREAD

**Issue by grizzlyjere** [adriankumpf/teslamate#60]
I've installed telsamate using the latest docker release.  The UI runs and displays data from the car, but it displays a spinner in the center.  

Looking at the debug window reports over 100 errors of the same type:
`WebSocket connection to 'ws://IP_REDACTED:4000/live/websocket?vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403`

**Comment by cgudea** [comment]
I didn't have the same error in my logs but I had to allow websocket in my proxy config to get the spinner to go away. If you're using nginx, here is a sample way: https://www.nginx.com/blog/websocket-nginx/

something like

```
    upstream websocket {
        server 192.168.100.10:8010;
    }
```

**Comment by skaforey** [comment]
I'm running this on a Synology and am also receiving the spinning circle

**Comment by mvaal** [comment]
I also am getting the spinning circle.

**Comment by perkz** [comment]
If you're using docker and accessing it on another machine, it looks like you need to add a VIRTUAL_HOST environment variable to the teslamate container when you create it otherwise it defaults to localhost and you get those Phoenix.Socket errors.

**Comment by skaforey** [comment]
Sorry for being a n00b, but since I have already configured teslamate, is there anyway to do this now that it's up and running?

**Comment by wavern** [comment]
Just to add for clarity. If you're using docker-compose for this..

Look for this in your docker-compose.yml file:
      - MQTT_HOST=mosquitto
Then add this after:
      - VIRTUAL_HOST=ip_address_of_your_docker_host

**Comment by bnj04** [comment]
an additional hint in case it happens for other : in my particuliar case, this issue was caused by a misconfigured MTU in the IPSEC tunnel used to reach teslamate. 

and thank you for the time you took to create teslamate !

**Comment by rglastra** [comment]
Landed on this from a Google search. I had set only a proxy_pass in nginx, but encountered the websocket error as described above.

Adding the following to my site .conf resolved it:
```
    proxy_pass http://localhost:4000; # Or your equivalent
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
```

**Comment by IanWardell** [comment]
For anyone else looking, I did something similar to @rglastra to fix this, I however also added a user/pass login.
* Note you need to make sure the network that teslamate runs on is added to the nginx container
* I changed my teslamate port in the dockerfile to to "127.0.0.1:4001:4000" , so nginx listens to 4000 and proxies that out to my network with a user/pass auth., but teslamate is only actually available on the localhost port 4001 without auth.

```
server {
listen 4000;
server_name 127.0.0.1;

location / {
  auth_basic           "Pass";
  auth_basic_user_file /etc/nginx/.htpasswd;
  proxy_pass http://teslamate-deploy-teslamate-1:4000;  # <remove comment if pasting> this is the name of the container

```

}

**Comment by ijord** [comment]
For those of us doing this on Synology, the solution is easy:
In your reverse proxy rule for Teslamate's web app. Go to "custom headers" and then click create and then "Websocket"
Save, and it should all be working.

https://mlohr.com/websockets-for-synology-dsm/
