### ISSUE TITLE
"Page not found" https://docs.teslamate.org/maintenance/backup_restore.md

### ISSUE THREAD

**Issue by oittaa** [adriankumpf/teslamate#600]
1. Open https://docs.teslamate.org/docs/upgrading
2. Click "Create a `backup` before updating."
3. Browser tries to open `https://docs.teslamate.org/maintenance/backup_restore.md`

`Page not found`

The link should point to https://docs.teslamate.org/docs/maintenance/backup_restore

**Comment by DrMichael** [comment]
Created PR in https://github.com/adriankumpf/teslamate/pull/602
