### ISSUE TITLE
Question: any easy way to use google assistant with Teslamate to 

### ISSUE THREAD

**Issue by Rathna-K** [adriankumpf/teslamate#601]
Any easy way to use google assistant with teslamate to start the heater/ air conditioner ? I used to use openhab but they dont have the sophisticated polling that you have and often drain the battery. Thanks!

**Comment by adriankumpf** [comment]
No, TeslaMate only logs data and does not send commands to the car.

**Comment by Rathna-K** [comment]
No plans to implement it ?

**Comment by Rathna-K** [comment]
And out of curiosity, i am guessing you also have a Tesla so do you use any other apps to do it or don't find the need? :) awesome app this btw.

**Comment by adriankumpf** [comment]
Nope, no plans to implement it as there are already other, more specialized apps for this purpose.

> And out of curiosity, i am guessing you also have a Tesla so do you use any other apps to do it or don't find the need? :) awesome app this btw.

Not really, I only use Home Assistant for automation (for example sending a push notification if the car is not locked; opening/closing the gate). That's basically it :)

**Comment by kongomongo** [comment]
> Not really, I only use Home Assistant for automation (for example sending a push notification if the car is not locked; opening/closing the gate). That's basically it :)

you mean sending a notification when you walk away from the car and it doesnt lock due to a not perfectly closed door?

**Comment by LelandSindt** [comment]
I was considering opening a feature request that would have Teslamate listening to an MQTT queue for commands to send the car ie: /teslamate/cars/1/command/locks [unlock|lock]

but from this thread it does not appear that you are immediately interested.

> other, more specialized apps for this purpose.
can you share the name(s) of projects/apps that you are aware of?

**Comment by ngardiner** [comment]
> can you share the name(s) of projects/apps that you are aware of?

HomeAssistant (quite popular with TeslaMate users)

**Comment by Rathna-K** [comment]
Home Assistant requires paid integrations for google assistant but OpenHab is supposed to provide easy integration. It used to work but recently it is not working for me so I opened a thread in their support forum. I used to have the car turn on and heat up etc. using OpenHab.

**Comment by ngardiner** [comment]
HomeAssistant doesn't require paid integration for Google Assistant. I use it without Nabu Casa. The paid system is just to make it plug and play for those not able to do it via the more advanced approach. Frankly this is out of scope of this discussion but I do want to correct that misconception.

**Comment by adriankumpf** [comment]
> I was considering opening a feature request that would have Teslamate listening to an MQTT queue for commands to send the car ie: /teslamate/cars/1/command/locks [unlock|lock]

Commands can sometimes fail, so in my opinion it would be better to trigger commands via classic HTTP requests than an async queue. But as I said above, I think applications like HomeAssistant ([RESTful Command](https://www.home-assistant.io/integrations/rest_command/)), Tasker Plugins or custom scripts are better for this purpose. I know of too many cases where teslamate instances have been made public without any protection whatsoever … Just imagine what would happen if API commands could be triggered just like that.

**Comment by LelandSindt** [comment]
I have done some automation via Google Home, IFTTT and an API "gateway" (https://github.com/LelandSindt/iftttGateway) and found that it's best if the gateway returns before completing the call(s) to Tesla, especially when the car is asleep. 

An MQTT queue feels the natural choice for potentially long running operations. Especially if the same process can watch the queue from Teslamate to see if the state change is complete. 

I have added an MQTT -> TeslaAPI Gateway to my list of "maybe" projects. May have to make it refuse to connect non TLS and require a user/pass for the MQTT queue to help save people from poor choices.

**Comment by JakobLichterfeld** [comment]
> > other, more specialized apps for this purpose.
> 
> can you share the name(s) of projects/apps that you are aware of?

There was some discussion in another feature request regarding climate control (#156).To summarize the solution out there do store your credentials or the token and you do not know how. Therefore I open-sourced my approach for full http api control in tasker and locally stored access token, see [Tesla_API_in_Tasker on GitHub](https://github.com/JakobLichterfeld/Tesla_API_in_Tasker)
