### ISSUE TITLE
Incorrect number of phases 

### ISSUE THREAD

**Issue by tomS3210** [adriankumpf/teslamate#605]
Hello, 

When recharging in three-phase Teslamat graph indicates "Phases: 2" it should be Phases: 3"
Here is a screenshoot in attachement.

No problem with 1 phase.

Thanks again for your work !

<img width="624" alt="2-3 phases charging" src="https://user-images.githubusercontent.com/949584/79640849-3e626480-8194-11ea-9ca7-cc192553dfd1.png">

**Comment by adriankumpf** [comment]
Duplicate of #414
