### ISSUE TITLE
Trip pie chart - adjust charge color; include other states?

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#608]
**Describe the bug**

Not necessary a "bug", nor a feature. More aesthetics. The color of "charging" on the pie chart is green, which reflects "sleeping" in the states dashboard. 

_This might be a feature :)_ Could we also add a pie chart to the "States" dashboard instead of the boxed legend under the continuous bar? 

**To Reproduce**

1. Go to Trip dashboard
2. View enough data to see drives and a charging session

**Expected behavior**

Since it is color coded, would expect similar colors across the solution

**Relevant entries from the logs**

N/A

**Screenshots**

![Screen Shot 2020-04-19 at 12 58 07 PM](https://user-images.githubusercontent.com/54645561/79695654-afaa2200-823d-11ea-8eb4-2b00189a3d8b.png)

**Data**

N/A

**Operating environment**

- TeslaMate Version: [v1.19]
- Type of installation: [Dockerl]
- OS: [Raspberry Pi]

**Comment by DrMichael** [comment]
> **Describe the bug**
> 
> Not necessary a "bug", nor a feature. More aesthetics. The color of "charging" on the pie chart is green, which reflects "sleeping" in the states dashboard.

Potentially you have just `driving`, `charging (AC)` and `charging (DC)`.  In my chart, the color for driving is the same as in the states dashboard. The two charging parts could be in different yellow colours:
![2020-04-20 12_14_46-Window](https://user-images.githubusercontent.com/8087682/79740956-c36a8c80-8300-11ea-88af-ff19bf604494.png)

**Comment by kongomongo** [comment]
Clicking on the legend color pops up the dialog to change colors.

![image](https://user-images.githubusercontent.com/5646390/79795257-f0945a80-8353-11ea-9775-b445c7ebcbab.png)

![image](https://user-images.githubusercontent.com/5646390/79795247-ee320080-8353-11ea-9582-dd0c0386b739.png)

**Comment by DrMichael** [comment]
Right, but that will be overwritten with next update...

**Comment by kongomongo** [comment]
indeed, unless you save the dashboard under "Trip - my uber version" name

**Comment by DrMichael** [comment]
Changed colors in https://github.com/adriankumpf/teslamate/pull/958

**Comment by adriankumpf** [comment]
Changed in https://github.com/adriankumpf/teslamate/pull/970
