### ISSUE TITLE
Efficiency Calculation Incorrect

### ISSUE THREAD

**Issue by Simple-Complexity** [adriankumpf/teslamate#61]
When using more power than rated for a particular vehicle the efficiency appears as over 100%. After investigating, the cause is likely that the fraction is inverse. For example, the current calculation looks like: 

`ideal_distance / distance`

in reality it should be:

`distance / ideal_distance`

This way, if distance traveled is less than the ideal rated distance we will see a lower percentage and vice-versa if the opposite is true.

**Comment by adriankumpf** [comment]
Isn't that a bit of a definition thing? :) When I added that feature it somehow felt natural to do it that way. But I see your point. Do yo happen to know how TeslaFi or other tools does it?

**Comment by skaforey** [comment]
Just my 0.02.  I totally agree that it's a definition thing.  It's not really a big deal either.  However, I do agree with the OP that you would want efficiency > 100% when you drive more efficient.
