### ISSUE TITLE
1.19.0 API Error an Timeout.

### ISSUE THREAD

**Issue by ctraber** [adriankumpf/teslamate#613]
Since updating to 1.19.0 I get API errors in the logs. Also saw the red healthcheck ! on the status page.

Here parts of my logs:

2:46:50.286 [info] GET /,
12:46:50.300 [info] Sent 200 in 13ms,
12:47:18.860 car_id=1 [info] Start / :online,
12:47:18.894 car_id=1 [info] Connecting ...,
12:47:49.903 [error] TeslaApi.Error / 502 – "<!DOCTYPE html>\n<html>\n<head>\n  <title>We're sorry, but something went wrong (500)</title>\n  <style type=\"text/css\">\n    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }\n    div.dialog {\n      width: 25em;\n      padding: 0 4em;\n      margin: 4em auto 0 auto;\n      border: 1px solid #ccc;\n      border-right-color: #999;\n      border-bottom-color: #999;\n    }\n    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }\n  </style>\n</head>\n\n<body>\n  \n  <div class=\"dialog\">\n    <h1>We're sorry, but something went wrong.</h1>\n  </div>\n</body>\n</html>\n",
12:47:49.903 car_id=1 [error] Error / :unknown,
12:49:49.073 [error] TeslaApi.Error / 502 – "<!DOCTYPE html>\n<html>\n<head>\n  <title>We're sorry, but something went wrong (500)</title>\n  <style type=\"text/css\">\n    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }\n    div.dialog {\n      width: 25em;\n      padding: 0 4em;\n      margin: 4em auto 0 auto;\n      border: 1px solid #ccc;\n      border-right-color: #999;\n      border-bottom-color: #999;\n    }\n    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }\n  </style>\n</head>\n\n<body>\n  \n  <div class=\"dialog\">\n    <h1>We're sorry, but something went wrong.</h1>\n  </div>\n</body>\n</html>\n",
12:49:49.073 car_id=1 [error] Error / :unknown,
12:49:56.070 [info] GET /,
12:49:56.087 [info] Sent 200 in 16ms,
12:50:25.356 [info] [alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}],
12:50:26.407 [info] GET /,
12:50:26.421 [info] Sent 200 in 13ms,
12:50:30.092 [info] GET /,
12:50:30.105 [info] Sent 200 in 12ms,
12:50:33.376 [info] GET /,
12:50:33.390 [info] Sent 200 in 12ms,
12:50:42.534 car_id=1 [info] Suspending logging,
12:51:36.063 [info] GET /,
12:51:36.076 [info] Sent 200 in 12ms,
12:51:45.535 [info] GET /settings,
12:51:45.549 [info] Sent 200 in 13ms,
12:56:03.401 [info] GET /,
12:56:03.416 [info] Sent 200 in 13ms,
12:56:10.803 [info] GET /,
12:56:10.818 [info] Sent 200 in 14ms,
12:56:16.856 car_id=1 [info] Resuming logging,
12:56:30.234 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil},
12:56:30.235 car_id=1 [error] Error / :timeout,
12:56:51.207 [error] TeslaApi.Error / 502 – "<!DOCTYPE html>\n<html>\n<head>\n  <title>We're sorry, but something went wrong (500)</title>\n  <style type=\"text/css\">\n    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }\n    div.dialog {\n      width: 25em;\n      padding: 0 4em;\n      margin: 4em auto 0 auto;\n      border: 1px solid #ccc;\n      border-right-color: #999;\n      border-bottom-color: #999;\n    }\n    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }\n  </style>\n</head>\n\n<body>\n  \n  <div class=\"dialog\">\n    <h1>We're sorry, but something went wrong.</h1>\n  </div>\n</body>\n</html>\n",
12:56:51.208 car_id=1 [error] Error / :unknown,
12:57:17.343 [info] GET /,
12:57:17.353 [info] Sent 200 in 10ms,
12:57:22.499 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil},
12:57:22.499 car_id=1 [error] Error / :timeout,
12:57:25.363 [info] [alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_1_api_error}],
12:57:53.760 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil},
12:57:53.760 car_id=1 [error] Error / :timeout,

**Comment by adriankumpf** [comment]
This has nothing to do with the update. It's a coincidence. The failed health check indicates that there is an issue with the Tesla servers.
