### ISSUE TITLE
Additional columns for the Grafana Dashboard "Updates"

### ISSUE THREAD

**Issue by theskyisthelimit** [adriankumpf/teslamate#617]
Hi Adrian,

I'm a big fan of Teslamate. There is one small thing I would like to see but I have no skills in databases nor Grafana to do it myself and send a pull request.

I would love to see more columns in the Grafana Dashboard "Updates"

e.g.
- Number of days between the installation dates
- Calculate average days between the installation dates (maybe there is a pattern?!)
- Installation time in minutes for each update

What do you thing?

**Comment by kongomongo** [comment]
as a quick hack (first two):

![image](https://user-images.githubusercontent.com/5646390/79795986-13733e80-8355-11ea-9bdc-fc70b4114396.png)

`select start_date, end_date, end_date-start_date as update_duration, start_date-lag(start_date) over ( order by start_date) as time_between_last_update, version from updates where $__timeFilter(start_date) and car_id = $car_id;`

**Comment by DrMichael** [comment]
Looks good. I suppose, we don't need seconds and milliseconds (or what it is) in the columns. I cannot figure out, how to change that though...

**Comment by theskyisthelimit** [comment]
That was very quick. Thank you!
Maybe we could also use the "Gauge" visualization if the average time between updates is approaching or something like that?

**Comment by Dulanic** [comment]
I suck sometimes at github, but I added a PR for this.

**Comment by theskyisthelimit** [comment]
Thanks for the implementation. Any comments regarding these points?

- Calculate average days between the installation dates
- Any visualizations that make sense for these scenarios

**Comment by theskyisthelimit** [comment]
Ah yes. Sorry, now I see the problem.

Couldn't we add a Grafana Visualization Panel and show the number there? In this panel we could also show how many days have passed since the car got updated to a new firmware update.

With enough data we could see a visual pattern and could anticipate when a new firmware update is likely to hit our own car. I think this might be very interesting to see. What do you think?

**Comment by Dulanic** [comment]
I'm going to be honest, there is no rhyme or reason to tesla's updates sometimes.I don't see a value add from this information, and it will do nothing but stress people out if they're 2 days past the average :) If you want to edit your dashboard go for it, but I don't see a value to it myself. 

Maybe I'm wrong and others would want it too, but I'm going to air on the side of... probably not.
