### ISSUE TITLE
Dashboard translation

### ISSUE THREAD

**Issue by dongbum** [adriankumpf/teslamate#619]
Many Tesla owners use teslamate in Korea.
Need Teslamate dashboard translation.
I can help translate to Korean.

A better way is a translation system that supports multiple languages.

**Comment by Jade-sje** [comment]
I want it too.
I want the Korean version.
I really wish.

**Comment by DrMichael** [comment]
Does anybody know, whether Grafana allows localisation at all? I cannot find anything.

**Comment by Jade-sje** [comment]
> 
> 
> I want it too.
> 
> I want the Korean version.
> 
> I really wish.


Wow.  There is already ko text in the source.  I'll have to update and see.  Thank you.

**Comment by Jade-sje** [comment]
find. *.po files.

**Comment by Jade-sje** [comment]
> Does anybody know, whether Grafana allows localisation at all? I cannot find anything.
> 
> 

Find *.po files.

**Comment by adriankumpf** [comment]
@dongbum, I saw your comment in the Grafana feature request thread (grafana/grafana/issues/448) but as long as Grafana does not provide such a feature, we cannot implement it.

As soon as this feature is available, I will open this issue again.
