### ISSUE TITLE
Failing Websocket Connection

### ISSUE THREAD

**Issue by carharv** [adriankumpf/teslamate#621]
TeslaMate.domain.com does not properly load. The Chrome console gives the following error:
`app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2 WebSocket connection to 'wss://teslamate.MYDOMAIN.com/live/websocket?_csrf_token=EwM3M1pHIhF2Ci8AZiQQPGB_DzcDOwUAdjaG1sXAB3b49qC_-OAE1If0&baseUrl=https%3A%2F%2Fteslamate.MYDOMAIN.com&referrer=https%3A%2F%2Fteslamate.MYDOMAIN.com%2F&tz=America%2FNew_York&vsn=2.0.0' failed: Invalid frame header
value @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
e @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
value @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
(anonymous) @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
o @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
(anonymous) @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
o @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
(anonymous) @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
(anonymous) @ app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d:2
`

I have an existing OpenLiteSpeed web server on my network and proxy the connections to TeslaMate and Grafana through it. OpenLiteSpeed was properly proxying all of the information, including the WebSocket, until I updated to v1.19 from ~v1.15. 

I am able to click the home button, settings button, and see the state of the car, but I am not able to interact with any options and the map never loads. 

Docker logs do not display any information regarding this issue, and there is nothing obvious to me in the OpenLiteSpeed logs either. 

I would think that this is an OpenLiteSpeed issue, but everything was working properly up until I updated TeslaMate. Thanks in advance!

- TeslaMate Version: [e.g. v1.19.0]
- Type of installation: Docker w/ Apache2
- OS: Ubuntu

**Comment by tobiasehlert** [comment]
Hi @carharv,

Have you checked, that the websocket settings in your Apache2 are set correct?
You can compare your configuration with the one on the docs page:
https://docs.teslamate.org/docs/guides/apache#teslamateconf

Or even better, please share the apache2 config so we can see, what you have configured.

Do you see some logs in the Apache2 server when the client tries to establish a connection to the TeslaMate interface?

Regards,
Tobias

**Comment by carharv** [comment]
`Define MYDOMAIN carsonharvey.tech
Define LOG access.teslamate.log

<VirtualHost *:80>
    ProxyPreserveHost On
    ServerName teslamate.${MYDOMAIN}
    CustomLog /var/log/apache2/${LOG} combined
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =teslamate.${MYDOMAIN}
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:80>
    ServerName grafana.${MYDOMAIN}
    CustomLog /var/log/apache2/${LOG} combined
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =grafana.${MYDOMAIN}
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>
    <VirtualHost *:443>
        ProxyPreserveHost On
        ServerName teslamate.${MYDOMAIN}
        ProxyPass /live/websocket ws://127.0.0.1:4000/live/websocket
        ProxyPassReverse /live/websocket ws://127.0.0.1:4000/live/websocket
        ProxyPass / http://127.0.0.1:4000/
        ProxyPassReverse / http://127.0.0.1:4000/
        CustomLog /var/log/apache2/${LOG} combined
        <Proxy *>
            Authtype Basic
            Authname "Password Required"
            AuthUserFile /etc/apache2/.htpasswd
            Require valid-user
        </Proxy>
        SSLCertificateFile /etc/letsencrypt/live/teslamate.${MYDOMAIN}/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/teslamate.${MYDOMAIN}/privatekey.key
    </VirtualHost>
</IfModule>

<IfModule mod_ssl.c>
    <VirtualHost *:443>
        ServerName grafana.${MYDOMAIN}
        ProxyPass / http://127.0.0.1:3000/
        ProxyPassReverse / http://127.0.0.1:3000/
        CustomLog /var/log/apache2/${LOG} combined
        SSLCertificateFile /etc/letsencrypt/live/teslamate.${MYDOMAIN}/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/teslamate.${MYDOMAIN}/privatekey.key
    </VirtualHost>
</IfModule>
`
My Apache2 config is default other than the SSL certificates I have from cloudflare. 

I just logged in to TeslaMate and this is what access.teslamate.log shows. 192.168.1.201 is my OpenLiteSpeed web server. 

`192.168.1.201 - - [30/Apr/2020:16:26:30 +0000] "GET / HTTP/1.1" 401 2654 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:26:41 +0000] "GET / HTTP/1.1" 200 7424 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:26:41 +0000] "GET /js/app-8cd72d4a785dfa890099b88d5d613f61.js?vsn=d HTTP/1.1" 200 68836 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:26:41 +0000] "GET /css/app-835222d00e0a4442fbb41c7ad8c7d847.css?vsn=d HTTP/1.1" 200 78883 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:26:41 +0000] "GET /images/logo-7419f8de4d14f8ee5376b367a9165ba0.svg?vsn=d HTTP/1.1" 200 1593 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:26:41 +0000] "GET /fonts/materialdesignicons-webfont.3e6c43d-a323c28ecd42189e70efca274f5b7089.woff2?vsn=d HTTP/1.1" 200 284117 "https://teslamate.MYDOMAIN.COM/css/app-835222d00e0a4442fbb41c7ad8c7d847.css?vsn=d" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:26:41 +0000] "GET /live/websocket?_csrf_token=N2lnLRNvcwYbNAwpCSIqcTICORwdJS4vmY5aw-Dhac9MoRu4_orRVWDv&baseUrl=https%3A%2F%2Fteslamate.MYDOMAIN.COM&referrer=&tz=America%2FNew_York&vsn=2.0.0 HTTP/1.1" 200 280 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:26:42 +0000] "GET /site.webmanifest?v=5AB53N3ALo HTTP/1.1" 200 919 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:26:42 +0000] "GET /favicon.ico?v=5AB53N3ALo HTTP/1.1" 200 15466 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:27:12 +0000] "GET / HTTP/1.1" 200 5671 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:27:13 +0000] "GET /site.webmanifest?v=5AB53N3ALo HTTP/1.1" 304 2109 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:27:43 +0000] "GET / HTTP/1.1" 200 5674 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:27:12 +0000] "GET /live/websocket?_csrf_token=AFUjFA0TWg8AMAUCKR8tMD86J3waQzoAZeqXiQmazg0fOoruRWl2Q1PY&baseUrl=https%3A%2F%2Fteslamate.MYDOMAIN.COM&referrer=https%3A%2F%2Fteslamate.MYDOMAIN.COM%2F&tz=America%2FNew_York&vsn=2.0.0 HTTP/1.1" 200 413 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:27:44 +0000] "GET /site.webmanifest?v=5AB53N3ALo HTTP/1.1" 304 355 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:28:14 +0000] "GET / HTTP/1.1" 200 5667 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:27:43 +0000] "GET /live/websocket?_csrf_token=KWhmOBYKWCwbYVcCIQMAAw8fKB8mChgusX4trHoBa6bfGs_FbrcQmxrw&baseUrl=https%3A%2F%2Fteslamate.MYDOMAIN.COM&referrer=https%3A%2F%2Fteslamate.MYDOMAIN.COM%2F&tz=America%2FNew_York&vsn=2.0.0 HTTP/1.1" 200 280 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:28:15 +0000] "GET /site.webmanifest?v=5AB53N3ALo HTTP/1.1" 304 355 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:28:45 +0000] "GET / HTTP/1.1" 200 5668 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:28:45 +0000] "GET /live/websocket?_csrf_token=I3oofTQTXRgqBFc7IyUNCBkeGmMyFCJgyJz1PQjvPSb_EURMtsQ-yfH9&baseUrl=https%3A%2F%2Fteslamate.MYDOMAIN.COM&referrer=https%3A%2F%2Fteslamate.MYDOMAIN.COM%2F&tz=America%2FNew_York&vsn=2.0.0 HTTP/1.1" 200 280 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:28:46 +0000] "GET /site.webmanifest?v=5AB53N3ALo HTTP/1.1" 304 355 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:28:14 +0000] "GET /live/websocket?_csrf_token=FVsxGztyXyQ8NlYePDQ3GjcDJAMhOxBtOkcW_0hJFaczZDh_ZnoMjIz4&baseUrl=https%3A%2F%2Fteslamate.MYDOMAIN.COM&referrer=https%3A%2F%2Fteslamate.MYDOMAIN.COM%2F&tz=America%2FNew_York&vsn=2.0.0 HTTP/1.1" 200 280 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:29:28 +0000] "GET / HTTP/1.1" 200 5673 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
192.168.1.201 - teslamate [30/Apr/2020:16:29:29 +0000] "GET /site.webmanifest?v=5AB53N3ALo HTTP/1.1" 304 355 "https://teslamate.MYDOMAIN.COM/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
`
There are no Apache2 error logs with relevant information. 

My OpenLiteSpeed server proxies normal traffic to TeslaMate at https://192.168.1.21:443. OpenLiteSpeed is also configured to proxy all websocket connections to TeslaMate at 192.168.1.21:443. I have also tried port 4000 for the websocket connections.

**Comment by tobiasehlert** [comment]
Hi @carharv,

Are you trying to run TeslaMate with the mydomain.com domain? Try to set it to a domain that you have and restart your installation.

Could be that there is some check in the wss implementation, that verifies the domain (a guess from my side).

Regards,
Tobias

**Comment by carharv** [comment]
MYDOMAIN.com was a place holder I put in for the sake of not posting my actual domain. For what it’s worth, I also setup a simple docker install on my machine running OpenLiteSpeed and that had no affect on this issue either.
