### ISSUE TITLE
Streaming API - Doesn't start logging instantly

### ISSUE THREAD

**Issue by spacecosmos** [adriankumpf/teslamate#623]
**Describe the bug**

My car still seems to sleep and not start the logging process. I have a _Signature Model X P90DL_ (MCU1 and AP1).

**Expected behavior**

I hoped that the logging would start instantly when using the Streaming API feature. It logs as usual when manually resuming.

Maybe someone could give a more precise information on how the Streaming API is supposed to work? A more detailed description of what it is and the functionality of it in general? 

**Operating environment**

- TeslaMate Version: v1.19.1
- Type of installation: Docker
- OS: Ubuntu

**Comment by siebevanineveld** [comment]
I have the same experience with the latest update (v1.19.1). Logging starts after a couple of minutes (700m from start point including a short wait for a traffic light).

**Comment by virtualm2000** [comment]
Streaming API mostly helps with sleep. 
Check your Teslamate logs, probably you have some timeouts. Usually after the car wakes up, it takes a bit to register the new online state with Tesla servers and the added polling delay from teslamate could create a delay that adds to a gap in logging.

**Comment by siebevanineveld** [comment]
You're right.

I found these timeouts in the log files:
`07:45:27.412 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
07:45:27.412 car_id=1 [error] Error / :timeout
07:46:07.777 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
07:46:07.777 car_id=1 [error] Error / :timeout
07:46:38.582 car_id=1 [info] Start / :online
07:46:38.603 car_id=1 [info] Connecting ...
07:46:38.604 car_id=1 [info] Driving / Start`

**Comment by virtualm2000** [comment]
Yes, I have that type of timeouts as well. Even if the car is online preheating etc, the moment you move and switch from WiFi to LTE it might cause a connection problem with Tesla servers for few seconds. It usually doesn't happen when I'm on LTE away from WiFi.

**Comment by spacecosmos** [comment]
> Yes, I have that type of timeouts as well. Even if the car is online preheating etc, the moment you move and switch from WiFi to LTE it might cause a connection problem with Tesla servers for few seconds. It usually doesn't happen when I'm on LTE away from WiFi.

So maybe this could be the (primary) problem? Disable WiFi and let it work via LTE and enable WiFi if you know there is a new software version released?

**Comment by virtualm2000** [comment]
For me it’s not a common occurrence so I don’t mind. But you can try and check if you get better results.

**Comment by cleanev** [comment]
I am a new user and while going thru various issues, I found this one and checked teslamate logs to find below. My car is parked about 50 miles away from where teslamate is running so it is on LTE. Are these errors benign or is there more to this than it shows?

teslamate_1  | 19:28:21.695 [info] GET /
teslamate_1  | 19:28:21.849 [info] Sent 200 in 155ms
teslamate_1  | 19:31:26.492 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:31:26.492 car_id=1 [error] Error / :timeout
teslamate_1  | 19:31:56.988 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:31:56.988 car_id=1 [error] Error / :timeout
teslamate_1  | 19:32:27.528 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:32:27.528 car_id=1 [error] Error / :timeout
teslamate_1  | 19:32:57.473 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:32:57.473 car_id=1 [error] Error / :timeout
teslamate_1  | 19:40:04.138 [info] GET /settings
teslamate_1  | 19:40:04.199 [info] Sent 200 in 61ms
