### ISSUE TITLE
Grafana syntax errors

### ISSUE THREAD

**Issue by skaforey** [adriankumpf/teslamate#63]
I manually imported and here are the errors I get:
Under Charging:
`pq: syntax error at or near "ORDER"`

It seems the $charging_process_id is hardcoded to a value of 28?

Under Consumption:
`pq: syntax error at or near "AND"`

It seems the $trip_id is hardcoded to value 459? 

Not sure what the hardcoded values are supposed to represent, or if I imported wrong somehow

**Comment by wavern** [comment]
This is because the dashboards you're looking at are meant to be launched from a click in the trips dashboard. Click on a trip and you'll see.

**Comment by rucknapucknavitz** [comment]
I did the wizzy import and have the same errors.

**Comment by wavern** [comment]
I created a separate folder in Grafana called "Secondary Dashboards" and moved both Consumption and Charging into them since neither of those dashboards are standalone and are meant to only be accessed from other dashboards.

**Comment by adriankumpf** [comment]
It's built that way because some users have more than one car connected to their account. It wouldn't make sense to mix data of multiple cars in those dashboards.

**Comment by skaforey** [comment]
Ok this makes sense.  Thanks for the clarification!
