### ISSUE TITLE
Ability to set Cost by Minute

### ISSUE THREAD

**Issue by Dulanic** [adriankumpf/teslamate#630]
**Is your feature request related to a problem? Please describe.**

Nope

**Describe the solution you'd like**

So some areas/states don't/can't charge by the the KwH and instead need to charge by the minute. EX: In Texas in the US it costs 24 cents per minute to use a supercharger. Unfortunately, Tesla doesn't provide this data via the API.  We have the length of time a charge takes, so it would be easy enough to edit the query to add the cost if we were able to set the cost per minute.

**Describe alternatives you've considered**

Haven't really considered any, it's just a would be nice to have.

**Additional context**

Maybe we can add a option to a location for charging cost by KwH vs by time?

I'd like to see the ability to set a charger cost by the minute ability within geo-fence. While I can add it in the data, I am not good /w elixir to help with the rest :(

**Comment by roadrash2108** [comment]
Here in Austria/Europe it is common practice to only charge by time (EUR/minute), because this prevents people from blocking chargers after finishing the charge.

So I would not rate this as a "nice to have", but rather a "must-have" to be able to track the costs for charging...

**Comment by tabascoeye** [comment]
gets even more complicated because (at least in DE) it's no longer allowed to charge by the minute **for newly built chargers**. So it would be tricky to track all this

**Comment by roadrash2108** [comment]
But a newly built charger has a different location and so can get its own geo-fence - I don't see a problem here tbh...

Regarding the cost-estimation: there are chargers that have prices depending on the timing (e.g. during the day more than during the night)...
