### ISSUE TITLE
Blank column in Drives dashboard

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#636]
**Describe the bug**

There is a blank column in the Drives dashboard table

**To Reproduce**

1. Launch TeslaMate and go to Grafana or open Grafana directly
2. Open Drive Dashboard
3. See blank column in Drives dashboard
**Expected behavior**

Not sure _what_ to expect here. 
**Relevant entries from the logs**

N/A

**Screenshots**

![Screen Shot 2020-04-23 at 7 57 45 AM](https://user-images.githubusercontent.com/54645561/80102495-69540c00-8538-11ea-8bd2-fd2117d8732c.png)

**Data**

N/A
**Operating environment**

- TeslaMate Version: [v19.0]
- Type of installation: [Docker]
- OS: [Raspbian]

**Comment by tobiasehlert** [comment]
Hi @cwanja,

That column is the **has_reduced_range** one.
If you live in colder climate, you will have a snowflake appear there, telling that you had reduced range.

Here is an example of my drives view:
![image](https://user-images.githubusercontent.com/4417850/80143967-fa18ff00-85ad-11ea-9514-bab21b3f2ac4.png)

Regards,
Tobias

**Comment by cwanja** [comment]
Ah, yes! I recall now seeing that _once or twice_ in South Texas. Perfect. Thanks. Maybe @adriankumpf we can think of a header title for it?

**Comment by Dulanic** [comment]
I bet it was done to keep the column header small, I added ❄ as the header to keep it small. I never noticed this either!
