### ISSUE TITLE
null and incorrect values pushed to MQTT when Teslamate is [re]started and the car is asleep

### ISSUE THREAD

**Issue by LelandSindt** [adriankumpf/teslamate#639]
**Describe the bug**

If the car is asleep and teslamate is [re]started Null and incorrect values are pushed to the MQTT queue.

I first noticed this when upgrading from 1.19.0-dev to 1.19.0 and seeing teslamate/cars/1/plugged_in flip form true to false... 

**To Reproduce**

1. watch MTQTT Queue.
2. [re]start Teslamate
3.  observe Null and incorrect values... 

**Expected behavior**

I would would think that nulls and incorrect/unknown values would not be pushed. 

**Relevant entries from the logs**

```
mosquitto_sub -h 192.168.1.51 -t teslamate/cars/1/# -v 
teslamate/cars/1/battery_level 81
teslamate/cars/1/is_user_present false
teslamate/cars/1/ideal_battery_range_km 359.98
teslamate/cars/1/version 2020.12
teslamate/cars/1/heading 350
teslamate/cars/1/charger_power 0
teslamate/cars/1/odometer 29175.25
teslamate/cars/1/charge_limit_soc 81
teslamate/cars/1/model 3
teslamate/cars/1/latitude [redacted]
teslamate/cars/1/windows_open false
teslamate/cars/1/charge_port_door_open true
teslamate/cars/1/plugged_in true
teslamate/cars/1/time_to_full_charge 0.0
teslamate/cars/1/wheel_type Pinwheel18
teslamate/cars/1/charge_energy_added 6.81
teslamate/cars/1/scheduled_charging_start_time 2020-04-23T10:41:33Z
teslamate/cars/1/exterior_color MidnightSilver
teslamate/cars/1/is_preconditioning false
teslamate/cars/1/since 2020-04-23T11:00:45.741200Z
teslamate/cars/1/locked true
teslamate/cars/1/update_available false
teslamate/cars/1/display_name IN B3TA
teslamate/cars/1/charger_voltage 2
teslamate/cars/1/charger_phases 1
teslamate/cars/1/is_climate_on false
teslamate/cars/1/state asleep
teslamate/cars/1/sentry_mode false
teslamate/cars/1/usable_battery_level 81
teslamate/cars/1/longitude [redacted]
teslamate/cars/1/est_battery_range_km 326.17
teslamate/cars/1/healthy true
teslamate/cars/1/spoiler_type None
teslamate/cars/1/geofence Home
teslamate/cars/1/speed 0
teslamate/cars/1/trunk_open false
teslamate/cars/1/frunk_open false
teslamate/cars/1/elevation 303

### restart teslamate.... 

teslamate/cars/1/version 2020.12
teslamate/cars/1/charge_energy_added (null)
teslamate/cars/1/charger_phases (null)
teslamate/cars/1/scheduled_charging_start_time (null)
teslamate/cars/1/inside_temp 16.6
teslamate/cars/1/charger_actual_current (null)
teslamate/cars/1/spoiler_type None
teslamate/cars/1/est_battery_range_km 326.17
teslamate/cars/1/latitude [redacted]
teslamate/cars/1/shift_state (null)
teslamate/cars/1/geofence Home
teslamate/cars/1/usable_battery_level 81
teslamate/cars/1/odometer 29175.25
teslamate/cars/1/healthy true
teslamate/cars/1/time_to_full_charge (null)
teslamate/cars/1/charger_voltage (null)
teslamate/cars/1/outside_temp 16.5
teslamate/cars/1/rated_battery_range_km 359.98
teslamate/cars/1/since 2020-04-23T11:00:45.741200Z
teslamate/cars/1/plugged_in false
teslamate/cars/1/exterior_color MidnightSilver
teslamate/cars/1/charger_power (null)
teslamate/cars/1/longitude [redacted]
teslamate/cars/1/state asleep
teslamate/cars/1/model 3
teslamate/cars/1/battery_level 81
teslamate/cars/1/trim_badging (null)
teslamate/cars/1/wheel_type Pinwheel18
```

**Operating environment**

- TeslaMate Version: 1.19.1
- Type of installation: kubernetes
- OS: ubuntu

**Comment by adriankumpf** [comment]
Some values are always published, even if they are NULL because it is a valid value. For example, `scheduled_charging_start_time` can be null if no scheduled charging time is set. This applies to the following values:
https://github.com/adriankumpf/teslamate/blob/2d08545396e23a2c5c0ca2ce55cec7624bccd5ad/lib/teslamate/mqtt/pubsub/vehicle_subscriber.ex#L47-L49

I have changed this in 2d08545 so that these values are not published after a restart if they are unknown because the car is asleep/offline. Based on your example, this would result in the following topics:

```
teslamate/cars/1/version 2020.12
teslamate/cars/1/inside_temp 16.6
teslamate/cars/1/spoiler_type None
teslamate/cars/1/est_battery_range_km 326.17
teslamate/cars/1/latitude [redacted]
teslamate/cars/1/geofence Home
teslamate/cars/1/usable_battery_level 81
teslamate/cars/1/odometer 29175.25
teslamate/cars/1/healthy true
teslamate/cars/1/outside_temp 16.5
teslamate/cars/1/rated_battery_range_km 359.98
teslamate/cars/1/since 2020-04-23T11:00:45.741200Z
teslamate/cars/1/exterior_color MidnightSilver
teslamate/cars/1/longitude [redacted]
teslamate/cars/1/state asleep
teslamate/cars/1/model 3
teslamate/cars/1/battery_level 81
teslamate/cars/1/trim_badging (null)
teslamate/cars/1/wheel_type Pinwheel18
```

The only wrong value I could find was "plugged_in", which should not be published anymore too.

**Comment by LelandSindt** [comment]
For my needs this works, thank you. 

That said, I wonder about a scenario where Teslamate only publishes _changes_ to the Queue. This would allow the consumer to act on a received message rather than having to look for changes.

...Just thinking "out loud".

**Comment by adriankumpf** [comment]
But isn't that how it already works? Since v1.19 values are only published if they have changed. Only a restart causes all values to be "reinitialized". Is that what you mean?

**Comment by LelandSindt** [comment]
The thought was Teslamate would only ever publish changed values to the queue. In the strictest terms  `teslamate/cars/1/model 3` would only ever be pushed once, when Teslamate _first_ starts, communicates with the car, and publishes to the queue.

Continuing that thought, I start to wonder if model, color, trim_badging, and wheel_type all values that will never change are appropriate for a queue.

In a situation where only changed values are ever published, persistent storage baking the Queue becomes incredibly important. 

again, just thinking things through...
