### ISSUE TITLE
New install, data imported fine but no new data appearing.

### ISSUE THREAD

**Issue by Stevehans** [adriankumpf/teslamate#641]
**Describe the bug**

I've installed teslamate in docker on ubuntu, imported TeslaFi data, the car is awake and charging but I'm not seeing any new data?

The containers are running (ps aux|grep docker)

The logs show nothing since 20:36 last night

The car is currently charging, I've exported the charge table and attached a tail below, as you can see there is nothing there apart from the TeslaFi import.

Streaming API is enabled in the settings.

**Relevant entries from the logs**

teslamate_1  | 20:09:42.891 [info] Repairing charging process #3 ...
teslamate_1  | 20:09:44.526 [info] OK
teslamate_1  | 20:14:26.360 [info] GET /
teslamate_1  | 20:14:26.363 [info] Sent 302 in 2ms
teslamate_1  | 20:14:26.399 [info] GET /import
teslamate_1  | 20:14:26.402 [info] Sent 200 in 2ms
teslamate_1  | 20:36:19.548 [info] GET /
teslamate_1  | 20:36:19.551 [info] Sent 302 in 2ms
teslamate_1  | 20:36:19.644 [info] GET /import
teslamate_1  | 20:36:19.647 [info] Sent 200 in 2ms

**Data**

4158,2020-04-22 03:06:08,,70,22.31,10,1,10,2,233,,,,MCSingleWireCAN,348.95,,9.0,32,,,348.95,70
4168,2020-04-22 03:16:08,,71,22.72,10,1,10,2,236,,,,MCSingleWireCAN,351.67,,9.0,32,,,351.67,70
4178,2020-04-22 03:26:10,,71,23.14,10,1,10,2,235,,,,MCSingleWireCAN,354.41,,8.5,32,,,354.41,71
4188,2020-04-22 03:36:10,,72,23.35,10,1,10,2,234,,,,MCSingleWireCAN,355.78,,8.5,32,,,355.78,71

**Operating environment**

- TeslaMate Version: 1.19.1
- Type of installation: Docker
- OS: Ubuntu

**Comment by Stevehans** [comment]
Updated to 1.19.2 but with no change.

I'm not sure what more information would you like me to provide?

**Comment by adriankumpf** [comment]
* Could you provide the complete logs from the time the container is restarted?
* What is shown on the TeslaMate web interface? Does it show your car? Which status is displayed?

**Comment by Stevehans** [comment]
The car is shown, I'll respond to the other parts as soon as I get back home.

Regards
Steve



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by Stevehans** [comment]
Another restart tonight and it's sprung into action, no idea what was wrong previously!
