### ISSUE TITLE
Grafana detailed dashboards forced to new window

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#653]
**Describe the bug**

Not sure if this is forced from TeslaMate or a new Grafana update. Any of the dashboards that open a detail dashboard (Drives, Charges, etc.) are forced to open in a new tab (or window). However, on my iPhone, I run TeslaMate as a "home screen" application. When trying to view the detailed dashboard, it cannot open.

**To Reproduce**

1. Open TeslaMate on an iPhone
2. Click the "Share" icon and add to Home Screen
3. Launch TeslaMate via the "app" that was created on the home screen
4. Navigate to the Drives or Charge dashboard
5. Try to click into a specific drive or charge and nothing should happen.

**Expected behavior**

Would expect the Grafana dashboard for the specific drive or charge to display

**Relevant entries from the logs**

N/A

**Screenshots**

Can post a screen recording if necessary. But no specific screenshot. 

**Data**

N/A

**Operating environment**

- TeslaMate Version: [1.19.2]
- Type of installation: [Docker]
- OS: [Raspbian]

**Comment by roadrash2108** [comment]
This seems to work now (at least for me with iOS 14) - @cwanja can you please recheck if this is still an issue?

**Comment by cwanja** [comment]
Yep! Can confirm it is back to working @roadrash2108 and @adriankumpf. Able to add it back to my home screen as an icon. 

I do not think it was iOS 14 that fixed it, believe it was the change in TeslaMate v1.20 that did not force the dashboards into kiosk mode. Or maybe Grafana v7. Not sure.
