### ISSUE TITLE
Update FQDN with new domains doesn't reflect changes in traefik

### ISSUE THREAD

**Issue by initishgupta** [adriankumpf/teslamate#656]
**Describe the bug**

I recently tried to update the FQDN for Graffana and Teslmate. It seems like traefik did not try to generate certs for new domains in trafik. The subdomains were generated from duckdns.org. 
The reason to update to duckdns subdomain as duckdns support adding TXT record generated byt my local ubuntu server

Note: I am using duckdns because duckdns allow TXT record of subdomain update. So subdomains are technically secure when going from duckdns 

**To Reproduce**

1. Go to .env file and update FQDN for both grafana and teslamate
2. Go to teslamate docker and run docker-compose up -d
3. It will create new containers for grafana and teslamate but not traefik.
4. In traefik logs i do not see the domains xxx.duckdns.org and yyy.duckdns.org

**Expected behavior**

New domains should have been update in traefik

**Relevant entries from the logs**

You must provide the logs of the teslamate container/application unless the bug can be narrowed down to Grafana.
To get the teslamate Docker container logs, for example, use the following command: `docker-compose logs teslamate`.

```

Teslamate
01:41:31.551 [info] Access TeslaMateWeb.Endpoint at http://xxx.duckdns.org
01:52:21.459 [info] Access TeslaMateWeb.Endpoint at http://xxx.duckdns.org

Grafana
t=2020-04-28T05:41:14+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=https://yyy.duckdns.org"
t=2020-04-28T05:52:07+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=https://yyy.duckdns.org"


```

**Screenshots**

If applicable, add screenshots to help explain the problem.

**Data**

If applicable, add an export of the data for the given period.

For example, to export charge data after January 1, 2020:

```bash
docker-compose exec database psql teslamate teslamate -c \
   "COPY (select * from charges where date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charges.csv

docker-compose exec database psql teslamate teslamate -c \
   "COPY (select * from charging_processes where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charging_processes.csv
```

To export drive data after January 1, 2020:

```bash
docker-compose exec database psql teslamate teslamate -c \
   "COPY (select id, car_id, drive_id, date, elevation, speed, power, odometer, ideal_battery_range_km, est_battery_range_km, rated_battery_range_km, battery_level, usable_battery_level, battery_heater_no_power, battery_heater_on, battery_heater, inside_temp, outside_temp, fan_status, driver_temp_setting, passenger_temp_setting, is_climate_on, is_rear_defroster_on, is_front_defroster_on from positions where date > '2020-01-20') TO STDOUT WITH CSV HEADER" > positions.csv

docker-compose exec database psql teslamate teslamate -c \
   "COPY (select * from drives where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > drives.csv
```

**Operating environment**

- TeslaMate Version: [e.g. v1.14.0]
- Type of installation: [e.g. Docker or Manual]
- OS: [e.g. Ubuntu]

**Comment by adriankumpf** [comment]
Try to stop the whole docker stack with `docker-compose down` to pick up the new values. If this does not help, I would ask you to report this in the traefik issue tracker, because this is a traefik-specific question and not a bug in TeslaMate.
