### ISSUE TITLE
Support for multiple Tesla Accounts?

### ISSUE THREAD

**Issue by tb205gti** [adriankumpf/teslamate#661]
**Describe the bug**
Not a bug per se - but could not find the answer anywhere. (cannot add the question tag)

Will it be possible to have support for multiple Tesla accounts? eg. two cars tied to each own account. (Perhaps to run teslamate in two instances on different ports?)

**To Reproduce**

**Expected behavior**

**Relevant entries from the logs**

You must provide the logs of the teslamate container/application unless the bug can be narrowed down to Grafana.
To get the teslamate Docker container logs, for example, use the following command: `docker-compose logs teslamate`.

```
paste logs here
```

**Screenshots**

If applicable, add screenshots to help explain the problem.

**Data**

If applicable, add an export of the data for the given period.

For example, to export charge data after January 1, 2020:

```bash
docker-compose exec database psql teslamate teslamate -c \
   "COPY (select * from charges where date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charges.csv

docker-compose exec database psql teslamate teslamate -c \
   "COPY (select * from charging_processes where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charging_processes.csv
```

To export drive data after January 1, 2020:

```bash
docker-compose exec database psql teslamate teslamate -c \
   "COPY (select id, car_id, drive_id, date, elevation, speed, power, odometer, ideal_battery_range_km, est_battery_range_km, rated_battery_range_km, battery_level, usable_battery_level, battery_heater_no_power, battery_heater_on, battery_heater, inside_temp, outside_temp, fan_status, driver_temp_setting, passenger_temp_setting, is_climate_on, is_rear_defroster_on, is_front_defroster_on from positions where date > '2020-01-20') TO STDOUT WITH CSV HEADER" > positions.csv

docker-compose exec database psql teslamate teslamate -c \
   "COPY (select * from drives where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > drives.csv
```

**Operating environment**

- TeslaMate Version: 1.19.2
- Type of installation: Manual
- OS: Ubuntu 18.04 LTS

**Comment by tb205gti** [comment]
So tried to setup a new instance in a different basedir, different database, db user, web port etc.

However there are a few challenges;

1) Cannot start teslamate on a different port due to the following error:
Protocol 'inet_tcp': the name teslamate@saturn seems to be in use by another Erlang node

2) MQTT topics would be mixed as you cannot change the prefix (teslamate) - so both instances would publish to teslamate/cars/1/# 

Can we have the MQTT prefix configurable perhaps?

**Comment by adriankumpf** [comment]
> 2 .MQTT topics would be mixed as you cannot change the prefix (teslamate) - so both instances would publish to teslamate/cars/1/#

What you are looking for is the [MQTT_NAMESPACE environment variable](https://docs.teslamate.org/docs/configuration/environment_variables).

 Native support for multiple accounts is not in line with the vision of this project. Similar requests were discussed in #348, #403 and #180.
