### ISSUE TITLE
pg_dump: schema with OID 2200 does not exist

### ISSUE THREAD

**Issue by tobintax** [adriankumpf/teslamate#668]
Teslamate is working fine and I can connect with pgadmin. Tried to implement a daily backup of my teslamate db with the suggested backup command. 

docker-compose exec database pg_dump -U teslamate teslamate > teslamate.bck

cat teslamate.bck
pg_dump: schema with OID 2200 does not exist

Here's the database section from my docker-compose.yml: 

  _database:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=xxxxxxx
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data_

Does anyone has this issue?

**Comment by wxyk** [comment]
Did you solve the problem?
