### ISSUE TITLE
Request: Index Removal

### ISSUE THREAD

**Issue by Dulanic** [adriankumpf/teslamate#669]
Wanted to mention that there are indexes that are not used that are using space . Use this SQL to find indexes that are not being used. Most are small and no big deal, but I'd recommend that index positions_ll_to_earth_latitude__longitude_index is removed as there is no usage and it adds significantly to the table size which can end up being detrimental to overall query performance.

tablename | indexname | num_rows | table_size | index_size | unique | number_of_scans | tuples_read | tuples_fetched
-- | -- | -- | -- | -- | -- | -- | -- | --
positions | positions_ll_to_earth_latitude__longitude_index | 340042 | 44 MB | 42 MB | N | 0 | 0 | 0

```
SELECT
    t.tablename,
    indexname,
    c.reltuples AS num_rows,
    pg_size_pretty(pg_relation_size(quote_ident(t.tablename)::text)) AS table_size,
    pg_size_pretty(pg_relation_size(quote_ident(indexrelname)::text)) AS index_size,
    CASE WHEN indisunique THEN 'Y'
       ELSE 'N'
    END AS UNIQUE,
    idx_scan AS number_of_scans,
    idx_tup_read AS tuples_read,
    idx_tup_fetch AS tuples_fetched
FROM pg_tables t
LEFT OUTER JOIN pg_class c ON t.tablename=c.relname
LEFT OUTER JOIN
    ( SELECT c.relname AS ctablename, ipg.relname AS indexname, x.indnatts AS number_of_columns, idx_scan, idx_tup_read, idx_tup_fetch, indexrelname, indisunique FROM pg_index x
           JOIN pg_class c ON c.oid = x.indrelid
           JOIN pg_class ipg ON ipg.oid = x.indexrelid
           JOIN pg_stat_all_indexes psai ON x.indexrelid = psai.indexrelid )
    AS foo
    ON t.tablename = foo.ctablename
WHERE t.schemaname='public'
AND idx_scan = 0
ORDER BY pg_relation_size(quote_ident(indexrelname)::TEXT) desc
```

**Comment by adriankumpf** [comment]
Thanks for pointing that out. I should have noticed these unused indexes, but apparently deleted both "ll_to_earth" indexes at some point. Therefore, my production database didn't have them at all.
