### ISSUE TITLE
"min. distance per drive" on Efficiency doesn't filter correctly in miles

### ISSUE THREAD

**Issue by dyxyl** [adriankumpf/teslamate#671]
(sorry for incomplete initial report -- hitting Enter unexpectedly posted it)

When the preferred unit of length is miles, the "min. distance per drive" doesn't filter correctly.
For example, setting it to 5 still considers drives less than 5 miles.

I think the problem is in the SQL in efficiency.json where it does:
```
AND distance >= convert_km($min_distance, '$length_unit')
```
This should be 
```
AND convert_km(distance, '$length_unit') >= $min_distance
```

**Comment by Dulanic** [comment]
It looks right to me, If I reverse it, you can see what this is excluding and it's all the tiny small drives less than 1 mile. Why do you think it's not working as intended?

![image](https://user-images.githubusercontent.com/2948206/80868117-1546d700-8c5e-11ea-8ec8-98daa699ce6e.png)

**Comment by Dulanic** [comment]
Oh I see the problem, it's the KM to mi conversion. PR inc.
