### ISSUE TITLE
Efficiency uses the word efficiency incorrectly

### ISSUE THREAD

**Issue by dyxyl** [adriankumpf/teslamate#674]
The three panes at the bottom of the Efficiency dashboard all use the word efficiency/efficiencies, but they are actually showing consumption.

**Comment by Dulanic** [comment]
This to me is a topic for debate :) To me efficiency elsewhere isn't fitting. The Wh/Mi to me is your efficiency. The other % efficiency to me is just a Rated to Actual comparison and not technically efficiency.

**Comment by dyxyl** [comment]
I know it does seem natural to use the word efficiency instead of consumption, but its wrong: the technical definition of efficiency is the ratio of the useful work produced to total input energy.  You are correct that Rated to Actual is not technically efficiency either, but at least it has the same units (i.e. none!).
