### ISSUE TITLE
Change date formats to universal

### ISSUE THREAD

**Issue by DrJohnM61** [adriankumpf/teslamate#676]
**What would you like to be added**:
US format dates are used and these are confusing to UK users as we use DD/MM/YY. Recommend using non ambiguous format DD-MMM-YY

**Why is this needed**:
To avoid confusion for global users

**Additional context**:

**Comment by Koofteh123** [comment]
Select to edit table, go to second tab and there you can change the date format.

24 hour clock makes my brain hurt, I was so glad when I finally switched it to AM/PM. 😁

**Comment by DrJohnM61** [comment]
@Koofteh123 Thank you. I can update the view or even the JSON, however, won't that get overwritten if there is a new release? Not a grafana expert...

![image](https://user-images.githubusercontent.com/59447364/80952163-2247ff80-8df1-11ea-8e54-f562763c37ee.png)

**Comment by Koofteh123** [comment]
Yes, it will get overwritten with an update. I learned this the hard way. 😕

You have to copy the JSON code when it tells you it can't save a provisioned dashboard. Then click the gear icon on top of the page, go to JSON model tab and paste in the code you copied.

**Comment by DrJohnM61** [comment]
> Yes, it will get overwritten with an update. I learned this the hard way. 😕
> 
> You have to copy the JSON code when it tells you it can't save a provisioned dashboard. Then click the gear icon on top of the page, go to JSON model tab and paste in the code you copied.

Thanks - I appreciate the advice and this is something that I am aware of and have experimented with. My request was for an enhancement so that this could be a universal change to the base code. My suggested format looks that it will work without taking much reporting space (IMHO), would be globally acceptable as a date format and be persistent if applied to the base JSON code.
