### ISSUE TITLE
Allow editing of start and end address in drive records

### ISSUE THREAD

**Issue by swotam** [adriankumpf/teslamate#681]
I’ve noticed that TeslaMate often “misses” the correct starting location of a drive and will use a random nearby address when the drive is detected.

Would it be possible to allow editing of the start or end addresses in Drive records so that, in cases where a drive is detected late, it can be manually fixed via the UI as opposed to trying to edit the database record.

I have many drives that started at home but were not detected as such, and instead have random starting addresses around my neighborhood that presumably correspond to the address the vehicle was passing at the time the detection occurred.

Alternatively, in cases where the vehicle was previously at a location such as Home or Work, would it be possible for this to be the start point for a subsequent drive even in cases where the drive is not initially detected for a minute or two?

Obviously if my vehicle is at home and I drive to get groceries, the start point of that drive was my home, not an address a couple of blocks away, etc.

**Comment by petariga** [comment]
I completely agree, I noticed some Drives have started a few minutes late and therefore they have different starting location in my neighbourhood, so editing of the start address would sort it out. However, I haven't noticed the same issue with the end address yet. 

It would be good to know, why this happens even with the streaming API. I thought that the streaming API was chosen for not having this behaviour.

**Comment by DrMichael** [comment]
Could that be a GPS issue? I noticed, that the navigation is quite disoriented during the first 20-30 seconds...

**Comment by petariga** [comment]
According to my perception, the bug with the late beginning of Drives (seems to be about 2-3 minutes only) is either connected to switching from wifi (in the garage) to LTE (out of garage) or not remembering the last GPS location (there is no GPS signal in the garage) and it requires time for gathering enough GPS signal again (once driving under the open sky again). However, of course, the car knows its location all the time, it is shown correctly in the map, so it might be a bug in the car's computer or Tesla's streaming API too.

**Comment by DrMichael** [comment]
> ... However, of course, the car knows its location all the time, it is shown correctly in the map, ...

I don't see that. At the beginning of a drive, the position on the map stays, where it was for some time. Perhaps 1 minute or so... And then it flips to the current position.

**Comment by petariga** [comment]
I can try to pay more attention to it next time. However, I assume that Tesla does not rely only on GPS - it definitely knows the direction (azimuth) and can read the distance covered from the wheels, so even if they do not get the GPS signal for a while, they must know where the car is with a high probability (this is the standard functionality of any recent navigation system in a car).

**Comment by tabascoeye** [comment]
I regularly see the map/position in the car being totally confused when exiting the garage and taking up to a minute or two to get a correct GPS fix again.
So the car itself definiitely also doesn't know its location all the time.
