### ISSUE TITLE
TeslaMate icon back to dot; previously arrow

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#683]
**Describe the bug**
When loading the TelsaMate homepage, the icon for displaying your cars location, it is back to a blue dot. In version 19.0, it added an arrow:
[V1.19.0](https://github.com/adriankumpf/teslamate/releases/tag/v1.19.0) `Display an arrow instead of a generic marker to indicate in which direction the vehicle is heading`

**Expected behavior**
Arrow pointing in the direction that the car is facing.

**How to reproduce it (as minimally and precisely as possible)**:
1. Load TeslaMate web interface
2. Look at location indicator

**Relevant entries from the logs**
N/A

**Screenshots**
![Screen Shot 2020-05-04 at 3 26 51 PM](https://user-images.githubusercontent.com/54645561/81010314-b038e000-8e1b-11ea-88f8-d0a979c9985c.png)

**Data**
N/A

**Environment**
- TeslaMate version: V1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: Rasbian
- User OS & Browser: macOS 15; Safari

**Comment by tucopup** [comment]
I  have 3 cars, one shows a dot (asleep for days), the other two (one asleep for a day and one awake) both show arrows.  I woke them up, they all now show arrows.  All of the arrows appear to face the correct directions.

**Comment by cwanja** [comment]
> I have 3 cars, one shows a dot (asleep for days), the other two (one asleep for a day and one awake) both show arrows. I woke them up, they all now show arrows. All of the arrows appear to face the correct directions.

Ah. So it is a sleep issue then. Wonder if that is intentional. Due to being asleep, the API cannot report the heading, thus it falls back to an icon (no clue if that is valid, just my assumption). Thanks @tucopup

**Comment by natrlhy** [comment]
I see this, too if I restart/update teslamate and the car is still asleep
