### ISSUE TITLE
[Question] Will TeslaMate detect the HW3 Upgrade?

### ISSUE THREAD

**Issue by SemoTech** [adriankumpf/teslamate#685]
Greetings! Having my TM3 HW2.5 computer upgraded to HW3.0 FSD this weekend and wanted to know if this will have any impact with TeslaMate?  Will the upgrade be detected similar to the firmware upgrades or somehow different. Do I have to do anything afterwards? Etc...

Thank you. 

P.S. Also if anyone has had this done already, have you asked Tesla and were you allowed to keep the old 2.5 computer?

**Comment by Rfvgyhn** [comment]
Regarding the old computer, I've read that some don't let you keep it and it and others charge a $1000 core charge to keep it. If you can't keep it, I recommend [wiping any data you can off of it](https://www.reddit.com/r/teslamotors/comments/gcy39w/if_you_had_model3_fsd_upgrade_or_mcu2_retrofit/fpe3e3j/). It seems as though [tesla doesn't wipe the MCUs](https://insideevs.com/news/419525/tesla-data-leak-personal-info-ebay/) and some tesla techs are selling off the old computers and they end up on places like ebay where that data can be obtained by someone other than you.

**Comment by SemoTech** [comment]
@Rfvgyhn that is exactly why I asked. Technically this is not an in-warranty repair, but a paid upgrade. You paid for the old computer and for the new computer by buying FSD. Both belong to you.

**Comment by Dulanic** [comment]
Tesla doesn't report the hardware version in the API's.

Also, they will likely pull a "technically" you paid for FSD, we just upgraded your hardware at no cost.

**Comment by durzel** [comment]
> @Rfvgyhn that is exactly why I asked. Technically this is not an in-warranty repair, but a paid upgrade. You paid for the old computer and for the new computer by buying FSD. Both belong to you.
> 
> Wiping info is lacking and seems to not erase everything. Any references for a more thorough process?

That presupposes that the upgrade price doesn't include them retaining the old hardware, though.

**Comment by SemoTech** [comment]
@durzel True, but in that case it should not end up on eBay. The fact that they are not tracking and properly recycling the old computers shows they have no need for them, and they are of no value to Tesla. The places charging $1K must be the managers private deals. I am sure if Elon found out he’d fire them. 

Anyway, we’re about to find out how far I get with my swap this weekend....

**Comment by SemoTech** [comment]
UPDATE: I heard back from my advisor. There is no $1K option to keep it, and supposedly they have to send it back to CA. They will give me a written data disposal statement confirming all data was wiped from the old one.

**Comment by SemoTech** [comment]
UPDATE 2: My car is being gutted, and the HW3.0 FSD computer being installed as we speak.  Let's hope there is no issue with TeslaMate detecting it and the Streaming API continuing to work afterwards.

**Comment by SemoTech** [comment]
UPDATE 3: All done! Dropped the TM3 off at 8:15AM and it was fully ready and waiting for me at 4:15PM. The entire swap, re-flash and re-program process (to 2020.12.11.1) took 8 hours! 

They backed-up all my settings, profiles, shortcuts, presets, passwords, and configs onto a USB stick and dropped them on the new HW3 computer. only thing different was the Bluetooth and WiFI MAC address so you have to re-pair and re-connect to WiFI. 

I got a work invoice for $0 that stated they properly wiped the old computer after the backup. Let’s hope they keep their word. 

All seems just like before, and TeslaMate did not skip a beat or noticed any difference, which is great to see. 

Only “issue” is that I cannot enable “Traffic Light and Stop Sign Control” until downloading latest ”updated maps” on WiFI. After update the car had 2019 maps. Well, I’ve been connected to WiFI for 3h and did get the 2020.12.11866 maps, yet this still seems not enough. 

What maps do any HW3 owners have that allow you to enable the Traffic light Autopilot toggle?
