### ISSUE TITLE
Teslamate status on MQTT

### ISSUE THREAD

**Issue by tb205gti** [adriankumpf/teslamate#688]
**What would you like to be added**:

MQTT Topic for internal status of teslamate

**Why is this needed**:
Integration of eg. when teslamate "goes into sleep mode" via mqtt topic

**Additional context**:

It would be nice to have some internal teslamate status published to a MQTT topic, specifically I'm
looking for a message when teslamate goes into the sleep mode where it does not poll the car.

**Comment by olexs** [comment]
This information is available via the `state` topic. It shows `suspended` during the "falling asleep" period.
