### ISSUE TITLE
404 Error in "Charge" page when i click on a location

### ISSUE THREAD

**Issue by tomS3210** [adriankumpf/teslamate#689]
Hello,

**Describe the bug**
I have a 404 Error in "Charge" page when i click on a location to edit or add one GeoFence
(Link : http://aaa.bbb.ccc.ddd:3000/geo-fences/1/edit for example)

**Environment**
- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian
- User OS & Browser: OSX / Chrome

Thanks for you work :-)

**Comment by Dulanic** [comment]
Sounds like a teslamate docker issue, when you go to http://ipaddress:4000 is it functioning properly? Can you go to geofences and get to 1? Or maybe you dont have the right URL stored in settings for webapp?

**Comment by Dulanic** [comment]
No i mean if you go to teslamate and then geofences... are they showing? If so, can you get into #1? If so, how does the url differ? That's the only possible explanation IMO. Look between going to the geofence via teslamate and the url if you go from grafana.

**Comment by tomS3210** [comment]
Ok

http://192.168.1.41:4000/geo-fences/1/edit <http://192.168.1.41:4000/geo-fences/1/edit> is working
But the link in the grafana charge page is going to : http://192.168.1.41:3000/geo-fences/1/edit <http://192.168.1.41:3000/geo-fences/1/edit>

So I just changed the URL ports in Teslamate Config and now it’s ok, thanks for your help.

Maybe i can improve the French translation to avoid this. What are supposed to be 
- URL APP Web
and
- URL Dashboards ?

Regards

thomas

**Comment by adriankumpf** [comment]
I think the translations are okay, but we could make it clearer what is meant by using "Grafana" instead of "Dashboards" (for all translations).

**Comment by tomS3210** [comment]
Hello,

For the URL’s you could use :

« Teslamate portal" and "Graphana Dashboard" ?

Thanks
Thomas
