### ISSUE TITLE
How do I change docker log level to debug?

### ISSUE THREAD

**Issue by scadaguru** [adriankumpf/teslamate#691]
I would like to change default logging level from "info" to "debug".
Also it will be nice to write them in generational log file with date stamp so I can mount volume to get persisted on host.
Great work guys! Please keep it up!
Thanks a lot

**Comment by bahree** [comment]
Logging for docker depends on the 'driver' you are using for logging and the details are correlated to those mechanisms. If you haven't have a look at: https://docs.docker.com/compose/compose-file/#logging
