### ISSUE TITLE
Cannot login to grafana

### ISSUE THREAD

**Issue by cleanev** [adriankumpf/teslamate#697]
**Describe the bug**
Cannot login to grafana

Installed latest teslamate following documentation on RPi3B+, everything seems to be working and when trying to favorite (star) a dashboard, mentions a need to login that does not work using ‘teslamate’/‘secret’ as I did not make any change to docker-compose.yml example in documentation.
Tried below combinations also
admin/admin
admin/secret
teslamate/admin
teslamate/password

**Expected behavior**

Hoped to login with user I’d/password in docker-compose.yml

**Environment**

- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian Buster on RPI3B+
- User OS & Browser: none
- Others: none

**Comment by pmboothby** [comment]
You can try to reset the password using this:
'
docker exec teslamate_grafana_1 grafana-cli admin reset-admin-password 'mynewpassword'
'

**Comment by cleanev** [comment]
Thank you @pmboothby that one worked perfectly.

> You can try to reset the password using this:
> 
> `docker exec teslamate_grafana_1 grafana-cli admin reset-admin-password 'mynewpassword'`

**Comment by Kriss1670** [comment]
Doesn't work on my TeslaMate (Raspberry Pi) : `Error : No such container : teslamate_grafana_1`

**Comment by pmboothby** [comment]
@Kriss1670 : It's possible that your container has a different name prefix to "teslamate_". If you used _docker-compose_ to create the containers, it will default to using the directory name holding the compose file to the container name prefix (e.g. teslamate_). Change to the directory with the docker compose file and run _docker-compose ps_. You'll see the names of all the running containers. Use the appropriate grafana container name for the password reset command. You'll see something like this:
```
pi@docker0:~/docker/teslamate $ docker-compose ps
        Name                       Command               State                    Ports
---------------------------------------------------------------------------------------------------------
teslamate_database_1    docker-entrypoint.sh postgres    Up      5432/tcp
teslamate_grafana_1     /run.sh                          Up      3000/tcp
teslamate_proxy_1       /entrypoint.sh --global.se ...   Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
teslamate_teslamate_1   tini -- /bin/sh /entrypoin ...   Up      0.0.0.0:4000->4000/tcp
```

**Comment by Kriss1670** [comment]
Worked perfectly ! Thank you very much, not very friend with Linux...

**Comment by tsjames6** [comment]
Thanks, Peter. I just migrated my Teslamate application to a new system then could't access it. The above fix worked perfectly. The container name on mine had dashes, not underscores between the words.
