### ISSUE TITLE
Consumption and kWh used not showing

### ISSUE THREAD

**Issue by cleanev** [adriankumpf/teslamate#699]
**Describe the bug**
Consumption and kWh not reported.
I am not sure if it my setup, or if the setup is too new to gather/display some metrics. Case in point, I have driven my car about 133 miles and recorded 6 out of 8 trips. 2 missing trips are That were exactly for 6 miles each way
**Expected behavior**
 When checking Drives, Drive stats, Trips and others there is no indication of consumption or kWh used

**Screenshots**
![E5923FFA-D1F1-45F8-904F-C2E0FE0288EE](https://user-images.githubusercontent.com/45519661/81295494-7e539380-903e-11ea-949d-3267f6e557fd.jpeg)

**Environment**

- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: RPi3B+
- User OS & Browser: MacOS/iPadOS & Safari
- Others: N/A

**Comment by Dulanic** [comment]
https://docs.teslamate.org/docs/faq

Why are no consumption values displayed in Grafana?
Unfortunately the Tesla API does not return consumption values for a trip. In order to still be able to display values TeslaMate estimates the consumption on the basis of the recorded (charging) data. It takes at least two charging sessions before the first estimate can be displayed. Each charging session will slightly improve the accuracy of the estimate, which is applied retroactively to all data.

**Comment by cleanev** [comment]
Ah, so that raises an interesting question. 

Does the charging mentioned in FAQ refer to home charging (AC) or supercharging (DC)?

I have charged 4 times at home as shown in attached snapshot 
![170D9CEF-A6E1-4809-88B5-E9FD72F3760D](https://user-images.githubusercontent.com/45519661/81346412-3ce7d600-9088-11ea-9e04-dac706dab835.jpeg)

**Comment by Dulanic** [comment]
Shouldn't matter. It should show to soon. I'm honestly surprised it hasn't yet.

**Comment by cleanev** [comment]
Thanks again @Dulanic.

I will continue to monitor and report

**Comment by cleanev** [comment]
Even after few more drives there is no indication of consumption populating. I tried to go thru all different panels that are present and took snapshots to see if @Dulanic has any other ideas I should explore.

![EE547FBA-8DB6-4CEB-BC0C-ED0197D7CE90](https://user-images.githubusercontent.com/45519661/81408488-52521400-910b-11ea-80cf-dec8fcbcdd53.jpeg)
![308637F3-881F-453C-AE44-3AC2BBC3A637](https://user-images.githubusercontent.com/45519661/81408491-52eaaa80-910b-11ea-8c68-e3c6d811422f.jpeg)
![9D48DFD4-F3D8-48F5-B33F-7ACCC30E0125](https://user-images.githubusercontent.com/45519661/81408492-53834100-910b-11ea-9922-adcb33c7219b.jpeg)
![A1BF633C-6FA6-4F6A-90AA-08D72D0AB9A1](https://user-images.githubusercontent.com/45519661/81408493-53834100-910b-11ea-85ea-e12e7473c758.jpeg)

**Comment by cleanev** [comment]
Finally results got in. Seems there is some requirement to be met for consumption to be calculated. After few days and almost 300+ miles everything seems to be functional.

Question is what is the threshold or minimum requirements for these calculations. Would be prudent to add this to readme/faq so new users can be directed to that.

![E871F246-FD9F-4FA7-A5D0-68D19E4E3D2B](https://user-images.githubusercontent.com/45519661/81476851-2eadcd00-91e2-11ea-8d7c-009d7f40f076.jpeg)
![72E14A4E-3674-4981-802B-AF631B0CE904](https://user-images.githubusercontent.com/45519661/81476852-2f466380-91e2-11ea-8f6a-91821da06d6b.jpeg)

**Comment by papakwstas** [comment]
For my case still there is quite a problem there. I installed Teslamate and restored data from previous backup and all seem to be OK. Unfortunatelly there is no comsumpion data yet although i have completed several AC and DC charges. Any ideas? This is quite furstrating. 
Please see the photos for more.. 
![drives](https://user-images.githubusercontent.com/58748093/151334881-951f202b-40ef-4bd6-82d6-2a63410b62bd.PNG)
![nodata](https://user-images.githubusercontent.com/58748093/151334893-39520e34-c834-49fd-960b-bb0473026afd.PNG)
![charges](https://user-images.githubusercontent.com/58748093/151334896-c09e20db-a7a4-4d32-aca4-9520496b940c.PNG)

**Comment by Stack9000** [comment]
I have the same issue as well, but only have four charges in my db so far. Will be patient. Thank you for posting this.

**Comment by abarghoud** [comment]
I fixed the issue by setting manually the `efficiency` column in the `cars` table, it was `null`, knowing that I've already recorded a lot of drives charges.

Please note that you need to set it using this formula: wh/km / 1000.
