### ISSUE TITLE
Strange information in Charge Details

### ISSUE THREAD

**Issue by petariga** [adriankumpf/teslamate#700]
While charging AC (Mennekes) the "Charge Details" state it is 2 phases, however according to standard and Tesla infotainment it should be 3 phases.
While charging DC (CCS) the "Charge Details" state Charging Voltage 2V, which obviously can't be true. Current (pilot) 16A looks also weird, if charging is with the power of 39 to 49kW. Starting power from -1kW (minus) seems to be strange as well.

**Expected behavior**
Show real number of phases for the AC.
Show real voltage and current for the DC, do not show negative power (kW). If the values are not available, let them set to zero (better than 2V or 16A).

**Screenshots**
See the attached screenshots.

**Environment**
- TeslaMate version: 1.19.2
- Type of installation: Docker
- OS TeslaMate is installed on: Linux
- User OS & Browser: Firefox
- Others: Model 3 LR

AC
![AC_charging_details](https://user-images.githubusercontent.com/64809507/81315420-9224e700-908a-11ea-8a51-a12a2591ebda.png)

DC
![DC_charging_details](https://user-images.githubusercontent.com/64809507/81315435-96510480-908a-11ea-9e32-f1a3b85e9b6e.png)

**Comment by adriankumpf** [comment]
These values are logged and displayed as reported by the car. TeslaMate has no influence on the correctness. Regarding the incorrect phases see  #670, #605 or #414.
