### ISSUE TITLE
Firmware Downgrade not logged

### ISSUE THREAD

**Issue by gryghst72** [adriankumpf/teslamate#704]
** Problem **
Firmware version reporting in Grafana does not match TM

** Description **
Car's firmware was downgraded from 12.10 to 12.5 and Grafana is still reporting 12.10

** Solution **
In lib/teslamate/vehicles/vehicle.ex, change: 
if normalize_version(last_vsn) < normalize_version(vsn) do
to:
if normalize_version(last_vsn) != normalize_version(vsn) do

**Environment**

- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: N/A
- User OS & Browser: N/A

**Comment by baylanger** [comment]
Downgrade car's firmware, I am and perhaps others are curious... was the downgrade done by service center or ?!

Agree that TM likely needs to support firmware downgrade, even if it's rare occasion.  The only case that I wonder... if you were at version A.B.C and upgraded to A.B.D and downgraded back to A.B.C - TM might not support 2 installation occurrences of the same firmware version on 2 different date/time.

**Comment by gryghst72** [comment]
Guess it doesn't matter now ... I have a new firmware push from the mothership. But if I take the upgrade, I'm afraid TM will miss this in-between number.

**Comment by Dulanic** [comment]
I know I had a tech push a firmware, but they just pushed the same version and that did show.


1 | 1/26/20 6:11 PM | 1/26/20 6:11 PM | 2019.40.50.7 ad132c7b057e | 1
-- | -- | -- | -- | --
2 | 1/31/20 10:49 PM | 1/31/20 11:08 PM | 2020.4.1 4a4ad401858f | 1
3 | 3/26/20 4:03 PM | 3/26/20 4:15 PM | 2020.4.1 4a4ad401858f | 1
4 | 3/31/20 5:12 PM | 3/31/20 5:43 PM | 2020.8.3 7cbc6c4cd1c8 | 1
5 | 4/11/20 2:36 AM | 4/11/20 2:53 AM | 2020.12.5 e2179e0650f0 | 1
6 | 5/7/20 9:32 PM | 5/7/20 9:41 PM | 2020.12.11.1 81280b81af0a | 1
