### ISSUE TITLE
Vampire Drain dashboard showing double entries

### ISSUE THREAD

**Issue by SJPprime** [adriankumpf/teslamate#716]
**Describe the bug**
Vampire Drain dashboard shows two entries for each time period of vampire drain.  The start and end times are the same for each entry.
**Expected behavior**
Only one entry should be listed for a period of vampire drain

**How to reproduce it (as minimally and precisely as possible)**:
Look at the vampire drain dashboard.  Is it related to the fact I have two vehichles being monitored by teslamate?

**Relevant entries from the logs**

[teslamate.log](https://github.com/adriankumpf/teslamate/files/4624097/teslamate.log)

**Screenshots**
![Screenshot from 2020-05-13 11-47-18](https://user-images.githubusercontent.com/65308374/81853158-f45d6c00-9510-11ea-9696-668624295f8d.png)

**Data**
I do not know how to export the data for vampire drain but will do so if someone can instruct me

**Environment**

- TeslaMate version: 1.19.2
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian
- User OS & Browser: Linux Mint and Google Chrome

**Comment by petariga** [comment]
I know about another case with double entries in vampire drain and this Tesla account has also 2 vehicles so it be connected as suggested by @SJPprime

**Comment by Dulanic** [comment]
Fixed once he migrates the PR, was easy change.
