### ISSUE TITLE
No Data in Grafana Dashboards

### ISSUE THREAD

**Issue by raag0007** [adriankumpf/teslamate#719]
**Dont see data in Grafana Dashboards after local install.**

**After local install in dockers I dont see any data in Grafana Dashboards. Message: Tzdata has updated the release from 2019c to 2020a. cursor kept blinking. I can access both Teslamate and Grafana.**

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots
<img width="2245" alt="Screen Shot 2020-05-14 at 3 05 30 PM" src="https://user-images.githubusercontent.com/49243264/81981125-7626c580-95f5-11ea-9ccc-c175eb5b6a2f.png">
**

**Data**

**Environment**

- TeslaMate version: latest 
- Docker
- OS TeslaMate is installed on: Windows linux docker
- User OS & Browser: Chrome
- Others:

**Comment by adriankumpf** [comment]
After driving around / charging the dashboards should be populated. Any changes since this issue was created?
