### ISSUE TITLE
Projected Range chart shows 0 values

### ISSUE THREAD

**Issue by airmaxx** [adriankumpf/teslamate#720]
**Describe the bug**

Since a few weeks the chart shows values of zero that make the line jump from 500 to 0 an back

**Expected behavior**

Same as before, a consistent line.

**Screenshots**

![Screenshot_20200515-195732_Chrome](https://user-images.githubusercontent.com/20067957/82081498-b87bff80-96e6-11ea-9ee6-99d1de3d34de.png)

**Environment**

- TeslaMate version: 1.19
- Type of installation: Manual
- OS TeslaMate is installed on: Ubuntu
- User OS & Browser: All
- Others:

**Comment by adriankumpf** [comment]
Could you please add an export of the data which is visualized in the "Projected Range" chart? 

```bash
psql teslamate teslamate -c \
      "COPY (SELECT car_id,battery_level,usable_battery_level,date,rated_battery_range_km,ideal_battery_range_km,outside_temp FROM positions WHERE date>'2020-04-01' AND ideal_battery_range_km IS NOT NULL) TO STDOUT WITH CSV HEADER" > positions.csv
```

and

```bash
psql teslamate teslamate -c \
      "COPY (SELECT p.car_id,battery_level,coalesce(usable_battery_level,battery_level)AS usable_battery_level,date,rated_battery_range_km,ideal_battery_range_km,outside_temp FROM charges c JOIN charging_processes p ON p.id=c.charging_process_id WHERE date>'2020-04-01') TO STDOUT WITH CSV HEADER" > charging_processes.csv
```

**Comment by airmaxx** [comment]
Thanks for investigating this. Here are the files.

[teslamatefiles.tar.gz](https://github.com/adriankumpf/teslamate/files/4673906/teslamatefiles.tar.gz)

**Comment by adriankumpf** [comment]
Hmm, with this data I get a completely different picture:

<img width="893" alt="Screenshot 2020-05-25 at 18 57 35" src="https://user-images.githubusercontent.com/8999358/82831846-cf2a0f80-9eb9-11ea-901f-d1b65427b171.png">

**Comment by adriankumpf** [comment]
Which Grafana version do you run?

**Comment by airmaxx** [comment]
Grafana version is 6.6.1

But you are right - I was not running latest dashboards. I need to check my update procedure, I thought they are beeing updated, yet they weren't.

Issue can be closed. TY again.
