### ISSUE TITLE
Migrate Docker Compose Teslamate & Postgres To New Host System

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#725]
Hi there,

I had been running the advanced setup of Teslamate on an Ubuntu VM.  I recently, tested a Linux Mint VM, and really like it.  I was able to get the advanced setup of Teslamate working in the Linux Mint environment.  However, I was wondering if there's a way to migrate over the historical data easily?  I looked up how to migrate docker containers, and honestly couldn't make much sense of what needed to be done.  Can it be done through Portainer? Or can I copy the specific Image/Volumes from the /var/lib/Docker/ folder?  Any suggestions on where to start would be greatly appreciated.  

Thanks in advance,

J

**Comment by patman2520** [comment]
HI, I migrated today from my Mac Docker setup to a Raspberry Pi docker setup. 
I migrated the data as described in the manual. It worked flawless for me. I also looked first at how to migrate in docker, in Postgresqlm .... But the teslamate manual was the solution for me!
[https://docs.teslamate.org/docs/maintenance/backup_restore](url)
good luck with it!

P@

**Comment by DrMichael** [comment]
I would say, the easiest way would be to backup the database and restore it on the target system. All data is in the database.

See https://docs.teslamate.org/docs/maintenance/backup_restore

**Comment by Dulanic** [comment]
Follow the backup and restore options.  https://docs.teslamate.org/docs/maintenance/backup_restore

**Comment by Dulanic** [comment]
lol I think we all had the same idea at the same time :)

**Comment by jun3280net** [comment]
Thanks @patman2520 @DrMichael  @Dulanic  . Going to try it now.  To be honest, I tried the previously to upgrade to Postgres 12 - but couldn't get it to work, and didn't try again.  Hoping this all works out this time!

**Comment by baylanger** [comment]
> ...But the teslamate manual was the solution for me!
> [https://docs.teslamate.org/docs/maintenance/backup_restore](url)

@patman2520 somehow the link in your post doesn't have proper url, clicking on the link opens a GitHub "No results matched your search" page.

**Comment by jun3280net** [comment]
Thanks to everyone's replies.  It was a much cleaner process than what Google had suggested.  

As I was not totally familiar with the process - I've decided to screen capture the steps for future reference :

**Part A - Original Environment**
1. Assuming the teslamate docker-compose is already running, open up another instance of terminal. 
2. Navigate to the folder where your teslamate docker-compose (eg) cd /Desktop/teslamate/
3. Execute : **sudo docker-compose exec database pg_dump -U teslamate teslamate > teslamate.bck**

![image](https://user-images.githubusercontent.com/30555695/82164501-30286680-986e-11ea-99c1-9bbd4d7bea69.png)

4. When the command completes, the teslamate.bck (backup file) is created in the /Desktop/teslamate/ folder.

![image](https://user-images.githubusercontent.com/30555695/82165228-78955380-9871-11ea-9070-89c13e72f0dc.png)

5. Copy the backup file to your new host system, to where your new teslamate docker-compose folder is (eg) /Desktop/teslamate/ .... I used Teamviewer to transfer the files

**Part B - New Environment**
1. Assuming the teslamate docker-compose is already running, open up another instance of terminal. 
2. Navigate to the folder where your teslamate docker-compose (eg) cd /Desktop/teslamate/
3. Stop teslamate by running : **sudo docker-compose stop teslamate**
![image](https://user-images.githubusercontent.com/30555695/82166024-6668e480-9874-11ea-8878-29cbf5a84fa5.png)

4. Execute the following command to drop the data from the new docker-compose, and reinitialize the data : 
**docker-compose exec -T database psql -U teslamate << .
drop schema public cascade;
create schema public;
create extension cube;
create extension earthdistance;
CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
    RETURNS public.earth
    LANGUAGE SQL
    IMMUTABLE STRICT
    PARALLEL SAFE
    AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
.**
![image](https://user-images.githubusercontent.com/30555695/82166200-06bf0900-9875-11ea-9f4a-7ed9a4f6ed6e.png)

5.  Now restore the database form the backup : 
**docker-compose exec -T database psql -U teslamate -d teslamate < teslamate.bck**
![image](https://user-images.githubusercontent.com/30555695/82166333-61586500-9875-11ea-8dc1-2af743cbe79a.png)

6.  Once restore complete.  
Shut down everything with : sudo docker-compose down . 
Now reload everything with : sudo docker-compose up.
![image](https://user-images.githubusercontent.com/30555695/82171399-6cff5800-9884-11ea-94cb-c2362f890955.png)

7.  Check Grafana to see if your data is there.
![image](https://user-images.githubusercontent.com/30555695/82171807-9c629480-9885-11ea-9523-946ebfd185e5.png)

**Comment by gjsmith66** [comment]
Thanks bro!
