### ISSUE TITLE
Question about adding second vehicle

### ISSUE THREAD

**Issue by cleanev** [adriankumpf/teslamate#728]
How do I add second vehicle to Teslamate

I will have second vehicle soon that will be registered under different account. Is it possible top track that vehicle using single instance of Teslamate or does that require a second instance of docker?

**Environment**

- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: RPi3B+
- User OS & Browser: Raspbian
- Others:

**Comment by adriankumpf** [comment]
You do not need to run a second instance of TeslaMate. Once your vehicle is connected to your Tesla account, all you need to do is restart the docker container. The car will then be added automatically.

**Comment by cleanev** [comment]
@adriankumpf - appreciate your response.
My challenge is that my daughter is picking up ‘Y’ in few weeks and will have her own account.
Is it possible to have her account information added to Teslamate so both cars can be seen thru a single instance? Or does this type of setup need another instance?

**Comment by natrlhy** [comment]
@cleanev 

Does this help?
https://teslamotorsclub.com/tmc/posts/3327404/

**Comment by cleanev** [comment]
@natrlhy - appreciate linking me to this option. I will definitely go that route once Tesla confirms delivery date in next few days.

**Comment by adriankumpf** [comment]
> @adriankumpf - appreciate your response.
> My challenge is that my daughter is picking up ‘Y’ in few weeks and will have her own account.
> Is it possible to have her account information added to Teslamate so both cars can be seen thru a single instance? Or does this type of setup need another instance?

@cleanev sorry, I missed that part. If you will be using multiple accounts, multiple instances of TeslaMate are required as well. The issues mentioned in https://github.com/adriankumpf/teslamate/issues/661#issuecomment-622931794 might be worth checking out.

**Comment by marttimato** [comment]
@adriankumpf 
Does this still work, I have two Teslas registered on the same account, but Teslamate only displays information for the older car? I have restarted Teslamate, but the new car does not appear there.

**Comment by Aeraxon** [comment]
I have Pickel up my new Model y today and restarted the Container but it does Not appear. Andy idea what i can try to get the 2nd car into teslamate?

**Comment by cwanja** [comment]
> I have Pickel up my new Model y today and restarted the Container but it does Not appear. Andy idea what i can try to get the 2nd car into teslamate?

Log out and log back in.

**Comment by Aeraxon** [comment]
That also does not work.

What I tried after my tesla app is showing two vehicles is:
1. restarting the teslamate container
2. resarting all container that come with teslamate
3. logout of teslamate and log back in with access and refresh token
4. logout of teslamate, restart all containers, log back in with access and refresh token

I still have only my model 3 in teslamate.

what could I try next?
I am on version 1.28.2 just in case that this information is important.

**Comment by cwanja** [comment]
Try and upgrade. Log out and in. The authentication and product (cars and energy products) list has been updated. Give that a day

**Comment by Aeraxon** [comment]
I have updated the containers to the newest version. - no 2nd car
I have loged out and back in again. - no 2nd car
am I doing that right? I am going on the teslamate (not grafana) ui on settings and on the bottom to logout and then reauthenticating with my tokens again.

I even created a completly fresh teslamate enviroment on my test-docker-host but also there only my model 3 is shown after logging in. no model y shown there.
I then checked if mobile access is enabled in the model y and it is.

just to keep it organized here a summary of what I have tried/did so far:
- mobile access is enabled in the car
- model Y is on the same account like the model 3
- I have restarted the teslamate container
- restarted all containers
- logged out of teslamate and reauthenticate with my tokens
- logged out of teslamate and reauthenticate  with freshly new generated tokens
- created a completly new and fresh teslamate enviroment on my docker test host

**Comment by cwanja** [comment]
> I have updated the containers to the newest version. - no 2nd car
> 
> I have loged out and back in again. - no 2nd car
> 
> am I doing that right? I am going on the teslamate (not grafana) ui on settings and on the bottom to logout and then reauthenticating with my tokens again.
> 
> 
> 
> I even created a completly fresh teslamate enviroment on my test-docker-host but also there only my model 3 is shown after logging in. no model y shown there.
> 
> I then checked if mobile access is enabled in the model y and it is.
> 
> 
> 
> just to keep it organized here a summary of what I have tried/did so far:
> 
> - mobile access is enabled in the car
> 
> - model Y is on the same account like the model 3
> 
> - I have restarted the teslamate container
> 
> - restarted all containers
> 
> - logged out of teslamate and reauthenticate with my tokens
> 
> - logged out of teslamate and reauthenticate  with freshly new generated tokens
> 
> - created a completly new and fresh teslamate enviroment on my docker test host

I'd open a new discussion. What do the container logs say when you start up?

**Comment by Aeraxon** [comment]
Yes, both cars are on the same account

I have upgraded to 1.23.3 and even did a fresh install with that version.
Even in the fresh install my model y does not get discovered while the model 3 is there instantly.

I will open a separate issue for that later today.

**Comment by cwanja** [comment]
> Yes, both cars are on the same account
> 
> 
> 
> I have upgraded to 1.28.3 and even did a fresh install with that version.
> 
> Even in the fresh install my model y does not get discovered while the model 3 is there instantly.
> 
> 
> 
> I will open a separate issue for that later today.

Please capture and provide the logs.

**Comment by Aeraxon** [comment]
I have opened a new issue
https://github.com/teslamate-org/teslamate/issues/3668

I have also attached the logs there.

**Comment by Aeraxon** [comment]
I managed to get it to work. Logging out of the tesla app on the phone and logging back in there did solf the issue.
