### ISSUE TITLE
MQTT setup with Home Assistant

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#730]
A couple days ago, I was forced to migrate from my existing home automation hardware (Wink).  I spun up a new VM to run Home Assistant, and was pleasantly surprised with all the capabilities.  Rather than run 2 separate VMs (Teslamate and Home Assistant), I migrated my Teslamate setup to the Home Assistant VM.  So far everything is working well.  Home Assistant already runs an MQTT server, so I ended up disabling the MQTT container from the docker-compose file.  I am hoping to share the Teslamate MQTT data with Home Assistant, but I don't even know if I'm setting up my docker-compose file properly.  

In searching through the Issues, list, I can see a number of the members are leveraging the MQTT and Home Assistant.  I was wondering if someone would gracious enough to share their docker-compose / Home Assistant configuration - please and thanks.  How can I get the Tesla data to show up as an Entity in Home Assistant?

**My docker-compose looks like the following :** 
![image](https://user-images.githubusercontent.com/30555695/82280701-b2875800-994c-11ea-8db1-9e93dfc4c584.png)
![image](https://user-images.githubusercontent.com/30555695/82280877-288bbf00-994d-11ea-99fa-4198e393ad69.png)
![image](https://user-images.githubusercontent.com/30555695/82280910-3ccfbc00-994d-11ea-98a8-2feb4eebe4bd.png)

**Home Assistant MQTT Configuration** 
![image](https://user-images.githubusercontent.com/30555695/82284439-46115680-9956-11ea-9764-9d1e3ae05a8e.png)

I'm getting the following error from Teslamate
![image](https://user-images.githubusercontent.com/30555695/82284552-853fa780-9956-11ea-9509-b35409973d81.png)

**Comment by jun3280net** [comment]
To clarify - Home Assistant is running its own docker with MQTT running inside.  Teslamate is running in its own docker instance.  They both reside on the same VM so they share the same IP.  However, it appears Teslamate is unable to "bind" to the other Home Assistant network.  Portainer shows all the containers running as follows :

![image](https://user-images.githubusercontent.com/30555695/82506950-40cf1b80-9abe-11ea-9a2f-666c7f2d684c.png)

**Comment by Dulanic** [comment]
Feel free to close since you got it worked out as per discord.

**Comment by jun3280net** [comment]
Turns out a fresh install of Teslamate fixed the issue.  I honestly, don't know what the issue was - but maybe it was formatting/syntax.  

To debug my issue, first I tried the basic installation of Teslamate with the MQTT container removed from the docker-compose and the MQTT_Host pointed to the IP Address of Home Assistant.  This worked as hoped.  It should be noted though - you are not able to retrieve the Teslamate MQTT data using an MQTT Client.  However, your MQTT Server logs should show a connection from Teslamate.

![image](https://user-images.githubusercontent.com/30555695/82633078-7b68af00-9bb7-11ea-9f09-b860089f5302.png)

For reference, my docker-compose looks like this (MQTT_USERNAME and MQTT_PASSWORD are optional and dependent on how you setup your server) : 

![image](https://user-images.githubusercontent.com/30555695/82632885-c59d6080-9bb6-11ea-8389-9f1e7c0754c0.png)
![image](https://user-images.githubusercontent.com/30555695/82632943-04331b00-9bb7-11ea-9f80-8f9751c96896.png)
![image](https://user-images.githubusercontent.com/30555695/82632982-2462da00-9bb7-11ea-8dd7-f458abdce520.png)

Assuming all goes well, you won't be seeing the MQTT publishing errors I was getting.

You can copy the the awesome Home Assistant guide verbatim here to see the Teslamate MQTT data : 
https://docs.teslamate.org/docs/integrations/home_assistant

**Comment by RonSpawnson** [comment]
FYI I think your initial issue was you named the env variable "MQTT_PASS" rather than "MQTT_PASSWORD".
