### ISSUE TITLE
Overview dashboard shows stale values

### ISSUE THREAD

**Issue by GaPhi** [adriankumpf/teslamate#735]
**Describe the bug**
Temperature in overview dashboard is 23°C (car is online) and Tesla's app shows 45°C

**Expected behavior**
Show actual temperature.

**How to reproduce it (as minimally and precisely as possible)**:
- Let the car in a sunny place
- Wait a while
- Check temperature and activate climate conditionner from Tesla's app (or another)
- Check dashboard for status (online) and temperature (not the one in Tesla's app)

**Relevant entries from the logs**
None

**Screenshots**
Clear enough I think

**Data**
Useless to understand the problem.

**Environment**
- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: Armbian
- User OS & Browser: Windows/Chrome
- Others:

**Comment by adriankumpf** [comment]
The Overview dashboard can only display information that is stored in the database. We do not want to store data unnecessarily that has no relation to drives, charges etc. The TeslaMate UI, on the other hand, always show the most recent values.

We could make sure that the dashboard does not show outdated information, for example (temperature) values older than 10 minutes could be hidden.

**Comment by GaPhi** [comment]
Ok to not log everything, this is useless but showing the up-to-date info is interesting.
Maybe it is possible to store last up-to-date data in database in a dedicated table with only one row per car (without time interval or only [data timestamp, nil[ interval).
