### ISSUE TITLE
Teslamate shows falling asleep state for over an hour

### ISSUE THREAD

**Issue by pichalite** [adriankumpf/teslamate#746]
**Describe the bug**

After getting the vehicle online by opening the Tesla app or just opening and closing the trunk to get something out of the car without unlocking the doors, teslamate shows the vehicle is falling asleep quickly but stays in that state for over an hour before showing asleep status.

**Expected behavior**

Vehicle falls asleep with in a few minutes.

**How to reproduce it (as minimally and precisely as possible)**:

1. Bring vehicle online by opening Tesla app.
2. Check teslamate for the next 60 to 90 mins.

**Relevant entries from the logs**

No specific logs

**Screenshots**

Forgot to take screenshot this time. Will add one if needed.

**Data**

N/A

**Environment**

- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: Raspberry Pi 3
- User OS & Browser: MacOS & Safari
- Others: Streaming API is on in settings and vehicle must be locked setting is checked

**Comment by adriankumpf** [comment]
It's not uncommon for the car to stay awake for that long after driving. TeslaMate has no influence on how long the vehicle takes to fall asleep. For a similar discussion on this topic see #658
