### ISSUE TITLE
Very short charging sessions are not displayed in Charges

### ISSUE THREAD

**Issue by petariga** [adriankumpf/teslamate#751]
**Describe the bug**
Very short charging sessions are not displayed in Charges, however they are displayed in Charging Stats at least in the Top Charging Station list.

**Expected behavior**
If the charging stop is recorded by Tesla and it is in the Top Charging Station list, it should be also mentioned among Charges, otherwise you also miss km driven in the Charges table.

**How to reproduce it (as minimally and precisely as possible)**:
I haven’t tried to reproduce it yet, however it was a brief stop on DC where probably less than 1kWh was charged and it lasted less than a minute (then I had to cancel the session).

**Relevant entries from the logs**
n/a

**Screenshots**
n/a

**Data**
n/a

**Environment**

- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: Linux
- User OS & Browser: Firefox
- Others: -

**Comment by adriankumpf** [comment]
The logs and an export of your most recent charging sessions are needed to investigate this any further.

**Comment by petariga** [comment]
I tried to get logs from the time of charging, I hope this helps:

teslamate_1  | 18:48:26.386 car_id=1 [info] Driving / Start
teslamate_1  | 19:09:09.347 car_id=1 [info] Driving / Ended / 12 km – 21 min
teslamate_1  | 19:09:09.347 car_id=1 [info] Start / :online
teslamate_1  | 19:10:13.557 car_id=1 [info] Charging / SOC: 22%
teslamate_1  | 19:10:13.557 car_id=1 [info] Disconnecting ...
teslamate_1  | 19:10:51.375 car_id=1 [info] Derived efficiency factor: 152.0 Wh/km (3x confirmed)
teslamate_1  | 19:10:51.375 car_id=1 [info] Charging / Stopped / 0.10 kWh – 1 min
teslamate_1  | 19:10:51.407 car_id=1 [info] Start / :online
teslamate_1  | 19:10:51.444 car_id=1 [info] Connecting ...
teslamate_1  | 19:13:35.460 car_id=1 [info] Driving / Start
teslamate_1  | 19:27:40.980 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 19:27:42.557 car_id=1 [info] Driving / Ended / 12 km – 14 min
teslamate_1  | 19:27:42.557 car_id=1 [info] Start / :online

If you need anything from the db, please specify the query.

**Comment by adriankumpf** [comment]
If you open a new bug report it shows how to export charge data. We need the charging_processes.csv and charges.csv.

**Comment by petariga** [comment]
Thank you, the charging session which is not displayed in the Charges in Grafana is this one:

id,start_date,end_date,charge_energy_added,start_ideal_range_km,end_ideal_range_km,start_battery_level,end_battery_level,duration_min,outside_temp_avg,car_id,position_id,address_id,start_rated_range_km,end_rated_range_km,geofence_id,charge_energy_used,cost
4,2020-05-14 17:10:13.063,2020-05-14 17:10:51.142,0.10,110.05,110.72,22,22,1,13.5,1,110151,40,110.05,110.72,,0.32,

id,date,battery_heater_on,battery_level,charge_energy_added,charger_actual_current,charger_phases,charger_pilot_current,charger_power,charger_voltage,fast_charger_present,conn_charge_cable,fast_charger_brand,fast_charger_type,ideal_battery_range_km,not_enough_power_to_heat,outside_temp,charging_process_id,battery_heater,battery_heater_no_power,rated_battery_range_km,usable_battery_level
1317,2020-05-14 17:10:13.063,f,22,0.00,0,,16,-1,2,t,IEC,<invalid>,Combo,110.05,,13.5,4,f,,110.05,22
1318,2020-05-14 17:10:20.753,f,22,0.00,0,,16,41,2,t,IEC,<invalid>,Combo,109.37,,13.5,4,f,,109.37,22
1319,2020-05-14 17:10:28.098,f,22,0.00,0,,16,37,2,t,IEC,<invalid>,Combo,109.37,,13.5,4,f,,109.37,22
1320,2020-05-14 17:10:35.788,f,22,0.00,0,,16,36,2,t,IEC,<invalid>,Combo,109.37,,13.5,4,f,,109.37,22
1321,2020-05-14 17:10:43.462,f,22,0.10,0,,16,37,2,t,IEC,<invalid>,Combo,110.72,,13.5,4,f,,110.72,22
1322,2020-05-14 17:10:51.142,f,22,0.10,0,,16,-1,2,t,IEC,<invalid>,Combo,110.72,,13.5,4,f,,110.72,22

If you need a previous and following sessions too, let me know.

**Comment by adriankumpf** [comment]
Fixed on master. Short charging sessions with 0.1 kWh or less were previously hidden.

**Comment by tabascoeye** [comment]
Can we make that configurable? I'd like to either not see "top up" charges or have them counted towards the "real" charge.
I.e. When I charge to 80% and keep plugged, the car will periodically charge from 79 to 80 again, which might be interesting for counting cycles but might also irritate in the number of "real" charges.
Depends on what data I want to see..

**Comment by petariga** [comment]
In my opinion eslaMate should always count all charges, otherwise it will not display real figures. If you do not want to see real power consumption, then you can omit some charges...

**Comment by tabascoeye** [comment]
I agree it should all be logged to the database. But there could be "viewing" options to "merge" the small top-up charges into "real" charges.

**Comment by petariga** [comment]
I think you made the point - merging. This could sort out many situations, if there is a way how to merge sequential charges or drives (I think this was mentioned in some other issue too). However, I do not see some easy way how to implement it in the current Grafana interface...

**Comment by tabascoeye** [comment]
“Some SQL wizardry required“
