### ISSUE TITLE
Projected Range reported incorrectly 

### ISSUE THREAD

**Issue by ratcliffeg** [adriankumpf/teslamate#752]
Imported all data from Teslafi, 2 years worth, and when looking at dashboard “projected range” this states 375 min, 401 max and average 383.  I’m assuming this is based on new Model S100D 2019, although that’s higher than current stated 379.

![IMG_0418](https://user-images.githubusercontent.com/53779543/82766245-612c0c80-9e15-11ea-94c1-45bd8fb6a726.png)

Mine is a late 2017 S100D, range 320 stated.  Based on battery degredation we are on around 310 miles today. 

Teslafi shows 306.
![IMG_0419](https://user-images.githubusercontent.com/53779543/82766242-56717780-9e15-11ea-8719-35c7310e7223.png)

Is this just an issue with import?

**Comment by adriankumpf** [comment]
The dashboard does not assume any model to calculate the projected range. Could you export the data visualized in this dashboard and post it? 

```bash
psql teslamate teslamate -c \
      "COPY (SELECT car_id,battery_level,usable_battery_level,date,rated_battery_range_km,ideal_battery_range_km,outside_temp FROM positions WHERE ideal_battery_range_km IS NOT NULL ORDER BY date) TO STDOUT WITH CSV HEADER" > positions.csv
```

and

```bash
psql teslamate teslamate -c \
      "COPY (SELECT p.car_id,battery_level,coalesce(usable_battery_level,battery_level)AS usable_battery_level,date,rated_battery_range_km,ideal_battery_range_km,outside_temp FROM charges c JOIN charging_processes p ON p.id=c.charging_process_id ORDER BY date) TO STDOUT WITH CSV HEADER" > charging_processes.csv
```

**Comment by ratcliffeg** [comment]
Sorry, it's in a docker image on a Synology box.  Assuming I can't just PSQL in as I am getting an error, psql: FATAL:  Peer authentication failed for user "teslamate"

**Comment by ratcliffeg** [comment]
See attached:

[files.zip](https://github.com/adriankumpf/teslamate/files/4688777/files.zip)

**Comment by adriankumpf** [comment]
I've only been able to take a brief look at the data but the discrepancy could perhaps be explained by the difference between `rated` and `ideal` range. Your maximum recorded  rated range is 634 km whereas the maximum ideal range is 511 km. You can change the preferred range on the settings page.

**Comment by ratcliffeg** [comment]
Ok, that makes sense. I've changed to ideal and that's more realistic.
Though I expect rated is based on the new models in that case as my rated is 335 miles, whereas the new ones are 379.

**Comment by adriankumpf** [comment]
Yeah, no idea why Tesla decided to report those higher range values for your car. Anyway, I guess I can close this then.
