### ISSUE TITLE
Tesla app doesn’t show location while car is driving

### ISSUE THREAD

**Issue by grizzlyjere** [adriankumpf/teslamate#753]
While the car is driving the location drops in and out from the Tesla app. It’ll display for a second then disappear. It will periodically display again.

The location always shows in TeslaMate. I don’t remember this happening before streaming was implemented.  I’m wondering if the polling is happening to frequent for the Tesla app to get a chance?

I’ve tried the Tesla app while on cellular in case it was an issue with my home network, but no luck.

**Comment by sumnerboy12** [comment]
+1 - I have seen this also.

**Comment by Dulanic** [comment]
Streaming or non streaming? I have yet to see this issue myself, so just curious.

**Comment by sumnerboy12** [comment]
Streaming

**Comment by grizzlyjere** [comment]
Streaming as well for me. Didn’t encounter this issue with TeslaFi for what it’s worth.

**Comment by Dulanic** [comment]
@adriankumpf  Question.... so TeslaFi stores data about once a second. For teslamate is is either about every 3 seconds without streaming or .5 seconds /w streaming. Is it possible to slow down the streaming or speed up the polling for non streaming? I'm curious if would make any differece?

**Comment by adriankumpf** [comment]
>  I’m wondering if the polling is happening to frequent for the Tesla app to get a chance?

With streaming enabled data is **pushed** to TeslaMate. We do not decide at what rate they should arrive.

It looks like Tesla's current implementation does only allow one client to stream data from the car. You could disable the usage of the streaming API to test that theory. But to me this does not seem like a problem with TeslaMate.

**Comment by grizzlyjere** [comment]
> It looks like Tesla's current implementation does only allow one client to stream data from the car. You could disable the usage of the streaming API on the settings page to test that theory. But to me this does not seem like a problem with TeslaMate.

Turned off streaming and that did the trick. Thanks. 

>TeslaFi does not use the streaming API.

Ah, thanks for the clarification, it seemed to have such granular updates I thought it did.

**Comment by longzheng** [comment]
I've also experienced this issue. There's also a side effect where the mobile app will display an invalid/broken location far away the actual location (I've seen it in the middle of the ocean, or in Europe, Russia and Africa, when the car is suppose to be in Melbourne Australia).

![image](https://user-images.githubusercontent.com/484912/95969523-9257b880-0e5a-11eb-8f5c-385fcbe1e3c6.png)

Disabling streaming API does seem to fix it.

@adriankumpf I think it might be a good idea for other users if there's some helptext with the "Streaming API" checkbox option that suggests "Enabling this may cause issues with the location updates in the Tesla mobile app"?

**Comment by Rasmus-Riis** [comment]
I have this issue as well
