### ISSUE TITLE
QUESTION - how to schedule a task to backup database to external device

### ISSUE THREAD

**Issue by cleanev** [adriankumpf/teslamate#770]
Subject says it all - 
I am using below command from documents added to crontab on raspberry Pi 3B+ that does not run while throws the error shown below when running manually at root. Crontab has 5 * * * * prepended to the command starting at docker-compose

If I switch to ‘use/local/bin where docker-compose exists command runs well without fail. 

docker-compose exec database pg_dump -U teslamate teslamate > /sharedfolders/common/teslamate/teslamate-`date +%F`.bck >/dev/null 2>&1
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by bahree** [comment]
I have this backing up to a shared volume on my NAS everynight from a Pi. Happy to share that here if required. There was also a cron job conversation (#453) - in case you haven't seen that.

**Comment by cleanev** [comment]
Thanks @bahree  for the link - I will follow that thread and report any issues I face
