### ISSUE TITLE
Include empty geofence topic when car is not inside geofence

### ISSUE THREAD

**Issue by paulkearney** [adriankumpf/teslamate#775]
It would be nice to be able to access the current geofence (if any) via MQTT topic. If the vehicle is currently not in a geofence, the value would be empty.

As teslamate is already determining if the vehicle is in a geofence, this keeps the list of geofences and the calculation logic in one location when integrating with other systems, like HomeAssistant.

My use case is in home automation (HomeSeer), where I would like to be notified if the car is at home, has a low state of charge and is not plugged in. I currently have access to all the necessary values from teslamate except for the named location.

**Comment by adriankumpf** [comment]
Check this out: [teslamate/cars/$car_id/geofence](https://docs.teslamate.org/docs/integrations/mqtt). Is this what you're looking for?

**Comment by paulkearney** [comment]
Ah, yes, that will do. When I was looking for something related to geofence, the car wasn't inside the fence, so it wasn't showing up. Thanks for the quick reply!

**Comment by adriankumpf** [comment]
You should actually receive such a message. But it could depend on the client how messages with an empty payload are handled. MQTT.fx, for example, shows said messages.

**Comment by paulkearney** [comment]
Thanks for the explanation. For some reason my client isn't picking that up, but I did see it in MQTT.fx.
