### ISSUE TITLE
Odd charge entries in charges table - level 1 only bug?

### ISSUE THREAD

**Issue by baylanger** [adriankumpf/teslamate#776]
While the car is charging, at times I see entries showing always these numbers :

charger_actual_current = 0
charger_power = 0
charger_voltage = 2

The remaining of the column for those entries seems fine.

Seems copying those 3 values from the last written row would work but that would be such an ugly fix.  I understand this is likely bad values reported by the API and it seems adding an if statement to cover such a case could be ugly.  I do wonder of the side effects for grafana stats, it's late here I'll check tomorrow, it seems some graphs might be odd looking with such bad entries.

I also noticed fast_charger_type used to always be MCSingleWireCAN but lately then it was flapping at times between <invalid> & MCSingleWireCAN .. and is now always <invalid>.  That is likely something else that Tesla API changed lately?

If there are such odd bugs in Tesla API , perhaps we shouldn't use the auto-pilot :)

**Data**
[charges.csv.zip](https://github.com/adriankumpf/teslamate/files/4727204/charges.csv.zip)

**Environment**
- TeslaMate version: 1.19.3
- Type of installation: Docker
- OS TeslaMate is installed on: Feb 2nd

**Comment by dyxyl** [comment]
I see a similar thing on 240V AC, but the small values are always the last row in a charging session, so I assume they happen just before the voltage drops to 0.  Why do you think they are a problem?

**Comment by baylanger** [comment]
You are right they are the last row in a charging session.  I realize now why I didn't notice it before, I thought select * 

Turns out Grafana does show those last "2 Volt" entries on all graph, I guess it's fine.  I'm puzzle why it always reports 2.

Closing this request, thank you.

**Comment by dyxyl** [comment]
Yes, you always need to add an "order by" clause in SQL if the order is important.

I see various small values at the end, but I suppose there is more chance of this on 240V.
