### ISSUE TITLE
BRAVO! Working on my Synology NAS in minutes!

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#78]
This is by far no issue at all. I just wanted to say THANK YOU for an awesome project! I, too have a Synology NAS server. I followed these steps to get it working QUICKLY:

1. On Synology NAS server, install the Docker Package
2. SSH to the Synology NAS and sudo -i (root)
3. cd /volume1/@docker
4. Create the docker-compose.yml file and configure your settings.
   I modified the VIRTUAL_HOST= to point to the IP of my NAS and TZ=America\Los Angeles
   Set the password for the DATABASE_PASS parameter
5. Save the file
6. Run docker-compose up -d (looked around in the other issues and this -d option was very helpful)

Within minutes, I went to http://mynasip:4000 and entered my mytesla credentials. Then went to http://mynasip:3000 and boom! Grafana was up and running, too!

I really appreciate how slick this is and how easy it was to setup!

Is upgrading as easy as:

docker-compose pull and restart with docker-compose up -d again? Or do I have to shutdown the instances first then run a docker-compose pull command?

Looking forward to more features if more come along! Maybe this can rival teslafi.com ;) Seems like it has most everything already

**Comment by ilkkao** [comment]
I'm also a fan. Architecture is really nice. Postgress is stable. Standard grafana instead of homegrown UI is also great!

**Comment by AmpManNC** [comment]
Sounds cool. I'd like to get this running on my Synology NAS, but I'm a complete Newb at this - did you have to install/config grafana, PostgreSQL, etc first, or do the commands above do it all?

Thanks!

**Comment by natrlhy** [comment]
@AmpManNC it’s as easy as the steps I mentioned. Google for how to install Docker and if you don’t have SSH enabled on your Synology. I created the docker-compose.yml file on my PC first then copied it to my Synology. Then I used SSH to move it to the folder I mentioned. Then just follow the rest! I was up and running in 10 minutes

**Comment by AmpManNC** [comment]
Thanks! Will give it a go...

**Comment by natrlhy** [comment]
I got a bash shell on my grafana docker and see the time is UTC. I'm wondering if it didn't take my TZ=America\Los Angeles (I do have a space in the .yml file, too). How do I go about changing the TZ now that things are up and running?

**Comment by normalfaults** [comment]
I think you'll need a `_` in between Los_Angeles ...

**Comment by natrlhy** [comment]
Ok, I've made that change. Do I just stop the container and restart it?

**Comment by scottismyname** [comment]
You can do that or you can restart it from the shell.

**Comment by natrlhy** [comment]
How are you restarting it from the shell? When I go into the default shell it's already running and pressing enter doesn't do anything
![Capture](https://user-images.githubusercontent.com/19696424/62563569-23370b00-b838-11e9-8ddb-88390c706bbf.PNG)

**Comment by scottismyname** [comment]
By shell, I mean from ssh, not from the UI.

`docker-compose restart`

**Comment by natrlhy** [comment]
Gotcha! A one-hitter-quitter restart of all images... makes sense...

grafana@f9afbdd81bb8:/usr/share/grafana$ date                                   
Tue Aug  6 18:05:40 UTC 2019                                                    

doesn't seem to re-read the docker-compose.yml file with any TZ changes...

**Comment by adriankumpf** [comment]
@natrlhy  Awesome, thanks!

> docker-compose pull and restart with docker-compose up -d again? Or do I have to shutdown the instances first then run a docker-compose pull command?

Yes, upgrading should be as easy as running `docker-compose up -d` again if the new images were previously `pull`ed.

At some point, a version 2.0 will be released which will include some breaking changes e.g. removal / introduction of environment variables. But that won't happen until it's really necessary. 

> grafana@f9afbdd81bb8:/usr/share/grafana$ date
> Tue Aug 6 18:05:40 UTC 2019
>
> doesn't seem to re-read the docker-compose.yml file with any TZ changes...

I think you changes to the environment require `docker-compose down && docker-compose up -d`

**Comment by scottismyname** [comment]
Good to know @adriankumpf .  I was under the impression that a simple restart would do it, but I guess not!

**Comment by adriankumpf** [comment]
> Gotcha! A one-hitter-quitter restart of all images... makes sense...
> 
> grafana@f9afbdd81bb8:/usr/share/grafana$ date
> Tue Aug 6 18:05:40 UTC 2019
> 
> doesn't seem to re-read the docker-compose.yml file with any TZ changes...

Now that I've thought about it, you don't necessarily need to set the timezone for the grafana container. The web interface will show you the dates based on your current browser settings.

**Comment by natrlhy** [comment]
> Now that I've thought about it, you don't necessarily need to set the timezone for the grafana container. The web interface will show you the dates based on your current browser settings.

docker-compose down && docker-compose up -d didn't change the TZ either as the container still sees UTC.

Good to know! Thanks!

**Comment by AmpManNC** [comment]
@natrlhy - Thanks for your help on this. I got it working on my DS218plus, and it's pretty slick.

Have you managed to get the Tasker/"PUT" solution working, to handle the situation where you resume driving the car while TeslaMate is in its 21 minute allow-the-car-to-fall-asleep mode?

I've looked through various Synology help pages regarding allowing app access from the internet for needs such as this, but am a bit befuddled about how to go about it...

**Comment by natrlhy** [comment]
@AmpManNC with Synology you can configure it to run scripts through it's Task Scheduler, but that's more for static times. We are also discussing such things with regards to the data gap stuff [here](https://github.com/adriankumpf/teslamate/issues/80)

**Comment by bahree** [comment]
Sorry for the dumb question - but to get this going, I don't need to clone the repo or install the DB, etc separately - just have the docker yaml file and then kick it off?

**Comment by normalfaults** [comment]
You’ll need docker and docker-compose : https://docs.docker.com/compose/gettingstarted/

Nirmal Mehta

**Comment by bahree** [comment]
Oh yes of course - sorry, I should have outlined that.

**Comment by normalfaults** [comment]
Then the answer to your question is yes :) 

Nirmal Mehta

**Comment by IMgoRt** [comment]
> Then the answer to your question is yes :) Nirmal Mehta
> […](#)
> On Aug 12, 2019, at 9:40 PM, Amit Bahree ***@***.***> wrote: Oh yes of course - sorry, I should have outlined that. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Technically the answer is - no, you don't need to clone the repo or install the DBs, etc. you just need to run the docker.yml having edited it for your environment ;-)

**Comment by natrlhy** [comment]
Correct, modify the docker-compose.yml file to your liking and run `docker-compose up -d`. That's it. It will create the 4 containers it needs to run everything.

**Comment by eoren1** [comment]
@natrlhy - I think I'm missing something obvious. I copied your steps but feel like I'm not doing one thing to make this work. This is on a Synology DS918+ by the way 

This is by far no issue at all. I just wanted to say THANK YOU for an awesome project! I, too have a Synology NAS server. I followed these steps to get it working QUICKLY:

> On Synology NAS server, install the Docker Package
Okay. Docker installed and have it working with other apps (sab, sonarr). I assume you don't mean to install the teslamate image found in the Synology Docker registry

> SSH to the Synology NAS and sudo -i (root) then cd /volume1/@docker
Okay. Now I have a prompt

> Create the docker-compose.yml file and configure your settings.
I modified the VIRTUAL_HOST= to point to the IP of my NAS and TZ=America\Los Angeles
Set the password for the DATABASE_PASS parameter
Save the file

I did this with TextEdit on a Mac which added a rtf to the end (I removed the extra extension when I moved the file to the Synology folder)
Here is where I am stuck - where and how exactly do you move this file? Also, do you need to copy any of the files in this GitHub project as well? I tried doing that into the Docker/teslamate-master folder but it didn't work - got error messages when I tried to run the app using the "docker-compose up -d" in line 1, column 1 of docker-compose

**Comment by baylanger** [comment]
Before asking for help, I'll try to help :)

{noformat}
TZ=America\Los Angeles
{noformat}

I believe it should be :

{noformat}
America/Los_Angeles
{noformat}

/ not \

**Comment by baylanger** [comment]
On my Synology, from the advanced docker-compose file, I left it as-is.  When teslamate comes up I get messages saying role 'teslamate' doesn't exist, etc.  I am unclear how to fix this, I thought teslamate at boot would be able to access the db and create roles/schema.

Any help is welcome.

Thank you for documenting this.
