### ISSUE TITLE
Typo in charge-details.json puts Charging Voltage on the wrong axis

### ISSUE THREAD

**Issue by dyxyl** [adriankumpf/teslamate#786]
I noticed that the Charging Voltage on Charge Details appears on the left hand axis, but charge-details.json attempts to put it on the right hand axis:

https://github.com/adriankumpf/teslamate/blob/master/grafana/dashboards/internal/charge-details.json#L85

This doesn't work because there are two spaces before the [V] whereas the SQL only has one space.

It seems to have been like this forever, but I think it makes the scale on the left hand axis less useful for 240V AC charging. It might not affect fast DC charging much if the Current is also high.

Charging Voltage on the left:
![left](https://user-images.githubusercontent.com/64472511/83979126-0067fe00-a904-11ea-8770-4e5ccddceb8d.png)

Charging Voltage on the right:
![right](https://user-images.githubusercontent.com/64472511/83979138-0cec5680-a904-11ea-96e2-8f2a3ab4d7ee.png)

**Comment by roadrash2108** [comment]
The problem with the space before the "[V]" can't be found in the code (anymore?), but for the request itself (having the current on the left axis) I must admit that having this would also make the other lines less usable as then both axis are in the hundreds and therefore the space for the lines like SOC is very limited. IMHO the current should stay on the right axis...

**Comment by dyxyl** [comment]
@roadrash2108 I looks like you have misread the request. There is no proposal to move the current, which is already on the left axis anyway.

When I created this request, the voltage (as well as the current) was on the left axis and I wanted to move it to the right axis for the exact reasons you state. This was done as part of https://github.com/adriankumpf/teslamate/commit/b76c44fda766017da38b324e35ce36e847692ee5 (thanks Adrian!).

**Comment by adriankumpf** [comment]
I had completely forgotten that this was already fixed. It's difficult to keep the overview with that many issues. Then this can be closed.
