### ISSUE TITLE
How to manually add charging sessions to complete the history of the monitored car?

### ISSUE THREAD

**Issue by petariga** [adriankumpf/teslamate#792]
I started to use TeslaMate when my car was about a month old. Therefore there have been some charging sessions which had not been logged into TeslaMate, but not too many. I kept the track of the sessions in a notebook. It would be nice to restore them somehow **to keep the charging history of my Tesla in TeslaMate complete from the date zero.** My goal would be to have the Dashboards "Charges", "Charging Stats" and maybe "Efficiency" (Consumption net, gross, Logged Distance) as thorough as possible.

Could you suggest what would be the best way how to achieve it? Is there some sort of import from .csv file (utilize the import from TeslaFi?) or some manual way how to type these sessions in? Is it sufficient to add these sessions only to "charging_processes" table or is it more complex and it can ruin the consistency of the entire system (for example there is no odometer attribute in the "charging_processes", so I assume it is kept elsewhere)? I.e. do you also need to add some drives to "drive" table or anything other to keep the consistency?

**Comment by ngardiner** [comment]
Hi @petariga,

I have added some charging sessions manually to the charging_processes table, and it worked. I have been concerned that perhaps a later update of TM may detect invalid data and remove them, so it's not necessarily the case that this is a foolproof approach but it did work for me in tracking charging consumption and cost. 

When I get some time, I'll go back through my SQL history (if it is still there) and find the insert commands that I used. You'll need to look up a few values, such as the place location ID for the charger (if you haven't visited there since, you'll have a challenge there) and also you may need to adjust the timing to account for timezone.

If you have charged at the same location since, my recommendation is to look at the charging_processes row for that charge and grab the entire row and the column headings. This will help you a lot to construct a charging session manually. 

For some columns (such as distance since last charge, perhaps SOC before and after) you may need to just use 0, which will show a blank in the table in grafana for those values. It hasn't impacted any of the grafana data from my perspective.

**Comment by petariga** [comment]
Hi @ngardiner, 

Thank you for your kind reply. I do have the data for charging_processes table ready including the location, distance since the last charge, SOC before & after. However, if you succeed to dig up the exact SQL command you used to submit or import these additional sessions, it would be definitely helpful.

Have you anyhow reflected the sequential order of these sessions? The sessions to be added happened before the others already presented in the db, however they will have a higher id than the later. Does it matter or is it enough to have a correct date & time for each session? Or shall I export all of them, add the historical sessions, reorder them, clear the entire table and reimport them?

**Comment by muffstic** [comment]
I am also interested in doing this if anyone comes up with a solution.

**Comment by plangin** [comment]
I would also like to add charging sessions manually.
In my case the car was charging underground with a bad internet connection. So TeslaMate was not save any date about this session.

**Comment by plangin** [comment]
So, is there a way add / change data manually in the database?

Is there a preferred tool like phpMyAdmin etc.?

**Comment by petariga** [comment]
I am still hesitant to make the changes directly in the SQL db :-(.

I think that it is a little more complicated. The charging session table is cross connected to other tables and I am not sure how the sequence of charging sessions is sensitive on jumping back and forth in time - if you add older session after the newer one. 

From my point of view the best way would be to define an importing csv structure and importing script or to make a web input interface with all required atributes and type in each missing session there, of course with all the back-end importing stuff which would be needed to do not brake anything else or to do not cause any issues in other data.

**Comment by thunder2k** [comment]
Hi, it would be really helpful to be able to do that. I have an sd card corruption in my raspberry pi, I was able to restore a backup copy of 10 days before but I also have the teslamate db backups with the missing data. I've exported it, but now I'm not sure on how to import it in the restored db to fill the gap.
Any hints?
Thanks!

**Comment by qgadrian** [comment]
I created a simple module to synchronize lost/old charges into Teslamate.

There are two types of charges this module will sync, _superchagers_ and _other charges_. 

### Syncing module

The module below does the following:

* Retrieves the charge info for the _charges.json_ file
* Matches the charging location with the available supercharges in _supercharers.json_
* Inserts (if needed) the address for the charging location
* Inserts a position for the charging location
* Inserts a _dummy charge_ because the Grafana dashboard expects a _charge_process_ to have a _max_voltage_ value set ([see related PR](https://github.com/adriankumpf/teslamate/pull/2589)).
* Inserts the _charging process_

### Prerequisites

I recommend you first **backup your data** (if you haven't already) or test this in a safe environment before messing with your database.

For *superchargers* you will need to:

* Retrieve the full JSON with your charges from [this URL](https://www.tesla.com/teslaaccount/charging/api/history?vin=) and save it in `charges.json`
    * You can get it by inspecting the web browser [on this page](https://www.tesla.com/teslaaccount/charging)
* The list of Tesla superchargers from HERE and save it in `superchargers.json`
    * Inspect the API responses in [this page](https://supercharge.info/data) to get the JSON

For *other chargers* the process is not that automated and you will need to specify by hand the charges to sync:

```elixir
@non_superchargers [
    %{
      start_date: DateTime.utc_now,
      end_date: DateTime.utc_now,
      cost: 23.57,
      postcode: "1234",
      kwh: 23.97,
      latitude: "37.3940974",
      longitude: "-122.1523805"
    }
```

After that, connect to the Teslamate node and call the module: 

* For **superchargers** `TeslaMate.ChargeHistorySync.sync("./charges.json")`
* For **other charges** `TeslaMate.ChargeHistorySync.sync_custom()`

### Considerations

This module might not work for some specific cases (non-matching postcodes, address...). If that is your case, I recommend you fix manually the JSON to match the data or modify the code with whatever your need.

The code below should be idempotent, so in case it fails for you running it again won't duplicate the charges in your database.

### The code

```elixir
defmodule TeslaMate.ChargeHistorySync do
  alias TeslaMate.Log.ChargingProcess
  alias TeslaMate.Locations.Address
  alias TeslaMate.Log.Position
  alias TeslaMate.Log.Charge

  alias TeslaMate.Repo

  import Ecto.Query, warn: false

  @superchargers "superchargers.json"
                 |> File.read!()
                 |> Jason.decode!()
                 |> Map.get("results")

  @non_superchargers []

  def sync_custom() do
    Enum.each(@non_superchargers, fn %{
                                       start_date: start_date,
                                       end_date: end_date,
                                       cost: cost,
                                       postcode: postcode,
                                       kwh: kwh,
                                       latitude: latitude,
                                       longitude: longitude
                                     } ->
      TeslaMate.ChargeHistorySync.insert_data(
        start_date,
        end_date,
        cost,
        kwh,
        postcode,
        latitude,
        longitude
      )
    end)
  end

  def sync(path_to_file) do
    path_to_file
    |> File.read!()
    |> Jason.decode!()
    |> Map.get("data")
    |> Enum.each(fn charge ->
      TeslaMate.Repo.transaction(fn ->
        start_date =
          charge
          |> Map.get("chargeStartDateTime")
          |> Timex.parse!("{ISO:Extended}")

        IO.puts(
          "Sync charge for day #{inspect(start_date)} at #{inspect(charge["siteLocationName"])}"
        )

        min = Timex.shift(start_date, seconds: -30)
        max = Timex.shift(start_date, seconds: 30)

        from(
          charging_process in ChargingProcess,
          where: ^min <= charging_process.start_date,
          where: ^max >= charging_process.start_date
        )
        |> Repo.one()
        |> Repo.preload(:address)
        |> case do
          nil ->
            # IO.puts(
            #   "No match for charge for day #{inspect(start_date)} at #{inspect(charge["siteLocationName"])}"
            # )

            sync_charge(charge)

          charging_process ->
            IO.puts(
              "[OK] Charge matches for day #{inspect(charging_process.start_date)} on #{charging_process.address.name}, #{charging_process.address.city}}"
            )
        end

        IO.puts("")
      end)
    end)
  end

  def sync_charge(charge_info) do
    start_date =
      charge_info
      |> Map.get("chargeStartDateTime")
      |> Timex.parse!("{ISO:Extended}")

    end_date =
      charge_info
      |> Map.get("chargeStopDateTime")
      |> Timex.parse!("{ISO:Extended}")

    cost =
      charge_info
      |> Map.get("fees")
      |> Enum.map(fn
        %{"pricingType" => "PAYMENT", "totalBase" => cost} ->
          cost

        %{"pricingType" => "CREDIT", "totalBase" => cost} ->
          cost

        _ ->
          nil
      end)
      |> Enum.reject(&is_nil/1)
      |> List.first()

    if is_nil(cost) do
      IO.puts("No price found for charge on the #{inspect(start_date)}")
    end

    location =
      charge_info
      |> Map.get("siteLocationName")
      |> String.trim()

    %{
      "gps" => %{
        "latitude" => supercharger_latitude,
        "longitude" => supercharger_longitude
      },
      "address" => %{
        "zip" => supercharger_postcode
      }
    } =
      _supercharger =
      Enum.find(@superchargers, fn
        %{"name" => ^location} = supercharger ->
          supercharger

        %{"name" => _other_location} ->
          nil
      end)

    energy_added =
      charge_info
      |> Map.get("fees")
      |> Enum.reduce(0, fn
        %{"pricingType" => "PAYMENT", "usageBase" => kwh}, total_kwh ->
          total_kwh + kwh

        %{"pricingType" => "CREDIT", "usageBase" => kwh}, total_kwh ->
          total_kwh + kwh

        _, total_kwh ->
          total_kwh
      end)

    insert_data(
      start_date,
      end_date,
      cost,
      energy_added,
      supercharger_postcode,
      supercharger_latitude,
      supercharger_longitude,
      location
    )
  end

  def insert_data(
        _start_date,
        _end_date,
        _cost,
        _energy_added,
        _postcode,
        _latitude,
        _longitude,
        location \\ ""
      )

  def insert_data(
        _start_date,
        _end_date,
        _cost,
        _energy_added,
        nil,
        _latitude,
        _longitude,
        location
      ) do
    IO.puts("[ERROR] Required postcode but is missing for `#{location}`")
  end

  def insert_data(
        start_date,
        end_date,
        cost,
        energy_added,
        postcode,
        latitude,
        longitude,
        _location
      ) do
    from(address in Address,
      where: address.postcode == ^postcode
    )
    |> Repo.all()
    |> List.first()
    |> case do
      nil ->
        IO.puts("[WARN] Creating new address for #{postcode}")

        {:ok, %{id: address_id}} =
          TeslaMate.Locations.find_address(%{
            latitude: latitude,
            longitude: longitude
          })

        insert_charge(
          start_date,
          end_date,
          cost,
          energy_added,
          latitude,
          longitude,
          address_id
        )

      %{id: address_id} ->
        insert_charge(
          start_date,
          end_date,
          cost,
          energy_added,
          latitude,
          longitude,
          address_id
        )
    end
  end

  #
  # Private functions
  #

  defp insert_charge(
         start_date,
         end_date,
         cost,
         energy_added,
         latitude,
         longitude,
         address_id
       ) do
    position_attrs = %{
      card_id: 1,
      date: start_date,
      latitude: latitude,
      longitude: longitude
    }

    %Position{id: position_id} =
      _position =
      %Position{car_id: 1}
      |> Position.changeset(position_attrs)
      |> Repo.insert!()

    IO.puts("[OK] New position `#{position_id}`")

    charging_process_attrs = %{
      start_date: start_date,
      end_date: end_date,
      address_id: address_id,
      position_id: position_id,
      duration_min: Timex.diff(end_date, start_date, :minutes),
      charge_energy_added: energy_added,
      charge_energy_used: 0,
      cost: cost
    }

    %{id: charging_process_id} =
      _charging_process =
      %ChargingProcess{car_id: 1}
      |> ChargingProcess.changeset(charging_process_attrs)
      |> Repo.insert!()

    charge_attrs = %{
      date: start_date,
      charge_energy_added: 0,
      charger_voltage: 200,
      charger_power: 0,
      ideal_battery_range_km: 0
    }

    %Charge{charging_process_id: charging_process_id}
    |> Charge.changeset(charge_attrs)
    |> Repo.insert!()

    IO.puts("[OK] New charging process `#{charging_process_id}`")
  end
end
```

**Comment by qgadrian** [comment]
> @qgadrian I am very new to all of this and have Teslamate running using docker but my limited understanding means I am not sure how to implement your code to import the data. I can understand how to add the missing data in to the code but the section on connecting to the Node and then calling the module is just escaping me right now

You can create a new Docker container that includes the sync modules and the charge data, then you can run the sync directly from the container.

Another option, if you have access to the database, is to run the project locally and run the sync module locally using `iex` directly.

Hope that helps.

**Comment by cjkendo** [comment]
> > @qgadrian I am very new to all of this and have Teslamate running using docker but my limited understanding means I am not sure how to implement your code to import the data. I can understand how to add the missing data in to the code but the section on connecting to the Node and then calling the module is just escaping me right now
> 
> You can create a new Docker container that includes the sync modules and the charge data, then you can run the sync directly from the container.
> 
> Another option, if you have access to the database, is to run the project locally and run the sync module locally using `iex` directly.
> 
> Hope that helps.

Thanks.  I think its a bit beyond my skill set :-). I couldn't workout how to create the docker container from your code which then got me stuck going any further.

**Comment by chanove** [comment]
> I created a simple module to synchronize lost/old charges into Teslamate.
> 
> There are two types of charges this module will sync, _superchagers_ and _other charges_.
> ### Syncing module
> 
> The module below does the following:
> 
>     * Retrieves the charge info for the _charges.json_ file
> 
>     * Matches the charging location with the available supercharges in _supercharers.json_
> 
>     * Inserts (if needed) the address for the charging location
> 
>     * Inserts a position for the charging location
> 
>     * Inserts a _dummy charge_ because the Grafana dashboard expects a _charge_process_ to have a _max_voltage_ value set ([see related PR](https://github.com/adriankumpf/teslamate/pull/2589)).
> 
>     * Inserts the _charging process_
> 
> 
> ### Prerequisites
> 
> I recommend you first **backup your data** (if you haven't already) or test this in a safe environment before messing with your database.
> 
> For _superchargers_ you will need to:
> 
>     * Retrieve the full JSON with your charges from [this URL](https://www.tesla.com/teslaaccount/charging/api/history?vin=) and save it in `charges.json`
>       
>       * You can get it by inspecting the web browser [on this page](https://www.tesla.com/teslaaccount/charging)
> 
>     * The list of Tesla superchargers from HERE and save it in `superchargers.json`
>       
>       * Inspect the API responses in [this page](https://supercharge.info/data) to get the JSON
> 
> 
> For _other chargers_ the process is not that automated and you will need to specify by hand the charges to sync:
> 
> ```elixir
> @non_superchargers [
>     %{
>       start_date: DateTime.utc_now,
>       end_date: DateTime.utc_now,
>       cost: 23.57,
>       postcode: "1234",
>       kwh: 23.97,
>       latitude: "37.3940974",
>       longitude: "-122.1523805"
>     }
> ```
> 
> After that, connect to the Teslamate node and call the module:
> 
>     * For **superchargers** `TeslaMate.ChargeHistorySync.sync("./charges.json")`
> 
>     * For **other charges** `TeslaMate.ChargeHistorySync.sync_custom()`
> 
> 
> ### Considerations
> 
> This module might not work for some specific cases (non-matching postcodes, address...). If that is your case, I recommend you fix manually the JSON to match the data or modify the code with whatever your need.
> 

Thanks [qgadrian](https://github.com/qgadrian) for your work.
I would like to use it but can't get a correct superchargers.json file.
Try with https://www.tesla.com/all-locations and https://supercharge.info/service/supercharge/allSites but both are not with the expected format.

**Comment by qgadrian** [comment]
> Thanks [qgadrian](https://github.com/qgadrian) for your work. I would like to use it but can't get a correct superchargers.json file. Try with [tesla.com/all-locations](https://www.tesla.com/all-locations) and [supercharge.info/service/supercharge/allSites](https://supercharge.info/service/supercharge/allSites) but both are not with the expected format.

Looks like the supercharge.info API changed their response, is not longer wrapped with _results_ and it just returns an array.

If that's the case and they didn't change anything else, I think you can simply adapt the example code and change it to:

```elixir
@superchargers "superchargers.json"
                 |> File.read!()
                 |> Jason.decode!()
```

**Comment by chanove** [comment]
Again thanks a lot [qgadrian](https://github.com/qgadrian). Compilation works fine now.

But a database error occurs when launching `TeslaMate.ChargeHistorySync.sync("/tmp/charges.json")` due to a contraint NOT NULL for position_id  in table charging_processes (Postgrex.Error) ERREUR 23502).
Get a message "[OK] New position `99999`" but id 99999 not in table positions ; maybe because it's a transaction (TeslaMate.Repo.transaction).

**Comment by chanove** [comment]
Found solution change
`%{id: charging_process_id} =
      _charging_process =
      %ChargingProcess{car_id: 1}
      |> ChargingProcess.changeset(charging_process_attrs)
      |> Repo.insert!()`

with
`%{id: charging_process_id} =
      _charging_process =
      %ChargingProcess{car_id: 1, position_id: position_id}
      |> ChargingProcess.changeset(charging_process_attrs)
      |> Repo.insert!()`

**Comment by muffstic** [comment]
I've found over the past several months that Teslamate is missing much more data from charges and drives. I did a full backup and restore several times. I even deleted and rebuilt docker and restored Teslamate from a backup but none if it worked. I decided to give Tessie a try and imported my data from Teslamate and all the missing data shows up in Tessie. I'm convinced there is some sort of bug in Teslamate because I have random data missing from 2 different cars and the dates affected are different on both cars.

**Comment by iamhrayr** [comment]
For anyone still looking for a solution, here's how I managed to add a missing charge in TeslaMate:

1. **Backup the Database**
_make sure to back up your TeslaMate database to prevent potential data loss._

2. Add a Location (optional — only if you want the correct address to appear on the dashboard)
_Insert a new row into the `addresses` table with the correct coordinates and relevant location details.
This allows TeslaMate to display the proper address for the charging session._

3. Add a Position (or use one of the existing ones)
_Insert a new row into the `positions` table with latest odometer number.
TeslaMate uses this entry to associate the charging session with an odometer reading._

4. Add the Charging Session
_Insert a new row into the `charging_processes` table.
Make sure to reference the `address_id` and `position_id` from steps 2 and 3.
You can duplicate an existing row as a starting point and update fields like `start_date`, `end_date`, `charging_energy_added`, `address_id`, `position_id`, etc..._

**Comment by kerkeniw** [comment]
Hi @qgadrian, 
I'm new EV User with a tesla and i'm new in tesla univers. Could you explain me how install this module et execute it please.
