### ISSUE TITLE
Send > charge now

### ISSUE THREAD

**Issue by denisjoshua** [adriankumpf/teslamate#795]
**What would you like to be added**:
Is the Tesla Mate read only app please ? 
Can I send MQTT topic to broker in order to tell to Tesla to start to charge now ? 

**Why is this needed**:
Need to start charge Tesla on PV too much production 

Thanks a lot 
Denis

**Comment by ngardiner** [comment]
Yes, TeslaMate is read-only.

Other projects out there do exactly what you're looking for - I maintain a fork of the TWCManager project which reads solar output and adjusts charge rate based on that, as an example of such a project:

https://github.com/ngardiner/TWCManager

I'm sure there are other projects out there doing similar work.

**Comment by denisjoshua** [comment]
Thanks a lot Adrian, 
but I already have make all the flow for charging in the Node-Red. 
But in order to cancel Tesla Integration in Home Assistant, 
I just ask if it's possible to send charge and stop charge command. 

But now I just discover Tesla Api node under Node-Red and it's work great :-) 

Thanks a lot fot the wonderful application.
>You are great :-) 
Denis 
![image](https://user-images.githubusercontent.com/32936800/84979765-89670c80-b130-11ea-89a7-75a7fc71a29d.png)
