### ISSUE TITLE
Question : Can I combine different backup files (.bck)?

### ISSUE THREAD

**Issue by Jade-sje** [adriankumpf/teslamate#796]
I have two backup files (bck) with different periods. 
Can these two be restored to one teslamate? 
 
The teslamate1.bck file that I backed up from January to April 
There is a teslamate2.bck file that backed up data from May to June by installing teslamate again. 
 
I installed a new teslamate and restored teslamate1.bck 1 bck as guided. 
Restored normally. 
 
After that, execute the following command for another period of bck file. 
 
docker-compose exec -T database psql -U teslamate -d teslamate <teslamate2.bck 
 
Then various errors appear as below. 
 
ERROR: type "length" already exists 
... 
ERROR: relation "addresses" already exists 
... 
ERROR: duplicate key value violates unique constraint "addresses_pkey" 
... 
ERROR: multiple primary keys for table "cars" are not allowed 
.... 
....
I wish there was a way to combine bck files with different data.

**Comment by Dulanic** [comment]
What I recommend is manually editing the .bck file and combining them and making sure you dedup the data between the 2 files. The .bck file is just a SQL query.

It's a manual process, but it's doable. The issue you run into is if you dont drop the schema between data restores, it tries to create a ENUM that already exists... you could manually work around that by changing the .bck and wrapping in a IF statement like so:

```
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unit_of_length') THEN
	CREATE TYPE public.unit_of_length AS ENUM (
		'km',
		'mi'
	);
    END IF;
END$$;
```

**Comment by Jade-sje** [comment]
Thank you very much for the advice. 
 
But... it's a very difficult task for me.. 
I should study more.

**Comment by Dulanic** [comment]
Ignore what I said above :) I am having to do the same thing now and yeah, it's not that simple. I'll let you know what I find out.

**Comment by marcel-hi** [comment]
@Dulanic have you had any result? I must also combine two .bck files

**Comment by Jade-sje** [comment]
No,,,Not yet..

**Comment by Jade-sje** [comment]
> @Dulanic have you had any result? I must also combine two .bck files, so I am interested if there is a good way to do it :).


No,,,Not yet..

**Comment by Dulanic** [comment]
No there isn't a good way. I got it done but it was a lot of manual editing of the files. I had to edit drive id's, charging id's etc... since they were duplicated.

**Comment by lisankai93** [comment]
I have the same problem. Anyone solved this?

Wating for your advices! Thanks!

**Comment by sparvata** [comment]
I am in need of a solution for merging two backups too.  I have gathered the commands like below to merge two databased but not sure how the rake option works and how to get docker-compose to execute the rake command.  Not even sure if this is the right sequence to follow

# get a dump with data only and inserts
docker-compose exec -T database pg_dump -a --inserts -U teslamate > t1_inserts.dump

# clean DB and load the t0.dump
docker-compose exec -T database rake db:drop; rake db:create psql database < ./tmp/t0.dump

docker-compose exec -T database psql -U teslamate -d teslamate < ./tmp/t0.dump

finally load the t1_inserts.dump
docker-compose exec -T database psql -U teslamate -d teslamate < t1_inserts.dump
