### ISSUE TITLE
Any clue what snapshot means? Question

### ISSUE THREAD

**Issue by cleanev** [adriankumpf/teslamate#798]
Does anyone know what this screenshot suggests. What health check is this related to, if known? I checked car and there are no notifications or warnings. Just curious

![D608755A-F264-482C-AD99-E4C6D0AAA2C7](https://user-images.githubusercontent.com/45519661/85079856-cb766980-b195-11ea-84b9-48b44d678cf1.jpeg)

**Comment by cleanev** [comment]
Now to something new after what showed up the other day as shown in first post. This weekend, I worked many times to migrate from Pi3b+ to Pi4B with 4GB. Below are the steps I took.

- install docker on new installation on Pi4B
- backup database on Pi3B+
- stop teslamate container on Pi3B+
- scp backup file to Pi4B
- run restore script mentioned at docs.teslamate.org
- restore finishes without any errors
- connecting to IP:4000 on Pi4B ends up with signin that does not allow with attached error

I have tried it 4 separate times without any success. Confirmed Userid/password combination is working by login into website. Currently I have left teslamate running on Pi3B+ and it is communicating with streaming site at Tesla. I may have lost few minutes each time I stopped original docker but other than that I have all the data.

Can someone let me know if the above steps are sufficient to migrate or what steps should I add/remove from above to migrate from Pi3B+ to Pi4B, please?

![0BBA8CC3-17AB-400F-9624-A7FBFA7684DD](https://user-images.githubusercontent.com/45519661/85242316-b5bea980-b40c-11ea-9dde-73425da76ea6.jpeg)

**Comment by adriankumpf** [comment]
"Health check failed" indicates that the car is not available to TeslaMate. The most common reason for this is temporary failures of the Tesla servers. But it can also be a problem on your side (network or DNS issues for example). In any case, more information can be found in the logs. 

Please do not simply post other problems that are not related to the initial issue. Check the logs for more information: `docker-compose logs -f` and open a separate issue if necessary.

**Comment by cleanev** [comment]
Thanks @adriankumpf - sorry for mixing 2 issues. I will open additional issue for migration and try to remove that comment from this thread before closing this thread

I am new to docker in general and your response got me reading more and making sure I can find the real problem. As you suggested I ran the command you presented only to have a very long scrolling log. So read from docker documentation and came up with below command that helped me see that most of the times it is TeslaAPI not connecting while on rare instance DNS issues - 
docker logs -t docker_teslamate_1 | grep "Connection Error" and 
docker logs -t docker_teslamate_1 | grew “Service Temporarily Unavailable“
