### ISSUE TITLE
Status Suspended or schläft ein

### ISSUE THREAD

**Issue by mapchen** [adriankumpf/teslamate#800]
Since approx. 17th june i can not get my tesla x sleeping. It stays in state suspended forever. One of my collegues has the same so i dont think its my setup. Anybody else has seen that issue? I am working with streaming API

**Comment by gpsbabel** [comment]
See if this is a duplicate of https://github.com/adriankumpf/teslamate/issues/818. (Yes, I know that mine might have been a duplicate of yours...)

**Comment by mapchen** [comment]
Issue is solved since last update to 2020.24.6. I think it was a tesla bug
