### ISSUE TITLE
 Bind mount failed

### ISSUE THREAD

**Issue by glynhudson** [adriankumpf/teslamate#802]
Trying to run teslamate for the first time, docker-compose had an error 

```
ERROR: for teslamate  Cannot start service teslamate: Bind mount failed: '/volume2/docker/teslamate/import' does not exists
```

**Expected behavior**

**How to reproduce it (as minimally and precisely as possible)**:

Create `docker-compose.yml` then run `docker-compose up` on Synology DS218+ with Docker version 18.09.8, docker-compose version 1.24.0

**Relevant entries from the logs**

**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by Dulanic** [comment]
It's kind of self evident.... this folder doesn't exist, but its defined in the error....

`'/volume2/docker/teslamate/import' `

**Comment by glynhudson** [comment]
Agh, I'm such a noob. Sorry for time-wasting, it's working now! Very impressed with teslamate :+1:
