### ISSUE TITLE
Drive Details shows no Distance, Energy used and Duration

### ISSUE THREAD

**Issue by Janus00** [adriankumpf/teslamate#803]
In the drive details i can't see the distance, energy used and the duration of my rides.

<img width="1840" alt="Screenshot 2020-06-22 at 12 43 56" src="https://user-images.githubusercontent.com/9690496/85279014-10e0b280-b486-11ea-8240-311c2ac63752.png">

**Comment by Dulanic** [comment]
Need more info, how did you get to the dashboard? That is a internal dashboard only to be viewed via a link from the drive dashboard.

**Comment by Janus00** [comment]
Just by going to this URL:
<myipadress>:3000/d/zm7wN6Zgz/drive-details?orgId=1

**Comment by Dulanic** [comment]
Yeah as stated, this dashboard is a internal dashboard meant to be used via link from the drives dashboard. Direct usage isn't feasible. It needs additional variables that are provided by that dasyboard. EX: of how it links:

https://grafana.domain.com/d/zm7wN6Zgz/drive-details?orgId=1&from=**1592866005000**&to=**1592866270000**&var-car_id=**1**&var-drive_id=**1004**
