### ISSUE TITLE
Streaming: drives / charges missing data points

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#806]
**Describe the bug**

This might not be a specific bug, but maybe more of a dialog. But I have been noticing more and more that with the streaming API I am missing more and more starts to drives and charges. 

Curious how the sleep / pinging behavior changed with the streaming API versus the non-streaming. I _still_ had datapoints missing prior to using the streaming API, but it seems more consistent now that I am missing data at the start of a drive or a charge after previously driving (e.g. while the car is "trying to fall asleep")

**Expected behavior**

Not to be missing data points.

**Relevant entries from the logs**

```
Will monitor and grab logs where I can. 
```

**Screenshots**

**Data**
Will provide as I monitor.

**Environment**

- TeslaMate version: 1.19.4
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian
- User OS & Browser: macOS Safari

**Comment by rshutterbug** [comment]
I’ve noticed this too. Often the first quarter mile of a drive can be missing, but yesterday TeslaMate missed the first 10 miles of a drive, which I’ve never seen before.

**Comment by cwanja** [comment]
This might be entirely related to issues in #571 and even more so, [specifically my issues with regards to 2020.20](https://github.com/adriankumpf/teslamate/issues/571#issuecomment-644125583). Just wanted to see if others are experiencing the same.

**Comment by hindsholm** [comment]
I have just noticed this as well. 10-20 km missing at  the beginning of several drives. I have never seen it before.

**Comment by DrMichael** [comment]
Just got 2020.24.6.1 today...

I had complete drives missing and a lot of errors like

```
teslamate_1  | 09:23:44.652 [error] TeslaApi.Error / 500 – %{
teslamate_1  |   "error" => "upstream internal error",
teslamate_1  |   "error_description" => "",
teslamate_1  |   "response" => nil
teslamate_1  | }
teslamate_1  | 09:23:44.652 car_id=1 [error] Error / :unknown
teslamate_1  | 09:23:52.546 [info] [alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}]
teslamate_1  | 09:24:06.067 car_id=1 [info] Suspending logging
teslamate_1  | 09:30:52.553 [info] [alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_1_api_error}]
teslamate_1  | 10:00:26.269 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 10:12:48.977 [info] Stream.Timeout / 5
teslamate_1  | 10:13:20.061 [info] Stream.Timeout / 6
teslamate_1  | 10:13:51.145 [info] Stream.Timeout / 7
teslamate_1  | 10:14:22.179 [info] Stream.Timeout / 8
teslamate_1  | 10:14:24.882 car_id=1 [info] Driving / Start
teslamate_1  | 10:24:29.173 car_id=1 [info] Driving / Ended / 6 km – 10 min
teslamate_1  | 10:24:29.173 car_id=1 [info] Start / :online
teslamate_1  | 10:26:00.848 car_id=1 [info] Received stream data: :inactive
teslamate_1  | 10:26:31.889 [info] Stream.Timeout / 5
teslamate_1  | 10:27:56.299 car_id=1 [info] Suspending logging
teslamate_1  | 10:32:06.157 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 10:32:37.196 [info] Stream.Timeout / 5
teslamate_1  | 10:37:04.297 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 10:37:35.344 [info] Stream.Timeout / 5
teslamate_1  | 10:38:06.404 [info] Stream.Timeout / 6
```

Just a thought. Since the endpoint of drives is almost always correct, can't we take the endpoint of the previous drive as starting point? Or apply some magic logic? Only very seldom will the starting point of a drive not be equal to the endpoint of the last drive, e.g. being towed away or being on a transporting car... Perhaps those cases can be identified?

**Comment by petariga** [comment]
I've been experiencing this issue as well, however just for the Drives, not for Charges. I miss the beginning of a drive quite often, usually first few minutes. I don't think it is anyhow connected to #571 , but it might be related to #681 (starting LTE after sleep state or switching from wifi to LTE).

**Comment by Vikinge** [comment]
I have same issue after 2020.24.6.1.  When I logged out of teslamate, I am unable to log back in. "Error: unknown"
