### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by danielrobinson95** [adriankumpf/teslamate#81]
Fresh install in docker container and receiving below error in chrome console window on TeslaMate home: 

app-3e0520f22c38662b278d3df0a4160cd5.js?vsn=d:1 WebSocket connection to 'ws://{my_hostname}:4000/live/websocket?vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by thomasantony** [comment]
Same problem here. Running on a linux server.

**Comment by adriankumpf** [comment]
@danielrobinson95  could you fix it by setting the `VIRTUAL_HOST` varable?

**Comment by danielrobinson95** [comment]
yes, that fixed it thank you.
