### ISSUE TITLE
Problem initiating Teslamate after sudden power off

### ISSUE THREAD

**Issue by joanquro** [adriankumpf/teslamate#816]
Hello.

Today I had a power blackout in my home. After this, my Raspberry Pi rebooted and since then I haven't been able to start Teslamate. I have tried docker-compose pull, down, and up and to no avail. If I use systemctl this is what I get:

sudo systemctl status teslamate.service
â teslamate.service - TeslaMate
   Loaded: loaded (/etc/systemd/system/teslamate.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-06-29 20:58:15 CEST; 4s ago
  Process: 25402 ExecStartPre=/usr/src/teslamate/_build/prod/rel/teslamate/bin/teslamate eval TeslaMate.Release.migrate (code=exited, status=200/CHDIR)

Is there anything I can do make it work without starting from scratch?. I have a backup, by the way. I'm not a Linux expert so if I can post any logs or something please tell me. 

Thank you.

**Comment by adriankumpf** [comment]
What do you see when you run this? `sudo journalctl -u teslamate --no-pager -n 1000`

**Comment by joanquro** [comment]
Hello. This is what I see (I copy the last lines). Looks like it is continuously restarting the service. With the power blackout I lost the NAT configuration in my router, that's why I wasn't able to access from outside my home. So it is working now but I don't know if this is ok:

Jun 30 13:50:13 teslamate systemd[1]: teslamate.service: Control process exited, code=exited, status=203/EXEC
Jun 30 13:50:13 teslamate systemd[1]: teslamate.service: Failed with result 'exit-code'.
Jun 30 13:50:13 teslamate systemd[1]: Failed to start TeslaMate.
Jun 30 13:50:18 teslamate systemd[1]: teslamate.service: Service RestartSec=5s expired, scheduling restart.
Jun 30 13:50:18 teslamate systemd[1]: teslamate.service: Scheduled restart job, restart counter is at 10927.
Jun 30 13:50:18 teslamate systemd[1]: Stopped TeslaMate.
Jun 30 13:50:18 teslamate systemd[1]: Starting TeslaMate...
Jun 30 13:50:18 teslamate systemd[10970]: teslamate.service: Failed to execute command: No such file or directory
Jun 30 13:50:18 teslamate systemd[10970]: teslamate.service: Failed at step EXEC spawning /usr/src/teslamate/_build/prod/rel/teslamate/bin/teslamate: No such file or directory
Jun 30 13:50:18 teslamate systemd[1]: teslamate.service: Control process exited, code=exited, status=203/EXEC
Jun 30 13:50:18 teslamate systemd[1]: teslamate.service: Failed with result 'exit-code'.
Jun 30 13:50:18 teslamate systemd[1]: Failed to start TeslaMate.
Jun 30 13:50:23 teslamate systemd[1]: teslamate.service: Service RestartSec=5s expired, scheduling restart.
Jun 30 13:50:23 teslamate systemd[1]: teslamate.service: Scheduled restart job, restart counter is at 10928.
Jun 30 13:50:23 teslamate systemd[1]: Stopped TeslaMate.
Jun 30 13:50:23 teslamate systemd[1]: Starting TeslaMate...
Jun 30 13:50:23 teslamate systemd[10971]: teslamate.service: Failed to execute command: No such file or directory
Jun 30 13:50:23 teslamate systemd[10971]: teslamate.service: Failed at step EXEC spawning /usr/src/teslamate/_build/prod/rel/teslamate/bin/teslamate: No such file or directory
Jun 30 13:50:23 teslamate systemd[1]: teslamate.service: Control process exited, code=exited, status=203/EXEC
Jun 30 13:50:24 teslamate systemd[1]: teslamate.service: Failed with result 'exit-code'.
Jun 30 13:50:24 teslamate systemd[1]: Failed to start TeslaMate.
Jun 30 13:50:29 teslamate systemd[1]: teslamate.service: Service RestartSec=5s expired, scheduling restart.
Jun 30 13:50:29 teslamate systemd[1]: teslamate.service: Scheduled restart job, restart counter is at 10929.
Jun 30 13:50:29 teslamate systemd[1]: Stopped TeslaMate.
Jun 30 13:50:29 teslamate systemd[1]: Starting TeslaMate...
Jun 30 13:50:29 teslamate systemd[10972]: teslamate.service: Failed to execute command: No such file or directory
Jun 30 13:50:29 teslamate systemd[10972]: teslamate.service: Failed at step EXEC spawning /usr/src/teslamate/_build/prod/rel/teslamate/bin/teslamate: No such file or directory
Jun 30 13:50:29 teslamate systemd[1]: teslamate.service: Control process exited, code=exited, status=203/EXEC
Jun 30 13:50:29 teslamate systemd[1]: teslamate.service: Failed with result 'exit-code'.
Jun 30 13:50:29 teslamate systemd[1]: Failed to start TeslaMate.

**Comment by adriankumpf** [comment]
This is the crucial clue to where the problem is: `/usr/src/teslamate/_build/prod/rel/teslamate/bin/teslamate: No such file or directory`. I don't know if has been lost, but you have to make sure that all data is available at the given location. You may have to go through the installation process again. Hopefully the vehicle data is still available …

**Comment by joanquro** [comment]
Thanks.

How can I start from scratch?. I have a backup, no problem with that. I mean, how can I erase every bit of the installation and begin with docker installation again?.

**Comment by adriankumpf** [comment]
Wait, you have installed TeslaMate manually and now want to you run it using Docker? In that case stop and disable the systemd service (`sudo systemd stop teslamate && sudo systemd disable teslamate`), follow the [docker installation](https://docs.teslamate.org/docs/installation/docker) and [restore the backup](https://docs.teslamate.org/docs/maintenance/backup_restore).

**Comment by joanquro** [comment]
No, I have always used Docker.

**Comment by adriankumpf** [comment]
OK then you need neither systemd nor the files at `/usr/src/teslamate`.
