### ISSUE TITLE
Question - Any way to import data files?

### ISSUE THREAD

**Issue by sumitkgarg** [adriankumpf/teslamate#817]
Hello - I just found out about this project yesterday and got it all set up and running, and it is awesome! Thanks.

I have a self-developed project that has been collecting /data/ endpoint JSON for about 9 months now. Is it possible to import these files into the TeslaMate application? I am happy to do some manual work to make it work. Just looking for some pointers. Thanks!

**Comment by adriankumpf** [comment]
This is only possible via CSV files formatted as TeslaFi exports. If you can transform the collected data into this format, you can import it (here is an example:: https://github.com/adriankumpf/teslamate/tree/master/test/fixtures/import/01_complete). Note, however, that data with sufficiently high resolution is required: https://github.com/adriankumpf/teslamate/issues/452
