### ISSUE TITLE
F/W 2020.24.6.1 and 'stay unlocked at home' inhibits sleeping

### ISSUE THREAD

**Issue by gpsbabel** [adriankumpf/teslamate#818]
Since upgrading to this version, my Model 3 hasn't slept while it's at home. I'm using the new "stay unlocked at home" setting.  Looking in the logs, I think this generates a warning that it's Unlocked which loops back to a GET / which keeps the API up which prevents it from sleeping.

**Expected behavior**

Deep, glorious sleep.

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade to current F/W.  I haven't yet A/B tested this theory. I will.

**Relevant entries from the logs**
```
teslamate_1  | 19:07:27.627 car_id=1 [warn] Unlocked ...
teslamate_1  | 19:07:58.646 car_id=1 [warn] Unlocked ...
teslamate_1  | 19:08:29.986 car_id=1 [warn] Unlocked ...
teslamate_1  | 19:08:55.170 [info] GET /
teslamate_1  | 19:08:55.190 [info] Sent 200 in 20ms
teslamate_1  | 19:09:01.790 car_id=1 [warn] Unlocked ...
teslamate_1  | 19:09:33.044 car_id=1 [warn] Unlocked ...
teslamate_1  | 19:10:03.571 car_id=1 [warn] Unlocked ...
```
This 'Unlocked' state os observed every 90 seconds or so. It's my theory that Teslamate is keeping the car awake because it's not accustomed to it being on home WiFI AND unlocked.

**Screenshots**

**Data**

N/A

**Environment**
It was observed on the verion  (1.19.1 maybe?) that I'd been running for many weeks. I just updated and restarted today (July 1)  with 1.19.4 to see if an update helped.

It's on a Pi 3, where it's been for a while.

I think (I could be wrong) the key variable is the addition of "keep unlocked" state.

**Comment by adriankumpf** [comment]
Go to `Setting` -> `Requirements` -> Uncheck `Vehicle must be locked` and enjoy deep, glorious sleep again ;)

**Comment by gpsbabel** [comment]
Doink. That's embarrassing. Thank you.

falling asleep for 5 min
Sweet slumber returns!

As that feature rolls out in the firmware, I suspect lots of users are
going to be nailed by this, not quite recognize the problem, and do a
generic rage/blame/hate that "TeslaMate eated muh battery".

Lots of us in areas with garages that lock are looking forward to keeping
their cars unlocked, but locked safely inside our garages. It's default off
in the firmware.

It may be time to reconsider that setting or to add a "Forced awake by
'Vehicle must be locked' setting'" on that main screen or something.


It's also possible that I'm the dumbest TeslaMate user, but I'm still a
fan. :-) Thanx for being awesome.

RJL

**Comment by adriankumpf** [comment]
No worries. I can image that it could lead to more confusion in the future.

> It may be time to reconsider that setting or to add a "Forced awake by
'Vehicle must be locked' setting'" on that main screen or something.

 Displaying a message on the main screen it is a good idea! Coming soon™

**Comment by gpsbabel** [comment]
Awesome. Thanks!
