### ISSUE TITLE
Vehicle Name in Grafana

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#819]
I was assuming if I changed my vehicles name it would also be reflected in Grafana. All charts show the old vehicle name. After a drive will it update in the database or do we have to manually change the vehicle name? If it is manually done how is that performed?

Thanks!

**Comment by natrlhy** [comment]
Reached out to users in the Discord channel and this did the trick:
1. cd to the directory where the .yml file is for the docker install
2. Run `docker-compose exec database psql -U teslamate -d teslamate` (My database container is called db so use the DB name accordingly).
3. `UPDATE cars SET name='new car name' WHERE id=1;` replacing “new car name” with the new name
4. Exit out of the DB and teslamate
5. Check Grafana and the new Car name should be updated

@adriankumpf is there a way to set it so TeslaMate automatically updates the car name when one changes the name?

**Comment by spacecosmos** [comment]
Also, it would be great if there was a way to prioritize the way multiple cars are shown. Choose a default car. 

For example:
I log two cars, my parents and my own. My parents Model 3 has a car name that is alphabetically before my Model X is. But I'm more interested in TeslaMate showing my car details first at all times. Not theirs.

**Comment by adriankumpf** [comment]
> @adriankumpf is there a way to set it so TeslaMate automatically updates the car name when one changes the name of their car/vehicle? Thanks!

This actually works automatically. However, it may take a while before the change is recognized. A restart should speed up this process. But it's nice that you were able to find an alternative solution 👍
