### ISSUE TITLE
Question: Two teslamate loggers at the same time

### ISSUE THREAD

**Issue by ki0w3** [adriankumpf/teslamate#822]
What are the problems that can occur with it?
For exmaple - one local on a rasp and one in the cloud via Google compute engine?

**Comment by spacecosmos** [comment]
There shouldn't be.

**Comment by spacecosmos** [comment]
There shouldn't be a problem. You can have multiple loggers to the same car(s), if you want. (Not exactly sure _why_ you need it though?)

**Comment by DrMichael** [comment]
There isn't. I am running three in parallel for safety reasons...

**Comment by cwanja** [comment]
> There isn't. I am running three in parallel for safety reasons...

Assume you can not use the streaming API as other issues have shown that is only can feed data to a single end-point at a time.

**Comment by ki0w3** [comment]
> > There isn't. I am running three in parallel for safety reasons...
> 
> Assume you can not use the streaming API as other issues have shown that is only can feed data to a single end-point at a time.

This was the result I got when I initially tried it a month ago.
I checked both my teslamate instances and they were not synced up.
They did not contain the same data.
I'll just make sure I back up my cloud instance.
Thanks!
