### ISSUE TITLE
Voltage at Supercharger

### ISSUE THREAD

**Issue by tomS3210** [adriankumpf/teslamate#827]
Hello,

On the charging table the voltage is always **2 Volts for a Supercharge**. No issue with a AC charge.
Could it be possible to display the correct voltage or is it a Tesla API issue ?

<img width="973" alt="Charging voltage Supercharger" src="https://user-images.githubusercontent.com/949584/86966386-621cc180-c169-11ea-8444-211ad069b274.png">

Thanks :-)

**Comment by adriankumpf** [comment]
Unfortunately, there is nothing to be done but to hide these values. They are reported by the Tesla API exactly like this.

**Comment by tomS3210** [comment]
Ok thank you for your answer.
So maybe the best thing to do is to hide it during the DC charge ?

**Comment by ninj4s** [comment]
It's visible during at V3 superchargers when you use a CCS adapter (S/X,) and other CCS/CHAdeMO chargers.

**Comment by JanBe** [comment]
> It's visible at V3 superchargers when you use a CCS adapter (S/X,) and other CCS/CHAdeMO chargers.

Just to confirm that it seems to only work with the adapter for S/X: I just checked V3 charging data for my CCS Model 3, it's also at 2V.

![Bildschirmfoto 2020-07-23 um 17 05 11](https://user-images.githubusercontent.com/956051/88302895-afbb3180-cd06-11ea-9286-c5245f4568fb.png)
