### ISSUE TITLE
Default geo-fences seem to small

### ISSUE THREAD

**Issue by kimma** [adriankumpf/teslamate#833]
**Describe the bug**

The Geo Fences for known charging locations seems to be too small.
Ex. charging on the "edge" superchargers of a Tesla Supercharger will not be registered as a Tesla Supercharger but instead the nearest street address.

**Expected behavior**

When TeslaMate registers a charging session it should always register to the nearest charging location even if it is not registered inside the geo fence (with of course an acceptable max-distance, ex. 300m or something).

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to tesla supercharger
2. Charge at the very edge of the supercharger (as far away as possible from the center according to the map)
3. Observe that the charging session will be linked to the nearest street address instead of the supercharger itself

**Screenshots**

Charging at edge of Tesla Supercharger. Note the Street Address instead of correctly identified Tesla Charger
![image](https://user-images.githubusercontent.com/1186008/87139524-6ac3e380-c2a0-11ea-84e0-c1d991dafa40.png)

Charging in the center of Tesla Supercharger. Note the correctly identified Tesla Supercharger.
![image](https://user-images.githubusercontent.com/1186008/87139567-80390d80-c2a0-11ea-9811-13ffa12683d8.png)

**Environment**

- TeslaMate version: 1.19.4
- Type of installation: Kubernetes (Docker / containerd)
- OS TeslaMate is installed on: Ubuntu
- User OS & Browser: Mac OS, Chrome

**Comment by adriankumpf** [comment]
The thing is, there are no default geo-fences. The location data comes from OpenStreetMap. So if a charger was not correctly detected, the intended solution is to create a geo-fence yourself (e.g. in your case "Tesla Rugtvedt Supercharger").

**Comment by kimma** [comment]
Would it be possible to utilize https://openchargemap.org/ to map charges to a nearby charger instead of letting OpenStreetMap automatically try to match you with the closest POI?

**Comment by kimma** [comment]
> Would it be possible to utilize https://openchargemap.org/ to map charges to a nearby charger instead of letting OpenStreetMap automatically try to match you with the closest POI (which often could turn out to not be a charger)?

https://openchargemap.org/site/develop/api#POI

distance | return results based on specified distance from specified latitude/longitude
distanceunit | Miles or KM | Miles




distance | return results based on specified distance from specified latitude/longitude | (blank)
-- | -- | --
distanceunit | Miles or KM | Miles
