### ISSUE TITLE
Reset grafana admin password

### ISSUE THREAD

**Issue by NHO123** [adriankumpf/teslamate#834]
Hello, I am not sure if there is a problem or the mistake is simply my self.

I have Teslamate intalled with Docker on a vultr.com ubuntu virtuel server using this fine guide https://docs.teslamate.org/docs/installation/docker 

Everything has run fine for 5-6 weeks, but last week I was logged in and I changed the standard Grafana admin/admin login to something I believe I can remember, but now I cant login to Grafana ( There is no problem loggin into Teslamate front, but when I click to see stats in grafana I am prompted for a login as I should, but it want let me in )

Is there a generel issue or is it me who have made the problem ?

Is there any way to reset Grafana admin login in order to get access ?

**Comment by adriankumpf** [comment]
Try this:

```￼
docker-compose exec grafana grafana-cli admin reset-admin-password
```

Source: https://grafana.com/docs/grafana/latest/administration/cli/#reset-admin-password

**Comment by NHO123** [comment]
Thx- worked perfect
