### ISSUE TITLE
TeslaFi Import works on the first go at it, but if you try and import again, it doesn't work even with new months/CSVs of data.

### ISSUE THREAD

**Issue by TMahlmann** [adriankumpf/teslamate#836]
I have ~11 months of data to import from TeslaFi into my TeslaMate server. I did a test import to make sure it all looked well and good before I went for the other 10. That worked. The other 10+ however did not. The 2nd month ticked a green checkmark (but didnt show up in Grafana) while the rest of the months displayed a circular blue icon with a dot in the middle.

**Describe the bug**

Importing TeslaFi data only works one time. I only have enough RAM on my Pi to do a few months at a time. Instead of buying a new Pi, I would like to be able to do a few months (1-3) then a few more after that (4-6) so the pi doesn't crash out mid month on me.

**Expected behavior**

I would expect the subsequent imports to work just as the first few, in batches. But anything after the 1st import batch fails/blue icons.

**How to reproduce it (as minimally and precisely as possible)**:

Try importing a month, then try importing another month after it. (Say June, then after that finishes, try July etc both by themselves.

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

[Link to screenshots](https://imgur.com/a/HtGWASq)

**Data**

<!--
If applicable, add an export of the data for the given period.
**Environment**

- TeslaMate version: latest
- Type of installation: Docker
- OS TeslaMate is installed on: Raspberry Pi
- User OS & Browser: Safari
- Others:

**Comment by GtHbbrr** [comment]
You will probably have more succes when you install Teslamate on Google Cloud using the excellent instructions on Teslaev.co.uk. Choose a more powerfull instance than the f1-micro and you can have all the RAM you want.

**Comment by GtHbbrr** [comment]
Then after you imported from Teslafi you can create a backup and transfer that backup to your pi

**Comment by adriankumpf** [comment]
You'll have to import all data at once. The documentation contains a small note why the other files were skipped after your first test import (hence the blue arrow):

```
If there is an overlap between the already existing TeslaMate and TeslaFi data, only the data prior to the first TeslaMate data will be imported.
```

**Comment by verygreen** [comment]
Kind of related ,want a separate PR?

I had an import failure in the middle of migration and since the process started from the earliest entry - no way to continue it. So it seems teslamate import should automatically be working backwards in time in the imports, not forward like it does now?

**Comment by adriankumpf** [comment]
In this case the backup should ideally be restored. The reason why data is imported in that order is that the exported CSV files virtually contain the raw data from the Tesla API. In order to interpret them correctly, they cannot be imported in pieces, in any order. This could lead to more or less wrong data or subtle bugs.

**Comment by jtamboli** [comment]
If you’re careful and comfortable building your own image, you can remove the date check from the import code. This means you can easily get duplicates, though, so make sure your CSV files don’t contain data you’ve already imported.

```patch
diff --git a/lib/teslamate/import/fake_api.ex b/lib/teslamate/import/fake_api.ex
index 2ef8e80..471821b 100644
--- a/lib/teslamate/import/fake_api.ex
+++ b/lib/teslamate/import/fake_api.ex
@@ -53,12 +53,6 @@ defmodule TeslaMate.Import.FakeApi do
         send(state.pid, :done)
         {:noreply, state}
 
-      {{:ok, %Vehicle{drive_state: %Drive{timestamp: ts}}}, state}
-      when ts >= date_limit ->
-        send(state.pid, {:done, state.current_chunk})
-        send(state.pid, :done)
-        {:noreply, state}
-
       {{:ok, %Vehicle{}} = event, state} ->
         {:reply, event, state}
     end
```

**Comment by roelvandermade** [comment]
> If you’re careful and comfortable building your own image, you can remove the date check from the import code. This means you can easily get duplicates, though, so make sure your CSV files don’t contain data you’ve already imported.
> 
> ```diff
> diff --git a/lib/teslamate/import/fake_api.ex b/lib/teslamate/import/fake_api.ex
> index 2ef8e80..471821b 100644
> --- a/lib/teslamate/import/fake_api.ex
> +++ b/lib/teslamate/import/fake_api.ex
> @@ -53,12 +53,6 @@ defmodule TeslaMate.Import.FakeApi do
>          send(state.pid, :done)
>          {:noreply, state}
>  
> -      {{:ok, %Vehicle{drive_state: %Drive{timestamp: ts}}}, state}
> -      when ts >= date_limit ->
> -        send(state.pid, {:done, state.current_chunk})
> -        send(state.pid, :done)
> -        {:noreply, state}
> -
>        {{:ok, %Vehicle{}} = event, state} ->
>          {:reply, event, state}
>      end
> ```

Hi @jtamboli , Interesting, this bit of code seems to have changed recently, would you mind checking the same functionality in the newer code to disable the check? I am kind of need of exactly this at the moment :-) I am using 1.21.5.

Thanks!
Roel.

**Comment by jtamboli** [comment]
@roelvandermade I think you'll want to delete the same lines of code, more or less:

```patch
diff --git a/lib/teslamate/import/fake_api.ex b/lib/teslamate/import/fake_api.ex
index 364fdd2..d450ab2 100644
--- a/lib/teslamate/import/fake_api.ex
+++ b/lib/teslamate/import/fake_api.ex
@@ -59,11 +59,6 @@ defmodule TeslaMate.Import.FakeApi do
         processing_complete(state)
         {:noreply, state}
 
-      {:event, %Vehicle{} = vehicle, state}
-      when vehicle.drive_state.timestamp >= state.date_limit ->
-        processing_complete(state)
-        {:noreply, state}
-
       {:event, %Vehicle{} = vehicle, state} ->
         {:reply, {:ok, vehicle}, state}
     end
```

I haven't tested that myself, but I think it's right.

**Comment by roelvandermade** [comment]
Hi @jtamboli 

> @roelvandermade I think you'll want to delete the same lines of code, more or less:
> 
> ```diff
> diff --git a/lib/teslamate/import/fake_api.ex b/lib/teslamate/import/fake_api.ex
> index 364fdd2..d450ab2 100644
> --- a/lib/teslamate/import/fake_api.ex
> +++ b/lib/teslamate/import/fake_api.ex
> @@ -59,11 +59,6 @@ defmodule TeslaMate.Import.FakeApi do
>          processing_complete(state)
>          {:noreply, state}
>  
> -      {:event, %Vehicle{} = vehicle, state}
> -      when vehicle.drive_state.timestamp >= state.date_limit ->
> -        processing_complete(state)
> -        {:noreply, state}
> -
>        {:event, %Vehicle{} = vehicle, state} ->
>          {:reply, {:ok, vehicle}, state}
>      end
> ```
> 
> I haven't tested that myself, but I think it's right.

This instantly fixed my issue (having a gap of 1 week in data and unable to import this from CSV).

thanks a lot!

Roel.
