### ISSUE TITLE
Teslamate waiting for database post database upgrade / restore

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#837]
**Describe the bug**

Tried to upgrade postgres today from 11 to 12 and followed the guide listed in the docs website.
Issues since 
- TeslaMate web interface will not display
- Grafana dashboards do not load, error:
```
Templating init failed
dial tcp: lookup database on 127.0.0.11:53: no such host
```

**Expected behavior**

Everything working, just PostgreSQL upgrade from version 11 to 12.

**Relevant entries from the logs**

```
Attaching to teslamate_teslamate_1
[36mteslamate_1  |[0m waiting for postgres at database:5432 (2sec)
[36mteslamate_1  |[0m waiting for postgres at database:5432 (4sec)
[36mteslamate_1  |[0m waiting for postgres at database:5432 (8sec)
[36mteslamate_1  |[0m waiting for postgres at database:5432 (16sec)
[36mteslamate_1  |[0m waiting for postgres at database:5432 (32sec)
[36mteslamate_1  |[0m waiting for postgres at database:5432 (64sec)
[36mteslamate_1  |[0m waiting for postgres at database:5432 (128sec)
[36mteslamate_1  |[0m waiting for postgres at database:5432 (256sec)
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version: v19.4
- Type of installation: Docker, Raspberry Pi
- OS TeslaMate is installed on: August/2019
- User OS & Browser: Safari, macOS

**Comment by cwanja** [comment]
I have also tried to upgrade my YML file from version 2 to version 3. Getting an issue with docker-compose version even though it is the default from the Docs and checked against Docker's website.

Tried downgrading from 12 to 11 in the YML file to no luck. Does not look like docker-compose is starting the Postgres process. 
`pi@teslapi:~/Documents/teslamate $ docker-compose ps
       Name                 Command                State                 Ports        
-------------------------------------------------------------------------------------
teslamate_db_1        docker-               Exit 1                                    
                      entrypoint.sh                                                   
                      postgres                                                        
teslamate_grafana_1   /run.sh               Up                    0.0.0.0:3000->3000/ 
                                                                  tcp                 
teslamate_mosquitto   /docker-              Up                    0.0.0.0:1883->1883/ 
_1                    entrypoint.sh /usr                          tcp, 0.0.0.0:9001-> 
                      ...                                         9001/tcp            
teslamate_teslamate   /sbin/tini --         Up                    0.0.0.0:4000->4000/ 
_1                    /bin/sh /ent ...                            tcp                 
pi@teslapi:~/Documents/teslamate $ 
`

**Comment by cwanja** [comment]
Just continuing the troubleshooting here. If I tail the database logs after I drop the database [per step 3](https://docs.teslamate.org/docs/maintenance/upgrading_postgres) I can see it gets initialized.
```
pi@teslapi:~/Documents/teslamate $ docker-compose logs -f db
Attaching to teslamate_db_1
db_1         | The files belonging to this database system will be owned by user "postgres".
db_1         | This user must also own the server process.
db_1         | 
db_1         | The database cluster will be initialized with locale "en_US.utf8".
db_1         | The default database encoding has accordingly been set to "UTF8".
db_1         | The default text search configuration will be set to "english".
db_1         | 
db_1         | Data page checksums are disabled.
db_1         | 
db_1         | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1         | creating subdirectories ... ok
db_1         | selecting dynamic shared memory implementation ... posix
db_1         | selecting default max_connections ... 100
db_1         | selecting default shared_buffers ... 128MB
db_1         | selecting default time zone ... Etc/UTC
db_1         | creating configuration files ... ok
db_1         | running bootstrap script ... ok
db_1         | performing post-bootstrap initialization ... ok
db_1         | syncing data to disk ... ok
db_1         | 
db_1         | 
db_1         | Success. You can now start the database server using:
db_1         | 
db_1         | initdb: warning: enabling "trust" authentication for local connections
db_1         | You can change this by editing pg_hba.conf or using the option -A, or
db_1         | --auth-local and --auth-host, the next time you run initdb.
db_1         |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1         | 
db_1         | waiting for server to start....2020-07-17 02:20:41.151 UTC [47] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 8.3.0-6) 8.3.0, 32-bit
db_1         | 2020-07-17 02:20:41.157 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2020-07-17 02:20:41.222 UTC [48] LOG:  database system was shut down at 2020-07-17 02:20:36 UTC
db_1         | 2020-07-17 02:20:41.241 UTC [47] LOG:  database system is ready to accept connections
db_1         |  done
db_1         | server started
db_1         | CREATE DATABASE
db_1         | 
db_1         | 
db_1         | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1         | 
db_1         | waiting for server to shut down....2020-07-17 02:20:42.780 UTC [47] LOG:  received fast shutdown request
db_1         | 2020-07-17 02:20:42.794 UTC [47] LOG:  aborting any active transactions
db_1         | 2020-07-17 02:20:42.818 UTC [47] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db_1         | 2020-07-17 02:20:42.819 UTC [49] LOG:  shutting down
db_1         | 2020-07-17 02:20:42.902 UTC [47] LOG:  database system is shut down
db_1         |  done
db_1         | server stopped
db_1         | 
db_1         | PostgreSQL init process complete; ready for start up.
db_1         | 
db_1         | 2020-07-17 02:20:43.050 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 8.3.0-6) 8.3.0, 32-bit
db_1         | 2020-07-17 02:20:43.051 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2020-07-17 02:20:43.051 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2020-07-17 02:20:43.080 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2020-07-17 02:20:43.135 UTC [65] LOG:  database system was shut down at 2020-07-17 02:20:42 UTC
db_1         | 2020-07-17 02:20:43.159 UTC [1] LOG:  database system is ready to accept connections
```

However, when I try the restore - nothing. No logs get written or even attempted to restore.

**Comment by cwanja** [comment]
I think I got it. Not sure if remaining the bck to sql worked or if removing the -d flag worked. But it is currently outputting every line as it imports :( so it is taking a while. We shall see. More to come :) 🍿

**Comment by cwanja** [comment]
I let it run overnight without the -T flag and it is still restoring seven plus hours later. It looks like it is on record 13000 of 400000 in the charging table. 

This does not seem normal.

**Comment by cwanja** [comment]
This it might be stuck. Has not moved in hours from importing record ID 20201. Damn 2020 😉

**Comment by cwanja** [comment]
**Update** finally got the database upgraded and restore with the following command:
```
docker exec -i teslamate_db_1 psql -U teslamate -d teslamate < ./20200714_teslamate.sql
```

Upgraded:
```
pi@teslapi:~/Documents/teslamate $ docker-compose exec db psql teslamate teslamatepsql (12.3 (Debian 12.3-1.pgdg100+1))
Type "help" for help.

teslamate=# \dt
                List of relations
 Schema |        Name        | Type  |   Owner   
--------+--------------------+-------+-----------
 public | addresses          | table | teslamate
 public | car_settings       | table | teslamate
 public | cars               | table | teslamate
 public | charges            | table | teslamate
 public | charging_processes | table | teslamate
 public | drives             | table | teslamate
 public | geofences          | table | teslamate
 public | positions          | table | teslamate
 public | schema_migrations  | table | teslamate
 public | settings           | table | teslamate
 public | states             | table | teslamate
 public | tokens             | table | teslamate
 public | updates            | table | teslamate
(13 rows)
```
However, the container still says it is waiting for the database. From the teslamate logs:
```
pi@teslapi:~/Documents/teslamate $ docker-compose logs -f teslamate
Attaching to teslamate_teslamate_1
teslamate_1  | waiting for postgres at database:5432 (2sec)
teslamate_1  | waiting for postgres at database:5432 (4sec)
teslamate_1  | waiting for postgres at database:5432 (8sec)
teslamate_1  | waiting for postgres at database:5432 (16sec)
teslamate_1  | waiting for postgres at database:5432 (32sec)
teslamate_1  | waiting for postgres at database:5432 (64sec)
```

Any new thoughts?

**Comment by cwanja** [comment]
Have to thank @Dulanic for his help in the Discord server. Got it up and running. Seems somewhere in the yaml file db was replaced with database. Got it back to db and we are cooking again.

**Comment by ronnyandre** [comment]
I have the same issue as you did. However, which YAML file had this `db` reference?

**Comment by cwanja** [comment]
> I have the same issue as you did. However, which YAML file had this `db` reference?

I only have a single YAML file and the database server in there was reflecting `database` as opposed to `db`.
