### ISSUE TITLE
Websocket not reconnecting mid-drive

### ISSUE THREAD

**Issue by MaxG88** [adriankumpf/teslamate#838]
**Describe the bug**

Before getting to the bug, I'd like to make sure I'm not mistaken about how getting data from the Tesla API works (for TeslaMate).
I'm assuming that it defaults to websockets, and falls back to polling if it doesn't work.

I've noticed that when I start a drive and websockets are unavailable for whatever reason (I do not have logs, but I could reproduce if they'd help), the entire drive is recorded by pulling from the API. It happens when I start a drive in a location with poor connectivity.
I'm assuming no attempt is made to reconnect to the websocket API mid-drive in this case since even if I go through places with perfect 4G connectivity, it keeps polling and doesn't switch to websockets.

I've been keeping an eye on commits and while I noticed a few of them related to websockets, I'm not 100% sure if it's already been fixed. This one in particular: https://github.com/adriankumpf/teslamate/commit/9311cb41710543866d8ef0ae9580225de14bba54.

**Expected behavior**

TeslaMate should attempt to reconnect to the websockets API mid-drive even it was unavailable when the drive started.

**How to reproduce it (as minimally and precisely as possible)**:

Start a drive in an area with no or poor connectivity and drive to an area with good connectivity (to confirm that connectivity isn't the issue).

**Relevant entries from the logs**

I don't have logs on hand but should be able to reproduce it in the coming weeks and get the logs.

**Environment**

- TeslaMate version: 1.19.4
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu 16.04

**Comment by adriankumpf** [comment]
>  I'm assuming that it defaults to websockets, and falls back to polling if it doesn't work.

Polling continues even if streaming is enabled. The only difference is the frequency with which polling takes place (no streaming = higher polling frequency).

TeslaMate is actually quite aggressive with reconnects. I've seen a similar behavior with some drives, though, where reconnecting just did not succeed. 

During the last weeks I have tried different strategies (not released yet but available on the master branch and as a developer image) . But sometimes it is simply not possible to get data from the car even if a connection is successfully established. In this case a reconnect will be done automatically after a while. But if the Tesla API or the car does not send any data (for whatever reason), TeslaMate cannot do anything.

You can try the current developer version: the `teslamate/teslamate:edge` and `teslamate/grafana:edge` Docker images always include the latest changes from the master branch.

**Comment by MaxG88** [comment]
Hey,

I was able to reproduce it on the latest 1.20.0-dev version.
Here are the logs for a drive:
`13:52:50.878 car_id=1 [info] Start / :online
13:53:37.415 car_id=1 [info] Driving / Start
13:55:20.310 [warn] Too many disconnects …
13:55:20.310 car_id=1 [info] Creating new connection …
13:55:20.310 car_id=1 [info] Disconnecting ...
13:55:20.319 car_id=1 [info] Connecting ...
13:55:30.867 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
13:55:41.414 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
13:55:51.969 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
13:56:02.457 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:01:50.595 [warn] Too many disconnects …
14:01:50.595 car_id=1 [info] Creating new connection …
14:01:50.595 car_id=1 [info] Disconnecting ...
14:01:50.601 car_id=1 [info] Connecting ...
14:02:01.111 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:02:11.621 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:02:22.132 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:02:32.641 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:08:19.726 [warn] Too many disconnects …
14:08:19.726 car_id=1 [info] Creating new connection …
14:08:19.726 car_id=1 [info] Disconnecting ...
14:08:19.732 car_id=1 [info] Connecting ...
14:08:30.272 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:08:40.781 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:08:51.325 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:09:01.871 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:14:48.362 [warn] Too many disconnects …
14:14:48.362 car_id=1 [info] Creating new connection …
14:14:48.362 car_id=1 [info] Disconnecting ...
14:14:48.371 car_id=1 [info] Connecting ...
14:14:58.843 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:15:09.395 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:15:19.941 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:15:30.455 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:21:16.821 [warn] Too many disconnects …
14:21:16.821 car_id=1 [info] Creating new connection …
14:21:16.821 car_id=1 [info] Disconnecting ...
14:21:16.830 car_id=1 [info] Connecting ...
14:21:27.373 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:21:37.880 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:21:48.422 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:21:58.934 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:27:45.409 [warn] Too many disconnects …
14:27:45.410 car_id=1 [info] Creating new connection …
14:27:45.410 car_id=1 [info] Disconnecting ...
14:27:45.419 car_id=1 [info] Connecting ...
14:27:55.973 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:28:06.480 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:28:17.052 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:28:27.568 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:34:14.230 [warn] Too many disconnects …
14:34:14.230 car_id=1 [info] Creating new connection …
14:34:14.231 car_id=1 [info] Disconnecting ...
14:34:14.240 car_id=1 [info] Connecting ...
14:34:24.755 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:34:35.263 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:34:45.773 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:34:56.283 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:40:42.859 [warn] Too many disconnects …
14:40:42.859 car_id=1 [info] Creating new connection …
14:40:42.859 car_id=1 [info] Disconnecting ...
14:40:42.868 car_id=1 [info] Connecting ...
14:40:53.418 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:41:03.928 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:41:14.456 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:41:14.887 [info] control:hello – 0
14:41:24.972 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:43:31.393 car_id=1 [info] Driving / Ended / 7 km – 50 min
14:43:31.393 car_id=1 [info] Start / :online
14:44:17.767 car_id=1 [info] Driving / Start
14:47:12.039 [warn] Too many disconnects …
14:47:12.039 car_id=1 [info] Creating new connection …
14:47:12.039 car_id=1 [info] Disconnecting ...
14:47:12.041 car_id=1 [info] Connecting ...
14:47:22.557 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:47:33.098 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:47:43.642 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:47:54.163 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
14:53:40.848 [warn] Too many disconnects …
14:53:40.848 car_id=1 [info] Creating new connection …
14:53:40.848 car_id=1 [info] Disconnecting ...
14:53:40.857 car_id=1 [info] Connecting ...
14:53:51.405 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
14:54:01.925 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
14:54:12.439 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
14:54:22.926 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
15:00:09.245 [warn] Too many disconnects …
15:00:09.245 car_id=1 [info] Creating new connection …
15:00:09.246 car_id=1 [info] Disconnecting ...
15:00:09.255 car_id=1 [info] Connecting ...
15:00:19.788 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
15:00:30.273 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
15:00:40.781 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
15:00:51.328 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
15:06:37.917 [warn] Too many disconnects …
15:06:37.918 car_id=1 [info] Creating new connection …
15:06:37.918 car_id=1 [info] Disconnecting ...
15:06:37.927 car_id=1 [info] Connecting ...
15:06:48.441 [info] Connction was closed (a:1|t:1|d:0). Reconnecting …
15:06:58.972 [info] Connction was closed (a:1|t:2|d:0). Reconnecting …
15:07:09.518 [info] Connction was closed (a:1|t:3|d:0). Reconnecting …
15:07:20.027 [info] Connction was closed (a:1|t:4|d:0). Reconnecting …
15:13:07.006 [warn] Too many disconnects …
15:13:07.006 car_id=1 [info] Creating new connection …
15:13:07.006 car_id=1 [info] Disconnecting ...
15:13:07.018 car_id=1 [info] Connecting ...
15:13:15.379 car_id=1 [info] Driving / Ended / 2 km – 29 min
`
I'm thinking there's probably somewhere I should've set the logs to DEBUG, because there doesn't seem to be much info there.
