### ISSUE TITLE
Number of Updates wrongly displayed for multiple cars

### ISSUE THREAD

**Issue by lemmerk** [adriankumpf/teslamate#839]
**Describe the bug**

Number of updates wrongly displayed for multiple cars due to missing car_id in query.

**Expected behavior**

Show the correct number of updates for individual cars.

**How to reproduce it (as minimally and precisely as possible)**:

Open dashboard: Teslamate > Updates > Updates

**Fix**

missing car_id in query:
original:
`SELECT count(*) FROM updates WHERE $__timeFilter(start_date)`
fix:
`SELECT count(*) FROM updates WHERE $__timeFilter(start_date) AND car_id = $car_id`

**Environment**

- TeslaMate version: 1.19.4
- Type of installation: Docker
- OS TeslaMate is installed on: raspian buster lite
- User OS & Browser:
- Others:

**Comment by DrMichael** [comment]
I created a PR: https://github.com/adriankumpf/teslamate/pull/840
