### ISSUE TITLE
Duplicate Vampire Drain Entries

### ISSUE THREAD

**Issue by kinteseay** [adriankumpf/teslamate#850]
Did this issue come back?  I'm using the latest postres and I'm getting the double entries for each vampire drain entry.  Was this an automatic fix with updates or is there something I need to manually do to fix it?

Thanks

**Comment by rndpsn** [comment]
@kinteseay do you have 2+ cars or just one?  Sounds the same as my issue #956 for 2 cars.

**Comment by kinteseay** [comment]
I have 2
