### ISSUE TITLE
Import from TeslaFI

### ISSUE THREAD

**Issue by Titanium31** [adriankumpf/teslamate#852]
Hello,

I just installed Teslamate on my Synology NAS. I am trying to import my data from TeslFI (10 months).
When I launch Teslafi, I can see my files but if I click on import nothing happens ... How do I know if the import is successful and when it will be finished ?
As nothing was happening, I clicked several times on import and now I have a small circle that turns around in front of each file, hence the same question: How to know if the import is done well and when it will be finished?

Thank's for your help

Daniel

PS: I connect from a Mac with Safari and Firefox, same problem on both.

**Comment by miksen** [comment]
There is a lot of status output in the terminal after you click import in the web UI. Have you looked at that @Titanium31 ?
