### ISSUE TITLE
Add efficiency on drive details

### ISSUE THREAD

**Issue by riesi77** [adriankumpf/teslamate#856]
As it is stated ((net) and (gross)) in the "Trip" Dashboard, it would be very helpful to have that as well in the "Drive Details". Nice to have: Also have it in the "Overview" for the logged drives.

**Comment by DrMichael** [comment]
Well for Overview it could look like:
![image](https://user-images.githubusercontent.com/8087682/94244109-aa51b180-ff18-11ea-9302-87c3e2acd8bd.png)

For Drives, I am not sure. We have already "Consumption" there?

**Comment by riesi77** [comment]
Overview looks good! Thanks.
Regarding Drives: I mean in the drive details. There is the distance and the Energy used - but the consumption in Wh/km would be valuable as well.

**Comment by DrMichael** [comment]
Ah, something like this?
![image](https://user-images.githubusercontent.com/8087682/94548091-7cd67200-0250-11eb-8445-dd5190737cad.png)

**Comment by riesi77** [comment]
Exactly.
Maybe a hint regarding consistency: Should it better be named "net"? But maybe it's worth having a look at the names around consumption in general? My suggestion is (but I can't say that I understand completely the different aspects of the different consumption values): net = drive consumption, gross = overall consumption (or time based consumption)?

**Comment by DrMichael** [comment]
Made a PR https://github.com/adriankumpf/teslamate/pull/958

**Comment by adriankumpf** [comment]
Added in https://github.com/adriankumpf/teslamate/pull/970
