### ISSUE TITLE
Master vs Last release

### ISSUE THREAD

**Issue by GtHbbrr** [adriankumpf/teslamate#858]
Using the documentation and the .yml I successfully installed the current release 1.19.4. What do I change in the installation to switch from release to the master version? Just using docker-compose pull I remain on the current release.

**Comment by DrJohnM61** [comment]
If you use the "image: teslamate/teslamate:latest" in your docker file, you should always get the latest image, viz, the master version

**Comment by GtHbbrr** [comment]
Thanks DrJohnM61

**Comment by GtHbbrr** [comment]
I checked my .yml and as per the default installation it is already using the "image: teslamate/teslamate:latest" in the docker file. Can I change this line to receive a docker image that has all the latest commits since the latest is now already 2 months old.

**Comment by GtHbbrr** [comment]
Purpose of this issue is to run a second teslamate installation with all the recent commits as opposed to the latest 1.19.4 release (release date June 4 vs today July 28)

**Comment by DrJohnM61** [comment]
The only other updated version of a docker tase that I can see is "edge" (ie, image: teslamate/teslamate:edge) although this is not built for all platforms and I cannot se any documentation for it. See https://hub.docker.com/r/teslamate/teslamate/tags

**Comment by DrJohnM61** [comment]
Just scanning old comments, I notice "You can try the current developer version: the teslamate/teslamate:edge and teslamate/grafana:edge Docker images always include the latest changes from the master branch." so looks like that is the right one. NB the grafana release also.

**Comment by GtHbbrr** [comment]
Thanks! So all I need to do is replace :latest with :edge in the image line

**Comment by adriankumpf** [comment]
Please note that `edge` this is not a stable release. It can break at any time even though we of course try to avoid this.
