### ISSUE TITLE
Inside/Outside temperature missing on homepage

### ISSUE THREAD

**Issue by cleanev** [adriankumpf/teslamate#860]
Teslamate home page does not display inside/outside temperature

**Expected behavior**
 Inside and outside temperature should be showing on teslamate homepage

**Screenshots**
![4B8974A7-3B75-499E-9B72-71F5E770454D](https://user-images.githubusercontent.com/45519661/88858919-ccec7600-d1c6-11ea-9bc3-a0e9ccf9ef7c.jpeg)

![E9EB9F68-0E19-4F28-9560-CD8F5DBA59F3](https://user-images.githubusercontent.com/45519661/88859210-42584680-d1c7-11ea-9ca3-b9b4695d2904.jpeg)

**Environment**

- TeslaMate version: 1.19.4 built on July 27
- Type of installation: Docker
- OS TeslaMate is installed on: Raspberry Pi OS 
- User OS & Browser: iOS/MacOS Safari
- Others:

Edit: added snapshot from Model 3 for comparison between Model Y and Model 3

**Comment by adriankumpf** [comment]
When the car goes to sleep, the TeslaMate has no access to the temperature readings. Therefore the temperature values are hidden if they have not been updated for 30 minutes.

**Comment by cleanev** [comment]
Thanks. That clarifies this
