### ISSUE TITLE
Experience with free Azure account?

### ISSUE THREAD

**Issue by ogezue** [adriankumpf/teslamate#864]
I'm trying to run teslamate in the free tier on a B1S which has 1GB RAM and supports docker. It worked a couple of weeks but from time to time I need to restart the VM as Teslamate is not reachable.

Are there any recommendations for the setup? Is it possible to use the free tier (1 year) of one of the cloud providers?

**Comment by BabyYeggie** [comment]
I run my instance on a g1-small vm on Google's Container OS. Maybe I'll switch over to Azure and see how it goes. The 1GB of ram is low due to docker. I think N1 @ 1vcpu/3.75GB works best but it's more expensive than buying and deploying a Pi4 4GB for the year.

Do you know of any other low-cost cloud services with larger ram allocations?

**Comment by ogezue** [comment]
I think Azure and AWS are on same price level. I haven't checked out google. It would be cool to have some kind of Teslamate-Service that would offer this. I would be willig to pay 3$/month for this.
Do you know the energy consumption of a PI4 running 24/7? (Maybe it could be shut down over night when I'm not driving)

**Comment by GtHbbrr** [comment]
I have Teslamate running in Google Cloud on a fs1-micro instance with 0.6Gb ram. 
You get a recommendation to upgrade to g1-small after setup as setting up uses more resources. But after that fs1-small in the free tier runs just fine

**Comment by BabyYeggie** [comment]
> I think Azure and AWS are on same price level. I haven't checked out google. It would be cool to have some kind of Teslamate-Service that would offer this. I would be willig to pay 3$/month for this.
> Do you know the energy consumption of a PI4 running 24/7? (Maybe it could be shut down over night when I'm not driving)

A Pi4 uses a 5v/3A adapter, so it uses roughly 15w continously or 10.8kwh/month. I pay 17c/kwh or roughly $1.80/month to run it.

> I have Teslamate running in Google Cloud on a fs1-micro instance with 0.6Gb ram.
> You get a recommendation to upgrade to g1-small after setup as setting up uses more resources. But after that fs1-small in the free tier runs just fine

Are you using the basic setup? I setup and pulled all the containers in a N1 instance, shutdown, then re-sized to a F1-micro and the VM instance wasn't able to rebuild the containers before the high load was killed by the cloud system.

Right now, I'm using a custom build with auto-update of all containers, auto-backup of the database, and automated off-site replication of the database backups. All this puts my Pi4 at a whole 1% cpu usage at 23% (775MB) ram usage.

I can't find a proper ARM-compiled container for caddy, Prometheus, and Cadvisor to monitor the containers so I use RaspController as an approximation.

**Comment by GtHbbrr** [comment]
Maybe your install was pulling more resources than mine. I followed the instructions per teslaev.co.uk
