### ISSUE TITLE
Incorrect trip energy usage calculation

### ISSUE THREAD

**Issue by verygreen** [adriankumpf/teslamate#869]
When looking on the drives tab, every trip reports energy used. This seems to be overinflated to the actual usage that is displayed on the car "trips" screen and when looking at the internal car variables or canbus scans.

It seems the assumption in Teslamate is that the rated Wh/mi is constant so multiplying rated range by rated wh/mi is the "real consumption. Alas it seems some time ago this was changed and now at 100% it works like this but as SoC decreases a "hidden" buffer is added so when the car displays say 8 miles of range left, in reality remaining battery is say 6+kWh as seen by internal variables (not on all cars too I imagine? but certainly on 100 packs) which also allows one to drive "below zero" SoC. The end result is the overinflation of energy used on a trip in TeslaMate.

I have some datapoints for a 100-pack s/x cars but no means to collect them for other car types so I am not sure how to go about this in a generic way to correct the display. Please let me know if you want the time series anyway.

**Comment by SDekkers** [comment]
The car doesn't return any data on how many % is hidden or perhaps miscalculated by the BMS. The range displayed in km/mi instead of % next to the battery icon is based on a static number and changes sometimes if Tesla decides to.

As the car doesn’t supply the data, this issue is probably unfixable.

For M3LR it was 152Wh/km, but I have suspected it to be 156Wh/km for my car now.

**Comment by verygreen** [comment]
The static number is not as static anymore, the old behavior you are describing used to be the case, but now there seems to be more of a dynamic formula where at 100% it is capacity/ratedwhmi but as you drop down in the SoC the formula breaks and the amount of reported miles remaining (and also reported SoC percentage!) starts to diverge.

Here's a sample:

![image](https://user-images.githubusercontent.com/625925/90539980-8c8d7180-e14e-11ea-94c7-41316549e8c4.png)
![image](https://user-images.githubusercontent.com/625925/90540013-97480680-e14e-11ea-8adc-ef24e5b4f311.png)

**Comment by SDekkers** [comment]
Isn't that since 2019.36(or .40?) with the "reservation" on the bottom end of the battery percentage ?
I only use Teslamate and it doesn't have this graph in Grafana; would be a nice addition though.

The difference could be explainable being the rated range using actual 5% as 0% (so 5% left in battery, display showing 0), and data returned via API calculating with actual 100%-0% values?

**Comment by verygreen** [comment]
I am not exactly sure when this change was implemented on Tesla side. It results in up to 5kWh "phantom" usage per segment by TeslaMate which might be material enough.

This graph is not possible with TeslaMate as it requires access beyond the app API - either to internal variables or to the canbus.

It does look like a new "hidden" buffer was added, I have some sessions recorded that hopefully could be used to calculate the new formula so TeslaMate energy use graphs are accurate again.

**Comment by SDekkers** [comment]
Bjorn talked about the buffer, or at least the disappearance of usable energy here: https://www.youtube.com/watch?v=QTOaDolXJXU

Regardless, got any ideas on how to implement, and measure it?

**Comment by verygreen** [comment]
I have a "log" of values that were used to produce the above graph. it's from LR+ car, but I can obtain similar for some other car types and then it should be possible to cross reference them and come up with a fitting formula.

I heard prev gen batteries (85 packs and prior) did not have this behavior added so might want to try on those cars as well.

I imagine it's something like "remaining capacity - (total nominal capacity - remaining capacity) * 0.05) / rated_whmi"

This seems to produce a much more stable graph within a couple miles from car reported values but I am sure it could be finetuned some more if anybody had tme to do it. I can export the values if there's any interest.

![image](https://user-images.githubusercontent.com/625925/90547554-b26c4380-e159-11ea-828d-1c268a311563.png)
