### ISSUE TITLE
Vampire Drain High - Not Sleeping?

### ISSUE THREAD

**Issue by EvanMcEwen** [adriankumpf/teslamate#87]
First off I would like to say kudos to the development of this app! I found it very easy to get setup on my own server and the stats have been very informative.

I'm having an issue where the car is not going to sleep or, if it is, it's being constantly woken up. 
Please see the following:
![Screen Shot 2019-08-13 at 9 19 45 AM](https://user-images.githubusercontent.com/1144060/62944841-87fbe380-bdab-11e9-9efa-83ad040cb1e9.png)

Ever since installing Teslamate I've had apparently an average vampire drain of ~200-230 W. I noticed I'd come to my car in the morning and be down more than a few percentage points of battery which I did not remember happening before installing Teslamate. Last night I decided to turn Teslamate off and then back on in the morning to see if that made a difference. As you can tell in the screenshot the loss of power was **significantly** down.

Is this expected behaviour or is something wrong?

**Comment by adriankumpf** [comment]
This is definitely not expected behaviour. The column 'standby' indicates that the car was online all the time. Usually it would show a percentage value.

How the log look like? Are there any errors / warnings?

**Comment by EvanMcEwen** [comment]
I just updated to 1.5.0 and when I clicked the "Try to sleep" button in the front-end I get "Car is not parked" even though it is parked.

When I try to manually hit the API with /suspend I see this in the logs:
```
teslamate_1            | 13:49:49.572 [info] PUT /api/car/1/logging/suspend
teslamate_1            | 13:49:49.952 [info] Could not suspend manually: :shift_state
teslamate_1            | 13:49:49.952 [info] Sent 412 in 379ms
```

**Comment by adriankumpf** [comment]
Okay, that's interesting ... afaik the car cannot fall asleep as long as a `shift_state` (either D, N, R or P) is reported by the API. Usually when the car is parked, after a while the `shift_state` becomes `nil`.

**Comment by adriankumpf** [comment]
I could make this condition / check optional or remove it altogether. But I still wonder why this problem occurs with your car in particular.

**Comment by EvanMcEwen** [comment]
Anything I can do to help debug? I'm a Software Engineer so throw anything at me.

Would having the raw JSON from the Tesla API be of any help? I don't think suspend logging has ever worked based on my logs.

**Comment by adriankumpf** [comment]
> Would having the raw JSON from the Tesla API be of any help? I don't think suspend logging has ever worked based on my logs.

Cool! Could you check the shift_state when the car is parked? https://tesla-api.timdorr.com/vehicle/state/drivestate

**Comment by EvanMcEwen** [comment]
I redacted the GPS info.
```
{
    "response": {
        "gps_as_of": 1565705272,
        "heading": ---,
        "latitude": ---,
        "longitude": ---,
        "native_latitude": ---,
        "native_location_supported": 1,
        "native_longitude": ---,
        "native_type": "wgs",
        "power": 0,
        "shift_state": "P",
        "speed": null,
        "timestamp": 1565705273283
    }
}
```

**Comment by natrlhy** [comment]
I've been wondering about how to interpret the vampire drain stats as well. I try to avoid using the Tesla App as much as possible since I know this constantly wakes the car back up.

![Capture](https://user-images.githubusercontent.com/19696424/62948595-832e3400-bd99-11e9-9828-f3d0e14d8f14.PNG)

**Comment by adriankumpf** [comment]
> I redacted the GPS info.
> 
> ```
> {
>     "response": {
>         "gps_as_of": 1565705272,
>         "heading": ---,
>         "latitude": ---,
>         "longitude": ---,
>         "native_latitude": ---,
>         "native_location_supported": 1,
>         "native_longitude": ---,
>         "native_type": "wgs",
>         "power": 0,
>         "shift_state": "P",
>         "speed": null,
>         "timestamp": 1565705273283
>     }
> }
> ```
> 
> Even though shift_state is "P" I cannot use the "Try to sleep" or /suspend API.

Thanks. Usually "P" becomes "null" after a while. But apparently this is not the case with all models / firmware versions. I'll fix it.

**Comment by EvanMcEwen** [comment]
If it helps: I have a 2018 Model S 100D running 2019.28.2

**Comment by adriankumpf** [comment]
> I've been wondering about how to interpret the vampire drain stats as well. I try to avoid using the Tesla App as much as possible since I know this constantly wakes the car back up.
> 
> ![Capture](https://user-images.githubusercontent.com/19696424/62948595-832e3400-bd99-11e9-9828-f3d0e14d8f14.PNG)

Looks okay to me. In general, longer periods of time are most meaningful. A vampire drain of ~200W or more is expected if sentry mode is enabled, for example.

**Comment by IMgoRt** [comment]
My 2016 P110DL produced this (I don't consult the app as my car's locking in my private garage)
![image](https://user-images.githubusercontent.com/53863760/62949408-096c6980-bdde-11e9-85df-616591fc1882.png)

**Comment by natrlhy** [comment]
> Looks okay to me. In general, longer periods are more meaningful. A vampire drain of ~200W or more is expected if sentry mode is enabled, for example.

Thanks. Yes I disable sentry at home while parked in the garage, too.
If I get a bash shell into the container, how do I see the logs? Sorry for the newbie questions around docker, etc.

bash-4.4$ ls -latrh
total 28
drwxr-xr-x    3 nobody   nobody      4.0K Aug  5 03:23 releases
drwxr-xr-x    2 nobody   nobody      4.0K Aug  5 03:23 bin
drwxr-xr-x    5 nobody   nobody      4.0K Aug  5 03:23 erts-10.4.4
drwxr-xr-x   52 nobody   nobody      4.0K Aug  5 03:23 lib
drwxr-xr-x    6 root     root        4.0K Aug  6 11:18 ..
drwxr-xr-x    7 nobody   nobody      4.0K Aug  6 11:18 .
drwxr-xr-x    2 nobody   nobody      4.0K Aug  6 11:18 tmp
bash-4.4$ pwd
/opt/app

**Comment by adriankumpf** [comment]
> Sorry for the newbie questions around docker, etc.

No problem at all. With shell access you can just `cd` into the folder with the `docker-compose.yml` and run:

```bash
docker-compose logs -f teslamate
```

**Comment by natrlhy** [comment]
> No problem at all. With shell access you can just `cd` into the folder with the `docker-compose.yml` and run:
> 
> ```shell
> docker-compose logs -f teslamate
> ```
Thanks! I'm also trying this in a browser window but I get a "Not Found" response:

`http://myiphere:4000/api/car/1/data_request/drive_state`

**Comment by adriankumpf** [comment]
@EvanMcEwen v1.5.1 is out. Let me know how it goes.

**Comment by adriankumpf** [comment]
> > No problem at all. With shell access you can just `cd` into the folder with the `docker-compose.yml` and run:
> > ```shell
> > docker-compose logs -f teslamate
> > ```
> 
> Thanks! I'm also trying this in a browser window but I get a "Not Found" response:
> 
> `http://myiphere:4000/api/car/1/data_request/drive_state`

Oh, that route does not exist. You would need to call the owner API (https://owner-api.teslamotors.com/) with a valid access token.

**Comment by EvanMcEwen** [comment]
Thanks @adriankumpf running 1.5.1 and I was able to get it into a "falling asleep" status. I'll let this run for another day and see what my Vampire Drain looks like.

Question: Does the /suspend stop all logging? Do I have to then hit /resume to start normal functionality again? Or does /suspend follow the same rules as laid out in your Readme
```
TeslaMate polls the car every few seconds while driving or charging. After that, it keeps polling for about 15 minutes (to catch the following drive if you stopped for a drink, for example). After this period, TeslaMate will stop polling the car for about 12 minutes to let it go to sleep. This is repeated until the car is asleep or starts to drive/charge again. Once sleeping, TeslaMate will never wake the wake the car. It is only checked twice a minute to see if it is still sleeping.
```

If I manually hit /suspend, will Teslamate continue to check my car based on the logic above to see if it has started driving?

**Comment by adriankumpf** [comment]
Okay, awesome!

Teslamate continues to check your car _after_ the 12 minutes period. If you start driving in the meantime, hitting /resume would start normal functionality again. Only then the drive will be logged from the start.

**Comment by EvanMcEwen** [comment]
Okay so just so I'm clear:

**Time to Try Sleeping: 12 Minutes**
This means that every 12 minutes or so you'll ping the API to check the status of the car?

**Idle Time Before Trying to Sleep: 15 minutes**
This means that so long as the car has been in a non-driving (parked) state for at least 15 minutes the app will attempt to go to sleep.

Is this correct?

**Comment by EvanMcEwen** [comment]
Also: Is there another state after "falling asleep"? It's been about 40 minutes in this state.

**Comment by adriankumpf** [comment]
I think you almost got it ... but I struggle to find meaningful descriptions / wordings here.

The process is as follows:

```
parked ---15min---> trying to sleep / "falling asleep"  ---12min---> asleep
```

If you suspend manually it jumps from parked to "falling asleep" immediately.

The state transition from "falling asleep" to "asleep" may take longer than 12 minutes. It depends on what the car is doing. Sometimes it sends data to Tesla, for example, which can take a few hours even.

**Comment by adriankumpf** [comment]
> Also: Is there another state after "falling asleep"? It's been about 40 minutes in this state.

Let's see if that changes in the next hour or so. But it seems a little long ...

**Comment by adriankumpf** [comment]
If it should not go into sleep mode, try increasing the "Time to Try Sleeping" to the pre v1.5 value of 21min

**Comment by adriankumpf** [comment]
If the above measures do not help, please try this: https://support.teslafi.com/knowledge-bases/2/articles/161-my-vehicle-is-not-sleeping

**Comment by EvanMcEwen** [comment]
Thanks I understand now. Yes I'm going to put the "Time to Try Sleeping" to 30 minutes as that makes the most sense for me. I'm going to charge up and report back tomorrow on my Vampire Drain. Thanks for the quick turnaround on the bug and replies! 👍

**Comment by IMgoRt** [comment]
> My 2016 P110DL produced this (I don't consult the app as my car's locking in my private garage) 2019.28.2
> ![image](https://user-images.githubusercontent.com/53863760/62949408-096c6980-bdde-11e9-85df-616591fc1882.png)

So since yesterday's updates my sleepy P100D (HW2.0, 2019.28.2) now never sleeps - zero changes made to the car, parked in exactly the same personal garage and the car has not slept since parked 20 hours ago.

**Comment by adriankumpf** [comment]
Can you verify that it sleeps again if the "Time to Try Sleeping" on the settings page is increased to the pre v1.5 value of 21min?

**Comment by IMgoRt** [comment]
> Can you verify that it sleeps again if the "Time to Try Sleeping" on the settings page is increased to the pre v1.5 value of 21min?

Yes, that fixes it for me, thank you again for the great app and equally good support.

**Comment by adriankumpf** [comment]
Okay, good to know. I really didn’t expect the various models to behave that differently. When I tested with a Model 3, 12 minutes were always enough for it to fall asleep. I’ll release a bugfix in a few hours that increases the value to its previous state.

**Comment by IMgoRt** [comment]
> Okay, good to know. I really didn’t expect the various models to behave that differently. When I tested with a Model 3, 12 minutes were always enough for it to fall asleep. I’ll release a bugfix in a few hours that increases the value to its previous state.

Happy to be here and testing for the good of the community

**Comment by EvanMcEwen** [comment]
@adriankumpf Okay much better:

![Screen Shot 2019-08-14 at 9 51 04 AM](https://user-images.githubusercontent.com/1144060/63026424-27d37300-be79-11e9-9586-04771dcf432b.png)

However my car is never truly "asleep" according to your app. I just see it being brought "online" and "offline" every half hour (my trying to sleep value). I also don't have a standby value as you can see. I'm happy enough with this as is but maybe you could add some extra values in the "trying to sleep" dropdown? I'd like to select an hour or more; I have a shortcut on my phone to hit /resume whenever I get ready to start driving so a higher value doesn't matter much to me in terms of potentially "loosing" driving data.

**Comment by EvanMcEwen** [comment]
Alternatively I wouldn't mind a /stop endpoint that completely stops Teslamate from hitting the TeslaAPI and can only be started again by hitting /resume (or maybe a new /start).

**Comment by adriankumpf** [comment]
Yeah, that's looks a bit better. The state being reported as "offline" is a good sign. The car being asleep is sometimes reported as offline even though it's not.

How's the wifi connection of your car? If it has a weak wifi signal it may be disconnecting and connecting to the wifi network repeatedly which prevents the car from sleeping.  Can you try turning off wifi all together to test if things change?

**Comment by EvanMcEwen** [comment]
There's no WiFi where my car is when it sleeps overnight. I'm parked two levels down in a Condo building so I only have LTE.

**Comment by EvanMcEwen** [comment]
I'm going to close this issue as I'm happy with the drain now. I've manually updated the database to make my suspend_min = 480 and I'll see if I get a better vampire drain tonight. I would still like to see a manual /stop and /start endpoint but that's more of a feature request and doesn't belong here. Thanks for the help @adriankumpf !

**Comment by adriankumpf** [comment]
I really want to know what's causing this, though ... If you figure something out let us know.

Anyway, `v1.5.3` was just released. It adds some extra values to the dropdown and hopefully fixes the sleep issue for most Model S owners like @IMgoRt. I'm also going to think about adding those endpoints. They probably won't be documented though because I don't want to deal with people accidentally calling them and thereby "breaking" everything.

**Comment by adriankumpf** [comment]
And thank you very much for the donation!

**Comment by EvanMcEwen** [comment]
> I really want to know what's causing this, though ... If you figure something out let us know.
> 
> Anyway, `v1.5.3` was just released. It adds some extra values to the dropdown and hopefully fixes the sleep issue for most Model S owners like @IMgoRt. I'm also going to think about adding those endpoints. They probably won't be documented though because I don't want to deal with people accidentally calling them and thereby "breaking" everything.

Heh yeah that's okay. As a self proclaimed "poweruser" in most of my IT dealings I like having more manual control over a system if possible :P Undocumented is perfectly fine.

My only other thought about what's causing it is that the TeslaAPI isn't responding how you thought it would (similar to the original issue with shift_state). Is there any endpoint you'd like me to hit at a certain time so I can provide the raw JSON?

**Comment by adriankumpf** [comment]
I can relate to that :D 

Yeah, maybe. On the other hand, by suspending all requests nothing should prevent the car from going to sleep. After the `suspend_min` period it sends a request to the [vehicles api](https://tesla-api.timdorr.com/api-basics/vehicles#get-api-1-vehicles-id) first, which does not wake up the car. It then notes that the vehicle state is still `online`. This triggers a request to the  [vehicle data api](https://tesla-api.timdorr.com/vehicle/state/data#get-api-1-vehicles-id-vehicle_data) (that is the one that prevents the car from sleeping). However, if the vehicle state would've been `asleep` or `offline` in the first place this request would not be made.

It's very strange. My wild guess atm is that the present `shift_state` value is related to this somehow ...

**Comment by EvanMcEwen** [comment]
So I do know that my car does go into an "offline" state... do you not count that as "asleep" for the purposes of being displayed on Grafana? It seems like (to me) "asleep" and "offline" are synonymous for each other at least in my car's case. I have yet to see it in the "asleep" state.

**Comment by adriankumpf** [comment]
I don't think so. The state transition from `suspended` (= falling asleep) to `offline`  happens regularly to my Model 3.

https://github.com/adriankumpf/teslamate/blob/0be3c36cf2d0269134e64346c8a9b518e788ee59/lib/teslamate/vehicles/vehicle/vehicle.ex#L445-L451

So, if the first request that is made after the `suspend_min` period returns the offline (or asleep) state, it should work.

**Comment by espenu** [comment]
My Model S is still not falling asleep in v1.5.3. TeslaMate reports either online, or falling asleep.
Time to Try Sleeping is set to 21min.

**Comment by adriankumpf** [comment]
Did it sleep prior to v1.5? What do you see in the logs?

**Comment by adriankumpf** [comment]
More questions to debug this issue: 

* Is Teslamate the only logger / app polling your car? 
* Did you use another logger before Teslamate and did your go into sleep mode then?

**Comment by espenu** [comment]
> More questions to debug this issue:
> 
> * Is Teslamate the only logger / app polling your car?
> * Did you use another logger before Teslamate and did your car go into sleep mode then?
> * Have you tried out these: https://support.teslafi.com/knowledge-bases/2/articles/161-my-vehicle-is-not-sleeping

I could see it sleep when on 1.4, but I had only been on 1.4 for a couple of days before 1.5 was available and I upgraded.
TeslaMate is the only logger currently in use. I used to have Tezlab, but I stopped using it a few weeks ago.
During the night I get a log note of "car_id=1 [info] Suspending logging" every 21 min.
I've looked at the teslafi troubleshooting article and I will try the steps that seem relevant. Usually I have my key by my front door close to the garage, but the key box is lined with aluminum foil. I've moved it to the other side of the house for now to see if it helps.
I've also rebooted the MCU (version 1).

**Comment by adriankumpf** [comment]
All right, if the steps from the teslafi troubleshooting article don't improve the situation, you cloud increase the sleep settings from 21 minutes to 30 or more. To rule out that the Tezlab continues to poll your car, change your Tesla Account password.

**Comment by espenu** [comment]
> All right, if the steps from the teslafi troubleshooting article don't improve the situation, you could increase the sleep settings from 21 minutes to 30 or more. To rule out that the Tezlab continues to poll your car, change your Tesla Account password.

After trying the Teslafi steps I changed my Tesla password, and set the sleep setting from 21 to 35 min. Still not sleeping.
I may have a backup of teslamate 1.4, so when I get time during the week I can try to spin up the backup and verify that it sleeps there as it did before. If it doesn't, is it possible for me to see what could be preventing it from sleeping?

**Comment by adriankumpf** [comment]
If you're using a docker-compose.yml it is possible to specify a version:

```YAML
version: '3'
services:
  teslamate:
    image: teslamate/teslamate:1.4.3

...

 grafana:
    image: teslamate/grafana:1.4.3

...
``` 

Honestly, I'd be very surprised if v1.4 improves things. But let's see ...

> If it doesn't, is it possible for me to see what could be preventing it from sleeping?

If the logs don't show any warnings or errors and the status screen shows "falling asleep", nothing should prevent your car from falling asleep.

Try turning off TeslaMate in the evening and turn it back on before the next drive. After that, take a look at the vampire drain.

**Comment by espenu** [comment]
> ~If you're using a docker-compose.yml it is possible to specify a version:~
> 
> Edit: it's not really backwards compatible. You'd need to manually rollback the migrations.
> 
> ```yaml
> version: '3'
> services:
>   teslamate:
>     image: teslamate/teslamate:1.4.3
> 
> ...
> 
>  grafana:
>     image: teslamate/grafana:1.4.3
> 
> ...
> ```
> 
> Honestly, I'd be very surprised if v1.4 improves things. But let's see ...
> 
> > If it doesn't, is it possible for me to see what could be preventing it from sleeping?
> 
> If the logs don't show any warnings or errors and the status screen shows "falling asleep", nothing should prevent your car from falling asleep.
> 
> Try turning off TeslaMate in the evening and turn it back on before the next drive. After that, take a look at the vampire drain.

I'll try that.

Compatibility is not a problem. I run docker in an Ubuntu container, and I have a backup of the whole container. So I'll just back up the database, wipe it, and bring back the old docker container.

**Comment by EvanMcEwen** [comment]
@espenu It may not be "sleeping" but do you have any vampire drain? Mine never showed up as "sleeping" either but my total power consumption was ~40-60 watts which is in-line with what sleeping produces.

**Comment by espenu** [comment]
Ok.. So I managed to get it to sleep (and it was actually still awake with almost 2kW drained per night). I thought the WiFi signal was fine, but decided to set my phone as a hotspot and leave it in the car so that it would get full signal. It then finally went to sleep.
Strangely after I removed the phone, it actually went back to sleep all night.. So I'm not quite sure what's going on with it.

But in any case it's definitely a car issue and not a teslamate issue.

**Comment by mapchen** [comment]
let me also post my states here to see if this is normal. I managed to get my car to sleep once in one week. 30% is offline and rest is online/driving/charging. I have tried all the tips like sentry mode, heat protection, wifi on/off. Nothing really changed. I am having a tesla x, delivered one week ago.

I can also not see the consumption in the table.
![image](https://user-images.githubusercontent.com/56200461/66705419-a4be8400-ed26-11e9-93b6-d0975f5b414b.png)

![image](https://user-images.githubusercontent.com/56200461/66705428-bef86200-ed26-11e9-9482-726ea674a8af.png)

In the end I am just wondering if this is normal behavior?

**Comment by adriankumpf** [comment]
In the vast majority of cases "offline" means "asleep" (maybe it's some kind of deep sleep mode?). 

Whether those longer online periods are normal is hard to tell. The question can be answered better by others in the community.  However, those offline periods show that TeslaMate does not prevent the car from sleeping. It seems to be caused by something else.

> I can also not see the consumption in the table. Has this to do with that my car is not identified?

See https://github.com/adriankumpf/teslamate/issues/191#issuecomment-538642450
