### ISSUE TITLE
Update to Grafana 7

### ISSUE THREAD

**Issue by phantom1584** [adriankumpf/teslamate#870]
**What would you like to be added**:
Update docker files to use Grafana 7 (currently on 6.7.4)

**Why is this needed**:
Use the latest features within Grafana

**Additional context**:

**Comment by adriankumpf** [comment]
We already have a branch with updated Dockerfiles and dashboards here: https://github.com/adriankumpf/teslamate/tree/grafana-7

What is currently blocking the full roll-out is this ticket I created in April: grafana/grafana#24092 It is supposed to be released with Grafana 7.2. Let's hope that this will happen 🤞

**Comment by phantom1584** [comment]
Thanks!  What updates are needed in the docker-compose.yml file to point to the grafana 7 branch?

**Comment by adriankumpf** [comment]
There is no docker image for download yet. You'd have to build it yourself first.

**Comment by fatbasstard** [comment]
Ah, They just moved this issue to 7.3 😢
