### ISSUE TITLE
Manual install instructions check out wrong release

### ISSUE THREAD

**Issue by leewillis77** [adriankumpf/teslamate#873]
**Describe the bug**
The manual install instructions (https://docs.teslamate.org/docs/installation/debian) say:
```git checkout $(git describe --tags) # Checkout the latest stable version```

At time of writing, this checks out `v1.19.3-123-g67f1785` however it appears that the latest release is `v1.19.4` according to `git tags -l` and the GitHub repository page.

**Comment by baylanger** [comment]
Maybe a tag is missing, not sure but try ```git checkout tags/v1.19.4```

**Comment by leewillis77** [comment]
@baylanger Thanks. However, I know how I can grab the latest version, just pointing out that either something was missed in the release process, or the docs are incorrect.
