### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by spot88** [adriankumpf/teslamate#875]
**Describe the bug**
When i try to go to teslamate.domain.com i get 404 page not found. Grafana works.

**Expected behavior**
Login screen, so i can login to Tesla?

**How to reproduce it (as minimally and precisely as possible)**:
Fresh installation with docker.

**Relevant entries from the logs**

```
teslamate_1  | 18:25:20.933 [info] == Migrated 20200306130218 in 0.0s
teslamate_1  | 18:25:20.937 [info] == Running 20200306133847 TeslaMate.Repo.Migrations.AddFlatFee.change/0 forward
teslamate_1  | 18:25:20.937 [info] alter table geofences
teslamate_1  | 18:25:20.938 [info] == Migrated 20200306133847 in 0.0s
teslamate_1  | 18:25:20.941 [info] == Running 20200318164021 TeslaMate.Repo.Migrations.UseStreamingApi.change/0 forward
teslamate_1  | 18:25:20.942 [info] alter table car_settings
teslamate_1  | 18:25:20.943 [info] == Migrated 20200318164021 in 0.0s
teslamate_1  | 18:25:20.946 [info] == Running 20200320140020 TeslaMate.Repo.Migrations.DropPowerAvg.change/0 forward
teslamate_1  | 18:25:20.947 [info] alter table drives
teslamate_1  | 18:25:20.948 [info] == Migrated 20200320140020 in 0.0s
teslamate_1  | 18:25:20.952 [info] == Running 20200401170940 TeslaMate.Repo.Migrations.RemoveSleepModeToggles.up/0 forward
teslamate_1  | 18:25:20.952 [info] alter table car_settings
teslamate_1  | 18:25:20.953 [info] drop table geofence_sleep_mode_whitelist
teslamate_1  | 18:25:20.954 [info] drop table geofence_sleep_mode_blacklist
teslamate_1  | 18:25:20.956 [info] == Migrated 20200401170940 in 0.0s
teslamate_1  | 18:25:20.960 [info] == Running 20200401171402 TeslaMate.Repo.Migrations.RemoveSleepModeRequirements.change/0 forward
teslamate_1  | 18:25:20.961 [info] alter table car_settings
teslamate_1  | 18:25:20.961 [info] == Migrated 20200401171402 in 0.0s
teslamate_1  | 18:25:20.965 [info] == Running 20200401171923 TeslaMate.Repo.Migrations.EnableStreaming.up/0 forward
teslamate_1  | 18:25:20.974 [info] == Migrated 20200401171923 in 0.0s
teslamate_1  | 18:25:20.977 [info] == Running 20200410112005 TeslaMate.Repo.Migrations.DatabaseEfficiencyImprovements.change/0 forward
teslamate_1  | 18:25:20.978 [info] alter table cars
teslamate_1  | 18:25:20.995 [info] alter table addresses
teslamate_1  | 18:25:21.008 [info] alter table charging_processes
teslamate_1  | 18:25:21.024 [info] alter table drives
teslamate_1  | 18:25:21.049 [info] alter table geofences
teslamate_1  | 18:25:21.058 [info] alter table positions
teslamate_1  | 18:25:21.075 [info] alter table charges
teslamate_1  | 18:25:21.087 [info] alter table states
teslamate_1  | 18:25:21.096 [info] alter table tokens
teslamate_1  | 18:25:21.101 [info] alter table updates
teslamate_1  | 18:25:21.108 [info] == Migrated 20200410112005 in 0.1s
teslamate_1  | 18:25:21.117 [info] == Running 20200502140646 TeslaMate.Repo.Migrations.DropUnusedIndexes.change/0 forward
teslamate_1  | 18:25:21.118 [info] drop index if exists positions_ll_to_earth_latitude__longitude_index
teslamate_1  | 18:25:21.119 [info] drop index if exists addresses_ll_to_earth_latitude__longitude_index
teslamate_1  | 18:25:21.121 [info] == Migrated 20200502140646 in 0.0s
teslamate_1  | 18:25:33.148 [info] Version: 1.19.4
teslamate_1  | 18:25:33.256 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
teslamate_1  | 18:25:33.262 [info] Access TeslaMateWeb.Endpoint at http://teslamate.domain.com
teslamate_1  | 18:25:33.279 [info] MQTT connection has been established
teslamate_1  | 18:25:36.683 [info] tzdata release in place is from a file last modified Wed, 11 Sep 2019 19:35:17 GMT. Release file on server was last modified Fri, 24 Apr 2020 04:15:20 GMT.
teslamate_1  | 18:25:38.564 [info] Tzdata has updated the release from 2019c to 2020a
teslamate_1  | 18:49:42.983 [info] SIGTERM received - shutting down
```

**Environment**

- TeslaMate version: 1.19.4
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu 18.04.5
- User OS & Browser: Chrome

**Comment by spot88** [comment]
Anyone? :D

**Comment by DrJohnM61** [comment]
If I read this correctly, you are trying to connect to teslamate. The documentation says to connect the web interface http://your-ip-address:4000

Eg, http://192.168.0.120:4000

**Comment by DrJohnM61** [comment]
Probably, this should be your tesla account username and password. The one you would sign in tesla.com

**Comment by spot88** [comment]
> Probably, this should be your tesla account username and password. The one you would sign in tesla.com

Thanks for reply, i have tryed that too. Nothing happends :(

**Comment by spot88** [comment]
root@TeslaMate:/opt/TeslaMate# docker-compose version
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
root@TeslaMate:/opt/TeslaMate# docker-compose images
      Container             Repository         Tag       Image Id       Size  
------------------------------------------------------------------------------
teslamate_database_1    postgres              12       62473370e7ee   314 MB  
teslamate_grafana_1     teslamate/grafana     latest   da32e86e8d14   239.7 MB
teslamate_mosquitto_1   eclipse-mosquitto     1.6      24b5edd285d3   10.13 MB
teslamate_proxy_1       traefik               v2.2     c6e6fde07226   78.41 MB
teslamate_teslamate_1   teslamate/teslamate   latest   35bff31921b9   42.49 MB

**Comment by spot88** [comment]
Logs right after i did a down, pull, and up -d. 
Even tryed to login teslamate.xxxx.com

`root@TeslaMate:/opt/TeslaMate# docker-compose logs
Attaching to teslamate_teslamate_1, teslamate_mosquitto_1, teslamate_database_1, teslamate_proxy_1, teslamate_grafana_1
database_1   | 
database_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1   | 
database_1   | 2020-08-26 11:04:31.138 UTC [1] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
database_1   | 2020-08-26 11:04:31.138 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1   | 2020-08-26 11:04:31.138 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1   | 2020-08-26 11:04:31.142 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1   | 2020-08-26 11:04:31.186 UTC [24] LOG:  database system was shut down at 2020-08-26 11:03:41 UTC
database_1   | 2020-08-26 11:04:31.214 UTC [1] LOG:  database system is ready to accept connections
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Starting Grafana" logger=server version=6.7.4 commit=8e44bbc5f5 branch=HEAD compiled=2020-05-26T17:35:38+0000
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana-plugins"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana-plugins"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=https://grafana.hagendata.no"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_ANALYTICS_REPORTING_ENABLED=FALSE"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_USER=anders"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_DISABLE_GRAVATAR=true"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ALLOW_EMBEDDING=true"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_USERS_ALLOW_SIGN_UP=false"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ENABLED=false"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_AUTH_BASIC_ENABLED=true"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana-plugins
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="App mode production" logger=settings
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing SqlStore" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Starting DB migration" logger=migrator
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing HTTPServer" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing BackendPluginManager" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing PluginManager" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Registering plugin" logger=plugins name="Map Panel"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Registering plugin" logger=plugins name=Discrete
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Registering plugin" logger=plugins name=TrackMap
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing HooksService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing OSSLicensingService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing InternalMetricsService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing RemoteCache" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing RenderingService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing AlertEngine" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing QuotaService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing ServerLockService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing UserAuthTokenService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing DatasourceCacheService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing LoginService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing SearchService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing TracingService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing UsageStatsService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing CleanUpService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing NotificationService" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing provisioningServiceImpl" logger=server
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Initializing Stream Manager"
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=info msg="Backend rendering via phantomJS" logger=rendering renderer=phantomJS
grafana_1    | t=2020-08-26T11:04:32+0000 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin. Read more at https://grafana.com/docs/grafana/latest/administration/image_rendering/" logger=rendering renderer=phantomJS
mosquitto_1  | 1598439870: mosquitto version 1.6.12 starting
mosquitto_1  | 1598439870: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto_1  | 1598439870: Opening ipv4 listen socket on port 1883.
mosquitto_1  | 1598439870: Opening ipv6 listen socket on port 1883.
mosquitto_1  | 1598439870: mosquitto version 1.6.12 running
mosquitto_1  | 1598439888: New connection from 172.18.0.6 on port 1883.
mosquitto_1  | 1598439888: New client connected from 172.18.0.6 as TESLAMATE_302E3536323 (p2, c1, k60).
teslamate_1  | 13:04:36.861 [info] Already up
teslamate_1  | 13:04:48.838 [info] Version: 1.19.4
teslamate_1  | 13:04:48.888 [info] Running TeslaMateWeb.Endpoint with cowboy 2.7.0 at :::4000 (http)
teslamate_1  | 13:04:48.890 [info] Access TeslaMateWeb.Endpoint at http://teslamate.xxxx.com
teslamate_1  | 13:04:48.901 [info] MQTT connection has been established
teslamate_1  | 13:04:52.376 [info] tzdata release in place is from a file last modified Wed, 11 Sep 2019 19:35:17 GMT. Release file on server was last modified Fri, 24 Apr 2020 04:15:20 GMT.
teslamate_1  | 13:04:54.328 [info] Tzdata has updated the release from 2019c to 2020a
proxy_1      | time="2020-08-26T11:04:31Z" level=info msg="Configuration loaded from flags."`

**Comment by spot88** [comment]
Tips anyone?

**Comment by adriankumpf** [comment]
The logs don't show any requests to the TeslaMate container. Did you manage to login with the user/password from the` .htpasswd`?  Try assigning a different password. And the .htpasswd file must be `/opts/TeslaMate`.

**Comment by spot88** [comment]
@adriankumpf - Thanks for reply. 

Did docker-compose down, changed the passord to Random467 (teslamate:Random467) - .htpasswd lays in /opt/TeslaMate
then docker-compose up, i get the same thing. Seems like i can't login to Teslamate with the .htpasswd when it pops up.

![image](https://user-images.githubusercontent.com/10884072/91478742-b0fcf280-e8a0-11ea-9073-55a0b82ae219.png)

**Comment by adriankumpf** [comment]
What happens if you temporarily switch off basic auth (remove the corresponding traefik label)? Does that work? And did you use a generator to create the file?

**Comment by spot88** [comment]
How do i switch off basic auth? Did not use a generator to create the file.

**Comment by spot88** [comment]
nano .htpasswd - is Basic what i did.

**Comment by adriankumpf** [comment]
See https://docs.teslamate.org/docs/guides/traefik#htpasswd

**Comment by spot88** [comment]
Basicly what i have done.
![image](https://user-images.githubusercontent.com/10884072/91479523-db02e480-e8a1-11ea-8451-60536f99c2cd.png)

**Comment by spot88** [comment]
@adriankumpf

**Comment by adriankumpf** [comment]
Please read this section again: https://docs.teslamate.org/docs/guides/traefik#htpasswd The .httpasswd does not contain the password in clear text. It must be generated, either by the linked Apache tools or by a htpasswd generator

**Comment by crazyboyL** [comment]
> Reboot of server and down\up solved it. Got login popup now. What do i type here? Tryed with info from .htpasswd

not working still teslamate 404 while grafana working
