### ISSUE TITLE
Column p0.drive_id does not exist

### ISSUE THREAD

**Issue by soybomb** [adriankumpf/teslamate#88]
Upgrading from 1.4 via docker-compose pull and now seeing this error on startup:

`** (Postgrex.Error) ERROR 42703 (undefined_column) column p0.drive_id does not exist
teslamate_1  | 17:53:45.342 [info] == Running 20190805092941 TeslaMate.Repo.Migrations.FixIncompleteChargingProcesses.up/0 forward
teslamate_1  | ** (Postgrex.Error) ERROR 42703 (undefined_column) column p0.drive_id does not exist
teslamate_1  |
teslamate_1  |     query: SELECT p0."id", p0."date", p0."latitude", p0."longitude", p0."speed", p0."power", p0."odometer", p0."ideal_battery_range_km", p0."battery_level", p0."battery_heater", p0."battery_heater_on", p0."battery_heater_no_power", p0."outside_temp", p0."inside_temp", p0."altitude", p0."fan_status", p0."driver_temp_setting", p0."passenger_temp_setting", p0."is_climate_on", p0."is_rear_defroster_on", p0."is_front_defroster_on", p0."car_id", p0."drive_id", p0."id" FROM "positions" AS p0 WHERE (p0."id" = $1)
teslamate_1  |
teslamate_1  |     hint: Perhaps you meant to reference the column "p0.trip_id".
`

**Comment by adriankumpf** [comment]
I'll investigate this. In the meantime upgrade to v1.4.3 first (by explicitly specifying the tag in the docker-compose file). After starting once, you can upgrade to the `latest` version i.e. v1.5.1.

**Comment by adriankumpf** [comment]
Never mind, I found a quick fix. Docker image will be ready in ~30 minutes.

**Comment by bahree** [comment]
I was going to pull and star this on my synology NAS - should I just wait until I hear on this? :)

**Comment by adriankumpf** [comment]
The image ist available. You can try it now :)

**Comment by soybomb** [comment]
working great now, thanks!
