### ISSUE TITLE
Temperature Chart

### ISSUE THREAD

**Issue by riesi77** [adriankumpf/teslamate#886]
**What would you like to be added**:
Add a new dashboard which shows a chronological chart of the outside temperature. Nice to have: also display the inside temperature. 

**Why is this needed**:
The car collects the information (inside temperature, outside temperature) - This is informative

**Additional context**:

**Comment by cwanja** [comment]
During what periods? 24/7? If so, it would never sleep (I believe). When it falls into a deep sleep, do not believe those values are reported by the API. 

If you want it during drivers or charges, that is available.

**Comment by DrMichael** [comment]
It is indeed. I've put together a temperature panel:

![2020-09-01 15_46_01-Window](https://user-images.githubusercontent.com/8087682/91859209-71505500-ec6a-11ea-95f8-14ff9835b39b.png)

Import this:

[Temperature-1598968166979.zip](https://github.com/adriankumpf/teslamate/files/5156597/Temperature-1598968166979.zip)

**Comment by bahree** [comment]
Thoughts on adding this as part of the default install @adriankumpf ?

**Comment by DrMichael** [comment]
Well, it is a stripped down version of my statistics panel:

![2020-09-01 18_01_49-Statistics - Grafana](https://user-images.githubusercontent.com/8087682/91876656-3f94b980-ec7d-11ea-9e45-8531db864af3.png)

That still has the issue, that you have to change the postgresql server tiimezone to your timezone... See https://github.com/adriankumpf/teslamate/issues/664

Happy to share anyway.

[Statistics-1598976191847.zip](https://github.com/adriankumpf/teslamate/files/5157493/Statistics-1598976191847.zip)

**Comment by adriankumpf** [comment]
> Thoughts on adding this as part of the default install @adriankumpf ?

I am not opposed to adding it, but I do not understand its purpose. Since the car sleeps most of the time and is therefore not available through the API, the dashboard only shows the average temperature during trips. What do you do with this information?

The statistics panel looks pretty cool though. A PR would be appreciated @DrMichael but I don't know how to work around the timezone issue.

**Comment by cwanja** [comment]
> Well, it is a stripped down version of my statistics panel:
> 
> ![2020-09-01 18_01_49-Statistics - Grafana](https://user-images.githubusercontent.com/8087682/91876656-3f94b980-ec7d-11ea-9e45-8531db864af3.png)
> 
> That still has the issue, that you have to change the postgresql server tiimezone to your timezone... See #664 (and would have to be migrated to the new table in Grafana 7, waiting for the bug fixes).
> 
> Happy to share anyway.
> 
> [Statistics-1598976191847.zip](https://github.com/adriankumpf/teslamate/files/5157493/Statistics-1598976191847.zip)

This is definitely really interesting statistics. Hopefully there is a way to set the timezone either through the interface or natively based upon the host.

**Comment by DrMichael** [comment]
> This is definitely really interesting statistics. Hopefully there is a way to set the timezone either through the interface or natively based upon the host.

Well, to make things worse, you can set the display timezone in Grafana 7 to every timezone instead of just UTC and local timezone...

**Comment by DrMichael** [comment]
> The statistics panel looks pretty cool though. A PR would be appreciated @DrMichael but I don't know how to work around the timezone issue.

I would hold back, until it is running properly with Grafana 7... Still two bugs with hidden fields and formatting timestamps. And still have to figure out, how to handel the km/mi and c/f settings reasonably, @adriankumpf any idea there?

**Comment by adriankumpf** [comment]
Yes, it's a real pity that the new component still doesn't support hidden fields. Can the timestamp problem solved with a custom format (https://github.com/grafana/grafana/issues/24917)?

What's the issue with units again? The existing conversion helpers do not work?

**Comment by DrMichael** [comment]
> Can the timestamp problem solved with a custom format ([grafana/grafana#24917](https://github.com/grafana/grafana/issues/24917))?

Well, it turns out, that formatting a time string does not work. It does work though for timestamps with "time: YYY-MM-DD HH:mm" e.g.

> What's the issue with units again? The existing conversion helpers do not work?

Ah, you can deal with that by using regexes... But, it appears to me, that the "new" fields (e.g. when you switch km to mi) show up at the far right of the table.

What are the conversion helpers?

**Comment by adriankumpf** [comment]
> Ah, you can deal with that by using regexes... But, it appears to me, that the "new" fields (e.g. when you switch km to mi) show up at the far right of the table.
> 
> What are the conversion helpers?

Ah ok, I thought you meant the conversion from km to mi based on user settings.

**Comment by DrMichael** [comment]
Oh, yes, I use e.g. "convert_km(sum(distance)::numeric, '$length_unit')" in queries...

(just to make others aware of that... :-)

**Comment by akac** [comment]
What id like to see is similar to this chart in Stats app:
https://pbs.twimg.com/media/EmVc8JRVcAE6uEz?format=jpg&name=large

Essentially it’s a temperature/efficiency chart.
