### ISSUE TITLE
Support pinch to zoom

### ISSUE THREAD

**Issue by riesi77** [adriankumpf/teslamate#887]
**What would you like to be added**:
Add the support for a pinch to zoom gesture for zooming in graphs

**Why is this needed**:
When looking at graphs in the dashboard, it's sometimes necessary to zoom in to get more details. This is very hard to achieve by changing the date/times of the timepicker. Supporting pinch to zoom (if that is possible) would be a great enancement.

**Additional context**:

**Comment by adriankumpf** [comment]
Such a functionality would have to be implemented by [Grafana](https://github.com/grafana/grafana). We can only use what Grafana offers.
