### ISSUE TITLE
grafana Charges display not updating

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#89]
Since getting TeslaMate configured and running I've since charged our car 2 times. Before it was showing our 1st charge, now it's only showing our most recent charge at all times. No matter what time I change the time range to, it's always showing 1 charge. How can this be corrected/fixed?

![Capture](https://user-images.githubusercontent.com/19696424/62974419-0a48cf80-bdcd-11e9-979b-0eead2fdf548.PNG)

Charge Details shows the two charges just fine, too

![Capture1](https://user-images.githubusercontent.com/19696424/62974514-3f552200-bdcd-11e9-993e-ac97fe97281d.PNG)

**Comment by adriankumpf** [comment]
I need more info on this. Could you: 

1. sign in with the default admin user (password is `admin`)
2. go to the Charges Dashboard
3. Click on "Charges" above the table, then "Edit"
4. in the text input field scroll to the bottom and remove those two lines:
    
   ```SQL
   WHERE
      distance >= 0 AND (charge_energy_added IS NULL OR charge_energy_added > 0.1);
   ```

5. click outside the text input to apply the changes

Does it now show the 2nd charge?

**Comment by adriankumpf** [comment]
I might have found the bug. Can you verify that this query works (replace the everything in step 4 with this):

```SQL
WITH data AS (
    SELECT
        (extract(epoch FROM start_date) * 1000) - 1000 AS start_date_ts,
        extract(epoch FROM end_date) * 1000 AS end_date_ts,
        start_date,
        end_date,
        CONCAT_WS(', ',
            COALESCE(addresses.name,
                CONCAT_WS(' ',
                    addresses.road,
                    addresses.house_number)),
            addresses.city) AS address,
        g.name as geofence_name,
        charge_energy_added,
        duration_min,
        start_battery_level,
        end_battery_level,
        start_range_km,
        end_range_km,
        calculated_max_range,
        outside_temp_avg,
        c.id,
        lag(end_range_km) OVER (ORDER BY start_date) - start_range_km AS range_loss,
        p.odometer - lag(p.odometer) OVER (ORDER BY start_date) AS distance,
        cars.efficiency
    FROM
        charging_processes c
    LEFT JOIN positions p ON p.id = c.position_id
    LEFT JOIN cars ON cars.id = c.car_id
    LEFT JOIN addresses ON addresses.id = c.address_id
    LEFT JOIN geofences g ON g.address_id = c.address_id
WHERE
    c.car_id = $car_id
    /* where $__timeFilter(start_date) */
ORDER BY
    start_date
)
SELECT
    start_date_ts,
    end_date_ts,
    start_date,
    end_date,
    COALESCE(geofence_name, address) as address,
    charge_energy_added,
    charge_energy_added * 60 / NULLIF (duration_min, 0) AS charge_energy_added_per_hour,
    convert_km((end_range_km - start_range_km) * 60 / NULLIF (duration_min, 0), '$length_unit') AS range_added_per_hour_$length_unit,
    duration_min,
    start_battery_level,
    end_battery_level,
    convert_km(start_range_km, '$length_unit') AS start_range_$length_unit,
    convert_km(end_range_km, '$length_unit') AS end_range_$length_unit,
    convert_km(distance, '$length_unit') AS distance_$length_unit,
    range_loss * efficiency AS consumption_kWh,
    range_loss * efficiency / NULLIF (distance, 0) * 100 * 
      CASE WHEN '$length_unit' = 'km' THEN 1
           WHEN '$length_unit' = 'mi' THEN 1.60934
      END AS consumption_kWh_100$length_unit,
    convert_km(calculated_max_range, '$length_unit') AS calculated_max_range_$length_unit,
    convert_celsius(outside_temp_avg, '$temp_unit') AS outside_temp_avg_$temp_unit,
    id
FROM
    data
WHERE
    (distance >= 0 OR distance IS NULL) AND (charge_energy_added IS NULL OR charge_energy_added > 0.1);
    
```

**Comment by natrlhy** [comment]
Indeed, the 2nd query edit shows both now...

![Capture](https://user-images.githubusercontent.com/19696424/62978991-75979f00-bdd7-11e9-9f26-fad91d0824fb.PNG)

**Comment by adriankumpf** [comment]
Okay. I updated the grafana image.

**Comment by natrlhy** [comment]
Man you're quick! Thanks! Ran:

`docker-compose pull`
`docker-compose up -d`

Charges graph is now showing both charges! Thanks @adriankumpf!

**Comment by natrlhy** [comment]
I'm still seeing both charges show up regardless of the time frame selected, however

**Comment by adriankumpf** [comment]
Cool! Thanks for reporting it. I didn't even notice the very first charge was missing.

> I'm still seeing both charges show up regardless of the time frame selected, however

Yeah, filtering by date is still disabled. I forget to enable it. The next release will fix that. But not today :)

**Comment by natrlhy** [comment]
> Cool! Thanks for reporting it. I didn't even notice the very first charge was missing.
Glad I could help! :)

> Yeah, filtering by date is still disabled. I forget to enable it. The next release will fix that. But not today :)

No worries, being a new owner I don't have much history... YET! :)
