### ISSUE TITLE
How do I connect to Postgres DB running on my hosted instance

### ISSUE THREAD

**Issue by rameshputrevu** [adriankumpf/teslamate#902]
Hello All,

I would like to connect to Postgres DB running on my instance? I am trying to connect from from pgAdmin but getting a 'timeout expired' error.  Can you please help me connect to my db instance?

![image](https://user-images.githubusercontent.com/49599861/92347317-8ff88680-f084-11ea-88f7-413a8ec9c5b8.png)

**Comment by DrMichael** [comment]
You need to expose the database in the docker-compose.yml with:

```
    ports:
      - 5432:5432
```

**Comment by rameshputrevu** [comment]
Thank you!
