### ISSUE TITLE
Traffic delays create new "drives"

### ISSUE THREAD

**Issue by thehoff** [adriankumpf/teslamate#904]
Issue/Bug: When stopped at traffic lights for X time it will generate a new drive.

Extended delays at traffic lights should not cause the generation of a new "drive" as the travel was a single trip.

Replication: Drive to a location and pause for 60+ seconds. New trip will be created.

Question: Is there a runtime/setting that can be modified to increase the timeout of a drive and the starting of a new on?

Thanks

**Comment by olexs** [comment]
A new drive should only start if the car is switched to Park. Do you do that while sitting at the lights?

**Comment by EasternPA** [comment]
Not OP but that just happened to me. I'm only on day 3 with the car and setup TeslaMate within 24 hours. I've been busy creating geofences for my popular stops to replace the township names and a destination came up where I sat waiting for traffic to clear so I could turn left. I didn't even think I came to a complete stop there, but yeah, it shows up as the start of a new drive.

**Comment by adriankumpf** [comment]
As with all potential bugs or unexplained behavior, please check the logs and provide the relevant parts, if possible.
