### ISSUE TITLE
How to resume logging when on the intranet?

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#91]
Sorry not really an issue but a questions - I was looking to understand on how to resume logging when running this locally and not exposed online.

The documentation says to use Tasker or Shortcuts and all this:
PUT https://teslamate.your-domain.com/api/car/$car_id/logging/resume

I am running Docker on my Synology NAS; and and it its IP is 192.168.1.2, what do I use? And is there a way to tickle this IP without a PUT call? Would it be something like:
http://192.168.10.2:3000/api/car/$car_id/logging/resume

And I presume $car_id is the ID column from the cars table and not the eid or vid? 

Thanks in advance!

**Comment by natrlhy** [comment]
It would be:

`http://192.168.10.2:4000/api/car/1/logging/resume`

to suspend logging:

`http://192.168.10.2:4000/api/car/1/logging/suspend`

grafana runs on port 3000 and the actual API/teslamate container is running/listening on port 4000

**Comment by Rfvgyhn** [comment]
Suspend and resume don't respond to anything but `PUT`. Tasker or Shortcuts should work as long as your car is in range of your wifi network (and assuming your nas is accessible via wifi).

If that's not the case, you'll have to either invoke suspend/resume via the web interface ui button or  send the request yourself via something like `curl`. If you're on windows and don't have `curl` you can run a powershell script that uses the `Invoke-WebRequest` cmdlet. Something like [this script](https://gist.github.com/Rfvgyhn/55c146dcc2615261e004c28cc987a425#file-teslamate-resume-ps1). Replace `$domain` with `http://192.168.10.2:4000`

**Comment by bahree** [comment]
This is great - thank you. I also wanted to share that cURL it not out of the box in PowerShell - at least on Windows 10, so one doesn't need to do anything else. Ditto on SSH btw, and not need for putty or anything. Perhaps if we update the readme it might help others or point them back to this thread. Thanks again.

**Comment by Dustin781** [comment]
Hi there,

I tried that, but I only get a "Not Found" on the website. However, the sleep attempt is not aborted. I wanted to connect it to the front door so that logging starts again as soon as I open the door.

Tesla Mate version 1.25.2
http://192.168.xx.15:4000/api/car/1/logging/resume

Has the path changed?
