### ISSUE TITLE
Will this be a show stopper? API blocked?

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#911]
https://www.reddit.com/r/TeslaLounge/comments/iqbt86/teslafi_and_other_3rd_party_stuff_apparently/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

I’m not seeing this yet but sure hope TeslaMate will survive!

EDIT: It may be limited to anyone running TeslaMate in AWS from some quick reads. I self host...

**Comment by empperi** [comment]
Can confirm that TeslaMate was **not** affected as a software. I'm also running TeslaMate in a server which is not in a cloud and it has worked flawlessly the whole time.

I would say this issue can be closed since the problem was definitely not in TeslaMate.

**Comment by natrlhy** [comment]
Yeah not an issue with TeslaMate at all. Self hosted or not on AWS seems fine...
