### ISSUE TITLE
Filter Cars

### ISSUE THREAD

**Issue by akac** [adriankumpf/teslamate#918]
**What would you like to be added**:
Select which car shows up first, or to visually filter one of the cars. 

**Why is this needed**:
We have two cars. My wife has no interest in the data and it gets annoying for me to go into Grafana and have to constantly hide her car (hers was first, so it shows up first). 

Ideally I'd like to keep capturing her data, but to make sure that unless I need to see her's -  I'm only seeing my car.

**Additional context**:
When I've tried to hide her car in Grafana it tells me that it can't save the changes because they are provided by Teslamate.

**Comment by tobiasehlert** [comment]
This is pretty similar to the request I've added, which is to totally disable logging for a car.
My issue is https://github.com/adriankumpf/teslamate/issues/1049
