### ISSUE TITLE
Issue after export/import of Postgres DB to another instance

### ISSUE THREAD

**Issue by rameshputrevu** [adriankumpf/teslamate#923]
Hello,

I exported the DB from one instance (in cloud running for last 7 days) and imported the DB into another brand new instance started locally. All the dashboards are working fine when I directly go to grafana via  localhost:3000. However when I go teslamate via localhost:4000 and try to go to dashboards, I am getting error.

What could be going wrong?

I appreciate the help!
Regards

**Comment by Dulanic** [comment]
Edit your grafana location in settings. It doesn't have the right URL if you don't set it.
