### ISSUE TITLE
Suggestion - In dashboard can we have the car names instead of ID?

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#93]
So I am curious if this is a simple join or something more - when looking at the various dashboards, instead of the car numeral ("1") in my case, is it possible to show the Car name instead? This is the drop down in the top left corner.

**Comment by adriankumpf** [comment]
Yes, that would be great! I haven't figured out how to do that yet. But there's probably a clever way.

**Comment by bahree** [comment]
When you insert the car ID in the database, perhaps if we add a column and call it CarName or something similar? From Tesla, the API returns this as "display_name" and it seems you are already logging this. 

Here is what I saw - looks like a function called create_new in vehicles.ex. Just using the display_name in addition to everything else might work.

```
Logger.info("Found car '#{vehicle.display_name}'")

    {:ok, car} =
      case Log.get_car_by_eid(vehicle.id) do
        nil ->
          properties = Identification.properties(vehicle)

          Log.create_car(%{
            eid: vehicle.id,
            vid: vehicle.vehicle_id,
            model: properties.model,
            efficiency: properties.efficiency
          })

        car ->
          {:ok, car}
      end
```
I don't know Elixir, but sometime back I had written a [Tesla Token Generator](https://github.com/bahree/TeslaTokenGenerator) (for windows) and you can see the details on what the API returns [here](https://github.com/bahree/TeslaTokenGenerator/blob/master/TeslaTokenGenerator/VehicleDetails.cs).

Happy to try it out and help test/debug. 

Thanks again!

**Comment by adriankumpf** [comment]
Yes, storing the `display_name` like you proposed would become necessary. The remaining part is showing the `display_name` in grafana while at the same time combining it with the `id` i.e. selecting the car's name in the dropdown should actually set the corresponding `car_id`. Does that make sense?

**Comment by bahree** [comment]
Do you think, it could be something like car_id - display_name. So it would show up like 1 - WhateverCoolNameYourCarHas - or something along those lines.

**Comment by adriankumpf** [comment]
If there is some way to replace text inside a variable, that could work!

Another idea is to use two variables: one to select the name and another hidden one that references the name variable fetches the corresponding car id.

**Comment by adriankumpf** [comment]
Oh, there is way to create a key/value variables in Grafana! 

```SQL
SELECT name AS __text, id AS __value FROM cars
```
