### ISSUE TITLE
Add "Actual Range" as a metric

### ISSUE THREAD

**Issue by jun3280net** [adriankumpf/teslamate#94]
Awesome tool you've developed!  Wondering if you could add Actual Range as a metric.  Would like to see range numbers match the Tesla app.  Thank you

**Comment by adriankumpf** [comment]
Sure, adding the Actual Range to the web interface (the one running on Port 4000) would be no problem at all. Or do you want to see the range in Grafana?

**Comment by jun3280net** [comment]
If it isn't too much trouble - both would be great please.
