### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by brombomb** [adriankumpf/teslamate#940]
I was reading through some of the issues and found one that I thought would be pretty easy to tackle.  Then I remembered Digitial Ocean's Hacktoberfest is coming up.  It's a super-easy way to get contributions.   

https://hacktoberfest.digitalocean.com/details#maintainers

I'm happy to help and super excited after installing last night.  Just thought why not share.

**Comment by adriankumpf** [comment]
Contributions are very welcome! A selection of issues that are good for getting started are marked with ["good first issue"](https://github.com/adriankumpf/teslamate/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). For all other issues and requests, contributions are of course highly appreciated as well.

**Comment by GtHbbrr** [comment]
do you run Teslamate in Digital Ocean cloud?

**Comment by DrMichael** [comment]
@adriankumpf Perhaps you should tag those issues also with a Hacktoberfest label?

**Comment by adriankumpf** [comment]
Done!

**Comment by ayonix** [comment]
After reading the hacktoberfest rules i noticed that contributions to the hacktoberfest are only counted if the repository has the topic hacktoberfest or pull requests get the label hacktoberfest-accepted. Labelling issues with hacktoberfest is for visibility only i guess, people won't get credit for it.

**Comment by brombomb** [comment]
They had to change some of the rules last week due to spammy low effort PRs.  Thanks for checking up on it.
