### ISSUE TITLE
Proxy Setting

### ISSUE THREAD

**Issue by myi2000** [adriankumpf/teslamate#941]
Hello, How to setup teslamate use proxy running in docker.  I tried the following but noavail
- by adding HTTP_PROXY and HTTPS_PROXY in docker.yml under teslamate/environment section
- by creating ~/.docker/config.json adding proxies section; and also  /etc/systemd/system/docker.service.d/http-proxy.conf

Please help
thanks

**Comment by smoothdvd** [comment]
Is there any solution?
