### ISSUE TITLE
Update SW version in Teslamate homescreen?

### ISSUE THREAD

**Issue by DrMichael** [adriankumpf/teslamate#943]
**What would you like to be added**:
TM shows nicely, when a new update is available. Would it be possible to also show the version of the update?

**Why is this needed**:
Currently you have to go to the car to see the SW version, which is up to installing.

Of course a question, whether the API provides that information...

**Comment by JakobLichterfeld** [comment]
SW version of pending SW update is available within the API. I would suggest to have it as a hovertext within the dashboard.

**Comment by DrMichael** [comment]
That'd be great.

I just realised, that the hover text is not visible for me:
![image](https://user-images.githubusercontent.com/8087682/95012738-52632b00-063b-11eb-9670-7d844de41f4b.png)

**Comment by JakobLichterfeld** [comment]
> That'd be great.
> 
> I just realised, that the hover text is not visible for me:

Wired, for me it shows update available. I would suggest to include the verision in it.

**Comment by DrMichael** [comment]
Well, perhaps because of the message at the bottom:
![image](https://user-images.githubusercontent.com/8087682/95012890-88ed7580-063c-11eb-8ee9-70dc9c46e792.png)

I am on the latest edge: 1.20.0-dev

**Comment by JakobLichterfeld** [comment]
Even if it is OT: What about the hover text of the lock?

**Comment by DrMichael** [comment]
Both were invisible.

**Comment by cwanja** [comment]
Is there any way to link to Teslascope for quick access to release notes?
