### ISSUE TITLE
Export Drive Data in TeslaFI Format

### ISSUE THREAD

**Issue by sw1002** [adriankumpf/teslamate#945]
**What would you like to be added**:
Ability to export drive data in Teslafi Format 

**Why is this needed**:
Migration from Teslamate to another logging solution

**Additional context**:

**Comment by luxus** [comment]
It would be great if this would be possible.. 
I think teslamate is great, but it would be nice if it would be possible to checkout other apps with the data from teslamate

**Comment by adriankumpf** [comment]
The TeslaFi format basically includes the raw Tesla API data. TeslaMate does not store this much data and also partly uses other Tesla API endpoints than TeslaFi. Therefore it is not possible to export the data in this exact format.

If data in CSV format is enough for you, then try the following:

```
$ docker-compose exec database psql teslamate teslamate -c \
    "COPY (select * from charges where date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charges.csv

 $ docker-compose exec database psql teslamate teslamate -c \
    "COPY (select * from charging_processes where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charging_processes.csv

 $ docker-compose exec database psql teslamate teslamate -c \
    "COPY (select * from positions where date > '2020-01-20') TO STDOUT WITH CSV HEADER" > positions.csv

 $ docker-compose exec database psql teslamate teslamate -c \
    "COPY (select * from drives where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > drives.csv
```

**Comment by muffstic** [comment]
> 
This works great on raspberrypi but doesn't work on windows. Is there a way to get this to work on windows? I get this error when running command on windows docker container: service "database" is not running container #1.

**Comment by muffstic** [comment]
> The TeslaFi format basically includes the raw Tesla API data. TeslaMate does not store this much data and also partly uses other Tesla API endpoints than TeslaFi. Therefore it is not possible to export the data in this exact format.
> 
> If data in CSV format is enough for you, then try the following:
> 
> ```
> $ docker-compose exec database psql teslamate teslamate -c \
>     "COPY (select * from charges where date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charges.csv
> 
>  $ docker-compose exec database psql teslamate teslamate -c \
>     "COPY (select * from charging_processes where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > charging_processes.csv
> 
>  $ docker-compose exec database psql teslamate teslamate -c \
>     "COPY (select * from positions where date > '2020-01-20') TO STDOUT WITH CSV HEADER" > positions.csv
> 
>  $ docker-compose exec database psql teslamate teslamate -c \
>     "COPY (select * from drives where start_date > '2020-01-01') TO STDOUT WITH CSV HEADER" > drives.csv
> ```

This works great on raspberrypi but doesn't work on windows. Is there a way to get this to work on windows? I get this error when running command on windows docker container: service "database" is not running container https://github.com/adriankumpf/teslamate/pull/1.
