### ISSUE TITLE
Integrate commands in MQTT

### ISSUE THREAD

**Issue by ultratoto14** [adriankumpf/teslamate#950]
**What would you like to be added**:
Teslamate is really convenient to get the all the needed data without vampire drain. It could be a great addition to add the ability to call the commands as climate, door lock and so on.

**Why is this needed**:
It can prevent having different components for the same "integration". Make teslamate the only service working with the Tesla

**Additional context**:
I tried numerous integrations and teslamate is the more stable for me.

**Comment by LelandSindt** [comment]
See this comment/thread for discussion on this topic. 

https://github.com/adriankumpf/teslamate/issues/601#issuecomment-616845343
