### ISSUE TITLE
Consumption per Month dashboard

### ISSUE THREAD

**Issue by riesi77** [adriankumpf/teslamate#951]
**What would you like to be added**:
I would love to see a new dashboard giving me the overview of my consumption (Wh/km) per month (maybe independent of the year)

**Why is this needed**:
It would give me a great overview of my consumption dependent of the season (winter vs. summer)

**Additional context**:

**Comment by pihomeserver** [comment]
Something like that ? 

<img width="1118" alt="PerMonth" src="https://user-images.githubusercontent.com/3817578/94960348-06a56a00-04f3-11eb-884c-817d25724e4d.png">

**Comment by riesi77** [comment]
Exactly. My original thought was to make it independent of the year (so October 2020 would go into October as well as October 2021) - but I'm not sure if this is a good idea. Having the Distance in the dashboard is better.

**Comment by pihomeserver** [comment]
This version groups by month without taking the year into account
If you confirm that you can create dashboards once authenticated i can share with you the JSON file file of the dashboard

**Comment by riesi77** [comment]
I tried - but there is no new dashboard button (using the docker installation).

**Comment by pihomeserver** [comment]
Docker too.
On bottom left you have a user icon, you log in with credentials admin/admin and no need to change the password

**Comment by riesi77** [comment]
Nice. Yes. Now I can add new dashboards. If you are so kind and provide me your json, I can add it. However, for the product it would be great to have that contained in a future update, too.

**Comment by pihomeserver** [comment]
Sure, I will when getting back home. If it works for you we can push a request to Adrian

**Comment by riesi77** [comment]
Very cool. Finally I managed to import it (also change the car's name). Thanks for your support. A very useful dashboard!
