### ISSUE TITLE
Fleet wide data comparison

### ISSUE THREAD

**Issue by rhatguy** [adriankumpf/teslamate#953]
**What would you like to be added**:  Optional fleet wide data comparison of certain metrics like degradation or wh/mi.  Similar to teslafi.

**Why is this needed**:  Sometimes things like degradation or wh/mi are helpful to know in contextual comparison to others with the same car.  For instance, is 10% degradation after 20k miles normal?  Is 245 wh/mi for a M3 LR AWD normal?

**Additional context**:  Other locally hosted tools like teslalogger are adding this type of data.  Perhaps it would be easy enough to add the ability to feed data into their existing implementation?  It would also be super cool to be able to pull this data locally into our teslamate implementations to display natively on our existing dashboards.

https://github.com/bassmaster187/TeslaLogger
https://teslalogger.de/degradation.php

**Comment by riesi77** [comment]
+1

**Comment by adriankumpf** [comment]
This feature will never happen, as it would require a central server infrastructure. Those who wish to compare their data with others are better off with cloud services.
