### ISSUE TITLE
On Updates page when tracking 2+ cars, Number of Updates received is wrong.

### ISSUE THREAD

**Issue by rndpsn** [adriankumpf/teslamate#955]
**Describe the bug**

On the Updates page, when tracking 2 or more cars, Number of Updates received is showing as the sum of the number of updates received by all cars.

**Expected behavior**

The Number of Updates received for each should be equal to the number of updates each of the cars has received.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have 2+ cars in a Tesla account.
2. Go to Updates page.
3. The values in the "Updates" box for all the cars are the same, and the value equals the sum of the number of updates received by all cars.

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

![image](https://user-images.githubusercontent.com/72171580/94748733-d618d100-0336-11eb-9fcd-c774c5dbfb0a.png)

**Data**

**Environment**

- TeslaMate version:1.19.4
- Type of installation: Docker
- OS TeslaMate is installed on: Docker
- User OS & Browser: Fedora Linux 32, Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- Others:

**Comment by DrMichael** [comment]
Fixed in next version: https://github.com/adriankumpf/teslamate/pull/840
