### ISSUE TITLE
Charging While Offline Interpreted Incorrectly

### ISSUE THREAD

**Issue by Simple-Complexity** [adriankumpf/teslamate#96]
Where I am, the only supercharger nearby is inside of a garage where there is no cell/wifi signal. In this case, the car is offline while charging. This leads to the Teslamate thinking that the trip to the charger and back is a single trip rather than a trip, charge, and another trip.

This results in drive details which encompass the charge duration and skewed metrics. Attached are the summaries and one detailed view of a charge for reference.

If a car goes offline and gains a significant amount in SoC it should be considered a charge session that begins when the car went offline and ends when it came back online. In addition, the previous drive should be stopped when the charge session began (or the car went offline) and a new drive should begin.

![OfflineChargingEg1](https://user-images.githubusercontent.com/3229786/63138549-cd790600-bf8f-11e9-881e-7c0357303d02.PNG)
![OfflineChargingEg2](https://user-images.githubusercontent.com/3229786/63138556-d23dba00-bf8f-11e9-9394-3daf699e8189.PNG)
![OfflineChargingEg3](https://user-images.githubusercontent.com/3229786/63138563-d79b0480-bf8f-11e9-8b66-d5121b06a981.PNG)

**Comment by adriankumpf** [comment]
Now that's an interesting corner case.

> If a car goes offline and gains a significant amount in SoC it should be considered a charge session that begins when the car went offline and ends when it came back online. In addition, the previous drive should be stopped when the charge session began (or the car went offline) and a new drive should begin.

I like that solution.

**Comment by Simple-Complexity** [comment]
Glad I was able to find it. I suppose I should learn Elixer so I can help you out.

**Comment by adriankumpf** [comment]
Oh, I'd love to see pull requests!

I'm gonna try to fix it myself soon. Real-world testing will be difficult though. You'll need to verify then if it's really fixed.

**Comment by bahree** [comment]
So I have a similar edge case. In my office the parking is in the basement (it's in downtown) - a few floors down with no network connectivity. So when I enter there is connectivity and at the end of the day when I leave it thinks the car has been driving all that time. 

So if we adding a option to detect SoC we can also perhaps add distance or something.

I know edge case and probably not useful for many so please feel free to ignore too. 🤓

**Comment by adriankumpf** [comment]
> I know edge case and probably not useful for many so please feel free to ignore too. 🤓

There are already two of you. Reason enough to fix it ;) I just pushed a fix to the dev branch which should already handle your case: when the car comes back online and notices that it was offline for at least 15 minutes, the previous drive is properly logged.

I'll let you know when the new release is available.

**Comment by bahree** [comment]
Awesome thank you. Happy to test it out.

**Comment by adriankumpf** [comment]
v1.6.0 is available. Please test it out.

**Comment by bahree** [comment]
Awesome thank you. Will pull later today. Would the existing data stay as is when I update the container? Sorry not sure on the specifics on that front.

**Comment by adriankumpf** [comment]
Yep, the docker-compose.yml specifies a few "volumes" which are the docker mechanism for persisting data generated / used by Docker containers.

**Comment by Simple-Complexity** [comment]
Thanks, I'll pull it today, but likely won't be able to test this edge case for a could days (currently fully charged 😂)

**Comment by adriankumpf** [comment]
@bahree any feedback on this front? :) Does v1.6 handle your case correctly? I still couldn't test it myself.

**Comment by adriankumpf** [comment]
Great! There should be two data points. I'll bet the seconds one becomes visible if you zoom out a few seconds.

**Comment by Simple-Complexity** [comment]
You're right! I wonder why it gets cut off.

Closing as it seems the issue is resolved.
