### ISSUE TITLE
support for user/driver profile data

### ISSUE THREAD

**Issue by Kosta-Github** [adriankumpf/teslamate#963]
**What would you like to be added**:

I would like to see some support for user/driver profile data, e.g., in order to differentiate between my wife and me as a driver.

**Why is this needed**:

See above.

**Additional context**:

The Tesla API provides `user_id` within the [vehicle data](https://www.teslaapi.io/vehicles/state-and-settings#vehicle-data) response already. But I am unsure, if this is the actual driver profile ID or an ID tied to the tesla account, which would be the same for my wife and myself if we are using the same tesla login...

**Comment by adriankumpf** [comment]
As far as I know the user_id has nothing to do with the driver profile. Presumably it indicates the logged in API user.

**Comment by JakobLichterfeld** [comment]
There is no value in the api for the driver profile from what I know. So it would be only possible to assign drives manually or with some automation, linke drive to location x always user a, drive to location y always user b.
