### ISSUE TITLE
On Trip page when tracking 2+ cars, the Battery Level graph is mixed up between the cars.

### ISSUE THREAD

**Issue by rndpsn** [adriankumpf/teslamate#967]
**Describe the bug**

On Trip page when tracking 2+ cars, the Battery Level & Range graph is a mixed up between the cars.

**Expected behavior**

The battery level graph for each car should match the graph on the Charge Level page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have 2+ cars in a Tesla account.
2. Go to the Trip page.
3. Check the Battery Level & Range graph.

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

The battery levels of my 2 cars are correct on the graphs on the Charge Level page, where car # 1's charge level was between 72-84% and car # 2's between 34-43%:

![image](https://user-images.githubusercontent.com/72171580/94982500-cb556c00-04ef-11eb-9527-5b8f4c2c16e4.png)

But on the Trip page, the Battery Level & Range graph looks like the graphs for both cars mixed up together. The graphs for both car # 1 and car # 2 are always the same -- even when there is no data for one car (only one car was driven for that day with date range set to "today so far"):

![image](https://user-images.githubusercontent.com/72171580/94982545-2b4c1280-04f0-11eb-8ccc-d05d51fddf2d.png)

Looking closer, the Battery Level & Range graph started off at 74% (car # 2) then dropped to 40% (car # 1) and later jumps back up to 82% (car # 2:)

![image](https://user-images.githubusercontent.com/72171580/94982599-ae6d6880-04f0-11eb-9ea2-c4d45de8155c.png)

**Data**

**Environment**

- TeslaMate version: 1.19.4
- Type of installation: Docker
- OS TeslaMate is installed on: Docker
- User OS & Browser: Fedora Linux 32, Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- Others:

**Comment by adriankumpf** [comment]
Fixed with #843
