### ISSUE TITLE
Charge report

### ISSUE THREAD

**Issue by nottheedge** [adriankumpf/teslamate#969]
**What would you like to be added**: It would be great to have a charge report based on location. 

**Why is this needed**: My employer provides me a possibility to charge but I need to report to him how much energy has been added. The charger doesn’t have a smart-meter build in. Because the charges are recorded this could be realised by a new dashboard. 

The charge location should be selectable.

**Additional context**:

**Comment by DrMichael** [comment]
Actually, you have that within the Charging Stats dashboard...

**Comment by nottheedge** [comment]
Sorry, maybe I'm blind. 
Indeed I do have some statistics in dashboard about charges, but it's not what I meant.

It would be cool to have as example the charges dashboard but with a possibility to select as filter the location where I charged. If location is selected the referring charging sessions should be displayed.

Maybe just the dashboard charges need to be enhanced with the filter for location.

Could you tell me where you mean to get that inside charge-stats-dashboard?

Regards

**Comment by DrMichael** [comment]
Well, scroll don win the Charging Stats und you'll see:
![image](https://user-images.githubusercontent.com/8087682/95021930-3def5480-0674-11eb-9ceb-d88230b5ec6f.png)

**Comment by nottheedge** [comment]
Ok, got it what you mean. Is there a way just to limit a specific location instead all locations I charged within last month?

**Comment by DrMichael** [comment]
Does not make sense in the summary. If you want to have the individual charges, take that:
![image](https://user-images.githubusercontent.com/8087682/95056406-f9f06400-06f4-11eb-9cc0-ad00b6fb12b6.png)

**Comment by nottheedge** [comment]
That's it.

**Comment by DrMichael** [comment]
Well, set a geofence at your employer's charge station, then open Charges dashboard and select that Geofence...

**Comment by nottheedge** [comment]
Question answered
