### ISSUE TITLE
New statistics dashboard fails to load

### ISSUE THREAD

**Issue by wishbone1138** [adriankumpf/teslamate#974]
Loading new statistics dashboard results in "no data" with the following error log.  I did try to set the environmental variable TZ to see if that would resolve this error without much luck.

```
db_1         | 2020-10-05 17:57:33.353 UTC [51] ERROR:  function date_trunc(unknown, timestamp without time zone, unknown) does not exist at character 43
db_1         | 2020-10-05 17:57:33.353 UTC [51] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
db_1         | 2020-10-05 17:57:33.353 UTC [51] STATEMENT:  WITH data AS (
db_1         |    SELECT
db_1         |      drives.*,
db_1         |      date_trunc('month', start_date::TIMESTAMP WITHOUT TIME ZONE, 'GMT') as local_period
db_1         |    FROM drives)
db_1         |  SELECT
db_1         |    EXTRACT(EPOCH FROM date_trunc('month', local_period))*1000 AS date_from,
db_1         |    EXTRACT(EPOCH FROM date_trunc('month', local_period + ('1 ' || 'month')::INTERVAL))*1000 AS date_to,
db_1         |    CASE 'month'
db_1         |      WHEN 'month' THEN to_char(local_period, 'YYYY Month')
db_1         |      WHEN 'year' THEN to_char(local_period, 'YYYY')
db_1         |      WHEN 'week' THEN 'week ' || to_char(local_period, 'WW') || ' starting ' || to_char(local_period, 'YYYY-MM-DD')
db_1         |      ELSE to_char(local_period, 'YYYY-MM-DD')
db_1         |    END AS display,
db_1         |    local_period AS date,
db_1         |    sum(GREATEST(start_rated_range_km - end_rated_range_km, 0) * car.efficiency * 1000) /
db_1         |    convert_km(sum(distance)::numeric, 'mi') as efficiency_net_mi
db_1         |  FROM data
db_1         |  JOIN cars car ON car.id = car_id
db_1         |  WHERE
db_1         |    car_id = '1' AND
db_1         |    start_date BETWEEN '2010-10-05T17:57:32.322Z' AND '2020-10-05T17:57:32.322Z'
db_1         |  GROUP BY date
db_1         |  ORDER BY date
```

**Environment**

- TeslaMate version: latest
- Type of installation: Docker
- OS TeslaMate is installed on: ubuntu
- User OS & Browser: win/firefox
- Others:

**Comment by rndpsn** [comment]
I've the same problem.  I'm on PostgreSQL 11 and I think I need to upgrade to PostgreSQL 12 (which provides the new date_trunc() function), but I haven't figured out a way to do that yet.  

If I just edit docker-compose.yml to PostgreSQL 12, it would not start, with this error:

```
2020-10-05T06:24:40.905101190Z 2020-10-05 06:24:40.904 UTC [1] FATAL:  database files are incompatible with server
2020-10-05T06:24:40.905387089Z 2020-10-05 06:24:40.904 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.4 (Debian 12.4-1.pgdg100+1).
```

**Comment by wishbone1138** [comment]
> I've the same problem. I'm on PostgreSQL 11 and I think I need to upgrade to PostgreSQL 12 (which provides the new date_trunc() function), but I haven't figured out a way to do that yet.

I've noticed that the new docker-compose.yml file actually mentions 13 now.   Digging into how to upgrade, will let you know if I figure it out.

**Comment by wishbone1138** [comment]
Closing this out, upgrading postgres as listed above worked for me.  Make sure you do it in the right order, per the instructions.  

However, I couldn't get the restore command to work so I had to use a different method for restoring the database.  I couldn't get docker-compose to accept the input file correctly, so I had to use docker.  Never figured that one out.

` docker exec -i 3061fff219d6 psql -U teslamate -d teslamate < 20201005_teslamate.bck`

**Comment by adriankumpf** [comment]
Interesting. We were not aware that postgres needs to be updated. I wonder if it is possible to adapt the query so that it works with older versions.

**Comment by wishbone1138** [comment]
> 
> 
> Interesting. We were not aware that postgres needs to be updated. I wonder if it is possible to adapt the query so that it works with older versions.

Looks like date_trunc is different in 11 than 13 (no optional time zone option in 11).  If the function call can be re-written without the timezone option, it should work in both.  I'd have to really dig into the code to see how that breaks his logic though.  I know that timezones was an issue in the original thread on this dashboard.
https://www.postgresql.org/docs/11/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC
https://www.postgresql.org/docs/13/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC

**Comment by DrMichael** [comment]
Well, without the timezone option the start would be always midnight UTC... That does not really harm as long as you're close to UTC, Australia e.g. looks different.
