### ISSUE TITLE
Suggestion - Updating the Drive Details dashboard with seperate graph plots?

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#98]
Just a suggestion not sure what others things about it - I personally prefer the driving details that tesla-apiscraper has where it breaks up some of the elements such as Speed and Power Reserve (e.g. [see this](https://raw.githubusercontent.com/lephisto/tesla-apiscraper/master/screenshots/teslametrics_v2_1.png)). 

All the plot lines with all the data is an overkill for me and takes me longer to track and see just the subset of data points I was interested in. 

I was wondering if it is possible to do a similar graph, combined with the map. Essentially a mashup of the two? Separating the data points, do take up more space but possibly something to try? And I don't want to lose the maps here. :)

**Comment by bahree** [comment]
OK, I just realized and adding this here for the benefit of others - clicking on one of the data time series in the legend, filters on that and shows only that. I didn't know this was possible. Doh. Still different views might be useful.

**Comment by nullgel** [comment]
I'm coming from tesla-apiscraper as well. So far with teslamate, I'm having a tougher time getting a nice dashboard like I was able to piece together in apiscraper. Unless I'm doing it wrong, teslamate seems to require more db scripting. I would definitely like to see more examples with the Gauge visualization, for example. I can't seem to create a simple one just to show the current battery level.

It was a minimal amount of work to make this dashboard that I was using in apiscraper:
![Annotation 2019-08-17 204308](https://user-images.githubusercontent.com/27741277/63218759-a6f1d100-c12f-11e9-805c-c695f4f88f41.jpg)

I really think the backend of teslamate is way better, so I'm hoping the front end becomes more non-dba friendly in the future.

**Comment by natrlhy** [comment]
Nice!

**Comment by adriankumpf** [comment]
@nullgel That's look really nice! TeslaMate doesn't use a time series database like tesla-apiscraper. That's why some queries have to be written differently. I started working a similar dashboard but it's far from finished: https://gist.github.com/adriankumpf/c0dabfd86c3e163508a8cb4936d4288e  It should provide you with some examples though.

Feel free to open a PR if you make any progress! :)

**Comment by nullgel** [comment]
Oh perfect. This looks great. I'll see what I can do with it.
