### ISSUE TITLE
Statistics Dashboard - No Data

### ISSUE THREAD

**Issue by cmchauvin** [adriankumpf/teslamate#982]
No data in the Statistics dashboard with the following error: 

pq: function date_trunc(unknown, timestamp without time zone, unknown) does not exist
Object
status:400
statusText:"Bad Request"
data:Object
results:Object
message:"pq: function date_trunc(unknown, timestamp without time zone, unknown) does not exist"
config:Object
url:"api/tsdb/query"
method:"POST"
data:Object
retry:0
headers:Object
hideFromInspector:false
message:"pq: function date_trunc(unknown, timestamp without time zone, unknown) does not exist"

**Comment by rndpsn** [comment]
You probably need to upgrade your DB.  See #974

**Comment by cmchauvin** [comment]
Upgrading to postgres 13 and modifying the docker-compose.yml file to match the latest version under the installation guide solved the issue.
