### ISSUE TITLE
teslamate/grafana:latest and grafana v7?

### ISSUE THREAD

**Issue by AnotherDaniel** [adriankumpf/teslamate#983]
Hi Adrian, first of all thank you very much for the work on teslamate - I love it to bits! :-)

One question though: I've updated to 1.20 today, which brings a requirement for grafana v7; however I'm pulling grafana into my dockerized setup as teslamate/grafana, and the :latest tag there still is a version 6 image.

Have I been a bit too early with my pull, and the updated teslamate/grafana is supposed to be available soon? Or should I/can I move over to generic grafana/grafana?

**Comment by AnotherDaniel** [comment]
P.S.: We're missing a 'question' label - this is not an idea, but I wouldn't classify it as an issue, either...

**Comment by adriankumpf** [comment]
The image published with the `latest` tag definitely uses Grafana v7:

<img width="236" alt="Screenshot 2020-10-07 at 17 51 30" src="https://user-images.githubusercontent.com/8999358/95355397-d03a6700-08c5-11eb-90e9-602184a243f5.png">

**Comment by AnotherDaniel** [comment]
Ah now I got it! For whatever reason it didn't work earlier...

Thanks very much!
