### ISSUE TITLE
New Statistics dashboard has timezone=None and displays no data

### ISSUE THREAD

**Issue by jmalcaide** [adriankumpf/teslamate#985]
The new Statistics dashboard fails to display any data, with this error message:

`pq: time zone "" not recognized`

Sure enough, the Time Zone field shows "None". After I input a valid time zone name in that field and reload, it works.

The Dashboard settings show that the value for Time Zone is "Browser default" (CEST in my case). I tried to change it to Europe/Madrid (and save the new setting), but the dashboard keeps showing time zone = None.

I am running a manual installation in a FreeNAS jail, with PostgreSQL 13 and Grafana 7.2.

**Comment by bahree** [comment]
I got a associated issue, but not the same. The timezone in my case always changes to GMT whenever I load the dashboard. When I select my correct timzeone, after reloading its back to GMT.

![image](https://user-images.githubusercontent.com/3529468/95631281-49f26200-0a38-11eb-99b5-cadf199d3fce.png)

My machine's timezone is correct - any ideas? Thanks.

**Comment by DrMichael** [comment]
You could set PGTZ to your timezone for the Grafana container...

**Comment by jmalcaide** [comment]
> You could set PGTZ to your timezone for the Grafana container...

Yes, but that is not documented. Moreover, I found out that the reference to PGTZ was removed from the file CHANGELOG.md as part of a set of changes named "Make time zone configurable”:

https://github.com/adriankumpf/teslamate/commit/af1af873b0293d4a51917bf67ad045e6bbda2e2e#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by DrMichael** [comment]
That dashboard is still kind of WIP... We are waiting for a fix in Grafana. Stay tuned...

> > You could set PGTZ to your timezone for the Grafana container...
> Yes, but that is not documented. Moreover, I found out that the reference to PGTZ was removed from the file CHANGELOG.md as part of a set of changes named "Make time zone configurable”:

Yes, but that was not working. It was recommending setting PGTZ for the Database container, but it should be set for the Grafana container.

**Comment by jmalcaide** [comment]
Ah, OK, understood. Thanks!

**Comment by airmaxx** [comment]
My statistics dashboard also shows no data.

pq: Funktion date_trunc(unknown, timestamp without time zone, unknown) existiert nicht

**Comment by DrMichael** [comment]
You should upgrade to at least Postgres 12, even better to 13...

**Comment by adriankumpf** [comment]
@airmaxx This will be fixed with v1.20.1
