### ISSUE TITLE
How do you log out of the teslamate.yourdomain.com dashboard to disconnect it from the services pulling from the api?

### ISSUE THREAD

**Issue by atc07** [adriankumpf/teslamate#986]
**Describe the bug**

**Expected behavior**

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by maccis** [comment]
You can close the teslamate instance, if you run it in docker run docker-compose down
