### ISSUE TITLE
Drives: How to add odometer to dashboard?

### ISSUE THREAD

**Issue by Eriktesla** [adriankumpf/teslamate#989]
It would be great to have the possibility to view odo_start and odo_end in the **drives** dashboard:

This information is needed for the kilometer administration for the Dutch tax return ;-)

Any help to add odo_start and odo_end in the JSON panel is greatly appreciated.

**Comment by cwanja** [comment]
I think it used to be on the Drivers dashboard, but to reduce the scrolling on the dashboard it was removed. I think it makes more sense on the Drive Details, under the smaller blocks in my opinion.

![Screen Shot 2020-10-08 at 12 27 01 PM](https://user-images.githubusercontent.com/54645561/95493071-93bc4900-0961-11eb-82f2-b196ccf64bed.png)

**Comment by Eriktesla** [comment]
The tax authorities impose the following requirements on the kilometer administration:

Drive date, drive ID, the **start and end position of the odometer** and the departure and arrival address. 

The only items what I miss in the Drives dashboard is odometer start and odometer end.

If those items are available then it is a peace of cake to export all car trips (each trip is a row) to csv format.

**Comment by wooter** [comment]
The fields **start_km** and **end_km** are available in the table **drives**.

I'd have to look into the source to see how to integrate a new query and JSON in the necessary Drives dashboard, but basically you need to 

- add "**start_km, end_km,**" in both **select** queries.
- add 2 Column styles, one for **start_km** and the other for **end_km**

**Comment by roadrash2108** [comment]
I'm on it. Are above columns all you need?

Then I would suggest to build a new dashboard soley for the purpose of "Tax reporting" - what do you think?

**Comment by wooter** [comment]
Yeah, I made it myself already; copying the Drives dashboard into a separate dashboard, and modifying the columns.

I can do a push request, but it's already a crowded table.

**Comment by roadrash2108** [comment]
This would be my proposal for the table:
![Screenshot 2020-10-09 002646](https://user-images.githubusercontent.com/26000761/95519807-2bec1980-09c6-11eb-9690-350e24e922cd.png)

**Comment by Eriktesla** [comment]
Wow I am impressed! That is exact the information what is needed.
Maybe it is possible to add the column with the end date/time of the ride and a column with the duration of the ride. 
That makes it complete.

**Comment by roadrash2108** [comment]
New version:
![Screenshot 2020-10-10 193832](https://user-images.githubusercontent.com/26000761/95661507-3296a000-0b30-11eb-9d82-e10afa15bee6.png)

Does that fit, @Eriktesla ?

**Comment by roadrash2108** [comment]
@adriankumpf I'm sorry for my lack of knowledge, but can you give me some hints how to deliver this? (just create a new file in the repo with the JSON-model that I copy/paste out of my Grafana? If yes, I would suggest to deliver such "special reports" in a separate folder - simply create it or does it have to be created via Grafana?) Many thanks for guidance!

**Comment by Eriktesla** [comment]
@roadrash2108 , super, thanks a lot!

**Comment by cwanja** [comment]
Will this end up showing up for everyone as "Dutch tax" dashboard if using the Docker image?

**Comment by adriankumpf** [comment]
It'll show up in a separate folder:

<img width="444" alt="Screenshot 2020-10-13 at 16 55 57" src="https://user-images.githubusercontent.com/8999358/95878042-1172c100-0d75-11eb-8703-ad3da8d03edb.png">

**Comment by roadrash2108** [comment]
@Eriktesla can you please clarify if it is required to have the full address for start/end or is it suitable to have the name of the geofence/location in the report? many thanks!

**Comment by cwanja** [comment]
> @Eriktesla can you please clarify if it is required to have the full address for start/end or is it suitable to have the name of the geofence/location in the report? many thanks!

The geofence _should_ work. It is just a wrapper around the physical address. Now for the tax authorities purposes, maybe they need the address as opposed to ‘Grandma’s house’. Maybe there is a way the dashboard can ignore geofences.

**Comment by Eriktesla** [comment]
> @Eriktesla can you please clarify if it is required to have the full address for start/end or is it suitable to have the name of the geofence/location in the report? many thanks!

The full address for start/end is needed. Geofence addresses like home, work or mother's house are unfortunately not allowed be the Tax authority.
