### ISSUE TITLE
What is the purpose of new bar graphs in efficiency dashboard?

### ISSUE THREAD

**Issue by petariga** [adriankumpf/teslamate#992]
**Describe the bug**
I noticed new orange/yellow/green bar graphs in the efficiency dashboard after updating TM to 1.20. They look nice, however they are all the same regardless of the corresponding efficiency percentage. Or I just might not get their real purpose...

**Expected behavior**
Make the bar graphs in the efficiency dashboard in a way that they really reflect the efficiency percentages (their size changes according to the percentage).

**How to reproduce it (as minimally and precisely as possible)**:
See the attached screenshot with an example.

**Relevant entries from the logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/64809507/95654116-eaf72080-0afd-11eb-93a9-4c25997e7498.png)

**Data**

**Environment**

- TeslaMate version: 1.20.0
- Type of installation: Docker
- OS TeslaMate is installed on: Linux
- User OS & Browser: Firefox & Safari
- Others:

**Comment by DrMichael** [comment]
That is because your Efficiencies are all over 100%. Mine looks reasonable:
![image](https://user-images.githubusercontent.com/8087682/95654959-3c0a1300-0b04-11eb-987c-e3897e093d5b.png)

**Comment by petariga** [comment]
Does that mean that nobody has counted on reaching efficiency above 100%?

**Comment by DrMichael** [comment]
Probably... :-)

**Comment by adriankumpf** [comment]
@petariga you can add a min/max override property and see what works best. We should probably set a fixed max value greater than 1.

**Comment by petariga** [comment]
Well, probably the most accurate solution would to get the highest percentage from the listed efficiency percentages and count the rest according to this value. And keep the orange bar for all values under approx. 90% and green above 90%.

Setting **Max** between **1.1** and **1.2** might work as a hot fix for the sizes of the bars in most cases too. However, the gradient colour of the bars does not match then. I would expect to have them orange up to let's say 90% and then green all the way to the maximal value, however with Max between 1.1 and 1.2 each bar has a different colour shift.
